Repository Oneflow-Inc/oneflow, pull requests merged in 2020-09, with the labels that each got.

#3515 add masked fill op
  oneflow/core/kernel/broadcast_to_compatible_with_kernel.cpp
  oneflow/core/kernel/constant_like_kernel.cpp
  oneflow/core/kernel/util/cuda_arithemetic_interface.cu
  oneflow/core/kernel/util/cuda_arithemetic_interface.h
  oneflow/python/ops/array_ops.py
  oneflow/python/test/ops/test_masked_fill.py
  oneflow/user/kernels/reduce_like_kernels.cpp
  oneflow/user/kernels/scalar_by_tensor_kernel.cpp
  oneflow/user/kernels/where_kernel.cpp
  oneflow/user/kernels/where_kernel_util.cu
Labels: automerge

#3511 Dev add op tril
  oneflow/python/ops/math_ops.py
  oneflow/python/test/ops/test_tril.py
  oneflow/user/kernels/tril_kernel.cpp
  oneflow/user/kernels/tril_kernel.cu
  oneflow/user/ops/tril_op.cpp
Labels: automerge

#3527 Migrate L1L2RegularizeGradientOp to UserOp Framework
  oneflow/core/job_rewriter/autograd.cpp
  oneflow/core/kernel/l1_l2_regularize_gradient_kernel.cpp
  oneflow/core/operator/l1_l2_regularize_gradient_op.cpp
  oneflow/core/operator/op_conf.proto
  oneflow/user/kernels/l1_l2_regularize_gradient_kernel.cpp
  oneflow/user/kernels/l1_l2_regularize_gradient_kernel_util.cpp
  oneflow/user/kernels/l1_l2_regularize_gradient_kernel_util.cu
  oneflow/user/kernels/l1_l2_regularize_gradient_kernel_util.h
  oneflow/user/ops/l1_l2_regularize_gradient_op.cpp
Labels: automerge

#3535 Use InferOutBlobDescsIf instead of InferBlobDescsIf in InferOpNodeLogicalBlobDesc
  oneflow/core/graph/op_graph.cpp
Labels: automerge

#3537 Add ctrl_in_op_name only when unreachable
  oneflow/core/job_rewriter/job_completer.cpp
Labels: automerge

#3536 Remove cuDNN fields from OperatorConf
  oneflow/core/kernel/kernel.h
  oneflow/core/operator/op_conf.proto
  oneflow/core/operator/operator.cpp
  oneflow/core/operator/operator.h
Labels: automerge

#3539 Avoid using local memory in CropMirrorNormalizeGpuKernel
  oneflow/user/kernels/image_preprocess_kernels.cu
Labels: automerge

#3531 upgrade XRT XLA to TF 2.3.0
  .gitignore
  cmake/third_party.cmake
  cmake/third_party/eigen.cmake
  cmake/third_party/protobuf.cmake
  cmake/third_party/tensorflow.cmake
  docker/package/manylinux/Dockerfile
  docker/package/manylinux/build_wheel.sh
  docker/package/manylinux/build_xla.sh
  docker/package/manylinux/launch.sh
  docker/package/manylinux/make_release.sh
  oneflow/python/test/ops/test_optimizers.py
  oneflow/python/version.py
  oneflow/xrt/xla/xla_allocator.cpp
  oneflow/xrt/xla/xla_allocator.h
  oneflow/xrt/xla/xla_graph_compiler.cpp
Labels: automerge

#3548 Fix BERT xla crash
  cmake/third_party/cocoapi.cmake
  docker/package/manylinux/build_wheel.sh
  oneflow/user/ops/bias_add_op.cpp
  oneflow/xrt/xla/ops/layer_norm_op.cpp
Labels: automerge

#3485 split BlobObject and EagerBlobObject
  oneflow/core/eager/blob_object.cpp
  oneflow/core/eager/blob_object.h
  oneflow/core/eager/eager_blob_object.cpp
  oneflow/core/eager/eager_blob_object.h
  oneflow/core/eager/lazy_ref_blob_object.h
  oneflow/core/eager/opkernel_instruction_type.cpp
Labels: automerge

#3559 move fmt to github hosted
  .github/actions/fmt/Dockerfile
  .github/actions/fmt/action.yml
  .github/actions/fmt/entrypoint.sh
  .github/workflows/test.yml
  ci/build/make.sh
  docker/ci/fmt/Dockerfile
  docker/ci/fmt/build.sh
  docker/package/manylinux/build_wheel.sh
Labels: automerge

#3560 fix masked_fill op doc
  oneflow/python/ops/array_ops.py
Labels: automerge

#3563 Fix NcclCollectiveBoxing builder_name
  oneflow/core/graph/boxing/collective_boxing_sub_task_graph_builder.cpp
Labels: automerge

#3495 onnx update
  oneflow/python/onnx/flow2onnx.py
  oneflow/python/onnx/graph.py
  oneflow/python/onnx/onnx_opset/array.py
  oneflow/python/onnx/onnx_opset/common.py
  oneflow/python/onnx/onnx_opset/math.py
  oneflow/python/onnx/onnx_opset/nn.py
  oneflow/python/onnx/onnx_opset/reduce.py
  oneflow/python/onnx/optimizer/back_to_back_optimizer.py
  oneflow/python/onnx/optimizer/const_fold_optimizer.py
  oneflow/python/onnx/optimizer/identity_optimizer.py
  oneflow/python/onnx/optimizer/loop_optimizer.py
  oneflow/python/onnx/optimizer/merge_duplicated_nodes_optimizer.py
  oneflow/python/onnx/optimizer/transpose_optimizer.py
  oneflow/python/onnx/schemas.py
  oneflow/python/onnx/util.py
  oneflow/python/test/onnx/models/test_alexnet.py
  oneflow/python/test/onnx/models/test_mobilenet_v2.py
  oneflow/python/test/onnx/models/test_resnet50.py
  oneflow/python/test/onnx/nodes/test_activations.py
  oneflow/python/test/onnx/nodes/test_add_n.py
  oneflow/python/test/onnx/nodes/test_batch_normalization.py
  oneflow/python/test/onnx/nodes/test_bias_add.py
  oneflow/python/test/onnx/nodes/test_concat.py
  oneflow/python/test/onnx/nodes/test_conv.py
  oneflow/python/test/onnx/nodes/test_gather_nd.py
  oneflow/python/test/onnx/nodes/test_large_array.py
  oneflow/python/test/onnx/nodes/test_math.py
  oneflow/python/test/onnx/nodes/test_matmul.py
  oneflow/python/test/onnx/nodes/test_pad.py
  oneflow/python/test/onnx/nodes/test_pooling.py
  oneflow/python/test/onnx/nodes/test_reduction.py
  oneflow/python/test/onnx/nodes/test_reshape.py
  oneflow/python/test/onnx/nodes/test_softmax.py
  oneflow/python/test/onnx/nodes/test_transpose.py
  oneflow/python/test/onnx/util.py
Labels: automerge

#3567 Add nccl_fusion_max_ops
  oneflow/core/job/collective_boxing_executor.cpp
  oneflow/core/job/resource.proto
  oneflow/python/framework/config_util.py
Labels: automerge

#3569 Dropout support add_to_output
  oneflow/core/job_rewriter/fuse_add_to_output_pass.cpp
  oneflow/user/kernels/dropout_kernel.cpp
  oneflow/user/kernels/dropout_kernel.cu
  oneflow/user/ops/dropout_op.cpp
Labels: automerge

#3562 Split call_op_kernel instruction args into const_input/mutable_input/output
  oneflow/core/eager/opkernel_instruction.msg.h
  oneflow/core/eager/opkernel_instruction_type.cpp
  oneflow/core/eager/opkernel_instruction_type_test.cpp
  oneflow/python/eager/vm_util.py
Labels: automerge

#3566 Fix TopoForEachNode in GenCollectiveBoxingPlan
  oneflow/core/job/oneflow.cpp
Labels: automerge

#3551 Upgrade grpc
  cmake/third_party.cmake
  cmake/third_party/absl.cmake
  cmake/third_party/cares.cmake
  cmake/third_party/grpc.cmake
  cmake/third_party/header_index/grpc_headers.txt
  cmake/third_party/openssl.cmake
  oneflow/core/control/ctrl_server.cpp
  oneflow/core/control/ctrl_service.cpp
  oneflow/core/control/ctrl_service.h
  oneflow/core/job/env.proto
  oneflow/core/job/env_desc.h
  oneflow/python/benchmarks/cnn_benchmark/of_cnn_benchmarks.py
  oneflow/python/benchmarks/cnn_benchmark/of_cnn_infer_benchmarks.py
  oneflow/python/framework/env_util.py
  oneflow/python/test/models/vgg16.py
Labels: automerge

#3573 LayerNormGpuKernel use fused InstanceScaleCenter
  oneflow/user/kernels/layer_norm_gpu_kernel.cu
Labels: automerge

#3577 Optimize nvcc gencode flag
  CMakeLists.txt
Labels: automerge

#3579 fix upsample
  oneflow/core/kernel/kernel_util.cu
  oneflow/user/kernels/upsample_kernel.cu
Labels: automerge

#3578 Fix gpu_atomic_max double overload use fmaxf
  oneflow/core/kernel/kernel_util.cu
Labels: automerge

#3581 Dev matmul add to output
  oneflow/core/job_rewriter/fuse_add_to_output_pass.cpp
  oneflow/python/test/ops/test_matmul.py
  oneflow/python/test/xrt/test_batch_norm_add.py
  oneflow/python/test/xrt/test_matmul_add.py
  oneflow/user/kernels/matmul_kernels.cpp
  oneflow/user/ops/matmul_op.cpp
  oneflow/xrt/tensorrt/ops/batch_norm_op.cpp
  oneflow/xrt/tensorrt/ops/matmul_op.cpp
  oneflow/xrt/xla/ops/batch_matmul_op.cpp
  oneflow/xrt/xla/ops/matmul_op.cpp
Labels: automerge

#3592 Auto upload tar to aliyun oss
  .github/workflows/test.yml
  tools/package_mirror.py
Labels: automerge

#3582 Tensor::dptr support half
  oneflow/core/common/data_type.h
  oneflow/core/framework/tensor.cpp
  oneflow/core/framework/tensor.h
  oneflow/python/test/ops/test_dropout.py
  oneflow/user/kernels/dropout_kernel.cu
Labels: automerge

#3589 [bugfix] GRPC: control server CompletionQueue shutdown.
  oneflow/core/control/ctrl_server.cpp
  oneflow/core/control/ctrl_test.cpp
Labels: automerge, bottleneck, bug

#3608 Add OpRegistry::SetAreaId
  oneflow/core/framework/user_op_registry.cpp
  oneflow/core/framework/user_op_registry.h
  oneflow/core/graph/logical_node.cpp
Labels: automerge

#3609 fix broadcast_to_compatible_with grad bug
  oneflow/core/job_rewriter/broadcast_to_compatible_with_grad.cpp
  oneflow/python/test/ops/test_broadcast_to_compatible_with.py
Labels: automerge

#3615 fix bug: oneflow cpu-only lib flags
  cmake/oneflow.cmake
Labels: bug

#3549 Transport
  cmake/oneflow.cmake
  oneflow/core/comm_network/comm_network.cpp
  oneflow/core/comm_network/comm_network.h
  oneflow/core/comm_network/epoll/epoll_comm_network.cpp
  oneflow/core/comm_network/epoll/epoll_comm_network.h
  oneflow/core/comm_network/epoll/socket_message.h
  oneflow/core/comm_network/epoll/socket_read_helper.cpp
  oneflow/core/comm_network/epoll/socket_write_helper.cpp
  oneflow/core/comm_network/ibverbs/ibverbs_comm_network.h
  oneflow/core/job/runtime.cpp
  oneflow/core/transport/transport.cpp
  oneflow/core/transport/transport.h
  oneflow/core/transport/transport_message.h
  oneflow/core/transport/transport_test_main.cpp
Labels: automerge, bottleneck, feature

#3623 update lib name in link flags
  oneflow/python/framework/sysconfig.py
Labels: automerge

#3624 [Bug fix] Release global variables
  oneflow/python/oneflow_internal_helper.h
Labels: automerge

#3625 Dev oneflow pybind api
  cmake/oneflow.cmake
  oneflow/api/python/init.cpp
  oneflow/api/python/of_api_registry.cpp
  oneflow/api/python/of_api_registry.h
Labels: automerge
