Repository Oneflow-Inc/oneflow, pull requests merged in 2020-10, with the labels that each got.

#3634 change link order to fix the cpu+openblas build
  cmake/third_party.cmake
Labels: automerge

#3637 Bugfix split config proto and session job set
  oneflow/core/comm_network/epoll/epoll_comm_network.cpp
  oneflow/core/comm_network/ibverbs/ibverbs_comm_network.cpp
  oneflow/core/control/ctrl_client.h
  oneflow/core/control/ctrl_test.cpp
  oneflow/core/job/cluster_instruction.cpp
  oneflow/core/job/job.proto
  oneflow/core/job/job_build_and_infer_ctx.cpp
  oneflow/core/job/job_build_and_infer_ctx.h
  oneflow/core/job/job_build_and_infer_ctx_mgr.cpp
  oneflow/core/job/job_build_and_infer_ctx_mgr.h
  oneflow/core/job/oneflow.cpp
  oneflow/core/job/runtime.cpp
  oneflow/core/job/session_global_objects_scope.cpp
  oneflow/core/job_rewriter/add_lbi_diff_watcher.cpp
  oneflow/core/transport/transport_test_main.cpp
  oneflow/python/framework/c_api_util.py
  oneflow/python/framework/compiler.py
  oneflow/python/framework/session_util.py
  oneflow/python/job_build_and_infer_helper.h
  oneflow/python/oneflow_internal.h
  oneflow/python/oneflow_internal_helper.h
Labels: automerge

#3643 MaskAndScaleHalf2
  oneflow/user/kernels/dropout_kernel.cu
Labels: automerge

#3644 Fused ImageDecoderRandomCropResize
  cmake/third_party.cmake
  oneflow/core/actor/naive_actor.cpp
  oneflow/core/device/cuda_util.cpp
  oneflow/core/device/cuda_util.h
  oneflow/core/graph/decode_h2d_compute_task_node.cpp
  oneflow/core/graph/decode_h2d_compute_task_node.h
  oneflow/core/graph/logical_node.cpp
  oneflow/core/graph/logical_node.h
  oneflow/core/graph/task_graph.cpp
  oneflow/core/graph/task_graph.h
  oneflow/core/job/id_manager.cpp
  oneflow/core/job/id_manager.h
  oneflow/core/job/scope.h
  oneflow/core/job/task.proto
  oneflow/core/kernel/image_decoder_random_crop_resize_kernel.cpp
  oneflow/core/kernel/kernel.proto
  oneflow/core/operator/image_decoder_random_crop_resize_op.cpp
  oneflow/core/operator/op_conf.proto
  oneflow/python/ops/data_ops.py
  oneflow/python/ops/user_data_ops.py
  oneflow/user/kernels/ofrecord_decoder_kernels.cpp
  oneflow/user/ops/ofrecord_decoder_ops.cpp
Labels: feature

#3648 Optimize some default values
  oneflow/core/job/resource.proto
  oneflow/core/operator/op_conf.proto
Labels: automerge

#3649 Add CudnnConvAlgoCache
  oneflow/core/device/cudnn_conv_util.cpp
  oneflow/core/device/cudnn_conv_util.h
  oneflow/core/job/env_global_objects_scope.cpp
Labels: automerge

#3652 Refactor scope
  oneflow/python/eager/interpreter_callback.py
  oneflow/python/eager/op_executor.py
  oneflow/python/eager/vm_util.py
  oneflow/python/experimental/name_scope.py
  oneflow/python/framework/compiler.py
  oneflow/python/framework/distribute_context.py
  oneflow/python/framework/env_util.py
  oneflow/python/framework/placement_context.py
  oneflow/python/framework/placement_util.py
  oneflow/python/framework/scope_symbol.py
  oneflow/python/framework/scope_util.py
  oneflow/python/framework/session_util.py
  oneflow/python/ops/__init__.py
Labels: automerge

#3597 Dev integrate cfg
  .gitignore
  cmake/cfg.cmake
  cmake/oneflow.cmake
  dev-requirements.txt
  oneflow/api/python/init.cpp
  tools/cfg/generate_cfg_head_dir_and_convert_src.py
  tools/cfg/include/oneflow/cfg/map_field.h
  tools/cfg/include/oneflow/cfg/pybind_module_registry.h
  tools/cfg/include/oneflow/cfg/repeated_field.h
  tools/cfg/include/oneflow/cfg/shared_pair_iterator.h
  tools/cfg/pybind_module_registry.cpp
  tools/cfg/template/template.cfg.cpp
  tools/cfg/template/template.cfg.h
  tools/cfg/template/template.pybind.cpp
  tools/cfg/template_convert.py
  tools/cfg/util/__init__.py
  tools/cfg/util/proto_reflect_util.py
Labels: automerge

#3655 support reflecting cfg message
  cmake/cfg.cmake
  oneflow/core/common/cfg_reflection_test.cpp
  oneflow/core/common/cfg_reflection_test.proto
  oneflow/core/common/protobuf.cpp
  oneflow/core/common/protobuf.h
  oneflow/core/kernel/kernel.h
  oneflow/user/kernels/image_preprocess_kernels.cu
  tools/cfg/include/oneflow/cfg/message.h
  tools/cfg/template/template.cfg.h
  tools/cfg/util/proto_reflect_util.py
Labels: automerge

#3658 Add AmpWhiteIdentityOp
  oneflow/core/job_rewriter/auto_mixed_precision.cpp
  oneflow/core/job_rewriter/auto_mixed_precision_lists.cpp
  oneflow/core/kernel/gather_kernel_util.cu
  oneflow/core/kernel/gather_kernel_util.h
  oneflow/core/kernel/kernel_util.cu
  oneflow/core/kernel/unsorted_segment_sum_kernel_util.cu
  oneflow/core/kernel/unsorted_segment_sum_kernel_util.h
  oneflow/python/ops/array_ops.py
  oneflow/user/kernels/amp_white_identity_kernel.cpp
  oneflow/user/ops/amp_white_identity_op.cpp
Labels: automerge

#3640 fix bug about pad value
  oneflow/python/ops/pad.py
  oneflow/python/test/ops/test_pad.py
Labels: automerge

#3660 AutoRegistrationFactory add key type
  oneflow/core/actor/actor.cpp
  oneflow/core/actor/actor.h
  oneflow/core/common/auto_registration_factory.h
  oneflow/core/device/memory_copier.cpp
  oneflow/core/device/memory_copier.h
  oneflow/core/framework/user_op_registry.cpp
  oneflow/core/framework/user_op_registry.h
  oneflow/core/graph/boxing/to_interface_sub_task_graph_builder.cpp
  oneflow/core/graph/logical_node.cpp
  oneflow/core/graph/logical_node.h
  oneflow/core/graph/normal_forward_compute_task_node.cpp
  oneflow/core/graph/task_graph.cpp
  oneflow/core/graph/task_node.h
  oneflow/core/job/job_desc.cpp
  oneflow/core/job/thrd_id_generator.cpp
  oneflow/core/job_rewriter/autograd.cpp
  oneflow/core/job_rewriter/autograd.h
  oneflow/core/job_rewriter/autotick.cpp
  oneflow/core/job_rewriter/autotick.h
  oneflow/core/job_rewriter/group_boxing_by_dst_parallel.cpp
  oneflow/core/job_rewriter/optimizer.cpp
  oneflow/core/job_rewriter/optimizer.h
  oneflow/core/kernel/kernel.cpp
  oneflow/core/kernel/kernel.h
  oneflow/core/operator/lars_model_update_op.cpp
  oneflow/core/operator/normal_model_update_op.cpp
  oneflow/core/operator/operator.cpp
  oneflow/core/operator/operator.h
  oneflow/core/operator/rmsprop_model_update_op.cpp
  oneflow/python/oneflow_internal.h
  oneflow/python/oneflow_internal_helper.h
  oneflow/user/ops/model_update_ops.cpp
Labels: automerge

#3657 Dev cfg reflection
  oneflow/core/common/cfg.cpp
  oneflow/core/common/cfg.h
  oneflow/core/common/cfg_reflection_test.cpp
  oneflow/core/common/cfg_reflection_test.proto
  oneflow/core/common/protobuf.cpp
  oneflow/core/common/protobuf.h
  oneflow/core/common/str_util.cpp
  oneflow/core/common/str_util.h
  oneflow/xrt/utility/message_attr.h
  tools/cfg/include/oneflow/cfg/map_field.h
  tools/cfg/include/oneflow/cfg/message.h
  tools/cfg/include/oneflow/cfg/repeated_field.h
  tools/cfg/template/template.cfg.h
Labels: automerge

#3663 fix bug in tensorbuffer kernel
  oneflow/user/kernels/tensor_buffer_kernels.cpp
Labels: automerge, bug

#3618 change paltform_xxx_macro_name
  oneflow/core/comm_network/epoll/epoll_comm_network.cpp
  oneflow/core/comm_network/epoll/epoll_comm_network.h
  oneflow/core/comm_network/epoll/io_event_poller.cpp
  oneflow/core/comm_network/epoll/io_event_poller.h
  oneflow/core/comm_network/epoll/socket_helper.cpp
  oneflow/core/comm_network/epoll/socket_helper.h
  oneflow/core/comm_network/epoll/socket_memory_desc.h
  oneflow/core/comm_network/epoll/socket_message.h
  oneflow/core/comm_network/epoll/socket_read_helper.cpp
  oneflow/core/comm_network/epoll/socket_read_helper.h
  oneflow/core/comm_network/epoll/socket_write_helper.cpp
  oneflow/core/comm_network/epoll/socket_write_helper.h
  oneflow/core/comm_network/ibverbs/ibverbs_comm_network.cpp
  oneflow/core/comm_network/ibverbs/ibverbs_comm_network.h
  oneflow/core/comm_network/ibverbs/ibverbs_memory_desc.cpp
  oneflow/core/comm_network/ibverbs/ibverbs_memory_desc.h
  oneflow/core/comm_network/ibverbs/ibverbs_qp.cpp
  oneflow/core/comm_network/ibverbs/ibverbs_qp.h
  oneflow/core/common/platform.h
  oneflow/core/common/util.cpp
  oneflow/core/control/ctrl_test.cpp
  oneflow/core/device/cuda_util.cpp
  oneflow/core/job/runtime.cpp
  oneflow/core/persistence/file_system.cpp
  oneflow/core/persistence/file_system_test.cpp
  oneflow/core/persistence/hadoop/hadoop_file_system.cpp
  oneflow/core/persistence/posix/posix_file_system.cpp
  oneflow/core/persistence/posix/posix_file_system.h
  oneflow/core/transport/transport_message.h
Labels: automerge

#3664 ci add label check workflow
  .github/workflows/pr.yml
Labels: ci, enhancement

#3669 Add cuda_pseudo_half.h
  oneflow/core/device/cuda_pseudo_half.h
  oneflow/core/device/cuda_util.h
  oneflow/user/kernels/dropout_kernel.cu
Labels: automerge, feature, op

#3620 LAMB support
  docker/ci/test/requirements.txt
  oneflow/core/graph/logical_node.cpp
  oneflow/core/job_rewriter/lamb_optm.cpp
  oneflow/core/operator/op_conf.proto
  oneflow/python/ops/optimizer.py
  oneflow/python/test/ops/test_lamb.py
  oneflow/python/test/ops/test_optimizers.py
  oneflow/user/kernels/model_update_kernel_util.cpp
  oneflow/user/kernels/model_update_kernel_util.cu
  oneflow/user/kernels/model_update_kernel_util.h
  oneflow/user/kernels/model_update_kernels.cpp
  oneflow/user/ops/model_update_ops.cpp
Labels: automerge, feature, op

#3676 fix missing symbol when load so
  cmake/oneflow.cmake
Labels: bug, tooling

#3544 slice_update op
  oneflow/python/ops/array_ops.py
  oneflow/python/test/ops/test_slice_v2.py
  oneflow/user/kernels/slice_kernel.cpp
  oneflow/user/ops/slice_op.cpp
Labels: automerge, enhancement, op

#3671 add requirements.txt for api-docs
  .github/workflows/release.yml
  docs/requirements.txt
Labels: ci, documentation, enhancement

#3587 Add api docs zzk
  oneflow/python/ops/array_ops.py
  oneflow/python/ops/constant_op.py
  oneflow/python/ops/optimizer.py
  oneflow/python/ops/random_ops.py
  oneflow/python/ops/tensor_buffer_ops.py
  oneflow/python/ops/tensor_list_ops.py
  oneflow/python/ops/user_data_ops.py
  oneflow/python/ops/watch.py
Labels: automerge, documentation, tooling

#3675 fix softmax condition
  oneflow/user/kernels/softmax_kernel.cu
Labels: automerge, bug, op

#3677 change url link of api docs
  README.md
Labels: documentation, enhancement, tooling

#3665 Add broadcast like backward
  oneflow/python/test/ops/test_broadcast_like.py
  oneflow/user/ops/broadcast_like_op.cpp
Labels: automerge, feature, op

#3679 Run xla and pure cpu only when cuda test succeeds
  .github/workflows/test.yml
Labels: ci, enhancement

#3670 Parallel run op cases
  ci/test/1node_op_test.sh
  ci/test/parallel_run.py
Labels: automerge, ci, feature, test

#3681 Fix eager mode bug
  oneflow/core/common/data_type_converter.h
  oneflow/core/common/gdb.cpp
  oneflow/core/common/gdb.h
  oneflow/core/control/ctrl_util.cpp
  oneflow/core/job/job_build_and_infer_ctx_mgr.cpp
  oneflow/core/job/job_build_and_infer_ctx_mgr.h
  oneflow/core/kernel/image_decoder_random_crop_resize_kernel.cpp
  oneflow/core/kernel/kernel.cpp
  oneflow/python/test/ops/test_TestMultiOutputOrder.py
Labels: bug, eager

#3682 import tensorflow in RunTensorFlowOp
  oneflow/python/test/ops/test_util.py
Labels: automerge, enhancement, test

#3666 Fix image resize test
  oneflow/python/test/ops/image_test_util.py
  oneflow/python/test/ops/test_image_resize.py
  oneflow/python/test/ops/test_image_target_resize.py
Labels: automerge, bug, test

#3683 Run check_license_and_format in every branch
  .github/workflows/test.yml
Labels: ci, enhancement

#3687 fix memcopy
  oneflow/core/device/memory_copier.cpp
Labels: automerge, bug, system

#3689 test use uuid log dir
  .dockerignore
  ci/test/parallel_run.py
  oneflow/python/framework/unittest.py
  oneflow/python/test/README.md
Labels: bug, ci

#3694 fix readme
  README.md
Labels: build, documentation

#3690 Fix image_test_util
  oneflow/python/test/ops/image_test_util.py
Labels: automerge, bug, test

#3692 Fix fuse scalar mul by tensor sbp
  oneflow/user/ops/model_update_ops.cpp
Labels: automerge, bug, op

#3699 Add UserOp::InferSbpSignature
  oneflow/core/framework/sbp_context.h
  oneflow/core/framework/user_op_registry.cpp
  oneflow/core/framework/user_op_registry.h
  oneflow/core/graph/logical_node.cpp
  oneflow/core/job/job_build_and_infer_ctx.cpp
  oneflow/core/job_rewriter/tie_up_chain_headers.cpp
  oneflow/core/job_rewriter/tuple_identity_grad.cpp
  oneflow/core/kernel/tuple_identity_kernel.cpp
  oneflow/core/kernel/tuple_identity_kernel.h
  oneflow/core/operator/op_conf.proto
  oneflow/core/operator/tuple_identity_op.cpp
  oneflow/core/operator/tuple_identity_op.h
  oneflow/core/operator/user_op.cpp
  oneflow/core/operator/user_op.h
  oneflow/python/ops/array_ops.py
  oneflow/python/test/ops/test_identity_n.py
  oneflow/user/kernels/tuple_identity_kernel.cpp
  oneflow/user/ops/tuple_identity_op.cpp
Labels: automerge, enhancement, op

#3695 Dev add api rst
  docs/source/index.rst
  docs/source/typing.rst
Labels: api, automerge, documentation, python

#3685 Add attribute "batch_axis_non_change" to `oneflow.transpose`
  oneflow/python/ops/array_ops.py
  oneflow/python/test/ops/test_transpose.py
  oneflow/user/ops/transpose_ops.cpp
Labels: WIP, bug, system

#3680 Add api docs zzk
  oneflow/python/framework/placement_util.py
  oneflow/python/ops/array_ops.py
  oneflow/python/ops/math_ops.py
  oneflow/python/ops/nn_ops.py
  oneflow/python/ops/tensor_buffer_ops.py
  oneflow/python/ops/tensor_list_ops.py
Labels: automerge, documentation, tooling

#3538 Add Nccl All2All
  oneflow/core/actor/naive_actor.cpp
  oneflow/core/graph/boxing/collective_boxing.proto
  oneflow/core/graph/boxing/collective_boxing_sub_task_graph_builder.cpp
  oneflow/core/graph/boxing/collective_boxing_util.cpp
  oneflow/core/graph/boxing_s2s_all2all_pack_compute_task_node.cpp
  oneflow/core/graph/boxing_s2s_all2all_pack_compute_task_node.h
  oneflow/core/graph/boxing_s2s_all2all_unpack_compute_task_node.cpp
  oneflow/core/graph/boxing_s2s_all2all_unpack_compute_task_node.h
  oneflow/core/job/collective_boxing_executor.cpp
  oneflow/core/job/resource.proto
  oneflow/core/job/task.proto
  oneflow/core/kernel/boxing_s2s_all2all_pack_kernel.cpp
  oneflow/core/kernel/boxing_s2s_all2all_unpack_kernel.cpp
  oneflow/core/operator/boxing_s2s_all2all_pack_op.cpp
  oneflow/core/operator/boxing_s2s_all2all_unpack_op.cpp
  oneflow/core/operator/op_conf.proto
  oneflow/python/framework/config_util.py
  oneflow/python/test/ops/test_boxing_v2.py
Labels: automerge, feature, system

#3693 Remove CheckNoCycle in chain graph
  oneflow/core/graph/chain_graph.cpp
  oneflow/core/graph/chain_graph.h
  oneflow/core/graph/task_graph.cpp
  oneflow/core/job/intra_job_mem_sharing_util.cpp
  oneflow/python/test/ops/test_where.py
Labels: automerge, bug, system

#3701 Use universal start global device id for all streams
  oneflow/core/vm/control_stream_type.cpp
  oneflow/core/vm/cpu_stream_type.cpp
  oneflow/core/vm/cuda_copy_d2h_stream_type.cpp
  oneflow/core/vm/cuda_copy_h2d_stream_type.cpp
  oneflow/core/vm/cuda_stream_type.cpp
  oneflow/core/vm/device_helper_stream_type.cpp
  oneflow/core/vm/host_stream_type.cpp
  oneflow/core/vm/nop_stream_type.cpp
  oneflow/core/vm/object_instruction_type.cpp
  oneflow/core/vm/stream.cpp
  oneflow/core/vm/stream.msg.h
  oneflow/core/vm/stream_desc.msg.h
  oneflow/core/vm/transport_stream_type.cpp
  oneflow/core/vm/virtual_machine.cpp
  oneflow/core/vm/virtual_machine.msg.h
  oneflow/core/vm/vm_resource_desc.cpp
  oneflow/core/vm/vm_resource_desc.msg.h
Labels: automerge, bug, eager

#3700 Use cudaMemcpyDefault
  oneflow/core/actor/accumulate_compute_actor.cpp
  oneflow/core/kernel/kernel_util.cpp
  oneflow/core/kernel/kernel_util.h
  oneflow/core/kernel/model_io_v2_kernel.cpp
  oneflow/core/kernel/new_kernel_util.cpp
  oneflow/core/kernel/new_kernel_util.cu
  oneflow/core/kernel/new_kernel_util.h
  oneflow/user/kernels/radix_sort_top_k_kernel.cu
Labels: automerge, enhancement, system

#3647 logical slice_assign and slice op
  oneflow/python/ops/array_ops.py
  oneflow/python/test/ops/test_logical_slice.py
  oneflow/python/test/ops/test_logical_slice_assign.py
  oneflow/user/kernels/slice_kernel.cpp
  oneflow/user/ops/slice_assign_op.cpp
  oneflow/user/ops/slice_op.cpp
Labels: feature, op

#3702 Dev switch instruction to cfg instruction
  cmake/cfg.cmake
  cmake/oneflow.cmake
  tools/cfg/include/oneflow/cfg/message.h
  tools/cfg/template/template.cfg.cpp
  tools/cfg/template/template.cfg.h
  tools/cfg/template/template.pybind.cpp
  tools/cfg/util/proto_reflect_util.py
Labels: automerge, bug, cfg, tooling

#3707 Add Repeat/Acc user op
  oneflow/core/actor/acc_compute_actor.cpp
  oneflow/core/actor/acc_compute_actor.h
  oneflow/core/actor/repeat_compute_actor.cpp
  oneflow/core/actor/repeat_forward_compute_actor.h
  oneflow/core/framework/framework.h
  oneflow/core/framework/infer_output_blob_time_shape_fn_context.h
  oneflow/core/framework/user_op_registry.cpp
  oneflow/core/framework/user_op_registry.h
  oneflow/core/graph/acc_compute_task_node.cpp
  oneflow/core/graph/acc_compute_task_node.h
  oneflow/core/graph/logical_node.cpp
  oneflow/core/graph/logical_node.h
  oneflow/core/graph/repeat_compute_task_node.cpp
  oneflow/core/graph/repeat_forward_compute_task_node.cpp
  oneflow/core/graph/repeat_forward_compute_task_node.h
  oneflow/core/job/task.proto
  oneflow/core/job_rewriter/acc_grad.cpp
  oneflow/core/job_rewriter/repeat_grad.cpp
  oneflow/core/kernel/accumulate_kernel.cpp
  oneflow/core/kernel/repeat_kernel.cpp
  oneflow/core/kernel/repeat_kernel.h
  oneflow/core/operator/acc_op.cpp
  oneflow/core/operator/acc_op.h
  oneflow/core/operator/op_conf.proto
  oneflow/core/operator/repeat_op.cpp
  oneflow/core/operator/repeat_op.h
  oneflow/core/operator/user_op.cpp
  oneflow/core/operator/user_op.h
  oneflow/python/framework/ops.py
  oneflow/user/kernels/acc_kernel.cpp
  oneflow/user/kernels/repeat_kernel.cpp
  oneflow/user/ops/acc_op.cpp
  oneflow/user/ops/repeat_op.cpp
Labels: automerge, feature, op, system

#3708 remove proton not related to Instruction
  cmake/cfg.cmake
Labels: automerge, bug, tooling

#3703 fix unpacked mirrored blob object shape
  oneflow/python/eager/vm_util.py
  oneflow/python/framework/op_arg_util.py
Labels: automerge, bug, eager

#3722 fix(OutputOp): fix bug in OutputOP when change S to B
  oneflow/core/operator/output_op.cpp
  oneflow/core/operator/output_op.h
Labels: bug

#3709 detect cxx11 abi availibility in cmake
  CMakeLists.txt
  cmake/util.cmake
Labels: automerge, bug, build

#3713 Log WARNING to stderr
  oneflow/core/job/env_global_objects_scope.cpp
Labels: automerge, enhancement, system

#3724 fix make -j in grpc and openssl
  cmake/third_party/grpc.cmake
  cmake/third_party/openssl.cmake
Labels: automerge, bug, build

#3717 Dev compare cfg file
  cmake/cfg.cmake
  cmake/oneflow.cmake
  tools/cfg/copy_proto_python_file.py
  tools/cfg/generate_cfg_head_dir_and_convert_src.py
  tools/cfg/template/template.cfg.cpp
  tools/cfg/template/template.cfg.pybind.cpp
  tools/cfg/template_convert.py
  tools/cfg/util/proto_reflect_util.py
Labels: automerge, cfg, enhancement, tooling

#3727 Unpack/Pack user op
  oneflow/core/actor/pack_compute_actor.cpp
  oneflow/core/actor/unpack_compute_actor.cpp
  oneflow/core/graph/logical_node.h
  oneflow/core/graph/pack_compute_task_node.cpp
  oneflow/core/graph/pack_forward_task_node.cpp
  oneflow/core/graph/pack_forward_task_node.h
  oneflow/core/graph/unpack_compute_task_node.cpp
  oneflow/core/graph/unpack_forward_task_node.cpp
  oneflow/core/graph/unpack_forward_task_node.h
  oneflow/core/job/task.proto
  oneflow/core/kernel/pack_kernel.cpp
  oneflow/core/kernel/pack_kernel.h
  oneflow/core/kernel/pack_kernel_util.cpp
  oneflow/core/kernel/pack_kernel_util.h
  oneflow/core/kernel/unpack_kernel.cpp
  oneflow/core/kernel/unpack_kernel.h
  oneflow/core/kernel/user_kernel.cpp
  oneflow/core/kernel/user_kernel.h
  oneflow/core/operator/op_conf.proto
  oneflow/core/operator/pack_op.cpp
  oneflow/core/operator/pack_op.h
  oneflow/core/operator/unpack_op.cpp
  oneflow/core/operator/unpack_op.h
  oneflow/python/framework/ops.py
  oneflow/user/kernels/pack_kernel.cpp
  oneflow/user/kernels/unpack_kernel.cpp
  oneflow/user/ops/pack_op.cpp
  oneflow/user/ops/unpack_op.cpp
Labels: automerge, enhancement, op

#3698 Refactor build script
  .github/actions/upload_oss/action.yml
  .github/actions/whl/action.yml
  .github/workflows/test.yml
  ci/test/parallel_run.py
  docker/package/manylinux/Dockerfile
  docker/package/manylinux/build_wheel.py
  oneflow/python/test/ops/test_nn_conv2d_padding_dynamic.py
  oneflow/python/test/ops/test_unsorted_segment_sum.py
Labels: build, ci, enhancement

#3104 Dev data onerec
  cmake/third_party.cmake
  cmake/third_party/flatbuffers.cmake
  cmake/third_party/lz4.cmake
  oneflow/python/ops/data_ops.py
  oneflow/python/ops/user_data_ops.py
  oneflow/user/data/batch_random_shuffle_dataset.h
  oneflow/user/data/onerec_data_reader.h
  oneflow/user/data/onerec_dataset.h
  oneflow/user/data/onerec_parser.h
  oneflow/user/kernels/example_generated.h
  oneflow/user/kernels/onerec_decoder_kernels.cpp
  oneflow/user/kernels/onerec_reader_kernel.cpp
  oneflow/user/ops/onerec_decoder_op.cpp
  oneflow/user/ops/onerec_reader_op.cpp
Labels: automerge, enhancement, tooling

#3711 use proxy blob_object for boxing, add some inter-node boxing
  oneflow/python/eager/boxing_hob.py
  oneflow/python/eager/boxing_util.py
  oneflow/python/eager/vm_util.py
Labels: automerge, eager, feature

#3729 Fix cfg sub proto mudule process bug
  tools/cfg/template_convert.py
Labels: automerge, bug, cfg, tooling

#3732 fix warning
  oneflow/user/ops/onerec_decoder_op.cpp
  oneflow/user/ops/onerec_reader_op.cpp
Labels: automerge, bug, op

#3638 Fix placement api doc
  oneflow/python/framework/placement_util.py
Labels: api, bug, documentation, python

#3737 RtRegst/Regst GetBlobDesc/BlobByOrdinal
  oneflow/core/register/register.cpp
  oneflow/core/register/register.h
  oneflow/core/register/register_desc.cpp
  oneflow/core/register/register_desc.h
  oneflow/core/register/register_manager.cpp
  oneflow/core/register/runtime_register_desc.cpp
  oneflow/core/register/runtime_register_desc.h
Labels: automerge, enhancement, system

#3739 Add user_op::KernelCreateContext
  oneflow/core/framework/op_kernel.h
  oneflow/core/framework/user_op_kernel_registry.cpp
  oneflow/core/framework/user_op_kernel_registry.h
  oneflow/core/kernel/user_kernel.cpp
  oneflow/user/kernels/model_update_kernels.cpp
Labels: enhancement, op

#3715 Ssp variable proxy
  oneflow/core/actor/actor.h
  oneflow/core/actor/case_compute_actor.h
  oneflow/core/actor/ssp_variable_proxy_actor.cpp
  oneflow/core/graph/copy_task_node.h
  oneflow/core/graph/repeat_compute_task_node.cpp
  oneflow/core/graph/ssp_variable_proxy_task_node.cpp
  oneflow/core/job/improver.cpp
  oneflow/core/job/oneflow.cpp
  oneflow/core/job/plan_util.cpp
  oneflow/core/job/plan_util.h
  oneflow/core/job/task.proto
  oneflow/core/register/register_desc.cpp
  oneflow/core/register/register_desc.h
  oneflow/core/register/register_desc.proto
  oneflow/core/vm/instruction.proto
  oneflow/python/experimental/ssp_variable_proxy_op.py
  oneflow/python/ops/user_op_builder.py
  oneflow/python/test/ops/test_ssp_variable_proxy.py
  oneflow/user/kernels/ssp_variable_proxy_kernel.cpp
  oneflow/user/ops/ssp_variable_proxy_op.cpp
Labels: automerge, feature, op, ssp

#3740 make float/double as aliases of float32/float64
  oneflow/python/framework/dtype.py
  oneflow/python/ops/pad.py
  tools/generate_oneflow_api.py
Labels: automerge, bug, python
