Repository Oneflow-Inc/oneflow, pull requests merged in 2020-11, with the labels that each got.

#3745 refactor OpGraphPass to JobPass
  oneflow/core/job/job_build_and_infer_ctx.cpp
  oneflow/core/job_rewriter/add_lbi_diff_watcher.cpp
  oneflow/core/job_rewriter/auto_learning_rate.cpp
  oneflow/core/job_rewriter/auto_mixed_precision.cpp
  oneflow/core/job_rewriter/auto_train_step.cpp
  oneflow/core/job_rewriter/complete_ofrecord_decoder.cpp
  oneflow/core/job_rewriter/cudnn_fused_normalization_add_relu_pass.cpp
  oneflow/core/job_rewriter/do_parallel_cast_before_widening_type_cast_pass.cpp
  oneflow/core/job_rewriter/dump_time_shape_and_blob_parallel_conf_pass.cpp
  oneflow/core/job_rewriter/dump_variable_info_pass.cpp
  oneflow/core/job_rewriter/fuse_add_to_output_pass.cpp
  oneflow/core/job_rewriter/fuse_update_ops_pass.cpp
  oneflow/core/job_rewriter/generate_backward_and_optimizer_op_confs.cpp
  oneflow/core/job_rewriter/indexed_slices_optimizer_rewrite_pass.cpp
  oneflow/core/job_rewriter/job_completer.cpp
  oneflow/core/job_rewriter/job_pass.cpp
  oneflow/core/job_rewriter/job_pass.h
  oneflow/core/job_rewriter/non_distributed_optimizer_pass.cpp
  oneflow/core/job_rewriter/op_graph_pass.h
  oneflow/core/job_rewriter/prune_cast_to_static_shape_op_pass.cpp
  oneflow/core/job_rewriter/prune_parallel_cast_op_pass.cpp
  oneflow/core/job_rewriter/set_default_variable_conf.cpp
  oneflow/core/job_rewriter/split_sparse_softmax_cross_entropy_op_pass.cpp
Labels: automerge, enhancement, system

#3754 fix ubuntu build relocation R_X86_64_PC32 against symbol error
  oneflow/core/job/job_build_and_infer_ctx.cpp
Labels: bug, build

#3744 Refactor ExecKernel::bn_in_op2regst_desc_id to bn_in_op2blob_info
  oneflow/core/actor/actor.cpp
  oneflow/core/actor/actor.h
  oneflow/core/actor/case_compute_actor.cpp
  oneflow/core/actor/esac_compute_actor.cpp
  oneflow/core/actor/input_wise_compute_actor.cpp
  oneflow/core/actor/reentrant_lock_compute_actor.cpp
Labels: automerge, enhancement, system

#3756 Dev scope attr value
  oneflow/core/framework/config_def.cpp
  oneflow/core/framework/config_def.h
  oneflow/core/framework/config_def.proto
  oneflow/core/framework/user_op_attr.proto
  oneflow/core/job/job_desc.cpp
  oneflow/core/job/scope.cpp
  oneflow/core/job/scope.h
  oneflow/core/job/scope.proto
  oneflow/python/framework/session_util.py
Labels: automerge, enhancement, system

#3761 Fix handle remote regst
  oneflow/core/actor/actor.cpp
  oneflow/core/register/register_manager.cpp
  oneflow/core/register/register_manager.h
Labels: automerge, bug, system

#3748 barrier for multi node eager
  oneflow/api/python/eager.cpp
  oneflow/core/eager/eager_oneflow.cpp
  oneflow/core/job/cluster.cpp
  oneflow/core/job/cluster_instruction.cpp
  oneflow/core/job/cluster_instruction.h
  oneflow/core/job/cluster_instruction.proto
Labels: automerge, bug, eager

#3766 Add bazel_cache dir for XLA build
  docker/package/manylinux/build_wheel.py
Labels: build, ci, enhancement

#3767 Fix bn[_add]_relu test case
  oneflow/python/test/ops/test_batch_normalization.py
  oneflow/python/test/ops/test_util.py
Labels: automerge, bug, op

#3763 adam_bias_correction_learning_rate
  oneflow/core/job_rewriter/adam_optm.cpp
  oneflow/core/job_rewriter/fuse_update_ops_pass.cpp
  oneflow/core/job_rewriter/generate_backward_and_optimizer_op_confs.cpp
  oneflow/core/job_rewriter/indexed_slices_optimizer_rewrite_pass.cpp
  oneflow/core/job_rewriter/job_pass.h
  oneflow/core/job_rewriter/lamb_optm.cpp
  oneflow/core/job_rewriter/lars_optm.cpp
  oneflow/core/job_rewriter/momentum_optm.cpp
  oneflow/core/job_rewriter/optimizer.cpp
  oneflow/core/job_rewriter/optimizer.h
  oneflow/core/job_rewriter/rmsprop_optm.cpp
  oneflow/core/job_rewriter/sgd_optm.cpp
  oneflow/user/kernels/model_update_kernel_util.cpp
  oneflow/user/kernels/model_update_kernel_util.cu
  oneflow/user/kernels/model_update_kernel_util.h
  oneflow/user/kernels/model_update_kernels.cpp
  oneflow/user/ops/model_update_ops.cpp
Labels: automerge, enhancement, op

#3742 fix exception in BlobObject __del__
  oneflow/init.py
  oneflow/python/eager/object.py
  oneflow/python/framework/python_interpreter_util.py
Labels: automerge, bug, python

#3765 Bakcport bug fixes for distributed run from multi node ci
  oneflow/api/python/init.cpp
  oneflow/core/comm_network/epoll/epoll_comm_network.cpp
  oneflow/core/job/cluster.cpp
  oneflow/core/job/cluster_instruction.cpp
  oneflow/core/job/cluster_instruction.h
  oneflow/core/job/cluster_instruction.proto
  oneflow/init.py
Labels: automerge, bug, system

#3774 refactor ParallelDescSymbol
  oneflow/python/eager/boxing_middle.py
  oneflow/python/eager/symbol.py
  oneflow/python/eager/vm_util.py
Labels: automerge, eager, enhancement, refactor

#3735 Multi node support in CI
  .dockerignore
  .github/workflows/test.yml
  .gitignore
  ci/test/2node_op_test.sh
  ci/test/distributed_run.py
  docker/ci/test/Dockerfile
  docker/ci/test/build.sh
  docker/ci/test/launch.sh
  oneflow/python/deprecated/init_cluster_env.py
  oneflow/python/framework/unittest.py
  oneflow/python/test/ops/test_dynamic_binary.py
Labels: automerge, ci, feature

#3778 Fix oneflow worker launch in py35
  oneflow/python/deprecated/init_cluster_env.py
Labels: bug, tooling

#3786 ci dont test 2n8c
  ci/test/2node_op_test.sh
Labels: ci, enhancement

#3795 Fix CUDA 11.1 compiler crashes
  oneflow/core/common/maybe.h
Labels: automerge, bug, system

#3788 Fix __hne in BinaryFuncFloorMod
  oneflow/core/ndarray/binary_func.h
Labels: automerge, bug, op

#3789 add flatten op implementation
  oneflow/python/ops/array_ops.py
  oneflow/python/test/ops/test_flatten.py
  oneflow/user/kernels/flatten_kernel.cpp
  oneflow/user/ops/flatten_op.cpp
Labels: automerge, enhancement, op, serving

#3802 OneFlow support tensor shape max dim size up to 6
  oneflow/core/common/util.h
  oneflow/core/kernel/arg_where_kernel.cpp
  oneflow/core/kernel/arg_where_kernel_util.h
  oneflow/core/ndarray/xpu_broadcast_ndarray.h
  oneflow/core/ndarray/xpu_shape.h
  oneflow/python/test/ops/test_transpose.py
Labels: automerge, feature, system

#3773 Replace py instruction to CFG Instruction
  cmake/cfg.cmake
  oneflow/python/eager/vm_util.py
  oneflow/python/framework/c_api_util.py
  oneflow/python/framework/session_util.py
  oneflow/python/ops/user_op_builder.py
Labels: automerge, cfg, eager, enhancement

#3806 Support Ampere devices
  CMakeLists.txt
  cmake/third_party/FindCUDNN.cmake
Labels: automerge, bug, enhancement, system

#3815 fix cfg module load error bug
  tools/cfg/template_convert.py
Labels: automerge, bug, cfg, tooling

#3830 Prevent CI failure
  .github/workflows/test.yml
  oneflow/python/test/ops/test_compat_conv2d.py
  oneflow/python/test/ops/test_nn_conv2d.py
  oneflow/python/test/ops/test_nn_conv2d_padding_dynamic.py
  oneflow/python/test/ops/test_pad.py
Labels: automerge, ci, enhancement

#3808 Dev forward declare cfg
  tools/cfg/include/oneflow/cfg/map_field.h
  tools/cfg/include/oneflow/cfg/repeated_field.h
  tools/cfg/template/template.cfg.cpp
  tools/cfg/template/template.cfg.h
  tools/cfg/template/template.cfg.pybind.cpp
  tools/cfg/util/proto_reflect_util.py
Labels: automerge, enhancement, system

#3796 Memory Reuse support time shape > meta shape
  oneflow/core/job/intra_job_mem_sharing_util.cpp
Labels: automerge, feature, ssp, system

#3813 skip conv2d padding dynamic test case
  oneflow/python/test/ops/test_nn_conv2d_padding_dynamic.py
Labels: automerge, bug, op

#3831 CI run when bot is requested review
  .github/workflows/test.yml
Labels: ci, enhancement

#3837 Add pull_request_target to allow forks access secrets when CI triggerd
  .github/workflows/test.yml
Labels: ci, enhancement

#3840 ci only use pull_request_target
  .github/workflows/test.yml
Labels: ci, enhancement

#3842 ci use pull_request ev
  .github/workflows/test.yml
Labels: ci, enhancement

#3843 External PR skip oss steps
  .github/actions/upload_oss/action.yml
  .github/workflows/test.yml
Labels: automerge, ci, enhancement

#3829 Dev cpp instructions builder
  oneflow/core/common/cfg_reflection_test.cpp
  oneflow/core/eager/eager_oneflow.cpp
  oneflow/core/eager/eager_oneflow.h
  oneflow/core/framework/eager_util.h
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/framework/instructions_builder.h
  oneflow/core/framework/interpreter.cpp
  oneflow/core/framework/interpreter.h
  oneflow/core/framework/interpreter_test.cpp
  oneflow/core/framework/symbol_id_cache.cpp
  oneflow/core/framework/symbol_id_cache.h
  oneflow/core/job/scope.proto
  oneflow/core/vm/id_generator.cpp
  oneflow/core/vm/id_generator.h
  oneflow/core/vm/symbol_storage.h
  oneflow/core/vm/test_util.cpp
  oneflow/core/vm/test_util.h
Labels: automerge, enhancement, system

#3847 Update hard coded host affiliations
  .github/workflows/pr.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  ci/test/distributed_run.py
Labels: ci, enhancement

#3602 torch.gather
  oneflow/python/ops/array_ops.py
  oneflow/python/test/ops/test_dim_gather.py
  oneflow/user/kernels/dim_gather_kernel_util.cpp
  oneflow/user/kernels/dim_gather_kernel_util.cu
  oneflow/user/kernels/dim_gather_kernel_util.h
  oneflow/user/kernels/dim_gather_kernels.cpp
  oneflow/user/ops/dim_gather_op.cpp
Labels: automerge, enhancement, op

#3844 Sort cfg obj forward declare
  tools/cfg/template_convert.py
  tools/cfg/util/proto_reflect_util.py
Labels: automerge, cfg, enhancement, tooling

#3863 Check label every push
  .github/workflows/pr.yml
Labels: ci, enhancement

#3853 Optimize softmax cuda kernel block size
  oneflow/user/kernels/softmax_kernel.cu
Labels: enhancement, op

#3793 add l1 loss op in python
  oneflow/python/ops/nn_ops.py
  oneflow/python/test/ops/test_l1loss.py
Labels: automerge, enhancement, feature, python

#3868 CI merge all jobs into one
  .github/workflows/test.yml
Labels: automerge, ci, enhancement

#3866 SplitLikeOp prefix support
  oneflow/user/kernels/split_like_kernel.cpp
  oneflow/user/ops/split_like_op.cpp
Labels: automerge, enhancement, op

#3725 add oneflow_range
  oneflow/python/ops/math_ops.py
  oneflow/python/test/ops/test_range.py
  oneflow/user/kernels/range_kernel.cpp
  oneflow/user/kernels/range_kernel_util.cpp
  oneflow/user/kernels/range_kernel_util.cu
  oneflow/user/kernels/range_kernel_util.h
  oneflow/user/ops/range_op.cpp
Labels: automerge, enhancement, op

#3870 Dev use union instead of struct for oneof
  tools/cfg/template/template.cfg.cpp
  tools/cfg/template/template.cfg.h
Labels: automerge, cfg, enhancement, tooling

#3861 Cfg template operator reform
  tools/cfg/template/template.cfg.cpp
Labels: automerge, cfg, enhancement, tooling

#3869 Fix CUDA_NVCC_GENCODES
  CMakeLists.txt
Labels: automerge, bug, build

#3832 Dev replace str to cfg obj in python callback
  oneflow/api/python/framework/python_callback.cpp
  oneflow/core/job/foreign_callback.h
  oneflow/core/job/job_build_and_infer_ctx.cpp
  oneflow/core/job_rewriter/auto_train_step.cpp
  oneflow/core/job_rewriter/autograd.cpp
  oneflow/core/operator/distribute_add_op.cpp
  oneflow/core/operator/distribute_clone_op.cpp
  oneflow/core/operator/distribute_concat_op.cpp
  oneflow/core/operator/distribute_split_op.cpp
  oneflow/python/framework/python_callback.py
Labels: automerge, enhancement, system

#3828 Dev enhance sort ops
  oneflow/python/ops/math_ops.py
  oneflow/python/ops/sort_ops.py
  oneflow/python/ops/transpose_util.py
  oneflow/python/test/ops/test_argmax.py
  oneflow/python/test/ops/test_argsort.py
  oneflow/python/test/ops/test_sort.py
  oneflow/python/test/ops/test_top_k.py
  oneflow/user/ops/transpose_ops.cpp
Labels: automerge, enhancement, op

#3876 fix pybind11 include
  cmake/pybind11.cmake
Labels: automerge, bug, system

#3809 optimize rmsprop and lars optimizers
  oneflow/core/job_rewriter/fuse_update_ops_pass.cpp
  oneflow/core/job_rewriter/lars_optm.cpp
  oneflow/core/job_rewriter/optimizer.cpp
  oneflow/core/job_rewriter/rmsprop_optm.cpp
  oneflow/core/kernel/lars_model_update_kernel.cpp
  oneflow/core/kernel/lars_model_update_kernel.cu
  oneflow/core/kernel/lars_model_update_kernel.h
  oneflow/core/kernel/rmsprop_model_update_kernel.cpp
  oneflow/core/kernel/rmsprop_model_update_kernel.cu
  oneflow/core/kernel/rmsprop_model_update_kernel.h
  oneflow/core/operator/lars_model_update_op.cpp
  oneflow/core/operator/lars_model_update_op.h
  oneflow/core/operator/op_conf.proto
  oneflow/core/operator/rmsprop_model_update_op.cpp
  oneflow/core/operator/rmsprop_model_update_op.h
  oneflow/user/kernels/model_update_kernel_util.cpp
  oneflow/user/kernels/model_update_kernel_util.cu
  oneflow/user/kernels/model_update_kernel_util.h
  oneflow/user/kernels/model_update_kernels.cpp
  oneflow/user/ops/model_update_ops.cpp
Labels: automerge, enhancement, op

#3878 fix stirng format in py35
  oneflow/python/ops/util/op_lib_builder.py
  oneflow/python/test/custom_ops/user_sigmoid/user_sigmoid_py_kernel.py
Labels: automerge, bug, enhancement, python

#3865 rm scope_proto symbol_id
  oneflow/core/framework/symbol_id_cache.h
  oneflow/core/job/scope.proto
  oneflow/python/eager/vm_util.py
  oneflow/python/framework/scope_symbol.py
Labels: automerge, eager, enhancement, python, refactor

#3855 Simple kernel memory bandwidth profiler
  CMakeLists.txt
  oneflow/core/kernel/kernel.cpp
  oneflow/core/profiler/kernel.cpp
  oneflow/core/profiler/kernel.h
  oneflow/core/profiler/profiler.cpp
  oneflow/core/profiler/profiler.h
Labels: automerge, enhancement, system

#3883 model update op add skip if
  oneflow/core/job_rewriter/fuse_update_ops_pass.cpp
  oneflow/user/kernels/model_update_kernel_util.cpp
  oneflow/user/kernels/model_update_kernel_util.cu
  oneflow/user/kernels/model_update_kernel_util.h
  oneflow/user/kernels/model_update_kernels.cpp
  oneflow/user/ops/model_update_ops.cpp
Labels: automerge, feature, op

#3879 multi_count_not_finite op
  oneflow/python/ops/count_not_finite.py
  oneflow/python/test/ops/test_count_not_finite.py
  oneflow/user/kernels/count_not_finite_kernel.cpp
  oneflow/user/kernels/count_not_finite_kernel.cu
  oneflow/user/ops/count_not_finite_op.cpp
Labels: automerge, feature, op

#3833 Op collection
  oneflow/api/python/framework/python_callback.cpp
  oneflow/core/common/error.cpp
  oneflow/core/common/error.h
  oneflow/core/common/error.proto
  oneflow/core/common/maybe.h
  oneflow/core/framework/interpreter.cpp
  oneflow/core/job/foreign_callback.h
  oneflow/core/job/job_build_and_infer_ctx.cpp
  oneflow/core/job/job_build_and_infer_ctx.h
  oneflow/core/job/scope.proto
  oneflow/core/job_rewriter/auto_mixed_precision.cpp
  oneflow/core/job_rewriter/calculation_pass.cpp
  oneflow/core/job_rewriter/calculation_pass.h
  oneflow/core/job_rewriter/generate_backward_and_optimizer_op_confs.cpp
  oneflow/core/job_rewriter/identity_grad.cpp
  oneflow/core/operator/distribute_clone_op.cpp
  oneflow/python/eager/interpreter_callback.py
  oneflow/python/framework/python_callback.py
Labels: automerge, enhancement, system

#3859 Add ssp variable proxy
  oneflow/core/framework/config_def.cpp
  oneflow/core/framework/config_def.h
  oneflow/core/graph/graph.h
  oneflow/core/graph/node.h
  oneflow/core/job/job_build_and_infer_ctx.cpp
  oneflow/core/job/scope.cpp
  oneflow/core/job/scope.h
  oneflow/core/job/ssp_config_def.cpp
  oneflow/core/job_rewriter/add_ssp_variable_proxy.cpp
  oneflow/core/job_rewriter/autograd.cpp
  oneflow/core/job_rewriter/autograd.h
  oneflow/core/operator/distribute_add_op.cpp
  oneflow/core/operator/distribute_clone_op.cpp
  oneflow/core/operator/distribute_concat_op.cpp
  oneflow/core/operator/distribute_split_op.cpp
  oneflow/core/operator/operator.cpp
  oneflow/python/framework/attr_util.py
  oneflow/python/framework/c_api_util.py
  oneflow/python/framework/scope_symbol.py
  oneflow/python/framework/scope_util.py
  oneflow/python/framework/session_util.py
  oneflow/python/oneflow_internal.h
  oneflow/python/oneflow_internal_helper.h
  oneflow/python/test/ops/test_ssp_variable_proxy.py
Labels: automerge, enhancement, system

#3804 add bceloss
  .github/workflows/test.yml
  oneflow/python/ops/nn_ops.py
  oneflow/python/test/ops/test_bce_loss.py
Labels: automerge, feature, python

#3835 add check in deconv
  oneflow/python/ops/nn_ops.py
  oneflow/python/test/models/test_dcgan.py
Labels: automerge, feature, python, refactor

#3898 fix unsorted segment sum like
  oneflow/user/kernels/unsorted_segment_sum_kernel.cpp
  oneflow/user/ops/unsorted_segment_sum_op.cpp
Labels: automerge, bug, op

#3900 fix gather set_is_dynamic
  oneflow/user/ops/gather_op.cpp
Labels: automerge, bug, op

#3904 UserOpWrapper add HasGradTensor4OpOutput
  oneflow/core/framework/user_op_conf.cpp
  oneflow/core/framework/user_op_conf.h
Labels: automerge, enhancement, op

#3899 distribute concat out dynamic false
  oneflow/core/operator/distribute_concat_op.cpp
Labels: automerge, bug, op

#3893 add mseloss
  oneflow/python/ops/nn_ops.py
  oneflow/python/test/ops/test_mseloss.py
Labels: automerge, feature, op, python

#3886 DynamicLossScale
  oneflow/core/common/protobuf.h
  oneflow/core/graph/op_graph.cpp
  oneflow/core/job/job_build_and_infer_ctx.cpp
  oneflow/core/job/job_conf.proto
  oneflow/core/job/job_desc.cpp
  oneflow/core/job/job_desc.h
  oneflow/core/job_rewriter/adam_optm.cpp
  oneflow/core/job_rewriter/auto_train_step.cpp
  oneflow/core/job_rewriter/autograd.cpp
  oneflow/core/job_rewriter/autograd.h
  oneflow/core/job_rewriter/dynamic_loss_scale_job_pass_state.h
  oneflow/core/job_rewriter/dynamic_loss_scale_schedule_pass.cpp
  oneflow/core/job_rewriter/generate_backward_and_optimizer_op_confs.cpp
  oneflow/core/job_rewriter/lamb_optm.cpp
  oneflow/core/job_rewriter/lars_optm.cpp
  oneflow/core/job_rewriter/momentum_optm.cpp
  oneflow/core/job_rewriter/optimizer.cpp
  oneflow/core/job_rewriter/optimizer.h
  oneflow/core/job_rewriter/rmsprop_optm.cpp
  oneflow/core/job_rewriter/sgd_optm.cpp
  oneflow/python/ops/optimizer.py
  oneflow/python/test/ops/test_dynamic_loss_scale_schedule.py
  oneflow/user/kernels/assign_if_kernel.cpp
  oneflow/user/kernels/assign_if_kernel.cu
  oneflow/user/kernels/dynamic_loss_scale_schedule_kernel.cpp
  oneflow/user/kernels/dynamic_loss_scale_schedule_kernel.cu
  oneflow/user/ops/assign_op.cpp
  oneflow/user/ops/dynamic_loss_scale_schedule_op.cpp
Labels: automerge, feature, system

#3541 Add polyval op
  oneflow/python/ops/math_ops.py
  oneflow/python/test/ops/test_polyval.py
Labels: automerge, enhancement, op

#3906 optimize cfg generator to save time
  cmake/cfg.cmake
  tools/cfg/copy_proto_python_file.py
  tools/cfg/generate_cfg_head_dir_and_convert_src.py
  tools/cfg/template_convert.py
Labels: automerge, cfg, enhancement, tooling

#3901 Dev split like add backward
  oneflow/python/test/ops/test_split_like.py
  oneflow/user/ops/split_like_op.cpp
Labels: automerge, bug, op

#3907 fix include files not copied
  cmake/oneflow.cmake
  oneflow/python/test/ops/test_batch_normalization.py
  tools/clean_generated_api.py
Labels: automerge, bug, build

#3731 Dev unsorted segment sum
  oneflow/core/kernel/indexed_slices_reduce_sum_kernel_util.cpp
  oneflow/core/kernel/unsorted_segment_sum_kernel_util.cpp
  oneflow/core/kernel/unsorted_segment_sum_kernel_util.cu
  oneflow/core/kernel/unsorted_segment_sum_kernel_util.h
  oneflow/python/test/ops/test_unsorted_segment_sum.py
  oneflow/user/kernels/unsorted_segment_sum_kernel.cpp
Labels: automerge, enhancement, op

#3864 Add triplet loss
  oneflow/python/ops/nn_ops.py
  oneflow/python/test/ops/test_MarginRankingLoss.py
  oneflow/python/test/ops/test_TripletMarginLoss.py
Labels: automerge, feature, python

#3917 Remove NormalModelUpdateOpConf
  oneflow/core/actor/normal_forward_compute_actor.cpp
  oneflow/core/graph/logical_node.cpp
  oneflow/core/graph/logical_node.h
  oneflow/core/graph/op_graph.cpp
  oneflow/core/graph/optimizer_compute_task_node.cpp
  oneflow/core/graph/optimizer_compute_task_node.h
  oneflow/core/job/task.proto
  oneflow/core/job_rewriter/optimizer.cpp
  oneflow/core/job_rewriter/optimizer.h
  oneflow/core/kernel/kernel.proto
  oneflow/core/kernel/normal_model_update_kernel.cpp
  oneflow/core/kernel/normal_model_update_kernel.h
  oneflow/core/operator/normal_model_update_op.cpp
  oneflow/core/operator/normal_model_update_op.h
  oneflow/core/operator/op_conf.proto
  oneflow/xrt/launch_op.h
Labels: enhancement, op

#3915 Reshape backward issue with distribute split
  oneflow/python/test/ops/test_reshapeV3.py
  oneflow/user/ops/broadcast_like_op.cpp
  oneflow/user/ops/dim_gather_op.cpp
  oneflow/user/ops/reshape_like_op.cpp
  oneflow/user/ops/reshape_op.cpp
  oneflow/user/ops/reshape_user_op_util.cpp
  oneflow/user/ops/reshape_user_op_util.h
Labels: automerge, bug, op

#3540 New checkpoint
  ci/test/2node_op_test.sh
  oneflow/core/framework/variable_meta_info.proto
  oneflow/core/job/job_set.proto
  oneflow/core/job/oneflow.cpp
  oneflow/core/operator/op_attribute.proto
  oneflow/python/eager/op_infer_util.py
  oneflow/python/eager/vm_util.py
  oneflow/python/experimental/interface_op_read_and_write.py
  oneflow/python/framework/c_api_util.py
  oneflow/python/framework/check_point.py
  oneflow/python/framework/check_point_v2.py
  oneflow/python/framework/config_util.py
  oneflow/python/framework/push_util.py
  oneflow/python/framework/session_util.py
  oneflow/python/oneflow_internal.h
  oneflow/python/oneflow_internal_helper.h
  oneflow/python/ops/get_variable.py
  oneflow/python/ops/initializer_util.py
  oneflow/python/test/ops/test_bce_loss.py
  oneflow/python/test/ops/test_checkpoint.py
  oneflow/python/test/ops/test_initializer.py
  oneflow/python/test/ops/test_layer_norm.py
  oneflow/python/test/ops/test_mseloss.py
  oneflow/user/kernels/slice_kernel.cpp
Labels: feature, system

#3803 fix distribute_clone sbp
  oneflow/core/operator/distribute_clone_op.cpp
Labels: automerge, bug, op

#3894 Build master whl once a day
  .github/workflows/release.yml
  .github/workflows/test.yml
  ci/build/ensure_img.py
  ci/test/parallel_run.py
  docker/package/manylinux/build_wheel.py
  oneflow/python/version.py
  tools/oss_file_exist.py
Labels: automerge, ci, enhancement

#3874 New Chain
  ci/test/distributed_run.py
  oneflow/core/graph/task_graph.cpp
  oneflow/core/graph/task_graph.h
  oneflow/core/job/compiler.cpp
  oneflow/core/job/intra_job_mem_sharing_util.cpp
  oneflow/core/job/job_conf.proto
  oneflow/core/operator/device_tick_op.cpp
  oneflow/core/operator/keep_header_only_op.cpp
  oneflow/core/operator/tick_op.cpp
Labels: automerge, bottleneck, enhancement, system

#3858 Dev switch error proto with cfg error proto
  cmake/cfg.cmake
  cmake/oneflow.cmake
  oneflow/core/common/error.cpp
  oneflow/core/common/error.h
  oneflow/core/common/maybe.h
  oneflow/core/graph/boxing/sub_task_graph_builder_util.cpp
  oneflow/core/graph/boxing/sub_task_graph_builder_util.h
  oneflow/user/ops/batch_gather_op.cpp
  tools/cfg/include/oneflow/cfg/pybind_module_registry.h
Labels: automerge, cfg, enhancement, system

#3924 Refine release oss url
  .github/workflows/release.yml
  README.md
  tools/create_pip_index.py
Labels: ci, enhancement

#3935 fix oss list file 100 limit
  .github/workflows/release.yml
  tools/create_pip_index.py
Labels: automerge, bug, ci

#3933 indexed_slices_model_update handle empty tensor
  oneflow/user/kernels/model_update_kernels.cpp
Labels: automerge, bug, op

#3937 Explicitly specify the SBP in NonDistributedOptimizerPass
  oneflow/core/job_rewriter/non_distributed_optimizer_pass.cpp
Labels: automerge, bug, system

#3943 disable new checkpoint by default temporarily
  oneflow/core/job/job_set.proto
  oneflow/python/test/ops/test_checkpoint.py
Labels: automerge, bug, system

#3942 Add NaiveB2PSubTskGphBuilder
  oneflow/core/actor/boxing_zeros_actor.cpp
  oneflow/core/actor/naive_actor.h
  oneflow/core/graph/boxing/naive_b2p_sub_task_graph_builder.cpp
  oneflow/core/graph/boxing/naive_b2p_sub_task_graph_builder.h
  oneflow/core/graph/boxing_zeros_task_node.cpp
  oneflow/core/graph/boxing_zeros_task_node.h
  oneflow/core/graph/task_graph.cpp
  oneflow/core/job/task.proto
  oneflow/core/kernel/boxing_zeros_kernel.cpp
  oneflow/core/operator/boxing_zeros_op.cpp
  oneflow/core/operator/op_conf.proto
Labels: automerge, feature, system

#3810 Dev replace py parallel conf proto to cfg
  oneflow/python/eager/boxing_middle.py
  oneflow/python/eager/boxing_util.py
  oneflow/python/eager/interpreter_callback.py
  oneflow/python/eager/op_executor.py
  oneflow/python/eager/symbol.py
  oneflow/python/eager/vm_util.py
  oneflow/python/framework/c_api_util.py
  oneflow/python/framework/parallel_conf_util.py
  oneflow/python/framework/placement_context.py
  oneflow/python/framework/python_callback.py
  oneflow/python/framework/remote_blob.py
  oneflow/python/framework/scope_symbol.py
  oneflow/python/ops/__init__.py
  oneflow/python/ops/watch.py
  oneflow/python/test/ops/test_cpu_only_user_op.py
  tools/cfg/template/template.cfg.cpp
  tools/cfg/template/template.cfg.h
  tools/cfg/template/template.cfg.pybind.cpp
Labels: automerge, cfg, enhancement, tooling

#3948 default show cpp error stack frame
  oneflow/python/framework/job_build_and_infer_error.py
Labels: enhancement, tooling

#3819 add combined margin loss
  oneflow/python/ops/combined_margin_loss.py
  oneflow/python/test/ops/test_combined_margin_loss.py
  oneflow/user/kernels/combined_margin_loss_kernel.cu
  oneflow/user/ops/combined_margin_loss_op.cpp
Labels: automerge, feature, op
