Repository Oneflow-Inc/oneflow, pull requests merged in 2020-12, with the labels that each got.

#3925 Refine custom op build
  oneflow/extension/python/py_compute.cpp
  oneflow/extension/python/py_kernel_caller.cpp
  oneflow/extension/python/py_kernel_caller.h
  oneflow/extension/python/py_kernel_registry.cpp
  oneflow/extension/python/py_kernel_registry.h
  oneflow/python/ops/util/custom_op_module.py
  oneflow/python/test/custom_ops/test_user_sigmoid.py
  oneflow/python/test/custom_ops/user_sigmoid/user_sigmoid_cpp_def.cpp
  oneflow/python/test/custom_ops/user_sigmoid/user_sigmoid_cpp_kernel.cpp
  oneflow/python/test/custom_ops/user_sigmoid/user_sigmoid_py_api.py
  oneflow/python/test/custom_ops/user_sigmoid/user_sigmoid_py_kernel.py
Labels: api, automerge, enhancement, refactor, tooling

#3947 Fix constant init value
  oneflow/python/ops/constant_op.py
  oneflow/python/test/ops/test_constant.py
Labels: automerge, bug, op

#3946 Fix CollectiveBoxingGenericTaskNode::ProduceAllRegstsAndBindEdges
  oneflow/core/graph/collective_boxing_task_node.cpp
Labels: automerge, bug, system

#3891 remove serialized in python callback
  oneflow/api/python/framework/python_callback.cpp
  oneflow/core/job/foreign_callback.h
  oneflow/core/job_rewriter/generate_backward_and_optimizer_op_confs.cpp
  oneflow/python/framework/python_callback.py
Labels: automerge, enhancement, system

#3960 TripOp add fill value
  oneflow/core/job_rewriter/auto_mixed_precision_lists.cpp
  oneflow/python/ops/math_ops.py
  oneflow/python/test/ops/test_tril.py
  oneflow/user/kernels/tril_kernel.cpp
  oneflow/user/kernels/tril_kernel.cu
  oneflow/user/ops/tril_op.cpp
Labels: automerge, feature, op

#3816 replace ScopeProto to cfg
  oneflow/python/eager/interpreter_callback.py
  oneflow/python/eager/vm_util.py
  oneflow/python/framework/attr_util.py
  oneflow/python/framework/python_callback.py
  oneflow/python/framework/scope_symbol.py
  oneflow/python/framework/scope_util.py
Labels: automerge, cfg, enhancement, refactor, tooling

#3856 Dev replace py job conf proto to cfg
  oneflow/python/eager/interpreter_callback.py
  oneflow/python/eager/vm_util.py
  oneflow/python/framework/c_api_util.py
  oneflow/python/framework/compiler.py
  oneflow/python/framework/function_desc.py
  oneflow/python/framework/function_util.py
  oneflow/python/framework/python_callback.py
  oneflow/python/framework/scope_util.py
  oneflow/python/framework/session_util.py
  oneflow/python/lib/core/pb_util.py
  oneflow/python/onnx/flow2onnx.py
  oneflow/python/ops/get_variable.py
  oneflow/python/test/customized/ccrelu_alexnet.py
  oneflow/python/test/models/alexnet.py
  oneflow/python/test/models/alexnet_with_unpack.py
Labels: cfg, enhancement, python

#3965 larger tol for bn
  oneflow/python/test/ops/test_batch_normalization.py
Labels: automerge, ci, enhancement, test

#3971 fix pad op
  oneflow/python/ops/pad.py
Labels: automerge, bug, op

#3977 Add multi_square_sum op
  oneflow/core/kernel/square_sum_kernel_util.cpp
  oneflow/core/kernel/square_sum_kernel_util.cu
  oneflow/core/kernel/square_sum_kernel_util.h
  oneflow/python/test/ops/test_multi_square_sum.py
  oneflow/user/kernels/square_sum_kernel.cpp
  oneflow/user/ops/count_not_finite_op.cpp
  oneflow/user/ops/square_sum_op.cpp
Labels: automerge, feature, op

#3980 fused_scale_tril / hot fix matmul / softmax broadcast_sub broadcast_div
  oneflow/core/job_rewriter/auto_mixed_precision_lists.cpp
  oneflow/core/kernel/util/cuda_blas_interface.cu
  oneflow/python/ops/math_ops.py
  oneflow/python/test/ops/test_fused_scale_tril.py
  oneflow/python/test/ops/test_matmul.py
  oneflow/user/kernels/softmax_kernel_util.cpp
  oneflow/user/kernels/softmax_kernel_util.cu
  oneflow/user/kernels/tril_kernel.cu
  oneflow/user/ops/tril_op.cpp
Labels: automerge, enhancement, op

#3981 nccl enable mixed fusion
  oneflow/core/job/collective_boxing_executor.cpp
  oneflow/core/job/resource.proto
  oneflow/python/framework/config_util.py
Labels: automerge, feature, system

#3979 Add gradients stats aggregation
  oneflow/core/job/job_conf.proto
  oneflow/core/job_rewriter/autograd.cpp
  oneflow/core/job_rewriter/generate_backward_and_optimizer_op_confs.cpp
  oneflow/python/framework/function_util.py
Labels: enhancement, system

#3976 Sublinear memory cost by checkpointing
  oneflow/core/job/checkpointing_config_def.cpp
  oneflow/core/job/job_build_and_infer_ctx.cpp
  oneflow/core/job_rewriter/checkpointing_pass.cpp
Labels: automerge, bottleneck, enhancement, system

#3988 Hotfix: add parallel cast to amp clear list
  oneflow/core/job_rewriter/auto_mixed_precision.cpp
Labels: automerge, bug, op

#3989 Optimize slice kernel
  oneflow/user/kernels/slice_util.cu
Labels: automerge, enhancement, op

#3992 Switch identity to user op and add it to auto mixed precision clear list
  oneflow/core/job_rewriter/auto_mixed_precision_lists.cpp
  oneflow/python/ops/array_ops.py
  oneflow/python/test/ops/test_tensor_list_and_tensor_buffer.py
Labels: api, enhancement, op

#3987 Dev optimize prelu
  oneflow/python/test/ops/test_prelu.py
  oneflow/user/kernels/prelu_kernel.cpp
  oneflow/user/kernels/prelu_kernel.cu
  oneflow/user/ops/prelu_op.cpp
Labels: enhancement, op

#3944 OptimizerPlacementOptimization
  oneflow/core/job/job_build_and_infer_ctx.cpp
  oneflow/core/job/job_conf.proto
  oneflow/core/job/job_desc.h
  oneflow/core/job/oneflow.cpp
  oneflow/core/job_rewriter/non_distributed_optimizer_pass.cpp
  oneflow/core/job_rewriter/optimizer_placement_optimization_pass.cpp
  oneflow/python/framework/function_util.py
  oneflow/python/framework/session_util.py
  oneflow/python/test/ops/test_non_distribute_optimizer.py
  oneflow/python/test/ops/test_optimizer_placement_optimization.py
Labels: feature, system

#3997 Optimize NcclCollectiveBoxingExecutorBackend::ExecuteGroup latency
  oneflow/core/job/collective_boxing_executor.cpp
  oneflow/core/job/collective_boxing_executor.h
  oneflow/core/kernel/collective_boxing_kernels.cpp
Labels: enhancement, system

#3998 layer_norm_grad_add_to_output
  oneflow/core/job_rewriter/fuse_add_to_output_pass.cpp
  oneflow/python/test/ops/test_layer_norm.py
  oneflow/user/kernels/layer_norm_gpu_kernel.cu
  oneflow/user/ops/layer_norm_op.cpp
Labels: enhancement, op

#3999 Fuse cast scale
  oneflow/core/job/job_build_and_infer_ctx.cpp
  oneflow/core/job/job_conf.proto
  oneflow/core/job_rewriter/fuse_cast_scale_pass.cpp
  oneflow/core/kernel/kernel_util.cu
  oneflow/python/framework/function_util.py
  oneflow/python/test/ops/test_fuse_cast_scale.py
  oneflow/user/kernels/fused_cast_scale_kernel.cpp
  oneflow/user/kernels/fused_cast_scale_kernel.cu
  oneflow/user/ops/fused_cast_scale_op.cpp
Labels: enhancement, op

#4000 upload bin to oss
  .github/workflows/release.yml
Labels: automerge, ci, enhancement

#4008 Fix eager memory leak and re-enable new checkpoint
  oneflow/core/job/job_set.proto
  oneflow/core/vm/virtual_machine.cpp
  oneflow/python/test/ops/test_checkpoint.py
Labels: bug, eager

#3972 add mish activation
  oneflow/python/ops/math_ops.py
  oneflow/python/test/ops/test_mish.py
Labels: automerge, feature, op, python

#4009 Argwhere support empty blob
  oneflow/core/kernel/arg_where_kernel.cpp
  oneflow/core/kernel/arg_where_kernel_util.cpp
  oneflow/core/kernel/arg_where_kernel_util.cu
  oneflow/core/kernel/arg_where_kernel_util.h
Labels: automerge, enhancement, op

#4010 fix argwhere format
  oneflow/core/kernel/arg_where_kernel_util.cpp
  oneflow/core/kernel/arg_where_kernel_util.cu
Labels: automerge, bug, op

#3970 add swish activation
  oneflow/python/ops/math_ops.py
  oneflow/python/test/ops/test_swish.py
Labels: automerge, feature, op, python

#4002 split_cfg_cpp_and_pybind_generator
  cmake/cfg.cmake
  tools/cfg/template_convert.py
Labels: automerge, feature, tooling

#3897 add stack
  oneflow/python/ops/array_ops.py
  oneflow/python/test/ops/test_stack.py
Labels: automerge, feature, python

#3940 migrate job_build_and_infer api to pybind11
  oneflow/api/python/job_build/job_build_and_infer.cpp
  oneflow/api/python/job_build/job_build_and_infer.h
  oneflow/api/python/job_build/job_build_and_infer_helper.h
  oneflow/python/framework/c_api_util.py
  oneflow/python/framework/job_build_and_infer_cfg_error.py
  oneflow/python/framework/ofblob.py
  oneflow/python/job_build_and_infer_if.h
  oneflow/python/oneflow_internal.i
Labels: automerge, enhancement, system

#4004 Fix eager bug of test split like
  oneflow/core/job/job_build_and_infer_ctx.cpp
  oneflow/python/ops/user_op_builder.py
Labels: automerge, bug, eager

#3875 Bump nccl from 2.7.3 to 2.8.3
  cmake/third_party/nccl.cmake
Labels: automerge, build, enhancement, system

#4007 CUDA template for element-wise kernels
  oneflow/core/cuda/elementwise.cuh
  oneflow/user/kernels/gelu_kernel.cu
  oneflow/user/kernels/where_kernel_util.cu
Labels: feature, op

#3930 Optimize ComputeEntropyGpu with CUB
  oneflow/core/kernel/util/cuda_kernel_util.cu
  oneflow/python/test/ops/test_softmax_cross_entropy.py
  oneflow/user/kernels/softmax_cross_entropy_kernel.cu
Labels: enhancement, op

#3991 add zeros api
  oneflow/python/ops/array_ops.py
  oneflow/python/test/ops/test_zeros.py
Labels: automerge, enhancement, op, python

#3969 Remove swig in oneflow
  CMakeLists.txt
  README.md
  docker/build/Dockerfile
  docker/build/build.ubuntu.dockerfile
  docker/ci/base/Dockerfile
  docker/package/manylinux/Dockerfile
  docs/source/troubleshooting.md
Labels: automerge, feature, system

#4011 Set default block size to 512
  oneflow/core/device/cuda_util.h
Labels: automerge, enhancement, system

#4013 Scalar kernels use element-wise template
  oneflow/core/kernel/kernel_util.cpp
  oneflow/core/kernel/kernel_util.cu
  oneflow/core/kernel/kernel_util.h
  oneflow/core/kernel/util/cuda_arithemetic_interface.cu
  oneflow/core/kernel/util/cuda_arithemetic_interface.h
  oneflow/core/kernel/util/host_arithemetic_interface.cpp
  oneflow/core/kernel/util/host_arithemetic_interface.h
  oneflow/user/kernels/scalar_add_kernel.cpp
  oneflow/user/kernels/scalar_mul_kernel.cpp
Labels: automerge, enhancement, op

#4003 add pixel shuffle
  oneflow/python/ops/nn_ops.py
  oneflow/python/test/ops/test_pixel_shuffle.py
  oneflow/python/test/ops/test_pixel_shufflev2.py
Labels: automerge, enhancement, op, python

#4014 Remove redundant `pack_size` in GenericLauncher
  oneflow/core/cuda/elementwise.cuh
Labels: automerge, bug, system

#4015 Add flatten/squeeze/expand_dims to auto mixed precision clear list and use reshape instead of reshape_like to do reshape grad computation
  oneflow/core/job_rewriter/auto_mixed_precision_lists.cpp
  oneflow/user/ops/reshape_op.cpp
Labels: automerge, enhancement, op

#3952 userop and general pr templates added
  .github/PULL_REQUEST_TEMPLATE/general_template.md
  .github/PULL_REQUEST_TEMPLATE/op_template.md
Labels: automerge, ci, documentation

#4018 Fix python cfg error bug
  oneflow/python/framework/c_api_util.py
  oneflow/python/framework/job_build_and_infer_cfg_error.py
  oneflow/python/framework/job_build_and_infer_error.py
Labels: automerge, bug, system

#3990 Dev oneflow ones
  oneflow/python/ops/array_ops.py
  oneflow/python/test/ops/test_ones.py
Labels: automerge, enhancement, op, python

#4022 Allow to keep oneflow_worker log in distributed CI
  ci/test/distributed_run.py
  oneflow/python/deprecated/init_cluster_env.py
Labels: automerge, ci, enhancement

#4023 Fix eager test_resume_training test
  oneflow/api/python/framework/framework.h
  oneflow/api/python/op/op_mgr.h
  oneflow/python/framework/compiler.py
  oneflow/python/framework/session_util.py
  oneflow/python/test/ops/test_checkpoint.py
Labels: automerge, bug, system

#4026 Make oneflow worker docker stay alive for 6 hours
  ci/test/distributed_run.py
Labels: automerge, ci, enhancement

#4012 add kldivloss
  oneflow/python/ops/nn_ops.py
  oneflow/python/test/ops/test_KLDivloss.py
Labels: automerge, enhancement, op, python

#4028 Upload log of distributed CI
  .github/workflows/test.yml
  .gitignore
  ci/test/distributed_run.py
Labels: automerge, ci, enhancement

#4027 Refactor gpu_atomic_add
  oneflow/core/cuda/atomic.cuh
  oneflow/core/kernel/batch_gather_kernel_util.cu
  oneflow/core/kernel/gather_kernel_util.cu
  oneflow/core/kernel/kernel_util.cu
  oneflow/core/kernel/kernel_util.cuh
  oneflow/core/kernel/square_sum_kernel_util.cpp
  oneflow/core/kernel/square_sum_kernel_util.cu
  oneflow/core/kernel/unsorted_segment_sum_kernel_util.cu
  oneflow/core/kernel/util/cuda_kernel_util.h
  oneflow/user/kernels/count_not_finite_kernel.cu
  oneflow/user/kernels/dim_gather_kernel_util.h
  oneflow/user/kernels/layer_norm_gpu_kernel.cu
  oneflow/user/kernels/model_update_kernel_util.cu
  oneflow/user/kernels/nd_index_slice_kernels.cu
  oneflow/user/kernels/softmax_kernel_util.cpp
  oneflow/user/kernels/upsample_kernel.cu
Labels: automerge, enhancement, op, refactor

#4020 Add implementation of InstanceNorm2D op
  oneflow/python/ops/nn_ops.py
  oneflow/python/test/ops/test_instance_norm_2d_op.py
Labels: automerge, feature, op

#4031 Fix CI wrong cmd when printing failed cmd due to shadowed var
  ci/test/parallel_run.py
Labels: automerge, bug, ci

#4024 Dev bcewithlogits loss
  oneflow/python/ops/nn_ops.py
  oneflow/python/test/ops/test_bce_loss.py
  oneflow/python/test/ops/test_bce_with_logits_loss.py
Labels: automerge, enhancement, op, python

#3995 change sbp order value for layer norm
  oneflow/core/operator/operator.cpp
Labels: automerge, bug, system

#3932 Tidy up op_conf.proto
  cmake/cfg.cmake
  oneflow/core/job/initializer_conf.proto
  oneflow/core/job/job_conf.proto
  oneflow/core/job/learning_rate_schedule_conf.proto
  oneflow/core/job/placement.proto
  oneflow/core/job/regularizer_conf.proto
  oneflow/core/operator/op_conf.proto
  oneflow/python/benchmarks/cnn_benchmark/vgg_model.py
  oneflow/python/deprecated/initializer_util.py
  oneflow/python/ops/data_ops.py
  oneflow/python/ops/get_variable.py
  oneflow/python/ops/initializer_util.py
  oneflow/python/ops/layers.py
  oneflow/python/ops/optimizer.py
  oneflow/python/ops/prelu.py
  oneflow/python/ops/regularizer_util.py
  oneflow/python/test/customized/ccrelu_alexnet.py
  oneflow/python/test/models/alexnet.py
  oneflow/python/test/models/alexnet_with_unpack.py
  oneflow/python/test/models/test_bert.py
  oneflow/python/test/models/vgg16.py
Labels: automerge, op, purge

#4030 Make `MaxWithLogThreshold` and `SafeLog` header only
  oneflow/core/kernel/kernel_util.cuh
  oneflow/core/kernel/sparse_cross_entropy_kernel_util.cu
  oneflow/core/kernel/util/cuda_kernel_util.cu
  oneflow/core/kernel/util/cuda_kernel_util.h
  oneflow/user/kernels/sparse_cross_entropy_kernel_util.cu
Labels: automerge, enhancement, op, refactor

#4036 Disable CUDA_SEPARABLE_COMPILATION
  CMakeLists.txt
Labels: automerge, build, enhancement

#4035 Dev rm old tanh
  oneflow/core/kernel/kernel_util.cpp
  oneflow/core/kernel/kernel_util.cu
  oneflow/core/kernel/kernel_util.h
  oneflow/core/kernel/util/cuda_dnn_interface.cu
  oneflow/core/kernel/util/cuda_dnn_interface.h
  oneflow/core/kernel/util/host_dnn_interface.cpp
  oneflow/core/kernel/util/host_dnn_interface.h
  oneflow/python/onnx/onnx_opset/math.py
  oneflow/python/ops/math_ops.py
  oneflow/python/ops/math_unary_elementwise_ops.py
  oneflow/python/test/ops/test_unary_elementwise_ops.py
  oneflow/python/test/xrt/test_tanh_grad.py
  oneflow/user/kernels/tanh_kernel.cpp
  oneflow/user/ops/math_unary_elementwise_seq.h
  oneflow/user/ops/tanh_op.cpp
Labels: automerge, bug, op

#4021 Migrate argwhere to user op
  oneflow/core/framework/op_kernel.cpp
  oneflow/core/framework/user_op_hob.cpp
  oneflow/core/framework/user_op_hob.h
  oneflow/core/kernel/arg_where_kernel.cpp
  oneflow/core/kernel/arg_where_kernel_util.cpp
  oneflow/core/kernel/arg_where_kernel_util.cu
  oneflow/core/kernel/arg_where_kernel_util.h
  oneflow/core/kernel/kernel.proto
  oneflow/core/operator/arg_where_op.cpp
  oneflow/core/operator/arg_where_op_util.cpp
  oneflow/core/operator/arg_where_op_util.h
  oneflow/core/operator/op_conf.proto
  oneflow/python/ops/array_ops.py
  oneflow/python/test/ops/test_argwhere.py
  oneflow/user/kernels/arg_where_kernel.cpp
  oneflow/user/kernels/arg_where_kernel_util.cpp
  oneflow/user/kernels/arg_where_kernel_util.cu
  oneflow/user/kernels/arg_where_kernel_util.h
  oneflow/user/ops/arg_where_op.cpp
Labels: automerge, bug, enhancement, op

#4025 slice support empty blob
  oneflow/python/test/ops/test_slice_v2.py
  oneflow/user/ops/slice_op.cpp
Labels: automerge, enhancement, op

#4038 add deprecate api optimizer.PolynomialSchduler
  oneflow/python/ops/optimizer.py
Labels: api, automerge, enhancement, python

#3777 Reflection pad2d op
  oneflow/python/ops/pad.py
  oneflow/python/test/ops/test_reflection_pad2d.py
  oneflow/user/kernels/reflection_pad2d_kernel.cpp
  oneflow/user/kernels/reflection_pad2d_kernel_util.cpp
  oneflow/user/kernels/reflection_pad2d_kernel_util.cu
  oneflow/user/kernels/reflection_pad2d_kernel_util.h
  oneflow/user/ops/reflection_pad2d_op.cpp
Labels: automerge, enhancement, op

#4032 Job desc with symbol
  oneflow/api/python/symbol/job_conf_symbol.cpp
  oneflow/api/python/symbol/symbol.cpp
  oneflow/core/eager/eager_oneflow.cpp
  oneflow/core/eager/eager_symbol_storage.h
  oneflow/core/job/job_desc.cpp
  oneflow/core/job/job_desc.h
  oneflow/core/vm/symbol_storage.cpp
  oneflow/core/vm/symbol_storage.h
  oneflow/python/eager/vm_util.py
  oneflow/python/framework/scope_symbol.py
Labels: automerge, enhancement, system

#4040 Scope with symbol
  oneflow/api/python/framework/foreign_callback.cpp
  oneflow/api/python/op/op_mgr.h
  oneflow/api/python/symbol/scope_symbol.cpp
  oneflow/api/python/symbol/symbol.cpp
  oneflow/core/eager/eager_oneflow.cpp
  oneflow/core/eager/eager_symbol_storage.h
  oneflow/core/eager/init_symbol_instruction_type_test.cpp
  oneflow/core/eager/opkernel_instruction_type_test.cpp
  oneflow/core/eager/transport_blob_instruction_type_test.cpp
  oneflow/core/job/foreign_callback.h
  oneflow/core/job/job_build_and_infer_ctx.cpp
  oneflow/core/job/scope.cpp
  oneflow/core/job/scope.h
  oneflow/core/job_rewriter/generate_backward_and_optimizer_op_confs.cpp
  oneflow/core/operator/distribute_add_op.cpp
  oneflow/core/operator/distribute_clone_op.cpp
  oneflow/core/operator/distribute_concat_op.cpp
  oneflow/core/operator/distribute_split_op.cpp
  oneflow/core/operator/image_decoder_random_crop_resize_op.cpp
  oneflow/core/operator/operator.cpp
  oneflow/core/vm/symbol_storage.cpp
  oneflow/core/vm/symbol_storage.h
  oneflow/python/eager/interpreter_callback.py
  oneflow/python/eager/op_executor.py
  oneflow/python/eager/opkernel_object.py
  oneflow/python/eager/symbol_storage.py
  oneflow/python/eager/vm_util.py
  oneflow/python/experimental/name_scope.py
  oneflow/python/framework/compiler.py
  oneflow/python/framework/distribute_context.py
  oneflow/python/framework/parallel_conf_util.py
  oneflow/python/framework/placement_context.py
  oneflow/python/framework/placement_util.py
  oneflow/python/framework/python_callback.py
  oneflow/python/framework/scope_util.py
  oneflow/python/ops/__init__.py
Labels: automerge, enhancement, system

#4042 optimize link time
  cmake/cfg.cmake
Labels: automerge, enhancement, tooling

#4039 User op dim_gather support dynamic input and index
  oneflow/python/test/ops/test_dim_gather_dynamic.py
  oneflow/user/ops/dim_gather_op.cpp
Labels: automerge, enhancement, op

#4033 Generic unfold kernel implementation
  oneflow/user/kernels/unfold_kernel.cpp
  oneflow/user/kernels/unfold_kernel_util.cpp
  oneflow/user/kernels/unfold_kernel_util.cu
  oneflow/user/kernels/unfold_kernel_util.h
  oneflow/user/ops/unfold_op.cpp
Labels: enhancement, op

#4046 Remove col_id
  oneflow/core/actor/acc_compute_actor.cpp
  oneflow/core/actor/accumulate_compute_actor.cpp
  oneflow/core/actor/accumulate_compute_actor.h
  oneflow/core/actor/actor.cpp
  oneflow/core/actor/actor.h
  oneflow/core/actor/decode_compute_actor.cpp
  oneflow/core/actor/decode_compute_actor.h
  oneflow/core/kernel/decode_ofrecord_kernel.cpp
  oneflow/core/kernel/decode_ofrecord_kernel.h
  oneflow/core/register/register.cpp
  oneflow/core/register/register.h
Labels: purge, system

#4045 Optimize dynamic loss scale parameters
  oneflow/core/job/job_conf.proto
  oneflow/python/ops/optimizer.py
  oneflow/user/kernels/dynamic_loss_scale_schedule_kernel.cpp
  oneflow/user/kernels/dynamic_loss_scale_schedule_kernel.cu
Labels: automerge, enhancement, system

#3764 Quantization aware training releated ops
  oneflow/core/cuda/atomic.cuh
  oneflow/python/ops/quantize_ops.py
  oneflow/python/test/ops/test_quantize_op.py
  oneflow/user/kernels/fake_quantization_kernel.cpp
  oneflow/user/kernels/fake_quantization_kernel.cu
  oneflow/user/kernels/min_max_observer_kernel.cpp
  oneflow/user/kernels/min_max_observer_kernel.cu
  oneflow/user/kernels/moving_average_min_max_observer_kernel.cpp
  oneflow/user/kernels/moving_average_min_max_observer_kernel.cu
  oneflow/user/ops/fake_quantization_op.cpp
  oneflow/user/ops/min_max_observer_op.cpp
  oneflow/user/ops/moving_average_min_max_observer_op.cpp
Labels: automerge, feature, op

#4048 Add err info for ncclGroupEnd check
  oneflow/core/job/collective_boxing_executor.cpp
Labels: automerge, enhancement, system

#4047 support eager empty blob
  oneflow/core/kernel/kernel.cpp
  oneflow/core/kernel/kernel_helper.cpp
  oneflow/core/kernel/kernel_helper.h
  oneflow/core/kernel/user_kernel.cpp
Labels: automerge, bug, system

#4050 Finetune cfg tool
  oneflow/core/common/error.cpp
  tools/cfg/template/template.cfg.h
  tools/cfg/template/template.cfg.pybind.cpp
Labels: automerge, enhancement, tooling

#4056 Add docs on installing legacy versions of oneflow
  README.md
Labels: documentation, enhancement, system

#4052 Add InstanceNorm 1d & 3d implementation
  oneflow/python/ops/nn_ops.py
  oneflow/python/test/ops/test_instance_norm_op.py
Labels: automerge, feature, op

#4058 Optimize softmax cuda kernel
  oneflow/python/ops/nn_ops.py
  oneflow/python/test/ops/test_softmax.py
  oneflow/user/kernels/softmax_kernel.cu
Labels: enhancement, op

#4061 initial fix
  oneflow/user/kernels/arg_where_kernel_util.cu
Labels: automerge, bug, op

#4064 Add nvtx range and thread naming
  CMakeLists.txt
  oneflow/core/job/oneflow.cpp
  oneflow/core/kernel/kernel.cpp
  oneflow/core/profiler/profiler.cpp
  oneflow/core/profiler/profiler.h
  oneflow/core/thread/cpu_thread.cpp
  oneflow/core/thread/gpu_thread.cpp
Labels: automerge, feature, system

#3611 Dev in top k
  oneflow/python/ops/math_ops.py
  oneflow/python/test/ops/test_in_top_k.py
  oneflow/python/test/ops/test_polyval.py
  oneflow/user/kernels/in_top_k_kernel.cpp
  oneflow/user/kernels/in_top_k_kernel_util.cpp
  oneflow/user/kernels/in_top_k_kernel_util.cu
  oneflow/user/kernels/in_top_k_kernel_util.h
  oneflow/user/ops/in_top_k_op.cpp
Labels: automerge, enhancement, op
