Repository Oneflow-Inc/oneflow, pull requests merged in 2020-08, with the labels that each got.

#3347 add automerge bot
  .github/workflows/automerge.yml
Labels: automerge

#3283 CopyBodyFromNdarray
  oneflow/core/register/ofblob.h
  oneflow/python/framework/ofblob.py
  oneflow/python/oneflow_internal.e.h
Labels: automerge

#3380 Revert "fix building error and warning in gcc10 (#3361)"
  oneflow/core/common/cached_object_msg_allocator.h
  oneflow/core/common/shared_or_plain.h
Labels: automerge

#3382 Refine gcc 10 support
  oneflow/core/common/cached_object_msg_allocator.h
  oneflow/core/common/shared_or_plain.h
Labels: automerge

#3386 fix some bugs in onnx module
  ci/test/onnx_export_model_test.sh
  oneflow/python/onnx/graph.py
  oneflow/python/onnx/onnx_opset/nn.py
  oneflow/python/test/onnx/nodes/test_gather_nd.py
  oneflow/python/test/onnx/nodes/test_pooling.py
  oneflow/python/test/onnx/util.py
Labels: automerge

#3377 refine XLA build
  cmake/third_party.cmake
  cmake/third_party/grpc.cmake
  cmake/third_party/header_index/protobuf_xla_headers.txt
  cmake/third_party/protobuf.cmake
  cmake/third_party/tensorflow.cmake
  docker/package/manylinux/README.md
  tools/generate_header_list.py
Labels: automerge

#3389 Implementation of CheckPoint.save in eager
  oneflow/python/eager/op_executor.py
  oneflow/python/framework/check_point.py
  oneflow/python/framework/placement_util.py
  oneflow/python/framework/scope_util.py
  oneflow/python/framework/session_util.py
  oneflow/python/ops/get_variable.py
  oneflow/python/test/ops/test_model_io.py
Labels: automerge

#3391 Conv1d Conv3d
  oneflow/python/ops/layers.py
  oneflow/python/ops/nn_ops.py
  oneflow/python/test/ops/test_layers_conv1d.py
  oneflow/python/test/ops/test_layers_conv3d.py
  oneflow/python/test/ops/test_nn_conv1d.py
  oneflow/python/test/ops/test_nn_conv3d.py
Labels: automerge

#3413 Cleanup task_graph/node
  oneflow/core/graph/chain_graph.cpp
  oneflow/core/graph/task_graph.cpp
  oneflow/core/graph/task_graph.h
  oneflow/core/graph/task_node.cpp
  oneflow/core/graph/task_node.h
  oneflow/core/job/compiler.cpp
  oneflow/core/job/runtime.cpp
  oneflow/core/job/task.proto
Labels: automerge

#3423 Add parallel_desc for GenKernelConf and UserKernelInitContext
  oneflow/core/eager/opkernel_instruction_type.cpp
  oneflow/core/eager/opkernel_object.cpp
  oneflow/core/eager/opkernel_object.h
  oneflow/core/framework/op_kernel.h
  oneflow/core/graph/exec_graph.cpp
  oneflow/core/kernel/kernel.proto
  oneflow/core/kernel/user_kernel.cpp
  oneflow/core/operator/operator.cpp
  oneflow/core/operator/operator.h
  oneflow/core/operator/user_op.cpp
  oneflow/core/operator/user_op.h
Labels: automerge

#3424 backport fix for placement
  oneflow/python/framework/placement_context.py
  oneflow/python/framework/placement_util.py
Labels: automerge

#3430 rm warning when cuda is off
  cmake/oneflow.cmake
Labels: automerge

#3431 Dev bn ln cpu
  oneflow/python/ops/layers.py
  oneflow/python/ops/nn_ops.py
  oneflow/python/test/ops/test_batch_normalization.py
  oneflow/user/ops/math_binary_broadcast_ops.cpp
Labels: automerge

#3419 Add ofrecord_image_classification_reader
  oneflow/python/ops/user_data_ops.py
  oneflow/python/test/models/alexnet.py
  oneflow/user/data/ofrecord_image_classification_data_reader.h
  oneflow/user/data/ofrecord_image_classification_dataset.h
  oneflow/user/data/ofrecord_image_classification_parser.h
  oneflow/user/kernels/ofrecord_image_classification_reader_kernel.cpp
  oneflow/user/ops/ofrecord_image_classification_reader_op.cpp
Labels: automerge

#3443 Add typing.List global function return annotation
  oneflow/python/framework/typing_util.py
  oneflow/python/test/ops/test_global_function_signature.py
Labels: automerge

#3442 image.random_crop
  oneflow/python/ops/user_data_ops.py
  oneflow/user/image/random_crop_generator.cpp
  oneflow/user/kernels/image_preprocess_kernels.cpp
  oneflow/user/kernels/ofrecord_decoder_kernels.cpp
  oneflow/user/kernels/random_crop_kernel_state.cpp
  oneflow/user/kernels/random_crop_kernel_state.h
  oneflow/user/ops/image_preprocess_ops.cpp
Labels: automerge

#3451 Fix InferLogicalOutBlobDescs
  oneflow/core/operator/operator.cpp
Labels: automerge

#3456 Fix keep_header_only name
  oneflow/core/job_rewriter/add_keep_header_only_op_conf.cpp
Labels: automerge

#3399 Dev add oneflow typing collection
  oneflow/python/framework/typing.py
  oneflow/python/framework/typing_util.py
  oneflow/python/test/ops/test_global_function_signature.py
Labels: automerge

#3433 Dev Layer Norm CPU and Batch Norm CPU training
  oneflow/core/job/job_build_and_infer_ctx.cpp
  oneflow/python/ops/layers.py
  oneflow/python/ops/nn_ops.py
  oneflow/python/ops/reduce_ops.py
  oneflow/python/test/ops/test_batch_normalization.py
  oneflow/python/test/ops/test_layer_norm.py
  oneflow/python/test/ops/test_moments.py
Labels: automerge

#3444 Refactor slice op
  oneflow/python/ops/array_ops.py
  oneflow/python/test/ops/test_reverse.py
  oneflow/python/test/ops/test_slice_v2.py
  oneflow/user/kernels/slice_kernel.cpp
  oneflow/user/kernels/slice_kernel.cu
  oneflow/user/kernels/slice_util.cpp
  oneflow/user/kernels/slice_util.cu
  oneflow/user/kernels/slice_util.h
  oneflow/user/ops/slice_op.cpp
  oneflow/user/ops/slice_util.h
Labels: automerge

#3464 add include head file for compile pass
  oneflow/core/common/switch_func.h
  oneflow/core/ndarray/xpu_ndarray_base.h
Labels: automerge

#3469 larger rol for conv 2d cpu
  oneflow/python/test/ops/test_nn_conv2d_padding_dynamic.py
Labels: automerge

#3450 Refactor image resize
  oneflow/python/benchmarks/coco_data_load/coco_data_loader.py
  oneflow/python/ops/user_data_ops.py
  oneflow/python/test/customized/new_data_pre.py
  oneflow/python/test/ops/test_image_resize.py
  oneflow/python/test/ops/test_image_target_resize.py
  oneflow/python/test/ops/test_object_bbox_flip.py
  oneflow/python/test/ops/test_object_bbox_scale.py
  oneflow/python/test/ops/test_object_segm_poly_flip.py
  oneflow/python/test/ops/test_object_segm_poly_to_mask.py
  oneflow/user/image/image_util.cpp
  oneflow/user/image/image_util.h
  oneflow/user/kernels/image_object_preprocess_kernels.cpp
  oneflow/user/kernels/image_preprocess_kernels.cpp
  oneflow/user/kernels/image_resize_kernels.cpp
  oneflow/user/ops/image_preprocess_ops.cpp
  oneflow/user/ops/image_resize_ops.cpp
Labels: automerge

#3475 Dev Refactor Test Model_Io
  oneflow/python/test/ops/test_model_io.py
Labels: automerge

#3476 bert cpu
  oneflow/python/test/models/test_bert.py
Labels: automerge

#3226 manipulate lazy interface blobs in eager
  oneflow/core/eager/blob_instruction_type.cpp
  oneflow/core/eager/blob_instruction_type.h
  oneflow/core/eager/blob_object.h
  oneflow/core/eager/cpu_blob_instruction_type.cpp
  oneflow/core/eager/cuda_blob_instruction_type.cpp
  oneflow/core/eager/lazy_ref_blob_object.h
  oneflow/core/operator/input_op.cpp
  oneflow/core/operator/output_op.cpp
  oneflow/core/operator/return_op.cpp
  oneflow/core/register/register_manager.cpp
  oneflow/core/register/register_manager.h
  oneflow/core/vm/object_instruction_type.cpp
  oneflow/python/eager/vm_util.py
  oneflow/python/experimental/interface_op_read_and_write.py
  oneflow/python/framework/c_api_util.py
  oneflow/python/framework/compile_context.py
  oneflow/python/framework/dtype.py
  oneflow/python/framework/push_util.py
  oneflow/python/framework/remote_blob.py
  oneflow/python/framework/session_util.py
  oneflow/python/oneflow_internal.h
  oneflow/python/test/ops/test_interface_op_read_and_write.py
Labels: automerge

#3305 Dev add docstring2
  oneflow/python/experimental/name_scope.py
  oneflow/python/framework/distribute.py
  oneflow/python/framework/placement_util.py
  oneflow/python/ops/data_ops.py
  oneflow/python/ops/initializer_util.py
  oneflow/python/ops/math_ops.py
  oneflow/python/ops/user_op_builder.py
Labels: automerge

#3490 Remove CUDA driver version from log
  oneflow/core/job/version.cpp
Labels: automerge

#3492 py fmt respects gitignore
  .github/workflows/test.yml
  ci/check/lintutils.py
  ci/check/run_clang_format.py
  ci/check/run_py_format.py
  cmake/oneflow.cmake
  docs/source/conf.py
  oneflow/init.py
  setup.py
  tools/clean_generated_api.py
  tools/generate_header_list.py
  tools/generate_oneflow_api.py
  tools/generate_oneflow_symbols_export_file.py
Labels: automerge

#3491 create symlink instead of copying python files
  .gitignore
  cmake/oneflow.cmake
Labels: automerge

#3479 Chain circle color print dot graph
  oneflow/core/graph/chain_graph.cpp
  oneflow/core/graph/graph.h
Labels: automerge

#3488 conv2d cpu support groups
  oneflow/python/ops/nn_ops.py
  oneflow/python/test/ops/test_nn_conv2d.py
Labels: automerge

#3494 move generated python files into oneflow/python_gen
  cmake/oneflow.cmake
  oneflow/init.py
  oneflow/python/framework/config_util.py
  oneflow/python/framework/placement_util.py
  oneflow/python/framework/session_util.py
  oneflow/python/framework/sysconfig.py
Labels: automerge

#3466 Dev boxing log
  oneflow/core/graph/boxing/b21_sub_task_graph_builder.cpp
  oneflow/core/graph/boxing/b21_sub_task_graph_builder.h
  oneflow/core/graph/boxing/boxing_logger.cpp
  oneflow/core/graph/boxing/boxing_logger.h
  oneflow/core/graph/boxing/chain_sub_task_graph_builder.cpp
  oneflow/core/graph/boxing/chain_sub_task_graph_builder.h
  oneflow/core/graph/boxing/collective_boxing_sub_task_graph_builder.cpp
  oneflow/core/graph/boxing/collective_boxing_sub_task_graph_builder.h
  oneflow/core/graph/boxing/naive_b2b_sub_task_graph_builder.cpp
  oneflow/core/graph/boxing/naive_b2b_sub_task_graph_builder.h
  oneflow/core/graph/boxing/one_to_one_sub_task_graph_builder.cpp
  oneflow/core/graph/boxing/one_to_one_sub_task_graph_builder.h
  oneflow/core/graph/boxing/slice_boxing_sub_task_graph_builder.cpp
  oneflow/core/graph/boxing/slice_boxing_sub_task_graph_builder.h
  oneflow/core/graph/boxing/sub_task_graph_builder.h
  oneflow/core/graph/boxing/sub_task_graph_builder_status_util.cpp
  oneflow/core/graph/boxing/sub_task_graph_builder_status_util.h
  oneflow/core/graph/boxing/sub_task_graph_builder_util.h
  oneflow/core/graph/boxing/to_interface_sub_task_graph_builder.cpp
  oneflow/core/graph/boxing/to_interface_sub_task_graph_builder.h
  oneflow/core/graph/task_graph.cpp
  oneflow/core/graph/task_graph.h
Labels: automerge

#3483 add api docs
  docker/ci/test/requirements.txt
  docs/source/conf.py
  oneflow/python/ops/layers.py
  oneflow/python/ops/math_ops.py
  oneflow/python/ops/nn_ops.py
Labels: automerge

#3507 Fix UserOpConfWrapper::has_input/has_output
  oneflow/core/framework/user_op_conf.cpp
Labels: automerge, bug

#3508 fix optimizer copy-paste bug
  oneflow/python/ops/optimizer.py
Labels: automerge

#3513 Fix the bug of using op_module_builder in namespace scope
  oneflow/python/ops/nn_ops.py
  oneflow/python/ops/user_data_ops.py
  oneflow/python/ops/user_op_builder.py
  oneflow/python/test/ops/test_user_op_module.py
Labels: automerge

#3517 pybind11 integration
  CMakeLists.txt
  cmake/oneflow.cmake
  cmake/pybind11.cmake
  cmake/third_party/gflags.cmake
  cmake/third_party/googletest.cmake
  oneflow/api/python/init.cpp
  oneflow/init.py
  oneflow/python/framework/c_api_util.py
  oneflow/python/oneflow_internal.h
  setup.py
Labels: automerge

#3474 flat ErrorProto error_type
  oneflow/core/common/error.cpp
  oneflow/core/common/error.h
  oneflow/core/common/error.proto
  oneflow/core/framework/to_string.cpp
  oneflow/core/graph/boxing/b21_sub_task_graph_builder.cpp
  oneflow/core/graph/boxing/chain_sub_task_graph_builder.cpp
  oneflow/core/graph/boxing/collective_boxing_sub_task_graph_builder.cpp
  oneflow/core/graph/boxing/naive_b2b_sub_task_graph_builder.cpp
  oneflow/core/graph/boxing/one_to_one_sub_task_graph_builder.cpp
  oneflow/core/graph/boxing/slice_boxing_sub_task_graph_builder.cpp
  oneflow/core/graph/boxing/sub_task_graph_builder_util.cpp
  oneflow/core/graph/boxing/to_interface_sub_task_graph_builder.cpp
  oneflow/core/job/job_build_and_infer_ctx.cpp
  oneflow/core/job/job_build_and_infer_ctx_mgr.cpp
  oneflow/python/oneflow_internal_helper.h
Labels: enhancement

#3522 upgrad to pybind11 master and pass exe path
  ci/check/run_license_format.py
  cmake/oneflow.cmake
  cmake/pybind11.cmake
  cmake/python.cmake
Labels: automerge
