Repository Oneflow-Inc/oneflow, pull requests merged in 2021-03, with the labels that each got.

#4279 add dtype
  oneflow/api/python/deprecated.cpp
  oneflow/api/python/framework/dtype.cpp
  oneflow/core/framework/dtype.cpp
  oneflow/core/framework/dtype.h
  oneflow/init.py
  oneflow/python/eager/eager_blob_util.py
  oneflow/python/eager/op_executor.py
  oneflow/python/experimental/dynamic_binary_split_concat_op.py
  oneflow/python/experimental/unique_op.py
  oneflow/python/framework/check_point_v2.py
  oneflow/python/framework/dtype.py
  oneflow/python/framework/function_util.py
  oneflow/python/framework/input_blob_def.py
  oneflow/python/framework/ofblob.py
  oneflow/python/framework/remote_blob.py
  oneflow/python/framework/typing.py
  oneflow/python/onnx/util.py
  oneflow/python/ops/array_ops.py
  oneflow/python/ops/combined_margin_loss.py
  oneflow/python/ops/constant_op.py
  oneflow/python/ops/count_not_finite.py
  oneflow/python/ops/data_ops.py
  oneflow/python/ops/get_variable.py
  oneflow/python/ops/initializer_util.py
  oneflow/python/ops/math_ops.py
  oneflow/python/ops/one_hot.py
  oneflow/python/ops/pad.py
  oneflow/python/ops/partial_fc_sample.py
  oneflow/python/ops/random_ops.py
  oneflow/python/ops/tensor_buffer_ops.py
  oneflow/python/ops/tensor_list_ops.py
  oneflow/python/ops/user_data_ops.py
  oneflow/python/ops/user_op_builder.py
Labels: automerge, feature, system

#4289 runtime_blob_shape_infer_helper fill logical blob desc
  oneflow/core/job/oneflow.cpp
  oneflow/core/kernel/kernel.proto
  oneflow/core/kernel/runtime_blob_shape_infer_helper.cpp
  oneflow/core/kernel/runtime_blob_shape_infer_helper.h
  oneflow/core/operator/operator.cpp
Labels: automerge, enhancement, system

#4184 Mig instruction build api about op atttribute
  oneflow/api/python/framework/instructions_builder.cpp
  oneflow/core/framework/dtype.h
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/framework/instructions_builder.h
  oneflow/init.py
  oneflow/python/eager/op_executor.py
  oneflow/python/eager/vm_util.py
Labels: automerge, eager, enhancement, system

#4269 New multi machine ci
  ci/test/2node_op_test.sh
  ci/test/distributed_run.py
  ci/test/parallel_run.py
  oneflow/core/control/ctrl_bootstrap.proto
  oneflow/core/job/env_desc.cpp
  oneflow/core/job/env_desc.h
  oneflow/core/job/env_global_objects_scope.cpp
  oneflow/core/job/resource_desc.cpp
  oneflow/core/job/resource_desc.h
  oneflow/python/deprecated/init_cluster_env.py
  oneflow/python/framework/env_util.py
  oneflow/python/framework/unittest.py
  oneflow/python/test/README.md
Labels: automerge, feature, test

#4187 Mig instruction build api other
  oneflow/api/python/framework/instructions_builder.cpp
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/framework/instructions_builder.h
  oneflow/python/eager/boxing_util.py
  oneflow/python/eager/eager_blob_util.py
  oneflow/python/eager/op_executor.py
  oneflow/python/eager/vm_util.py
  oneflow/python/experimental/interface_op_read_and_write.py
  oneflow/python/framework/push_util.py
  oneflow/python/framework/register_class_method_util.py
Labels: automerge, eager, enhancement

#4293 Dev modify api maybe return
  oneflow/api/python/env/env.h
  oneflow/api/python/framework/eager_blob_util.cpp
  oneflow/api/python/framework/op_arg_util.cpp
Labels: api, automerge, enhancement, system

#4291 Remove dynamic binary split/concat op
  oneflow/core/kernel/dynamic_binary_split_concat_kernel.cpp
  oneflow/core/operator/dynamic_binary_split_concat_op.cpp
  oneflow/core/operator/op_conf.proto
  oneflow/python/experimental/dynamic_binary_split_concat_op.py
  oneflow/python/test/ops/test_dynamic_binary.py
Labels: automerge, op, purge

#4226 DeviceId/StreamId/TaskId part 1
  oneflow/core/common/id_util.h
  oneflow/core/device/cpu_stream_index.cpp
  oneflow/core/device/cpu_stream_index.h
  oneflow/core/device/cuda_stream_index.cpp
  oneflow/core/device/cuda_stream_index.h
  oneflow/core/device/stream_index.h
  oneflow/core/graph/boxing/collective_boxing_sub_task_graph_builder.cpp
  oneflow/core/graph/boxing/naive_b2p_sub_task_graph_builder.cpp
  oneflow/core/graph/boxing/slice_boxing_sub_task_graph_builder.cpp
  oneflow/core/graph/copy_task_node.cpp
  oneflow/core/graph/id_serialization.cpp
  oneflow/core/graph/id_serialization.h
  oneflow/core/graph/logical_node.h
  oneflow/core/graph/task_graph.cpp
  oneflow/core/graph/task_graph.h
  oneflow/core/graph/task_id_generator.h
  oneflow/core/graph/task_node.cpp
  oneflow/core/graph/task_node.h
  oneflow/core/graph_impl/logical_node.cpp
  oneflow/core/job/id_manager.cpp
  oneflow/core/job/id_manager.h
  oneflow/core/job/id_manager_test.cpp
  oneflow/core/job/thrd_id_generator.cpp
  oneflow/core/job/thrd_id_generator.h
  oneflow/core/thread/thread_manager.cpp
  oneflow/core/thread/thread_manager.h
Labels: automerge, feature, refactor, system

#4197 add autograd
  oneflow/api/python/autograd/autograd.cpp
  oneflow/core/autograd/autograd_engine.h
  oneflow/core/framework/tensor_tuple.cpp
  oneflow/core/framework/tensor_tuple.h
Labels: automerge, feature, system

#4283 Remove AreaId
  oneflow/core/graph/accumulate_compute_task_node.cpp
  oneflow/core/graph/boxing/collective_boxing_sub_task_graph_builder.cpp
  oneflow/core/graph/boxing/naive_b2p_sub_task_graph_builder.cpp
  oneflow/core/graph/boxing_identity_task_node.cpp
  oneflow/core/graph/boxing_identity_task_node.h
  oneflow/core/graph/boxing_zeros_task_node.cpp
  oneflow/core/graph/boxing_zeros_task_node.h
  oneflow/core/graph/chain_act_graph.cpp
  oneflow/core/graph/collective_boxing_pack_task_node.cpp
  oneflow/core/graph/collective_boxing_pack_task_node.h
  oneflow/core/graph/collective_boxing_task_node.cpp
  oneflow/core/graph/collective_boxing_task_node.h
  oneflow/core/graph/collective_boxing_unpack_task_node.cpp
  oneflow/core/graph/collective_boxing_unpack_task_node.h
  oneflow/core/graph/logical_node.h
  oneflow/core/graph/plan_task_graph.h
  oneflow/core/graph/slice_boxing_task_node.cpp
  oneflow/core/graph/task_graph.cpp
  oneflow/core/graph/task_graph.h
  oneflow/core/graph/task_node.cpp
  oneflow/core/graph/task_node.h
  oneflow/core/graph_impl/acc_compute_task_node.cpp
  oneflow/core/graph_impl/logical_node.cpp
  oneflow/core/graph_impl/pack_compute_task_node.cpp
  oneflow/core/graph_impl/repeat_compute_task_node.cpp
  oneflow/core/graph_impl/ssp_variable_proxy_task_node.cpp
  oneflow/core/graph_impl/unpack_compute_task_node.cpp
  oneflow/core/job/task.proto
Labels: automerge, purge, refactor, system

#4292 Add parallel_conf_signature
  cmake/cfg.cmake
  oneflow/core/job/parallel_conf_signature.proto
  oneflow/core/kernel/runtime_blob_shape_infer_helper.cpp
  oneflow/core/operator/op_attribute.proto
  oneflow/core/operator/operator.cpp
Labels: automerge, enhancement, system

#4306 refactor DeterminedTensor to TensorIf<DerivedT>
  oneflow/api/python/framework/tensor.cpp
  oneflow/core/framework/tensor.cpp
  oneflow/core/framework/tensor.h
  oneflow/core/framework/tensor_impl.cpp
  oneflow/core/framework/tensor_impl.h
Labels: automerge, enhancement, system

#4303 Registration for creating thread
  oneflow/core/thread/cpu_thread.cpp
  oneflow/core/thread/gpu_thread.cpp
  oneflow/core/thread/thread_manager.cpp
  oneflow/core/thread/thread_manager.h
Labels: automerge, enhancement, system

#4299 Yangfei/zero pad2d
  oneflow/python/ops/pad.py
  oneflow/python/test/ops/test_zero_pad2d.py
Labels: automerge, enhancement, op, python

#4305 fix bn_add_relu LogicalTensorDescInferFn
  oneflow/user/ops/normalization_op.cpp
Labels: automerge, enhancement, op

#4304 Remove accumulate
  oneflow/core/actor/acc_compute_actor.cpp
  oneflow/core/actor/acc_tick_compute_actor.cpp
  oneflow/core/actor/accumulate_compute_actor.cpp
  oneflow/core/actor/accumulate_compute_actor.h
  oneflow/core/graph/acc_tick_compute_task_node.cpp
  oneflow/core/graph/acc_tick_compute_task_node.h
  oneflow/core/graph/accumulate_compute_task_node.cpp
  oneflow/core/graph/accumulate_compute_task_node.h
  oneflow/core/graph_impl/acc_compute_task_node.cpp
  oneflow/core/kernel/accumulate_kernel.cpp
  oneflow/core/kernel/accumulate_kernel.h
  oneflow/core/operator/acc_tick_op.h
  oneflow/core/operator/accumulate_op.cpp
  oneflow/core/operator/accumulate_op.h
  oneflow/core/operator/op_conf.proto
Labels: automerge, purge, refactor, system

#4195 Mig logical and pyhsical run
  oneflow/api/python/framework/instructions_builder.cpp
  oneflow/api/python/framework/python_interpreter_util.cpp
  oneflow/api/python/framework/session_util.cpp
  oneflow/api/python/vm/run_instruction.h
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/framework/instructions_builder.h
  oneflow/core/framework/object.h
  oneflow/core/framework/python_interpreter_util.cpp
  oneflow/core/framework/python_interpreter_util.h
  oneflow/core/framework/session_util.cpp
  oneflow/core/framework/session_util.h
  oneflow/init.py
  oneflow/python/eager/blob_cache.py
  oneflow/python/eager/boxing_util.py
  oneflow/python/eager/eager_blob_util.py
  oneflow/python/eager/interpreter_callback.py
  oneflow/python/eager/op_executor.py
  oneflow/python/eager/vm_util.py
  oneflow/python/experimental/interface_op_read_and_write.py
  oneflow/python/framework/check_point_v2.py
  oneflow/python/framework/compiler.py
  oneflow/python/framework/interpret_util.py
  oneflow/python/framework/push_util.py
  oneflow/python/framework/python_interpreter_util.py
  oneflow/python/framework/remote_blob.py
  oneflow/python/framework/scope_util.py
  oneflow/python/framework/session_context.py
  oneflow/python/framework/session_util.py
  oneflow/python/ops/__init__.py
  oneflow/python/ops/assign_op.py
  oneflow/python/ops/get_variable.py
  oneflow/python/ops/user_op_builder.py
Labels: automerge, eager, enhancement

#4311 Always infer data type
  oneflow/core/operator/device_tick_op.cpp
  oneflow/core/operator/dst_subset_tick_op.cpp
  oneflow/core/operator/operator.cpp
  oneflow/core/operator/sink_tick_op.cpp
  oneflow/core/operator/source_tick_op.cpp
  oneflow/core/operator/src_subset_tick_op.cpp
  oneflow/core/operator/tick_op.cpp
Labels: enhancement, op

#4202 Mig blob cache
  oneflow/api/python/framework/blob_cache.cpp
  oneflow/api/python/framework/blob_register.cpp
  oneflow/api/python/framework/eager_blob_util.cpp
  oneflow/api/python/framework/instructions_builder.cpp
  oneflow/api/python/of_api_registry.cpp
  oneflow/core/framework/blob_cache.cpp
  oneflow/core/framework/blob_cache.h
  oneflow/core/framework/blob_register.cpp
  oneflow/core/framework/blob_register.h
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/framework/instructions_builder.h
  oneflow/core/framework/object_storage.cpp
  oneflow/core/framework/op_arg_util.cpp
  oneflow/core/framework/session_util.cpp
  oneflow/init.py
  oneflow/python/eager/blob_cache.py
  oneflow/python/eager/blob_register.py
  oneflow/python/eager/boxing_util.py
  oneflow/python/eager/eager_blob_util.py
  oneflow/python/eager/interpreter_callback.py
  oneflow/python/eager/op_executor.py
  oneflow/python/experimental/interface_op_read_and_write.py
  oneflow/python/framework/check_point_v2.py
  oneflow/python/framework/interpret_util.py
  oneflow/python/framework/push_util.py
  oneflow/python/framework/register_class_method_util.py
  oneflow/python/framework/remote_blob.py
  oneflow/python/framework/session_util.py
  oneflow/python/ops/__init__.py
  oneflow/python/ops/get_variable.py
  oneflow/python/ops/user_op_builder.py
Labels: automerge, eager, enhancement

#4310 Xfjiang/fix optimizer compatibility
  oneflow/core/job/job_build_and_infer_ctx.cpp
  oneflow/core/job/job_conf.proto
  oneflow/core/job_rewriter/model_update_conf_compatible_pass.cpp
  oneflow/python/framework/function_util.py
Labels: automerge, bug, system

#4302 xrt infer_shape_pass fill logical_blob_desc, sbp, parallel_desc
  oneflow/core/graph/op_graph.cpp
  oneflow/core/graph/op_graph.h
  oneflow/core/job/job.proto
  oneflow/core/job_rewriter/dump_time_shape_and_blob_parallel_conf_pass.cpp
  oneflow/core/operator/op_conf.proto
  oneflow/xrt/launch_kernel.cpp
  oneflow/xrt/launch_op.cpp
  oneflow/xrt/passes/infer_shape_pass.cpp
  oneflow/xrt/passes/rebuild_job_pass.cpp
Labels: automerge, enhancement, system

#4314 add_bytes_in_dtype
  oneflow/api/python/framework/dtype.cpp
  oneflow/core/framework/dtype.cpp
  oneflow/core/framework/dtype.h
Labels: automerge, enhancement, system

#4319 Backport changes for clang
  docker/package/manylinux/build_wheel.py
  oneflow/core/common/container_util.h
  oneflow/core/common/hash_container.h
  oneflow/core/common/type_traits.h
  oneflow/core/common/util.h
Labels: automerge, build, enhancement

#4316 remove_useless_cfg_pybind_file
  cmake/cfg.cmake
  oneflow/api/python/framework/session_util.cpp
  oneflow/python/framework/c_api_util.py
  oneflow/python/framework/session_util.py
Labels: automerge, ci, feature, tooling

#4308 python tensor interface
  oneflow/api/python/framework/shape.cpp
  oneflow/api/python/framework/tensor.cpp
  oneflow/init.py
  oneflow/python/framework/tensor.py
  oneflow/python/test/ops/test_size.py
Labels: automerge, enhancement, system

#4322 Fix ObjectMsgStructDefault and std::min
  .github/workflows/test.yml
  oneflow/core/object_msg/object_msg_core.h
  oneflow/core/persistence/persistent_in_stream.cpp
  oneflow/core/persistence/stream_scanner.cpp
Labels: automerge, bug, build

#4325 Remove Operator::job_desc()
  oneflow/core/eager/opkernel_object.cpp
  oneflow/core/framework/infer_util.h
  oneflow/core/framework/op_kernel_infer_cache.cpp
  oneflow/core/graph/boxing_identity_task_node.cpp
  oneflow/core/graph/boxing_zeros_task_node.cpp
  oneflow/core/graph/collective_boxing_pack_task_node.cpp
  oneflow/core/graph/collective_boxing_task_node.cpp
  oneflow/core/graph/collective_boxing_unpack_task_node.cpp
  oneflow/core/graph/copy_task_node.cpp
  oneflow/core/graph/exec_graph.cpp
  oneflow/core/graph/op_graph.h
  oneflow/core/graph/slice_boxing_task_node.cpp
  oneflow/core/job/job_build_and_infer_ctx.cpp
  oneflow/core/job/job_builder.cpp
  oneflow/core/kernel/runtime_blob_shape_infer_helper.cpp
  oneflow/core/kernel/user_kernel.cpp
  oneflow/core/operator/foreign_input_op.cpp
  oneflow/core/operator/image_decoder_random_crop_resize_op.cpp
  oneflow/core/operator/indexed_slices_reduce_sum_op.cpp
  oneflow/core/operator/op_conf.proto
  oneflow/core/operator/operator.cpp
  oneflow/core/operator/operator.h
  oneflow/core/operator/slice_boxing_op.cpp
  oneflow/core/operator/unique_with_counts_op.cpp
  oneflow/core/operator/user_op.cpp
  oneflow/core/operator/user_op.h
  oneflow/core/operator/variable_op.cpp
  oneflow/python/ops/get_variable.py
  oneflow/user/kernels/conv_cudnn_kernels.cpp
  oneflow/user/kernels/deconv_cudnn_kernel.cpp
  oneflow/xrt/build_graph.cpp
  oneflow/xrt/passes/infer_shape_pass.cpp
  oneflow/xrt/passes/update_arg_metadata_pass.cpp
Labels: automerge, enhancement, system

#3912 Dev rm tensor list from coco reader
  oneflow/python/benchmarks/coco_data_load/coco_data_loader.py
  oneflow/python/ops/tensor_buffer_ops.py
  oneflow/python/test/ops/test_tensor_buffer_to_list_of_tensors.py
  oneflow/user/kernels/tensor_buffer_kernels.cpp
  oneflow/user/ops/tensor_buffer_ops.cpp
Labels: automerge, enhancement, op

#4290 Separate build and test
  .github/actions/upload_oss/action.yml
  .github/actions/whl/action.yml
  .github/workflows/test.yml
  ci/check/run_py_format.py
  ci/test/try_install.sh
  docker/package/manylinux/build_wheel.py
Labels: automerge, ci, enhancement

#4329 Remove ExperimentalRun and refine oneflow LOG(INFO) compile time
  oneflow/core/graph/boxing/collective_boxing_sub_task_graph_builder.cpp
  oneflow/core/graph/collective_boxing_task_node.cpp
  oneflow/core/graph/decode_random_compute_task_node.cpp
  oneflow/core/graph/wait_and_send_ids_compute_task_node.cpp
  oneflow/core/graph_impl/source_tick_compute_task_node.cpp
  oneflow/core/job/improver.cpp
  oneflow/core/job/intra_job_mem_sharing_util.cpp
  oneflow/core/job/job_conf.proto
  oneflow/core/job/job_desc.cpp
  oneflow/core/job/job_desc.h
  oneflow/core/job/model_io_job.cpp
  oneflow/core/job/model_io_v2_job.cpp
  oneflow/core/job/oneflow.cpp
  oneflow/core/job_rewriter/autograd.cpp
  oneflow/core/job_rewriter/autotick.cpp
Labels: automerge, purge, refactor, system

#4332 replace 'switch ... case ...' with register mechanism in actor.cpp
  oneflow/core/actor/actor.cpp
  oneflow/core/device/cpu_device_context.cpp
  oneflow/core/device/cuda_device_context.cpp
  oneflow/core/device/device_context.h
Labels: automerge, enhancement, system

#4330 Fix model_io check variable_conf
  oneflow/core/job/model_io_job.cpp
  oneflow/core/job/model_io_v2_job.cpp
  oneflow/python/test/models/alexnet.py
Labels: automerge, bug, system

#4328 Add back 3rd party backup and update TF commit and fix XRT
  .github/workflows/test.yml
  cmake/third_party/tensorflow.cmake
  oneflow/xrt/launch_op.cpp
  oneflow/xrt/launch_op.h
Labels: automerge, ci, enhancement

#4337 Refine user_kernel_conf
  oneflow/core/kernel/kernel.proto
  oneflow/core/kernel/user_kernel.cpp
  oneflow/core/operator/user_op.cpp
Labels: automerge, op, purge

#4336 Speedup DelOps in job pass
  oneflow/core/job_rewriter/fuse_update_ops_pass.cpp
  oneflow/core/job_rewriter/prune_cast_to_static_shape_op_pass.cpp
  oneflow/core/job_rewriter/prune_parallel_cast_op_pass.cpp
Labels: automerge, enhancement, system

#4340 XLA TF bazel mirror
  .github/actions/whl/action.yml
  cmake/third_party/lz4.cmake
  cmake/third_party/tensorflow.cmake
  docker/package/manylinux/build_wheel.py
  tools/package_mirror.py
Labels: automerge, ci, enhancement

#4341 bugfixes for multi device types support
  oneflow/core/framework/to_string.cpp
  oneflow/core/kernel/foreign_watch_kernel.cpp
  oneflow/python/framework/placement_util.py
Labels: bug, system

#4342 Versioned manylinux images
  .github/actions/whl/action.yml
  .github/workflows/test.yml
  docker/package/manylinux/build_wheel.py
Labels: automerge, ci, enhancement

#4343 Refine oss update path
  .github/workflows/test.yml
Labels: automerge, ci, enhancement

#4324 refactor tensor constructor and device
  oneflow/api/python/framework/device.cpp
  oneflow/api/python/framework/tensor.cpp
  oneflow/core/framework/device.cpp
  oneflow/core/framework/device.h
  oneflow/core/framework/tensor_impl.cpp
  oneflow/init.py
  oneflow/python/framework/device.py
  oneflow/python/framework/tensor.py
Labels: automerge, enhancement, system

#4345 Feat python FunctionNode
  oneflow/api/python/autograd/function_node.cpp
  oneflow/core/autograd/autograd_engine.h
Labels: automerge, feature, python

#4334 logical_blob_desc infer physical
  oneflow/core/framework/infer_util.h
  oneflow/core/framework/user_op_registry.cpp
  oneflow/core/kernel/user_kernel.cpp
  oneflow/core/operator/operator.cpp
  oneflow/core/operator/user_op.cpp
Labels: automerge, enhancement, system

#4315 Feat python size
  oneflow/api/python/framework/shape.cpp
  oneflow/python/test/ops/test_size.py
Labels: automerge, feature, python

#4347 Refine InferTimeShape
  oneflow/core/graph/acc_tick_compute_task_node.cpp
  oneflow/core/graph/acc_tick_compute_task_node.h
  oneflow/core/graph/compute_task_node.cpp
  oneflow/core/graph/compute_task_node.h
  oneflow/core/graph/decode_h2d_compute_task_node.cpp
  oneflow/core/graph/decode_h2d_compute_task_node.h
  oneflow/core/graph/decode_random_compute_task_node.cpp
  oneflow/core/graph/decode_random_compute_task_node.h
  oneflow/core/graph/device_tick_compute_task_node.h
  oneflow/core/graph/distribute_concat_compute_task_node.cpp
  oneflow/core/graph/distribute_concat_compute_task_node.h
  oneflow/core/graph/distribute_split_compute_task_node.cpp
  oneflow/core/graph/distribute_split_compute_task_node.h
  oneflow/core/graph/dst_subset_tick_compute_task_node.h
  oneflow/core/graph/logical_graph.cpp
  oneflow/core/graph/logical_node.h
  oneflow/core/graph/normal_forward_compute_task_node.cpp
  oneflow/core/graph/normal_forward_compute_task_node.h
  oneflow/core/graph/op_graph.cpp
  oneflow/core/graph/op_graph.h
  oneflow/core/graph/sink_compute_task_node.h
  oneflow/core/graph/source_tick_compute_task_node.h
  oneflow/core/graph/src_subset_tick_compute_task_node.h
  oneflow/core/graph/tick_compute_task_node.h
  oneflow/core/graph_impl/acc_compute_task_node.cpp
  oneflow/core/graph_impl/device_tick_compute_task_node.cpp
  oneflow/core/graph_impl/dst_subset_tick_compute_task_node.cpp
  oneflow/core/graph_impl/pack_compute_task_node.cpp
  oneflow/core/graph_impl/repeat_compute_task_node.cpp
  oneflow/core/graph_impl/source_tick_compute_task_node.cpp
  oneflow/core/graph_impl/src_subset_tick_compute_task_node.cpp
  oneflow/core/graph_impl/tick_compute_task_node.cpp
  oneflow/core/graph_impl/unpack_compute_task_node.cpp
  oneflow/core/job/job.proto
  oneflow/core/job/job_build_and_infer_ctx.cpp
  oneflow/core/job/job_builder.cpp
  oneflow/core/job/job_builder.h
  oneflow/core/job_rewriter/autograd.cpp
  oneflow/core/job_rewriter/autotick.cpp
  oneflow/core/job_rewriter/dump_blob_parallel_conf_pass.cpp
  oneflow/core/job_rewriter/job_completer.cpp
  oneflow/core/operator/acc_tick_op.cpp
  oneflow/core/operator/acc_tick_op.h
  oneflow/core/operator/operator.cpp
  oneflow/core/operator/operator.h
  oneflow/core/operator/user_op.cpp
  oneflow/core/operator/user_op.h
  oneflow/xrt/build_graph.cpp
  oneflow/xrt/passes/rebuild_job_pass.cpp
Labels: automerge, enhancement, system

#4346 Separate CUDA op tests from other tests
  .github/workflows/test.yml
Labels: automerge, ci, enhancement

#4350 Support run cpu cases without gpu
  .github/workflows/test.yml
  ci/test/parallel_run.py
  oneflow/python/framework/tensor.py
  oneflow/python/test/ops/test_nn_conv1d.py
  oneflow/python/test/ops/test_nn_conv3d.py
  oneflow/python/test/ops/test_pool.py
  oneflow/python/test/ops/test_pool_padding.py
  oneflow/python/test/ops/test_reduce_ops.py
  oneflow/python/test/xrt/test_layer_norm.py
Labels: automerge, ci, enhancement

#4286 module.apply added
  oneflow/python/nn/module.py
  oneflow/python/test/ops/test_module.py
Labels: api

#4357 Restore some cases for backward compatibility guarantee
  .github/workflows/test.yml
  dev-requirements.txt
  oneflow/python/test/models/1node_test.py
Labels: automerge, ci, enhancement

#4355 Refine user op infer ctx
  oneflow/core/framework/infer_util.h
  oneflow/core/framework/sbp_context.h
  oneflow/core/job/job.proto
  oneflow/core/kernel/user_kernel.cpp
  oneflow/core/operator/user_op.cpp
  oneflow/core/operator/user_op.h
Labels: automerge, enhancement, system

#4352 Remove TaskGraph::AcyclicTopoForEachNode
  oneflow/core/graph/task_graph.cpp
  oneflow/core/graph/task_graph.h
Labels: automerge, purge, refactor, system

#4362 Add Operator::ToOpAttribute
  oneflow/core/operator/operator.cpp
  oneflow/core/operator/operator.h
Labels: automerge, enhancement, system

#4358 Remove print logical,task,actor
  oneflow/core/actor/normal_forward_compute_actor.cpp
  oneflow/core/graph/logical_node.h
  oneflow/core/graph/print_compute_task_node.h
  oneflow/core/graph_impl/logical_node.cpp
  oneflow/core/graph_impl/print_compute_task_node.cpp
  oneflow/core/job/task.proto
  oneflow/core/operator/model_save_op.cpp
Labels: automerge, purge, refactor, system

#4348 Parallel conf add hierarchy
  oneflow/api/python/framework/instructions_builder.cpp
  oneflow/api/python/framework/parallel_conf_util.cpp
  oneflow/api/python/symbol/placement_symbol.cpp
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/framework/instructions_builder.h
  oneflow/core/framework/parallel_conf_util.cpp
  oneflow/core/framework/parallel_conf_util.h
  oneflow/core/framework/parallel_conf_util_test.cpp
  oneflow/core/job/parallel_desc.cpp
  oneflow/core/job/parallel_desc.h
  oneflow/core/job/placement.proto
  oneflow/core/operator/operator.cpp
  oneflow/python/eager/boxing_middle.py
  oneflow/python/eager/boxing_util.py
  oneflow/python/eager/interpreter_callback.py
  oneflow/python/experimental/interface_op_read_and_write.py
  oneflow/python/framework/compiler.py
  oneflow/python/framework/placement_context.py
  oneflow/python/framework/placement_util.py
  oneflow/python/framework/scope_symbol.py
  oneflow/python/framework/scope_util.py
  oneflow/python/ops/assign_op.py
  oneflow/python/serving/inference_session.py
Labels: automerge, enhancement, system

#4360 Mutil process on single client
  oneflow/core/control/ctrl_bootstrap.proto
  oneflow/core/control/global_process_ctx.cpp
  oneflow/core/eager/opkernel_instruction_type_test.cpp
  oneflow/core/eager/transport_blob_instruction_type_test.cpp
  oneflow/core/framework/interpreter_test.cpp
  oneflow/core/job/parallel_desc.cpp
  oneflow/core/job/parallel_desc_test.cpp
  oneflow/core/vm/nop_stream_type_test.cpp
  oneflow/core/vm/object_instruction_type_test.cpp
Labels: automerge, enhancement, system

#4369 Stop building release for py3.5
  .github/workflows/release.yml
  cmake/third_party/flatbuffers.cmake
  cmake/third_party/libjpeg-turbo.cmake
  cmake/third_party/opencv.cmake
  docker/package/manylinux/build_wheel.py
  oneflow/python/test/ops/test_reduce_opsV2.py
Labels: automerge, ci, enhancement

#4371 Add condition for nightly build
  .github/workflows/release.yml
Labels: automerge, ci, enhancement

#4359 Construct tensor as same as pytorch
  oneflow/api/python/framework/tensor.cpp
  oneflow/core/framework/tensor.cpp
  oneflow/core/framework/tensor.h
  oneflow/python/framework/tensor.py
Labels: automerge, enhancement, system

#4376 Optimize InferLogicalOutBlobDescsIf time
  oneflow/core/graph/op_graph.cpp
  oneflow/core/graph/op_graph.h
  oneflow/core/operator/boxing_op.cpp
  oneflow/core/operator/operator.cpp
  oneflow/core/operator/operator.h
  oneflow/core/operator/user_op.cpp
  oneflow/core/register/blob_desc.cpp
Labels: enhancement, system

#4366 Fix MAX_VAL_SEQ and MIN_VAL_SEQ for unsigned long
  oneflow/core/common/data_type.h
Labels: automerge, build, enhancement

#4192 Develop one::Opbuilder
  oneflow/api/python/framework/op_builder.cpp
  oneflow/api/python/framework/op_expr.cpp
  oneflow/core/common/maybe.h
  oneflow/core/framework/op_builder.cpp
  oneflow/core/framework/op_builder.h
  oneflow/core/framework/op_expr.cpp
  oneflow/core/framework/op_expr.h
  oneflow/python/ops/builtin_ops.py
Labels: automerge, enhancement, refactor, system

#4372 Don't generate imports for onnx if not available
  tools/generate_oneflow_symbols_export_file.py
Labels: automerge, enhancement, python

#4379 fix group boxing by dst parallel
  oneflow/core/job_rewriter/group_boxing_by_dst_parallel.cpp
Labels: bug, system

#4370 fix LARS
  oneflow/core/job_rewriter/fuse_update_ops_pass.cpp
  oneflow/core/job_rewriter/lars_optm.cpp
  oneflow/python/ops/optimizer.py
  oneflow/python/test/ops/test_optimizers.py
  oneflow/user/kernels/model_update_kernel_util.cpp
  oneflow/user/kernels/model_update_kernel_util.cu
  oneflow/user/kernels/model_update_kernel_util.h
  oneflow/user/kernels/model_update_kernels.cpp
  oneflow/user/ops/model_update_ops.cpp
Labels: automerge, bug, system

#4384 Feat py tensor tuple
  oneflow/api/python/framework/shape.cpp
  oneflow/api/python/framework/tensor_tuple.cpp
Labels: automerge, feature, python

#4375 Remove unused interface in graphs
  oneflow/core/graph/logical_graph.cpp
  oneflow/core/graph/logical_graph.h
  oneflow/core/graph/op_graph.cpp
  oneflow/core/graph/op_graph.h
  oneflow/core/graph/task_graph.h
Labels: automerge, purge, system

#4383 add empty initializer
  oneflow/core/job/initializer_conf.proto
  oneflow/core/kernel/kernel_util.cpp
  oneflow/python/framework/check_point_v2.py
  oneflow/python/framework/tensor.py
  oneflow/python/ops/initializer_util.py
Labels: automerge, enhancement, op

#4386 Fix segfault caused by mutex in vm
  oneflow/core/object_msg/object_msg_mutexed_list.h
Labels: automerge, bug, system

#4373 add frequently used methods as same as torch.nn.init
  oneflow/python/framework/check_point_v2.py
  oneflow/python/framework/tensor.py
  oneflow/python/nn/__init__.py
  oneflow/python/nn/init.py
  oneflow/python/test/ops/test_tensor.py
Labels: automerge, enhancement, system

#4392 Add parallel_distribution for 2D SBP
  oneflow/core/common/protobuf.h
  oneflow/core/framework/infer_util.h
  oneflow/core/framework/user_op_registry.cpp
  oneflow/core/graph/exec_graph.cpp
  oneflow/core/graph/op_graph.cpp
  oneflow/core/graph/op_graph.h
  oneflow/core/job/job.proto
  oneflow/core/job/job_build_and_infer_ctx.cpp
  oneflow/core/job/job_build_and_infer_ctx.h
  oneflow/core/job/job_builder.cpp
  oneflow/core/job/job_builder.h
  oneflow/core/job/parallel_distribution_infer_hint.h
  oneflow/core/job/sbp_parallel.cpp
  oneflow/core/job/sbp_parallel.h
  oneflow/core/job/sbp_parallel.proto
  oneflow/core/job_rewriter/autograd.cpp
  oneflow/core/job_rewriter/dump_blob_parallel_conf_pass.cpp
  oneflow/core/job_rewriter/generate_backward_and_optimizer_op_confs.cpp
  oneflow/core/job_rewriter/group_boxing_by_dst_parallel.cpp
  oneflow/core/job_rewriter/optimizer_placement_optimization_pass.cpp
  oneflow/core/job_rewriter/split_sparse_softmax_cross_entropy_op_pass.cpp
  oneflow/core/kernel/user_kernel.cpp
  oneflow/core/operator/op_attribute.proto
  oneflow/core/operator/operator.cpp
  oneflow/core/operator/operator.h
  oneflow/core/operator/user_op.cpp
Labels: enhancement, system

#4391 Refactor DeviceTag4DeviceType
  oneflow/core/eager/blob_object.cpp
  oneflow/core/framework/to_string.cpp
  oneflow/core/framework/to_string.h
  oneflow/core/graph/boxing/boxing_logger.cpp
  oneflow/core/graph/boxing/collective_boxing_sub_task_graph_builder.cpp
  oneflow/core/graph/boxing_identity_task_node.cpp
  oneflow/core/graph/boxing_zeros_task_node.cpp
  oneflow/core/graph/collective_boxing_pack_task_node.cpp
  oneflow/core/graph/collective_boxing_unpack_task_node.cpp
  oneflow/core/graph/copy_task_node.cpp
  oneflow/core/graph/logical_graph.cpp
  oneflow/core/graph/op_graph.cpp
  oneflow/core/graph/slice_boxing_task_node.cpp
  oneflow/core/job/improver.cpp
  oneflow/core/job/job_build_and_infer_ctx.cpp
  oneflow/core/job/parallel_desc.cpp
  oneflow/core/job_rewriter/optimizer_placement_optimization_pass.cpp
  oneflow/core/operator/operator.cpp
  oneflow/python/test/ops/test_checkpoint.py
  oneflow/user/summary/plan_to_physical_graph.cpp
  oneflow/xrt/passes/rebuild_job_pass.cpp
Labels: automerge, bug, system

#4388 Optimize construct op
  oneflow/core/framework/user_op_conf.cpp
  oneflow/core/framework/user_op_conf.h
  oneflow/core/framework/user_op_registry.cpp
  oneflow/core/graph/op_graph.cpp
  oneflow/core/graph/op_graph.h
  oneflow/core/operator/boxing_op.h
  oneflow/core/operator/operator.cpp
  oneflow/core/operator/operator.h
  oneflow/core/operator/user_op.cpp
Labels: enhancement, system

#4394 Add virtual destructors for persistence classes to prevent memory leak
  oneflow/core/device/stream_index.h
  oneflow/core/persistence/persistent_in_stream.h
  oneflow/core/persistence/stream_scanner.h
Labels: automerge, bug, system

#4405 Fix ImageDecoderRandomCropResizeOp::InferLogicalOutBlobDescs
  oneflow/core/operator/image_decoder_random_crop_resize_op.cpp
Labels: automerge, bug, op

#4364 Implement autograd engine
  oneflow/api/python/autograd/autograd.cpp
  oneflow/core/autograd/autograd_engine.cpp
  oneflow/core/autograd/autograd_engine.h
  oneflow/core/framework/tensor.h
  oneflow/core/framework/tensor_arg.cpp
  oneflow/core/framework/tensor_arg.h
Labels: automerge, enhancement, system

#4408 TaskGraph add ctrl in chain build real edge of graph
  oneflow/core/graph/task_graph.cpp
  oneflow/core/graph/task_node.cpp
  oneflow/core/graph/task_node.h
Labels: automerge, bug, refactor, system

#4414 Only include onnx if not darwin
  setup.py
Labels: automerge, build, enhancement

#4413 Fix VM access erase segfault
  oneflow/core/vm/virtual_machine.cpp
Labels: automerge, bug, system

#4406 fix user op attr at_list_float
  oneflow/python/ops/user_op_builder.py
Labels: automerge, bug, op

#4349 Refine stream index getter
  oneflow/core/graph/compute_task_node.h
  oneflow/core/graph/stream_index_getter_registry.cpp
  oneflow/core/graph/stream_index_getter_registry.h
  oneflow/core/graph/stream_index_getter_registry_manager.cpp
  oneflow/core/graph/stream_index_getter_registry_manager.h
  oneflow/core/graph/task_graph.cpp
  oneflow/core/graph/task_graph.h
  oneflow/core/graph_impl/callback_notify_compute_task_node.cpp
  oneflow/core/graph_impl/case_compute_task_node.cpp
  oneflow/core/graph_impl/decode_h2d_compute_task_node.cpp
  oneflow/core/graph_impl/device_tick_compute_task_node.cpp
  oneflow/core/graph_impl/dst_subset_tick_compute_task_node.cpp
  oneflow/core/graph_impl/esac_compute_task_node.cpp
  oneflow/core/graph_impl/foreign_input_compute_task_node.cpp
  oneflow/core/graph_impl/foreign_output_compute_task_node.cpp
  oneflow/core/graph_impl/logical_node.cpp
  oneflow/core/graph_impl/normal_forward_compute_task_node.cpp
  oneflow/core/graph_impl/reentrant_lock_compute_task_node.cpp
  oneflow/core/graph_impl/source_tick_compute_task_node.cpp
  oneflow/core/graph_impl/src_subset_tick_compute_task_node.cpp
  oneflow/core/graph_impl/tick_compute_task_node.cpp
  oneflow/core/graph_impl/wait_and_send_ids_compute_task_node.cpp
Labels: automerge, enhancement, system

#4265 Migrate unique_with_counts to user op
  oneflow/core/kernel/indexed_slices_reduce_sum_kernel.cpp
  oneflow/core/kernel/indexed_slices_reduce_sum_kernel_util.h
  oneflow/core/kernel/kernel.proto
  oneflow/core/kernel/unique_with_counts_kernel.cpp
  oneflow/core/operator/indexed_slices_reduce_sum_op.cpp
  oneflow/core/operator/indexed_slices_reduce_sum_op_util.cpp
  oneflow/core/operator/op_conf.proto
  oneflow/core/operator/unique_op_util.cpp
  oneflow/core/operator/unique_op_util.h
  oneflow/core/operator/unique_with_counts_op.cpp
  oneflow/python/experimental/indexed_slices_ops.py
  oneflow/python/experimental/unique_op.py
  oneflow/user/kernels/indexed_slices_reduce_sum_kernel.cpp
  oneflow/user/kernels/indexed_slices_reduce_sum_kernel_util.cpp
  oneflow/user/kernels/indexed_slices_reduce_sum_kernel_util.h
  oneflow/user/kernels/model_update_kernels.cpp
  oneflow/user/kernels/unique_kernel_util.cpp
  oneflow/user/kernels/unique_kernel_util.cu
  oneflow/user/kernels/unique_kernel_util.h
  oneflow/user/kernels/unique_with_counts_kernel.cpp
  oneflow/user/kernels/unsorted_segment_sum_kernel.cpp
  oneflow/user/kernels/unsorted_segment_sum_kernel_util.cpp
  oneflow/user/kernels/unsorted_segment_sum_kernel_util.cu
  oneflow/user/kernels/unsorted_segment_sum_kernel_util.h
  oneflow/user/ops/indexed_slices_reduce_sum_op.cpp
  oneflow/user/ops/unique_with_counts_op.cpp
Labels: api, automerge, enhancement, op, system

#4409 Fix DecodeRandomOp::InferLogicalOutBlobDescs
  oneflow/core/operator/decode_random_op.cpp
  oneflow/core/operator/decode_random_op.h
Labels: automerge, bug, op

#4410 Fix overflow may caused by incorrect data type in Improver::AvailableMemSize
  oneflow/core/common/util.cpp
  oneflow/core/job/improver.cpp
Labels: automerge, bug, system

#4417 Fix InferLogicalOutBlobDescs
  oneflow/core/operator/acc_tick_op.cpp
  oneflow/core/operator/acc_tick_op.h
  oneflow/core/operator/boxing_identity_op.cpp
  oneflow/core/operator/boxing_zeros_op.cpp
  oneflow/core/operator/collective_boxing_ops.cpp
  oneflow/core/operator/collective_boxing_pack_op.cpp
  oneflow/core/operator/collective_boxing_unpack_op.cpp
  oneflow/core/operator/copy_comm_net_op.h
  oneflow/core/operator/copy_hd_op.cpp
  oneflow/core/operator/model_io_v2_op.cpp
  oneflow/core/operator/operator.cpp
  oneflow/core/operator/operator.h
  oneflow/core/operator/slice_boxing_op.cpp
Labels: automerge, bug, op

#4399 [one::OpBuilder] Change pybind held type by shared_ptr
  oneflow/api/python/framework/foreign_callback.cpp
  oneflow/api/python/framework/foreign_watcher.cpp
  oneflow/api/python/framework/framework.h
  oneflow/api/python/framework/framework_api.h
  oneflow/core/eager/opkernel_instruction_type.cpp
  oneflow/core/eager/remove_foreign_callback_instruction_type.cpp
  oneflow/core/job/job_build_and_infer_ctx.cpp
  oneflow/core/job_rewriter/auto_train_step.cpp
  oneflow/core/job_rewriter/autograd.cpp
  oneflow/core/job_rewriter/dynamic_loss_scale_schedule_pass.cpp
  oneflow/core/kernel/foreign_watch_kernel.cpp
  oneflow/core/operator/operator.cpp
Labels: automerge, enhancement, system

#4393 Add hierarchical_sub_task_graph_builder
  oneflow/core/graph/boxing/boxing_logger.cpp
  oneflow/core/graph/boxing/boxing_logger.h
  oneflow/core/graph/boxing/hierarchical_sub_task_graph_builder.h
  oneflow/core/graph/boxing/hierarchical_sub_task_graph_builder_impl.cpp
  oneflow/core/graph/boxing/hierarchical_sub_task_graph_builder_impl.h
  oneflow/core/graph/task_graph.cpp
  oneflow/core/graph/task_graph.h
  oneflow/core/graph_impl/logical_node.cpp
Labels: automerge, enhancement, system

#4423 fix resnet50 throughput
  oneflow/core/graph_impl/dst_subset_tick_compute_task_node.cpp
  oneflow/core/graph_impl/src_subset_tick_compute_task_node.cpp
Labels: automerge, bug, system

#4419 Update workflow scheduler
  .github/workflows/test.yml
Labels: automerge, ci, enhancement

#4412 add resnet50 test for gpu decoder
  ci/test/1node_benchmark_test.sh
  oneflow/python/benchmarks/cnn_benchmark/data_loader.py
  oneflow/python/benchmarks/cnn_benchmark/of_cnn_benchmarks.py
Labels: automerge, enhancement, test

#4427 Fix indentation in wheel script
  docker/package/manylinux/build_wheel.py
Labels: automerge, build, enhancement

#4395 export flow.placement, support creating ConsistentTensor
  oneflow/api/python/symbol/placement_symbol.cpp
  oneflow/init.py
  oneflow/python/framework/placement_util.py
  oneflow/python/framework/remote_blob.py
  oneflow/python/framework/tensor.py
  oneflow/python/test/ops/test_tensor.py
Labels: automerge, enhancement, system

#4433 Generate unique name if the op name was not given.
  oneflow/api/python/framework/op_builder.cpp
  oneflow/core/framework/op_builder.cpp
  oneflow/core/framework/op_builder.h
  oneflow/python/ops/builtin_ops.py
Labels: automerge, feature, system

#4420 fix bug in callback notifier
  oneflow/core/job/oneflow.cpp
Labels: automerge, bug, system

#4404 [one::OpBuilder] Export boxing util for Python
  oneflow/api/python/framework/foreign_boxing_util.cpp
  oneflow/core/eager/foreign_boxing_util.h
  oneflow/python/eager/boxing_util.py
Labels: automerge, enhancement, system

#4389 nn.Linear
  oneflow/python/framework/tensor.py
  oneflow/python/nn/modules/linear.py
  oneflow/python/test/ops/test_module_linear.py
Labels: api, feature, op, python

#4402 [one::OpBuilder] Merge JobBuildAndInferCtx interface
  oneflow/api/python/job_build/job_build_and_infer.h
  oneflow/core/framework/py_remote_blob.cpp
  oneflow/core/job/job_build_and_infer_ctx_mgr.cpp
  oneflow/core/job/job_build_and_infer_ctx_mgr.h
Labels: automerge, purge, system

#4380 Add nn.AvgPool2d Module
  oneflow/python/nn/modules/pooling.py
  oneflow/python/test/module/test_avgpool2d_module.py
Labels: feature, op, python

#4421 Dev module maxpool2d
  oneflow/python/nn/modules/pooling.py
  oneflow/python/test/modules/test_global_storage.py
  oneflow/python/test/modules/test_maxpool2d_module.py
  oneflow/python/test/modules/test_util.py
Labels: enhancement, op

#4436 Remove OpEdge::InitDistributeHierarchyInfo
  oneflow/core/graph/op_graph.cpp
  oneflow/core/graph/op_graph.h
Labels: automerge, purge, system

#4435 Optimize sbp equality
  oneflow/core/job/sbp_parallel.cpp
Labels: automerge, enhancement, system

#4415 Do mem reuse in Compiler
  oneflow/core/graph/plan_task_graph.cpp
  oneflow/core/graph/plan_task_graph.h
  oneflow/core/job/compiler.cpp
  oneflow/core/job/improver.cpp
  oneflow/core/job/improver.h
  oneflow/core/job/intra_job_mem_sharing_util.cpp
  oneflow/core/job/intra_job_mem_sharing_util.h
  oneflow/core/job/oneflow.cpp
  oneflow/core/job/plan_util.cpp
  oneflow/core/job/plan_util.h
Labels: automerge, enhancement, refactor, system

#4439 make check point only depend on blob object
  oneflow/python/framework/check_point_v2.py
  oneflow/python/framework/tensor.py
Labels: automerge, enhancement, system

#4431 Use existing wheel if already built & upload whl and bin conditionally
  .github/actions/upload_ssh/action.yml
  .github/workflows/test.yml
Labels: automerge, ci, enhancement

#4432 Dev py profiler
  oneflow/api/python/profiler.cpp
  oneflow/python/framework/profiler.py
Labels: api, automerge, feature, python

#4430 Use SetAllocated other than New to avoid logging.
  oneflow/api/python/framework/framework.h
Labels: automerge, bug, system

#4428 optimize_dot_file
  oneflow/core/common/constant.h
  oneflow/core/job/oneflow.cpp
  oneflow/core/job/plan_util.cpp
  oneflow/core/operator/op_conf.proto
Labels: automerge, enhancement, system

#4363 module
  oneflow/python/framework/module.py
  oneflow/python/nn/module.py
  oneflow/python/nn/modules/__init__.py
  oneflow/python/nn/modules/container.py
  oneflow/python/nn/parameter.py
  oneflow/python/test/ops/test_module.py
  oneflow/python/test/ops/test_module_container.py
  oneflow/python/test/ops/test_user_op_module.py
Labels: automerge, feature, system

#4378 Dev module identity
  oneflow/python/nn/modules/linear.py
  oneflow/python/test/modules/test_linear.py
Labels: enhancement, op

#4403 Sync blob object and tensor's attributes
  oneflow/core/framework/device.cpp
  oneflow/core/framework/device.h
  oneflow/core/framework/tensor.h
  oneflow/core/framework/tensor_impl.cpp
  oneflow/core/framework/tensor_impl.h
Labels: automerge, enhancement, system

#4437 Feat PySize support slicing
  oneflow/api/python/framework/shape.cpp
  oneflow/python/test/ops/test_size.py
Labels: automerge, feature, python

#4429 rm job_helper identical_sbp_oba_pairs
  oneflow/core/graph/op_graph.cpp
  oneflow/core/job/job.proto
  oneflow/core/job/job_builder.cpp
  oneflow/core/job/job_builder.h
  oneflow/core/job_rewriter/autograd.cpp
  oneflow/core/job_rewriter/autograd.h
  oneflow/core/job_rewriter/generate_backward_and_optimizer_op_confs.cpp
  oneflow/user/ops/dim_gather_op.cpp
Labels: enhancement, system

#4453 Fix FillOpParallelDesc order
  oneflow/core/kernel/runtime_blob_shape_infer_helper.cpp
  oneflow/core/operator/operator.cpp
Labels: automerge, bug, system

#4447 Optimize InferOpTimeShape
  oneflow/core/graph/op_graph.cpp
  oneflow/core/operator/acc_tick_op.cpp
  oneflow/core/operator/acc_tick_op.h
  oneflow/core/operator/operator.cpp
  oneflow/core/operator/operator.h
  oneflow/core/operator/user_op.cpp
  oneflow/core/operator/user_op.h
Labels: automerge, enhancement, system

#4456 Always use protobuf 392
  cmake/third_party/header_index/protobuf_headers.txt
  cmake/third_party/header_index/protobuf_xla_headers.txt
  cmake/third_party/protobuf.cmake
Labels: automerge, enhancement, system

#4460 Remove RegstLifetimeGraph
  oneflow/core/graph/regst_lifetime_graph.cpp
  oneflow/core/graph/regst_lifetime_graph.h
  oneflow/core/job/improver.cpp
Labels: automerge, purge, refactor, system

#4459 Refine graph/ header file
  oneflow/core/graph/acc_tick_compute_task_node.h
  oneflow/core/graph/callback_notify_compute_task_node.h
  oneflow/core/graph/case_compute_task_node.h
  oneflow/core/graph/decode_h2d_compute_task_node.h
  oneflow/core/graph/device_tick_compute_task_node.h
  oneflow/core/graph/distribute_concat_compute_task_node.h
  oneflow/core/graph/distribute_split_compute_task_node.h
  oneflow/core/graph/dst_subset_tick_compute_task_node.h
  oneflow/core/graph/esac_compute_task_node.h
  oneflow/core/graph/foreign_input_compute_task_node.h
  oneflow/core/graph/foreign_io_compute_task_node.h
  oneflow/core/graph/foreign_output_compute_task_node.h
  oneflow/core/graph/reentrant_lock_compute_task_node.h
  oneflow/core/graph/sink_compute_task_node.cpp
  oneflow/core/graph/sink_compute_task_node.h
  oneflow/core/graph/source_tick_compute_task_node.h
  oneflow/core/graph/src_subset_tick_compute_task_node.h
  oneflow/core/graph/tick_compute_task_node.h
  oneflow/core/graph/wait_and_send_ids_compute_task_node.h
  oneflow/core/graph_impl/acc_tick_compute_task_node.cpp
  oneflow/core/graph_impl/callback_notify_compute_task_node.cpp
  oneflow/core/graph_impl/case_compute_task_node.cpp
  oneflow/core/graph_impl/decode_h2d_compute_task_node.cpp
  oneflow/core/graph_impl/device_tick_compute_task_node.cpp
  oneflow/core/graph_impl/distribute_concat_compute_task_node.cpp
  oneflow/core/graph_impl/distribute_split_compute_task_node.cpp
  oneflow/core/graph_impl/dst_subset_tick_compute_task_node.cpp
  oneflow/core/graph_impl/esac_compute_task_node.cpp
  oneflow/core/graph_impl/foreign_input_compute_task_node.cpp
  oneflow/core/graph_impl/foreign_io_compute_task_node.cpp
  oneflow/core/graph_impl/foreign_output_compute_task_node.cpp
  oneflow/core/graph_impl/reentrant_lock_compute_task_node.cpp
  oneflow/core/graph_impl/source_tick_compute_task_node.cpp
  oneflow/core/graph_impl/src_subset_tick_compute_task_node.cpp
  oneflow/core/graph_impl/tick_compute_task_node.cpp
  oneflow/core/graph_impl/wait_and_send_ids_compute_task_node.cpp
Labels: automerge, purge, refactor, system

#4462 fix_epoll_comm_network
  oneflow/core/comm_network/epoll/epoll_comm_network.cpp
Labels: automerge, enhancement, system

#4467 Ensure protobuf in py is no older than C++
  setup.py
Labels: automerge, enhancement, python

#4461 remove names and init
  oneflow/python/nn/modules/activation.py
  oneflow/python/nn/modules/batchnorm.py
  oneflow/python/nn/modules/flatten.py
  oneflow/python/nn/modules/linear.py
  oneflow/python/nn/modules/pooling.py
Labels: bug, op, python

#4470 Add counter methods for new control client abstract class
  .github/workflows/test.yml
  docker/package/manylinux/build_wheel.py
  oneflow/core/control/ctrl_client.cpp
  oneflow/core/rpc/include/base.h
  oneflow/core/rpc/include/grpc.h
  oneflow/core/rpc/include/local.h
  oneflow/core/rpc/lib/local.cpp
Labels: automerge, feature, system

#4469 model_io_v2 support parallel_distribution
  oneflow/core/common/shape_vec.h
  oneflow/core/graph/boxing/sub_task_graph_builder_util.cpp
  oneflow/core/graph/boxing/sub_task_graph_builder_util.h
  oneflow/core/job/model_io_v2_job.cpp
  oneflow/core/kernel/kernel.proto
  oneflow/core/kernel/model_io_v2_kernel.cpp
  oneflow/core/operator/model_io_v2_op.cpp
  oneflow/core/operator/op_conf.proto
Labels: enhancement, op

#4468 Add args to tensor op
  oneflow/python/framework/tensor.py
  oneflow/python/nn/modules/flatten.py
  oneflow/python/test/modules/test_flatten.py
Labels: bug, op

#4472 fix_eager_boxing_bug
  oneflow/core/operator/boxing_op.h
  oneflow/core/operator/operator.cpp
  oneflow/core/operator/operator.h
  oneflow/python/eager/boxing_util.py
Labels: automerge, bug, eager

#4463 add hierarchical parallel cast
  oneflow/core/framework/framework.h
  oneflow/core/framework/infer_parallel_distribution_fn_context.h
  oneflow/core/framework/user_op_registry.cpp
  oneflow/core/framework/user_op_registry.h
  oneflow/core/operator/operator.cpp
  oneflow/core/operator/operator.h
  oneflow/core/operator/user_op.cpp
  oneflow/core/operator/user_op.h
  oneflow/python/framework/ops.py
  oneflow/python/test/ops/test_hierarchical_parallel_cast.py
  oneflow/user/kernels/identity_kernel.cpp
  oneflow/user/ops/hierarchical_parallel_cast_op.cpp
Labels: automerge, enhancement, op

#4471 Refine release tasks
  .github/workflows/release.yml
Labels: automerge, ci, enhancement

#4477 Fix release package name
  .github/workflows/release.yml
Labels: automerge, bug, ci

#4367 New ci about multi process on single client
  ci/test/1node_op_test.sh
  cmake/oneflow.cmake
  oneflow/__main__.py
  oneflow/core/actor/actor.cpp
  oneflow/core/comm_network/comm_network.cpp
  oneflow/core/comm_network/epoll/epoll_comm_network.cpp
  oneflow/core/comm_network/ibverbs/ibverbs_comm_network.cpp
  oneflow/core/common/global.h
  oneflow/core/control/ctrl_test.cpp
  oneflow/core/eager/init_symbol_instruction_type_test.cpp
  oneflow/core/framework/device.cpp
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/framework/parallel_conf_util.cpp
  oneflow/core/job/cluster.cpp
  oneflow/core/job/critical_section_desc.h
  oneflow/core/job/env_global_objects_scope.cpp
  oneflow/core/job/id_manager.cpp
  oneflow/core/job/id_manager_test.cpp
  oneflow/core/job/oneflow.cpp
  oneflow/core/job/parallel_desc.cpp
  oneflow/core/job/parallel_desc.h
  oneflow/core/job/parallel_desc_test.cpp
  oneflow/core/job/plan_util.cpp
  oneflow/core/job/resource_desc.cpp
  oneflow/core/job/resource_desc.h
  oneflow/core/job/runtime.cpp
  oneflow/core/job/session_global_objects_scope.cpp
  oneflow/core/job_rewriter/autotick.cpp
  oneflow/core/rpc/include/base.h
  oneflow/core/transport/transport_test_main.cpp
  oneflow/core/vm/test_util.cpp
  oneflow/core/vm/vm_resource_desc.cpp
  oneflow/core/vm/vm_resource_desc.msg.h
  oneflow/python/advanced/distribute_ops.py
  oneflow/python/deprecated/init_cluster_env.py
  oneflow/python/eager/boxing_middle.py
  oneflow/python/eager/boxing_util.py
  oneflow/python/framework/input_blob_def.py
  oneflow/python/framework/unittest.py
  oneflow/python/ops/two_stage_reduce.py
  oneflow/python/test/ops/test_multi_process.py
Labels: automerge, ci, enhancement, system

#4473 add round to zero point
  oneflow/python/test/ops/test_quantize_op.py
  oneflow/user/kernels/min_max_observer_kernel.cpp
  oneflow/user/kernels/min_max_observer_kernel.cu
  oneflow/user/kernels/moving_average_min_max_observer_kernel.cpp
  oneflow/user/kernels/moving_average_min_max_observer_kernel.cu
Labels: automerge, bug, op, refactor

#4466 Support dynamic OneFlow libs & rm modularity & refine CI for macOS
  .github/actions/mac-build/action.yml
  .github/workflows/test.yml
  CMakeLists.txt
  cmake/oneflow.cmake
  cmake/third_party/glog.cmake
  docker/package/manylinux/build_wheel.py
  oneflow/api/python/flags.cpp
  oneflow/core/CMakeLists.txt
  oneflow/core/graph/CMakeLists.txt
  oneflow/core/job/env.proto
  oneflow/core/job/env_global_objects_scope.cpp
  oneflow/core/rpc/CMakeLists.txt
  oneflow/core/rpc/lib/local.cpp
  oneflow/python/framework/env_util.py
  oneflow/python/framework/sysconfig.py
  oneflow/python/framework/unittest.py
  oneflow/python/test/ops/test_multi_process.py
Labels: automerge, build, enhancement

#4475 Variable add parallel distribution
  oneflow/core/job_rewriter/adam_optm.cpp
  oneflow/core/job_rewriter/auto_train_step.cpp
  oneflow/core/job_rewriter/dump_variable_info_pass.cpp
  oneflow/core/job_rewriter/dynamic_loss_scale_schedule_pass.cpp
  oneflow/core/job_rewriter/lamb_optm.cpp
  oneflow/core/job_rewriter/optimizer_placement_optimization_pass.cpp
  oneflow/core/job_rewriter/quantization_aware_training.cpp
  oneflow/core/operator/model_io_v2_op.cpp
  oneflow/core/operator/op_conf.proto
  oneflow/core/operator/operator.cpp
  oneflow/core/operator/operator.h
  oneflow/core/operator/user_op.cpp
  oneflow/core/operator/user_op.h
  oneflow/core/operator/variable_op.cpp
  oneflow/core/operator/variable_op.h
  oneflow/python/ops/get_variable.py
Labels: enhancement, mac-ci, system

#4480 fix unchanged dynamic
  oneflow/core/framework/infer_util.cpp
Labels: automerge, bug, system

#4481 fix mis-ordered parallel desc in GetPhysicalParallelDescSymbols
  oneflow/core/framework/instructions_builder.cpp
Labels: automerge, bug, system

#4457 fix bug in tensor placement
  oneflow/api/python/framework/tensor.cpp
  oneflow/core/framework/tensor.cpp
  oneflow/core/framework/tensor.h
  oneflow/python/framework/tensor.py
  oneflow/python/test/ops/test_tensor.py
Labels: automerge, bug, system

#4401 [one::OpBuilder] Mig session util
  .github/workflows/test.yml
  oneflow/api/python/framework/session_util.cpp
  oneflow/core/framework/session_util.cpp
  oneflow/core/framework/session_util.h
  oneflow/python/framework/distribute_context.py
  oneflow/python/framework/session_util.py
Labels: automerge, enhancement, system

#4483 Fix collective boxing sub task graph ctrl edge connect bug
  oneflow/core/graph/boxing/collective_boxing_sub_task_graph_builder.cpp
Labels: bug, system

#4407 [one::OpBuilder] op interpreter core
  oneflow/api/python/framework/foreign_boxing_util.cpp
  oneflow/api/python/framework/op_expr.cpp
  oneflow/core/framework/op_builder.cpp
  oneflow/core/framework/op_expr.cpp
  oneflow/core/framework/op_expr.h
  oneflow/core/framework/op_interpreter.cpp
  oneflow/core/framework/op_interpreter.h
  oneflow/core/framework/op_interpreter_util.cpp
  oneflow/core/framework/op_interpreter_util.h
  oneflow/core/framework/py_distribute.cpp
  oneflow/core/framework/py_distribute.h
  oneflow/core/framework/tensor_name_scope.cpp
  oneflow/core/framework/tensor_name_scope.h
  oneflow/python/ops/builtin_ops.py
Labels: automerge, enhancement, system

#4486 Refine label check of PR
  .github/workflows/pr.yml
Labels: automerge, ci, enhancement

#4485 Add XLA CI back
  .github/workflows/test.yml
Labels: automerge, ci, enhancement

#4479 interface_op support parallel_distribution
  oneflow/core/framework/op_arg_util.cpp
  oneflow/core/job/job_conf.proto
  oneflow/core/job/model_io_job.cpp
  oneflow/core/job/model_io_v2_job.cpp
  oneflow/core/job/oneflow.cpp
  oneflow/core/operator/input_op.cpp
  oneflow/core/operator/input_op.h
  oneflow/core/operator/interface_blob_conf.proto
  oneflow/core/operator/interface_op_util.cpp
  oneflow/core/operator/interface_op_util.h
  oneflow/core/operator/output_op.cpp
  oneflow/core/operator/output_op.h
  oneflow/python/framework/input_blob_def.py
  oneflow/python/serving/inference_session.py
  oneflow/python/serving/saved_model_builder.py
Labels: automerge, enhancement, system

#4490 Check xla is enable in script
  .github/workflows/test.yml
  ci/test/test_xla.sh
Labels: automerge, ci, enhancement

#4487 Refactor builder instr pb list to instr msg list
  oneflow/api/python/framework/instructions_builder.cpp
  oneflow/core/eager/eager_oneflow.cpp
  oneflow/core/eager/eager_oneflow.h
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/framework/instructions_builder.h
  oneflow/core/framework/interpreter.cpp
  oneflow/core/framework/session_util.cpp
  oneflow/core/framework/session_util.h
  oneflow/core/vm/control_stream_type_test.cpp
  oneflow/core/vm/instruction.cpp
  oneflow/core/vm/instruction.msg.h
  oneflow/core/vm/instruction_operand.cpp
  oneflow/core/vm/instruction_operand.msg.h
  oneflow/core/vm/mirrored_object_id.cpp
  oneflow/core/vm/mirrored_object_id.msg.h
  oneflow/core/vm/nop_stream_type_test.cpp
  oneflow/core/vm/object_instruction_type_test.cpp
  oneflow/core/vm/string_instruction_type_test.cpp
  oneflow/core/vm/test_util.h
  oneflow/core/vm/virtual_machine.msg.h
  oneflow/core/vm/vm_util.cpp
  oneflow/python/test/vm/test_symbol.py
Labels: automerge, enhancement, system

#4492 Remove PackedBlob and packed_id
  oneflow/core/actor/acc_compute_actor.cpp
  oneflow/core/actor/actor.cpp
  oneflow/core/common/protobuf.h
  oneflow/core/graph/copy_task_node.cpp
  oneflow/core/graph/op_graph.cpp
  oneflow/core/operator/copy_comm_net_op.cpp
  oneflow/core/operator/copy_hd_op.cpp
  oneflow/core/operator/op_conf.proto
  oneflow/core/operator/operator.h
  oneflow/core/register/blob_desc.cpp
  oneflow/core/register/blob_desc.h
  oneflow/core/register/logical_blob_id.proto
  oneflow/core/register/register.cpp
  oneflow/core/register/register.h
  oneflow/core/register/register_desc.cpp
  oneflow/core/register/register_desc.h
  oneflow/core/register/register_desc.proto
  oneflow/core/register/register_manager.cpp
  oneflow/core/register/runtime_register_desc.cpp
  oneflow/core/register/runtime_register_desc.h
Labels: automerge, purge, refactor, system

#4496 Feat autograd mode
  oneflow/core/autograd/autograd_mode.cpp
  oneflow/core/autograd/autograd_mode.h
Labels: automerge, feature, system

#4422 add embedding module
  oneflow/python/nn/modules/embedding.py
  oneflow/python/nn/modules/flatten.py
  oneflow/python/test/modules/test_embedding_module.py
Labels: feature, op, python

#4493 Use local rpc backend by default if single process
  .github/workflows/release.yml
  .github/workflows/test.yml
  CMakeLists.txt
  oneflow/core/job/env_global_objects_scope.cpp
Labels: automerge, enhancement, system

#4497 fixbug: mem reuse ctrl safe guard when block has multi-sink
  oneflow/core/job/intra_job_mem_sharing_util.cpp
Labels: automerge, bug, system

#4465 add some quantization ops conversion in onnx
  oneflow/python/onnx/onnx_opset/__init__.py
  oneflow/python/onnx/onnx_opset/quantize.py
  oneflow/python/ops/quantize_ops.py
  oneflow/python/test/onnx/nodes/test_min_max_observer.py
  oneflow/python/test/onnx/nodes/test_moving_average_max_min_observer.py
  oneflow/python/test/ops/test_quantization_aware_training.py
  oneflow/python/test/ops/test_quantize_op.py
  oneflow/user/kernels/min_max_observer_kernel.cpp
  oneflow/user/kernels/min_max_observer_kernel.cu
  oneflow/user/kernels/moving_average_min_max_observer_kernel.cu
Labels: automerge, enhancement, onnx, python

#4489 user_kernel support parallel_distribution
  oneflow/core/framework/op_kernel.h
  oneflow/core/graph/boxing/collective_boxing_sub_task_graph_builder.cpp
  oneflow/core/graph/boxing/slice_boxing_sub_task_graph_builder.cpp
  oneflow/core/graph/boxing/sub_task_graph_builder_util.cpp
  oneflow/core/graph/boxing/sub_task_graph_builder_util.h
  oneflow/core/job/parallel_distribution_util.cpp
  oneflow/core/job/parallel_distribution_util.h
  oneflow/core/kernel/model_io_v2_kernel.cpp
  oneflow/core/kernel/user_kernel.cpp
  oneflow/user/kernels/gather_kernel.cpp
  oneflow/user/kernels/unsorted_segment_sum_kernel.cpp
  oneflow/user/ops/reshape_op.cpp
Labels: automerge, enhancement, op

#4494 construct pure intr msg list without pb
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/vm/instruction.cpp
  oneflow/core/vm/instruction.msg.h
Labels: automerge, eager, enhancement

#4424 Add nn.CrossEntropyLoss Module
  oneflow/python/framework/tensor.py
  oneflow/python/nn/modules/loss.py
  oneflow/python/nn/modules/math_op.py
  oneflow/python/test/modules/test_crossentropyloss_module.py
  oneflow/python/test/modules/test_div_module.py
  oneflow/python/test/modules/test_mean_module.py
  oneflow/python/test/modules/test_mul_module.py
  oneflow/python/test/modules/test_reciprocal_module.py
  oneflow/python/test/modules/test_sub_module.py
  oneflow/python/test/modules/test_sum_module.py
Labels: enhancement, op

#4506 Remove RegstDesc::Lock() and TaskNode::LockRegst()
  oneflow/core/graph/normal_forward_compute_task_node.h
  oneflow/core/graph/task_node.cpp
  oneflow/core/graph/task_node.h
  oneflow/core/graph_impl/distribute_concat_compute_task_node.cpp
  oneflow/core/graph_impl/distribute_split_compute_task_node.cpp
  oneflow/core/graph_impl/normal_forward_compute_task_node.cpp
  oneflow/core/register/register_desc.cpp
  oneflow/core/register/register_desc.h
Labels: automerge, purge, refactor, system
