Repository Oneflow-Inc/oneflow, pull requests merged in 2021-10, with the labels that each got.

#6271 Primitive based cast kernel
  oneflow/core/primitive/cuda/cast.cu
  oneflow/user/kernels/cast_bfloat16_kernel.cu
  oneflow/user/kernels/cast_kernel.cpp
  python/oneflow/compatible/single_client/test/ops/test_cast.py
Labels: enhancement, automerge, system

#6464 Align kernel dtype [Part4]
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/core/ndarray/binary_func.h
  oneflow/core/ndarray/ndarray_apply_binary_core.cpp
  oneflow/core/ndarray/ndarray_apply_binary_core.cu
  oneflow/core/ndarray/ndarray_apply_broadcast_binary_core.cpp
  oneflow/core/ndarray/ndarray_apply_broadcast_binary_core.cu
  oneflow/user/kernels/dim_gather_kernel_util.h
  oneflow/user/kernels/dim_gather_kernels.cpp
  oneflow/user/kernels/math_binary_broadcast_kernels.cpp
  oneflow/user/kernels/nd_index_slice_kernels.cpp
  oneflow/user/kernels/nd_index_slice_kernels.cu
  oneflow/user/kernels/scalar_logical_kernels.cpp
  oneflow/user/kernels/scalar_logical_kernels.h
Labels: enhancement, automerge, op

#6475 hotfix GlobalProcessCtx::Rank() to GlobalProcessCtx::LocalRank()
  oneflow/core/device/cuda_event_record.cpp
Labels: enhancement, automerge, system, need-clean-ccache

#6476 fix typo
  oneflow/user/ops/image_object_preprocess_ops.cpp
Labels: automerge, bug, op

#6645 Refactor oneflow.Size
  oneflow/api/python/framework/instructions_builder.cpp
  oneflow/api/python/framework/parallel_conf_util.cpp
  oneflow/api/python/framework/shape.cpp
  oneflow/api/python/framework/size.cpp
  oneflow/api/python/framework/size.h
  oneflow/api/python/framework/tensor.cpp
  oneflow/api/python/functional/common.cpp
  oneflow/api/python/functional/common.h
  oneflow/api/python/functional/python_arg.cpp
  oneflow/api/python/symbol/placement_symbol.cpp
  python/oneflow/compatible/single_client/test/ops/test_size.py
Labels: enhancement, automerge, system

#6656 update speed test threshold
  ci/test/test_speed_multi_client.sh
Labels: enhancement, automerge, ci
