Repository Oneflow-Inc/oneflow, pull requests merged in 2021-04, with the labels that each got.

#4562 fix_partial_memory_leak
  oneflow/api/python/framework/blob_cache.cpp
  oneflow/core/framework/blob_cache.cpp
  oneflow/core/framework/blob_cache.h
  oneflow/core/framework/blob_register.cpp
  oneflow/core/framework/instructions_builder.cpp
  oneflow/init.py
  oneflow/python/eager/blob_cache.py
  oneflow/python/eager/boxing_util.py
  oneflow/python/eager/eager_blob_util.py
  oneflow/python/eager/op_executor.py
  oneflow/python/experimental/interface_op_read_and_write.py
  oneflow/python/framework/check_point_v2.py
  oneflow/python/framework/push_util.py
  oneflow/python/framework/register_class_method_util.py
  oneflow/python/framework/remote_blob.py
  oneflow/python/framework/session_util.py
  oneflow/python/ops/__init__.py
  oneflow/python/ops/get_variable.py
Labels: automerge, bug, system

#4561 Refine nightly
  .github/workflows/release.yml
  README.md
  docs/requirements.txt
Labels: automerge, ci, enhancement

#4560 Refactor eager mirrored tensor
  oneflow/core/eager/eager_blob_object.cpp
  oneflow/core/eager/eager_blob_object.h
  oneflow/core/eager/opkernel_instruction_type.cpp
  oneflow/core/framework/tensor_impl.cpp
  oneflow/core/framework/tensor_impl.h
  oneflow/core/framework/tensor_storage.cpp
  oneflow/core/framework/tensor_storage.h
Labels: automerge, enhancement, system

#4538 Optimize compile time memory usage
  docker/package/manylinux/build_wheel.py
  oneflow/core/job/compiler.cpp
  oneflow/core/job/inter_job_mem_sharing_util.cpp
  oneflow/core/job/intra_job_mem_sharing_util.cpp
  oneflow/core/job/oneflow.cpp
  oneflow/core/job/plan.proto
  oneflow/core/job/plan_util.cpp
  oneflow/core/job/plan_util.h
  oneflow/core/kernel/kernel.proto
Labels: automerge, enhancement, system

#4527 GPT Data Loader
  oneflow/core/common/util.h
  oneflow/core/framework/infer_parallel_distribution_fn_context.h
  oneflow/core/operator/user_op.cpp
  oneflow/python/ops/get_variable.py
  oneflow/python/ops/user_data_ops.py
  oneflow/python/test/ops/test_gpt_data_loader.py
  oneflow/user/data/gpt_dataset.cpp
  oneflow/user/data/gpt_dataset.h
  oneflow/user/kernels/gpt_data_loader_kernel.cpp
  oneflow/user/ops/gpt_data_loader_op.cpp
Labels: automerge, feature, op

#4568 fix softmax sbp
  oneflow/user/ops/softmax_op.cpp
Labels: automerge, bug, op

#4564 fix blob_desc ctor
  oneflow/core/register/blob_desc.cpp
  oneflow/core/register/pod_desc.cpp
  oneflow/core/register/pod_desc.h
Labels: automerge, enhancement, system

#4530 Refactor tensor desc as abstract class
  oneflow/core/framework/tensor_desc.cpp
  oneflow/core/framework/tensor_desc.h
  oneflow/core/framework/user_op_conf.cpp
  oneflow/core/framework/user_op_conf.h
  oneflow/core/kernel/user_kernel.cpp
  oneflow/core/operator/user_op.cpp
Labels: automerge, enhancement, system

#4567 Support link shared lib Protobuf
  .github/workflows/test.yml
  cmake/oneflow.cmake
  cmake/third_party/protobuf.cmake
  docker/package/manylinux/build_wheel.py
Labels: automerge, build, enhancement

#4566 fuse tril scale softmax dropout
  oneflow/core/cuda/softmax.cuh
  oneflow/core/job_rewriter/auto_mixed_precision_lists.cpp
  oneflow/python/ops/math_ops.py
  oneflow/python/test/ops/test_fused_scale_tril_softmax_mask_and_scale.py
  oneflow/user/kernels/fused_tril_scale_softmax_mask_scale_kernel.cu
  oneflow/user/kernels/softmax_kernel.cu
  oneflow/user/kernels/sparse_softmax_cross_entropy_kernel.cu
  oneflow/user/ops/fused_scale_tril_softmax_mask_scale_op.cpp
Labels: enhancement, op

#4572 allow more streams using scheduling thread
  oneflow/core/eager/blob_instruction_type.cpp
  oneflow/core/vm/control_stream_type.cpp
  oneflow/core/vm/control_stream_type.h
  oneflow/core/vm/cpu_stream_type.h
  oneflow/core/vm/cuda_copy_d2h_stream_type.h
  oneflow/core/vm/cuda_copy_h2d_stream_type.h
  oneflow/core/vm/cuda_stream_type.h
  oneflow/core/vm/device_helper_stream_type.h
  oneflow/core/vm/host_stream_type.h
  oneflow/core/vm/infer_stream_type.h
  oneflow/core/vm/nop_stream_type.cpp
  oneflow/core/vm/stream_type.h
  oneflow/core/vm/transport_stream_type.h
  oneflow/core/vm/virtual_machine.cpp
Labels: automerge, enhancement, system

#4573 Fix iteration variable name
  oneflow/python/ops/user_data_ops.py
  oneflow/user/data/gpt_dataset.cpp
Labels: automerge, bug, op

#4576 sparse_softmax_cross_entropy support 2d model_parallel
  oneflow/core/graph/boxing/hierarchical_sub_task_graph_builder_impl.cpp
  oneflow/core/job_rewriter/split_sparse_softmax_cross_entropy_op_pass.cpp
  oneflow/python/ops/nn_ops.py
  oneflow/python/test/ops/test_sparse_softmax_cross_entropy_ms.py
  oneflow/user/kernels/sparse_cross_entropy_kernel.cpp
  oneflow/user/kernels/sparse_softmax_cross_entropy_kernel.cpp
  oneflow/user/ops/sparse_cross_entropy_op.cpp
  oneflow/user/ops/sparse_softmax_cross_entropy_op.cpp
  oneflow/user/ops/two_stage_reduce_ops.cpp
Labels: enhancement, system

#4577 try static switch
  oneflow/core/framework/user_op_hob.cpp
  oneflow/core/framework/user_op_hob.h
  oneflow/user/kernels/arg_where_kernel.cpp
Labels: automerge, enhancement, op

#4581 Local RPC supports TryLockResult::kDoing
  oneflow/core/rpc/include/local.h
  oneflow/core/rpc/lib/local.cpp
Labels: automerge, bug, system

#4584 change nccl logical debug log from console to LOG.INFO
  oneflow/core/job_rewriter/insert_nccl_logical_op_pass.cpp
Labels: automerge, feature, system

#4579 Nccl support s1 to B and P to s1
  oneflow/core/graph/boxing/boxing_logger.cpp
  oneflow/core/graph/boxing/collective_boxing_sub_task_graph_builder.cpp
Labels: automerge, enhancement, system

#4569 fix pad_op sbp setting
  oneflow/user/ops/pad2d_ops.cpp
Labels: automerge, bug, op

#4499 make eager execution async by default
  oneflow/api/python/eager/eager.cpp
  oneflow/api/python/env/env.cpp
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/framework/instructions_builder.h
  oneflow/core/framework/interpreter_test.cpp
  oneflow/core/job/cluster.cpp
  oneflow/core/job/cluster_instruction.cpp
  oneflow/core/job/cluster_instruction.proto
  oneflow/core/object_msg/object_msg_skiplist.h
  oneflow/core/vm/control_stream_type.cpp
  oneflow/core/vm/instruction.cpp
  oneflow/core/vm/instruction.msg.h
  oneflow/core/vm/instruction.proto
  oneflow/core/vm/instruction_operand.cpp
  oneflow/core/vm/instruction_operand.msg.h
  oneflow/core/vm/instruction_type.cpp
  oneflow/core/vm/instruction_type.h
  oneflow/core/vm/object_instruction_type.cpp
  oneflow/core/vm/object_instruction_type_test.cpp
  oneflow/core/vm/oneflow_vm.cpp
  oneflow/core/vm/oneflow_vm.h
  oneflow/core/vm/sequential_instruction_type.cpp
  oneflow/core/vm/sequential_instruction_type_test.cpp
  oneflow/core/vm/stream.cpp
  oneflow/core/vm/stream.msg.h
  oneflow/core/vm/thread_ctx.cpp
  oneflow/core/vm/virtual_machine.cpp
  oneflow/core/vm/virtual_machine.msg.h
  oneflow/core/vm/vm_object.cpp
  oneflow/core/vm/vm_object.msg.h
  oneflow/core/vm/vm_util.cpp
  oneflow/core/vm/vm_util.h
  oneflow/python/framework/check_point_v2.py
Labels: automerge, eager, enhancement

#4587 Fix DeviceTick time shape
  oneflow/core/actor/acc_compute_actor.cpp
  oneflow/core/job_rewriter/autotick.cpp
  oneflow/core/operator/acc_tick_op.cpp
  oneflow/core/operator/device_tick_op.cpp
  oneflow/core/operator/device_tick_op.h
  oneflow/core/operator/op_conf.proto
Labels: automerge, bug, system

#4588 CheckpointingPass ignore Repeat/Unpack
  oneflow/core/job_rewriter/checkpointing_pass.cpp
Labels: automerge, enhancement, system

#4580 clip_by_global_norm and count_not_finite add cast to P
  oneflow/core/job_rewriter/autograd.cpp
Labels: automerge, enhancement, system

#4590 Fix include cuda header
  oneflow/core/graph/task_graph.cpp
  oneflow/core/operator/image_decoder_random_crop_resize_op.cpp
Labels: automerge, bug, op

#4593 NCCL logical op support [*, S(1)] -> [*, B]
  oneflow/core/job_rewriter/insert_nccl_logical_op_pass.cpp
  oneflow/core/job_rewriter/split_sparse_softmax_cross_entropy_op_pass.cpp
  oneflow/user/kernels/nccl_logical_2d_sbp_kernels.cpp
  oneflow/user/ops/nccl_logical_2d_sbp_ops.cpp
Labels: automerge, bottleneck, feature, system

#4592 Remove option CUDA_SEPARABLE_COMPILATION
  cmake/third_party.cmake
Labels: automerge, bug, system

#4585 Remove outdate PrintSbpLog in test_ops.cpp
  oneflow/user/ops/test_ops.cpp
Labels: automerge, op, purge

#4583 Refine create NcclCollectiveBoxingExecutorBackend
  oneflow/core/job/collective_boxing_executor.cpp
Labels: automerge, enhancement, system

#4594 Fix hob device type lifetime
  .github/workflows/test.yml
  docker/package/manylinux/build_wheel.py
  oneflow/core/framework/user_op_hob.cpp
  oneflow/core/framework/user_op_hob.h
Labels: automerge, bug, system

#4595 fuse bias add dropout gelu ops
  oneflow/core/job_rewriter/auto_mixed_precision_lists.cpp
  oneflow/core/job_rewriter/fuse_add_to_output_pass.cpp
  oneflow/python/ops/nn_ops.py
  oneflow/python/test/ops/test_fused_bias_add_dropout.py
  oneflow/python/test/ops/test_fused_bias_add_gelu.py
  oneflow/user/kernels/fused_bias_add_kernel.cu
  oneflow/user/ops/fused_bias_add_op.cpp
Labels: automerge, enhancement, op

#4597 Don't ssh copy packages if custom op test fails
  .github/workflows/test.yml
Labels: automerge, ci, enhancement

#4596 acc_kernel add half, acc_tick add GetSbp
  oneflow/core/operator/acc_tick_op.cpp
  oneflow/core/operator/acc_tick_op.h
  oneflow/user/kernels/acc_kernel.cpp
Labels: automerge, bug, op

#3734 Add GradientAccumulationRewritePass
  oneflow/core/graph_impl/acc_compute_task_node.cpp
  oneflow/core/graph_impl/acc_tick_compute_task_node.cpp
  oneflow/core/job/job_build_and_infer_ctx.cpp
  oneflow/core/job/job_conf.proto
  oneflow/core/job_rewriter/auto_mixed_precision_lists.cpp
  oneflow/core/job_rewriter/autograd.cpp
  oneflow/core/job_rewriter/gradient_accumulation_rewrite_pass.cpp
  oneflow/core/job_rewriter/normalization_exponential_average_auto_tick_rewrite_pass.cpp
  oneflow/python/framework/function_util.py
  oneflow/user/kernels/nop_kernel.cpp
  oneflow/user/ops/cast_to_tick_op.cpp
Labels: automerge, feature, system

#4599 PhyInstrOperand::ForEachXXXMirroredObject
  oneflow/core/vm/instruction_operand.msg.h
  oneflow/core/vm/no_arg_cb_phy_instr_operand.h
  oneflow/core/vm/phy_instr_operand.h
  oneflow/core/vm/virtual_machine.cpp
Labels: automerge, enhancement, system

#4603 Matmul add alpha Attr
  oneflow/core/kernel/util/cuda_blas_interface.cu
  oneflow/core/kernel/util/cuda_blas_interface.h
  oneflow/core/kernel/util/host_blas_interface.cpp
  oneflow/core/kernel/util/host_blas_interface.h
  oneflow/python/ops/linalg.py
  oneflow/python/test/ops/test_matmul.py
  oneflow/user/kernels/matmul_kernels.cpp
  oneflow/user/ops/matmul_op.cpp
Labels: automerge, enhancement, op

#4600 half reduce_sum_like use gemm
  oneflow/python/test/ops/test_reduce_sum_like.py
  oneflow/user/kernels/reduce_like_kernels.cpp
Labels: automerge, enhancement, op

#4598 fix empty initializer
  oneflow/core/kernel/kernel_util.cpp
Labels: automerge, bug, system

#4601 Add seperated matrix for eager
  .github/workflows/test.yml
Labels: automerge, ci, enhancement

#4610 add module common part
  oneflow/python/experimental/interface_op_read_and_write.py
  oneflow/python/framework/check_point_v2.py
  oneflow/python/framework/tensor.py
  oneflow/python/nn/init.py
  oneflow/python/ops/initializer_util.py
  oneflow/python/test/modules/test_util.py
  oneflow/python/test/ops/test_tensor.py
Labels: automerge, enhancement, python

#4602 model inherit new module
  oneflow/python/framework/model.py
Labels: automerge, eager, feature, refactor

#4611 Add static check for user op dtype register
  oneflow/core/framework/user_op_registry_manager.cpp
  oneflow/user/ops/cast_to_tick_op.cpp
  oneflow/user/ops/nccl_logical_2d_sbp_ops.cpp
Labels: automerge, enhancement, system

#4604 Optimize repeat placement
  oneflow/core/job_rewriter/gradient_accumulation_rewrite_pass.cpp
Labels: automerge, enhancement, system

#4606 Check and complete op_conf.scope_symbol_id in JobPass
  oneflow/core/job/job_build_and_infer_ctx.cpp
  oneflow/core/job/job_build_and_infer_ctx.h
  oneflow/core/job_rewriter/autograd.cpp
  oneflow/core/job_rewriter/broadcast_to_compatible_with_grad.cpp
  oneflow/core/job_rewriter/fuse_update_ops_pass.cpp
  oneflow/core/job_rewriter/indexed_slices_optimizer_rewrite_pass.cpp
  oneflow/python/serving/inference_session.py
Labels: automerge, feature, system

#4582 Dry run output gpu mem usage
  oneflow/core/job/improver.cpp
Labels: automerge, enhancement, system

#4614 nccl logical 1D op support ParallelDistribution
  oneflow/user/ops/nccl_logical_ops.cpp
Labels: automerge, bug, op

#4613 fix count_not_finite and clip_by_global add's parallel_conf
  oneflow/core/job_rewriter/autograd.cpp
  oneflow/core/operator/operator.cpp
Labels: automerge, bug, system

#4617 Fix receive blob instruction stream and deadlock
  oneflow/core/eager/transport_blob_instruction_type.h
Labels: automerge, bug, system

#4515 [one::OpBuilder] Dev user op gradient
  oneflow/core/autograd/gradient_funcs/default.cpp
  oneflow/core/framework/op_builder.cpp
  oneflow/core/framework/op_builder.h
  oneflow/core/framework/op_expr.cpp
  oneflow/core/framework/op_expr.h
  oneflow/core/framework/op_expr_grad_function.h
Labels: automerge, enhancement, system

#4622 Fix ctrl_in_op restriction
  oneflow/core/graph/task_graph.cpp
Labels: automerge, bug, system

#4608 VmLocalDepObject
  oneflow/core/framework/tensor_impl.cpp
  oneflow/core/framework/tensor_impl.h
  oneflow/core/framework/tensor_storage.cpp
  oneflow/core/framework/tensor_storage.h
  oneflow/core/framework/vm_local_dep_object.cpp
  oneflow/core/framework/vm_local_dep_object.h
  oneflow/core/vm/oneflow_vm.h
Labels: enhancement, system

#4634 Add privilege for CI container for gdb
  .github/workflows/test.yml
Labels: automerge, ci, enhancement

#4633 Xfjiang/dev save lr to csv
  oneflow/core/job_rewriter/auto_learning_rate.cpp
  oneflow/core/kernel/learning_rate_schedule_kernel.cpp
Labels: automerge, enhancement, system

#4607 Remove Pod and header in BlobDesc
  oneflow/core/eager/lazy_ref_blob_object.h
  oneflow/core/framework/op_arg_util.cpp
  oneflow/core/framework/tensor_desc.cpp
  oneflow/core/kernel/runtime_blob_shape_infer_helper.cpp
  oneflow/core/kernel/user_kernel.cpp
  oneflow/core/register/blob.cpp
  oneflow/core/register/blob.h
  oneflow/core/register/blob_desc.cpp
  oneflow/core/register/blob_desc.h
  oneflow/core/register/blob_desc.proto
  oneflow/core/register/runtime_blob_desc.cpp
  oneflow/core/register/runtime_blob_desc.h
  oneflow/python/onnx/flow2onnx.py
Labels: automerge, purge, refactor, system

#4624 Fix Memory Leak
  oneflow/core/eager/transport_blob_instruction_type.cpp
  oneflow/core/job/cluster.cpp
  oneflow/core/job/env_global_objects_scope.cpp
  oneflow/core/job/runtime.cpp
Labels: automerge, enhancement, system

#4628 Dev AttrValueMap and support dynamic attributes.
  oneflow/api/python/framework/attr_val_map.cpp
  oneflow/api/python/framework/op_expr.cpp
  oneflow/core/autograd/gradient_funcs/default.cpp
  oneflow/core/framework/attr_value_map.cpp
  oneflow/core/framework/attr_value_map.h
  oneflow/core/framework/op_expr.cpp
  oneflow/core/framework/op_expr.h
  oneflow/core/framework/op_expr_grad_function.h
  oneflow/core/framework/op_interpreter.h
  oneflow/core/framework/op_interpreter/eager_consistent_op_interpreter.cpp
  oneflow/core/framework/op_interpreter/eager_mirrored_op_interpreter.cpp
  oneflow/core/framework/op_interpreter/op_interpreter.cpp
  oneflow/core/framework/op_interpreter/op_interpreter_util.cpp
  oneflow/core/framework/op_interpreter/op_interpreter_util.h
  oneflow/python/framework/attr_util.py
  oneflow/python/framework/op_expr_util.py
  oneflow/python/ops/builtin_ops.py
Labels: automerge, enhancement, system

#4638 Remove RecordBlob and Blob::record_num
  oneflow/core/register/blob.cpp
  oneflow/core/register/blob.h
Labels: automerge, purge, refactor, system

#4642 fix a bug in fake_quantization
  oneflow/python/onnx/onnx_opset/quantize.py
  oneflow/python/test/onnx/nodes/test_fake_quantization.py
Labels: automerge, bug, enhancement, python

#4640 Support oneflow convert tools
  oneflow/python/framework/c_api_util.py
Labels: api, automerge, enhancement, onnx, python

#4646 Add cudnn conf in resource
  oneflow/core/job/job_desc.cpp
  oneflow/core/job/resource.proto
  oneflow/core/job/resource_desc.cpp
  oneflow/core/job/resource_desc.h
  oneflow/user/kernels/conv_cudnn_kernels.cpp
  oneflow/user/kernels/deconv_cudnn_kernel.cpp
  oneflow/user/kernels/matmul_kernels.cpp
Labels: automerge, enhancement, system

#4649 Update readme, remove CentOS info, add Ubuntu 20.04 info
  README.md
Labels: automerge, build, documentation

#4651 fix typo when add optimizer op
  oneflow/core/job_rewriter/generate_backward_and_optimizer_op_confs.cpp
Labels: automerge, bug, system

#4655 Fix add function node
  oneflow/api/python/framework/tensor.cpp
  oneflow/core/autograd/autograd_engine.cpp
  oneflow/core/autograd/autograd_engine.h
  oneflow/core/framework/op_interpreter/op_interpreter.cpp
  oneflow/core/framework/tensor.cpp
  oneflow/core/framework/tensor.h
Labels: automerge, bug, eager

#4653 Use vector instead of set for memory reduce
  oneflow/core/job/intra_job_mem_sharing_util.cpp
Labels: enhancement, system

#4658 Use cmake type release by default
  CMakeLists.txt
  README.md
Labels: automerge, build, enhancement

#4648 pure stateful opkernel
  oneflow/core/eager/blob_object.h
  oneflow/core/eager/eager_blob_object.cpp
  oneflow/core/eager/eager_blob_object.h
  oneflow/core/eager/lazy_ref_blob_object.h
  oneflow/core/eager/opkernel_instruction_type.cpp
  oneflow/core/memory/memory_case_util.cpp
  oneflow/core/memory/memory_case_util.h
  oneflow/core/register/blob_desc.h
  oneflow/core/register/pod_desc.h
  oneflow/user/kernels/stateful_local_opkernel.cpp
  oneflow/user/kernels/stateful_local_opkernel.h
Labels: automerge, enhancement, system

#4652 Add nvtx start end op
  oneflow/python/ops/array_ops.py
  oneflow/python/test/ops/test_nvtx_range.py
  oneflow/user/kernels/nvtx_range_kernel.cu
  oneflow/user/ops/nvtx_range_op.cpp
Labels: automerge, enhancement, op

#4641 Master use sub plan rather than full plan to save memory usage
  oneflow/core/job/oneflow.cpp
Labels: automerge, enhancement, system

#4650 of_protoobj and of_cfgobj only link protobuf
  cmake/oneflow.cmake
  cmake/proto2cpp.cmake
  cmake/third_party/protobuf.cmake
  setup.py
Labels: automerge, build, enhancement

#4654 Dev autograd interpreter and rewrite batch gather grad function.
  oneflow/api/python/autograd/autograd.cpp
  oneflow/core/autograd/gradient_funcs/batch_gather.cpp
  oneflow/core/autograd/gradient_funcs/default.cpp
  oneflow/core/framework/op_expr.cpp
  oneflow/core/framework/op_expr.h
  oneflow/core/framework/op_expr_grad_function.h
  oneflow/core/framework/op_expr_helper.cpp
  oneflow/core/framework/op_expr_helper.h
  oneflow/core/framework/op_interpreter.h
  oneflow/core/framework/op_interpreter/eager_consistent_op_interpreter.cpp
  oneflow/core/framework/op_interpreter/op_interpreter.cpp
  oneflow/core/framework/op_interpreter/op_interpreter_util.cpp
  oneflow/core/framework/op_interpreter/op_interpreter_util.h
  oneflow/core/framework/user_op_conf_trait.cpp
  oneflow/core/framework/user_op_conf_trait.h
Labels: automerge, enhancement, system

#4552 tensor with requires grad setter
  oneflow/api/python/framework/tensor.cpp
  oneflow/python/framework/tensor.py
Labels: api, automerge, enhancement, system

#4664 Add OF_PROFILER_LOG_HOST_MEMORY_USAGE
  oneflow/core/profiler/profiler.cpp
  oneflow/core/profiler/profiler.h
Labels: automerge, feature, system

#4665 prune hierarchical_parallel_cast
  oneflow/core/job_rewriter/prune_parallel_cast_op_pass.cpp
Labels: automerge, enhancement, system

#4643 Refactor Global CommNetwork struct and remove deprecated init
  oneflow/core/comm_network/comm_network.cpp
  oneflow/core/comm_network/comm_network.h
  oneflow/core/comm_network/epoll/epoll_comm_network.cpp
  oneflow/core/comm_network/epoll/epoll_comm_network.h
  oneflow/core/comm_network/ibverbs/ibverbs_comm_network.cpp
  oneflow/core/comm_network/ibverbs/ibverbs_comm_network.h
  oneflow/core/job/runtime.cpp
Labels: automerge, purge, refactor, system

#4667 Axpy use half2
  oneflow/core/kernel/util/cuda_blas_interface.cu
  oneflow/python/test/ops/test_repeat_acc.py
Labels: automerge, enhancement, op

#4644 Remove RtBlobDesc
  oneflow/core/eager/eager_blob_object.cpp
  oneflow/core/eager/eager_blob_object.h
  oneflow/core/eager/lazy_ref_blob_object.h
  oneflow/core/graph/task_graph.cpp
  oneflow/core/job_rewriter/add_input_output_ops_pass.cpp
  oneflow/core/job_rewriter/do_parallel_cast_before_widening_type_cast_pass.cpp
  oneflow/core/job_rewriter/fuse_add_to_output_pass.cpp
  oneflow/core/job_rewriter/fuse_cast_scale_pass.cpp
  oneflow/core/job_rewriter/fuse_update_ops_pass.cpp
  oneflow/core/job_rewriter/prune_cast_to_static_shape_op_pass.cpp
  oneflow/core/job_rewriter/prune_parallel_cast_op_pass.cpp
  oneflow/core/kernel/model_io_v2_kernel.cpp
  oneflow/core/kernel/runtime_blob_shape_infer_helper.cpp
  oneflow/core/kernel/runtime_blob_shape_infer_helper.h
  oneflow/core/kernel/user_kernel.cpp
  oneflow/core/memory/memory_allocator.cpp
  oneflow/core/register/blob.cpp
  oneflow/core/register/blob.h
  oneflow/core/register/blob_desc.cpp
  oneflow/core/register/blob_desc.h
  oneflow/core/register/register_desc.cpp
  oneflow/core/register/register_manager.cpp
  oneflow/core/register/runtime_blob_desc.cpp
  oneflow/core/register/runtime_blob_desc.h
  oneflow/core/register/runtime_register_desc.cpp
  oneflow/core/register/runtime_register_desc.h
  oneflow/xrt/launch_kernel.cpp
Labels: automerge, purge, refactor, system

#4671 nvtx start end add to clear_list
  oneflow/core/job_rewriter/auto_mixed_precision_lists.cpp
Labels: automerge, enhancement, op

#4668 fused_bias_add_dropout use bias_add when rate is 0 or predict
  oneflow/python/ops/nn_ops.py
Labels: automerge, enhancement, op

#4618 Feat: nccl_use_compute_stream support batch accumulation
  oneflow/core/graph/task_graph.cpp
  oneflow/core/job/eager_nccl_comm_manager.cpp
  oneflow/core/job_rewriter/insert_nccl_logical_op_pass.cpp
  oneflow/user/ops/cast_to_tick_op.cpp
Labels: automerge, bottleneck, feature, system

#4164 Add expand op implementation
  oneflow/python/ops/array_ops.py
  oneflow/python/test/ops/test_expand_op.py
  oneflow/user/kernels/expand_kernel.cpp
  oneflow/user/kernels/expand_kernel.cu
  oneflow/user/kernels/expand_kernel_utils.h
  oneflow/user/ops/expand_op.cpp
Labels: automerge, feature, op

#4676 CMake creates a source file in build dir
  cmake/oneflow.cmake
  cmake/third_party/protobuf.cmake
Labels: automerge, build, enhancement

#4677 refactor tensor/module/op register function
  oneflow/python/framework/tensor.py
Labels: automerge, enhancement, system

#4673 Refactor op expr.
  oneflow/api/python/framework/op_expr.cpp
  oneflow/core/autograd/gradient_funcs/default.cpp
  oneflow/core/framework/op_expr.cpp
  oneflow/core/framework/op_expr.h
  oneflow/core/framework/op_expr_helper.h
  oneflow/core/framework/op_interpreter/op_interpreter.cpp
  oneflow/core/framework/op_interpreter/op_interpreter_util.cpp
Labels: automerge, enhancement, system

#4682 acc 0 use memcpy instead of memset axpy
  oneflow/core/actor/acc_compute_actor.cpp
Labels: automerge, enhancement, op

#4685 user op add error info
  oneflow/core/operator/user_op.cpp
Labels: automerge, enhancement, op

#4672 Add more grad functions
  oneflow/core/autograd/gradient_funcs/bias_add.cpp
  oneflow/core/autograd/gradient_funcs/broadcast_binary_ops.cpp
  oneflow/core/autograd/gradient_funcs/cast.cpp
  oneflow/core/autograd/gradient_funcs/deconv.cpp
  oneflow/core/autograd/gradient_funcs/layer_norm.cpp
  oneflow/core/autograd/gradient_funcs/normalization.cpp
  oneflow/core/autograd/gradient_funcs/reshape.cpp
  oneflow/core/autograd/gradient_funcs/split_like.cpp
  oneflow/core/autograd/gradient_funcs/tensor_scalar_binary.cpp
Labels: automerge, enhancement, system

#4690 small fix in CreateOpAttributeRef
  oneflow/core/job/compiler.cpp
Labels: automerge, enhancement, system

#4686 run FuseAddToOutputPass again to fuse ops created in the first run
  oneflow/core/job/job_build_and_infer_ctx.cpp
Labels: automerge, enhancement, system

#4696 Speed up autograd.grad
  oneflow/core/autograd/autograd_engine.cpp
  oneflow/core/autograd/autograd_engine.h
  oneflow/core/framework/tensor.h
  oneflow/core/framework/tensor_impl.h
Labels: automerge, eager

#4683 prune amp_white_identity
  oneflow/core/job/job_build_and_infer_ctx.cpp
  oneflow/core/job/job_conf.proto
  oneflow/core/job/job_desc.h
  oneflow/core/job_rewriter/prune_amp_white_identity_op_pass.cpp
  oneflow/python/framework/function_util.py
Labels: automerge, enhancement, system

#4688 Broadcast matmul
  oneflow/python/ops/linalg.py
  oneflow/python/test/ops/test_matmul.py
  oneflow/user/kernels/matmul_kernels.cpp
  oneflow/user/ops/matmul_op.cpp
Labels: automerge, enhancement, op

#4699 Reserve space to avoid resize.
  oneflow/core/autograd/gradient_funcs/bias_add.cpp
Labels: automerge, enhancement, system

#4695 Fix transpose op
  oneflow/core/kernel/util/cuda_arithemetic_interface.cu
  oneflow/user/kernels/transpose_kernel.cpp
  oneflow/user/ops/transpose_ops.cpp
Labels: automerge, enhancement, op

#4701 Reserve space to avoid resize.
  oneflow/core/autograd/gradient_funcs/split_like.cpp
Labels: automerge, enhancement, system

#4659 Remove user op conf in kernel init ctx
  oneflow/core/device/cudnn_conv_util.cpp
  oneflow/core/device/cudnn_conv_util.h
  oneflow/core/framework/infer_util.cpp
  oneflow/core/framework/infer_util.h
  oneflow/core/framework/op_kernel.cpp
  oneflow/core/framework/op_kernel.h
  oneflow/core/framework/user_op_conf.cpp
  oneflow/core/framework/user_op_conf.h
  oneflow/core/kernel/user_kernel.cpp
  oneflow/core/operator/user_op.cpp
  oneflow/extension/python/py_compute.cpp
  oneflow/user/kernels/arg_where_kernel.cpp
  oneflow/user/kernels/conv_cudnn_kernels.cpp
  oneflow/user/kernels/conv_kernels.cpp
  oneflow/user/kernels/deconv_cudnn_kernel.cpp
  oneflow/user/kernels/dropout_kernel.cpp
  oneflow/user/kernels/dropout_kernel.cu
  oneflow/user/kernels/fused_bias_add_kernel.cu
  oneflow/user/kernels/layer_norm_gpu_kernel.cu
  oneflow/user/kernels/matmul_kernels.cpp
  oneflow/user/kernels/model_update_kernels.cpp
  oneflow/user/kernels/normalization_kernel.cu
  oneflow/user/kernels/nvtx_range_kernel.cu
  oneflow/user/kernels/square_sum_kernel.cpp
  oneflow/user/kernels/stateful_local_opkernel.cpp
  oneflow/user/kernels/stateful_local_opkernel.h
  oneflow/user/kernels/tuple_identity_kernel.cpp
  oneflow/user/ops/assign_op.cpp
  oneflow/user/ops/conv_op.cpp
  oneflow/user/ops/layer_norm_op.cpp
  oneflow/user/ops/math_binary_broadcast_ops.cpp
  oneflow/user/ops/matmul_op.cpp
  oneflow/user/ops/model_update_ops.cpp
  oneflow/user/ops/normalization_op.cpp
  oneflow/user/ops/square_sum_op.cpp
  oneflow/user/ops/tuple_identity_op.cpp
Labels: automerge, enhancement, system

#4707 Fix memory leaks caused by circle reference.
  oneflow/core/framework/op_interpreter.h
Labels: automerge, enhancement, system

#4704 flow.config.enable_mem_chain_merge(val=True)
  oneflow/core/job/intra_job_mem_sharing_util.cpp
  oneflow/core/job/resource.proto
  oneflow/python/framework/config_util.py
Labels: automerge, feature, system

#4700 Relax tolerance for broadcast matmul test
  oneflow/python/test/ops/test_matmul.py
Labels: automerge, bug, op, test

#4692 Support python3 -m oneflow --doctor
  ci/test/1node_op_test.sh
  oneflow/__main__.py
Labels: automerge, enhancement, python

#4691 Feat autograd interface and bug fix
  oneflow/api/python/autograd/autograd.cpp
  oneflow/core/autograd/autograd_engine.cpp
  oneflow/core/autograd/autograd_engine.h
  oneflow/core/common/exception.h
  oneflow/core/framework/tensor.h
  oneflow/core/framework/tensor_impl.h
  oneflow/python/autograd/__init__.py
  oneflow/python/autograd/autograd.py
  oneflow/python/framework/tensor.py
  oneflow/python/framework/tensor_tuple_util.py
Labels: automerge, eager, feature

#4709 Fix layer_norm sbp signature
  oneflow/user/ops/layer_norm_op.cpp
Labels: automerge, bug, op

#4706 Fix spelling error
  oneflow/core/transport/transport.cpp
  oneflow/python/framework/function_util.py
Labels: automerge, bug, python

#4703 Remove outdate use_memory_allocation_algorithm_v2
  oneflow/core/job/job_conf.proto
  oneflow/core/job/job_desc.h
  oneflow/python/framework/function_util.py
Labels: automerge, purge, system

#4714 Add broadcast_matmul to amp white list
  oneflow/core/job_rewriter/auto_mixed_precision_lists.cpp
Labels: automerge, bug, op

#4702 rm useless reshape_op_util
  oneflow/core/operator/reshape_op_util.cpp
  oneflow/core/operator/reshape_op_util.h
Labels: automerge, enhancement, op

#4715 fix docs export bug
  docs/source/conf.py
Labels: automerge, bug, documentation, python

#4710 Fix test threshold in TripletMarginLoss
  oneflow/python/test/ops/test_TripletMarginLoss.py
Labels: automerge, bug, ci, op, python, test

#4693 Use bitset in MakePredicatorIsReachable to reduce memory usage
  oneflow/core/graph/graph.h
Labels: automerge, enhancement, system

#4662 support stashing job after passes
  oneflow/python/framework/compiler.py
  oneflow/python/framework/session_util.py
  oneflow/python/serving/saved_model_builder.py
Labels: automerge, enhancement, python, serving

#4705 Remove MemoryCaseUtil::MergeThrdMemZoneId
  oneflow/core/memory/memory_case_util.cpp
  oneflow/core/memory/memory_case_util.h
Labels: automerge, purge, system

#4684 RepeatOp regst num hacking
  oneflow/core/actor/repeat_compute_actor.cpp
Labels: automerge, enhancement, system

#4559 eager local stateful kernel
  oneflow/core/eager/cpu_opkernel_instruction_type.cpp
  oneflow/core/eager/cuda_opkernel_instruction_type.cpp
  oneflow/core/eager/eager_blob_object.cpp
  oneflow/core/eager/eager_blob_object.h
  oneflow/core/eager/local_call_opkernel_phy_instr_operand.cpp
  oneflow/core/eager/local_call_opkernel_phy_instr_operand.h
  oneflow/core/eager/opkernel_instruction_type.cpp
  oneflow/core/eager/opkernel_instruction_type.h
  oneflow/core/framework/device.cpp
  oneflow/core/framework/device.h
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/framework/instructions_builder.h
  oneflow/core/framework/op_expr.cpp
  oneflow/core/framework/op_expr.h
  oneflow/core/framework/op_interpreter/eager_mirrored_op_interpreter.cpp
  oneflow/core/framework/op_interpreter/op_interpreter_util.cpp
  oneflow/core/framework/op_interpreter/op_interpreter_util.h
  oneflow/core/framework/tensor.h
  oneflow/core/framework/tensor_impl.cpp
  oneflow/core/framework/tensor_impl.h
  oneflow/core/framework/tensor_storage.cpp
  oneflow/core/framework/tensor_storage.h
  oneflow/core/job/parallel_desc.cpp
  oneflow/core/job/parallel_desc.h
  oneflow/core/register/blob_desc.h
  oneflow/core/vm/phy_instr_operand.h
  oneflow/core/vm/stream.cpp
  oneflow/python/test/ops/test_stateful_local_kernel.py
  oneflow/user/kernels/stateful_local_opkernel.cpp
  oneflow/user/kernels/stateful_local_opkernel.h
Labels: automerge, eager, feature, system

#4717 Add instruction to release tensor
  oneflow/core/eager/release_tensor_instruction_type.cpp
  oneflow/core/eager/release_tensor_instruction_type.h
  oneflow/core/vm/release_tensor_arg_phy_instr_operand.cpp
  oneflow/core/vm/release_tensor_arg_phy_instr_operand.h
Labels: automerge, enhancement, system

#4719 Fix bugs encountered by RNN
  oneflow/core/autograd/autograd_engine.cpp
  oneflow/core/autograd/gradient_funcs/default.cpp
  oneflow/core/framework/tensor_arg.cpp
  oneflow/core/framework/tensor_arg.h
Labels: automerge, enhancement, system

#4716 reshape ops infer parallel_distribution
  oneflow/core/framework/infer_parallel_distribution_fn_context.h
  oneflow/core/operator/user_op.cpp
  oneflow/python/test/ops/test_hierarchical_parallel_cast.py
  oneflow/user/ops/reshape_like_op.cpp
  oneflow/user/ops/reshape_op.cpp
  oneflow/user/ops/reshape_user_op_util.cpp
  oneflow/user/ops/reshape_user_op_util.h
Labels: automerge, enhancement, op

#4660 Fused SelfAttention query multipy key and value op
  oneflow/core/job_rewriter/auto_mixed_precision_lists.cpp
  oneflow/python/ops/domain_ops.py
  oneflow/python/test/ops/test_fused_self_attention_query_mul_key_and_value.py
  oneflow/user/kernels/fused_self_attention_query_mul_key_and_value_kernel.cu
  oneflow/user/ops/fused_self_attention_query_mul_key_and_value_ops.cpp
Labels: automerge, enhancement, op

#4722 fix expand op docs bug
  oneflow/python/ops/array_ops.py
Labels: api, automerge, bug, op

#4382 Add diag op
  oneflow/python/ops/diag_ops.py
  oneflow/python/test/ops/test_diag.py
  oneflow/user/kernels/diag_kernel.cpp
  oneflow/user/kernels/diag_kernel.cu
  oneflow/user/kernels/diag_kernel.h
  oneflow/user/ops/diag_op.cpp
Labels: automerge, enhancement, op

#4670 fix mirrored eager tensor with empty parallel desc
  .gitignore
  oneflow/api/python/env/env.cpp
  oneflow/api/python/env/env.h
  oneflow/api/python/env/env_api.h
  oneflow/core/framework/device.cpp
  oneflow/core/framework/device.h
  oneflow/core/job/env.proto
  oneflow/core/job/env_global_objects_scope.cpp
  oneflow/core/job/env_global_objects_scope.h
  oneflow/init.py
  oneflow/python/framework/c_api_util.py
  oneflow/python/framework/env_util.py
Labels: automerge, bottleneck, bug, system

#4733 Change get op attributes to get interface op attributes
  oneflow/api/python/op/op_mgr.cpp
  oneflow/api/python/op/op_mgr.h
  oneflow/api/python/op/op_mgr_api.h
  oneflow/python/framework/c_api_util.py
  oneflow/python/framework/session_util.py
Labels: api, automerge, feature, refactor, system

#4708 Move tasks when pushing plan
  cmake/oneflow.cmake
  oneflow/core/job/oneflow.cpp
  oneflow/core/job/runtime_buffers_scope.cpp
  oneflow/core/job/runtime_buffers_scope.h
  oneflow/core/operator/operator.cpp
Labels: automerge, enhancement, system

#4730 fuse cast scalar_mul scalar_mul_by_tensor
  oneflow/core/job_rewriter/fuse_cast_scale_pass.cpp
  oneflow/python/test/ops/test_fuse_cast_scale.py
  oneflow/user/kernels/fused_cast_scale_kernel.cpp
  oneflow/user/kernels/fused_cast_scale_kernel.cu
  oneflow/user/ops/fused_cast_scale_op.cpp
Labels: automerge, enhancement, system

#4720 dev empty op
  oneflow/user/kernels/empty_kernel.cpp
  oneflow/user/ops/empty_op.cpp
Labels: automerge, enhancement, op

#4737 release tensor by ReleaseTensor instruction
  oneflow/api/python/framework/shut_down_util.cpp
  oneflow/core/eager/eager_blob_object.cpp
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/framework/instructions_builder.h
  oneflow/core/framework/object.h
  oneflow/core/framework/shut_down_util.cpp
  oneflow/core/framework/shut_down_util.h
  oneflow/core/framework/tensor_impl.cpp
  oneflow/core/framework/tensor_storage.cpp
Labels: automerge, eager, enhancement

#4736 Import oneflow in custom_exit
  oneflow/init.py
Labels: automerge, bug, python

#4734 remove SourceIntruction, add ResettingIdToObjectMap, fix bug in ForEachMutMirroredObject4MutPhyInstrOperand
  oneflow/core/vm/control_stream_type.cpp
  oneflow/core/vm/instruction_type.h
  oneflow/core/vm/object_instruction_type.cpp
  oneflow/core/vm/parallel_desc_instruction_type.cpp
  oneflow/core/vm/virtual_machine.cpp
  oneflow/core/vm/virtual_machine.msg.h
Labels: automerge, bug, eager

#4713 Refactor physical run
  oneflow/api/python/framework/foreign_boxing_util.cpp
  oneflow/api/python/framework/instructions_builder.cpp
  oneflow/api/python/symbol/placement_symbol.cpp
  oneflow/core/eager/eager_oneflow.cpp
  oneflow/core/eager/eager_oneflow.h
  oneflow/core/eager/foreign_boxing_util.h
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/framework/instructions_builder.h
  oneflow/core/framework/interpreter.cpp
  oneflow/core/framework/interpreter.h
  oneflow/core/framework/op_interpreter/eager_consistent_op_interpreter.cpp
  oneflow/core/framework/op_interpreter/eager_mirrored_op_interpreter.cpp
  oneflow/core/framework/tensor_impl.cpp
  oneflow/core/job/parallel_desc.cpp
  oneflow/core/vm/vm_util.cpp
Labels: automerge, documentation, eager, refactor, system

#4746 make parameter local for now
  oneflow/python/nn/parameter.py
Labels: automerge, bug, eager

#4743 Replace GetPtrOrThrow by JUST
  oneflow/core/autograd/gradient_funcs/broadcast_binary_ops.cpp
  oneflow/core/framework/op_interpreter/op_interpreter_util.cpp
  oneflow/core/framework/tensor_arg.cpp
  oneflow/core/job/parallel_desc.cpp
Labels: automerge, enhancement, system

#4749 Support add_to_output fusion for broadcast matmul
  oneflow/core/job_rewriter/fuse_add_to_output_pass.cpp
  oneflow/user/kernels/matmul_kernels.cpp
  oneflow/user/ops/matmul_op.cpp
Labels: automerge, enhancement, op

#4727 Refactor namespace eager
  oneflow/core/eager/blob_instruction_type.cpp
  oneflow/core/eager/blob_instruction_type.h
  oneflow/core/eager/blob_object.cpp
  oneflow/core/eager/blob_object.h
  oneflow/core/eager/cpu_blob_instruction_type.cpp
  oneflow/core/eager/cpu_opkernel_instruction_type.cpp
  oneflow/core/eager/cuda_blob_instruction_type.cpp
  oneflow/core/eager/cuda_opkernel_instruction_type.cpp
  oneflow/core/eager/eager_blob_object.cpp
  oneflow/core/eager/eager_blob_object.h
  oneflow/core/eager/eager_instruction.proto
  oneflow/core/eager/eager_oneflow.cpp
  oneflow/core/eager/eager_oneflow.h
  oneflow/core/eager/eager_symbol.proto
  oneflow/core/eager/init_symbol_instruction_type.cpp
  oneflow/core/eager/init_symbol_instruction_type_test.cpp
  oneflow/core/eager/lazy_ref_blob_object.h
  oneflow/core/eager/local_call_opkernel_phy_instr_operand.cpp
  oneflow/core/eager/local_call_opkernel_phy_instr_operand.h
  oneflow/core/eager/opkernel_instruction.msg.h
  oneflow/core/eager/opkernel_instruction_type.cpp
  oneflow/core/eager/opkernel_instruction_type.h
  oneflow/core/eager/opkernel_instruction_type_test.cpp
  oneflow/core/eager/opkernel_object.cpp
  oneflow/core/eager/opkernel_object.h
  oneflow/core/eager/release_tensor_instruction_type.cpp
  oneflow/core/eager/release_tensor_instruction_type.h
  oneflow/core/eager/remove_foreign_callback_instruction_type.cpp
  oneflow/core/eager/transport_blob_instruction_type.cpp
  oneflow/core/eager/transport_blob_instruction_type.h
  oneflow/core/eager/transport_blob_instruction_type_test.cpp
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/framework/instructions_builder.h
  oneflow/core/framework/interpreter.cpp
  oneflow/core/framework/interpreter.h
  oneflow/core/framework/op_interpreter/eager_mirrored_op_interpreter.cpp
  oneflow/core/framework/op_interpreter/eager_mirrored_op_interpreter.h
  oneflow/core/framework/op_interpreter/op_interpreter_util.cpp
  oneflow/core/framework/op_interpreter/op_interpreter_util.h
  oneflow/core/framework/session_util.cpp
  oneflow/core/framework/session_util.h
  oneflow/core/framework/tensor.cpp
  oneflow/core/framework/tensor.h
  oneflow/core/framework/tensor_impl.cpp
  oneflow/core/framework/tensor_impl.h
  oneflow/core/framework/tensor_storage.cpp
  oneflow/core/framework/tensor_storage.h
  oneflow/core/job/cluster.cpp
  oneflow/core/job/cluster_instruction.proto
  oneflow/core/vm/access_blob_arg_cb_phy_instr_operand.h
  oneflow/core/vm/read_tensor_shape_arg_cb_phy_instr_operand.h
  oneflow/core/vm/release_tensor_arg_phy_instr_operand.h
  oneflow/user/kernels/stateful_local_opkernel.cpp
  oneflow/user/kernels/stateful_local_opkernel.h
Labels: automerge, eager, enhancement, refactor

#4745 stateful local kernel supports dynamic attrs
  oneflow/core/eager/local_call_opkernel_phy_instr_operand.h
  oneflow/core/eager/opkernel_instruction_type.cpp
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/framework/instructions_builder.h
  oneflow/core/framework/op_expr.cpp
  oneflow/core/framework/op_interpreter/eager_mirrored_op_interpreter.cpp
  oneflow/core/framework/op_kernel.h
  oneflow/core/framework/user_op_kernel_registry.h
  oneflow/core/kernel/user_kernel.cpp
  oneflow/core/operator/user_op.cpp
  oneflow/python/test/ops/test_stateful_local_kernel.py
  oneflow/user/kernels/stateful_local_opkernel.cpp
  oneflow/user/kernels/stateful_local_opkernel.h
Labels: automerge, eager, enhancement, system

#4742 Add resnet linear module
  oneflow/python/nn/init.py
  oneflow/python/nn/modules/linear.py
  oneflow/python/test/modules/test_linear.py
Labels: automerge, feature, op, python

#4741 New eager test for interface 1.0
  .github/workflows/test.yml
  ci/test/1node_op_test.sh
  ci/test/1node_test.sh
  ci/test/parallel_run.py
  oneflow/python/nn/module.py
  oneflow/python/test/modules/test_module.py
  oneflow/python/test/modules/test_util.py
  oneflow/python/test/tensor/test_tensor.py
Labels: automerge, ci, enhancement

#4750 remove useless register func in tensor
  oneflow/python/framework/tensor.py
Labels: automerge, enhancement, system

#4712 fix summary_graph bug
  oneflow/python/summary/summary_graph.py
  oneflow/python/test/ops/test_summary.py
Labels: automerge, bug, python, test

#4757 fix tmp_buffer in stateful local kernel
  oneflow/user/kernels/stateful_local_opkernel.cpp
  oneflow/user/kernels/stateful_local_opkernel.h
Labels: automerge, bug, eager

#4623 Add nn.AvgPool2d Module
  oneflow/python/nn/modules/pooling.py
  oneflow/python/test/modules/test_avgpool2d_module.py
Labels: automerge, enhancement, op

#4751 add exp_tanh_gelu module
  oneflow/python/nn/modules/activation.py
  oneflow/python/nn/modules/exp.py
  oneflow/python/test/modules/test_activation.py
  oneflow/python/test/modules/test_exp.py
Labels: api, automerge, feature, op

#4725 Lml/mem optimize
  oneflow/core/graph/task_node.cpp
  oneflow/core/job/compiler.cpp
  oneflow/core/job/oneflow.cpp
  oneflow/core/operator/operator.cpp
Labels: automerge, enhancement, system

#4771 add default dtype for oneflow range
  oneflow/python/ops/math_ops.py
Labels: automerge, bug, op, python

#4770 b21 boxing add ctrl_edge
  oneflow/core/graph/boxing/b21_sub_task_graph_builder.cpp
Labels: automerge, enhancement, system

#4762 model_io_v2 process multi variable
  oneflow/core/job/model_io_v2_job.cpp
  oneflow/core/kernel/model_io_v2_kernel.cpp
  oneflow/core/operator/model_io_v2_op.cpp
  oneflow/core/operator/op_conf.proto
Labels: automerge, enhancement, system

#4756 add greater_less_argmax module
  oneflow/python/nn/modules/argmax.py
  oneflow/python/nn/modules/greater.py
  oneflow/python/nn/modules/less.py
  oneflow/python/nn/modules/squeeze.py
  oneflow/python/nn/modules/transpose.py
  oneflow/python/test/modules/test_argmax.py
  oneflow/python/test/modules/test_greater.py
  oneflow/python/test/modules/test_less.py
  oneflow/python/test/modules/test_squeeze.py
  oneflow/python/test/modules/test_transpose.py
Labels: automerge, feature, op, python

#4774 Fix NcclLogicalS2S kernel comm BUG.
  oneflow/user/kernels/nccl_logical_kernels.cpp
Labels: automerge, bug, op

#4759 Add flatten module and unit test
  oneflow/python/nn/modules/flatten.py
  oneflow/python/test/modules/test_flatten.py
Labels: automerge, eager, enhancement, op, python

#4772 NCCL logical op support S1 to B
  oneflow/core/job_rewriter/insert_nccl_logical_op_pass.cpp
  oneflow/user/kernels/nccl_logical_2d_sbp_kernels.cpp
  oneflow/user/kernels/nccl_logical_kernels.cpp
  oneflow/user/ops/nccl_logical_ops.cpp
Labels: automerge, feature, op, system

#4768 fix bug about pos_weight
  oneflow/python/ops/nn_ops.py
Labels: automerge, bug, op, python

#4766 Create default log under log dir
  .gitignore
  oneflow/core/job/env.proto
  oneflow/core/job/env_global_objects_scope.cpp
Labels: automerge, build, enhancement

#4755 Dev refactor attr value map
  oneflow/api/python/framework/attr_map.cpp
  oneflow/api/python/framework/op_expr.cpp
  oneflow/core/autograd/gradient_funcs/batch_gather.cpp
  oneflow/core/autograd/gradient_funcs/bias_add.cpp
  oneflow/core/autograd/gradient_funcs/broadcast_binary_ops.cpp
  oneflow/core/autograd/gradient_funcs/cast.cpp
  oneflow/core/autograd/gradient_funcs/deconv.cpp
  oneflow/core/autograd/gradient_funcs/default.cpp
  oneflow/core/autograd/gradient_funcs/layer_norm.cpp
  oneflow/core/autograd/gradient_funcs/normalization.cpp
  oneflow/core/autograd/gradient_funcs/reshape.cpp
  oneflow/core/autograd/gradient_funcs/split_like.cpp
  oneflow/core/autograd/gradient_funcs/tensor_scalar_binary.cpp
  oneflow/core/common/shape.cpp
  oneflow/core/common/shape.h
  oneflow/core/eager/local_call_opkernel_phy_instr_operand.h
  oneflow/core/framework/attr_map.cpp
  oneflow/core/framework/attr_map.h
  oneflow/core/framework/attr_value_accessor.cpp
  oneflow/core/framework/attr_value_accessor.h
  oneflow/core/framework/attr_value_map.cpp
  oneflow/core/framework/attr_value_map.h
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/framework/instructions_builder.h
  oneflow/core/framework/op_expr.cpp
  oneflow/core/framework/op_expr.h
  oneflow/core/framework/op_expr_grad_function.h
  oneflow/core/framework/op_interpreter.h
  oneflow/core/framework/op_interpreter/eager_consistent_op_interpreter.cpp
  oneflow/core/framework/op_interpreter/eager_mirrored_op_interpreter.cpp
  oneflow/core/framework/op_interpreter/op_interpreter.cpp
  oneflow/core/framework/op_interpreter/op_interpreter_util.cpp
  oneflow/core/framework/op_interpreter/op_interpreter_util.h
  oneflow/core/framework/user_op_conf_trait.h
  oneflow/python/framework/op_expr_util.py
  oneflow/user/kernels/stateful_local_opkernel.cpp
  oneflow/user/kernels/stateful_local_opkernel.h
Labels: automerge, enhancement, refactor, system

#4763 Upgrade cares to support cmake 3.19 or higher
  cmake/third_party/cares.cmake
Labels: automerge, build, enhancement

#4744 Dev merge modules
  oneflow/python/nn/modules/activation.py
  oneflow/python/nn/modules/batchnorm.py
  oneflow/python/nn/modules/constant.py
  oneflow/python/nn/modules/math_ops.py
  oneflow/python/nn/modules/pooling.py
  oneflow/python/test/modules/test_activation.py
  oneflow/python/test/modules/test_batchnorm.py
  oneflow/python/test/modules/test_constant.py
  oneflow/python/test/modules/test_math_ops.py
  oneflow/python/test/modules/test_pooling.py
Labels: automerge, eager, enhancement, op
