Repository Oneflow-Inc/oneflow, pull requests merged in 2021-11, with the labels that each got.

#6652 optional: add monadic operations `map`, `bind` and `or_else`
  oneflow/core/common/optional.h
  oneflow/core/common/optional_test.cpp
Labels: enhancement, automerge, system

#6640 Optimize Dropout
  oneflow/user/kernels/dropout_kernel.cu
  oneflow/user/kernels/narrow_kernel.cpp
  oneflow/user/kernels/narrow_util.cpp
  oneflow/user/kernels/narrow_util.cu
  oneflow/user/kernels/narrow_util.h
Labels: enhancement, feature, automerge, op

#6661 Add --inplace in readme build wheel script docs
  README.md
Labels: automerge, bug, documentation, build

#6387 migrate parital fc op from lazy to functor
  oneflow/core/autograd/gradient_funcs/partial_fc_sample.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/user/kernels/partial_fc_sample_kernel.cu
  python/oneflow/__init__.py
  python/oneflow/test/modules/test_parital_fc.py
Labels: enhancement, automerge, op

#6664 update speed test threshold
  ci/test/test_speed_multi_client.sh
Labels: enhancement, automerge, ci

#6667 just macro: rename local variables to prevent shadowing
  oneflow/core/common/just.h
Labels: enhancement, automerge, system

#6634 restruct reshape gradient funcs
  oneflow/core/autograd/gradient_funcs/reshape.cpp
Labels: enhancement, bug, eager, api

#6673 Fix model update pass adam
  oneflow/core/job_rewriter/fuse_update_ops_pass.cpp
Labels: automerge, bug, op

#6671 adjust GILForeignLockHelper order to avoid glog print to stderr
  python/oneflow/__init__.py
Labels: automerge, bug, system

#6677 Reduce memory usage for broadcast binary ops backward
  oneflow/core/autograd/gradient_funcs/broadcast_binary_ops.cpp
Labels: enhancement, automerge, system

#6680 update speed test threshold
  ci/test/test_speed_multi_client.sh
Labels: enhancement, automerge, ci

#6679 make block methods more private to reduce conflicts with module
  python/oneflow/nn/graph/block.py
Labels: enhancement, automerge, bug, python, graph

#6528 save/load by pickle, update placement ctor
  oneflow/api/python/symbol/placement_symbol.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/check_point_v2.py
  python/oneflow/framework/tensor.py
  python/oneflow/test/modules/test_module.py
  python/oneflow/test/modules/test_optim_adagrad.py
  python/oneflow/test/modules/test_optim_adam.py
  python/oneflow/test/modules/test_optim_adamw.py
  python/oneflow/test/modules/test_optim_rmsprop.py
  python/oneflow/test/modules/test_optim_sgd.py
Labels: feature, automerge, bug, python

#6647 Event pool
  oneflow/core/common/cpp_attribute.h
  oneflow/core/common/single_thread_obj_pool.h
  oneflow/core/common/single_thread_obj_pool_test.cpp
  oneflow/core/common/util.h
  oneflow/core/device/cuda_event.cpp
  oneflow/core/device/cuda_event.h
  oneflow/core/eager/blob_instruction_type.h
  oneflow/core/eager/cuda_blob_instruction_type.cpp
  oneflow/core/eager/opkernel_instruction_type.cpp
  oneflow/core/eager/opkernel_instruction_type.h
  oneflow/core/intrusive/shared_ptr.h
  oneflow/core/vm/async_cuda_stream_type.cpp
  oneflow/core/vm/async_cuda_stream_type.h
  oneflow/core/vm/cpu_stream_type.cpp
  oneflow/core/vm/cuda_copy_d2h_device_context.h
  oneflow/core/vm/cuda_copy_d2h_stream_type.cpp
  oneflow/core/vm/cuda_copy_d2h_stream_type.h
  oneflow/core/vm/cuda_copy_h2d_stream_type.cpp
  oneflow/core/vm/cuda_copy_h2d_stream_type.h
  oneflow/core/vm/cuda_instruction_status_querier.cpp
  oneflow/core/vm/cuda_instruction_status_querier.h
  oneflow/core/vm/cuda_optional_event_record_status_querier.cpp
  oneflow/core/vm/cuda_optional_event_record_status_querier.h
  oneflow/core/vm/cuda_stream_handle_device_context.h
  oneflow/core/vm/cuda_stream_type.cpp
  oneflow/core/vm/cuda_stream_type.h
  oneflow/core/vm/instruction.cpp
  oneflow/core/vm/instruction.h
  oneflow/core/vm/instruction_type.h
  oneflow/core/vm/stream.cpp
  oneflow/core/vm/stream_type.cpp
  oneflow/core/vm/stream_type.h
  oneflow/core/vm/virtual_machine.cpp
  oneflow/user/kernels/stateful_local_opkernel.h
Labels: enhancement, automerge, system

#6665 graph debug with more detailed info
  oneflow/core/framework/op_interpreter/lazy_op_interpreter.cpp
  python/oneflow/nn/graph/graph.py
Labels: feature, automerge, tooling, graph

#6684 Fix permute.cu static_assert
  oneflow/core/primitive/cuda/permute.cu
Labels: automerge, bug, system, need-clean-ccache

#6681 IsMultiClient returns Maybe<bool>
  oneflow/core/common/multi_client.h
  oneflow/core/framework/interpreter_test.cpp
  oneflow/core/kernel/callback_notify_kernel.cpp
  oneflow/core/kernel/input_kernel.cpp
  oneflow/core/kernel/output_kernel.cpp
  oneflow/core/kernel/return_kernel.cpp
  oneflow/core/kernel/wait_and_send_ids_kernel.cpp
  oneflow/core/vm/oneflow_vm.cpp
Labels: enhancement, automerge, build

#6663 Refactor id_util.h
  oneflow/core/actor/actor.cpp
  oneflow/core/actor/actor.h
  oneflow/core/actor/actor_message.cpp
  oneflow/core/actor/actor_message_bus.cpp
  oneflow/core/actor/copy_comm_net_actor.cpp
  oneflow/core/actor/light_actor.cpp
  oneflow/core/common/id_util.h
  oneflow/core/device/device_id.h
  oneflow/core/device/stream_index.h
  oneflow/core/graph/boxing/collective_boxing_sub_task_graph_builder.cpp
  oneflow/core/graph/boxing/naive_b2p_sub_task_graph_builder.cpp
  oneflow/core/graph/boxing/slice_boxing_sub_task_graph_builder.cpp
  oneflow/core/graph/copy_task_node.cpp
  oneflow/core/graph/id_serialization.cpp
  oneflow/core/graph/id_serialization.h
  oneflow/core/graph/slice_boxing_task_node.cpp
  oneflow/core/graph/stream_index_getter_registry_manager.h
  oneflow/core/graph/task_graph.cpp
  oneflow/core/graph/task_id.cpp
  oneflow/core/graph/task_id.h
  oneflow/core/graph/task_id_generator.h
  oneflow/core/graph/task_node.cpp
  oneflow/core/job/id_manager.cpp
  oneflow/core/job/id_manager.h
  oneflow/core/job/plan_util.cpp
  oneflow/core/job/plan_util.h
  oneflow/core/memory/memory_zone.cpp
  oneflow/core/memory/memory_zone.h
  oneflow/core/stream/cpu_stream_context.cpp
  oneflow/core/stream/cuda_graph_context.h
  oneflow/core/stream/cuda_stream_context.cpp
  oneflow/core/stream/cuda_stream_context.h
  oneflow/core/stream/stream_context.h
  oneflow/core/stream/stream_id.cpp
  oneflow/core/stream/stream_id.h
  oneflow/core/thread/thread.cpp
  oneflow/core/thread/thread_manager.cpp
Labels: enhancement, automerge, system, need-clean-ccache

#6685 Fix tensor deepcopy
  python/oneflow/framework/check_point_v2.py
  python/oneflow/test/tensor/test_tensor.py
Labels: automerge, bug, python

#6678 remove_onehot_consistent_tensor_limit
  oneflow/core/functional/impl/nn_functor.cpp
Labels: bottleneck, automerge, bug, eager, interface

#6676 Remove CollectiveBoxingDeviceCtx
  oneflow/core/actor/actor.cpp
  oneflow/core/actor/actor_context.h
  oneflow/core/actor/collective_boxing_actor_context.cpp
  oneflow/core/actor/collective_boxing_actor_context.h
  oneflow/core/actor/generic_actor_context.cpp
  oneflow/core/actor/generic_actor_context.h
  oneflow/core/actor/light_actor.cpp
  oneflow/core/device/collective_boxing_device_context.cpp
  oneflow/core/device/collective_boxing_device_context.h
  oneflow/core/framework/multi_client_session_context.cpp
  oneflow/core/job/collective_boxing/scheduler.h
  oneflow/core/job/collective_boxing_device_ctx_poller.cpp
  oneflow/core/job/collective_boxing_device_ctx_poller.h
  oneflow/core/job/session_global_objects_scope.cpp
  oneflow/core/kernel/collective_boxing_kernels.cpp
Labels: enhancement, automerge, system, need-clean-ccache

#6693 Reorganize dir oneflow/core/stream
  cmake/oneflow.cmake
  oneflow/core/actor/actor.cpp
  oneflow/core/actor/actor_context.h
  oneflow/core/actor/light_actor.cpp
  oneflow/core/device/device_context_adapter.cpp
  oneflow/core/device/device_context_adapter.h
  oneflow/core/device/stream_index.h
  oneflow/core/eager/opkernel_object.h
  oneflow/core/framework/op_kernel.h
  oneflow/core/graph/stream_id.cpp
  oneflow/core/graph/stream_id.h
  oneflow/core/graph/task_id.h
  oneflow/core/job/plan_util.h
  oneflow/core/kernel/kernel_context.h
  oneflow/core/kernel/kernel_util.cpp
  oneflow/core/kernel/model_io_v2_kernel.cpp
  oneflow/core/kernel/user_kernel.cpp
  oneflow/core/kernel/user_kernel.h
  oneflow/core/persistence/snapshot.cpp
  oneflow/core/primitive/cuda/add.cu
  oneflow/core/primitive/cuda/broadcast_matmul.cpp
  oneflow/core/primitive/cuda/cast.cu
  oneflow/core/primitive/cuda/copy_nd.cu
  oneflow/core/primitive/cuda/fill.cu
  oneflow/core/primitive/cuda/memcpy.cpp
  oneflow/core/primitive/cuda/memset.cpp
  oneflow/core/primitive/cuda/permute.cu
  oneflow/core/primitive/cuda/softmax.cu
  oneflow/core/primitive/cuda/softmax_backward.cu
  oneflow/core/primitive/include/primitive.h
  oneflow/core/profiler/kernel.cpp
  oneflow/core/stream/common/stream_context_adapter.cpp
  oneflow/core/stream/cpu/cpu_stream_context.cpp
  oneflow/core/stream/cuda/cuda_graph_context.cpp
  oneflow/core/stream/cuda/cuda_graph_context.h
  oneflow/core/stream/cuda/cuda_stream_context.cpp
  oneflow/core/stream/cuda/cuda_stream_context.h
  oneflow/core/stream/include/execution_context_hook.h
  oneflow/core/stream/include/stream_context.h
  oneflow/core/stream/include/stream_context_adapter.h
  oneflow/core/thread/thread.cpp
  oneflow/user/kernels/stateful_local_opkernel.cpp
Labels: enhancement, automerge, system, need-clean-ccache

#6694 Refine cuda memory allocation strategy and some grad func to reduce memory occupy
  oneflow/core/autograd/gradient_funcs/bias_add.cpp
  oneflow/core/autograd/gradient_funcs/narrow.cpp
  oneflow/core/autograd/gradient_funcs/unsqueeze.cpp
  oneflow/core/vm/cuda_allocator.cpp
Labels: enhancement, automerge, system

#6691 fix bug construct tensor from numpy
  oneflow/api/python/utils/tensor_utils.cpp
  python/oneflow/test/tensor/test_tensor.py
Labels: automerge, bug, system

#6688 Add functional fused tril scale softmax dropout kernel
  oneflow/core/autograd/gradient_funcs/fused_scale_tril_softmax_mask_scale.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/core/functional/impl/nn_grad_functor.cpp
  python/oneflow/test/modules/test_fused_tril_softmax_mask_scale.py
Labels: enhancement, automerge, op

#6692 Support fork process
  oneflow/core/device/cuda_util.cpp
  oneflow/core/platform/include/pthread_fork.h
  oneflow/core/platform/lib/pthread_fork.cpp
  oneflow/core/thread/thread_manager.h
  oneflow/core/vm/oneflow_vm.cpp
  oneflow/core/vm/virtual_machine.cpp
  oneflow/core/vm/virtual_machine.h
  python/oneflow/test/modules/test_fork_sub_process.py
Labels: enhancement, automerge, system, need-clean-ccache

#6701 support fork
  python/oneflow/test/dataloader/test_cifar_dataset_multiprocess.py
  python/oneflow/test/dataloader/test_cifar_dataset_singleprocess.py
  python/oneflow/utils/data/dataloader.py
Labels: enhancement, automerge, eager, api

#6703 Print out sorted SBP for op graph
  oneflow/core/graph/op_graph.cpp
  oneflow/core/graph/op_graph.h
Labels: AutoParallel

#6697 Remove NewKernelUtil::Fill
  oneflow/core/job/collective_boxing/nccl_executor_backend.cu
  oneflow/core/kernel/batch_memcpy_kernel_util.cpp
  oneflow/core/kernel/batch_memcpy_kernel_util.cu
  oneflow/core/kernel/batch_memcpy_kernel_util.h
  oneflow/core/kernel/case_kernel.cpp
  oneflow/core/kernel/esac_kernel.cpp
  oneflow/core/kernel/shape_elem_cnt_kernel.cpp
  oneflow/core/kernel/util/cuda_arithemetic_interface.cu
  oneflow/core/kernel/util/cuda_arithemetic_interface.h
  oneflow/core/kernel/util/host_arithemetic_interface.cpp
  oneflow/core/kernel/util/host_arithemetic_interface.h
  oneflow/user/kernels/arg_where_kernel_util.cpp
  oneflow/user/kernels/arg_where_kernel_util.cu
  oneflow/user/kernels/constant_kernel.cpp
  oneflow/user/kernels/layer_norm_gpu_kernel.cu
  oneflow/user/kernels/one_hot_kernel.cpp
  oneflow/user/kernels/ones_like_kernel.cpp
  oneflow/user/kernels/reduce_kernel.cpp
  oneflow/user/kernels/reduce_like_kernels.cpp
  oneflow/user/kernels/test_kernels.cpp
Labels: enhancement, automerge, system, need-clean-ccache

#6687 Add implementation of batchnorm cpu kernel
  oneflow/user/kernels/normalization_kernel.cpp
  python/oneflow/nn/modules/batchnorm.py
  python/oneflow/nn/modules/batchnorm_fused.py
  python/oneflow/test/modules/test_batchnorm_add_relu.py
Labels: enhancement, automerge, eager, op, python

#6654 Add resnet50 mlir dialect part2
  oneflow/ir/include/OneFlow/OneFlowOps.td
  oneflow/ir/lib/OneFlow/OneFlowOps.cpp
Labels: feature, automerge, system

#6675 Add fuse patterns for BERT in MLIR
  .github/workflows/pr.yml
  CMakeLists.txt
  cmake/caches/ci/cuda.cmake
  cmake/oneflow.cmake
  oneflow/api/python/flags.cpp
  oneflow/core/job/job_build_and_infer_ctx.cpp
  oneflow/core/job_rewriter/ir_pass.cpp
  oneflow/ir/CMakeLists.txt
  oneflow/ir/include/OneFlow/OneFlowOps.td
  oneflow/ir/include/OneFlow/Passes.h
  oneflow/ir/include/OneFlow/Transform/OutlineAndFuse.h
  oneflow/ir/lib/OneFlow/CMakeLists.txt
  oneflow/ir/lib/OneFlow/Conversion/PTXToCubin.cpp
  oneflow/ir/lib/OneFlow/OneFlowOps.cpp
  oneflow/ir/lib/OneFlow/Passes.cpp
  oneflow/ir/lib/OneFlow/Transform/OutlineAndFuse.cpp
  oneflow/ir/oneflow-extension/CMakeLists.txt
  oneflow/ir/oneflow-extension/extension.cpp
  oneflow/ir/oneflow-opt/oneflow-opt.cpp
  oneflow/ir/oneflow-translate/lib/OneFlow/MLIROneFlowTranslation.cpp
  oneflow/ir/test/OneFlow/CUDA/lit.local.cfg
  oneflow/ir/test/OneFlow/test_fuse_cast_scale.mlir
  oneflow/ir/test/OneFlow/test_fuse_cast_scale.py
  oneflow/ir/test/OneFlow/test_fuse_tril_scale.py
  oneflow/ir/test/lit.cfg.py
  oneflow/ir/test/lit.site.cfg.py.in
  python/oneflow/__main__.py
  python/oneflow/compatible/single_client/sysconfig.py
  python/oneflow/sysconfig.py
  tools/generate_pip_version.py
Labels: feature, automerge, system

#6698 fix chunk
  python/oneflow/nn/modules/chunk.py
Labels: automerge, bug, op

#6696 fix quick start
  README.md
Labels: automerge, op, documentation

#6708 fix ssd 0shape
  oneflow/user/kernels/dim_gather_kernels.cpp
  oneflow/user/kernels/heap_selection_top_k_kernel.cu
  oneflow/user/kernels/radix_sort_top_k_kernel.cu
  oneflow/user/kernels/top_k_kernel.cpp
Labels: automerge, bug, op

#6705 kernel use softmax/logsoftmax primitive
  oneflow/user/kernels/log_softmax_kernel.cpp
  oneflow/user/kernels/log_softmax_kernel.cu
  oneflow/user/kernels/softmax_cross_entropy_kernel.h
  oneflow/user/kernels/softmax_kernel.cpp
  oneflow/user/kernels/softmax_kernel.cu
  oneflow/user/kernels/softmax_kernel_util.cpp
  oneflow/user/kernels/softmax_kernel_util.cu
  oneflow/user/kernels/softmax_kernel_util.h
  oneflow/user/kernels/sparse_softmax_cross_entropy_kernel.cpp
Labels: enhancement, automerge, op

#6714 add build_profile for ci
  .github/workflows/release.yml
Labels: enhancement, ci, build

#6715 Remove NewKernelUtil::Transpose
  oneflow/core/kernel/collective_boxing_pack_kernel.cpp
  oneflow/core/kernel/collective_boxing_unpack_kernel.cpp
  oneflow/core/kernel/util/cuda_arithemetic_interface.cu
  oneflow/core/kernel/util/cuda_arithemetic_interface.h
  oneflow/core/kernel/util/host_arithemetic_interface.cpp
  oneflow/core/kernel/util/host_arithemetic_interface.h
  oneflow/user/kernels/eager_nccl_kernels.cpp
  oneflow/user/kernels/eager_nccl_kernels.cu
  oneflow/user/kernels/fused_self_attention_query_mul_key_and_value_kernel.cu
  oneflow/user/kernels/nccl_logical_2d_sbp_kernels.cpp
  oneflow/user/kernels/nccl_logical_kernels.cpp
Labels: enhancement, automerge, system, need-clean-ccache

#6718 Align with torch with double data type
  oneflow/user/kernels/normalization_kernel.cpp
Labels: enhancement, automerge, op, refactor

#6724 Support op compute compute_complexity function
  oneflow/core/auto_parallel/sbp_constructor.cpp
  oneflow/core/framework/compute_complexity_fn_context.h
  oneflow/core/framework/framework.h
  oneflow/core/framework/infer_nd_sbp_fn_context.h
  oneflow/core/framework/user_op_registry.cpp
  oneflow/core/framework/user_op_registry.h
  oneflow/core/graph/op_graph.cpp
  oneflow/core/operator/operator.cpp
  oneflow/core/operator/operator.h
  oneflow/core/operator/user_op.cpp
  oneflow/core/operator/user_op.h
Labels: feature, AutoParallel

#6719 check cublas version
  oneflow/core/stream/cuda/cuda_stream_context.cpp
Labels: enhancement, automerge, system, need-clean-ccache

#6723 Fix cublas gemm algo
  oneflow/core/primitive/cuda/broadcast_matmul.cpp
Labels: automerge, bug, op, need-clean-ccache

#6721 delete meshgrid Module
  python/oneflow/framework/docstr/__init__.py
  python/oneflow/framework/docstr/meshgrid.py
  python/oneflow/nn/modules/meshgrid.py
Labels: enhancement, automerge, bug, ci, eager, interface

#6727 Modified MultiThreadLoop
  oneflow/core/thread/thread_manager.h
Labels: enhancement, automerge, system

#6720 Fix auto fmt
  .github/workflows/test.yml
Labels: automerge, bug, ci

#6726 use threadpool in element-wise cpu kernel
  oneflow/user/kernels/math_binary_elementwise_kernel.cpp
  oneflow/user/kernels/math_unary_elementwise_kernel.cpp
  oneflow/user/kernels/slice_util.cpp
Labels: enhancement, automerge, eager, op

#6728 reshape sbp for 0d tensor
  .github/workflows/simple.yml
  .github/workflows/test.yml
  oneflow/user/ops/reshape_user_op_util.cpp
Labels: automerge, bug, op

#6729 fix_segmentation_fault_at_exit
  .github/workflows/test.yml
  oneflow/api/python/utils/tensor_utils.h
Labels: automerge, bug, system, need-clean-ccache

#6731 support len(tensor)
  python/oneflow/framework/tensor.py
  python/oneflow/test/tensor/test_tensor.py
Labels: enhancement, feature, automerge, eager, api

#6732 Fix SimplifyPermutation
  oneflow/core/primitive/common/permute.h
  oneflow/core/primitive/common/permute_test.cpp
  oneflow/core/primitive/cuda/permute.cu
Labels: automerge, bug, op, need-clean-ccache

#6710 fix int constant in data_type.h
  oneflow/core/common/data_type.h
Labels: automerge, bug, system

#6657 Fix missing functor autograd - part 1
  oneflow/api/python/autograd/autograd.cpp
  oneflow/core/autograd/gradient_funcs/consistent_cast.cpp
  oneflow/core/autograd/gradient_funcs/ctc_loss.cpp
  oneflow/core/autograd/gradient_funcs/deconv.cpp
  oneflow/core/autograd/gradient_funcs/dim_gather.cpp
  oneflow/core/autograd/gradient_funcs/dim_scatter.cpp
  oneflow/core/autograd/gradient_funcs/eager_nccl_broadcast.cpp
  oneflow/core/autograd/gradient_funcs/expand.cpp
  oneflow/core/autograd/gradient_funcs/fused_bias_add_dropout.cpp
  oneflow/core/autograd/gradient_funcs/gather.cpp
  oneflow/core/autograd/gradient_funcs/roll.cpp
  oneflow/core/autograd/gradient_funcs/softmax.cpp
  oneflow/core/autograd/gradient_funcs/sparse_softmax_cross_entropy.cpp
  oneflow/core/autograd/gradient_funcs/tensor_scalar_binary.cpp
  oneflow/core/autograd/gradient_funcs/upsample.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/activation_functor.cpp
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/core/functional/impl/consistent_cast.cpp
  oneflow/core/functional/impl/nn_grad_functor.cpp
Labels: enhancement, automerge, system

#6597 improve performance of vm empty schedule
  oneflow/core/eager/blob_instruction_type.cpp
  oneflow/core/eager/critical_section_stream_type.h
  oneflow/core/eager/init_symbol_instruction_type_test.cpp
  oneflow/core/eager/lazy_job_stream_type.h
  oneflow/core/eager/local_dep_object.cpp
  oneflow/core/eager/local_dep_object.h
  oneflow/core/eager/opkernel_instruction_type_test.cpp
  oneflow/core/intrusive/mutexed_list.h
  oneflow/core/vm/async_cuda_stream_type.h
  oneflow/core/vm/control_stream_type.cpp
  oneflow/core/vm/control_stream_type.h
  oneflow/core/vm/control_stream_type_test.cpp
  oneflow/core/vm/cpu_stream_type.h
  oneflow/core/vm/cuda_copy_d2h_stream_type.h
  oneflow/core/vm/cuda_copy_h2d_stream_type.h
  oneflow/core/vm/cuda_stream_type.h
  oneflow/core/vm/device_helper_stream_type.h
  oneflow/core/vm/host_stream_type.h
  oneflow/core/vm/infer_stream_type.h
  oneflow/core/vm/instruction.h
  oneflow/core/vm/instruction_type.cpp
  oneflow/core/vm/instruction_type.h
  oneflow/core/vm/object_instruction_type.cpp
  oneflow/core/vm/object_instruction_type_test.cpp
  oneflow/core/vm/oneflow_vm.cpp
  oneflow/core/vm/oneflow_vm.h
  oneflow/core/vm/parallel_desc_instruction_type.cpp
  oneflow/core/vm/sequential_instruction_type.cpp
  oneflow/core/vm/sequential_instruction_type_test.cpp
  oneflow/core/vm/stream_type.cpp
  oneflow/core/vm/stream_type.h
  oneflow/core/vm/string_instruction_type_test.cpp
  oneflow/core/vm/transport_stream_type.h
  oneflow/core/vm/virtual_machine_engine.cpp
  oneflow/core/vm/virtual_machine_engine.h
  oneflow/core/vm/virtual_machine_engine_test.cpp
  oneflow/core/vm/virtual_machine_scope.cpp
  oneflow/core/vm/vm_desc.h
  oneflow/core/vm/vm_object.h
Labels: enhancement, automerge, system, need-clean-ccache

#6734 Add conv/pooling/matmul/softmax cost function and auto-parallel config api
  oneflow/user/ops/avg_pooling_op.cpp
  oneflow/user/ops/conv_op.cpp
  oneflow/user/ops/matmul_op.cpp
  oneflow/user/ops/pool_op.cpp
  oneflow/user/ops/pooling_op.cpp
  oneflow/user/ops/softmax_op.cpp
  python/oneflow/nn/graph/graph_config.py
Labels: feature, AutoParallel

#6744 Fix cudaErrorCudartUnloading error
  oneflow/core/framework/random_generator_impl.cpp
Labels: enhancement, automerge, bug, system

#6745 undo element-wise threadloop
  oneflow/user/kernels/math_binary_elementwise_kernel.cpp
  oneflow/user/kernels/math_unary_elementwise_kernel.cpp
  oneflow/user/kernels/slice_util.cpp
Labels: enhancement, automerge, system

#6747 Use static_cast to convert StreamContext
  oneflow/core/device/device_context_adapter.cpp
  oneflow/core/primitive/cuda/add.cu
  oneflow/core/primitive/cuda/broadcast_matmul.cpp
  oneflow/core/primitive/cuda/cast.cu
  oneflow/core/primitive/cuda/copy_nd.cu
  oneflow/core/primitive/cuda/elementwise_unary.cu
  oneflow/core/primitive/cuda/fill.cu
  oneflow/core/primitive/cuda/memcpy.cpp
  oneflow/core/primitive/cuda/memset.cpp
  oneflow/core/primitive/cuda/permute.cu
  oneflow/core/primitive/cuda/softmax.cu
  oneflow/core/primitive/cuda/softmax_backward.cu
  oneflow/core/stream/include/stream_context.h
Labels: enhancement, automerge, system, need-clean-ccache

#6749 Auto parallel/merge sbp collector
  oneflow/core/auto_parallel/sbp_collector.cpp
  oneflow/core/auto_parallel/sbp_collector.h
  oneflow/core/auto_parallel/sbp_constructor.cpp
  oneflow/core/auto_parallel/sbp_constructor.h
  oneflow/core/auto_parallel/sbp_edge.h
  oneflow/core/auto_parallel/sbp_graph.h
  oneflow/core/auto_parallel/sbp_node.h
  oneflow/core/job_rewriter/auto_parallel.cpp
Labels: AutoParallel

#6752 Support mainstem algorithm
  oneflow/core/auto_parallel/sbp_constructor.cpp
  oneflow/core/auto_parallel/sbp_constructor.h
  oneflow/core/job/job_conf.proto
  oneflow/core/job_rewriter/auto_parallel.cpp
  python/oneflow/nn/graph/graph_config.py
Labels: feature, AutoParallel

#6756 add OF_FORCE_COLORED_DIAGNOSTICS option
  CMakeLists.txt
Labels: enhancement, automerge, build

#6742 Undo mutilthreadvecloop changes
  oneflow/core/thread/thread_manager.h
Labels: enhancement, automerge, system

#6659 Fix missing functor autograd - part 2
  oneflow/core/autograd/gradient_funcs/math_binary_op.cpp
  oneflow/core/autograd/gradient_funcs/math_unary_op.cpp
  oneflow/core/framework/op_interpreter/eager_mirrored_op_interpreter.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/binary_functor.h
  oneflow/core/functional/impl/binary_grad_functor.cpp
  oneflow/core/functional/impl/unary_functor.cpp
  oneflow/user/kernels/math_binary_elementwise_func.h
  oneflow/user/kernels/math_binary_elementwise_kernel.cpp
  oneflow/user/kernels/math_binary_elementwise_kernel.cu
  oneflow/user/ops/math_binary_elementwise_seq.h
  python/oneflow/test/modules/test_math_ops.py
Labels: enhancement, system

#6740 add resnet50 ddp graph to ci
  .github/workflows/test.yml
  ci/test/test_resnet50_graph_ddp.sh
Labels: enhancement, automerge, ci, eager, test, graph

#6758 Dev clip_grad_value
  python/oneflow/nn/utils/__init__.py
  python/oneflow/nn/utils/clip_grad.py
  python/oneflow/test/modules/test_clip_grad.py
Labels: feature, automerge, eager

#6716 Fix typo of Permute
  oneflow/core/primitive/cuda/permute.cu
  python/oneflow/test/modules/test_permute.py
Labels: enhancement, automerge, op

#6762 fix bugs of ddp multiple return values
  oneflow/core/autograd/gradient_funcs/select_top_n.cpp
  oneflow/core/framework/tensor.h
  oneflow/core/functional/impl/math_functor.cpp
Labels: automerge, bug, eager

#6625 Add support for liboneflow
  CMakeLists.txt
  cmake/cfg.cmake
  cmake/functional.cmake
  cmake/oneflow-config.cmake
  cmake/oneflow.cmake
  cmake/third_party.cmake
  oneflow/api/common/device.cpp
  oneflow/api/common/device.h
  oneflow/api/cpp/api.h
  oneflow/api/cpp/api_test.cpp
  oneflow/api/cpp/device.cpp
  oneflow/api/cpp/device.h
  oneflow/api/cpp/env.cpp
  oneflow/api/cpp/env.h
  oneflow/api/python/framework/device.cpp
  oneflow/api/python/functional/python_arg.cpp
  oneflow/core/rpc/include/base.h
  oneflow/ir/oneflow-extension/CMakeLists.txt
  tools/functional/generate_functional_api.py
Labels: enhancement, feature, automerge, build, system, need-clean-ccache

#6632 add flow.get_rng_state()
  oneflow/core/framework/random_generator_impl.cpp
  python/oneflow/__init__.py
  python/oneflow/compatible/single_client/__init__.py
  python/oneflow/compatible/single_client/framework/generator.py
  python/oneflow/framework/generator.py
  python/oneflow/framework/tensor.py
  python/oneflow/nn/modules/random_ops.py
  python/oneflow/test/modules/test_generator.py
  python/oneflow/utils/data/dataset.py
Labels: enhancement, automerge, system, python

#6755 fix problems in some loss operators
  oneflow/user/kernels/binary_cross_entropy_kernel.cpp
  oneflow/user/kernels/binary_cross_entropy_kernel.cu
  oneflow/user/kernels/binary_cross_entropy_with_logits_kernel.cu
  oneflow/user/kernels/kl_div_kernel.cu
  oneflow/user/kernels/loss_kernel_util.cu
  oneflow/user/kernels/nll_kernel.cpp
  oneflow/user/kernels/nll_kernel.cu
  oneflow/user/kernels/smooth_l1_loss_kernel.cu
  oneflow/user/ops/nll_op.cpp
Labels: enhancement, feature, automerge, bug, op

#6765 support compiling cuda by clang
  CMakeLists.txt
  cmake/oneflow.cmake
Labels: enhancement, automerge, build

#6699 Refactor stream index generator
  oneflow/core/common/data_type.h
  oneflow/core/common/device_type.h
  oneflow/core/device/cpu_stream_index.cpp
  oneflow/core/device/cpu_stream_index.h
  oneflow/core/device/cuda_stream_index.cpp
  oneflow/core/device/cuda_stream_index.h
  oneflow/core/device/stream_index.h
  oneflow/core/framework/multi_client_session_context.cpp
  oneflow/core/graph/boxing/collective_boxing_sub_task_graph_builder.cpp
  oneflow/core/graph/boxing/naive_b2p_sub_task_graph_builder.cpp
  oneflow/core/graph/boxing/slice_boxing_sub_task_graph_builder.cpp
  oneflow/core/graph/compute_task_node.h
  oneflow/core/graph/copy_task_node.cpp
  oneflow/core/graph/stream_index_generator.cpp
  oneflow/core/graph/stream_index_generator.h
  oneflow/core/graph/stream_index_getter_registry.cpp
  oneflow/core/graph/stream_index_getter_registry.h
  oneflow/core/graph/stream_index_getter_registry_manager.cpp
  oneflow/core/graph/stream_index_getter_registry_manager.h
  oneflow/core/graph/task_graph.cpp
  oneflow/core/graph/task_node.h
  oneflow/core/graph/task_stream_id.h
  oneflow/core/graph/task_stream_index_manager.cpp
  oneflow/core/graph/task_stream_index_manager.h
  oneflow/core/graph_impl/acc_compute_task_node.cpp
  oneflow/core/graph_impl/acc_tick_compute_task_node.cpp
  oneflow/core/graph_impl/callback_notify_compute_task_node.cpp
  oneflow/core/graph_impl/case_compute_task_node.cpp
  oneflow/core/graph_impl/decode_h2d_compute_task_node.cpp
  oneflow/core/graph_impl/device_tick_compute_task_node.cpp
  oneflow/core/graph_impl/distribute_concat_compute_task_node.cpp
  oneflow/core/graph_impl/distribute_split_compute_task_node.cpp
  oneflow/core/graph_impl/dst_subset_tick_compute_task_node.cpp
  oneflow/core/graph_impl/esac_compute_task_node.cpp
  oneflow/core/graph_impl/foreign_io_compute_task_node.cpp
  oneflow/core/graph_impl/normal_forward_compute_task_node.cpp
  oneflow/core/graph_impl/pack_compute_task_node.cpp
  oneflow/core/graph_impl/reentrant_lock_compute_task_node.cpp
  oneflow/core/graph_impl/repeat_compute_task_node.cpp
  oneflow/core/graph_impl/source_tick_compute_task_node.cpp
  oneflow/core/graph_impl/src_subset_tick_compute_task_node.cpp
  oneflow/core/graph_impl/ssp_variable_proxy_task_node.cpp
  oneflow/core/graph_impl/tick_compute_task_node.cpp
  oneflow/core/graph_impl/unpack_compute_task_node.cpp
  oneflow/core/graph_impl/wait_and_send_ids_compute_task_node.cpp
  oneflow/core/job/eager_nccl_comm_manager.cpp
  oneflow/core/job/eager_nccl_comm_manager.h
  oneflow/core/job/id_manager.h
  oneflow/core/job/session_global_objects_scope.cpp
  oneflow/core/job_rewriter/gradient_accumulation_rewrite_pass.cpp
  oneflow/core/job_rewriter/insert_nccl_logical_op_pass.cpp
  oneflow/core/operator/op_conf.proto
  oneflow/user/kernels/nccl_logical_2d_sbp_kernels.cpp
  oneflow/user/kernels/nccl_logical_kernels.cpp
Labels: enhancement, automerge, system, graph

#6768 Fix test_grid_sample fail in ci
  python/oneflow/test/modules/test_grid_sample.py
Labels: automerge, bug, python

#6769 Fix cmake for liboneflow
  cmake/oneflow.cmake
Labels: automerge, bug, build, need-simple-ci

#6610 Dev tensor unfold
  docs/source/tensor.rst
  oneflow/core/autograd/gradient_funcs/unfold_tensor.cpp
  oneflow/core/framework/op_expr_helper.cpp
  oneflow/core/framework/op_expr_helper.h
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/user/kernels/unfold_tensor_kernel.cpp
  oneflow/user/kernels/unfold_tensor_kernel.cu
  oneflow/user/kernels/unfold_tensor_kernel_utils.h
  oneflow/user/ops/unfold_tensor_op.cpp
  python/oneflow/framework/docstr/tensor.py
  python/oneflow/framework/tensor.py
  python/oneflow/test/modules/test_unfold_tensor.py
Labels: enhancement, automerge, op, interface

#6772 Fix constant consistent op physic shape bug
  oneflow/user/ops/constant_op.cpp
Labels: enhancement, feature, automerge, bug, eager, api

#6774 Remove DeviceCtx::AddCallBack
  oneflow/core/device/cpu_device_context.h
  oneflow/core/device/cuda_stream_handle.cpp
  oneflow/core/device/cuda_stream_handle.h
  oneflow/core/device/device_context.h
  oneflow/core/device/device_context_adapter.cpp
  oneflow/core/eager/lazy_job_device_context.h
  oneflow/core/kernel/sync_dynamic_resize_kernel.cpp
  oneflow/core/profiler/kernel.cpp
  oneflow/core/stream/common/stream_context_adapter.cpp
  oneflow/core/vm/cuda_copy_d2h_device_context.h
  oneflow/core/vm/cuda_stream_handle_device_context.h
Labels: enhancement, automerge, system, need-clean-ccache

#6780 Fix simple CI targets
  .github/actions/mac-build/action.yml
  .github/workflows/simple.yml
Labels: automerge, bug, ci, need-simple-ci

#6776 Fix sbp update bug
  oneflow/core/auto_parallel/sbp_constructor.cpp
  oneflow/core/auto_parallel/sbp_constructor.h
  oneflow/core/auto_parallel/sbp_node.h
  oneflow/core/job_rewriter/auto_parallel.cpp
Labels: bug, AutoParallel

#6779 Add the function to transfer ndsbp to a string.
  oneflow/core/job/sbp_parallel.cpp
  oneflow/core/job/sbp_parallel.h
Labels: AutoParallel

#6743 Refactor handling the vm pending
  oneflow/core/eager/critical_section_phy_instr_operand.cpp
  oneflow/core/eager/critical_section_phy_instr_operand.h
  oneflow/core/eager/lazy_job_phy_instr_operand.cpp
  oneflow/core/eager/lazy_job_phy_instr_operand.h
  oneflow/core/eager/local_call_opkernel_phy_instr_operand.cpp
  oneflow/core/eager/local_call_opkernel_phy_instr_operand.h
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/job/parallel_desc.cpp
  oneflow/core/job/parallel_desc.h
  oneflow/core/vm/access_blob_arg_cb_phy_instr_operand.cpp
  oneflow/core/vm/access_blob_arg_cb_phy_instr_operand.h
  oneflow/core/vm/consume_local_dep_object_phy_instr_operand.cpp
  oneflow/core/vm/consume_local_dep_object_phy_instr_operand.h
  oneflow/core/vm/instruction.cpp
  oneflow/core/vm/instruction.h
  oneflow/core/vm/no_arg_cb_phy_instr_operand.h
  oneflow/core/vm/oneflow_vm.cpp
  oneflow/core/vm/oneflow_vm.h
  oneflow/core/vm/phy_instr_operand.h
  oneflow/core/vm/release_tensor_arg_phy_instr_operand.cpp
  oneflow/core/vm/release_tensor_arg_phy_instr_operand.h
  oneflow/core/vm/runtime_instr_type_id.h
  oneflow/core/vm/sequential_instruction_type_test.cpp
  oneflow/core/vm/stream_runtime_desc.h
  oneflow/core/vm/virtual_machine_engine.cpp
  oneflow/core/vm/virtual_machine_engine.h
Labels: enhancement, automerge, system

#6771 fix DispatchSoftmaxGradWarpImplCols rows_per_access
  oneflow/core/cuda/softmax.cuh
  python/oneflow/compatible/single_client/test/ops/test_softmax.py
Labels: automerge, bug, op

#6781 implement exponential lr
  docs/source/optim.rst
  python/oneflow/nn/optimizer/exponential_lr.py
  python/oneflow/optim/lr_scheduler.py
  python/oneflow/test/modules/test_lr_scheduler.py
Labels: enhancement, automerge, op, interface

#6787 fix wrong raii usage in nccl_executor_backend.cu
  oneflow/core/job/collective_boxing/nccl_executor_backend.cu
Labels: automerge, bug, system

#6785 fix neg bug
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/math_ops.py
  python/oneflow/framework/docstr/tensor.py
  python/oneflow/framework/tensor.py
  python/oneflow/nn/modules/tensor_ops.py
  python/oneflow/test/tensor/test_tensor.py
Labels: enhancement, automerge, bug, eager, interface

#6789 [Ndarray] Use ep::Stream instead of DeviceCtx
  oneflow/core/device/cuda_util.cpp
  oneflow/core/device/cuda_util.h
  oneflow/core/kernel/broadcast_to_compatible_with_kernel.cpp
  oneflow/core/kernel/new_kernel_util.cpp
  oneflow/core/kernel/new_kernel_util.cu
  oneflow/core/kernel/new_kernel_util.h
  oneflow/core/ndarray/ndarray_apply_binary.h
  oneflow/core/ndarray/ndarray_apply_binary_core.cpp
  oneflow/core/ndarray/ndarray_apply_binary_core.cu
  oneflow/core/ndarray/ndarray_apply_binary_core.h
  oneflow/core/ndarray/ndarray_apply_broadcast_binary.h
  oneflow/core/ndarray/ndarray_apply_broadcast_binary_core.cpp
  oneflow/core/ndarray/ndarray_apply_broadcast_binary_core.cu
  oneflow/core/ndarray/ndarray_apply_broadcast_binary_core.h
  oneflow/core/ndarray/ndarray_apply_broadcast_unary.h
  oneflow/core/ndarray/ndarray_apply_broadcast_unary_core.cpp
  oneflow/core/ndarray/ndarray_apply_broadcast_unary_core.cu
  oneflow/core/ndarray/ndarray_apply_broadcast_unary_core.h
  oneflow/core/ndarray/ndarray_apply_unary.h
  oneflow/core/ndarray/ndarray_apply_unary_core.cpp
  oneflow/core/ndarray/ndarray_apply_unary_core.cu
  oneflow/core/ndarray/ndarray_apply_unary_core.h
  oneflow/core/ndarray/ndarray_assign_core.cpp
  oneflow/core/ndarray/ndarray_assign_core.cu
  oneflow/core/ndarray/ndarray_assign_core.h
  oneflow/core/ndarray/ndarray_reduce.h
  oneflow/core/ndarray/ndarray_reduce_impl.cpp
  oneflow/core/ndarray/ndarray_reduce_impl.cu
  oneflow/core/ndarray/ndarray_reduce_impl.h
  oneflow/core/ndarray/ndarray_util.h
  oneflow/core/ndarray/xpu_ndarray_assign.cu
  oneflow/core/ndarray/xpu_ndarray_assign.h
  oneflow/core/ndarray/xpu_util.h
  oneflow/user/kernels/bias_add_kernel.cpp
  oneflow/user/kernels/binary_cross_entropy_with_logits_kernel.cpp
  oneflow/user/kernels/binary_cross_entropy_with_logits_kernel.cu
  oneflow/user/kernels/broadcast_div_grad_kernel.cpp
  oneflow/user/kernels/broadcast_like_kernel.cpp
  oneflow/user/kernels/broadcast_pow_grad_kernel.cpp
  oneflow/user/kernels/broadcast_pow_grad_kernel.cu
  oneflow/user/kernels/layer_norm_gpu_kernel.cu
  oneflow/user/kernels/math_binary_broadcast_kernels.cpp
  oneflow/user/kernels/reduce_kernel.cpp
  oneflow/user/kernels/reduce_like_kernels.cpp
  oneflow/user/kernels/tf_prelu_kernel.cpp
  oneflow/user/kernels/tf_prelu_kernel.cu
  oneflow/user/kernels/two_stage_reduce_kernel.cpp
  oneflow/user/kernels/where_kernel.cpp
Labels: enhancement, automerge, system, need-clean-ccache

#6778 Fix NNGraph deconstruction deadlock
  oneflow/core/framework/multi_client_session_context.cpp
  oneflow/core/framework/multi_client_session_context.h
Labels: automerge, bug, system

#6797 Output op use sbp in blob_conf
  oneflow/core/operator/output_op.cpp
Labels: bug, AutoParallel

#6792 Add ep::Stream::Sync()
  oneflow/core/device/cpu_device_context.h
  oneflow/core/device/device_context.h
  oneflow/core/device/device_context_adapter.cpp
  oneflow/core/eager/lazy_job_device_context.h
  oneflow/core/ep/cpu/cpu_stream.h
  oneflow/core/ep/cuda/cuda_stream.cpp
  oneflow/core/ep/cuda/cuda_stream.h
  oneflow/core/ep/include/stream.h
  oneflow/core/kernel/kernel_util.cpp
  oneflow/core/kernel/return_kernel.cpp
  oneflow/core/kernel/sync_check_kernel_observer.cpp
  oneflow/core/profiler/kernel.cpp
  oneflow/core/stream/common/stream_context_adapter.cpp
  oneflow/core/stream/cpu/cpu_stream_context.cpp
  oneflow/core/stream/cuda/cuda_stream_context.cpp
  oneflow/core/stream/include/stream_context.h
  oneflow/core/vm/cuda_copy_d2h_device_context.h
  oneflow/core/vm/cuda_stream_handle_device_context.h
Labels: enhancement, automerge, system

#6653 Refactor tensor.to
  oneflow/api/python/framework/tensor.cpp
  oneflow/api/python/symbol/placement_symbol.cpp
  oneflow/core/framework/placement_utils.cpp
  oneflow/core/framework/placement_utils.h
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/array_functor.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/tensor.py
  python/oneflow/framework/tensor.py
  python/oneflow/nn/modules/index_select.py
  python/oneflow/nn/modules/to.py
Labels: enhancement, automerge, python, refactor

#6803 Dev remove op expr helper
  oneflow/core/autograd/gradient_funcs/fused_scale_tril_softmax_mask_scale.cpp
  oneflow/core/framework/op_expr_helper.cpp
  oneflow/core/framework/op_expr_helper.h
  oneflow/core/framework/op_interpreter/eager_mirrored_op_interpreter.cpp
Labels: enhancement, automerge, system

#6788 Fix loss sbp
  oneflow/user/ops/binary_cross_entropy_op.cpp
  oneflow/user/ops/binary_cross_entropy_with_logits_op.cpp
  oneflow/user/ops/kl_div_op.cpp
  oneflow/user/ops/loss_op_util.cpp
  oneflow/user/ops/loss_op_util.h
  oneflow/user/ops/nll_op.cpp
  oneflow/user/ops/smooth_l1_loss_op.cpp
Labels: enhancement, automerge, bug, op

#6801 [ep::Stream] Cuda Graphs / ExecutionContextHook
  oneflow/core/device/device_context_adapter.cpp
  oneflow/core/ep/cuda/cuda_stream.cpp
  oneflow/core/ep/cuda/cuda_stream.h
  oneflow/core/ep/include/stream.h
  oneflow/core/kernel/user_kernel.cpp
  oneflow/core/kernel/user_kernel.h
  oneflow/core/lazy/actor/light_actor.cpp
  oneflow/core/stream/common/stream_context_adapter.cpp
  oneflow/core/stream/cuda/cuda_graph_context.cpp
  oneflow/core/stream/cuda/cuda_graph_context.h
  oneflow/core/stream/cuda/cuda_stream_context.cpp
  oneflow/core/stream/cuda/cuda_stream_context.h
  oneflow/core/stream/include/execution_context_hook.h
  oneflow/core/thread/thread.cpp
Labels: enhancement, automerge, system

#6794 Add module parameter print for autotest framework
  python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py
Labels: feature, automerge, eager, test, api, interface

#6793 Fix ilegal access error in Arange
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/user/kernels/arange_kernel.cpp
  oneflow/user/kernels/arange_kernel_util.cpp
  oneflow/user/kernels/arange_kernel_util.cu
  oneflow/user/kernels/arange_kernel_util.h
  oneflow/user/kernels/randperm_kernel.cpp
  oneflow/user/kernels/randperm_kernel.cu
  oneflow/user/ops/arange_op.cpp
  python/oneflow/compatible/single_client/ops/math_ops.py
Labels: automerge, bug, op

#6763 remove waiting list
  oneflow/core/vm/control_stream_type_test.cpp
  oneflow/core/vm/virtual_machine_engine.cpp
  oneflow/core/vm/virtual_machine_engine.h
Labels: enhancement, automerge, system

#6775 Add bn add relu pattern in MLIR and upgrade LLVM Mono
  cmake/oneflow.cmake
  oneflow/core/job/job_build_and_infer_ctx.cpp
  oneflow/core/job_rewriter/ir_pass.cpp
  oneflow/ir/include/OneFlow/OneFlowOps.td
  oneflow/ir/lib/OneFlow/CMakeLists.txt
  oneflow/ir/lib/OneFlow/Conversion/OneFlowToTosa.cpp
  oneflow/ir/lib/OneFlow/OneFlowOps.cpp
  oneflow/ir/lib/OneFlow/Passes.cpp
  oneflow/ir/oneflow-extension/CMakeLists.txt
  oneflow/ir/oneflow-extension/extension.cpp
  oneflow/ir/oneflow-opt/oneflow-opt.cpp
  oneflow/ir/oneflow-translate/include/OneFlow/MLIROneFlowTranslation.h
  oneflow/ir/oneflow-translate/lib/OneFlow/CMakeLists.txt
  oneflow/ir/oneflow-translate/lib/OneFlow/Importer.cpp
  oneflow/ir/oneflow-translate/lib/OneFlow/MLIROneFlowTranslation.cpp
  oneflow/ir/test/OneFlow/lower_to_tosa.mlir
  oneflow/ir/test/OneFlow/test_fuse_bn_add_relu.py
  oneflow/user/kernels/normalization_kernel.cu
  python/oneflow/__init__.py
Labels: feature, automerge, system

#6753 Rename class OneflowVM to VirtualMachine
  oneflow/core/eager/local_dep_object.cpp
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/job/oneflow.cpp
  oneflow/core/vm/virtual_machine.cpp
  oneflow/core/vm/virtual_machine.h
  oneflow/core/vm/virtual_machine_scope.cpp
  oneflow/core/vm/vm_util.cpp
Labels: enhancement, automerge, system, refactor

#6795 upgrade cub to 1.11.0 for https://github.com/NVIDIA/cub/pull/170
  cmake/third_party/cub.cmake
  cmake/third_party/header_index/cub_headers.txt
Labels: enhancement, automerge, build

#6806 lazy create cuda_stream
  oneflow/core/vm/cuda_copy_d2h_device_context.h
  oneflow/core/vm/cuda_stream_handle_device_context.h
Labels: automerge, bug, system

#6800 add tensor method docstr
  docs/source/oneflow.rst
  docs/source/tensor.rst
  python/oneflow/framework/docstr/tensor.py
  python/oneflow/framework/tensor.py
  python/oneflow/nn/modules/bmm.py
  python/oneflow/test/tensor/test_tensor.py
Labels: enhancement, automerge, bug, eager, documentation, need-clean-ccache

#6808 Auto parallel/fix max movement size bug
  oneflow/core/auto_parallel/sbp_collector.cpp
  oneflow/core/auto_parallel/sbp_constructor.cpp
  oneflow/core/auto_parallel/sbp_edge.h
  oneflow/core/auto_parallel/sbp_util.cpp
  oneflow/core/auto_parallel/sbp_util.h
  oneflow/core/graph/boxing/collective_boxing_sub_task_graph_builder.cpp
  oneflow/core/job/sbp_parallel.cpp
  oneflow/user/ops/ofrecord_reader_op.cpp
Labels: AutoParallel

#6810 Add sbp check after auto_parallel pass
  oneflow/core/auto_parallel/sbp_constructor.cpp
  oneflow/core/auto_parallel/sbp_constructor.h
  oneflow/core/job_rewriter/auto_parallel.cpp
Labels: feature, AutoParallel

#6816 Auto parallel/of format
  oneflow/core/auto_parallel/binary_set.cpp
  oneflow/core/auto_parallel/sbp_collector.cpp
  oneflow/core/auto_parallel/sbp_constructor.cpp
  oneflow/core/auto_parallel/sbp_edge.h
  oneflow/core/auto_parallel/sbp_graph.h
  oneflow/core/auto_parallel/sbp_node.h
  oneflow/core/auto_parallel/sbp_util.cpp
  oneflow/user/ops/ofrecord_reader_op.cpp
Labels: AutoParallel

#6819 Make PrintSBPGraphDebugInfo() const
  oneflow/core/graph/op_graph.cpp
  oneflow/core/graph/op_graph.h
Labels: AutoParallel

#6813 set common compiler flags in oneflow_add_library(...), enable it for CUDA
  cmake/caches/cn/fast/cuda-61-clang.cmake
  cmake/caches/cn/fast/cuda-75-clang.cmake
  cmake/oneflow.cmake
  oneflow/core/cuda/softmax.cuh
  oneflow/core/intrusive/list_test.cpp
  oneflow/core/kernel/util/cuda_arithemetic_interface.cu
  oneflow/user/kernels/grid_sample_kernel_util.h
  oneflow/user/kernels/scalar_math_kernels.cu
  tools/cfg/template/template.cfg.cpp
Labels: enhancement, automerge, build

#6807 Remove redundant code in softmax cuda kernel
  oneflow/core/cuda/softmax.cuh
Labels: automerge, bug, op, need-clean-ccache

#6826 Prevent CI failure when cublas alloc fail
  ci/test/parallel_run.py
Labels: enhancement, automerge, ci

#6817 Dev nms
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/user/kernels/nms_kernel.cu
  oneflow/user/ops/nms_op.cpp
  python/oneflow/__init__.py
  python/oneflow/nn/modules/nms.py
  python/oneflow/test/modules/test_nms.py
Labels: enhancement, automerge, eager, op, need-clean-ccache

#6748 Refactor vm consuming
  oneflow/core/eager/critical_section_phy_instr_operand.h
  oneflow/core/eager/lazy_job_phy_instr_operand.h
  oneflow/core/eager/local_call_opkernel_phy_instr_operand.h
  oneflow/core/intrusive/cpp_attribute.h
  oneflow/core/intrusive/object_pool.h
  oneflow/core/intrusive/object_pool_test.cpp
  oneflow/core/intrusive/ref.h
  oneflow/core/vm/access_blob_arg_cb_phy_instr_operand.h
  oneflow/core/vm/consume_local_dep_object_phy_instr_operand.h
  oneflow/core/vm/instruction.cpp
  oneflow/core/vm/instruction.h
  oneflow/core/vm/no_arg_cb_phy_instr_operand.h
  oneflow/core/vm/phy_instr_operand.h
  oneflow/core/vm/release_tensor_arg_phy_instr_operand.cpp
  oneflow/core/vm/release_tensor_arg_phy_instr_operand.h
  oneflow/core/vm/stream.cpp
  oneflow/core/vm/virtual_machine_engine.cpp
  oneflow/core/vm/virtual_machine_engine.h
  oneflow/core/vm/vm_object.cpp
  oneflow/core/vm/vm_object.h
Labels: enhancement, automerge, system

#6828 Add init method docstr modify int to int32
  docs/source/nn.rst
  python/oneflow/compatible/single_client/ops/initializer_util.py
  python/oneflow/compatible/single_client/test/ops/test_quantize_op.py
  python/oneflow/nn/init.py
  python/oneflow/ops/initializer_util.py
  python/oneflow/test/modules/test_fake_quantization.py
  python/oneflow/test/modules/test_min_max_observer.py
  python/oneflow/test/modules/test_quantization.py
Labels: enhancement, automerge, eager, documentation, need-clean-ccache

#6812 Check whether the expand_shape parameter is legal
  oneflow/core/functional/impl/array_functor.cpp
Labels: enhancement, automerge, bug, op

#6733 refactor local call opkernel instruction
  oneflow/core/eager/local_call_opkernel_phy_instr_operand.cpp
  oneflow/core/eager/local_call_opkernel_phy_instr_operand.h
  oneflow/core/eager/opkernel_instruction_type.cpp
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/framework/user_op_kernel_registry.cpp
  oneflow/core/framework/user_op_kernel_registry.h
  oneflow/user/kernels/stateful_local_opkernel.cpp
  oneflow/user/kernels/stateful_local_opkernel.h
Labels: enhancement, automerge, system

#6796 one_hot primitive interface
  oneflow/core/ep/include/primitive/one_hot.h
Labels: enhancement, automerge, system, need-clean-ccache

#6835 revert DependenceVector to std::vector
  oneflow/core/vm/phy_instr_operand.h
Labels: enhancement, automerge, system, need-simple-ci

#6824 fix indexed slice for adam max_v
  oneflow/core/job_rewriter/indexed_slices_optimizer_rewrite_pass.cpp
Labels: automerge, bug, system, need-clean-ccache

#6832 set str option
  docs/source/oneflow.rst
  python/oneflow/__init__.py
  python/oneflow/framework/tensor_str.py
Labels: feature, automerge, system

#6847 Empty op support float16
  oneflow/api/python/utils/tensor_utils.cpp
  oneflow/core/common/data_type.cpp
  oneflow/core/common/data_type.h
  oneflow/core/common/data_type_seq.h
  oneflow/user/kernels/empty_kernel.cpp
  python/oneflow/test/modules/test_empty.py
Labels: enhancement, automerge, bug, eager

#6799 resnet optimization features
  python/oneflow/nn/graph/graph_config.py
  python/oneflow/test/graph/test_optimization_conf.py
Labels: feature, automerge, system, python, graph

#6815 Dev vm view instruction
  oneflow/api/python/framework/tensor.cpp
  oneflow/core/autograd/gradient_funcs/reshape.cpp
  oneflow/core/eager/blob_instruction_type.cpp
  oneflow/core/eager/blob_instruction_type.h
  oneflow/core/eager/cpu_blob_instruction_type.cpp
  oneflow/core/eager/cuda_blob_instruction_type.cpp
  oneflow/core/eager/eager_blob_object.cpp
  oneflow/core/eager/eager_blob_object.h
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/framework/instructions_builder.h
  oneflow/core/framework/tensor.cpp
  oneflow/core/framework/tensor.h
  oneflow/core/framework/tensor_impl.cpp
  oneflow/core/framework/tensor_impl.h
  oneflow/core/framework/tensor_meta.h
  oneflow/core/framework/tensor_method.cpp
  oneflow/core/framework/tensor_methods.cpp
  oneflow/core/framework/tensor_methods.h
  oneflow/core/functional/function_library.h
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/core/vm/tensor_view_operand.cpp
  oneflow/core/vm/tensor_view_operand.h
Labels: enhancement, eager, op, system

#6844 Remove deafult l2 and use bias add in lazy mode
  oneflow/core/framework/op_interpreter/lazy_op_interpreter.cpp
Labels: enhancement, automerge, system

#6841 Add arccos op and docstr
  docs/source/oneflow.rst
  docs/source/tensor.rst
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/math_ops.py
  python/oneflow/framework/docstr/tensor.py
  python/oneflow/framework/tensor.py
  python/oneflow/test/modules/test_math_ops.py
  python/oneflow/test/tensor/test_tensor.py
Labels: enhancement, eager, documentation, need-clean-ccache

#6635 add some fused kernels
  oneflow/core/autograd/gradient_funcs/fused_scale_mask_softmax.cpp
  oneflow/core/autograd/gradient_funcs/fused_scale_mask_softmax_dropout.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/core/functional/impl/nn_grad_functor.cpp
  oneflow/core/job_rewriter/auto_mixed_precision_lists.cpp
  oneflow/user/kernels/fused_scale_mask_softmax.cu
  oneflow/user/kernels/fused_scale_mask_softmax_dropout.cu
  oneflow/user/ops/fused_scale_mask_softmax_dropout_op.cpp
  oneflow/user/ops/fused_scale_mask_softmax_op.cpp
  python/oneflow/test/modules/test_fused_scale_mask_softmax.py
  python/oneflow/test/modules/test_fused_scale_mask_softmax_dropout.py
Labels: enhancement, automerge, ci, op, api, need-clean-ccache

#6802 Add CUDA arch 52 back
  oneflow/core/kernel/cuda_check_numerics_kernel_observer.cu
Labels: enhancement, automerge, ci, build

#6836 Fix FuseBN eval error
  oneflow/core/autograd/gradient_funcs/normalization_add_relu.cpp
  oneflow/core/functional/impl/nn_functor.cpp
  python/oneflow/test/modules/test_batchnorm_add_relu.py
Labels: enhancement, automerge, bug, op

#6862 Remove KernelXxxContext::device_ctx()
  oneflow/core/device/cuda_util.cpp
  oneflow/core/device/cuda_util.h
  oneflow/core/framework/op_kernel.h
  oneflow/core/kernel/user_kernel.cpp
  oneflow/core/kernel/user_kernel.h
  oneflow/user/kernels/arange_kernel_util.h
  oneflow/user/kernels/arg_where_kernel_util.h
  oneflow/user/kernels/avg_pooling_kernel_util.h
  oneflow/user/kernels/clip_by_value_kernel.h
  oneflow/user/kernels/ctc_loss_kernel_util.cu
  oneflow/user/kernels/ctc_loss_kernel_util.h
  oneflow/user/kernels/dim_scatter_scalar_kernel_util.h
  oneflow/user/kernels/distributions/normal_distribution.h
  oneflow/user/kernels/distributions/uniform_distribution.h
  oneflow/user/kernels/distributions/uniform_int_distribution.h
  oneflow/user/kernels/eye_kernel_util.h
  oneflow/user/kernels/fold_kernel_util.h
  oneflow/user/kernels/in_top_k_kernel_util.cpp
  oneflow/user/kernels/in_top_k_kernel_util.cu
  oneflow/user/kernels/in_top_k_kernel_util.h
  oneflow/user/kernels/l2_normalize_kernel.cu
  oneflow/user/kernels/leaky_relu_kernel.cu
  oneflow/user/kernels/loss_kernel_util.h
  oneflow/user/kernels/math_unary_elementwise_kernel.cu
  oneflow/user/kernels/one_hot_kernel.cu
  oneflow/user/kernels/pooling_kernel_util.h
  oneflow/user/kernels/random_mask_generator.h
  oneflow/user/kernels/randperm_kernel.cpp
  oneflow/user/kernels/randperm_kernel.cu
  oneflow/user/kernels/stateful_local_opkernel.cpp
  oneflow/user/kernels/stateful_local_opkernel.h
  oneflow/user/kernels/two_stage_reduce_kernel_util.cpp
  oneflow/user/kernels/two_stage_reduce_kernel_util.h
  oneflow/user/kernels/unfold_kernel_util.h
  oneflow/user/ops/normalization_op.cpp
Labels: enhancement, automerge, system, need-clean-ccache

#6840 Fix sbp check bug
  oneflow/core/auto_parallel/sbp_constructor.cpp
  oneflow/core/graph/op_graph.cpp
  oneflow/core/operator/operator.cpp
  oneflow/core/register/register_manager.cpp
Labels: bug, AutoParallel

#6853 pool code refine
  oneflow/core/autograd/gradient_funcs/pool.cpp
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/core/job_rewriter/auto_mixed_precision_lists.cpp
  oneflow/core/job_rewriter/quantization_aware_training.cpp
  oneflow/ir/include/OneFlow/OneFlowOps.td
  oneflow/ir/lib/OneFlow/OneFlowOps.cpp
  oneflow/user/kernels/pool_cpu_kernel.cpp
  oneflow/user/kernels/pool_gpu_kernel.cpp
  oneflow/user/kernels/pooling_kernel.cpp
  oneflow/user/kernels/pooling_kernel.cu
  oneflow/user/kernels/pooling_kernel_util.cpp
  oneflow/user/kernels/pooling_kernel_util.h
  oneflow/user/ops/avg_pooling_op.cpp
  oneflow/user/ops/pool_op.cpp
  oneflow/user/ops/pooling_op.cpp
  oneflow/xrt/api.cpp
  python/oneflow/compatible/single_client/ops/nn_ops.py
Labels: purge, automerge, op

#6823 Add cpu group conv impl
  oneflow/user/kernels/group_conv_kernel.cpp
  python/oneflow/nn/modules/conv.py
  python/oneflow/test/modules/test_conv1d.py
  python/oneflow/test/modules/test_conv2d.py
  python/oneflow/test/modules/test_conv3d.py
  python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py
Labels: enhancement, feature, automerge, eager, fmt-only, interface

#6865 Add nsys profile host thread name
  oneflow/core/eager/lazy_job_instruction_type.cpp
  oneflow/core/kernel/image_decoder_random_crop_resize_kernel.cpp
  oneflow/core/stream/cuda/cuda_stream_context.cpp
  oneflow/core/thread/thread.cpp
  oneflow/core/vm/virtual_machine.cpp
Labels: feature, automerge, tooling

#6860 Check modify op module
  docs/source/oneflow.rst
  python/oneflow/framework/docstr/tensor.py
  python/oneflow/framework/tensor.py
  python/oneflow/nn/modules/argsort.py
  python/oneflow/nn/modules/broadcast_like.py
  python/oneflow/nn/modules/constant.py
  python/oneflow/nn/modules/nms.py
  python/oneflow/nn/modules/sort.py
Labels: enhancement, automerge, eager, op, documentation

#6868 Fix random ops
  oneflow/core/functional/impl/random_functor.cpp
  oneflow/user/kernels/distributions/uniform_int_kernel.h
  oneflow/user/ops/distributions/normal_op.cpp
  oneflow/user/ops/distributions/uniform_int_op.cpp
  oneflow/user/ops/distributions/uniform_op.cpp
  oneflow/user/ops/randperm_op.cpp
Labels: automerge, bug, system

#6554 fix docstr problem
  python/oneflow/compatible/single_client/ops/diag_ops.py
  python/oneflow/framework/docstr/array_ops.py
  python/oneflow/framework/docstr/comm.py
  python/oneflow/framework/docstr/random.py
  python/oneflow/nn/modules/constant.py
  python/oneflow/nn/modules/math_ops.py
  python/oneflow/nn/modules/random_ops.py
Labels: op, documentation

#6870 Fix retinanet
  oneflow/user/kernels/narrow_kernel.cpp
  python/oneflow/framework/tensor.py
Labels: automerge, bug, eager, op

#6842 Optimize LayerNorm Forward
  CMakeLists.txt
  oneflow/core/cuda/layer_norm.cuh
  oneflow/user/kernels/layer_norm_gpu_kernel.cu
  python/oneflow/compatible/single_client/test/ops/test_layer_norm.py
  python/oneflow/test/modules/test_layernorm.py
Labels: enhancement, automerge, op

#6852 Refactor last used device
  oneflow/core/eager/eager_blob_object.h
  oneflow/core/eager/local_dep_object.h
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/framework/tensor_impl.cpp
Labels: automerge, bug, system, refactor

#6881 fix pipeline delay ctrl edge between src subset tick and output
  oneflow/core/graph/task_graph.cpp
Labels: enhancement, automerge, system, graph

#6859 remove useless codes
  python/oneflow/comm/comm_ops.py
  python/oneflow/framework/tensor.py
  python/oneflow/nn/modules/expand.py
  python/oneflow/nn/modules/index_select.py
Labels: enhancement, automerge, eager, python

#6867 add alpha parameter in add_op
  oneflow/core/autograd/autograd_engine.cpp
  oneflow/core/autograd/gradient_funcs/normalization.cpp
  oneflow/core/autograd/gradient_funcs/normalization_add_relu.cpp
  oneflow/core/framework/tensor_arg.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/binary_functor.cpp
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/core/functional/impl/nn_functor.cpp
  python/oneflow/test/modules/test_add.py
Labels: feature, automerge, op

#6582 add fallback to cpu builder
  oneflow/core/graph/boxing/fallback_to_cpu_slice_boxing_sub_task_graph_builder.cpp
  oneflow/core/graph/boxing/fallback_to_cpu_slice_boxing_sub_task_graph_builder.h
  oneflow/core/graph/boxing/hierarchical_sub_task_graph_builder_impl.cpp
  oneflow/core/graph/boxing/slice_boxing_sub_task_graph_builder.cpp
Labels: enhancement, automerge, system

#6884 graph debug add time cost
  python/oneflow/nn/graph/graph.py
Labels: enhancement, automerge, system

#6873 fix eye op attr name error
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/user/kernels/eye_kernel.cpp
  oneflow/user/ops/eye_op.cpp
Labels: enhancement, automerge, op

#6861 add inplace mul
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/binary_functor.cpp
  oneflow/core/functional/impl/math_functor.cpp
  python/oneflow/framework/docstr/tensor.py
  python/oneflow/framework/tensor.py
  python/oneflow/test/modules/test_add.py
  python/oneflow/test/modules/test_mul.py
Labels: feature, automerge, op

#6879 Dev roialign
  oneflow/core/autograd/gradient_funcs/roi_align.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/user/kernels/roi_align_kernel.cu
  oneflow/user/ops/roi_align_op.cpp
  python/oneflow/__init__.py
  python/oneflow/test/modules/test_roi_align.py
Labels: enhancement, automerge, eager, op

#6856 Pick Variant from Standalone Maybe
  cmake/oneflow.cmake
  oneflow/maybe/config.h
  oneflow/maybe/type_traits.h
  oneflow/maybe/type_traits_test.cpp
  oneflow/maybe/utility.h
  oneflow/maybe/utility_test.cpp
  oneflow/maybe/variant.h
  oneflow/maybe/variant_test.cpp
Labels: enhancement, automerge, system

#6767 Add oneDNN
  CMakeLists.txt
  cmake/caches/ci/cpu.cmake
  cmake/third_party.cmake
  cmake/third_party/oneDNN.cmake
  oneflow/core/ep/cpu/cpu_stream.h
  oneflow/core/ep/cpu/primitive/add.cpp
  oneflow/core/ep/cpu/primitive/type_seq.h
  oneflow/core/kernel/slice_boxing_kernel.cpp
  oneflow/user/kernels/acc_kernel.cpp
  oneflow/user/kernels/conv_kernels.cpp
  oneflow/user/kernels/dropout_kernel.cpp
  oneflow/user/kernels/eager_p_to_b_kernel.cpp
  oneflow/user/kernels/eager_p_to_s_kernel.cpp
  oneflow/user/kernels/group_conv_kernel.cpp
Labels: enhancement, automerge, system

#6886 fix cudnn include
  oneflow/core/job_rewriter/cudnn_fused_normalization_add_relu_pass.cpp
Labels: automerge, bug, system, need-clean-ccache

#6895 Fix nn graph variable bind
  oneflow/core/framework/nn_graph.cpp
  oneflow/core/framework/nn_graph.h
Labels: bug, AutoParallel

#6717 Implement Fused Dropout Kernel
  oneflow/core/autograd/gradient_funcs/dropout.cpp
  oneflow/core/framework/random_generator_impl.cpp
  oneflow/core/framework/random_generator_impl.cu
  oneflow/core/framework/random_generator_impl.h
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/user/kernels/dropout_kernel.cpp
  oneflow/user/kernels/dropout_kernel.cu
  oneflow/user/kernels/dropout_kernel.h
  oneflow/user/ops/dropout_op.cpp
  python/oneflow/compatible/single_client/ops/nn_ops.py
  python/oneflow/compatible/single_client/test/ops/test_dropout.py
  python/oneflow/compatible/single_client/test/ops/test_fused_bias_add_dropout.py
  python/oneflow/compatible/single_client/test/ops/test_fused_scale_tril_softmax_mask_and_scale.py
  python/oneflow/framework/docstr/dropout.py
  python/oneflow/nn/modules/dropout.py
  python/oneflow/test/modules/test_dropout.py
  python/oneflow/test/modules/test_fused_bias_add_dropout.py
  python/oneflow/test/modules/test_fused_scale_mask_softmax_dropout.py
  python/oneflow/test/modules/test_fused_tril_softmax_mask_scale.py
  python/oneflow/test/modules/test_generator.py
Labels: enhancement, automerge, op, system, need-clean-ccache

#6892 refine softmax
  oneflow/core/cuda/softmax.cuh
Labels: enhancement, automerge, op

#6896 Fix Accelerate lib link flag on Mac
  .github/workflows/test.yml
  cmake/third_party.cmake
Labels: automerge, bug, build, need-simple-ci
