Repository Oneflow-Inc/oneflow, pull requests merged in 2021-05, with the labels that each got.

#4796 Manylinux docker supports CUDA 11.2 and oneAPI MKL
  docker/package/manylinux/CentOS7-Base-163.repo
  docker/package/manylinux/Dockerfile
  docker/package/manylinux/build_wheel.py
Labels: automerge, build, feature

#4753 Feat: InsertNcclLogicalOps support multi-subgraph by placement group
  oneflow/core/job_rewriter/insert_nccl_logical_op_pass.cpp
Labels: automerge, feature, system

#4801 dont use import to determine if export onnx interface
  tools/generate_oneflow_symbols_export_file.py
Labels: automerge, bug, python

#4798 Insert double pipeline buffer between adjacent stage
  oneflow/core/job_rewriter/pipeline_buffer_pass.cpp
Labels: automerge, enhancement, system

#4806 NCCL logical support Pipeline Parallel By independent NcclComputeStream.
  oneflow/core/device/cuda_stream_index.h
  oneflow/core/framework/op_kernel.h
  oneflow/core/graph/task_graph.cpp
  oneflow/core/job/eager_nccl_comm_manager.cpp
  oneflow/core/job/eager_nccl_comm_manager.h
  oneflow/core/job_rewriter/insert_nccl_logical_op_pass.cpp
  oneflow/core/job_rewriter/job_completer.cpp
  oneflow/core/job_rewriter/pipeline_buffer_pass.cpp
  oneflow/core/operator/op_conf.proto
  oneflow/user/kernels/nccl_logical_2d_sbp_kernels.cpp
  oneflow/user/kernels/nccl_logical_kernels.cpp
Labels: automerge, bottleneck, bug, feature, system

#4800 Dev merge modules part3
  oneflow/python/nn/modules/dropout.py
  oneflow/python/nn/modules/linear.py
  oneflow/python/nn/modules/math_ops.py
  oneflow/python/nn/modules/normalization.py
  oneflow/python/test/modules/test_dropout.py
  oneflow/python/test/modules/test_linear.py
  oneflow/python/test/modules/test_math_ops.py
  oneflow/python/test/modules/test_normalization.py
Labels: api, automerge, eager, feature, op

#4809 Add GetRank and GetWordSize interface
  oneflow/api/python/env/env.cpp
  oneflow/api/python/env/env.h
  oneflow/api/python/env/env_api.h
Labels: api, automerge, eager, enhancement

#4795 ArgTuple
  oneflow/api/python/framework/blob_register.cpp
  oneflow/core/common/maybe.h
  oneflow/core/eager/local_call_opkernel_phy_instr_operand.h
  oneflow/core/eager/opkernel_instruction_type.cpp
  oneflow/core/framework/arg_tuple.cpp
  oneflow/core/framework/arg_tuple.h
  oneflow/core/framework/blob_register.cpp
  oneflow/core/framework/blob_register.h
  oneflow/core/framework/eager_blob_util.cpp
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/framework/instructions_builder.h
  oneflow/core/framework/op_expr.cpp
  oneflow/core/framework/op_expr.h
  oneflow/user/kernels/stateful_local_opkernel.cpp
  oneflow/user/kernels/stateful_local_opkernel.h
Labels: automerge, enhancement, system

#4811 Export distribute interface for get_rank and get_word_size
  oneflow/python/framework/distribute.py
Labels: automerge, enhancement, python

#4812 Fix CommNet::ReadDone lock scope
  oneflow/core/comm_network/comm_network.cpp
Labels: automerge, bug, system

#4810 Serialize proto in binary rather than text
  oneflow/api/python/framework/framework.cpp
  oneflow/api/python/framework/framework.h
  oneflow/core/job/inter_user_job_info.proto
  oneflow/python/framework/c_api_util.py
Labels: automerge, enhancement, python

#4789 Add negative and nllloss module
  oneflow/python/framework/tensor.py
  oneflow/python/nn/modules/loss.py
  oneflow/python/nn/modules/negative.py
  oneflow/python/test/modules/test_negative.py
  oneflow/python/test/modules/test_nllloss.py
Labels: api, automerge, documentation, op, python

#4808 fix crossentropy_loss bug
  oneflow/python/nn/modules/loss.py
  oneflow/python/test/modules/test_crossentropyloss.py
Labels: api, automerge, bug, documentation, op

#4805 remove duplicate license in test_range.py
  oneflow/python/test/ops/test_range.py
Labels: automerge, documentation, good for pr, python, test

#4724 Refactor autograd engine
  cmake/oneflow.cmake
  oneflow/api/python/framework/tensor.cpp
  oneflow/core/autograd/autograd_engine.cpp
  oneflow/core/autograd/autograd_engine.h
  oneflow/core/autograd/autograd_meta.cpp
  oneflow/core/autograd/autograd_meta.h
  oneflow/core/autograd/autograd_mode.h
  oneflow/core/framework/op_expr_grad_function.h
  oneflow/core/framework/op_expr_helper.cpp
  oneflow/core/framework/op_expr_helper.h
  oneflow/core/framework/op_interpreter.h
  oneflow/core/framework/op_interpreter/op_interpreter_util.cpp
  oneflow/core/framework/tensor.cpp
  oneflow/core/framework/tensor.h
  oneflow/core/framework/tensor_impl.cpp
  oneflow/core/framework/tensor_impl.h
  oneflow/python/framework/tensor.py
Labels: automerge, eager, feature

#4680 feat eager optimizer
  oneflow/python/nn/optimizer/__init__.py
  oneflow/python/nn/optimizer/optimizer.py
  oneflow/python/test/modules/test_optimizers.py
Labels: automerge, eager, feature, python

#4818 ibverbs structure initialization
  oneflow/core/comm_network/ibverbs/ibverbs_comm_network.cpp
  oneflow/core/comm_network/ibverbs/ibverbs_memory_desc.cpp
  oneflow/core/comm_network/ibverbs/ibverbs_qp.cpp
Labels: automerge, enhancement, system

#4815 Delete ops outside of loops in job passes
  oneflow/core/job_rewriter/fuse_add_to_output_pass.cpp
  oneflow/core/job_rewriter/fuse_cast_scale_pass.cpp
Labels: automerge, enhancement, system

#4819 Skip GenCollectiveBoxingPlan if no CollectiveBoxingTaskNode
  oneflow/core/job/oneflow.cpp
Labels: automerge, enhancement, system

#4821 Fix cpu_only complie bug with gcc 730
  cmake/oneflow.cmake
Labels: automerge, bug, system

#4723 add pow module
  oneflow/python/nn/modules/math_ops.py
  oneflow/python/test/modules/test_math_ops.py
Labels: api, automerge, eager, enhancement, op

#4820 Use multi core to run TaskNode::ToProto
  oneflow/core/graph/compute_task_node.cpp
  oneflow/core/graph/compute_task_node.h
  oneflow/core/graph/task_node.cpp
  oneflow/core/graph/task_node.h
  oneflow/core/job/compiler.cpp
  oneflow/core/operator/operator.cpp
Labels: automerge, enhancement, system

#4814 Dev align corners
  oneflow/python/ops/layers.py
  oneflow/python/test/ops/test_upsample.py
  oneflow/user/kernels/upsample_kernel.cu
  oneflow/user/ops/upsample_op.cpp
Labels: automerge, feature, op

#4754 Add more tests for tensor
  oneflow/python/framework/dtype.py
  oneflow/python/framework/tensor.py
  oneflow/python/test/modules/test_add.py
  oneflow/python/test/modules/test_batchnorm.py
  oneflow/python/test/modules/test_div.py
  oneflow/python/test/modules/test_linear.py
  oneflow/python/test/modules/test_sub.py
  oneflow/python/test/tensor/test_tensor.py
Labels: automerge, eager, enhancement, python, test

#4832 Add device infer fn cpu only
  oneflow/core/framework/device.cpp
  oneflow/core/framework/device.h
  oneflow/core/framework/user_op_registry.cpp
Labels: automerge, eager, enhancement

#4822 export optim optimizers
  docs/source/index.rst
  docs/source/optim.rst
Labels: api, automerge, documentation, enhancement, python

#4830 add broadcast matmul support
  oneflow/python/nn/modules/matmul.py
  oneflow/python/test/modules/test_matmul.py
Labels: automerge, eager, enhancement, op

#4823 Rewrite sparse_softmax_cross_entropy and reduce ops gradient funcs
  oneflow/core/autograd/gradient_funcs/reduce_ops.cpp
  oneflow/core/autograd/gradient_funcs/sparse_softmax_cross_entropy.cpp
  oneflow/core/framework/op_expr_helper.cpp
  oneflow/core/framework/op_expr_helper.h
  oneflow/python/test/modules/test_crossentropyloss_grad.py
Labels: automerge, enhancement, system

#4841 Add scalar support of greater less module
  oneflow/python/nn/modules/greater.py
  oneflow/python/nn/modules/less.py
  oneflow/python/test/modules/test_greater.py
  oneflow/python/test/modules/test_less.py
Labels: automerge, eager, enhancement

#4840 Refine optimizer
  oneflow/python/nn/optimizer/adam.py
  oneflow/python/nn/optimizer/optimizer.py
  oneflow/python/nn/optimizer/sgd.py
  oneflow/python/test/modules/test_optim_adam.py
  oneflow/python/test/modules/test_optim_sgd.py
Labels: automerge, documentation, eager, python, refactor

#4846 add docstring
  oneflow/python/nn/modules/cast.py
Labels: automerge, documentation, eager

#4752 fix eager with unknow symbol id
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/vm/instruction.cpp
  oneflow/core/vm/instruction.msg.h
  oneflow/core/vm/stream.cpp
  oneflow/core/vm/stream.msg.h
  oneflow/core/vm/virtual_machine.cpp
  oneflow/core/vm/virtual_machine.msg.h
  oneflow/core/vm/vm_object.msg.h
Labels: automerge, bug, eager

#4836 Dev fix linear module
  oneflow/python/nn/modules/linear.py
  oneflow/python/test/modules/test_linear.py
Labels: automerge, bug, eager, enhancement

#4834 Add rmsprop optimizer
  oneflow/python/nn/optimizer/rmsprop.py
  oneflow/python/test/modules/test_optim_rmsprop.py
Labels: api, automerge, documentation, feature, python

#4824 add adamw optimizer
  oneflow/python/nn/optimizer/adamw.py
  oneflow/python/test/modules/test_optim_adamw.py
Labels: api, automerge, documentation, enhancement, feature, python

#4850 remove MakeParallelDescByDevice
  oneflow/core/framework/device.cpp
  oneflow/core/framework/device.h
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/framework/op_expr.cpp
  oneflow/core/framework/op_interpreter/eager_mirrored_op_interpreter.cpp
  oneflow/core/framework/tensor_impl.cpp
  oneflow/core/vm/instruction.cpp
Labels: automerge, bug, eager, enhancement

#4856 fix_experimental_apis_bug
  docs/source/index.rst
  docs/source/tmp.rst
  oneflow/python/nn/modules/cast.py
  oneflow/python/nn/modules/constant.py
  oneflow/python/nn/modules/expand.py
  oneflow/python/nn/modules/flatten.py
  oneflow/python/nn/modules/math_ops.py
  oneflow/python/nn/modules/matmul.py
  oneflow/python/nn/modules/repeat.py
  oneflow/python/nn/modules/reshape.py
  oneflow/python/nn/modules/squeeze.py
  oneflow/python/nn/modules/transpose.py
  oneflow/python/ops/math_ops.py
  oneflow/python/test/modules/test_cast.py
Labels: api, automerge, documentation, eager, op

#4845 Add where module
  oneflow/python/nn/modules/broadcast_like.py
  oneflow/python/nn/modules/where.py
  oneflow/python/ops/array_ops.py
  oneflow/python/test/modules/test_broadcast_like.py
  oneflow/python/test/modules/test_where.py
Labels: api, automerge, documentation, enhancement, feature, python

#4860 dev_compare_cfg_file
  tools/cfg/template_convert.py
Labels: automerge, feature, tooling

#4857 stateful local opkernel: return a temp parallel ctx
  oneflow/api/python/env/env.cpp
  oneflow/api/python/env/env.h
  oneflow/api/python/env/env_api.h
  oneflow/python/framework/distribute.py
  oneflow/user/kernels/stateful_local_opkernel.cpp
Labels: automerge, eager, enhancement

#4844 Optimize memory occupancy for interface 1.0
  oneflow/core/autograd/autograd_engine.cpp
  oneflow/core/autograd/autograd_engine.h
  oneflow/core/vm/cuda_allocator.cpp
Labels: automerge, enhancement, system

#4861 use less event records
  oneflow/core/eager/blob_instruction_type.cpp
  oneflow/core/framework/op_interpreter/eager_mirrored_op_interpreter.cpp
  oneflow/core/vm/cuda_optional_event_record_status_querier.cpp
  oneflow/core/vm/cuda_optional_event_record_status_querier.h
  oneflow/core/vm/cuda_stream_type.cpp
  oneflow/core/vm/cuda_stream_type.h
  oneflow/core/vm/instruction.cpp
  oneflow/core/vm/instruction.msg.h
  oneflow/core/vm/stream_type.h
Labels: automerge, enhancement, system

#4853 Refine cast grad func.
  oneflow/core/autograd/gradient_funcs/cast.cpp
Labels: automerge, enhancement, system

#4839 copy eager blob object to/from numpy in c++, use busy loop to wait
  oneflow/api/foreign_lock_helper.h
  oneflow/api/python/framework/tensor.cpp
  oneflow/api/python/gil_foreign_lock_helper.cpp
  oneflow/api/python/ofblob/ofblob.e.h
  oneflow/python/framework/tensor.py
  oneflow/python/test/tensor/test_tensor.py
Labels: automerge, eager, enhancement

#4855 align squeeze module with torch
  oneflow/python/nn/modules/argmax.py
  oneflow/python/nn/modules/loss.py
  oneflow/python/nn/modules/squeeze.py
  oneflow/python/test/modules/test_squeeze.py
Labels: api, automerge, bug, python

#4848 Fix groupnorm
  oneflow/python/ops/nn_ops.py
  oneflow/python/test/ops/test_group_norm_op.py
  oneflow/user/ops/reshape_like_op.cpp
Labels: automerge, bug, op

#4838 use composed attr map in contexts
  oneflow/api/python/framework/op_expr.cpp
  oneflow/core/autograd/gradient_funcs/default.cpp
  oneflow/core/framework/op_builder.cpp
  oneflow/core/framework/op_expr.cpp
  oneflow/core/framework/op_expr.h
  oneflow/core/framework/user_op_kernel_registry.h
  oneflow/core/kernel/user_kernel.cpp
  oneflow/core/operator/user_op.cpp
  oneflow/user/kernels/stateful_local_opkernel.cpp
  oneflow/user/kernels/stateful_local_opkernel.h
Labels: automerge, eager, enhancement

#4870 flow.Size support negative index and add test
  oneflow/api/python/framework/shape.cpp
  oneflow/python/test/ops/test_size.py
Labels: automerge, eager, feature, python

#4867 fix export experimental docs bug
  docs/source/experimental.rst
  docs/source/optim.rst
  oneflow/python/nn/modules/greater.py
Labels: api, automerge, bug, documentation, python

#4873 reorder VirtualMachine fields
  oneflow/core/vm/virtual_machine.msg.h
Labels: automerge, bug, eager, system

#4865 Align module params with torch
  oneflow/python/nn/modules/math_ops.py
  oneflow/python/test/modules/test_math_ops.py
  oneflow/python/test/modules/test_mean.py
Labels: automerge, bug, eager

#4876 Generate cfg header and source files in parallel and prevent rebuild from scratch when Python version changes
  cmake/cfg.cmake
  cmake/oneflow.cmake
  tools/cfg/template_convert.py
Labels: automerge, build, enhancement

#4872 fix interpreter determin output leaf and grad
  oneflow/core/framework/op_interpreter/op_interpreter.cpp
  oneflow/python/test/tensor/test_tensor.py
Labels: automerge, bug, system

#4875 support crossentropy loss 3dim
  oneflow/python/nn/modules/loss.py
  oneflow/python/test/modules/test_crossentropyloss.py
Labels: automerge, bug, op, python

#4874 supoort nllloss 3dim
  oneflow/python/nn/modules/loss.py
  oneflow/python/test/modules/test_nllloss.py
Labels: automerge, bug, op, python

#4862 Device compute dep object
  oneflow/core/eager/local_call_opkernel_phy_instr_operand.cpp
  oneflow/core/framework/device.cpp
  oneflow/core/framework/device.h
  oneflow/core/framework/op_expr.cpp
  oneflow/init.py
  oneflow/user/kernels/stateful_local_opkernel.cpp
  oneflow/user/kernels/stateful_local_opkernel.h
Labels: automerge, eager, enhancement, system

#4879 remove cambricon quantization test
  oneflow/python/test/ops/test_quantize_op.py
Labels: automerge, bug, test

#4852 Use dlopen to call ibverbs APIs
  ci/test/2node_op_test.sh
  cmake/third_party.cmake
  oneflow/core/comm_network/ibverbs/ibverbs_comm_network.cpp
  oneflow/core/comm_network/ibverbs/ibverbs_memory_desc.cpp
  oneflow/core/comm_network/ibverbs/ibverbs_qp.cpp
  oneflow/core/dl/include/ibv.h
  oneflow/core/dl/include/wrapper.h
  oneflow/core/dl/lib/ibv_wrapper.cpp
  oneflow/core/dl/lib/wrapper.cpp
  oneflow/core/job/runtime.cpp
  oneflow/python/deprecated/init_cluster_env.py
Labels: automerge, feature, system

#4842 Add copy user op
  oneflow/api/python/framework/device.cpp
  oneflow/core/autograd/gradient_funcs/copy.cpp
  oneflow/core/eager/cuda_opkernel_instruction_type.cpp
  oneflow/core/framework/infer_util.h
  oneflow/core/framework/op_expr.cpp
  oneflow/core/framework/op_expr_helper.cpp
  oneflow/core/framework/op_expr_helper.h
  oneflow/core/framework/op_interpreter/eager_mirrored_op_interpreter.cpp
  oneflow/python/framework/tensor.py
  oneflow/python/nn/module.py
  oneflow/python/nn/modules/to.py
  oneflow/python/test/modules/test_batchnorm.py
  oneflow/python/test/modules/test_conv.py
  oneflow/python/test/modules/test_normalization.py
  oneflow/python/test/modules/test_to.py
  oneflow/python/test/tensor/test_tensor.py
  oneflow/user/kernels/copy_kernel.cpp
  oneflow/user/ops/copy_op.cpp
Labels: automerge, enhancement, system

#4882 Fix reduce sum grad func.
  oneflow/core/autograd/gradient_funcs/reduce_ops.cpp
  oneflow/core/framework/op_expr_helper.cpp
Labels: automerge, enhancement, system

#4880 align dim size funtion
  oneflow/python/framework/tensor.py
  oneflow/python/nn/init.py
Labels: automerge, bug, eager

#4883 support expand and repeat op int datatype
  oneflow/python/test/modules/test_expand.py
  oneflow/python/test/modules/test_repeat.py
  oneflow/user/kernels/expand_kernel.cpp
  oneflow/user/kernels/expand_kernel.cu
Labels: api, automerge, documentation, op, python

#4864 return LocalTensor (TensorTuple) directly from op expr __call__
  oneflow/core/object_msg/embedded_skiplist.h
  oneflow/python/autograd/autograd.py
  oneflow/python/framework/op_expr_util.py
  oneflow/python/framework/tensor.py
  oneflow/python/framework/tensor_tuple_util.py
  tools/generate_oneflow_symbols_export_file.py
Labels: automerge, eager, enhancement, python

#4881 Support custom parameters for optimizer
  oneflow/core/framework/attr_map.cpp
  oneflow/python/nn/optimizer/adam.py
  oneflow/python/nn/optimizer/adamw.py
  oneflow/python/nn/optimizer/optimizer.py
  oneflow/python/nn/optimizer/rmsprop.py
  oneflow/python/nn/optimizer/sgd.py
  oneflow/python/test/modules/test_optim_adam.py
  oneflow/python/test/modules/test_optim_adamw.py
  oneflow/python/test/modules/test_optim_rmsprop.py
  oneflow/python/test/modules/test_optim_sgd.py
Labels: automerge, eager, feature, python

#4877 align transpose module with pytorch
  oneflow/python/nn/modules/activation.py
  oneflow/python/nn/modules/argmax.py
  oneflow/python/nn/modules/transpose.py
  oneflow/python/test/modules/test_expand.py
  oneflow/python/test/modules/test_transpose.py
Labels: automerge, bug, op, python

#4889 Add ones like op
  oneflow/api/python/autograd/autograd.cpp
  oneflow/core/framework/op_expr_helper.cpp
  oneflow/core/framework/op_expr_helper.h
  oneflow/python/test/modules/test_ones_like.py
  oneflow/user/kernels/ones_like_kernel.cpp
  oneflow/user/ops/ones_like_op.cpp
Labels: automerge, eager, feature, python

#4894 Cpu support conv module
  oneflow/python/nn/modules/conv.py
Labels: automerge, bug, eager, feature, op, python

#4895 Async cuda stream type
  oneflow/core/eager/cuda_blob_instruction_type.cpp
  oneflow/core/eager/cuda_opkernel_instruction_type.cpp
  oneflow/core/vm/async_cuda_stream_type.cpp
  oneflow/core/vm/async_cuda_stream_type.h
Labels: automerge, bug, eager, system

#4868 skip infer instr when physical operand != nullptr, remove unused code
  oneflow/api/python/framework/instructions_builder.cpp
  oneflow/core/eager/blob_instruction_type.cpp
  oneflow/core/eager/blob_instruction_type.h
  oneflow/core/eager/eager_blob_object.cpp
  oneflow/core/eager/eager_blob_object.h
  oneflow/core/eager/local_call_opkernel_phy_instr_operand.cpp
  oneflow/core/eager/opkernel_instruction_type.cpp
  oneflow/core/eager/release_tensor_instruction_type.cpp
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/framework/instructions_builder.h
  oneflow/core/framework/op_interpreter/eager_mirrored_op_interpreter.cpp
  oneflow/core/framework/tensor.h
  oneflow/core/framework/tensor_impl.cpp
  oneflow/core/framework/tensor_impl.h
  oneflow/core/vm/access_blob_arg_cb_phy_instr_operand.cpp
  oneflow/core/vm/access_blob_arg_cb_phy_instr_operand.h
  oneflow/core/vm/oneflow_vm.cpp
  oneflow/core/vm/read_tensor_shape_arg_cb_phy_instr_operand.cpp
  oneflow/core/vm/read_tensor_shape_arg_cb_phy_instr_operand.h
  oneflow/core/vm/release_tensor_arg_phy_instr_operand.cpp
  oneflow/core/vm/release_tensor_arg_phy_instr_operand.h
  oneflow/core/vm/sequential_instruction_type.cpp
  oneflow/core/vm/sequential_instruction_type_test.cpp
  oneflow/core/vm/virtual_machine.cpp
  oneflow/core/vm/virtual_machine.msg.h
  oneflow/python/nn/module.py
  oneflow/user/kernels/stateful_local_opkernel.cpp
  oneflow/user/kernels/stateful_local_opkernel.h
Labels: automerge, eager, enhancement

#4897 fix and check to with module on forwad and backward
  oneflow/python/nn/module.py
  oneflow/python/test/modules/test_module_to.py
  oneflow/python/test/modules/test_to.py
Labels: automerge, bug, eager, op

#4891 add JUST
  oneflow/core/framework/op_interpreter/eager_mirrored_op_interpreter.cpp
Labels: automerge, enhancement, system

#4892 Fix docs bug
  oneflow/python/nn/modules/arange.py
  oneflow/python/nn/modules/constant.py
  oneflow/python/nn/modules/container.py
  oneflow/python/nn/modules/eq.py
  oneflow/python/nn/modules/flatten.py
  oneflow/python/nn/modules/greater.py
  oneflow/python/nn/modules/less.py
  oneflow/python/nn/modules/linear.py
  oneflow/python/nn/modules/masked_fill.py
  oneflow/python/nn/modules/math_ops.py
  oneflow/python/nn/modules/normalization.py
  oneflow/python/nn/modules/pooling.py
  oneflow/python/nn/modules/reshape.py
  oneflow/python/nn/modules/squeeze.py
  oneflow/python/nn/modules/transpose.py
  oneflow/python/nn/modules/unsqueeze.py
  oneflow/python/nn/modules/where.py
  oneflow/python/test/modules/test_expand.py
Labels: automerge, bug, documentation, eager, enhancement

#4896 Add warning when no param update
  oneflow/python/nn/optimizer/optimizer.py
Labels: automerge, bug, eager, python

#4826 Add gather embedding module
  docs/source/experimental.rst
  oneflow/python/nn/modules/gather.py
  oneflow/python/nn/modules/sparse.py
  oneflow/python/test/modules/test_gather.py
  oneflow/python/test/modules/test_sparse.py
Labels: automerge, eager, enhancement

#4863 Support create cpu only tensor
  oneflow/core/framework/op_expr_helper.cpp
  oneflow/core/framework/op_expr_helper.h
  oneflow/core/framework/op_interpreter/eager_mirrored_op_interpreter.cpp
  oneflow/core/framework/op_interpreter/eager_mirrored_op_interpreter.h
  oneflow/core/framework/tensor.cpp
  oneflow/python/test/tensor/test_tensor.py
Labels: automerge, enhancement, system

#4901 Add permute module
  docs/source/experimental.rst
  oneflow/python/nn/modules/permute.py
  oneflow/python/test/modules/test_permute.py
Labels: automerge, eager, feature, op, python

#4903 remove useless code in expand module test
  oneflow/python/test/modules/test_expand.py
Labels: automerge, bug, eager, python

#4904 Add conv docs
  oneflow/python/nn/modules/conv.py
  oneflow/python/nn/modules/linear.py
Labels: automerge, documentation, eager, op, python

#4678 Fix eager test bug
  oneflow/core/job/job_build_and_infer_ctx.cpp
  oneflow/python/eager/op_executor.py
  oneflow/python/test/ops/test_dim_gather_dynamic.py
  oneflow/python/test/ops/test_fused_bias_add_dropout.py
  oneflow/python/test/ops/test_fused_bias_add_gelu.py
  oneflow/python/test/ops/test_fused_scale_tril_softmax_mask_and_scale.py
  oneflow/python/test/ops/test_gather_nd.py
  oneflow/python/test/ops/test_gpt_data_loader.py
  oneflow/python/test/ops/test_hierarchical_parallel_cast.py
  oneflow/python/test/ops/test_interface_op_read_and_write.py
  oneflow/python/test/ops/test_module_container.py
  oneflow/python/test/ops/test_optimizers.py
  oneflow/python/test/ops/test_parallel_cast.py
  oneflow/python/test/ops/test_sigmoid_cross_entropy.py
  oneflow/python/test/ops/test_softmax.py
  oneflow/python/test/ops/test_softmax_cross_entropy.py
  oneflow/python/test/ops/test_stateful_local_kernel.py
  oneflow/python/test/ops/test_summary.py
  oneflow/python/test/ops/test_watch.py
Labels: automerge, bug, eager, system

#4908 Test gpu optimizer test
  oneflow/python/test/modules/test_optim_adam.py
  oneflow/python/test/modules/test_optim_adamw.py
  oneflow/python/test/modules/test_optim_rmsprop.py
  oneflow/python/test/modules/test_optim_sgd.py
Labels: automerge, eager, enhancement, test

#4906 cache cudnn handle when inferring batchnorm tmp size
  oneflow/user/kernels/normalization_kernel.cu
Labels: automerge, enhancement, op

#4907 Fix ones zeros like
  oneflow/python/framework/check_point_v2.py
  oneflow/python/nn/modules/constant.py
  oneflow/python/nn/optimizer/adam.py
  oneflow/python/nn/optimizer/adamw.py
  oneflow/python/nn/optimizer/rmsprop.py
  oneflow/python/nn/optimizer/sgd.py
  oneflow/python/test/modules/test_optim_adam.py
  oneflow/python/test/modules/test_optim_adamw.py
  oneflow/python/test/modules/test_optim_rmsprop.py
  oneflow/python/test/modules/test_optim_sgd.py
Labels: automerge, bug, eager, enhancement, python

#4899 Bump nccl from 2.8.3 to 2.9.8
  cmake/third_party/nccl.cmake
Labels: automerge, enhancement, system

#4902 Add prelu module
  docs/source/experimental.rst
  oneflow/core/autograd/gradient_funcs/prelu.cpp
  oneflow/core/framework/op_expr_helper.cpp
  oneflow/core/framework/op_expr_helper.h
  oneflow/python/nn/modules/prelu.py
  oneflow/python/test/modules/test_prelu.py
Labels: api, automerge, eager, feature, op, python

#4589 add InitEagerSession for eager mode
  oneflow/api/python/session/session.cpp
  oneflow/api/python/session/session.h
  oneflow/api/python/session/session_api.h
  oneflow/core/comm_network/epoll/epoll_comm_network.cpp
  oneflow/core/eager/eager_blob_object.cpp
  oneflow/core/eager/eager_blob_object.h
  oneflow/core/job/resource_desc.h
  oneflow/core/job/session_global_objects_scope.cpp
  oneflow/core/job/session_global_objects_scope.h
  oneflow/python/framework/session_util.py
  oneflow/python/nn/modules/dataset.py
  oneflow/python/test/modules/test_dataset.py
Labels: api, automerge, enhancement, op, system

#4914 add hardtanh module
  docs/source/experimental.rst
  oneflow/python/nn/modules/activation.py
  oneflow/python/test/modules/test_activation.py
Labels: automerge, eager, feature, python

#4905 fix_matmul_module_test_ci_bug
  oneflow/python/test/modules/test_matmul.py
Labels: automerge, bug, ci, python

#4890 Cpu support of batchnorm layernorm module
  docs/source/experimental.rst
  oneflow/core/autograd/gradient_funcs/layer_norm.cpp
  oneflow/python/nn/modules/batchnorm.py
  oneflow/python/nn/modules/math_ops.py
  oneflow/python/nn/modules/normalization.py
  oneflow/python/nn/modules/utils.py
  oneflow/python/test/modules/test_batchnorm.py
  oneflow/python/test/modules/test_math_ops.py
  oneflow/python/test/modules/test_normalization.py
Labels: api, automerge, eager, enhancement

#4829 Add flow.tensor
  oneflow/python/framework/tensor.py
  oneflow/python/test/tensor/test_tensor.py
Labels: automerge, enhancement, system

#4921 Feat lr scheduler
  docs/source/optim.rst
  oneflow/python/nn/optimizer/cosine_scheduler.py
  oneflow/python/nn/optimizer/lr_scheduler.py
  oneflow/python/test/modules/test_lr_scheduler.py
Labels: automerge, eager, feature, python

#4918 Fix CommNetIf::RegisterMemory/UnRegisterMemory lock scope
  oneflow/core/comm_network/comm_network.h
Labels: automerge, bug, system

#4912 add leakyrelu module
  docs/source/experimental.rst
  oneflow/python/nn/modules/activation.py
  oneflow/python/test/modules/test_activation.py
Labels: api, automerge, eager, feature, op

#4917 Support cast in tensor.to
  docs/source/experimental.rst
  oneflow/python/framework/tensor.py
  oneflow/python/nn/modules/to.py
  oneflow/python/test/modules/test_to.py
  oneflow/python/test/tensor/test_tensor.py
Labels: api, automerge, enhancement, op

#4915 add hard swish module
  docs/source/experimental.rst
  oneflow/python/nn/modules/activation.py
  oneflow/python/test/modules/test_activation.py
Labels: automerge, eager, feature, python

#4900 Replace oneflow_worker with worker agent
  .github/workflows/test.yml
  ci/test/2node_op_test.sh
  ci/test/distributed_run.py
  ci/test/excludelist
  cmake/oneflow.cmake
  oneflow/core/job/oneflow_worker.cpp
  oneflow/python/deprecated/init_cluster_env.py
  oneflow/python/framework/unittest.py
Labels: automerge, ci, enhancement

#4919 add hardsigmoid module
  docs/source/experimental.rst
  oneflow/python/nn/modules/activation.py
  oneflow/python/test/modules/test_activation.py
Labels: api, automerge, documentation, eager, enhancement, feature

#4916 Refactor tensor
  oneflow/api/python/framework/tensor.cpp
  oneflow/core/autograd/gradient_funcs/copy.cpp
  oneflow/core/framework/infer_util.h
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/framework/op_expr.cpp
  oneflow/core/framework/op_interpreter/eager_mirrored_op_interpreter.cpp
  oneflow/core/framework/op_interpreter/op_interpreter_util.cpp
  oneflow/core/framework/tensor.cpp
  oneflow/core/framework/tensor.h
  oneflow/core/framework/tensor_impl.cpp
  oneflow/core/framework/tensor_impl.h
Labels: automerge, eager, enhancement, system

#4925 add relu6 module
  docs/source/experimental.rst
  oneflow/python/nn/modules/activation.py
  oneflow/python/test/modules/test_activation.py
Labels: automerge, eager, feature, python

#4888 add cuda test for add method(module)
  oneflow/python/test/modules/test_add.py
  oneflow/python/test/modules/test_linear.py
Labels: automerge, enhancement, op

#4923 add upsample module
  docs/source/experimental.rst
  oneflow/python/nn/modules/upsample.py
  oneflow/python/test/modules/test_upsample2d.py
Labels: automerge, documentation, eager, feature, python

#4924 add elu module
  docs/source/experimental.rst
  oneflow/python/nn/modules/activation.py
  oneflow/python/test/modules/test_activation.py
Labels: automerge, documentation, enhancement, python

#4920 improve ofrecord unit test
  oneflow/python/test/modules/test_dataset.py
Labels: automerge, ci, eager, enhancement, test

#4933 align inplace param
  oneflow/python/nn/modules/activation.py
Labels: api, automerge, feature, python

#4930 refactor SGDUpdate and MomentumUpdate UserOp
  oneflow/python/nn/optimizer/sgd.py
  oneflow/user/kernels/model_update_kernel_util.cpp
  oneflow/user/kernels/model_update_kernel_util.cu
  oneflow/user/kernels/model_update_kernel_util.h
  oneflow/user/kernels/model_update_kernels.cpp
  oneflow/user/ops/model_update_ops.cpp
Labels: automerge, eager, enhancement, op, refactor

#4898 Dev support tensor slice
  oneflow/python/framework/tensor.py
  oneflow/python/nn/modules/slice.py
  oneflow/python/ops/array_ops.py
  oneflow/python/test/modules/test_slice.py
  oneflow/python/test/tensor/test_tensor.py
  oneflow/user/kernels/slice_kernel.cpp
Labels: automerge, eager, enhancement

#4927 add tensor.zeros_() and SoftSyncStream instr
  oneflow/api/python/framework/tensor.cpp
  oneflow/core/eager/blob_instruction_type.cpp
  oneflow/core/eager/blob_instruction_type.h
  oneflow/core/eager/cpu_blob_instruction_type.cpp
  oneflow/core/eager/cuda_blob_instruction_type.cpp
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/framework/instructions_builder.h
  oneflow/core/framework/op_interpreter/eager_mirrored_op_interpreter.cpp
  oneflow/core/kernel/kernel_util.cpp
  oneflow/core/kernel/kernel_util.h
  oneflow/core/register/ofblob.h
  oneflow/core/vm/soft_sync_stream_phy_instr_operand.cpp
  oneflow/core/vm/soft_sync_stream_phy_instr_operand.h
  oneflow/python/framework/tensor.py
  oneflow/python/nn/optimizer/optimizer.py
  oneflow/python/test/tensor/test_tensor.py
Labels: automerge, eager, enhancement

#4929 Add logsigmoid softplus module
  docs/source/experimental.rst
  oneflow/python/nn/modules/activation.py
  oneflow/python/nn/modules/arange.py
  oneflow/python/test/modules/test_activation.py
Labels: automerge, documentation, eager, python

#4926 Add module backward test
  oneflow/core/autograd/gradient_funcs/transpose.cpp
  oneflow/core/framework/op_expr_helper.cpp
  oneflow/core/framework/op_expr_helper.h
  oneflow/python/test/modules/test_activation.py
  oneflow/python/test/modules/test_transpose.py
  oneflow/python/test/modules/test_util.py
Labels: automerge, eager, enhancement

#4941 fix flow.save
  oneflow/python/framework/check_point_v2.py
  oneflow/python/framework/tensor.py
  oneflow/python/test/modules/test_module.py
Labels: automerge, bug, eager

#4586 fix zero point in fake quantization pass
  oneflow/core/job_rewriter/quantization_aware_training.cpp
  oneflow/user/kernels/fake_quantization_kernel.cpp
Labels: automerge, bug, system

#4950 Also allow ONEFLOW_DEBUG=1 to enable debug mode
  oneflow/core/job/resource_desc.cpp
Labels: automerge, enhancement, system

#4939 Add Device Descriptor
  oneflow/core/device/basic_device_descriptor_list.cpp
  oneflow/core/device/basic_device_descriptor_list.h
  oneflow/core/device/cuda_device_descriptor.cpp
  oneflow/core/device/cuda_device_descriptor.h
  oneflow/core/device/cuda_device_descriptor_class.cpp
  oneflow/core/device/device_descriptor.h
  oneflow/core/device/device_descriptor_class.cpp
  oneflow/core/device/device_descriptor_class.h
  oneflow/core/device/device_descriptor_list.h
  oneflow/core/device/node_device_descriptor.cpp
  oneflow/core/device/node_device_descriptor.h
  oneflow/core/device/node_device_descriptor_manager.cpp
  oneflow/core/device/node_device_descriptor_manager.h
  oneflow/core/job/env_global_objects_scope.cpp
  oneflow/core/job/session_global_objects_scope.cpp
Labels: automerge, feature, system

#4938 Refactor Optimizers for eager
  oneflow/python/nn/optimizer/adam.py
  oneflow/python/nn/optimizer/adamw.py
  oneflow/python/nn/optimizer/rmsprop.py
  oneflow/user/kernels/model_update_kernel_util.cpp
  oneflow/user/kernels/model_update_kernel_util.cu
  oneflow/user/kernels/model_update_kernel_util.h
  oneflow/user/kernels/model_update_kernels.cpp
  oneflow/user/ops/model_update_ops.cpp
Labels: automerge, enhancement, op, refactor

#4949 Add instructions on making sys env permanent
  docs/source/troubleshooting.md
Labels: automerge, build, documentation

#4913 add gradient functions for dim_gather op
  oneflow/core/autograd/gradient_funcs/dim_gather.cpp
  oneflow/core/framework/op_expr_helper.cpp
  oneflow/core/framework/op_expr_helper.h
  oneflow/python/test/modules/test_gather.py
Labels: automerge, enhancement, op

#4961 add gradient funs for unary and binary math op
  oneflow/core/autograd/gradient_funcs/math_binary_op.cpp
  oneflow/core/autograd/gradient_funcs/math_unary_op.cpp
  oneflow/core/framework/op_expr_helper.cpp
  oneflow/core/framework/op_expr_helper.h
  oneflow/python/nn/modules/math_ops.py
  oneflow/python/test/modules/test_exp.py
  oneflow/python/test/modules/test_math_ops.py
  oneflow/python/test/modules/test_pow.py
Labels: automerge, enhancement, op

#4937 Refactor consistent tensor
  oneflow/api/python/framework/tensor.cpp
  oneflow/core/framework/op_interpreter/eager_consistent_op_interpreter.cpp
  oneflow/core/framework/op_interpreter/op_interpreter_util.cpp
  oneflow/core/framework/op_interpreter/op_interpreter_util.h
  oneflow/core/framework/tensor.h
  oneflow/core/framework/tensor_impl.cpp
  oneflow/core/framework/tensor_impl.h
  oneflow/python/framework/check_point_v2.py
  oneflow/python/framework/tensor.py
  oneflow/python/test/tensor/test_tensor.py
Labels: automerge, eager, enhancement, system

#4958 support tensorrt7 qat
  .github/workflows/pr.yml
  oneflow/core/job_rewriter/quantization_aware_training.cpp
Labels: automerge, enhancement, system

#4948 fix softmax testcase
  oneflow/python/test/modules/test_activation.py
Labels: automerge, bug, eager, test

#4970 Add FunctionNode op_name
  oneflow/api/python/autograd/function_node.cpp
  oneflow/core/autograd/autograd_engine.cpp
  oneflow/core/autograd/autograd_engine.h
  oneflow/core/framework/op_expr.cpp
  oneflow/core/framework/op_interpreter/op_interpreter.cpp
Labels: eager, feature

#4976 Rename type_name to op_type_name
  oneflow/api/python/framework/op_expr.cpp
  oneflow/core/framework/op_expr.cpp
  oneflow/core/framework/op_expr.h
  oneflow/core/framework/op_interpreter/op_interpreter.cpp
Labels: eager, enhancement

#4935 add module backward
  oneflow/core/autograd/gradient_funcs/expand.cpp
  oneflow/core/framework/op_expr_helper.cpp
  oneflow/core/framework/op_expr_helper.h
  oneflow/python/nn/modules/expand.py
  oneflow/python/nn/modules/repeat.py
  oneflow/python/test/modules/test_expand.py
  oneflow/python/test/modules/test_pow.py
  oneflow/python/test/modules/test_repeat.py
  oneflow/python/test/modules/test_reshape.py
  oneflow/python/test/modules/test_squeeze.py
Labels: automerge, eager, feature, python

#4966 rewrite unsqueeze backward
  oneflow/core/autograd/gradient_funcs/unsqueeze.cpp
  oneflow/python/test/modules/test_unsqueeze.py
Labels: api, automerge, eager, enhancement

#4942 add module backward
  oneflow/python/nn/modules/argmax.py
  oneflow/python/nn/modules/greater.py
  oneflow/python/nn/modules/less.py
  oneflow/python/test/modules/test_argmax.py
  oneflow/python/test/modules/test_greater.py
  oneflow/python/test/modules/test_less.py
  oneflow/python/test/modules/test_matmul.py
  oneflow/python/test/modules/test_negative.py
  oneflow/python/test/tensor/test_tensor.py
Labels: automerge, ci, eager, feature, test

#4980 fix activation ci bug
  oneflow/python/test/modules/test_activation.py
Labels: automerge, bug, ci, eager, python

#4951 Hashable attr map
  oneflow/core/common/util.h
  oneflow/core/framework/attr_map.cpp
  oneflow/core/framework/attr_map.h
  oneflow/core/framework/attr_map_test.cpp
  oneflow/core/framework/attr_value.cpp
  oneflow/core/framework/attr_value.h
  oneflow/user/kernels/stateful_local_opkernel.cpp
  oneflow/user/kernels/stateful_local_opkernel.h
Labels: automerge, enhancement, system

#4981 Fix Global<CommNet>::Delete()
  oneflow/core/job/runtime.cpp
Labels: automerge, bug, system

#4979 add of_softmax_use_fast_math
  CMakeLists.txt
  oneflow/core/cuda/softmax.cuh
Labels: automerge, enhancement, op

#4992 Fix local tensor requires grad
  oneflow/api/python/framework/tensor.cpp
  oneflow/python/framework/tensor.py
  oneflow/python/test/tensor/test_tensor.py
Labels: api, automerge, bug, python

#4985 Support localtensor slice
  oneflow/python/framework/tensor.py
Labels: automerge, eager, enhancement

#4969 Symbol::shared_from_symbol
  oneflow/core/common/symbol.h
  oneflow/core/common/symbol_test.cpp
Labels: automerge, enhancement, system

#4983 CI formats code automatically
  .github/workflows/test.yml
Labels: automerge, ci, enhancement

#4984 Eager consistent tensor
  oneflow/api/python/framework/tensor.cpp
  oneflow/core/autograd/autograd_meta.h
  oneflow/core/common/maybe.h
  oneflow/core/common/symbol.h
  oneflow/core/common/type_traits.h
  oneflow/core/framework/device.cpp
  oneflow/core/framework/device.h
  oneflow/core/framework/dtype.h
  oneflow/core/framework/op_interpreter/op_interpreter_util.cpp
  oneflow/core/framework/tensor.cpp
  oneflow/core/framework/tensor.h
  oneflow/core/framework/tensor_impl.cpp
  oneflow/core/framework/tensor_impl.h
  oneflow/core/operator/operator.cpp
  oneflow/core/operator/operator.h
  oneflow/core/rpc/include/global_process_ctx.h
  oneflow/core/rpc/lib/global_process_ctx.cpp
Labels: automerge, enhancement, system

#4957 add resnet50 model test
  oneflow/python/test/modules/resnet50_model.py
  oneflow/python/test/modules/test_resnet50_with_bn.py
  oneflow/python/test/modules/test_resnet50_without_bn.py
Labels: automerge, ci, eager, enhancement, test

#4998 Add arg where module
  docs/source/experimental.rst
  oneflow/python/nn/modules/argwhere.py
  oneflow/python/ops/array_ops.py
  oneflow/python/test/modules/test_argmax.py
  oneflow/python/test/modules/test_argwhere.py
Labels: automerge, documentation, eager, op, python

#4990 fix hierarchical_sub_task_graph_builder condition
  oneflow/core/graph/boxing/hierarchical_sub_task_graph_builder_impl.cpp
Labels: automerge, bug, system

#4928 Add __str__ and tolist for tensor
  oneflow/api/python/autograd/function_node.cpp
  oneflow/api/python/framework/device.cpp
  oneflow/api/python/framework/op_expr.cpp
  oneflow/core/autograd/autograd_engine.cpp
  oneflow/core/autograd/autograd_engine.h
  oneflow/core/framework/device.cpp
  oneflow/core/framework/device.h
  oneflow/core/framework/op_expr.cpp
  oneflow/core/framework/op_expr.h
  oneflow/core/framework/op_interpreter/op_interpreter.cpp
  oneflow/python/framework/tensor.py
  oneflow/python/framework/tensor_str.py
  oneflow/python/nn/modules/batchnorm.py
  oneflow/python/nn/modules/math_ops.py
  oneflow/python/nn/modules/normalization.py
  oneflow/python/test/tensor/test_tensor.py
Labels: automerge, enhancement, python

#5007 Add squeeze module backward
  oneflow/core/autograd/gradient_funcs/squeeze.cpp
  oneflow/python/test/modules/test_squeeze.py
Labels: automerge, ci, eager, enhancement, python

#4968 RPC backend local supports barrier of barrier_num > 1
  oneflow/core/rpc/include/local.h
  oneflow/core/rpc/lib/local.cpp
Labels: automerge, enhancement, system

#4967 add activation module backward test
  oneflow/python/nn/modules/permute.py
  oneflow/python/test/modules/test_activation.py
  oneflow/python/test/modules/test_permute.py
  oneflow/python/test/modules/test_prelu.py
Labels: automerge, bug, ci, eager, test

#5005 Add sys_ptrace for build docker container
  .github/workflows/test.yml
Labels: automerge, ci, enhancement

#5002 Refine PYTHONPATH getting in cmake
  cmake/oneflow.cmake
Labels: automerge, build, enhancement

#4996 Refactor scope parallel desc
  oneflow/api/python/symbol/scope_symbol.cpp
  oneflow/core/job/job_build_and_infer_ctx.cpp
  oneflow/core/job/scope.cpp
  oneflow/core/job/scope.h
  oneflow/core/job_rewriter/add_ssp_variable_proxy.cpp
  oneflow/core/operator/operator.cpp
Labels: automerge, enhancement, system

#4978 add arange module backward
  oneflow/python/nn/modules/arange.py
  oneflow/python/test/modules/test_arange.py
Labels: automerge, eager, enhancement, test

#5017 CI skips resnet50 to prevent segfault
  .github/workflows/test.yml
  oneflow/python/test/modules/test_resnet50_with_bn.py
  oneflow/python/test/modules/test_resnet50_without_bn.py
Labels: automerge, ci, enhancement

#4997 NetSocket device enumeration
  oneflow/core/device/basic_device_descriptor_list.cpp
  oneflow/core/device/basic_device_descriptor_list.h
  oneflow/core/device/net_socket_device_descriptor.cpp
  oneflow/core/device/net_socket_device_descriptor.h
  oneflow/core/device/net_socket_device_descriptor_class.cpp
Labels: automerge, feature, system

#4989 Add device unmatch info
  oneflow/core/common/error.cpp
  oneflow/core/common/error.h
  oneflow/core/common/error.proto
  oneflow/core/common/exception.h
  oneflow/core/framework/op_interpreter/eager_mirrored_op_interpreter.cpp
  oneflow/python/framework/op_expr_util.py
Labels: automerge, bug, ci, eager, enhancement, test

#4988 rewrite matmul op backward
  oneflow/core/autograd/gradient_funcs/matmul.cpp
  oneflow/core/framework/op_expr_helper.cpp
  oneflow/core/framework/op_expr_helper.h
Labels: automerge, eager, enhancement, test

#5013 Add concat module backward
  oneflow/core/autograd/gradient_funcs/concat.cpp
  oneflow/core/framework/op_expr_helper.cpp
  oneflow/core/framework/op_expr_helper.h
  oneflow/python/test/modules/test_concat.py
Labels: automerge, eager, enhancement, python

#5014 rewrite dropout backward
  oneflow/core/autograd/gradient_funcs/dropout.cpp
  oneflow/core/framework/op_expr_helper.cpp
  oneflow/core/framework/op_expr_helper.h
  oneflow/python/nn/modules/dropout.py
  oneflow/python/test/modules/test_dropout.py
Labels: automerge, eager, enhancement, test
