Repository Oneflow-Inc/oneflow, pull requests merged in 2021-08, with the labels that each got.

#5620 Support 0shape tensor
  oneflow/api/python/functional/indexing.cpp
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/core/functional/tensor_index.cpp
  oneflow/core/kernel/kernel_util.cu
  oneflow/core/kernel/util/cuda_arithemetic_interface.cu
  oneflow/core/kernel/util/cuda_dnn_interface.cu
  oneflow/core/ndarray/ndarray_apply_binary_core.cu
  oneflow/core/ndarray/ndarray_apply_broadcast_binary.h
  oneflow/core/ndarray/ndarray_apply_broadcast_binary_core.cu
  oneflow/core/ndarray/ndarray_apply_broadcast_unary_core.cu
  oneflow/core/ndarray/ndarray_apply_unary_core.cu
  oneflow/core/ndarray/ndarray_assign_core.cu
  oneflow/user/kernels/add_n_kernel.cu
  oneflow/user/kernels/clip_by_value_kernel.cu
  oneflow/user/kernels/concat_kernel.cpp
  oneflow/user/kernels/constant_kernel.cpp
  oneflow/user/kernels/empty_kernel.cpp
  oneflow/user/kernels/math_binary_elementwise_kernel.cu
  oneflow/user/kernels/math_unary_elementwise_kernel.cu
  oneflow/user/kernels/reduce_kernel.cpp
  oneflow/user/kernels/reduce_like_kernels.cpp
  oneflow/user/kernels/slice_util.cu
  oneflow/user/kernels/triu_kernel.cu
  oneflow/user/ops/math_binary_broadcast_ops.cpp
  oneflow/user/ops/reshape_op.cpp
  oneflow/user/ops/slice_op.cpp
  python/oneflow/framework/tensor.py
  python/oneflow/nn/modules/reduce_ops.py
  python/oneflow/ops/array_ops.py
  python/oneflow/test/modules/test_abs.py
  python/oneflow/test/modules/test_activation.py
  python/oneflow/test/modules/test_add.py
  python/oneflow/test/modules/test_argwhere.py
  python/oneflow/test/modules/test_cast.py
  python/oneflow/test/modules/test_ceil.py
  python/oneflow/test/modules/test_clamp.py
  python/oneflow/test/modules/test_concat.py
  python/oneflow/test/modules/test_constant.py
  python/oneflow/test/modules/test_div.py
  python/oneflow/test/modules/test_eq.py
  python/oneflow/test/modules/test_expm1.py
  python/oneflow/test/modules/test_fmod.py
  python/oneflow/test/modules/test_greater.py
  python/oneflow/test/modules/test_ne.py
  python/oneflow/test/modules/test_negative.py
  python/oneflow/test/modules/test_pow.py
  python/oneflow/test/modules/test_reshape.py
  python/oneflow/test/modules/test_sign.py
  python/oneflow/test/modules/test_squeeze.py
  python/oneflow/test/modules/test_sub.py
  python/oneflow/test/modules/test_sum.py
  python/oneflow/test/modules/test_transpose.py
  python/oneflow/test/modules/test_triu.py
  python/oneflow/test/modules/test_unsqueeze.py
  python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py
Labels: automerge, feature, system

#5631 add batchnorm3d module
  docs/source/nn.rst
  python/oneflow/nn/__init__.py
  python/oneflow/nn/modules/batchnorm.py
  python/oneflow/test/modules/test_batchnorm.py
  python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py
Labels: api, automerge, eager, feature, interface, op

#5619 Add tag for Optional inplace constructor
  oneflow/core/common/optional.h
Labels: automerge, bug, refactor, system

#5689 enlarge tolerance of dataloader test
  python/oneflow/test/dataloader/test_tensor_dataset.py
Labels: automerge, enhancement, python, test

#5327 Add conv3d Module
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  python/oneflow/nn/__init__.py
  python/oneflow/nn/modules/conv.py
  python/oneflow/test/modules/test_conv3d.py
Labels: automerge, eager, enhancement, feature, op

#5552 0-dim tensor support
  oneflow/api/python/framework/tensor.cpp
  oneflow/core/common/fixed_vector.h
  oneflow/core/common/shape.cpp
  oneflow/core/common/shape.h
  oneflow/core/device/memory_copier.cpp
  oneflow/core/device/memory_copier.h
  oneflow/core/eager/eager_blob_object.cpp
  oneflow/core/framework/tensor_impl.cpp
  oneflow/core/framework/tensor_meta.h
  oneflow/core/graph/task_graph.cpp
  oneflow/core/graph/task_node.cpp
  oneflow/core/graph/task_node.h
  oneflow/core/job/intra_job_mem_sharing_util.cpp
  oneflow/core/job/job_build_and_infer_ctx.cpp
  oneflow/core/job/sbp_signature_builder.cpp
  oneflow/core/ndarray/xpu_shape.cpp
  oneflow/core/operator/interface_op_util.cpp
  oneflow/core/operator/operator.cpp
  oneflow/core/register/blob_desc.cpp
  oneflow/core/register/register_desc.cpp
  oneflow/core/register/register_desc.h
  oneflow/core/register/tensor_slice_copier.cpp
  oneflow/user/kernels/slice_kernel.cpp
  oneflow/user/ops/add_n_op.cpp
  oneflow/user/ops/argmax_op.cpp
  oneflow/user/ops/constant_op.cpp
  oneflow/user/ops/empty_op.cpp
  oneflow/user/ops/layer_norm_op.cpp
  oneflow/user/ops/model_update_ops.cpp
  oneflow/user/ops/slice_op.cpp
  oneflow/user/ops/squeeze_op.cpp
  python/oneflow/compatible/single_client/ops/array_ops.py
  python/oneflow/compatible/single_client/test/ops/test_argmax.py
  python/oneflow/compatible/single_client/test/ops/test_bce_loss.py
  python/oneflow/compatible/single_client/test/ops/test_bce_with_logits_loss.py
  python/oneflow/compatible/single_client/test/ops/test_dynamic_loss_scale_schedule.py
  python/oneflow/compatible/single_client/test/ops/test_l1loss.py
  python/oneflow/compatible/single_client/test/ops/test_squeeze.py
  python/oneflow/framework/tensor.py
  python/oneflow/nn/modules/argmax.py
  python/oneflow/nn/modules/constant.py
  python/oneflow/nn/modules/loss.py
  python/oneflow/nn/modules/math_ops.py
  python/oneflow/nn/modules/norm.py
  python/oneflow/nn/modules/reduce_ops.py
  python/oneflow/nn/utils/clip_grad.py
  python/oneflow/test/dataloader/test_tensor_dataset.py
  python/oneflow/test/modules/test_0_dim_tensor.py
  python/oneflow/test/modules/test_dataset.py
  python/oneflow/test/modules/test_resnet50_with_bn.py
  python/oneflow/test/modules/test_resnet50_without_bn.py
  python/oneflow/utils/data/sampler.py
  python/oneflow/utils/vision/transforms/functional.py
Labels: automerge, eager, enhancement, feature, need-simple-ci

#5683 Multi-Runtime for multi nn.Graph
  oneflow/core/framework/multi_client_session_context.cpp
  oneflow/core/job/runtime.cpp
  oneflow/core/job/runtime.h
  oneflow/core/job/runtime_job_descs.cpp
  oneflow/core/job/runtime_job_descs.h
  oneflow/core/job/session_global_objects_scope.cpp
  python/oneflow/test/graph/test_multi_graph.py
Labels: feature, interface, refactor, system

#5685 multi client multi machine test
  .github/workflows/test.yml
  ci/test/2node_op_test_multi_client.sh
  ci/test/distributed_run.py
  ci/test/generic_test_multi_client.sh
  ci/test/test_speed_multi_client.sh
  python/oneflow/framework/unittest.py
  python/oneflow/test/modules/test_allreduce.py
Labels: automerge, ci, feature

#5672 [part4]Remove singleclient outdated api
  docs/source/nn.rst
  python/oneflow/__init__.py
  python/oneflow/nn/__init__.py
  python/oneflow/ops/loss_ops.py
  python/oneflow/ops/losses.py
  python/oneflow/ops/math_binary_elementwise_ops.py
  python/oneflow/ops/one_hot.py
  python/oneflow/ops/partial_fc_sample.py
  python/oneflow/ops/prelu.py
  python/oneflow/ops/random_ops.py
  python/oneflow/ops/random_util.py
  python/oneflow/ops/tensor_buffer_ops.py
Labels: automerge, enhancement, python

#5271 Support tensor.to()/to_local()
  oneflow/api/python/framework/device.cpp
  oneflow/core/autograd/gradient_funcs/consistent_cast.cpp
  oneflow/core/autograd/gradient_funcs/eager_nccl_broadcast.cpp
  oneflow/core/common/flat_shape.cpp
  oneflow/core/common/flat_shape.h
  oneflow/core/common/optional_test.cpp
  oneflow/core/device/device_context.h
  oneflow/core/eager/foreign_boxing_util.h
  oneflow/core/framework/device.cpp
  oneflow/core/framework/nd_sbp.cpp
  oneflow/core/framework/nd_sbp.h
  oneflow/core/framework/op_expr.cpp
  oneflow/core/framework/op_expr.h
  oneflow/core/framework/op_expr_grad_function.h
  oneflow/core/framework/op_interpreter.h
  oneflow/core/framework/op_interpreter/eager_consistent_op_interpreter.cpp
  oneflow/core/framework/op_interpreter/eager_mirrored_op_interpreter.cpp
  oneflow/core/framework/op_interpreter/op_interpreter.cpp
  oneflow/core/framework/op_kernel.h
  oneflow/core/framework/placement_sbp_util.cpp
  oneflow/core/framework/placement_sbp_util.h
  oneflow/core/framework/placement_sbp_util_test.cpp
  oneflow/core/framework/rank_group_rpc_util.cpp
  oneflow/core/framework/rpc_token.cpp
  oneflow/core/framework/rpc_token.h
  oneflow/core/framework/rpc_util.cpp
  oneflow/core/framework/rpc_util.h
  oneflow/core/framework/sync_symbol_consistent_tensor_meta.cpp
  oneflow/core/framework/sync_symbol_parallel_desc.cpp
  oneflow/core/framework/sync_symbol_parallel_distribution.cpp
  oneflow/core/framework/tensor_impl.cpp
  oneflow/core/framework/tensor_impl.h
  oneflow/core/framework/tensor_rpc_util.cpp
  oneflow/core/framework/tensor_rpc_util.h
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/consistent_cast.cpp
  oneflow/core/job/parallel_desc.cpp
  oneflow/core/job/parallel_desc.h
  oneflow/core/kernel/kernel.h
  oneflow/core/rpc/lib/global_process_ctx.cpp
  oneflow/user/kernels/eager_nccl_kernels.cu
  oneflow/user/kernels/stateful_local_opkernel.h
  oneflow/user/ops/eager_nccl_ops.cpp
  python/oneflow/__init__.py
  python/oneflow/nn/modules/consistent_cast.py
Labels: automerge, enhancement, system

#5475 added nn.RecordBytesDecoder with its test
  docs/source/nn.rst
  python/oneflow/nn/__init__.py
  python/oneflow/nn/modules/dataset.py
  python/oneflow/test/modules/test_dataset.py
Labels: automerge, eager, enhancement, test

#5674 [part5]Remove singleclient outdated api
  python/oneflow/__init__.py
  python/oneflow/nn/__init__.py
  python/oneflow/ops/count_not_finite.py
  python/oneflow/ops/domain_ops.py
  python/oneflow/ops/eager_nccl_ops.py
  python/oneflow/ops/linalg.py
  python/oneflow/ops/quantize_ops.py
  python/oneflow/ops/reduce_mean.py
  python/oneflow/ops/regularizer_util.py
  python/oneflow/ops/two_stage_reduce.py
  python/oneflow/ops/user_op_builder.py
Labels: automerge, documentation, python

#5701 Fix url not downloadable in some browers
  tools/create_pip_index.py
Labels: automerge, ci, enhancement

#5691 export datasets interface
  python/oneflow/__init__.py
  python/oneflow/nn/modules/constant.py
  python/oneflow/test/dataloader/test_cifar_dataset.py
  python/oneflow/test/dataloader/test_fashion_mnist_dataset.py
  python/oneflow/test/dataloader/test_lenet.py
  python/oneflow/test/dataloader/test_numpy_dataset.py
  python/oneflow/test/dataloader/test_tensor_dataset.py
  python/setup.py
Labels: automerge, eager, enhancement, need-simple-ci

#5698 support any number positional arguments for ones and zeros op
  python/oneflow/nn/modules/constant.py
  python/oneflow/nn/modules/loss.py
  python/oneflow/nn/modules/math_ops.py
Labels: automerge, enhancement, op

#5705 Fix macOS for recent changes
  oneflow/core/framework/rpc_token.cpp
  oneflow/core/framework/rpc_util.cpp
  oneflow/core/job/env_global_objects_scope.cpp
Labels: automerge, build, ci, enhancement, need-simple-ci

#5706 fix circular deps of sbp python module
  python/oneflow/__init__.py
  python/oneflow/nn/modules/constant.py
Labels: automerge, enhancement, python

#5712 Rename cpu to async cpu
  oneflow/core/eager/cpu_blob_instruction_type.cpp
  oneflow/core/eager/cpu_opkernel_instruction_type.cpp
  oneflow/core/eager/release_tensor_instruction_type.cpp
  oneflow/core/vm/async_cpu_stream_type.cpp
  oneflow/core/vm/async_cpu_stream_type.h
Labels: automerge, enhancement, system

#5710 Fix ClearKV("plan")
  oneflow/core/framework/nn_graph.cpp
Labels: automerge, bug, system

#5662 nn.Graph with training
  oneflow/api/python/autograd/autograd.cpp
  oneflow/api/python/framework/op_expr.cpp
  oneflow/api/python/session/session.h
  oneflow/core/framework/multi_client_session_context.cpp
  oneflow/core/framework/multi_client_session_context.h
  oneflow/core/framework/nn_graph.cpp
  oneflow/core/framework/op_interpreter/lazy_op_interpreter.cpp
  oneflow/core/framework/op_interpreter/op_interpreter_util.cpp
  oneflow/core/framework/op_interpreter/op_interpreter_util.h
  oneflow/core/framework/user_op_conf.h
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/core/job_rewriter/autograd.cpp
  oneflow/core/operator/shape_elem_cnt_op.cpp
  oneflow/user/ops/reduce_ops.cpp
  oneflow/user/ops/scalar_mul_op.cpp
  python/oneflow/nn/graph.py
  python/oneflow/nn/graph_block.py
  python/oneflow/ops/nn_ops.py
  python/oneflow/test/graph/alexnet_model.py
  python/oneflow/test/graph/ofrecord_data_utils.py
  python/oneflow/test/graph/test_alexnet_graph.py
  python/oneflow/test/graph/test_graph_linear_train.py
Labels: automerge, feature, python, system

#5703 consistent_tensor_to_api
  oneflow/api/python/symbol/placement_symbol.cpp
  python/oneflow/nn/modules/to.py
Labels: api, automerge, enhancement, python

#5636 Dev logical_and/or modules
  docs/source/oneflow.rst
  docs/source/tensor.rst
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/binary_functor.cpp
  oneflow/core/ndarray/binary_func.h
  oneflow/user/ops/math_binary_broadcast_seq.h
  python/oneflow/__init__.py
  python/oneflow/compatible/single_client/__init__.py
  python/oneflow/compatible/single_client/nn/modules/logical_and.py
  python/oneflow/compatible/single_client/nn/modules/logical_or.py
  python/oneflow/nn/modules/logical_and.py
  python/oneflow/nn/modules/logical_or.py
  python/oneflow/test/modules/test_logical_and.py
  python/oneflow/test/modules/test_logical_or.py
Labels: automerge, enhancement, interface, op

#5711 Feat: LazyInterpret::ApplyImpl support SourceUserOpExpr and Copy
  oneflow/api/python/framework/op_expr.cpp
  oneflow/api/python/symbol/sbp_symbol.cpp
  oneflow/core/framework/op_interpreter/lazy_op_interpreter.cpp
  oneflow/core/operator/output_op.cpp
  oneflow/user/ops/image_preprocess_ops.cpp
  oneflow/user/ops/ofrecord_reader_op.cpp
  python/oneflow/nn/modules/dataset.py
  python/oneflow/test/graph/test_graph_copy.py
  python/oneflow/test/graph/test_graph_ofrecord_reader.py
Labels: automerge, feature, interface, op, system

#5713 Refactor functional sub, mul and div apis
  oneflow/api/python/functional/python_functions.cpp
  oneflow/core/functional/functional_api.yaml
  python/oneflow/nn/modules/math_ops.py
Labels: api, automerge, enhancement, refactor, system

#5720 Add env ONEFLOW_THREAD_ENABLE_LOCAL_MESSAGE_QUEUE
  oneflow/core/actor/actor.cpp
  oneflow/core/actor/actor.h
  oneflow/core/job/resource.proto
  oneflow/core/job/resource_desc.h
  oneflow/core/thread/thread.cpp
  oneflow/core/thread/thread.h
  python/oneflow/compatible/single_client/framework/config_util.py
  python/oneflow/framework/config_util.py
Labels: automerge, enhancement, system

#5727 Fea/nn graph/block proxy func
  python/oneflow/nn/graph_block.py
  python/oneflow/test/graph/test_graph.py
  python/oneflow/test/graph/test_graph_block.py
Labels: automerge, enhancement, feature, python

#5728 Add env ONEFLOW_KERNEL_DISABLE_BLOB_ACCESS_CHECKER
  oneflow/core/kernel/acc_tick_kernel.h
  oneflow/core/kernel/device_tick_kernel.h
  oneflow/core/kernel/dst_subset_tick_kernel.cpp
  oneflow/core/kernel/kernel.cpp
  oneflow/core/kernel/kernel.h
  oneflow/core/kernel/sink_tick_kernel.h
  oneflow/core/kernel/source_tick_kernel.h
  oneflow/core/kernel/src_subset_tick_kernel.cpp
  oneflow/core/kernel/tick_kernel.h
Labels: automerge, enhancement, system

#5686 beautify stack frame
  oneflow/api/python/framework/throw.h
  oneflow/core/common/error.cpp
  oneflow/core/common/error.h
  oneflow/core/common/error.proto
  oneflow/core/common/error_util.cpp
  oneflow/core/common/error_util.h
  oneflow/core/common/maybe.h
  python/oneflow/test/modules/test_generator.py
Labels: automerge, enhancement, system

#5731 Replace piece_id with comm_net_sequence_number
  oneflow/core/actor/acc_compute_actor.cpp
  oneflow/core/actor/actor.cpp
  oneflow/core/actor/actor.h
  oneflow/core/actor/actor_message.cpp
  oneflow/core/actor/actor_message.h
  oneflow/core/actor/actor_message_bus.cpp
  oneflow/core/actor/actor_message_bus.h
  oneflow/core/actor/boxing_zeros_actor.cpp
  oneflow/core/actor/case_compute_actor.cpp
  oneflow/core/actor/case_compute_actor.h
  oneflow/core/actor/collective_boxing_generic_actor.cpp
  oneflow/core/actor/copy_comm_net_actor.cpp
  oneflow/core/actor/copy_comm_net_actor.h
  oneflow/core/actor/copy_hd_actor.cpp
  oneflow/core/actor/esac_compute_actor.cpp
  oneflow/core/actor/input_wise_compute_actor.cpp
  oneflow/core/actor/naive_actor.cpp
  oneflow/core/actor/normal_forward_compute_actor.cpp
  oneflow/core/actor/normal_forward_compute_actor.h
  oneflow/core/actor/pack_compute_actor.cpp
  oneflow/core/actor/pack_compute_actor.h
  oneflow/core/actor/reentrant_lock_compute_actor.cpp
  oneflow/core/actor/repeat_compute_actor.cpp
  oneflow/core/actor/source_tick_compute_actor.cpp
  oneflow/core/actor/source_tick_compute_actor.h
  oneflow/core/actor/ssp_variable_proxy_actor.cpp
  oneflow/core/actor/tick_compute_actor.cpp
  oneflow/core/actor/tick_compute_actor.h
  oneflow/core/actor/unpack_compute_actor.cpp
  oneflow/core/actor/unpack_compute_actor.h
  oneflow/core/actor/wait_and_send_ids_compute_actor.cpp
  oneflow/core/actor/wait_and_send_ids_compute_actor.h
  oneflow/core/register/register.cpp
  oneflow/core/register/register.h
Labels: automerge, enhancement, system

#5734 Add autotest for BatchNorm2d
  python/oneflow/test/modules/test_batchnorm.py
Labels: enhancement, test

#5724 Refacotr maximum minimum py2cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/binary_functor.cpp
  oneflow/core/functional/impl/math_functor.cpp
  python/oneflow/nn/modules/math_ops.py
Labels: api, automerge, enhancement, system

#5735 rename rpc_token to TransportToken
  oneflow/api/python/framework/tensor.cpp
  oneflow/api/python/rpc/consistent_rpc_token_scope.cpp
  oneflow/api/python/rpc/rank_group.cpp
  oneflow/core/framework/op_interpreter/eager_consistent_op_interpreter.cpp
  oneflow/core/framework/op_interpreter/eager_mirrored_op_interpreter.cpp
  oneflow/core/framework/rank_group_rpc_util.cpp
  oneflow/core/framework/rank_group_rpc_util.h
  oneflow/core/framework/rpc_token.cpp
  oneflow/core/framework/rpc_token.h
  oneflow/core/framework/sync_symbol_consistent_tensor_meta.cpp
  oneflow/core/framework/sync_symbol_consistent_tensor_meta.h
  oneflow/core/framework/sync_symbol_parallel_desc.cpp
  oneflow/core/framework/sync_symbol_parallel_desc.h
  oneflow/core/framework/sync_symbol_parallel_distribution.cpp
  oneflow/core/framework/sync_symbol_parallel_distribution.h
  oneflow/core/framework/tensor.h
  oneflow/core/framework/tensor_impl.h
  oneflow/core/framework/tensor_rpc_util.cpp
  oneflow/core/framework/tensor_rpc_util.h
  oneflow/core/framework/transport_token.cpp
  oneflow/core/framework/transport_token.h
  oneflow/core/framework/transport_util.cpp
  oneflow/core/framework/transport_util.h
  oneflow/core/functional/impl/consistent_cast.cpp
  oneflow/core/thread/consistent_unique_id.cpp
  python/oneflow/__init__.py
Labels: automerge, enhancement, system

#5733 Dev fix batch norm not stats
  oneflow/core/autograd/gradient_funcs/normalization.cpp
  oneflow/core/autograd/gradient_funcs/softmax.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/core/functional/impl/nn_grad_functor.cpp
  oneflow/user/kernels/normalization_kernel.cu
  oneflow/user/ops/normalization_op.cpp
  python/oneflow/nn/modules/batchnorm.py
  python/oneflow/test/modules/test_batchnorm.py
Labels: api, automerge, enhancement, system

#5747 Remove obsolete Profiler
  oneflow/core/actor/acc_compute_actor.cpp
  oneflow/core/actor/acc_tick_compute_actor.cpp
  oneflow/core/actor/acc_tick_compute_actor.h
  oneflow/core/actor/act_event.proto
  oneflow/core/actor/act_event_logger.cpp
  oneflow/core/actor/act_event_logger.h
  oneflow/core/actor/actor.cpp
  oneflow/core/actor/actor.h
  oneflow/core/actor/actor_message.cpp
  oneflow/core/actor/actor_message.h
  oneflow/core/actor/case_compute_actor.cpp
  oneflow/core/actor/case_compute_actor.h
  oneflow/core/actor/copy_comm_net_actor.cpp
  oneflow/core/actor/copy_comm_net_actor.h
  oneflow/core/actor/input_wise_compute_actor.cpp
  oneflow/core/actor/input_wise_compute_actor.h
  oneflow/core/actor/pack_compute_actor.h
  oneflow/core/actor/reentrant_lock_compute_actor.cpp
  oneflow/core/actor/reentrant_lock_compute_actor.h
  oneflow/core/actor/ssp_variable_proxy_actor.cpp
  oneflow/core/control/control.proto
  oneflow/core/control/ctrl_client.cpp
  oneflow/core/control/ctrl_server.cpp
  oneflow/core/control/host_list_bootstrap_server.cpp
  oneflow/core/control/rank_info_bootstrap_server.cpp
  oneflow/core/control/rpc_client.cpp
  oneflow/core/control/rpc_client.h
  oneflow/core/control/rpc_server.cpp
  oneflow/core/framework/multi_client_session_context.cpp
  oneflow/core/graph/chain_act_graph.cpp
  oneflow/core/graph/chain_act_graph.h
  oneflow/core/job/improver.cpp
  oneflow/core/job/improver.h
  oneflow/core/job/job_set.proto
  oneflow/core/job/oneflow.cpp
  oneflow/core/job/profiler.cpp
  oneflow/core/job/profiler.h
  oneflow/core/job/runtime.cpp
  oneflow/core/job/session_global_objects_scope.cpp
  oneflow/core/register/register.cpp
  oneflow/core/register/register.h
  oneflow/core/rpc/include/base.h
  oneflow/core/rpc/include/grpc.h
  oneflow/core/rpc/include/local.h
  oneflow/core/rpc/lib/local.cpp
  python/oneflow/compatible/single_client/framework/config_util.py
  python/oneflow/config/__init__.py
  python/oneflow/framework/config_util.py
Labels: enhancement, automerge, system

#5742 user/summary: fix memory leak in `FillImageInSummary`
  oneflow/user/summary/event_writer_helper.cpp
Labels: automerge, bug, tooling

#5744 delete unused code
  oneflow/user/ops/avg_pooling_op.cpp
Labels: enhancement, automerge, eager, op

#5721 use default_generator.seed() as random_seed in init
  .gitignore
  python/oneflow/framework/tensor.py
  python/oneflow/test/dataloader/test_fashion_mnist_dataset.py
  python/oneflow/test/dataloader/test_lenet.py
  python/oneflow/utils/data/sampler.py
Labels: automerge, bug, python

#5726 Cpu mpi broadcast
  oneflow/core/ccl/ccl.cpp
  oneflow/core/ccl/ccl.h
  oneflow/core/common/optional.h
  oneflow/core/framework/op_interpreter/eager_mirrored_op_interpreter.cpp
  oneflow/core/framework/transport_util.cpp
  oneflow/core/framework/transport_util.h
  oneflow/core/job/rank_group.cpp
  oneflow/core/job/rank_group.h
  oneflow/core/vm/async_cpu_stream_type.h
  oneflow/user/kernels/eager_nccl_kernels.cpp
  oneflow/user/ops/eager_nccl_ops.cpp
Labels: enhancement, automerge, eager

#5760 fix argwhere 0-dim bug
  oneflow/user/kernels/arg_where_kernel.cpp
Labels: enhancement, automerge, bug, eager, op

#5704 [part6]Remove singleclient outdated api
  python/oneflow/__init__.py
  python/oneflow/experimental/__init__.py
  python/oneflow/framework/check_point_v2.py
  python/oneflow/ops/assign_op.py
  python/oneflow/ops/categorical_ordinal_encode_op.py
  python/oneflow/ops/constant_op.py
  python/oneflow/ops/get_variable.py
  python/oneflow/ops/nn_ops.py
Labels: purge, automerge, python

#5767 Quick fix Lazy nn.Graph input/output OpConf.BlobConf.is_dynamic
  oneflow/core/framework/op_interpreter/lazy_op_interpreter.cpp
Labels: automerge, bug, op, interface

#5753 fix upsample bug
  oneflow/user/kernels/upsample_kernel.h
Labels: enhancement, automerge, bug, op, interface

#5771 fix 0-dim tensor.fill_
  python/oneflow/framework/tensor.py
Labels: automerge, bug, eager, need-simple-ci

#5779 Print stack unconditionally
  .github/workflows/test.yml
  ci/test/1node_model_serve_test.sh
  ci/test/2node_op_test.sh
  ci/test/print_stack_in_all_dirs.sh
  ci/test/test_xla.sh
  python/oneflow/test/dataloader/test_cifar_dataset.py
  python/oneflow/test/dataloader/test_fashion_mnist_dataset.py
  python/oneflow/test/dataloader/test_lenet.py
Labels: enhancement, automerge, ci

#5786 change flip_code to scalar
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/dataset_functor.cpp
  oneflow/user/kernels/image_object_preprocess_kernels.cpp
  oneflow/user/ops/image_object_preprocess_ops.cpp
  python/oneflow/nn/modules/dataset.py
Labels: enhancement, automerge, eager, op

#5659 Feat empty op
  docs/source/oneflow.rst
  oneflow/api/python/framework/tensor.cpp
  oneflow/api/python/functional/indexing.cpp
  oneflow/core/common/shape.cpp
  oneflow/core/common/shape.h
  oneflow/core/common/shape_view.cpp
  oneflow/core/eager/eager_blob_object.cpp
  oneflow/core/eager/eager_blob_object.h
  oneflow/core/framework/op_interpreter/eager_mirrored_op_interpreter.cpp
  oneflow/core/framework/tensor.cpp
  oneflow/core/framework/tensor_impl.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/core/graph/exec_graph.cpp
  oneflow/user/ops/constant_op.cpp
  oneflow/user/ops/empty_op.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/graph_build_util.py
  python/oneflow/nn/modules/empty.py
  python/oneflow/nn/modules/utils.py
  python/oneflow/test/modules/test_empty.py
Labels: feature, automerge, op, need-simple-ci

#5687 Rm useless code in gather files
  oneflow/user/kernels/dim_gather_kernel_util.h
Labels: enhancement, automerge, op

#5693 add first batch of methods in oneflow.nn.functional namespace
  docs/source/functional.rst
  docs/source/index.rst
  oneflow/core/functional/functional_api.yaml
  python/oneflow/framework/docstr/__init__.py
  python/oneflow/framework/docstr/activation.py
  python/oneflow/framework/docstr/conv.py
  python/oneflow/framework/docstr/dropout.py
  python/oneflow/framework/docstr/math_ops.py
  python/oneflow/framework/docstr/pooling.py
  python/oneflow/framework/docstr/random.py
  python/oneflow/framework/docstr/vision.py
  python/oneflow/nn/functional.py
  python/oneflow/nn/functional/__init__.py
Labels: automerge, documentation, python

#5762 better repr of nn.Graph for debug
  python/oneflow/framework/tensor.py
  python/oneflow/framework/tensor_str.py
  python/oneflow/nn/graph.py
  python/oneflow/nn/graph_block.py
  python/oneflow/nn/module.py
  python/oneflow/test/dataloader/test_cifar_dataset.py
  python/oneflow/test/dataloader/test_fashion_mnist_dataset.py
  python/oneflow/test/dataloader/test_lenet.py
  python/oneflow/test/graph/test_alexnet_graph.py
Labels: feature, automerge, api, python

#5782 find more accurately which files need to be doctested
  ci/test/parallel_run.py
Labels: automerge, ci, documentation

#5790 Refactor consistent infer result
  oneflow/core/framework/consistent_tensor_infer_cache.cpp
  oneflow/core/framework/consistent_tensor_infer_cache.h
  oneflow/core/framework/op_interpreter/eager_consistent_op_interpreter.cpp
Labels: enhancement, automerge, eager

#5715 Refactor scatter, clamp and pow in cpp instead of in python
  oneflow/api/python/functional/python_functions.cpp
  oneflow/core/functional/functional_api.yaml
  python/oneflow/nn/modules/math_ops.py
  python/oneflow/nn/modules/scatter.py
Labels: enhancement, automerge, op

#5791 Remove modules not required(tan, erfc, log1p, scatter_nd)
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/array_functor.cpp
  python/oneflow/nn/modules/log1p.py
  python/oneflow/nn/modules/math_ops.py
  python/oneflow/nn/modules/scatter_nd.py
  python/oneflow/nn/modules/tan.py
Labels: enhancement, automerge, op

#5794 DECORATE
  oneflow/core/common/cached_caller.h
  oneflow/core/common/decorator.h
  oneflow/core/common/decorator_test.cpp
  oneflow/core/common/static_check.h
  oneflow/core/framework/op_interpreter/boxing/eager_boxing_interpreter_mgr.cpp
Labels: enhancement, automerge, system

#5663 Add api
  docs/source/oneflow.rst
  docs/source/tensor.rst
Labels: enhancement, automerge, bug, eager, documentation, api

#5754 Refactor: remove module not required, call function directly
  python/oneflow/nn/modules/abs.py
  python/oneflow/nn/modules/acos.py
  python/oneflow/nn/modules/acosh.py
  python/oneflow/nn/modules/argwhere.py
  python/oneflow/nn/modules/atanh.py
  python/oneflow/nn/modules/bmm.py
  python/oneflow/nn/modules/cast.py
  python/oneflow/nn/modules/chunk.py
  python/oneflow/nn/modules/concat.py
  python/oneflow/nn/modules/constant.py
  python/oneflow/nn/modules/diag.py
  python/oneflow/nn/modules/eq.py
  python/oneflow/nn/modules/exp.py
  python/oneflow/nn/modules/expand.py
  python/oneflow/nn/modules/eye.py
  python/oneflow/nn/modules/flip.py
  python/oneflow/nn/modules/floor.py
  python/oneflow/nn/modules/gather.py
  python/oneflow/nn/modules/gather_nd.py
  python/oneflow/nn/modules/greater.py
  python/oneflow/nn/modules/greater_equal.py
  python/oneflow/nn/modules/less.py
  python/oneflow/nn/modules/less_equal.py
  python/oneflow/nn/modules/masked_fill.py
  python/oneflow/nn/modules/masked_select.py
  python/oneflow/nn/modules/math_ops.py
  python/oneflow/nn/modules/matmul.py
  python/oneflow/nn/modules/ne.py
  python/oneflow/nn/modules/negative.py
  python/oneflow/nn/modules/permute.py
  python/oneflow/nn/modules/reduce_ops.py
  python/oneflow/nn/modules/repeat.py
  python/oneflow/nn/modules/reshape.py
  python/oneflow/nn/modules/round.py
  python/oneflow/nn/modules/sign.py
  python/oneflow/nn/modules/sinh.py
  python/oneflow/nn/modules/slice.py
  python/oneflow/nn/modules/squeeze.py
  python/oneflow/nn/modules/stack.py
  python/oneflow/nn/modules/tensor_ops.py
  python/oneflow/nn/modules/tile.py
  python/oneflow/nn/modules/transpose.py
  python/oneflow/nn/modules/triu.py
  python/oneflow/nn/modules/unsqueeze.py
  python/oneflow/nn/modules/where.py
Labels: enhancement, automerge, op

#5690 Add fake quantize op
  docs/source/nn.rst
  oneflow/core/autograd/gradient_funcs/fake_quantization.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/quantization.cpp
  oneflow/user/kernels/min_max_observer_kernel.cpp
  oneflow/user/kernels/min_max_observer_kernel.cu
  oneflow/user/kernels/quantization_kernel.cpp
  oneflow/user/kernels/quantization_kernel.cu
  oneflow/user/ops/quantization_op.cpp
  python/oneflow/nn/__init__.py
  python/oneflow/nn/modules/fake_quantization.py
  python/oneflow/nn/modules/min_max_observer.py
  python/oneflow/nn/modules/moving_average_min_max_observer.py
  python/oneflow/nn/modules/quantization.py
  python/oneflow/quantization.py
  python/oneflow/test/modules/test_fake_quantization.py
  python/oneflow/test/modules/test_min_max_observer.py
  python/oneflow/test/modules/test_moving_average_min_max_observer.py
  python/oneflow/test/modules/test_quantization.py
Labels: enhancement, feature, automerge, eager, api

#5750 [part8]Remove singleclient outdated api
  docs/source/oneflow.rst
  python/oneflow/__init__.py
  python/oneflow/advanced/distribute_ops.py
  python/oneflow/deprecated/initializer_util.py
  python/oneflow/experimental/__init__.py
  python/oneflow/experimental/namescope.py
  python/oneflow/framework/check_point_v2.py
  python/oneflow/framework/session_util.py
Labels: purge, automerge, python

#5798 restore test of alexnet graph
  python/oneflow/test/graph/test_alexnet_graph.py
Labels: automerge, bug, test

#5795 Fix throw abort
  oneflow/api/python/framework/throw.h
Labels: enhancement, automerge, system

#5752 [part9]Remove singleclient outdated api
  python/oneflow/__init__.py
  python/oneflow/env.py
  python/oneflow/framework/check_point_v2.py
  python/oneflow/framework/env_util.py
  python/oneflow/framework/function_desc.py
  python/oneflow/framework/model.py
Labels: purge, automerge, python

#5743 Fix bug in scatter
  oneflow/user/kernels/dim_scatter_kernel_util.h
  oneflow/user/kernels/dim_scatter_kernels.cpp
  oneflow/user/kernels/dim_scatter_scalar_kernel_util.h
  oneflow/user/kernels/dim_scatter_scalar_kernels.cpp
Labels: automerge, bug, op

#5755 fix weight decay in RMSprop
  python/oneflow/nn/optimizer/rmsprop.py
  python/oneflow/test/modules/test_optim_rmsprop.py
Labels: automerge, bug, python

#5495 Collective boxing executor add_plan delete_plan
  oneflow/core/framework/multi_client_session_context.cpp
  oneflow/core/job/collective_boxing_executor.cpp
  oneflow/core/job/collective_boxing_executor.h
  oneflow/core/job/runtime.cpp
  oneflow/core/job/runtime.h
  oneflow/core/job/session_global_objects_scope.cpp
Labels: enhancement, automerge, system

#5764 Refactor hierarchical parallel cast autograd
  oneflow/core/autograd/gradient_funcs/hierarchical_parallel_cast.cpp
Labels: enhancement, automerge, system

#5802 fix third party mirror check_sum
  tools/package_mirror.py
Labels: enhancement, automerge, ci

#5805 delete interpolate int type
  oneflow/user/kernels/upsample_bicubic2d_kernel.cpp
  oneflow/user/kernels/upsample_bicubic2d_kernel.cu
  oneflow/user/kernels/upsample_bilinear_2d_kernel.cpp
  oneflow/user/kernels/upsample_bilinear_2d_kernel.cu
  oneflow/user/kernels/upsample_kernel.h
  oneflow/user/kernels/upsample_linear_1d_kernel.cpp
  oneflow/user/kernels/upsample_linear_1d_kernel.cu
  oneflow/user/kernels/upsample_nearest_kernel.cpp
  oneflow/user/kernels/upsample_nearest_kernel.cu
  oneflow/user/kernels/upsample_trilinear_3d_kernel.cpp
  oneflow/user/kernels/upsample_trilinear_3d_kernel.cu
Labels: automerge, bug, eager, op

#5736 add flow.randn
  docs/source/oneflow.rst
  oneflow/core/framework/op_interpreter.h
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/random_functor.cpp
  oneflow/user/kernels/distributions/normal_distribution.cpp
  oneflow/user/kernels/distributions/normal_distribution.cu
  oneflow/user/kernels/distributions/normal_distribution.h
  oneflow/user/kernels/distributions/normal_kernel.cpp
  oneflow/user/kernels/distributions/normal_kernel.h
  oneflow/user/ops/distributions/normal_op.cpp
  python/oneflow/__init__.py
  python/oneflow/nn/modules/random_ops.py
  python/oneflow/test/modules/test_randn.py
Labels: feature, automerge, system

#5756 [part10]Remove singleclient outdated api
  python/oneflow/__init__.py
  python/oneflow/framework/input_blob_def.py
  python/oneflow/framework/job_set_util.py
  python/oneflow/framework/ops.py
  python/oneflow/framework/placement_util.py
  python/oneflow/framework/session_util.py
Labels: purge, automerge, python

#5761 enhance_local_to_consistent
  oneflow/core/framework/device.cpp
  oneflow/core/functional/impl/consistent_cast.cpp
  python/oneflow/test/modules/test_consistent_cast.py
Labels: enhancement, automerge, system

#5801 set created generator with default rng seed
  oneflow/core/framework/random_generator.cpp
  oneflow/core/framework/random_generator.h
  python/oneflow/test/modules/test_generator.py
Labels: enhancement, automerge, system

#5806 Fix naive b2p error
  oneflow/core/framework/op_interpreter/boxing/naive_b2p_boxing_interpreter.cpp
Labels: automerge, bug, system

#5809 dev-nonzero
  docs/source/oneflow.rst
  docs/source/tensor.rst
  python/oneflow/__init__.py
  python/oneflow/nn/modules/nonzero.py
  python/oneflow/test/modules/test_nonzero.py
  python/oneflow/test/tensor/test_tensor.py
Labels: enhancement, automerge, eager, documentation, api

#5810 fix distributed run on built dir
  ci/test/distributed_run.py
Labels: enhancement, automerge, ci

#5811 bn tol 1e-4 => 1e-3
  python/oneflow/compatible/single_client/test/xrt/test_layer_norm.py
  python/oneflow/test/modules/test_normalization.py
Labels: enhancement, automerge, ci

#5658 Multi-nn.Graph memory reuse by Chunk manager
  oneflow/core/framework/multi_client_session_context.cpp
  oneflow/core/job/plan_util.cpp
  oneflow/core/job/session_global_objects_scope.cpp
  oneflow/core/memory/chunk_manager.cpp
  oneflow/core/memory/chunk_manager.h
  oneflow/core/register/register_manager.cpp
  python/oneflow/nn/graph_block.py
Labels: feature, automerge, system, interface

#5717 Get parallel_id and parallel_num through rank and world size in DDP
  oneflow/core/job/parallel_desc.cpp
  oneflow/core/job/parallel_desc.h
  oneflow/user/data/coco_data_reader.cpp
  oneflow/user/data/ofrecord_dataset.h
  oneflow/user/kernels/gpt_data_loader_kernel.cpp
  oneflow/user/kernels/stateful_local_opkernel.cpp
  oneflow/user/ops/coco_reader_op.cpp
  python/oneflow/framework/tensor.py
  python/oneflow/nn/__init__.py
  python/oneflow/nn/graph.py
  python/oneflow/nn/graph_block.py
  python/oneflow/nn/modules/dataset.py
  python/oneflow/test/modules/test_coco_reader.py
  python/oneflow/test/modules/test_gpt_data_loader.py
  python/oneflow/test/modules/test_ofrecord_reader.py
Labels: enhancement, automerge, op

#5770 fix launcher description
  python/oneflow/distributed/launch.py
Labels: automerge, documentation, system

#5812 Feat consistent tensor python constructor
  oneflow/api/python/common.cpp
  oneflow/api/python/framework/tensor.cpp
  oneflow/core/framework/device.h
  python/oneflow/test/modules/test_generator.py
  python/oneflow/test/tensor/test_tensor.py
Labels: feature, automerge, system

#5816 Fix argwhere bug
  python/oneflow/nn/modules/argwhere.py
Labels: automerge, bug, eager, api, interface

#5820 unpack_call: impl new `unpack_call_dispatcher` for better performance
  oneflow/api/python/functional/unpack_call.h
Labels: enhancement, automerge, system, api

#5751 Fix all warnings & Add option TREAT_WARING_AS_ERROR to cmake
  .github/workflows/test.yml
  CMakeLists.txt
  cmake/oneflow.cmake
  oneflow/core/autograd/gradient_funcs/adaptive_pool.cpp
  oneflow/core/autograd/gradient_funcs/avg_pooling.cpp
  oneflow/core/autograd/gradient_funcs/broadcast_binary_ops.cpp
  oneflow/core/autograd/gradient_funcs/pool.cpp
  oneflow/core/autograd/gradient_funcs/pooling.cpp
  oneflow/core/common/cached_object_msg_allocator.h
  oneflow/core/common/maybe.h
  oneflow/core/common/symbol.h
  oneflow/core/eager/opkernel_instruction_type.h
  oneflow/core/eager/opkernel_object.h
  oneflow/core/framework/config_def.cpp
  oneflow/core/framework/device.h
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/framework/op_expr.h
  oneflow/core/framework/tensor_rpc_util.h
  oneflow/core/framework/user_op_conf.cpp
  oneflow/core/framework/vm_local_dep_object.cpp
  oneflow/core/functional/packed_functor.h
  oneflow/core/job/job_build_and_infer_ctx_mgr.cpp
  oneflow/core/job/job_build_and_infer_ctx_mgr.h
  oneflow/core/job/session_global_objects_scope.cpp
  oneflow/core/job_rewriter/autotick.h
  oneflow/core/job_rewriter/job_pass.h
  oneflow/core/kernel/slice_boxing_kernel.cpp
  oneflow/core/kernel/util/arithemetic_interface.h
  oneflow/core/ndarray/binary_func.h
  oneflow/core/object_msg/object_msg_core.h
  oneflow/core/object_msg/object_msg_list.h
  oneflow/core/operator/broadcast_to_compatible_with_op.cpp
  oneflow/core/operator/constant_like_op.cpp
  oneflow/core/operator/copy_hd_op.cpp
  oneflow/core/operator/dynamic_reshape_op.cpp
  oneflow/core/operator/learning_rate_schedule_op.cpp
  oneflow/core/operator/model_init_op.cpp
  oneflow/core/operator/model_load_op.cpp
  oneflow/core/profiler/kernel.h
  oneflow/core/register/pod_desc.cpp
  oneflow/core/vm/control_stream_type.h
  oneflow/core/vm/host_stream_type.h
  oneflow/core/vm/infer_stream_type.h
  oneflow/core/vm/instr_type_id.h
  oneflow/core/vm/instruction.msg.h
  oneflow/core/vm/instruction_type.h
  oneflow/core/vm/phy_instr_operand.h
  oneflow/core/vm/stream.msg.h
  oneflow/core/vm/stream_runtime_desc.msg.h
  oneflow/core/vm/stream_type.h
  oneflow/core/vm/stream_type_id.h
  oneflow/core/vm/test_util.h
  oneflow/core/vm/virtual_machine.cpp
  oneflow/core/vm/virtual_machine.msg.h
  oneflow/core/vm/vm_object.msg.h
  oneflow/core/vm/vm_util.h
  oneflow/user/kernels/deconv_cpu_kernel.cpp
  oneflow/user/kernels/pool_cpu_kernel.cpp
  oneflow/user/kernels/pooling_kernel.cpp
Labels: enhancement, automerge, build, need-simple-ci

#5803 graph/block io check
  python/oneflow/framework/graph_build_util.py
  python/oneflow/framework/tensor.py
  python/oneflow/nn/graph.py
  python/oneflow/nn/graph_block.py
  python/oneflow/nn/util.py
  python/oneflow/test/graph/ofrecord_data_utils.py
  python/oneflow/test/graph/test_alexnet_graph.py
  python/oneflow/test/graph/test_graph_check.py
Labels: enhancement, feature, automerge, python

#5808 fix squeeze
  python/oneflow/nn/modules/squeeze.py
Labels: automerge, bug, eager, op

#5818 fix pooling ceil_mode bug
  oneflow/user/kernels/avg_pooling_kernel_util.cpp
  oneflow/user/kernels/pooling_kernel_util.cpp
  python/oneflow/test/modules/test_pooling.py
Labels: automerge, bug, eager, need-simple-ci

#5653 fix bug in AddInputOutputOpsPass: check existence of key in HashMap(inferface_lbi2scope_sym_id)
  oneflow/core/job_rewriter/add_input_output_ops_pass.cpp
Labels: enhancement, automerge, system, serving

#5694 Dev logical_xor module
  docs/source/oneflow.rst
  docs/source/tensor.rst
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/binary_functor.cpp
  oneflow/core/ndarray/binary_func.h
  oneflow/user/ops/math_binary_broadcast_seq.h
  python/oneflow/__init__.py
  python/oneflow/nn/modules/logical_xor.py
  python/oneflow/test/modules/test_logical_xor.py
Labels: enhancement, automerge, op, interface

#5821 remove scale arg in optimizer
  python/oneflow/nn/optimizer/adamw.py
  python/oneflow/nn/optimizer/rmsprop.py
  python/oneflow/nn/optimizer/sgd.py
  python/oneflow/test/graph/test_graph_optimizer.py
  python/oneflow/test/modules/test_optim_adamw.py
  python/oneflow/test/modules/test_optim_rmsprop.py
Labels: enhancement, purge, automerge, eager, python

#5828 Remove move in conv_cudnn
  oneflow/user/kernels/conv_cudnn_kernels.cpp
Labels: enhancement, automerge, op

#5745 dev adamw graph config
  python/oneflow/nn/optimizer/adamw.py
  python/oneflow/test/graph/test_graph_adamw_optim.py
Labels: enhancement, automerge, test

#5823 RTH_update_op_test
  python/oneflow/test/modules/test_eq.py
  python/oneflow/test/modules/test_erf.py
  python/oneflow/test/modules/test_erfc.py
  python/oneflow/test/modules/test_exp.py
  python/oneflow/test/modules/test_expand.py
  python/oneflow/test/modules/test_round.py
  python/oneflow/test/tensor/test_tensor.py
Labels: enhancement, automerge, test

#5840 Use gcc 7 in release to prevent error
  .github/workflows/release.yml
  .github/workflows/test.yml
  docker/package/manylinux/build_wheel.py
Labels: enhancement, automerge, ci

#5841 use clang tidy appimage in ci
  .github/workflows/simple.yml
Labels: enhancement, automerge, ci, need-simple-ci

#5842 set CMAKE_BUILD_TYPE to Release if undefined
  CMakeLists.txt
Labels: automerge, bug, build

#5777 Support Free EagerTensor caught in nn.Graph build
  oneflow/api/python/framework/tensor.cpp
  oneflow/api/python/job_build/lazy_mode.cpp
  oneflow/core/framework/multi_client_session_context.cpp
  oneflow/core/framework/multi_client_session_context.h
  oneflow/core/framework/nn_graph.cpp
  oneflow/core/framework/nn_graph.h
  oneflow/core/framework/op_interpreter/lazy_op_interpreter.cpp
  oneflow/core/job/job_build_and_infer_ctx.cpp
  oneflow/core/job/lazy_mode.h
  python/oneflow/framework/graph_build_util.py
  python/oneflow/test/graph/test_graph.py
  python/oneflow/test/graph/test_graph_free_eager_tensor.py
  python/oneflow/test/graph/test_input_op_expr.py
  python/oneflow/test/graph/test_output_op_expr.py
  python/oneflow/test/graph/test_user_op_expr.py
  python/oneflow/test/graph/test_variable_op_expr.py
Labels: feature, automerge, system, interface

#5768 Dev RMSprop graph conf
  python/oneflow/nn/optimizer/rmsprop.py
  python/oneflow/nn/optimizer/sgd.py
  python/oneflow/test/graph/test_graph_rmsprop_optim.py
Labels: enhancement, feature, automerge, python

#5834 Fix ddp grad size
  python/oneflow/nn/parallel/ddp.py
  python/oneflow/test/modules/test_ddp.py
Labels: automerge, bug, python

#5838 cmake: disable array-bounds check & treat warnings as errors for pyextobj and oneflow_internal & fix warnings
  cmake/oneflow.cmake
  oneflow/api/python/functional/python_arg.h
  oneflow/core/framework/eager_blob_util.h
  oneflow/user/ops/batch_gather_op.cpp
Labels: enhancement, automerge, build

#5850 Align where op with torch
  python/oneflow/nn/modules/where.py
  python/oneflow/test/modules/test_where.py
Labels: feature, automerge, bug, eager, api

#5851 fix nvjpeg hw acc
  oneflow/core/kernel/image_decoder_random_crop_resize_kernel.cpp
Labels: automerge, bug, op

#5853 Fix placement print bug
  oneflow/api/python/symbol/placement_symbol.cpp
  oneflow/core/rpc/include/global_process_ctx.h
  oneflow/core/rpc/lib/global_process_ctx.cpp
Labels: automerge, bug, system

#5661 add index_select op
  docs/source/oneflow.rst
  docs/source/tensor.rst
  python/oneflow/__init__.py
  python/oneflow/nn/modules/index_select.py
  python/oneflow/test/modules/test_index_select.py
Labels: enhancement, automerge, op, interface

#5714 Dev split
  docs/source/oneflow.rst
  docs/source/tensor.rst
  oneflow/core/autograd/gradient_funcs/narrow.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/user/kernels/narrow_kernel.cpp
  oneflow/user/kernels/narrow_util.cpp
  oneflow/user/kernels/narrow_util.cu
  oneflow/user/kernels/narrow_util.h
  oneflow/user/ops/narrow_op.cpp
  python/oneflow/__init__.py
  python/oneflow/nn/modules/narrow.py
  python/oneflow/nn/modules/split.py
  python/oneflow/test/modules/test_narrow.py
  python/oneflow/test/modules/test_split.py
Labels: enhancement, automerge, eager, op

#5804 align reshape input param with pytorch
  python/oneflow/nn/modules/batchnorm.py
  python/oneflow/nn/modules/instancenorm.py
  python/oneflow/nn/modules/loss.py
  python/oneflow/nn/modules/meshgrid.py
  python/oneflow/nn/modules/norm.py
  python/oneflow/nn/modules/normalization.py
  python/oneflow/nn/modules/pixelshuffle.py
  python/oneflow/nn/modules/reshape.py
  python/oneflow/test/dataloader/test_fashion_mnist_dataset.py
  python/oneflow/test/tensor/test_tensor.py
  python/oneflow/utils/vision/datasets/mnist.py
  python/oneflow/utils/vision/transforms/functional.py
Labels: automerge, bug, eager, api, interface

#5819 add_eager_boxing_and_op_interpreter_dispatch_error_info
  oneflow/core/framework/op_interpreter/boxing/eager_boxing_interpreter_mgr.cpp
  oneflow/core/framework/op_interpreter/op_interpreter_util.cpp
  oneflow/core/job/sbp_parallel.cpp
  oneflow/core/job/sbp_parallel.h
Labels: enhancement, automerge, system

#5835 make setitem device match
  python/oneflow/framework/tensor.py
Labels: enhancement, automerge, bug, eager

#5796 Decorator 4 disable recursive boxing call
  oneflow/api/python/framework/tensor.cpp
  oneflow/core/ccl/ccl.cpp
  oneflow/core/ccl/ccl.h
  oneflow/core/common/container_util.h
  oneflow/core/common/device_type.h
  oneflow/core/common/flat_shape.cpp
  oneflow/core/common/flat_shape.h
  oneflow/core/common/maybe.h
  oneflow/core/framework/op_interpreter/boxing/collective_boxing_interpreter.cpp
  oneflow/core/framework/op_interpreter/boxing/eager_boxing_interpreter_mgr.cpp
  oneflow/core/framework/op_interpreter/boxing/eager_boxing_interpreter_mgr.h
  oneflow/core/framework/op_interpreter/boxing/identity_boxing_interpreter.cpp
  oneflow/core/framework/op_interpreter/boxing/naive_s2p_boxing_interpreter.cpp
  oneflow/core/framework/op_interpreter/eager_consistent_op_interpreter.cpp
  oneflow/core/framework/op_interpreter/eager_mirrored_op_interpreter.cpp
  oneflow/core/framework/placement_sbp_util.cpp
  oneflow/core/framework/placement_sbp_util.h
  oneflow/core/framework/tensor_consistent_id.cpp
  oneflow/core/framework/tensor_consistent_id.h
  oneflow/core/framework/tensor_impl.h
  oneflow/core/framework/tensor_rpc_util.cpp
  oneflow/core/framework/tensor_rpc_util.h
  oneflow/core/framework/transport_token.cpp
  oneflow/core/framework/transport_token.h
  oneflow/core/framework/transport_util.cpp
  oneflow/core/framework/transport_util.h
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/consistent_cast.cpp
  oneflow/core/job/parallel_desc.cpp
  oneflow/core/job/parallel_desc.h
  oneflow/core/job/parallel_desc_test.cpp
  oneflow/core/job/rank_group.cpp
  oneflow/core/job/rank_group.h
  oneflow/core/rpc/include/global_process_ctx.h
  oneflow/core/rpc/lib/global_process_ctx.cpp
  oneflow/user/kernels/stateful_local_opkernel.cpp
  python/oneflow/nn/modules/consistent_cast.py
  python/oneflow/test/modules/test_check_meta_consistency.py
  python/oneflow/test/modules/test_consistent_cast.py
Labels: enhancement, automerge, system

#5746 Lcy logsoftmax
  oneflow/core/autograd/gradient_funcs/logsoftmax.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/activation_functor.cpp
  oneflow/user/kernels/logsoftmax_kernel.cpp
  oneflow/user/kernels/logsoftmax_kernel.cu
  oneflow/user/kernels/logsoftmax_kernel_util.cpp
  oneflow/user/kernels/logsoftmax_kernel_util.cu
  oneflow/user/kernels/logsoftmax_kernel_util.h
  oneflow/user/ops/logsoftmax_op.cpp
  python/oneflow/nn/modules/activation.py
Labels: enhancement, automerge, op

#5839 Optimize maybe.
  oneflow/core/common/either_ptr.h
  oneflow/core/common/maybe.h
  oneflow/core/common/shared_or_scalar.h
Labels: enhancement, automerge, system

#5859 add l2_normalize for mutl-client interfaces
  docs/source/functional.rst
  oneflow/core/autograd/gradient_funcs/l2_normalize.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  python/oneflow/compatible/single_client/ops/math_ops.py
  python/oneflow/nn/functional/__init__.py
  python/oneflow/nn/modules/norm.py
  python/oneflow/test/modules/test_l2_normalize.py
Labels: enhancement, automerge, op

#5863 Skip ci jobs by git diff
  .github/workflows/test.yml
  python/oneflow/framework/sysconfig.py
  python/oneflow/sysconfig.py
Labels: enhancement, automerge, ci

#5872 Fix compile warning (strict-aliasing)
  oneflow/core/common/either_ptr.h
Labels: automerge, bug, build

#5860 wait vm empty before exiting
  oneflow/core/vm/oneflow_vm.cpp
  oneflow/core/vm/virtual_machine.cpp
Labels: enhancement, automerge, system

#5848 Fix optimizer list parameters input bug
  python/oneflow/nn/optimizer/adam.py
  python/oneflow/nn/optimizer/adamw.py
  python/oneflow/nn/optimizer/optimizer.py
  python/oneflow/nn/optimizer/rmsprop.py
  python/oneflow/nn/optimizer/sgd.py
Labels: enhancement, automerge, eager

#5784 Broadcast consistent shape and dtype
  oneflow/core/job/parallel_desc_test.cpp
  oneflow/core/rpc/lib/global_process_ctx.cpp
  python/oneflow/test/modules/test_consistent_cast.py
Labels: enhancement, automerge, eager

#5774 Lazy to_consistent
  oneflow/api/python/framework/tensor.cpp
  oneflow/api/python/functional/indexing.cpp
  oneflow/core/framework/op_expr.cpp
  oneflow/core/framework/op_expr.h
  oneflow/core/framework/op_interpreter.h
  oneflow/core/framework/op_interpreter/eager_mirrored_op_interpreter.cpp
  oneflow/core/framework/op_interpreter/lazy_op_interpreter.cpp
  oneflow/core/framework/op_interpreter/op_interpreter.cpp
  oneflow/core/framework/sbp_context.cpp
  oneflow/core/framework/sbp_context.h
  oneflow/core/framework/tensor.h
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/consistent_cast.cpp
  oneflow/user/ops/coco_reader_op.cpp
  oneflow/user/ops/constant_op.cpp
  oneflow/user/ops/copy_op.cpp
  oneflow/user/ops/empty_op.cpp
  oneflow/user/ops/gpt_data_loader_op.cpp
  oneflow/user/ops/ofrecord_reader_op.cpp
  oneflow/user/ops/pooling_op.cpp
  python/oneflow/nn/module.py
  python/oneflow/nn/modules/batchnorm.py
  python/oneflow/nn/modules/consistent_cast.py
  python/oneflow/nn/modules/conv.py
  python/oneflow/nn/modules/linear.py
  python/oneflow/nn/modules/to.py
  python/oneflow/test/graph/test_to_consistent.py
Labels: feature, automerge, system, interface

#5783 Tensor str
  oneflow/api/python/framework/tensor.cpp
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/core/functional/tensor_index.cpp
  python/oneflow/compatible/single_client/nn/modules/activation.py
  python/oneflow/framework/docstr/activation.py
  python/oneflow/framework/docstr/pooling.py
  python/oneflow/framework/tensor.py
  python/oneflow/framework/tensor_str.py
  python/oneflow/nn/modules/acosh.py
  python/oneflow/nn/modules/activation.py
  python/oneflow/nn/modules/dropout.py
  python/oneflow/nn/modules/interpolate.py
  python/oneflow/nn/modules/loss.py
  python/oneflow/nn/modules/math_ops.py
  python/oneflow/nn/modules/negative.py
  python/oneflow/nn/modules/norm.py
  python/oneflow/nn/modules/padding.py
  python/oneflow/nn/modules/reduce_ops.py
  python/oneflow/nn/modules/scatter_nd.py
  python/oneflow/nn/modules/upsampling.py
  python/oneflow/nn/modules/where.py
  python/oneflow/nn/utils/clip_grad.py
  python/oneflow/test/modules/test_tensor_str.py
Labels: enhancement, automerge, system

#5836 Feat tensor to bool
  docs/source/oneflow.rst
  python/oneflow/__init__.py
  python/oneflow/framework/tensor.py
  python/oneflow/nn/modules/batchnorm.py
  python/oneflow/nn/modules/conv.py
  python/oneflow/nn/modules/instancenorm.py
  python/oneflow/nn/modules/loss.py
  python/oneflow/nn/modules/normalization.py
  python/oneflow/test/modules/test_clip_grad.py
  python/oneflow/test/tensor/test_tensor.py
Labels: feature, automerge, eager

#5858 enable CMake first class cuda support
  .github/workflows/test.yml
  CMakeLists.txt
  cmake/caches/cn/fast/cuda-61.cmake
  cmake/caches/cn/fast/cuda-75.cmake
  cmake/oneflow.cmake
  cmake/third_party.cmake
  docker/package/manylinux/build_wheel.py
  python/oneflow/test/modules/test_instancenorm.py
  tools/flags_from_git_diff.py
Labels: enhancement, automerge, build

#5880 Lazy Interpret support infer default device cpu
  oneflow/core/framework/op_interpreter/lazy_op_interpreter.cpp
  python/oneflow/test/graph/test_graph_arange.py
Labels: feature, automerge, system

#5881 Bugfix async callback
  oneflow/api/foreign_lock_helper.h
  oneflow/api/python/framework/tensor.cpp
  oneflow/api/python/gil_foreign_lock_helper.cpp
  oneflow/api/python/ofblob/ofblob.e.h
  oneflow/core/common/spin_counter.cpp
  oneflow/core/common/spin_counter.h
  oneflow/core/eager/init_symbol_instruction_type_test.cpp
  oneflow/core/eager/lazy_job_instruction_type_test.cpp
  oneflow/core/eager/opkernel_instruction_type_test.cpp
  oneflow/core/eager/transport_blob_instruction_type_test.cpp
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/framework/instructions_builder.h
  oneflow/core/framework/tensor_impl.cpp
  oneflow/core/framework/transport_util.cpp
  oneflow/core/vm/control_stream_type_test.cpp
  oneflow/core/vm/nop_stream_type_test.cpp
  oneflow/core/vm/object_instruction_type_test.cpp
  oneflow/core/vm/oneflow_vm.cpp
  oneflow/core/vm/sequential_instruction_type_test.cpp
  oneflow/core/vm/string_instruction_type_test.cpp
  oneflow/core/vm/virtual_machine.cpp
  oneflow/core/vm/virtual_machine.msg.h
  oneflow/core/vm/vm_util.cpp
Labels: enhancement, automerge, eager

#5886 disable TREAT_WARNINGS_AS_ERRORS in Release CI
  .github/workflows/release.yml
Labels: enhancement, automerge, ci

#5884 Ignore opencv-python on machine aarch64
  dev-requirements.txt
Labels: enhancement, automerge, build

#5890 fix typo in `raise RuntimeError`
  python/oneflow/framework/tensor_str.py
Labels: automerge, bug, system

#5891 Fix BUG of LazyInterpret FreeEagerTensor memory shared with regst
  oneflow/core/framework/op_interpreter/lazy_op_interpreter.cpp
  python/oneflow/test/graph/test_graph_free_eager_tensor.py
Labels: automerge, bug, system

#5778 Dev scalar op
  oneflow/api/python/functional/python_functions.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/user/kernels/scalar_logical_kernels.cpp
  oneflow/user/kernels/scalar_logical_kernels.cu
  oneflow/user/kernels/scalar_logical_kernels.h
  oneflow/user/ops/scalar_logical_op.cpp
  python/oneflow/framework/tensor.py
  python/oneflow/nn/modules/dataset.py
  python/oneflow/nn/modules/eq.py
  python/oneflow/nn/modules/greater.py
  python/oneflow/nn/modules/greater_equal.py
  python/oneflow/nn/modules/less.py
  python/oneflow/nn/modules/less_equal.py
  python/oneflow/nn/modules/ne.py
  python/oneflow/nn/modules/where.py
  python/oneflow/nn/parallel/ddp.py
  python/oneflow/test/graph/test_graph_free_eager_tensor.py
  python/oneflow/test/modules/test_module.py
  python/oneflow/test/modules/test_randn.py
  python/oneflow/test/tensor/test_tensor.py
Labels: enhancement, automerge, op

#5893 The scheduler thread joins worker threads
  oneflow/core/vm/oneflow_vm.cpp
  oneflow/core/vm/oneflow_vm.h
Labels: enhancement, automerge, eager

#5888 fix gather kernel 0 shape
  oneflow/user/kernels/gather_kernel.cpp
  python/oneflow/test/modules/test_module.py
Labels: automerge, bug, eager, op

#5879 cmake: include third party headers as system headers to avoid warnings
  cmake/cfg.cmake
  cmake/oneflow.cmake
  cmake/third_party.cmake
  oneflow/core/kernel/gather_kernel_util.cpp
Labels: enhancement, automerge, build

#5897 Add cmake option USE_SYSTEM_NCCL
  cmake/third_party/nccl.cmake
Labels: enhancement, automerge, build

#5903 Lazy interpreter for new ConsistentToConsistentOpExpr
  oneflow/core/framework/op_interpreter/lazy_op_interpreter.cpp
Labels: enhancement, system

#5883 Dev consistent arange
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/user/ops/distributions/normal_op.cpp
  oneflow/user/ops/distributions/uniform_op.cpp
  oneflow/user/ops/range_op.cpp
  python/oneflow/nn/modules/arange.py
  python/oneflow/test/modules/test_arange.py
Labels: enhancement, automerge, system, api, refactor

#5315 functional_one_hot
  docs/source/functional.rst
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  python/oneflow/framework/docstr/__init__.py
  python/oneflow/framework/docstr/onehot.py
  python/oneflow/nn/__init__.py
  python/oneflow/nn/functional/__init__.py
  python/oneflow/nn/modules/one_hot.py
  python/oneflow/test/modules/test_one_hot.py
Labels: enhancement, automerge, op, api, interface

#5807 fix docstring in oneflow.nn.functional namespace
  python/oneflow/framework/docstr/activation.py
  python/oneflow/framework/docstr/conv.py
  python/oneflow/framework/docstr/pooling.py
  python/oneflow/framework/docstr/vision.py
Labels: automerge, ci, documentation

#5830 Support combined_margin_loss op in flow.nn.modules
  docs/source/nn.rst
  oneflow/core/autograd/gradient_funcs/combined_margin_loss.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/core/functional/impl/nn_grad_functor.cpp
  oneflow/user/kernels/combined_margin_loss_kernel.cpp
  oneflow/user/kernels/combined_margin_loss_kernel.cu
  python/oneflow/nn/__init__.py
  python/oneflow/nn/modules/loss.py
  python/oneflow/test/modules/test_combined_margin_loss.py
Labels: enhancement, automerge, op

#5854 Move the judgment content to c++， And add scalar fmod
  oneflow/api/python/functional/python_functions.cpp
  oneflow/core/autograd/gradient_funcs/scalar_fmod.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/user/kernels/scalar_fmod_kernel.cpp
  oneflow/user/kernels/scalar_fmod_kernel.cu
  oneflow/user/kernels/scalar_fmod_kernel.h
  oneflow/user/ops/scalar_fmod_op.cpp
  python/oneflow/nn/modules/math_ops.py
Labels: enhancement, automerge, op

#5899 Add autotest
  oneflow/user/ops/prelu_op.cpp
  python/oneflow/nn/modules/activation.py
  python/oneflow/nn/modules/meshgrid.py
  python/oneflow/test/modules/test_abs.py
  python/oneflow/test/modules/test_activation.py
  python/oneflow/test/modules/test_batchnorm.py
  python/oneflow/test/modules/test_ceil.py
  python/oneflow/test/modules/test_meshgrid.py
  python/oneflow/test/modules/test_pow.py
  python/oneflow/test/modules/test_stack.py
Labels: enhancement, automerge, bug, eager, interface

#5906 Try to fix the problem that the insightface cannot converge。
  oneflow/user/kernels/prelu_kernel.cpp
  oneflow/user/kernels/prelu_kernel.cu
  python/oneflow/test/modules/test_prelu.py
Labels: enhancement, automerge, bug, eager, interface

#5907 Sync access and assign indexing tensor.
  oneflow/api/python/functional/indexing.cpp
  oneflow/api/python/symbol/sbp_symbol.cpp
  oneflow/core/framework/op_interpreter/boxing/eager_boxing_interpreter_mgr.cpp
  oneflow/core/functional/tensor_index.cpp
  oneflow/core/job/sbp_parallel.cpp
  oneflow/core/job/sbp_parallel.h
Labels: enhancement, automerge, bug, system

#5909 fix bug of SyncOnMasterFn atexit
  python/oneflow/__init__.py
Labels: automerge, bug, python

#5911 Restruct sort and argsort op
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/array_functor.cpp
  python/oneflow/nn/modules/argsort.py
  python/oneflow/nn/modules/sort.py
  python/oneflow/test/modules/test_argsort.py
  python/oneflow/test/modules/test_l1loss.py
  python/oneflow/test/modules/test_sort.py
  python/oneflow/test/tensor/test_tensor.py
Labels: enhancement, automerge, bug, eager, documentation, interface

#5641 Use symbol dtype
  oneflow/api/python/deprecated.cpp
  oneflow/api/python/framework/dtype.cpp
  oneflow/api/python/framework/tensor.cpp
  oneflow/api/python/functional/indexing.cpp
  oneflow/api/python/functional/python_arg.cpp
  oneflow/core/autograd/autograd_meta.h
  oneflow/core/autograd/gradient_funcs/cast.cpp
  oneflow/core/autograd/gradient_funcs/clip_by_scalar.cpp
  oneflow/core/autograd/gradient_funcs/clip_by_scalar_max.cpp
  oneflow/core/autograd/gradient_funcs/clip_by_scalar_min.cpp
  oneflow/core/autograd/gradient_funcs/normalization.cpp
  oneflow/core/autograd/gradient_funcs/padding.cpp
  oneflow/core/autograd/gradient_funcs/select_first.cpp
  oneflow/core/framework/dtype.cpp
  oneflow/core/framework/dtype.h
  oneflow/core/framework/op_interpreter/boxing/eager_boxing_interpreter.h
  oneflow/core/framework/op_interpreter/eager_mirrored_op_interpreter.cpp
  oneflow/core/framework/op_interpreter/lazy_op_interpreter.cpp
  oneflow/core/framework/op_interpreter/op_interpreter_util.cpp
  oneflow/core/framework/tensor.cpp
  oneflow/core/framework/tensor.h
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/core/functional/impl/consistent_cast.cpp
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/core/functional/impl/nn_grad_functor.cpp
  oneflow/core/functional/impl/random_functor.cpp
  oneflow/core/functional/value_types.h
  python/oneflow/compatible/single_client/ops/user_data_ops.py
  tools/generate_functional_api.py
Labels: enhancement, automerge, system

#5910 Fix inplace op circle reference bug
  oneflow/api/python/functional/python_functions.cpp
  oneflow/core/framework/op_expr_grad_function.h
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/binary_functor.cpp
  oneflow/core/functional/impl/binary_functor.h
  python/oneflow/nn/modules/linear.py
Labels: feature, automerge, bug, op

#5845 Control Graph / Session / Env's python c++ object destruction
  oneflow/api/python/session/session.cpp
  oneflow/api/python/session/session.h
  oneflow/api/python/session/session_api.h
  oneflow/core/framework/multi_client_session_context.cpp
  oneflow/core/framework/multi_client_session_context.h
  oneflow/core/framework/nn_graph.cpp
  oneflow/core/framework/nn_graph.h
  oneflow/core/job/env_global_objects_scope.cpp
  python/oneflow/framework/env_util.py
  python/oneflow/framework/multi_client_session.py
  python/oneflow/nn/graph.py
  python/oneflow/nn/graph_block.py
  python/oneflow/test/graph/test_graph_session_env_destruct.py
  python/oneflow/test/graph/test_graph_session_env_destruct1.py
Labels: enhancement, feature, automerge, system

#5914 fix grad error
  oneflow/core/autograd/gradient_funcs/activation.cpp
Labels: automerge, bug, op

#5919 Remove CompActor
  oneflow/core/actor/acc_actor.cpp
  oneflow/core/actor/acc_tick_actor.cpp
  oneflow/core/actor/acc_tick_compute_actor.h
  oneflow/core/actor/callback_notify_actor.cpp
  oneflow/core/actor/callback_notify_compute_actor.cpp
  oneflow/core/actor/case_actor.cpp
  oneflow/core/actor/case_compute_actor.h
  oneflow/core/actor/collective_boxing_generic_actor.cpp
  oneflow/core/actor/compute_actor.h
  oneflow/core/actor/copy_comm_net_actor.cpp
  oneflow/core/actor/copy_comm_net_actor.h
  oneflow/core/actor/copy_hd_actor.h
  oneflow/core/actor/esac_actor.cpp
  oneflow/core/actor/esac_compute_actor.h
  oneflow/core/actor/input_wise_actor.cpp
  oneflow/core/actor/input_wise_actor.h
  oneflow/core/actor/input_wise_compute_actor.h
  oneflow/core/actor/naive_actor.cpp
  oneflow/core/actor/naive_actor.h
  oneflow/core/actor/normal_forward_compute_actor.cpp
  oneflow/core/actor/normal_forward_compute_actor.h
  oneflow/core/actor/pack_actor.cpp
  oneflow/core/actor/reentrant_lock_actor.cpp
  oneflow/core/actor/repeat_actor.cpp
  oneflow/core/actor/sink_actor.cpp
  oneflow/core/actor/sink_actor.h
  oneflow/core/actor/sink_compute_actor.cpp
  oneflow/core/actor/sink_compute_actor.h
  oneflow/core/actor/source_tick_actor.cpp
  oneflow/core/actor/source_tick_compute_actor.cpp
  oneflow/core/actor/source_tick_compute_actor.h
  oneflow/core/actor/ssp_variable_proxy_actor.cpp
  oneflow/core/actor/tick_actor.cpp
  oneflow/core/actor/tick_compute_actor.cpp
  oneflow/core/actor/unpack_actor.cpp
  oneflow/core/actor/unpack_compute_actor.h
  oneflow/core/actor/wait_and_send_ids_actor.cpp
Labels: purge, automerge, system

#5680 add randperm with test and docs
  docs/source/oneflow.rst
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/random_functor.cpp
  oneflow/user/kernels/randperm_kernel.cpp
  oneflow/user/kernels/randperm_kernel.cu
  oneflow/user/ops/randperm_op.cpp
  python/oneflow/__init__.py
  python/oneflow/nn/modules/random_ops.py
  python/oneflow/test/modules/test_randperm.py
Labels: enhancement, automerge, ci, op, test, python

#5916 shared_or_scalar: fix alias warnings
  oneflow/core/common/shared_or_scalar.h
Labels: automerge, bug, system

#5917 Remove GlobalWorkStreamId/GlobalThrdId
  oneflow/core/actor/actor.cpp
  oneflow/core/actor/actor.h
  oneflow/core/graph/task_graph.cpp
  oneflow/core/graph/task_node.cpp
  oneflow/core/graph/task_node.h
  oneflow/core/job/id_manager.cpp
  oneflow/core/job/id_manager.h
Labels: enhancement, automerge, system

#5922 Move parse env to the constructor
  oneflow/core/comm_network/ibverbs/ibverbs_qp.cpp
  oneflow/core/comm_network/ibverbs/ibverbs_qp.h
Labels: automerge, bug, system
