Repository Oneflow-Inc/oneflow, pull requests merged in 2021-09, with the labels that each got.

#6093 add doc of graph
  docs/source/graph.rst
  python/oneflow/nn/graph/block.py
  python/oneflow/nn/graph/config.py
  python/oneflow/nn/graph/graph.py
Labels: automerge, documentation, api, python

#6117 move numpy c api init in numpy.cpp, make np array contiguous before copying
  oneflow/api/python/framework/tensor.cpp
  oneflow/api/python/ofblob/ofblob.e.h
  oneflow/extension/python/numpy.cpp
  oneflow/extension/python/numpy.h
  oneflow/extension/python/numpy_internal.h
  python/oneflow/test/tensor/test_tensor.py
Labels: automerge, bug, eager, api

#6121 Fix LayerNorm expr bug
  python/oneflow/nn/modules/normalization.py
Labels: automerge, bug, eager

#6123 disable_print_stack_in_tensor_numpy
  oneflow/api/python/blocking.cpp
  oneflow/api/python/framework/tensor.cpp
  oneflow/core/common/thread_local_callback.cpp
  oneflow/core/common/thread_local_callback.h
  oneflow/core/framework/transport_util.cpp
  python/oneflow/framework/tensor.py
Labels: enhancement, automerge, system

#6125 Fix test_grid_sample.py and test_affine_grid.py threshold
  python/oneflow/test/modules/test_affine_grid.py
  python/oneflow/test/modules/test_grid_sample.py
Labels: automerge, bug, python

#5992 send/recv
  oneflow/core/ccl/ccl.cpp
  oneflow/core/ccl/ccl.h
  oneflow/core/device/cuda_util.h
  oneflow/core/framework/transport_util.cpp
  oneflow/core/framework/transport_util.h
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/comm_functor.cpp
  oneflow/user/kernels/p2p_comm_kernel.cpp
  oneflow/user/ops/comm_net_device_infer_util.cpp
  oneflow/user/ops/comm_net_device_infer_util.h
  oneflow/user/ops/p2p_comm_op.cpp
  python/oneflow/__init__.py
  python/oneflow/comm/__init__.py
  python/oneflow/test/modules/test_comm.py
Labels: feature, automerge, system

#6116 Naive generic boxing
  oneflow/core/framework/op_interpreter/boxing/asymmetric_broadcast.cpp
  oneflow/core/framework/op_interpreter/boxing/asymmetric_x_to_b.cpp
  oneflow/core/framework/op_interpreter/boxing/boxing_dividor_util.cpp
  oneflow/core/framework/op_interpreter/boxing/boxing_dividor_util.h
  oneflow/core/framework/op_interpreter/boxing/eager_boxing_interpreter_mgr.cpp
  oneflow/core/framework/op_interpreter/boxing/naive_b2p_boxing_interpreter.cpp
  oneflow/core/framework/op_interpreter/boxing/nccl_boxing_function.cpp
  oneflow/core/framework/op_interpreter/boxing/symmetric_x_to_b.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/comm_functor.cpp
  oneflow/user/kernels/eager_nccl_kernels.cu
  python/oneflow/test/modules/test_consistent_cast.py
  python/oneflow/test/modules/test_eager_boxing.py
Labels: enhancement, system

#6113 update speed test
  .github/workflows/test.yml
  ci/test/test_speed_multi_client.sh
Labels: automerge, bug, ci

#6127 add_tensor_api_doc
  python/oneflow/framework/tensor.py
Labels: automerge, documentation, python

#6131 add optimizer api docs
  docs/source/nn.rst
  python/oneflow/nn/optimizer/adam.py
  python/oneflow/nn/optimizer/adamw.py
  python/oneflow/nn/optimizer/cosine_decay_lr.py
  python/oneflow/nn/optimizer/optimizer.py
  python/oneflow/nn/optimizer/rmsprop.py
  python/oneflow/nn/optimizer/sgd.py
  python/oneflow/nn/optimizer/warm_up_lr.py
Labels: automerge, documentation, python

#6048 Eager boxing one to one
  oneflow/core/framework/op_interpreter/boxing/asymmetric_broadcast.cpp
  oneflow/core/framework/op_interpreter/boxing/asymmetric_x_to_b.cpp
  oneflow/core/framework/op_interpreter/boxing/boxing_dividor_util.cpp
  oneflow/core/framework/op_interpreter/boxing/boxing_dividor_util.h
  oneflow/core/framework/op_interpreter/boxing/cuda_copy_boxing_interpreter.cpp
  oneflow/core/framework/op_interpreter/boxing/eager_boxing_interpreter_mgr.cpp
  oneflow/core/framework/op_interpreter/boxing/naive_b2p_boxing_interpreter.cpp
  oneflow/core/framework/op_interpreter/boxing/nccl_boxing_function.cpp
  oneflow/core/framework/op_interpreter/boxing/one_to_one_boxing.cpp
  oneflow/core/framework/op_interpreter/boxing/symmetric_x_to_b.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/comm_functor.cpp
  oneflow/core/functional/impl/consistent_cast.cpp
  oneflow/user/kernels/eager_nccl_kernels.cu
  python/oneflow/test/modules/test_consistent_cast.py
  python/oneflow/test/modules/test_eager_boxing.py
Labels: enhancement, automerge, system

#6110 Vm cpu efficiency
  oneflow/core/common/notifier.cpp
  oneflow/core/common/notifier.h
  oneflow/core/eager/cpu_blob_instruction_type.cpp
  oneflow/core/eager/cpu_opkernel_instruction_type.cpp
  oneflow/core/eager/release_tensor_instruction_type.cpp
  oneflow/core/object_msg/object_msg_mutexed_list.h
  oneflow/core/vm/cpu_stream_type.cpp
  oneflow/core/vm/cpu_stream_type.h
  oneflow/core/vm/oneflow_vm.cpp
  oneflow/core/vm/oneflow_vm.h
  oneflow/core/vm/virtual_machine.cpp
  oneflow/core/vm/virtual_machine.msg.h
  oneflow/core/vm/vm_util.cpp
Labels: enhancement, automerge, system

#6130 Add clipgrad doc and contiguous
  python/oneflow/__init__.py
  python/oneflow/framework/tensor.py
  python/oneflow/nn/modules/as_tensor.py
  python/oneflow/nn/utils/clip_grad.py
Labels: automerge, bug, ci, eager, op, documentation, interface

#6134 Refactor boxing interpreter to boxing expr
  oneflow/core/framework/op_interpreter/boxing/collective_boxing_interpreter.cpp
  oneflow/core/framework/op_interpreter/boxing/collective_boxing_interpreter.h
  oneflow/core/framework/op_interpreter/boxing/cuda_based_cpu_mpi_boxing_interpreter.cpp
  oneflow/core/framework/op_interpreter/boxing/cuda_based_cpu_mpi_boxing_interpreter.h
  oneflow/core/framework/op_interpreter/boxing/cuda_copy_boxing_interpreter.cpp
  oneflow/core/framework/op_interpreter/boxing/cuda_copy_boxing_interpreter.h
  oneflow/core/framework/op_interpreter/boxing/eager_boxing_interpreter_mgr.cpp
  oneflow/core/framework/op_interpreter/boxing/identity_boxing_interpreter.cpp
  oneflow/core/framework/op_interpreter/boxing/identity_boxing_interpreter.h
  oneflow/core/framework/op_interpreter/boxing/naive_1_to_n_boxing.cpp
  oneflow/core/framework/op_interpreter/boxing/naive_b2p_boxing_interpreter.cpp
  oneflow/core/framework/op_interpreter/boxing/naive_b2p_boxing_interpreter.h
  oneflow/core/framework/op_interpreter/boxing/naive_s2p_boxing_interpreter.cpp
  oneflow/core/framework/op_interpreter/boxing/naive_s2p_boxing_interpreter.h
Labels: enhancement, automerge, system

#6135 Static grad scaler
  python/oneflow/amp/__init__.py
  python/oneflow/amp/grad_scaler.py
  python/oneflow/nn/graph/graph.py
Labels: feature, eager

#6122 support consistent_tensor.to(copy=True)
  oneflow/api/python/eager/multi_client.cpp
  oneflow/api/python/eager/single_client.cpp
  oneflow/core/framework/nn_graph.cpp
  oneflow/core/framework/op_interpreter/lazy_op_interpreter.cpp
  oneflow/core/framework/tensor.cpp
  oneflow/core/framework/tensor.h
  oneflow/core/framework/tensor_impl.cpp
  oneflow/core/vm/vm_util.cpp
  oneflow/core/vm/vm_util.h
  oneflow/user/kernels/copy_kernel.cpp
  python/oneflow/nn/modules/to.py
  python/oneflow/test/modules/test_tensor_to.py
Labels: enhancement, automerge, eager

#6140 mv_boxing_folder_to_core
  oneflow/core/autograd/gradient_funcs/consistent_cast.cpp
  oneflow/core/boxing/asymmetric_broadcast.cpp
  oneflow/core/boxing/asymmetric_x_to_b.cpp
  oneflow/core/boxing/boxing_dividor.h
  oneflow/core/boxing/boxing_dividor_util.cpp
  oneflow/core/boxing/boxing_dividor_util.h
  oneflow/core/boxing/cuda_copy_boxing_interpreter.cpp
  oneflow/core/boxing/eager_boxing_interpreter.cpp
  oneflow/core/boxing/eager_boxing_interpreter.h
  oneflow/core/boxing/eager_boxing_interpreter_mgr.cpp
  oneflow/core/boxing/eager_boxing_interpreter_mgr.h
  oneflow/core/boxing/eager_boxing_interpreter_util.cpp
  oneflow/core/boxing/eager_boxing_interpreter_util.h
  oneflow/core/boxing/flatten_hierarchy.cpp
  oneflow/core/boxing/identity_boxing_interpreter.cpp
  oneflow/core/boxing/naive_1_to_n_boxing.cpp
  oneflow/core/boxing/naive_b2p_boxing_interpreter.cpp
  oneflow/core/boxing/naive_n_to_1_boxing.cpp
  oneflow/core/boxing/nccl_boxing_function.cpp
  oneflow/core/boxing/one_to_one_boxing.cpp
  oneflow/core/boxing/symmetric_x_to_b.cpp
  oneflow/core/framework/op_interpreter/eager_consistent_op_interpreter.cpp
Labels: enhancement, automerge, system

#6138 SystemOpFillJobNamePass
  oneflow/core/framework/op_kernel_infer_cache.cpp
  oneflow/core/job_rewriter/job_completer.cpp
  oneflow/core/job_rewriter/system_op_fill_job_name_pass.cpp
  oneflow/core/kernel/callback_notify_kernel.cpp
  oneflow/core/kernel/case_kernel.cpp
  oneflow/core/kernel/input_kernel.cpp
  oneflow/core/kernel/kernel.cpp
  oneflow/core/kernel/model_io_v2_kernel.cpp
  oneflow/core/kernel/output_kernel.cpp
  oneflow/core/kernel/return_kernel.cpp
  oneflow/core/kernel/runtime_blob_shape_infer_helper.cpp
  oneflow/core/kernel/runtime_blob_shape_infer_helper.h
  oneflow/core/kernel/wait_and_send_ids_kernel.cpp
  oneflow/core/operator/op_conf.proto
  oneflow/core/operator/op_infer_cache.h
Labels: enhancement, automerge, system

#6139 XRT remove job_desc
  oneflow/xrt/api.cpp
  oneflow/xrt/api.h
  oneflow/xrt/build_graph.cpp
  oneflow/xrt/build_graph.h
  oneflow/xrt/launch_kernel.cpp
  oneflow/xrt/launch_kernel.h
  oneflow/xrt/launch_op.cpp
  oneflow/xrt/passes/infer_shape_pass.cpp
Labels: enhancement, automerge, system

#6141 NewUniqueId thread safe
  oneflow/core/common/util.h
Labels: automerge, bug, system

#6142 Fix select_first_grad bug
  oneflow/core/autograd/gradient_funcs/select_first.cpp
Labels: enhancement, automerge, bug, op

#5800 Decompose nd sbp boxing
  oneflow/api/python/symbol/sbp_symbol.cpp
  oneflow/core/boxing/eager_boxing_interpreter_mgr.cpp
  oneflow/core/boxing/identity_boxing_interpreter.cpp
  oneflow/core/framework/op_interpreter/boxing/symmetric_nd_sbp_boxing.cpp
  oneflow/core/framework/op_interpreter/eager_consistent_op_interpreter.cpp
  oneflow/core/framework/op_interpreter/eager_mirrored_op_interpreter.cpp
  oneflow/core/framework/placement_sbp_util.cpp
  oneflow/core/framework/placement_sbp_util.h
  oneflow/core/framework/placement_sbp_util_test.cpp
  oneflow/core/functional/impl/consistent_cast.cpp
  oneflow/core/functional/impl/random_functor.cpp
  oneflow/core/job/parallel_desc.h
  oneflow/user/kernels/stateful_local_opkernel.cpp
  python/oneflow/test/modules/test_consistent_cast.py
Labels: enhancement, automerge, eager

#6136 not fuse request for nccl 2.10.3
  oneflow/core/job/collective_boxing_executor.cpp
Labels: enhancement, automerge, system

#6126 Fea/graph/add outputs buffer to enable pipeline
  oneflow/core/eager/lazy_job_instruction_type.cpp
  oneflow/core/framework/nn_graph.cpp
  python/oneflow/amp/__init__.py
  python/oneflow/amp/grad_scaler.py
  python/oneflow/nn/graph/config.py
  python/oneflow/nn/graph/graph.py
  python/oneflow/test/graph/test_graph_check.py
Labels: enhancement, automerge, system, api

#6148 add is_training to dropout functor
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  python/oneflow/nn/modules/dropout.py
Labels: enhancement, automerge, eager, api

#5799 fix cross_entropy_loss and its test
  python/oneflow/nn/modules/loss.py
  python/oneflow/test/modules/test_bce_loss.py
  python/oneflow/test/modules/test_bcewithlogitsloss.py
  python/oneflow/test/modules/test_crossentropyloss.py
  python/oneflow/test/modules/test_kldivloss.py
  python/oneflow/test/modules/test_l1loss.py
  python/oneflow/test/modules/test_loss.py
  python/oneflow/test/modules/test_marginrankingloss.py
  python/oneflow/test/modules/test_mseloss.py
  python/oneflow/test/modules/test_nllloss.py
  python/oneflow/test/modules/test_nllloss_grad.py
  python/oneflow/test/modules/test_smoothl1loss.py
  python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py
Labels: enhancement, automerge, op, test

#6144 UserKernel remove job_desc
  oneflow/core/eager/opkernel_object.cpp
  oneflow/core/framework/op_kernel.h
  oneflow/core/framework/op_kernel_infer_cache.cpp
  oneflow/core/framework/op_kernel_infer_cache.h
  oneflow/core/kernel/eager_kernel.h
  oneflow/core/kernel/kernel.cpp
  oneflow/core/kernel/kernel.h
  oneflow/core/kernel/user_kernel.cpp
  oneflow/core/kernel/user_kernel.h
  oneflow/user/kernels/conv_cudnn_kernels.cpp
  oneflow/user/kernels/deconv_cudnn_kernel.cpp
  oneflow/user/kernels/stateful_local_opkernel.h
Labels: enhancement, automerge, system

#6146 Fix wrong inplace acc grad
  oneflow/core/autograd/autograd_engine.cpp
  oneflow/core/framework/tensor_arg.cpp
  python/oneflow/test/modules/test_autograd.py
Labels: automerge, bug, system

#6150 fix repeat 0-dim tensor bug
  python/oneflow/nn/modules/repeat.py
Labels: automerge, bug, eager, op, api, interface

#6152 Fix optim load_state_dict bug
  python/oneflow/nn/optimizer/optimizer.py
Labels: automerge, bug, eager

#5960 Fix do bias correction in Adam/AdamW
  oneflow/core/job/job_conf.proto
  oneflow/core/job_rewriter/adam_optm.cpp
  oneflow/user/kernels/model_update_kernel_util.cpp
  oneflow/user/kernels/model_update_kernel_util.cu
  oneflow/user/kernels/model_update_kernel_util.h
  oneflow/user/kernels/model_update_kernels.cpp
  oneflow/user/ops/model_update_ops.cpp
  python/oneflow/compatible/single_client/test/ops/test_optimizers.py
  python/oneflow/nn/optimizer/adam.py
  python/oneflow/nn/optimizer/adamw.py
  python/oneflow/test/graph/test_graph_adam_optim.py
  python/oneflow/test/graph/test_graph_adamw_optim.py
  python/oneflow/test/modules/test_optim_adam.py
  python/oneflow/test/modules/test_optim_adamw.py
Labels: enhancement, automerge, bug, op

#6057 remove op_expr_helper inside gradient_funcs
  oneflow/core/autograd/gradient_funcs/adaptive_pool.cpp
  oneflow/core/autograd/gradient_funcs/avg_pooling.cpp
  oneflow/core/autograd/gradient_funcs/bias_add.cpp
  oneflow/core/autograd/gradient_funcs/broadcast_like.cpp
  oneflow/core/autograd/gradient_funcs/cast.cpp
  oneflow/core/autograd/gradient_funcs/concat.cpp
  oneflow/core/autograd/gradient_funcs/copy.cpp
  oneflow/core/autograd/gradient_funcs/deconv.cpp
  oneflow/core/autograd/gradient_funcs/flatten.cpp
  oneflow/core/autograd/gradient_funcs/logsoftmax.cpp
  oneflow/core/autograd/gradient_funcs/matmul.cpp
  oneflow/core/autograd/gradient_funcs/pool.cpp
  oneflow/core/autograd/gradient_funcs/pooling.cpp
  oneflow/core/autograd/gradient_funcs/reshape.cpp
  oneflow/core/autograd/gradient_funcs/select_first.cpp
  oneflow/core/autograd/gradient_funcs/split_like.cpp
  oneflow/core/autograd/gradient_funcs/squeeze.cpp
  oneflow/core/autograd/gradient_funcs/tensor_scalar_binary.cpp
  oneflow/core/autograd/gradient_funcs/transpose.cpp
  oneflow/core/autograd/gradient_funcs/unsqueeze.cpp
  oneflow/core/framework/user_op_conf_trait.cpp
  oneflow/core/framework/user_op_conf_trait.h
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/array_functor.cpp
Labels: enhancement, automerge, system

#6137 support inplace operation for hardsigmoid
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/activation_functor.cpp
  python/oneflow/nn/modules/activation.py
  python/oneflow/test/modules/test_activation.py
Labels: enhancement, automerge, op

#6157 add interpolate and layer_norm docs
  docs/source/functional.rst
Labels: enhancement, automerge, bug, ci, documentation, api

#5304 Add dtype bfloat16
  oneflow/api/python/flags.cpp
  oneflow/api/python/framework/dtype.cpp
  oneflow/core/common/data_type.cpp
  oneflow/core/common/data_type.proto
  oneflow/core/device/cuda_pseudo_bfloat16.h
  oneflow/core/framework/dtype.cpp
  oneflow/core/framework/dtype.h
  oneflow/user/kernels/cast_bfloat16_kernel.cu
  oneflow/user/kernels/cast_kernel.cpp
  oneflow/user/kernels/relu_bfloat16_kernel.cu
  python/oneflow/__init__.py
  python/oneflow/compatible/single_client/__init__.py
  python/oneflow/compatible/single_client/framework/dtype.py
  python/oneflow/compatible/single_client/framework/sysconfig.py
  python/oneflow/compatible/single_client/sysconfig.py
  python/oneflow/compatible/single_client/test/ops/test_bfloat16_relu.py
  python/oneflow/framework/dtype.py
  python/oneflow/framework/sysconfig.py
  python/oneflow/sysconfig.py
  tools/generate_oneflow_api.py
Labels: feature, automerge, system

#6151 Plan memory log
  oneflow/core/framework/nn_graph.cpp
  oneflow/core/job/oneflow.cpp
  oneflow/core/job/plan_util.cpp
  oneflow/core/job/plan_util.h
  oneflow/core/vm/cuda_allocator.cpp
Labels: feature, automerge, system

#6114 transfer python function to c++ method
  docs/source/_C.rst
  docs/source/index.rst
  docs/source/oneflow.rst
  oneflow/api/python/framework/doc.cpp
  pyth
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/__init__.py
  python/oneflow/framework/docstr/activation.py
  python/oneflow/framework/docstr/array_ops.py
  python/oneflow/framework/docstr/cast.py
  python/oneflow/framework/docstr/comparison.py
  python/oneflow/framework/docstr/constant.py
  python/oneflow/framework/docstr/conv.py
  python/oneflow/framework/docstr/dropout.py
  python/oneflow/framework/docstr/math_ops.py
  python/oneflow/framework/docstr/onehot.py
  python/oneflow/framework/docstr/pooling.py
  python/oneflow/framework/docstr/random.py
  python/oneflow/framework/docstr/vision.py
  python/oneflow/framework/tensor.py
  python/oneflow/nn/modules/activation.py
  python/oneflow/nn/modules/cast.py
  python/oneflow/nn/modules/comparison.py
  python/oneflow/nn/modules/consistent_cast.py
  python/oneflow/nn/modules/constant.py
  python/oneflow/nn/modules/diag.py
  python/oneflow/nn/modules/exp.py
  python/oneflow/nn/modules/log1p.py
  python/oneflow/nn/modules/math_ops.py
  python/oneflow/nn/modules/random_ops.py
  python/oneflow/nn/modules/round.py
  python/oneflow/nn/modules/softplus.py
  python/oneflow/nn/modules/trigonometric_ops.py
  python/oneflow/nn/modules/tril.py
  python/oneflow/nn/modules/triu.py
  python/oneflow/test/modules/test_functional_docstr.py
  python/oneflow/test/tensor/test_tensor.py
Labels: enhancement, feature, automerge, bug, ci, eager, op, documentation, interface

#6161 CI: fix clang tidy checks in simple ci
  .github/workflows/simple.yml
Labels: automerge, bug, ci, need-simple-ci

#6162 delete file
  pyth
Labels: feature, automerge, bug, eager, api, interface

#6163 Aligin pooling op functional api names with torch
  oneflow/core/functional/functional_api.yaml
  python/oneflow/nn/functional/__init__.py
  python/oneflow/nn/modules/pooling.py
Labels: enhancement, automerge, eager, api, interface

#6164 equal => allclose
  python/oneflow/test/tensor/test_tensor.py
  python/oneflow/test/tensor/test_tensor_indexing.py
Labels: enhancement, automerge, ci

#6160 restore instr_local_dep_object_pool_size for nccl
  oneflow/core/framework/device.cpp
Labels: automerge, bug, eager

#6170 align dropout api name with pytorch
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
Labels: automerge, bug, eager, op, api, interface

#6171 Fix autotest codegen bug
  python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py
Labels: enhancement, automerge, bug, eager, interface

#6174 Add Int support for functional.avg/maxpool
  oneflow/core/functional/functional_api.yaml
Labels: enhancement, automerge, op, api

#6168 Fix BroadcastMatmulGrad bug
  oneflow/core/autograd/gradient_funcs/matmul.cpp
  oneflow/core/autograd/gradient_funcs/transpose.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_grad_functor.cpp
  python/oneflow/test/modules/test_matmul.py
Labels: automerge, bug, op, system

#6169 Remove IDMgr::GetGpuPhyIdFromThrdId/IDMgr::GetDeviceTypeFromThrdId
  oneflow/core/graph/boxing/slice_boxing_sub_task_graph_builder.cpp
  oneflow/core/graph/boxing/sub_task_graph_builder_util.cpp
  oneflow/core/graph/copy_task_node.cpp
  oneflow/core/graph/task_graph.cpp
  oneflow/core/graph/task_node.cpp
  oneflow/core/graph/task_node.h
  oneflow/core/job/id_manager.cpp
  oneflow/core/job/id_manager.h
  oneflow/core/job/intra_job_mem_sharing_util.cpp
  oneflow/core/job/plan_util.cpp
  oneflow/core/job/plan_util.h
  oneflow/user/summary/plan_to_physical_graph.cpp
Labels: enhancement, automerge, system

#6149 fix backward index for gamma beta
  oneflow/core/autograd/gradient_funcs/layer_norm.cpp
  oneflow/core/framework/op_expr_helper.cpp
  oneflow/core/framework/op_expr_helper.h
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_grad_functor.cpp
  oneflow/user/ops/layer_norm_op.cpp
  python/oneflow/nn/modules/normalization.py
  python/oneflow/test/modules/test_layernorm.py
  python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py
Labels: automerge, bug, eager, op

#6023 add: test convert dependency
  python/oneflow/test/graph/test_tvm_frontend_dependency_on_graph.py
Labels: enhancement, automerge, good for pr, eager, api, interface

#6182 Change dropout api
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  python/oneflow/nn/modules/dropout.py
Labels: enhancement, automerge, eager, api

#6184 Align Torch.nn.functional poolXd
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  python/oneflow/nn/functional/__init__.py
  python/oneflow/nn/functional/functional_maxpool.py
  python/oneflow/nn/modules/pooling.py
Labels: enhancement, automerge, op

#6183 Primitive
  oneflow/core/common/auto_registration_factory.h
  oneflow/core/kernel/copy_hd_kernel.cpp
  oneflow/core/primitive/cpu/memcpy.cpp
  oneflow/core/primitive/cuda/memcpy.cpp
  oneflow/core/primitive/memcpy.h
  oneflow/core/primitive/primitive.h
Labels: enhancement, automerge, system

#6188 Disable implicit boxing when parallel num eq one
  oneflow/core/framework/op_interpreter/eager_consistent_op_interpreter.cpp
Labels: enhancement, automerge, system

#6181 Lazy support Scalar
  oneflow/core/common/shape.cpp
  oneflow/core/common/shape.h
  oneflow/core/job/nd_sbp_util.cpp
  oneflow/core/job/plan_util.cpp
  oneflow/core/operator/operator.cpp
  python/oneflow/test/graph/test_graph_scalar.py
Labels: feature, automerge, system, interface

#6196 Fix LayerNorm check bug
  python/oneflow/nn/modules/normalization.py
Labels: automerge, bug, eager

#6065 add glu op
  docs/source/functional.rst
  docs/source/nn.rst
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/activation_functor.cpp
  python/oneflow/framework/docstr/activation.py
  python/oneflow/nn/__init__.py
  python/oneflow/nn/functional/__init__.py
  python/oneflow/nn/modules/activation.py
  python/oneflow/test/modules/test_glu.py
Labels: enhancement, automerge, eager, op, api

#6195 Primitive based copy task node
  oneflow/core/graph/copy_task_node.cpp
  oneflow/core/graph/copy_task_node.h
  oneflow/core/graph/task_graph.cpp
  oneflow/core/graph/task_node.h
  oneflow/core/primitive/cpu/memcpy.cpp
  oneflow/core/primitive/cuda/memcpy.cpp
Labels: enhancement, automerge, system

#6198 Typesafe KernelState
  oneflow/core/actor/actor.cpp
  oneflow/core/actor/case_actor.cpp
  oneflow/core/actor/esac_actor.cpp
  oneflow/core/actor/light_actor.cpp
  oneflow/core/actor/reentrant_lock_actor.cpp
  oneflow/core/actor/wait_and_send_ids_actor.cpp
  oneflow/core/eager/opkernel_object.h
  oneflow/core/kernel/case_kernel.cpp
  oneflow/core/kernel/case_kernel.h
  oneflow/core/kernel/esac_kernel.cpp
  oneflow/core/kernel/esac_kernel.h
  oneflow/core/kernel/kernel.cpp
  oneflow/core/kernel/kernel.h
  oneflow/core/kernel/kernel_context.h
  oneflow/core/kernel/reentrant_lock_kernel.cpp
  oneflow/core/kernel/reentrant_lock_kernel.h
  oneflow/core/kernel/wait_and_send_ids_kernel.cpp
  oneflow/core/kernel/wait_and_send_ids_kernel.h
Labels: enhancement, automerge, system

#6172 container_util: fix VectorAt, remove useless MutMapAt
  oneflow/core/common/container_util.h
  oneflow/core/framework/placement_sbp_util.cpp
Labels: enhancement, automerge, system

#6191 Refine StreamContext
  oneflow/core/actor/actor.cpp
  oneflow/core/actor/light_actor.cpp
  oneflow/core/device/device_context.h
  oneflow/core/stream/cpu_stream_context.cpp
  oneflow/core/stream/cuda_stream_context.cpp
  oneflow/core/stream/execution_context_hook.h
  oneflow/core/stream/stream_context.h
  oneflow/core/thread/thread.cpp
Labels: enhancement, automerge, system

#6153 Cpu symetric s to s
  oneflow/core/boxing/ccl_boxing_function.cpp
  oneflow/core/boxing/eager_boxing_interpreter_mgr.cpp
  oneflow/core/functional/impl/comm_functor.cpp
  oneflow/user/kernels/eager_nccl_kernels.cpp
  python/oneflow/test/modules/test_consistent_cast.py
Labels: enhancement, automerge, system

#6197 Fix bug in model fused update
  oneflow/core/job_rewriter/fuse_update_ops_pass.cpp
  oneflow/user/ops/model_update_ops.cpp
Labels: automerge, bug, op

#6202 consistent tensor zeros_()
  oneflow/api/python/utils/tensor_utils.cpp
  python/oneflow/test/tensor/test_tensor.py
Labels: enhancement, automerge, eager

#6155 [Feat.] nn.Graph support grad acc with input/output tensor
  oneflow/core/job_rewriter/gradient_accumulation_rewrite_pass.cpp
  oneflow/core/operator/output_op.cpp
  oneflow/user/kernels/pack_kernel.cpp
  oneflow/user/ops/pack_op.cpp
  python/oneflow/framework/graph_build_util.py
  python/oneflow/nn/graph/graph.py
  python/oneflow/test/graph/test_graph_grad_acc.py
Labels: feature, bottleneck, automerge, system, interface

#6199 Dev eliminate gcc warnings
  oneflow/core/framework/op_interpreter/boxing/symmetric_nd_sbp_boxing.cpp
  oneflow/core/job/session_global_objects_scope.cpp
  oneflow/user/kernels/nvtx_range_kernel.cu
  oneflow/user/ops/narrow_op.cpp
  oneflow/user/ops/prelu_op.cpp
Labels: enhancement, automerge, system

#6206 Autotest generate input tensor
  python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py
Labels: automerge, bug, eager, tooling, test, api, interface

#6212 Cleanup KernelUtil
  oneflow/core/kernel/kernel_util.cpp
  oneflow/core/kernel/kernel_util.cu
  oneflow/core/kernel/kernel_util.h
Labels: purge, automerge, system

#6190 Rename flow to oneflow in user hint
  ci/test/test_speed_multi_client.sh
  oneflow/api/python/autograd/autograd.cpp
  oneflow/api/python/framework/shape.cpp
  oneflow/core/framework/tensor.h
  python/oneflow/framework/docstr/comparison.py
  python/oneflow/framework/docstr/math_ops.py
  python/oneflow/framework/docstr/vision.py
  python/oneflow/nn/graph/graph.py
  python/oneflow/nn/modules/affine_grid.py
  python/oneflow/nn/modules/batchnorm.py
  python/oneflow/nn/modules/bmm.py
  python/oneflow/nn/modules/concat.py
  python/oneflow/nn/modules/consistent_cast.py
  python/oneflow/nn/modules/conv.py
  python/oneflow/nn/modules/empty.py
  python/oneflow/nn/modules/expand.py
  python/oneflow/nn/modules/flatten.py
  python/oneflow/nn/modules/floor.py
  python/oneflow/nn/modules/fold.py
  python/oneflow/nn/modules/gather.py
  python/oneflow/nn/modules/linear.py
  python/oneflow/nn/modules/math_ops.py
  python/oneflow/nn/modules/matmul.py
  python/oneflow/nn/modules/padding.py
  python/oneflow/nn/modules/permute.py
  python/oneflow/nn/modules/pixelshuffle.py
  python/oneflow/nn/modules/pooling.py
  python/oneflow/nn/modules/random_ops.py
  python/oneflow/nn/modules/repeat.py
  python/oneflow/nn/modules/reshape.py
  python/oneflow/nn/modules/slice.py
  python/oneflow/nn/modules/squeeze.py
  python/oneflow/nn/modules/stack.py
  python/oneflow/nn/modules/tensor_buffer.py
  python/oneflow/nn/modules/tile.py
  python/oneflow/nn/modules/transpose.py
  python/oneflow/nn/modules/unsqueeze.py
Labels: enhancement, automerge, eager

#6175 make flow._C.local_all_reduce sync lanuched
  oneflow/core/functional/impl/comm_functor.cpp
Labels: automerge, bug, eager

#6208 [Feat.] Lazy interpreter skip hierarchical_parallel_cast
  oneflow/core/framework/op_interpreter/lazy_op_interpreter.cpp
Labels: feature, automerge, system, interface

#6203 fix sparse_softmax get_nd_sbp
  oneflow/core/job_rewriter/split_sparse_softmax_cross_entropy_op_pass.cpp
Labels: automerge, bug, op

#6201 support default value in intlist
  tools/functional/generator.py
Labels: enhancement, automerge, op

#6189 add all_gather and fix bug of multi rank doctest
  python/oneflow/comm/__init__.py
  python/oneflow/comm/comm_ops.py
  python/oneflow/framework/unittest.py
  python/oneflow/test/modules/test_sync_comm_ops.py
Labels: feature, automerge, system

#6214 add emoji in speed test output, make it continue-on-error
  .github/workflows/test.yml
  ci/test/test_speed_multi_client.sh
Labels: enhancement, automerge, ci

#6217 Add StreamContext::device_type()/DeviceCtx::device_type()
  oneflow/core/device/collective_boxing_device_context.h
  oneflow/core/device/cpu_device_context.h
  oneflow/core/device/cuda_device_context.h
  oneflow/core/device/device_context.h
  oneflow/core/eager/lazy_job_device_context.h
  oneflow/core/job/collective_boxing_executor.cpp
  oneflow/core/stream/cpu_stream_context.cpp
  oneflow/core/stream/cuda_stream_context.cpp
  oneflow/core/stream/stream_context.h
  oneflow/core/stream/stream_context_adapter.cpp
  oneflow/core/vm/cuda_copy_d2h_device_context.h
  oneflow/core/vm/cuda_stream_handle_device_context.h
Labels: enhancement, automerge, system

#6218 Add memset primitive
  oneflow/core/primitive/cpu/memset.cpp
  oneflow/core/primitive/cuda/memset.cpp
  oneflow/core/primitive/memset.h
  oneflow/core/primitive/primitive.h
Labels: enhancement, automerge, system

#6154 Rename op_name_ to op_type_name_ in AutogradEngine
  oneflow/core/autograd/autograd_engine.cpp
  oneflow/core/autograd/autograd_engine.h
Labels: enhancement, automerge, system, refactor

#6213 Comm broadcast
  oneflow/core/framework/op_interpreter/eager_mirrored_op_interpreter.cpp
  oneflow/core/framework/op_interpreter/eager_mirrored_op_interpreter.h
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/comm_functor.cpp
  python/oneflow/comm/__init__.py
  python/oneflow/comm/comm_ops.py
  python/oneflow/test/modules/test_comm_ops.py
Labels: feature, automerge, system

#6165 rnn test
  python/oneflow/nn/__init__.py
  python/oneflow/nn/modules/rnn.py
  python/oneflow/test/modules/test_rnn.py
Labels: enhancement, feature, automerge, op, python

#6223 Dev reconstruct pad ops
  oneflow/core/autograd/gradient_funcs/padding.cpp
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/core/functional/impl/nn_grad_functor.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/vision.py
  python/oneflow/nn/modules/padding.py
  python/oneflow/test/modules/test_constantpad.py
Labels: enhancement, automerge, eager, api, interface

#6230 UserKernel init CUDA Graphs with state
  oneflow/core/kernel/cuda_graph_support.h
  oneflow/core/kernel/user_kernel.cpp
  oneflow/user/kernels/conv_cudnn_kernels.cpp
Labels: enhancement, automerge, system

#6077 Dev fused bn functional
  oneflow/core/autograd/gradient_funcs/normalization_add_relu.cpp
  oneflow/core/framework/op_expr.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/core/functional/impl/nn_grad_functor.cpp
  oneflow/user/ops/normalization_op.cpp
  python/oneflow/nn/__init__.py
  python/oneflow/nn/modules/batchnorm_fused.py
  python/oneflow/test/modules/test_bn_add_relu.py
Labels: enhancement, automerge, op

#6192 graph activation checkpointing
  python/oneflow/nn/graph/block.py
  python/oneflow/nn/graph/graph.py
  python/oneflow/nn/graph/util.py
  python/oneflow/test/graph/test_graph_activation_checkpoint.py
  python/oneflow/test/graph/test_graph_check.py
  python/oneflow/test/graph/test_optimization_conf.py
  python/oneflow/utils/__init__.py
Labels: enhancement, automerge, test, python

#6235 move scalar to oneflow namespace.
  oneflow/api/python/functional/common.cpp
  oneflow/api/python/functional/common.h
  oneflow/api/python/functional/python_arg.cpp
  oneflow/api/python/functional/tensor_api.cpp
  oneflow/api/python/functional/value_types.h
  oneflow/core/autograd/gradient_funcs/broadcast_binary_ops.cpp
  oneflow/core/autograd/gradient_funcs/clip_by_scalar.cpp
  oneflow/core/autograd/gradient_funcs/clip_by_scalar_max.cpp
  oneflow/core/autograd/gradient_funcs/clip_by_scalar_min.cpp
  oneflow/core/autograd/gradient_funcs/fused_scale_tril.cpp
  oneflow/core/autograd/gradient_funcs/padding.cpp
  oneflow/core/autograd/gradient_funcs/scalar_mul.cpp
  oneflow/core/common/scalar.cpp
  oneflow/core/common/scalar.h
  oneflow/core/framework/nn_graph.cpp
  oneflow/core/framework/tensor.cpp
  oneflow/core/functional/impl/activation_functor.cpp
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/core/functional/impl/binary_functor.cpp
  oneflow/core/functional/impl/comm_functor.cpp
  oneflow/core/functional/impl/dataset_functor.cpp
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/core/functional/impl/nn_grad_functor.cpp
  oneflow/core/functional/impl/quantization.cpp
  tools/functional/generate_functional_api.py
  tools/functional/generate_tensor_api.py
Labels: enhancement, automerge, system

#6204 Auto FixPipelineStageIdPass
  oneflow/core/job/job_build_and_infer_ctx.cpp
  oneflow/core/job_rewriter/fix_pipeline_stage_id_pass.cpp
  oneflow/core/job_rewriter/pipeline_buffer_pass.cpp
Labels: feature, bottleneck, automerge, system, interface

#6222 Use attr nd_sbp to check consistent
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/core/job/parallel_desc.cpp
  oneflow/core/job/parallel_desc.h
  oneflow/user/data/coco_data_reader.cpp
  oneflow/user/data/ofrecord_dataset.h
  oneflow/user/kernels/gpt_data_loader_kernel.cpp
  python/oneflow/compatible/single_client/test/ops/test_gpt_data_loader.py
Labels: automerge, bug, op

#6228 Support assign copy interface
  oneflow/api/python/framework/tensor.cpp
  oneflow/core/common/maybe.h
  oneflow/core/framework/tensor.cpp
  oneflow/core/framework/tensor.h
  python/oneflow/nn/module.py
  python/oneflow/nn/optimizer/adam.py
  python/oneflow/nn/optimizer/adamw.py
  python/oneflow/nn/optimizer/optimizer.py
  python/oneflow/nn/optimizer/rmsprop.py
  python/oneflow/nn/optimizer/sgd.py
  python/oneflow/test/dataloader/test_lenet.py
  python/oneflow/test/graph/test_graph_scalar.py
  python/oneflow/test/tensor/test_consistent_tensor.py
  python/oneflow/test/tensor/test_parameter.py
  python/oneflow/test/tensor/test_tensor.py
Labels: feature, automerge, eager

#6234 Add cast primitive
  oneflow/core/primitive/cast.h
  oneflow/core/primitive/cpu/cast.cpp
  oneflow/core/primitive/cpu/type_seq.h
  oneflow/core/primitive/cuda/cast.cu
  oneflow/core/primitive/cuda/type_seq.h
  oneflow/core/primitive/primitive.h
Labels: enhancement, automerge, bug, system

#6221 Fix bug of Multi-Client src tick output order
  oneflow/core/framework/nn_graph.cpp
  oneflow/core/graph/task_graph.cpp
  oneflow/core/graph/task_graph.h
  oneflow/core/job/compiler.cpp
  python/oneflow/test/graph/test_graph_pipeline_delay.py
Labels: automerge, bug, system, interface

#5849 Cpu all reduce
  oneflow/core/boxing/ccl_boxing_function.cpp
  oneflow/core/boxing/eager_boxing_interpreter_mgr.cpp
  oneflow/core/ccl/ccl.cpp
  oneflow/core/ccl/ccl.h
  oneflow/core/functional/impl/comm_functor.cpp
  oneflow/core/thread/thread_manager.cpp
  oneflow/user/kernels/eager_nccl_kernels.cpp
  python/oneflow/test/modules/test_consistent_cast.py
Labels: enhancement, automerge, eager

#6239 fix bug about tensor str in nonsymmetric cast and getitem in consist…
  oneflow/core/functional/impl/array_functor.cpp
  python/oneflow/framework/tensor_str.py
  python/oneflow/test/modules/test_tensor_str.py
Labels: enhancement, automerge, bug, eager

#6105 Fea/pipeline in graph
  oneflow/core/framework/instructions_builder.h
  oneflow/core/job_rewriter/gradient_accumulation_rewrite_pass.cpp
  oneflow/core/job_rewriter/pipeline_buffer_pass.cpp
  oneflow/user/kernels/empty_kernel.cpp
  python/oneflow/compatible/single_client/framework/env_util.py
  python/oneflow/framework/env_util.py
  python/oneflow/framework/graph_build_util.py
  python/oneflow/nn/graph/block.py
  python/oneflow/nn/graph/config.py
  python/oneflow/nn/graph/graph.py
  python/oneflow/test/graph/test_graph_pipeline.py
Labels: feature, automerge, python

#6240 NNGraph input/output valid by register tensors
  oneflow/api/python/framework/nn_graph.cpp
  oneflow/core/eager/lazy_job_instruction_type.cpp
  oneflow/core/eager/lazy_job_instruction_type_test.cpp
  oneflow/core/framework/nn_graph.cpp
  oneflow/core/framework/nn_graph.h
  oneflow/core/framework/nn_graph_if.h
  python/oneflow/nn/graph/graph.py
  python/oneflow/test/graph/test_graph_buffer_limit.py
Labels: feature, bottleneck, automerge, bug, system, interface

#6233 Dev functional batch_gather
  docs/source/oneflow.rst
  oneflow/core/autograd/gradient_funcs/batch_gather.cpp
  oneflow/core/framework/op_expr_helper.cpp
  oneflow/core/framework/op_expr_helper.h
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/array_functor.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/array_ops.py
  python/oneflow/nn/modules/broadcast_like.py
  python/oneflow/test/modules/test_batch_gather.py
Labels: automerge, op, documentation

#6248 fix default stride value
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  python/oneflow/nn/functional/functional_maxpool.py
  python/oneflow/test/modules/test_avgpool.py
  python/oneflow/test/modules/test_maxpool.py
  tools/functional/generator.py
Labels: enhancement, automerge, op

#6256 Comm scatter
  docs/source/comm.rst
  docs/source/index.rst
  python/oneflow/comm/__init__.py
  python/oneflow/comm/comm_ops.py
  python/oneflow/framework/docstr/__init__.py
  python/oneflow/framework/docstr/comm.py
  python/oneflow/test/modules/test_comm_ops.py
Labels: automerge, eager, documentation, system

#6257 OpKernel add stream_ctx
  cmake/oneflow.cmake
  oneflow/core/framework/op_kernel.h
  oneflow/core/kernel/user_kernel.cpp
  oneflow/core/kernel/user_kernel.h
  oneflow/user/kernels/stateful_local_opkernel.cpp
  oneflow/user/kernels/stateful_local_opkernel.h
Labels: enhancement, automerge, system

#6263 Refine tensor getitem to support backward for local tensor.
  oneflow/core/autograd/gradient_funcs/slice.cpp
  oneflow/core/framework/op_interpreter/op_interpreter.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/core/functional/impl/common.cpp
Labels: enhancement, automerge, system

#6268 Replace reshape conf in grad acc pass
  oneflow/core/common/shape.cpp
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/core/job_rewriter/gradient_accumulation_rewrite_pass.cpp
Labels: feature, system

#6264 CudaGraphPrimitive
  oneflow/core/primitive/cuda/cast.cu
  oneflow/core/primitive/cuda/cuda_graph_support.cpp
  oneflow/core/primitive/cuda/cuda_graph_support.h
  oneflow/core/primitive/cuda/memcpy.cpp
  oneflow/core/primitive/cuda/memset.cpp
Labels: enhancement, automerge, system

#6251 replace ##__LINE__ in ONEFLOW_API_PYBIND11_MODULE by OF_PP_CAT
  oneflow/api/python/of_api_registry.h
Labels: automerge, bug, python

#6254 [Feat.] flow.reshape support Gradient Accumulation and Scalar
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/core/job_rewriter/gradient_accumulation_rewrite_pass.cpp
  oneflow/user/ops/reshape_op.cpp
  python/oneflow/test/graph/test_graph_reshape_acc.py
  python/oneflow/test/modules/test_reshape.py
Labels: feature, bottleneck, automerge, bug, op

#6262 graph support eager lrs
  oneflow/core/job/learning_rate_schedule_conf.proto
  oneflow/core/kernel/learning_rate_schedule_kernel.cpp
  python/oneflow/amp/grad_scaler.py
  python/oneflow/nn/graph/graph.py
  python/oneflow/nn/graph/optimizer.py
  python/oneflow/nn/optimizer/adam.py
  python/oneflow/nn/optimizer/adamw.py
  python/oneflow/nn/optimizer/cosine_annealing_lr.py
  python/oneflow/nn/optimizer/cosine_decay_lr.py
  python/oneflow/nn/optimizer/multistep_lr.py
  python/oneflow/nn/optimizer/rmsprop.py
  python/oneflow/nn/optimizer/sgd.py
  python/oneflow/nn/optimizer/step_lr.py
  python/oneflow/nn/optimizer/warm_up_lr.py
  python/oneflow/test/graph/test_graph_lr_with_warmup.py
  python/oneflow/test/graph/test_graph_lrs.py
  python/oneflow/test/graph/test_graph_optim_adam.py
  python/oneflow/test/graph/test_graph_optim_adamw.py
  python/oneflow/test/graph/test_graph_optim_rmsprop.py
  python/oneflow/test/graph/test_graph_optim_sgd.py
Labels: feature, automerge, op, system

#6269 Refactor symmetric b to s
  oneflow/core/boxing/eager_boxing_interpreter_mgr.cpp
  oneflow/core/boxing/nccl_boxing_function.cpp
  oneflow/core/boxing/symmetric_b_to_s_boxing.cpp
Labels: enhancement, automerge, system

#6258 sccache -> ccache
  .github/workflows/simple.yml
  .github/workflows/test.yml
  cmake/caches/cn/fast/cpu-clang.cmake
  cmake/caches/cn/fast/cpu.cmake
  cmake/caches/cn/fast/cuda-61.cmake
  cmake/caches/cn/fast/cuda-75.cmake
Labels: enhancement, automerge, ci, need-simple-ci

#6266 add comm reduce op
  python/oneflow/comm/__init__.py
  python/oneflow/comm/comm_ops.py
  python/oneflow/test/modules/test_comm_ops.py
Labels: automerge, documentation, system, api

#6267 functional: support overload
  oneflow/core/functional/function_library.h
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/math_functor.cpp
  tools/functional/generator.py
Labels: enhancement, automerge, tooling, api, python

#6274 Create device generator immediately when creating kernel state.
  oneflow/core/common/device_type.h
  oneflow/core/framework/random_generator.cpp
  oneflow/core/framework/random_generator.h
  oneflow/user/kernels/bernoulli_kernel.cpp
  oneflow/user/kernels/distributions/normal_kernel.h
  oneflow/user/kernels/distributions/uniform_kernel.h
  oneflow/user/kernels/random_mask_like_kernel.h
  oneflow/user/kernels/randperm_kernel.cpp
  oneflow/user/kernels/randperm_kernel.cu
  python/oneflow/test/modules/test_generator.py
Labels: enhancement, automerge, system

#6278 fix simple ci env yml not found
  .github/workflows/simple.yml
Labels: automerge, bug, ci, need-simple-ci

#6284 Cpu all gather
  oneflow/core/boxing/ccl_boxing_function.cpp
  oneflow/core/boxing/eager_boxing_interpreter_mgr.cpp
  oneflow/core/ccl/ccl.cpp
  oneflow/core/ccl/ccl.h
  oneflow/core/functional/impl/comm_functor.cpp
  oneflow/user/kernels/eager_nccl_kernels.cpp
  python/oneflow/test/modules/test_consistent_cast.py
Labels: enhancement, automerge, system

#6187 optional: refactor & make it a first-class user of JUST macros
  oneflow/api/python/functional/tensor_api.cpp
  oneflow/api/python/utils/tensor_utils.cpp
  oneflow/core/autograd/autograd_meta.cpp
  oneflow/core/autograd/gradient_funcs/clip_by_scalar_max.cpp
  oneflow/core/autograd/gradient_funcs/clip_by_scalar_min.cpp
  oneflow/core/autograd/gradient_funcs/consistent_cast.cpp
  oneflow/core/autograd/gradient_funcs/consistent_to_consistent.cpp
  oneflow/core/autograd/gradient_funcs/eager_nccl_broadcast.cpp
  oneflow/core/boxing/one_to_one_boxing.cpp
  oneflow/core/boxing/symmetric_b_to_s_boxing.cpp
  oneflow/core/ccl/ccl.cpp
  oneflow/core/common/error.cpp
  oneflow/core/common/error.h
  oneflow/core/common/error.proto
  oneflow/core/common/just.h
  oneflow/core/common/maybe.h
  oneflow/core/common/optional.h
  oneflow/core/common/optional_test.cpp
  oneflow/core/common/shape.h
  oneflow/core/eager/eager_blob_object.h
  oneflow/core/eager/local_call_opkernel_phy_instr_operand.cpp
  oneflow/core/eager/run_lazy_job_phy_instr_operand.cpp
  oneflow/core/framework/consistent_tensor_infer_cache.cpp
  oneflow/core/framework/device.cpp
  oneflow/core/framework/op_interpreter/eager_consistent_op_interpreter.cpp
  oneflow/core/framework/op_interpreter/eager_mirrored_op_interpreter.cpp
  oneflow/core/framework/op_interpreter/lazy_op_interpreter.cpp
  oneflow/core/framework/op_interpreter/op_interpreter_util.cpp
  oneflow/core/framework/placement_sbp_util.cpp
  oneflow/core/framework/tensor_impl.cpp
  oneflow/core/framework/tensor_impl.h
  oneflow/core/framework/tensor_rpc_util.cpp
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/core/functional/impl/comm_functor.cpp
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/core/functional/impl/random_functor.cpp
  oneflow/user/kernels/stateful_local_opkernel.cpp
Labels: enhancement, automerge, system

#6265 Refactor symmetric s to p
  oneflow/core/boxing/eager_boxing_interpreter_mgr.cpp
  oneflow/core/boxing/symmetric_b_to_p_boxing.cpp
  oneflow/core/boxing/symmetric_s_to_p_boxing.cpp
  oneflow/user/kernels/eager_symmetric_s_to_p_kernel.cpp
  oneflow/user/ops/eager_symmetric_s_to_p_op.cpp
  python/oneflow/test/modules/test_consistent_cast.py
  python/oneflow/test/modules/test_eager_boxing.py
Labels: enhancement, automerge, system

#6210 Replace the Send Receive of the buffer
  oneflow/api/python/framework/framework.h
  oneflow/core/common/buffer.h
  oneflow/core/eager/lazy_job_instruction_type.cpp
  oneflow/core/eager/lazy_job_instruction_type_test.cpp
  oneflow/core/kernel/wait_and_send_ids_kernel.cpp
  oneflow/user/data/data_reader.h
  oneflow/user/data/ofrecord_image_classification_dataset.h
Labels: enhancement, automerge, system

#6286 update readme 0.5rc1
  .github/workflows/simple.yml
  README.md
Labels: automerge, documentation, system, need-simple-ci

#6289 default mem chain merge false
  oneflow/core/job/resource.proto
Labels: automerge, bug, system

#6250 set argmax output dtype to int64_t
  oneflow/user/kernels/argmax_kernel.cpp
  oneflow/user/kernels/argmax_kernel.cu
  oneflow/user/ops/argmax_op.cpp
  python/oneflow/nn/modules/argmax.py
Labels: enhancement, bug, op

#6186 Naive Eager S to S
  oneflow/core/boxing/eager_boxing_interpreter_mgr.cpp
  oneflow/core/boxing/naive_s_to_s_boxing.cpp
  oneflow/core/ccl/ccl.cpp
  oneflow/core/common/math_util.cpp
  oneflow/core/common/math_util.h
  oneflow/core/device/nccl_util.h
  oneflow/core/framework/placement_sbp_util.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/slice_boxing_functor.cpp
  oneflow/core/job/parallel_desc.cpp
  oneflow/core/job/parallel_desc.h
  oneflow/user/kernels/communicate_util.cpp
  oneflow/user/kernels/communicate_util.h
  oneflow/user/kernels/eager_nccl_kernels.cpp
  oneflow/user/kernels/eager_s_to_s_kernel.cpp
  oneflow/user/ops/eager_s_to_s_op.cpp
  python/oneflow/test/modules/test_eager_boxing.py
Labels: enhancement, automerge, system

#6273 add comm_gather
  docs/source/comm.rst
  python/oneflow/comm/__init__.py
  python/oneflow/comm/comm_ops.py
  python/oneflow/test/modules/test_comm_ops.py
Labels: automerge, eager, test, documentation, api

#6288 Fix single-client reader parallel
  oneflow/user/data/coco_data_reader.cpp
  oneflow/user/data/ofrecord_dataset.h
  oneflow/user/kernels/gpt_data_loader_kernel.cpp
Labels: automerge, bug, op

#6295 Fix quantization docs bug
  python/oneflow/nn/modules/fake_quantization.py
  python/oneflow/nn/modules/min_max_observer.py
  python/oneflow/nn/modules/moving_average_min_max_observer.py
  python/oneflow/nn/modules/quantization.py
Labels: enhancement, automerge, ci, documentation, api

#6297 Fix ddp all_reduce bug
  python/oneflow/nn/parallel/ddp.py
Labels: automerge, bug, eager

#6300 Fix bug of reshape rewrite in Single-Client grad acc
  oneflow/core/job_rewriter/gradient_accumulation_rewrite_pass.cpp
Labels: automerge, bug, system

#6296 Use new conda build in simple CI
  .github/workflows/simple.yml
  cmake/caches/ci/gh-hosted/cpu-clang.cmake
  cmake/caches/ci/gh-hosted/cpu-gcc.cmake
Labels: enhancement, automerge, ci, need-simple-ci

#6277 add comm reduce_scatter
  docs/source/comm.rst
  python/oneflow/comm/__init__.py
  python/oneflow/comm/comm_ops.py
  python/oneflow/test/modules/test_comm_ops.py
Labels: feature, automerge, eager, op

#6305 remove_eager_boxing_interpreter_util
  oneflow/core/boxing/asymmetric_broadcast.cpp
  oneflow/core/boxing/asymmetric_x_to_b.cpp
  oneflow/core/boxing/ccl_boxing_function.cpp
  oneflow/core/boxing/eager_boxing_interpreter_mgr.cpp
  oneflow/core/boxing/eager_boxing_interpreter_util.cpp
  oneflow/core/boxing/eager_boxing_interpreter_util.h
  oneflow/core/boxing/naive_1_to_n_boxing.cpp
  oneflow/core/boxing/naive_n_to_1_boxing.cpp
  oneflow/core/boxing/naive_s_to_s_boxing.cpp
  oneflow/core/boxing/nccl_boxing_function.cpp
  oneflow/core/boxing/one_to_one_boxing.cpp
  oneflow/core/boxing/symmetric_b_to_p_boxing.cpp
  oneflow/core/boxing/symmetric_s_to_p_boxing.cpp
  oneflow/core/boxing/symmetric_x_to_b.cpp
  oneflow/core/framework/id_util.h
Labels: enhancement, automerge, system

#6307 fix the test_rnn.py
  python/oneflow/test/modules/test_rnn.py
Labels: automerge, bug, test

#6261 Transfer python assertion in PReLU to c++
  oneflow/core/functional/impl/activation_functor.cpp
  python/oneflow/nn/modules/activation.py
Labels: enhancement, automerge, op

#6306 cast: return self for same dtype
  oneflow/core/functional/impl/math_functor.cpp
Labels: enhancement, automerge, system, api

#6225 System kernels use memcpy/memset primitive
  oneflow/core/eager/lazy_job_instruction_type.cpp
  oneflow/core/kernel/assign_kernel.cpp
  oneflow/core/kernel/boxing_kernel.cpp
  oneflow/core/kernel/boxing_zeros_kernel.cpp
  oneflow/core/kernel/collective_boxing_kernels.cpp
  oneflow/core/kernel/collective_boxing_pack_kernel.cpp
  oneflow/core/kernel/collective_boxing_unpack_kernel.cpp
  oneflow/core/kernel/copy_hd_kernel.cpp
  oneflow/core/kernel/distribute_add_kernel.cpp
  oneflow/core/kernel/distribute_clone_kernel.cpp
  oneflow/core/kernel/distribute_concat_kernel.cpp
  oneflow/core/kernel/distribute_kernels.cpp
  oneflow/core/kernel/distribute_split_kernel.cpp
  oneflow/core/kernel/dynamic_reshape_kernel.cpp
  oneflow/core/kernel/dynamic_reshape_like_kernel.cpp
  oneflow/core/kernel/identity_kernel.cpp
  oneflow/core/kernel/input_kernel.cpp
  oneflow/core/kernel/kernel_util.cpp
  oneflow/core/kernel/kernel_util.cu
  oneflow/core/kernel/kernel_util.h
  oneflow/core/kernel/output_kernel.cpp
  oneflow/core/kernel/return_kernel.cpp
  oneflow/core/register/blob.cpp
  oneflow/core/register/blob.h
  oneflow/user/kernels/reduce_kernel.cpp
  oneflow/user/kernels/reduce_like_kernels.cpp
Labels: enhancement, automerge, system

#6301 Parameter override grad_fn_node functions
  oneflow/core/framework/tensor.h
  python/oneflow/test/tensor/test_parameter.py
  python/oneflow/test/tensor/test_tensor.py
  python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py
Labels: automerge, bug, eager, system

#6308 Add framework utils for Chinese Version API Docs
  docs/source/conf.py
  docs/source/zh/__init__.py
  docs/source/zh/activation.py
  docs/source/zh/math_ops.py
  oneflow/api/python/framework/doc.cpp
  python/oneflow/framework/docstr/utils.py
Labels: automerge, documentation, system

#6310 Fix ddp multi-output bug
  oneflow/core/autograd/gradient_funcs/select_top_n.cpp
  oneflow/core/framework/op_expr.cpp
  oneflow/core/framework/op_expr.h
  oneflow/core/framework/op_interpreter.h
  oneflow/core/framework/op_interpreter/eager_consistent_op_interpreter.cpp
  oneflow/core/framework/op_interpreter/eager_mirrored_op_interpreter.cpp
  oneflow/core/framework/op_interpreter/op_interpreter.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/math_functor.cpp
  python/oneflow/nn/parallel/ddp.py
Labels: automerge, bug, eager

#6318 fix 2d-sbp consistent tensor initalization
  python/oneflow/framework/tensor.py
  python/oneflow/test/tensor/test_consistent_tensor.py
Labels: automerge, bug, python

#6312 Add primitive
  oneflow/core/device/cuda_pseudo_bfloat16.h
  oneflow/core/primitive/add.h
  oneflow/core/primitive/cpu/add.cpp
  oneflow/core/primitive/cpu/cast.cpp
  oneflow/core/primitive/cuda/add.cu
  oneflow/core/primitive/cuda/cast.cu
Labels: enhancement, automerge, system

#6328 fix_broadcast_grad_bug
  oneflow/core/framework/op_interpreter/eager_mirrored_op_interpreter.cpp
Labels: automerge, bug, system

#6330 nd sbp tensor temporarily print '[...]'
  python/oneflow/framework/tensor_str.py
Labels: feature, automerge, system

#6333 fix url System Design
  README.md
Labels: automerge, documentation, system

#6303 refactor SoftSyncStream and call it in ReleaseTensor
  ci/test/test_speed_multi_client.sh
  oneflow/core/eager/blob_instruction_type.cpp
  oneflow/core/eager/blob_instruction_type.h
  oneflow/core/eager/cpu_blob_instruction_type.cpp
  oneflow/core/eager/cuda_blob_instruction_type.cpp
  oneflow/core/eager/eager_blob_object.h
  oneflow/core/framework/device.cpp
  oneflow/core/framework/device.h
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/framework/instructions_builder.h
  oneflow/core/framework/op_interpreter/eager_consistent_op_interpreter.cpp
  oneflow/core/framework/op_interpreter/eager_mirrored_op_interpreter.cpp
  oneflow/core/functional/impl/comm_functor.cpp
  oneflow/core/vm/consume_local_dep_object_phy_instr_operand.cpp
  oneflow/core/vm/consume_local_dep_object_phy_instr_operand.h
Labels: automerge, bug, eager

#6316 Add cn docs build to CI test
  .gitignore
  ci/test/build_docs.sh
  docs/Makefile
  docs/source/cn/__init__.py
  docs/source/cn/activation.py
  docs/source/cn/math_ops.py
  docs/source/conf.py
Labels: enhancement, automerge, ci, documentation

#6118 Dev Adagrad Optimizer
  docs/source/optim.rst
  oneflow/core/job/job_conf.proto
  oneflow/core/job_rewriter/adagrad_optm.cpp
  oneflow/user/kernels/model_update_kernel_util.cpp
  oneflow/user/kernels/model_update_kernel_util.cu
  oneflow/user/kernels/model_update_kernel_util.h
  oneflow/user/kernels/model_update_kernels.cpp
  oneflow/user/ops/model_update_ops.cpp
  python/oneflow/nn/optimizer/adagrad.py
  python/oneflow/optim/__init__.py
  python/oneflow/test/graph/test_graph_optim_adagrad.py
  python/oneflow/test/modules/test_optim_adagrad.py
Labels: feature, automerge, op

#6313 Add more autotest sample
  oneflow/user/kernels/upsample_kernel.h
  python/oneflow/nn/modules/gather.py
  python/oneflow/nn/modules/index_select.py
  python/oneflow/nn/modules/math_ops.py
  python/oneflow/nn/modules/normalization.py
  python/oneflow/nn/modules/sort.py
  python/oneflow/test/modules/test_activation.py
  python/oneflow/test/modules/test_batch_gather.py
  python/oneflow/test/modules/test_bernoulli.py
  python/oneflow/test/modules/test_cat.py
  python/oneflow/test/modules/test_concat.py
  python/oneflow/test/modules/test_conv1d.py
  python/oneflow/test/modules/test_conv2d.py
  python/oneflow/test/modules/test_deconv2d.py
  python/oneflow/test/modules/test_exp.py
  python/oneflow/test/modules/test_gather.py
  python/oneflow/test/modules/test_groupnorm.py
  python/oneflow/test/modules/test_masked_select.py
  python/oneflow/test/modules/test_math_ops.py
  python/oneflow/test/modules/test_mean.py
  python/oneflow/test/modules/test_relu.py
  python/oneflow/test/modules/test_sign.py
  python/oneflow/test/modules/test_upsample.py
  python/oneflow/test/tensor/test_tensor.py
  python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py
Labels: enhancement, automerge, bug, ci, api

#6320 Refactor user op expr infer ctx
  oneflow/core/framework/consistent_tensor_infer_cache.cpp
  oneflow/core/framework/op_expr.cpp
  oneflow/core/framework/op_expr.h
  oneflow/core/framework/op_interpreter/eager_mirrored_op_interpreter.cpp
Labels: enhancement, automerge, system

#6326 fix bug when output tensor is 0 shape
  oneflow/user/kernels/concat_kernel.cpp
  python/oneflow/framework/tensor_str.py
  python/oneflow/test/modules/test_concat.py
  python/oneflow/test/tensor/test_tensor.py
Labels: automerge, bug, system

#6334 Refine Lamb
  oneflow/core/kernel/kernel_util.cpp
  oneflow/core/kernel/kernel_util.cu
  oneflow/core/kernel/kernel_util.h
  oneflow/core/primitive/add.h
  oneflow/core/primitive/cast.h
  oneflow/core/primitive/memcpy.h
  oneflow/core/primitive/memset.h
  oneflow/user/kernels/model_update_kernel_util.cpp
  oneflow/user/kernels/model_update_kernel_util.cu
  oneflow/user/kernels/model_update_kernel_util.h
Labels: enhancement, automerge, op

#6337 Add sbp and placment doc
  docs/source/index.rst
  docs/source/placement.rst
  docs/source/sbp.rst
  oneflow/api/python/symbol/placement_symbol.cpp
  oneflow/api/python/symbol/sbp_symbol.cpp
  python/oneflow/framework/docstr/__init__.py
  python/oneflow/framework/docstr/placement.py
  python/oneflow/framework/docstr/sbp.py
  python/oneflow/framework/env_util.py
  python/oneflow/test/modules/test_functional_docstr.py
Labels: automerge, documentation, system

#6340 Dev scalar Logical and or xor And Reload operator
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/user/kernels/scalar_logical_kernels.cpp
  oneflow/user/kernels/scalar_logical_kernels.cu
  oneflow/user/kernels/scalar_logical_kernels.h
  oneflow/user/ops/scalar_logical_op.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/tensor.py
  python/oneflow/nn/modules/logical_ops.py
  python/oneflow/test/modules/test_logical_and.py
  python/oneflow/test/modules/test_logical_or.py
  python/oneflow/test/modules/test_logical_xor.py
Labels: enhancement, automerge, op

#6347 Fill primitive
  oneflow/core/kernel/case_kernel.cpp
  oneflow/core/kernel/constant_like_kernel.cpp
  oneflow/core/kernel/esac_kernel.cpp
  oneflow/core/kernel/kernel_util.cpp
  oneflow/core/kernel/kernel_util.cu
  oneflow/core/kernel/kernel_util.h
  oneflow/core/kernel/shape_elem_cnt_kernel.cpp
  oneflow/core/primitive/cpu/fill.cpp
  oneflow/core/primitive/cuda/fill.cu
  oneflow/core/primitive/fill.h
  oneflow/user/kernels/arg_where_kernel_util.cpp
  oneflow/user/kernels/arg_where_kernel_util.cu
  python/oneflow/compatible/single_client/test/ops/test_constant_like.py
Labels: enhancement, automerge, system

#6348 Reduce simple ci usage
  .github/workflows/simple.yml
Labels: enhancement, automerge, ci, need-simple-ci

#6211 Asymmetric s(x) to b boxing
  oneflow/core/boxing/eager_boxing_interpreter_mgr.cpp
  oneflow/core/boxing/naive_s_to_b_boxing.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/slice_boxing_functor.cpp
  oneflow/user/kernels/eager_s_to_b_kernel.cpp
  oneflow/user/ops/eager_s_to_b_op.cpp
  python/oneflow/test/modules/test_eager_boxing.py
Labels: enhancement, automerge, system

#6285 Implement generator "__getstate__" and "__setstate__"
  oneflow/api/python/common.cpp
  oneflow/api/python/common.h
  oneflow/api/python/framework/device.cpp
  oneflow/api/python/framework/device.h
  oneflow/api/python/framework/random_generator.cpp
  oneflow/core/framework/device.cpp
  oneflow/core/framework/device.h
  oneflow/core/framework/random_generator.cpp
  oneflow/core/framework/random_generator.h
  oneflow/core/framework/random_generator_impl.cpp
  oneflow/core/framework/random_generator_impl.h
  python/oneflow/framework/generator.py
  python/oneflow/test/modules/test_bernoulli.py
  python/oneflow/test/modules/test_generator.py
  python/oneflow/test/modules/test_rand.py
  python/oneflow/test/modules/test_randint.py
  python/oneflow/test/modules/test_randn.py
  python/oneflow/test/modules/test_randperm.py
Labels: enhancement, feature, automerge, system
