Repository Oneflow-Inc/oneflow, pull requests merged in 2021-12, with the labels that each got.

#6888 fix a bug about graph debug
  python/oneflow/nn/graph/graph.py
Labels: enhancement, automerge, system

#5572 Dev add torch dot op eager - backward for eager mode
  oneflow/core/autograd/gradient_funcs/dot.cpp
Labels: enhancement, op

#5578 Dev add torch dot - backward for lazy mode
  oneflow/user/ops/dot_op.cpp
Labels: documentation, system

#6713 throw.h: move to core/common
  oneflow/api/python/framework/doc.cpp
  oneflow/api/python/framework/tensor.cpp
  oneflow/api/python/functional/common.h
  oneflow/api/python/functional/py_function.h
  oneflow/api/python/functional/python_arg.h
  oneflow/api/python/functional/unpack_call.h
  oneflow/api/python/symbol/job_conf_symbol.cpp
  oneflow/api/python/symbol/op_conf_symbol.cpp
  oneflow/api/python/symbol/op_node_signature_symbol.cpp
  oneflow/api/python/symbol/placement_symbol.cpp
  oneflow/api/python/symbol/scope_symbol.cpp
  oneflow/api/python/symbol/string_symbol.cpp
  oneflow/core/common/throw.h
  oneflow/extension/python/numpy.cpp
Labels: enhancement, automerge, system, api

#6913 More information on CI bot auto posted message
  .github/workflows/test.yml
Labels: enhancement, automerge, ci

#6227 Lch movedim
  docs/source/oneflow.rst
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/math_functor.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/math_ops.py
  python/oneflow/test/modules/test_movedim.py
Labels: enhancement, automerge, ci, op

#6906 nd_index_helper for loop use N
  oneflow/core/common/nd_index_offset_helper.h
Labels: enhancement, automerge, system, need-clean-ccache

#6902 Auto parallel/add nd sbp
  oneflow/core/auto_parallel/sbp_collector.cpp
  oneflow/core/auto_parallel/sbp_collector.h
  oneflow/core/auto_parallel/sbp_constructor.cpp
  oneflow/core/auto_parallel/sbp_constructor.h
  oneflow/core/auto_parallel/sbp_edge.h
  oneflow/core/auto_parallel/sbp_util.cpp
  oneflow/core/auto_parallel/sbp_util.h
  oneflow/core/framework/compute_complexity_fn_context.h
  oneflow/core/framework/user_op_registry.cpp
  oneflow/core/framework/user_op_registry.h
  oneflow/core/job/sbp_parallel.cpp
  oneflow/core/job/sbp_parallel.h
  oneflow/core/operator/operator.cpp
  oneflow/core/operator/operator.h
  oneflow/core/operator/output_op.h
  oneflow/core/operator/user_op.cpp
  oneflow/core/operator/user_op.h
  oneflow/user/ops/avg_pooling_op.cpp
  oneflow/user/ops/conv_op.cpp
  oneflow/user/ops/matmul_op.cpp
  oneflow/user/ops/ofrecord_reader_op.cpp
  oneflow/user/ops/pool_op.cpp
  oneflow/user/ops/pooling_op.cpp
  oneflow/user/ops/softmax_op.cpp
Labels: AutoParallel

#6833 add unittest of test_ddp_multmple_outputs
  python/oneflow/test/modules/test_ddp.py
  python/oneflow/test/modules/test_ddp_multi_outputs.py
Labels: enhancement, automerge, bug, eager, test

#6912 [EP] Memory Management
  oneflow/core/device/cuda_util.cpp
  oneflow/core/device/cuda_util.h
  oneflow/core/ep/cpu/cpu_device.cpp
  oneflow/core/ep/cpu/cpu_device.h
  oneflow/core/ep/cuda/cuda_device.cpp
  oneflow/core/ep/cuda/cuda_device.h
  oneflow/core/ep/include/allocation_options.h
  oneflow/core/ep/include/device.h
  oneflow/core/memory/memory_allocator.cpp
  oneflow/core/memory/memory_allocator.h
Labels: enhancement, automerge, system, need-clean-ccache

#6919 Migrate python logic to functor
  oneflow/core/functional/impl/nn_functor.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/__init__.py
  python/oneflow/framework/docstr/bmm.py
  python/oneflow/framework/docstr/tensor.py
Labels: enhancement, automerge, eager, documentation, api

#5522 add dot operator
  docs/source/oneflow.rst
  oneflow/core/autograd/gradient_funcs/dot.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/user/kernels/dot_kernel.cpp
  oneflow/user/ops/dot_op.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/math_ops.py
  python/oneflow/test/modules/test_dot.py
Labels: enhancement, automerge, system

#6915 Fix Dropout return value and Optimize CPU schedule
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/user/kernels/dropout_kernel.cu
  python/oneflow/test/modules/test_dropout.py
Labels: enhancement, automerge, bug, op, need-clean-ccache

#6784 Decompose ndarray reduce in out dtype and dev all any
  oneflow/api/python/framework/dtype.cpp
  oneflow/api/python/framework/tensor.cpp
  oneflow/api/python/ofblob/ofblob.cpp
  oneflow/api/python/ofblob/ofblob.e.h
  oneflow/api/python/utils/tensor_utils.cpp
  oneflow/core/common/data_type.cpp
  oneflow/core/common/data_type.h
  oneflow/core/common/data_type.proto
  oneflow/core/common/data_type_seq.h
  oneflow/core/framework/dtype.cpp
  oneflow/core/framework/dtype.h
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/core/ndarray/binary_func.h
  oneflow/core/ndarray/ndarray_assign_core.cpp
  oneflow/core/ndarray/ndarray_assign_core.cu
  oneflow/core/ndarray/ndarray_assign_core.h
  oneflow/core/ndarray/ndarray_reduce.h
  oneflow/core/ndarray/ndarray_reduce_impl.cpp
  oneflow/core/ndarray/ndarray_reduce_impl.cu
  oneflow/core/ndarray/ndarray_reduce_impl.h
  oneflow/core/ndarray/xpu_ndarray_assign.cu
  oneflow/core/ndarray/xpu_ndarray_assign.h
  oneflow/user/kernels/reduce_kernel.cpp
  oneflow/user/kernels/slice_kernel.cpp
  oneflow/user/kernels/slice_util.h
  oneflow/user/ops/reduce_ops.cpp
  python/oneflow/__init__.py
  python/oneflow/compatible/single_client/__init__.py
  python/oneflow/compatible/single_client/framework/dtype.py
  python/oneflow/framework/dtype.py
  python/oneflow/framework/tensor.py
  python/oneflow/nn/modules/reduce_ops.py
  python/oneflow/test/modules/test_logical_reduce.py
  tools/generate_oneflow_api.py
Labels: enhancement, automerge, op, system

#6924 Fix .clang-tidy: `modernize-use-emplace` is added to `WarningsAsErrors` but not `Checks`
  .clang-tidy
Labels: enhancement, automerge, ci

#6918 Fix bug of tensor index in consistent
  oneflow/core/functional/tensor_index.cpp
Labels: automerge, bug, eager, op

#6887 move python code to cpp for dim_gather, gather_nd
  oneflow/core/autograd/gradient_funcs/dim_scatter.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/array_functor.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/array_ops.py
  python/oneflow/framework/docstr/tensor.py
  python/oneflow/framework/tensor.py
  python/oneflow/nn/modules/gather.py
Labels: enhancement, op, documentation

#6911 move lazy op to eager mode: read_onerec, decode_onerec
  docs/source/oneflow.rst
  oneflow/api/python/functional/python_arg.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/dataset_functor.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/__init__.py
  python/oneflow/framework/docstr/dataset.py
  python/oneflow/test/modules/test_one_rec_ops.py
Labels: enhancement, automerge, op, need-clean-ccache

#6932 Add CudaStream::device_properties()
  oneflow/core/ep/cuda/cuda_device.cpp
  oneflow/core/ep/cuda/cuda_device.h
  oneflow/core/ep/cuda/cuda_stream.cpp
  oneflow/core/ep/cuda/cuda_stream.h
  oneflow/user/kernels/dropout_kernel.cu
Labels: enhancement, automerge, system, need-clean-ccache

#6935 Rename namespace device to hardware
  .github/CODEOWNERS
  oneflow/core/device/cuda_util.cpp
  oneflow/core/ep/cuda/cuda_stream.cpp
  oneflow/core/hardware/basic_device_descriptor_list.cpp
  oneflow/core/hardware/basic_device_descriptor_list.h
  oneflow/core/hardware/cuda_device_descriptor.cpp
  oneflow/core/hardware/cuda_device_descriptor.h
  oneflow/core/hardware/cuda_device_descriptor_class.cpp
  oneflow/core/hardware/device_descriptor.h
  oneflow/core/hardware/device_descriptor_class.cpp
  oneflow/core/hardware/device_descriptor_class.h
  oneflow/core/hardware/device_descriptor_list.h
  oneflow/core/hardware/net_ib_device_descriptor.cpp
  oneflow/core/hardware/net_ib_device_descriptor.h
  oneflow/core/hardware/net_ib_device_descriptor_class.cpp
  oneflow/core/hardware/net_socket_device_descriptor.cpp
  oneflow/core/hardware/net_socket_device_descriptor.h
  oneflow/core/hardware/net_socket_device_descriptor_class.cpp
  oneflow/core/hardware/node_device_descriptor.cpp
  oneflow/core/hardware/node_device_descriptor.h
  oneflow/core/hardware/node_device_descriptor_manager.cpp
  oneflow/core/hardware/node_device_descriptor_manager.h
  oneflow/core/hardware/topology_descriptor.cpp
  oneflow/core/hardware/topology_descriptor.h
  oneflow/core/job/env_global_objects_scope.cpp
  oneflow/core/job/session_global_objects_scope.cpp
Labels: enhancement, automerge, system, need-clean-ccache

#6869 Optimize prelu kernel
  oneflow/core/job_rewriter/auto_mixed_precision_lists.cpp
  oneflow/user/kernels/prelu_kernel.cu
  python/oneflow/test/modules/test_prelu.py
Labels: enhancement, feature, automerge, bug, eager, op, interface

#6925 Refine loss operators with cuda::elementwise
  oneflow/user/kernels/binary_cross_entropy_kernel.cu
  oneflow/user/kernels/binary_cross_entropy_with_logits_kernel.cu
  oneflow/user/kernels/kl_div_kernel.cu
  oneflow/user/kernels/smooth_l1_loss_kernel.cu
Labels: enhancement, automerge, op, refactor

#6928 Fix ODS pool op and add user op ODS generating to CMake
  cmake/oneflow.cmake
  oneflow/api/python/ir.cpp
  oneflow/ir/include/OneFlow/CMakeLists.txt
  oneflow/ir/include/OneFlow/OneFlowBase.td
  oneflow/ir/include/OneFlow/OneFlowEnums.td
  oneflow/ir/include/OneFlow/OneFlowOpGetGen.td
  oneflow/ir/include/OneFlow/OneFlowOps.td
  oneflow/ir/include/OneFlow/OneFlowPatterns.td
  oneflow/ir/include/OneFlow/OneFlowUserOpGen.td
  oneflow/ir/lib/OneFlow/CMakeLists.txt
  oneflow/ir/lib/OneFlow/Passes.cpp
  oneflow/ir/oneflow-gen-ods/oneflow-gen-ods.cpp
  oneflow/ir/test/OneFlow/ops/test_adaptive_pool.py
Labels: enhancement, automerge, bug, build, system, api

#6942 Annotation conv group and rmsprop
  python/oneflow/test/modules/test_conv1d.py
  python/oneflow/test/modules/test_conv2d.py
  python/oneflow/test/modules/test_conv3d.py
  python/oneflow/test/modules/test_fused_scale_mask_softmax_dropout.py
  python/oneflow/test/modules/test_grid_sample.py
  python/oneflow/test/modules/test_optim_rmsprop.py
  python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py
Labels: enhancement, automerge, bug, eager, interface

#6943 Refactor the way data type attribute is handled for Op Schema
  oneflow/ir/include/OneFlow/OneFlowEnums.td
  oneflow/ir/oneflow-gen-ods/oneflow-gen-ods.cpp
  oneflow/ir/oneflow-translate/lib/OneFlow/Importer.cpp
  oneflow/ir/test/OneFlow/jit-outline-func.mlir
  oneflow/ir/test/OneFlow/lower_to_tosa.mlir
Labels: enhancement, automerge, system

#6947 fix modernize-use-emplace check in simple ci
  oneflow/api/python/symbol/placement_symbol.cpp
  oneflow/core/graph/boxing/fallback_to_cpu_slice_boxing_sub_task_graph_builder.cpp
Labels: enhancement, automerge, ci

#6959 Refine OneFlow dialect namespace
  .github/workflows/pr.yml
  oneflow/ir/CMakeLists.txt
  oneflow/ir/include/OneFlow/OneFlowBase.td
  oneflow/ir/include/OneFlow/OneFlowPatterns.td
  oneflow/ir/include/OneFlow/OneFlowSupport.h
  oneflow/ir/lib/OneFlow/CMakeLists.txt
  oneflow/ir/lib/OneFlow/Conversion/OneFlowToTosa.cpp
  oneflow/ir/lib/OneFlow/OneFlowDialect.cpp
  oneflow/ir/lib/OneFlow/OneFlowOpTraits.cpp
  oneflow/ir/lib/OneFlow/OneFlowOps.cpp
  oneflow/ir/lib/OneFlow/OneFlowSupport.cpp
  oneflow/ir/lib/OneFlow/Passes.cpp
  oneflow/ir/oneflow-extension/ir_pass.cpp
  oneflow/ir/oneflow-gen-ods/oneflow-gen-ods.cpp
  oneflow/ir/oneflow-translate/include/OneFlow/MLIROneFlowTranslation.h
  oneflow/ir/oneflow-translate/lib/OneFlow/Importer.cpp
  oneflow/ir/oneflow-translate/lib/OneFlow/MLIROneFlowTranslation.cpp
  oneflow/ir/oneflow-translate/oneflow-translate.cpp
Labels: enhancement, system, ir

#6938 revert_pr_6852
  oneflow/core/eager/eager_blob_object.cpp
  oneflow/core/eager/eager_blob_object.h
  oneflow/core/eager/local_dep_object.h
  oneflow/core/eager/opkernel_instruction_type.cpp
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/framework/tensor_impl.cpp
  oneflow/core/framework/tensor_impl.h
  oneflow/core/framework/tensor_storage.cpp
  oneflow/core/framework/tensor_storage.h
  oneflow/user/kernels/stateful_local_opkernel.cpp
Labels: automerge, bug, system

#6975 remove test/models directory
  python/oneflow/test/models/1node_test.py
  python/oneflow/test/models/2node_test.py
  python/oneflow/test/models/alexnet.py
  python/oneflow/test/models/alexnet_with_unpack.py
  python/oneflow/test/models/bert.py
  python/oneflow/test/models/cnns_tests.py
  python/oneflow/test/models/eager_1node_test.py
  python/oneflow/test/models/env_1node.py
  python/oneflow/test/models/env_2node.py
  python/oneflow/test/models/inceptionv3.py
  python/oneflow/test/models/pretrain.py
  python/oneflow/test/models/resnet50.py
  python/oneflow/test/models/run_cnns_test.py
  python/oneflow/test/models/test_1node_mixin.py
  python/oneflow/test/models/test_2node_mixin.py
  python/oneflow/test/models/test_alexnet_model.py
  python/oneflow/test/models/test_bert.py
  python/oneflow/test/models/test_dcgan.py
  python/oneflow/test/models/test_dcgan_model.py
  python/oneflow/test/models/test_dqn.py
  python/oneflow/test/models/vgg16.py
Labels: automerge, bug, test

#6909 Dev fix boolean array index
  oneflow/api/python/functional/indexing.cpp
  oneflow/core/common/data_type.cpp
  oneflow/core/functional/tensor_index.cpp
  python/oneflow/test/tensor/test_tensor_indexing.py
Labels: enhancement, automerge, bug, system

#6855 nn.Graph support process num greater than physical device num
  .github/workflows/test.yml
  oneflow/core/eager/lazy_job_phy_instr_operand.cpp
  oneflow/core/framework/multi_client_session_context.cpp
  python/oneflow/test/graph/test_neq_device_process_num.py
Labels: automerge, bug, system, graph

#6946 Fix generate rate
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/user/kernels/random_mask_generator.cu
Labels: enhancement, automerge, bug, op

#6952 add prelu half kernel
  oneflow/user/kernels/tf_prelu_kernel.cu
Labels: enhancement, feature, automerge, eager, documentation

#6978 add oneflow_add_llvm_library etc., fix warnings
  cmake/oneflow.cmake
  cmake/util.cmake
  oneflow/core/common/high_order_bool.h
  oneflow/core/framework/user_op_tensor.h
  oneflow/ir/CMakeLists.txt
  oneflow/ir/include/OneFlow/Extension.h
  oneflow/ir/lib/OneFlow/CMakeLists.txt
  oneflow/ir/oneflow-extension/CMakeLists.txt
  oneflow/ir/oneflow-extension/ir_pass.cpp
  oneflow/ir/oneflow-translate/lib/OneFlow/CMakeLists.txt
  oneflow/ir/oneflow-translate/lib/OneFlow/Importer.cpp
Labels: enhancement, automerge, build

#6961 fix bug of ResourceDesc process_ranks init
  oneflow/core/job/resource_desc.cpp
Labels: automerge, bug, system

#6872 Optimize LayerNorm Backward dx
  oneflow/core/cuda/layer_norm.cuh
  oneflow/user/kernels/layer_norm_gpu_kernel.cu
  python/oneflow/compatible/single_client/test/ops/test_layer_norm.py
  python/oneflow/test/modules/test_layernorm.py
Labels: enhancement, automerge, op, need-clean-ccache

#6949 [EP] DeviceManagerFactory
  cmake/oneflow.cmake
  oneflow/core/common/data_type.h
  oneflow/core/common/fp16_data_type.h
  oneflow/core/ep/common/device_manager_registry.cpp
  oneflow/core/ep/cpu/cpu_device_manager_factory.cpp
  oneflow/core/ep/cuda/cuda_device_manager_factory.cpp
  oneflow/core/ep/include/device_manager_factory.h
  oneflow/core/ep/include/device_manager_registry.h
  oneflow/core/framework/device_register_cuda.h
  oneflow/core/framework/device_registry.cpp
  oneflow/core/framework/device_registry.h
  oneflow/core/framework/device_registry_manager.cpp
  oneflow/core/framework/device_registry_manager.h
  oneflow/core/framework/dtype.cpp
  oneflow/core/framework/to_string.cpp
  oneflow/core/graph/op_graph.cpp
  oneflow/core/job/version.cpp
Labels: enhancement, automerge, system, need-clean-ccache

#6969 softmax use pack_offset to fix uncoalesced access for nvcc 11.3
  oneflow/core/cuda/softmax.cuh
  oneflow/user/kernels/fused_scale_mask_softmax.cu
  oneflow/user/kernels/fused_scale_mask_softmax_dropout.cu
  oneflow/user/kernels/fused_tril_scale_softmax_mask_scale_kernel.cu
Labels: enhancement, automerge, op, need-clean-ccache

#6950 add sbp and placement for onerec ops
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/dataset_functor.cpp
  oneflow/user/ops/onerec_decoder_op.cpp
  oneflow/user/ops/onerec_reader_op.cpp
  python/oneflow/framework/docstr/dataset.py
  python/oneflow/test/modules/test_one_rec_ops.py
Labels: enhancement, automerge, op, need-clean-ccache

#6960 fix nvtx thread host name of cpu actor
  oneflow/core/thread/thread.cpp
Labels: automerge, bug, tooling

#6948 Support save/load for lr_scheduler
  python/oneflow/nn/optimizer/lr_scheduler.py
  python/oneflow/test/modules/test_lr_scheduler.py
Labels: feature, automerge, eager

#6973 Fix eye_op attr
  oneflow/user/ops/eye_op.cpp
  python/oneflow/test/graph/test_graph_eye.py
  python/oneflow/test/graph/test_util.py
Labels: automerge, bug, op

#6992 softmax double use uncached impl to accelerate compile
  oneflow/core/cuda/softmax.cuh
Labels: enhancement, automerge, op

#6997 Add [[nodiscard]] for cpp api
  oneflow/api/cpp/framework/device.h
  oneflow/api/cpp/framework/dtype.h
  oneflow/api/cpp/framework/shape.h
  oneflow/api/cpp/framework/tensor.h
Labels: enhancement, automerge, build, serving

#6998 Support Arange delta to decide dtype
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/math_functor.cpp
  python/oneflow/nn/modules/arange.py
  python/oneflow/test/modules/test_arange.py
Labels: enhancement, automerge, op

#6983 Migrate chunk python layer to functor
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/array_functor.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/__init__.py
  python/oneflow/framework/docstr/chunk.py
  python/oneflow/framework/docstr/tensor.py
  python/oneflow/framework/tensor.py
Labels: enhancement, op, need-clean-ccache

#7000 Reduce memory usage when compiling oneflow dialect ops
  oneflow/ir/include/OneFlow/CMakeLists.txt
  oneflow/ir/include/OneFlow/OneFlowOpTraits.h
  oneflow/ir/include/OneFlow/OneFlowOps.h
  oneflow/ir/lib/OneFlow/OneFlowOpGetGen.cpp.in
Labels: enhancement, automerge, ir

#6976 CudaAllocator device reset before OOM
  oneflow/core/vm/cuda_allocator.cpp
Labels: automerge, bug, system

#6989 Refactor vm stream desc
  oneflow/core/eager/critical_section_stream_type.cpp
  oneflow/core/eager/lazy_job_stream_type.cpp
  oneflow/core/vm/async_cuda_stream_type.cpp
  oneflow/core/vm/control_stream_type.cpp
  oneflow/core/vm/cpu_stream_type.cpp
  oneflow/core/vm/cuda_copy_d2h_stream_type.cpp
  oneflow/core/vm/cuda_copy_h2d_stream_type.cpp
  oneflow/core/vm/cuda_stream_type.cpp
  oneflow/core/vm/device_helper_stream_type.cpp
  oneflow/core/vm/host_stream_type.cpp
  oneflow/core/vm/stream_desc.cpp
  oneflow/core/vm/stream_desc.h
  oneflow/core/vm/test_util.cpp
  oneflow/core/vm/transport_stream_type.cpp
Labels: enhancement, automerge, system

#6016 Add Diagonal Op
  docs/source/oneflow.rst
  docs/source/tensor.rst
  oneflow/core/autograd/gradient_funcs/diagonal.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/user/kernels/diagonal_kernel.cpp
  oneflow/user/kernels/diagonal_kernel.cu
  oneflow/user/ops/diagonal_op.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/array_ops.py
  python/oneflow/framework/tensor.py
  python/oneflow/test/modules/test_diagonal.py
Labels: feature, automerge, op

#6283 add all to all op
  docs/source/comm.rst
  python/oneflow/comm/__init__.py
  python/oneflow/comm/comm_ops.py
  python/oneflow/test/modules/test_comm_ops.py
Labels: feature, automerge, eager

#6890 Dev ivalue for cpp api
  oneflow/api/cpp/framework.h
  oneflow/api/cpp/framework/dtype.h
  oneflow/api/cpp/framework/ivalue.cpp
  oneflow/api/cpp/framework/ivalue.h
  oneflow/api/cpp/framework/shape.cpp
  oneflow/api/cpp/framework/shape.h
  oneflow/api/cpp/framework/tensor.cpp
  oneflow/api/cpp/framework/tensor.h
  oneflow/api/cpp/nn.h
  oneflow/api/cpp/nn/functional/activation.h
  oneflow/api/cpp/tests/api_test.cpp
  oneflow/api/cpp/tests/ivalue_test.cpp
Labels: enhancement, feature, automerge, system, serving

#7001 default use cpu generator
  python/oneflow/utils/data/_utils/worker.py
  python/oneflow/utils/data/dataloader.py
  python/oneflow/utils/data/distributed.py
  python/oneflow/utils/data/sampler.py
Labels: bottleneck, automerge, bug, eager, interface

#6956 optimize reshape/slice/transpose functor
  oneflow/core/framework/tensor_methods.cpp
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/user/kernels/transpose_kernel.cpp
Labels: enhancement, automerge, build

#6968 fix IsContinuosSubspace error
  oneflow/core/functional/tensor_index.cpp
  python/oneflow/test/tensor/test_tensor_indexing.py
Labels: enhancement, automerge, bug, build

#7007 Migrate the python layer logic of broadcastlike to functor
  oneflow/core/functional/impl/array_functor.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/__init__.py
  python/oneflow/framework/docstr/broadcast_like.py
Labels: enhancement, automerge, op

#7015 Temporarily skip comm test cases
  python/oneflow/test/modules/test_comm_ops.py
Labels: automerge, bug, op

#7017 Fix nd_sbp attribute type and set nd_sbp in random functors
  oneflow/core/functional/impl/random_functor.cpp
  oneflow/user/ops/distributions/normal_op.cpp
  oneflow/user/ops/distributions/uniform_int_op.cpp
  oneflow/user/ops/distributions/uniform_op.cpp
  oneflow/user/ops/randperm_op.cpp
Labels: automerge, bug, system

#6986 Fix Simple CI linkage
  cmake/oneflow.cmake
Labels: automerge, bug, ci, need-simple-ci

#6984 Fix loss sbp of optional weight
  oneflow/user/ops/binary_cross_entropy_with_logits_op.cpp
  oneflow/user/ops/loss_op_util.cpp
  oneflow/user/ops/loss_op_util.h
  oneflow/user/ops/nll_op.cpp
Labels: enhancement, automerge, op, need-clean-ccache, AutoParallel

#7013 Feat from numpy
  docs/source/oneflow.rst
  oneflow/api/python/functional/tensor_api.cpp
  oneflow/api/python/functional/tensor_api.yaml
  oneflow/core/framework/tensor_methods.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/tensor.py
  python/oneflow/test/modules/test_from_numpy.py
  python/oneflow/test/modules/test_functional_docstr.py
Labels: feature, automerge, eager

#7023 Add custom ShapeAttr in ODS
  ci/test/1node_op_test.sh
  cmake/oneflow.cmake
  oneflow/ir/include/OneFlow/OneFlowBase.td
  oneflow/ir/include/OneFlow/OneFlowOpTraits.h
  oneflow/ir/include/OneFlow/OneFlowOps.td
  oneflow/ir/oneflow-gen-ods/oneflow-gen-ods.cpp
  oneflow/ir/oneflow-translate/include/OneFlow/MLIROneFlowTranslation.h
  oneflow/ir/oneflow-translate/lib/OneFlow/Importer.cpp
  oneflow/ir/oneflow-translate/lib/OneFlow/MLIROneFlowTranslation.cpp
  python/oneflow/compatible/single_client/test/ops/test_multi_process.py
Labels: enhancement, automerge, ir

#7028 Fix Clang none-CUDA build's CMake init cache
  cmake/caches/cn/fast/cuda-61-clang.cmake
  cmake/caches/cn/fast/cuda-75-clang.cmake
Labels: automerge, bug, build

#7006 Add linspace op
  docs/source/oneflow.rst
  oneflow/user/kernels/arange_kernel.cpp
  oneflow/user/ops/arange_op.cpp
  python/oneflow/__init__.py
  python/oneflow/nn/modules/linspace.py
  python/oneflow/test/modules/test_arange.py
  python/oneflow/test/modules/test_linspace.py
Labels: enhancement, feature, automerge, eager, api

#7014 fix fasterrcnn infer
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/unary_functor.cpp
  oneflow/user/kernels/heap_selection_top_k_kernel.cu
  oneflow/user/kernels/math_unary_elementwise_func.h
  oneflow/user/kernels/radix_sort_top_k_kernel.cu
  oneflow/user/kernels/roi_align_kernel.cu
  oneflow/user/kernels/top_k_kernel.cpp
  oneflow/user/ops/math_unary_elementwise_seq.h
  oneflow/user/ops/top_k_op.cpp
  python/oneflow/__init__.py
  python/oneflow/nn/modules/math_ops.py
Labels: enhancement, automerge, eager, op

#7025 Add fully support for all datatype
  oneflow/api/python/framework/dtype.cpp
  oneflow/core/common/data_type.proto
  oneflow/core/framework/dtype.cpp
  oneflow/core/framework/dtype.h
  python/oneflow/compatible/single_client/__init__.py
  python/oneflow/compatible/single_client/framework/dtype.py
Labels: enhancement, feature, automerge, system, need-clean-ccache

#7030 Migrate split python layer to functor
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/__init__.py
  python/oneflow/framework/docstr/split.py
  python/oneflow/framework/docstr/tensor.py
  python/oneflow/framework/tensor.py
  python/oneflow/test/modules/test_split.py
  python/oneflow/test/tensor/test_tensor.py
Labels: enhancement, automerge, op

#7003 Refine RUN_CUDA_KERNEL
  oneflow/core/device/cuda_util.cpp
  oneflow/core/device/cuda_util.h
  oneflow/core/ep/cuda/cuda_stream.cpp
  oneflow/core/ep/cuda/cuda_stream.h
  oneflow/core/job/env_global_objects_scope.cpp
  oneflow/core/ndarray/ndarray_assign_core.cu
  oneflow/core/ndarray/xpu_ndarray_assign.cu
  oneflow/user/kernels/min_max_observer_kernel.cu
  oneflow/user/kernels/moving_average_min_max_observer_kernel.cu
Labels: enhancement, automerge, system, need-clean-ccache

#7004 return_self_in_to_consistent_if_necessary
  oneflow/core/functional/impl/consistent_cast.cpp
  python/oneflow/test/modules/test_eager_boxing.py
Labels: enhancement, automerge, system, need-clean-ccache

#7027 Decouple ep and global
  oneflow/core/ep/common/active_device_guard.cpp
  oneflow/core/ep/common/device_manager_registry.cpp
  oneflow/core/ep/cpu/cpu_device.cpp
  oneflow/core/ep/cpu/cpu_device.h
  oneflow/core/ep/cpu/cpu_device_manager.cpp
  oneflow/core/ep/cpu/cpu_device_manager.h
  oneflow/core/ep/cpu/cpu_device_manager_factory.cpp
  oneflow/core/ep/cuda/cuda_device.cpp
  oneflow/core/ep/cuda/cuda_device.h
  oneflow/core/ep/cuda/cuda_device_manager.cpp
  oneflow/core/ep/cuda/cuda_device_manager.h
  oneflow/core/ep/cuda/cuda_device_manager_factory.cpp
  oneflow/core/ep/cuda/cuda_stream.cpp
  oneflow/core/ep/include/device.h
  oneflow/core/ep/include/device_manager.h
  oneflow/core/ep/include/device_manager_factory.h
  python/oneflow/compatible/single_client/framework/config_util.py
  python/oneflow/framework/config_util.py
Labels: enhancement, automerge, system, need-clean-ccache

#7035 arange doc fix
  python/oneflow/framework/docstr/__init__.py
  python/oneflow/framework/docstr/arange.py
  python/oneflow/nn/modules/arange.py
Labels: automerge, op, documentation

#7002 add_consistency_check_in_consistent_tensor_set_data
  oneflow/core/framework/tensor.cpp
  oneflow/core/framework/tensor.h
Labels: enhancement, automerge, system

#7005 [cmake] add liboneflow_cpp target
  .github/workflows/test.yml
  CMakeLists.txt
  cmake/caches/ci/canary/cuda.cmake
  cmake/caches/ci/cpu.cmake
  cmake/caches/ci/cuda.cmake
  cmake/oneflow-config.cmake
  cmake/oneflow.cmake
  cmake/third_party.cmake
Labels: enhancement, automerge, build, need-simple-ci

#7031 Fix CUDA 52 and add it to CI
  cmake/caches/ci/llvm/cuda-75-clang.cmake
  oneflow/core/kernel/kernel_util.cuh
  oneflow/user/kernels/math_binary_elementwise_func.h
  oneflow/user/kernels/math_unary_elementwise_func.h
Labels: enhancement, automerge, bug, ci, build

#6991 Add check of placement constructor
  oneflow/api/python/framework/op_expr.cpp
  oneflow/api/python/functional/tensor_api.cpp
  oneflow/api/python/symbol/placement_symbol.cpp
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/core/functional/impl/consistent_cast.cpp
  oneflow/core/functional/impl/dataset_functor.cpp
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/core/functional/impl/random_functor.cpp
  oneflow/core/job/parallel_desc.cpp
  oneflow/core/job/parallel_desc.h
Labels: enhancement, automerge, system

#7042 Fix from_numpy in stride
  oneflow/api/python/functional/tensor_api.cpp
  python/oneflow/test/modules/test_from_numpy.py
Labels: automerge, bug, eager

#6999 add non virtual destructor back
  oneflow/core/common/high_order_bool.h
  oneflow/core/framework/user_op_tensor.h
Labels: enhancement, automerge, system

#7036 move python code to cpp: eye
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/eye_functor.cpp
  oneflow/core/functional/impl/math_functor.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/math_ops.py
  python/oneflow/nn/modules/eye.py
Labels: enhancement, automerge, op

#7044 Fix l2norm block_size
  oneflow/core/ep/cuda/cuda_stream.h
  oneflow/user/kernels/l2_normalize_kernel.cu
Labels: automerge, bug, op, need-clean-ccache

#7052 Fix undefined symbol: cudaGetDeviceCount
  cmake/oneflow.cmake
  oneflow/api/python/symbol/placement_symbol.cpp
  oneflow/core/job/parallel_desc.cpp
Labels: automerge, bug, build, system, need-clean-ccache

#7048 fix_worker_orphan_process
  python/oneflow/distributed/launch.py
  python/oneflow/utils/data/_utils/__init__.py
Labels: enhancement, bottleneck, bug, eager, need-clean-ccache

#7056 Auto parallel/complete auto
  oneflow/core/auto_parallel/sbp_constructor.cpp
  oneflow/core/auto_parallel/sbp_graph.h
  oneflow/core/operator/operator.cpp
Labels: AutoParallel

#6939 Quick fix for testing nd sbps
  oneflow/core/auto_parallel/sbp_collector.cpp
  oneflow/core/auto_parallel/sbp_collector.h
  oneflow/core/auto_parallel/sbp_constructor.cpp
  oneflow/core/auto_parallel/sbp_constructor.h
  oneflow/core/auto_parallel/sbp_edge.h
  oneflow/core/auto_parallel/sbp_graph.h
  oneflow/core/auto_parallel/sbp_node.h
  oneflow/core/auto_parallel/sbp_util.cpp
  oneflow/core/auto_parallel/sbp_util.h
  oneflow/core/framework/framework.h
  oneflow/core/framework/get_nd_sbp_signature_list_context.h
  oneflow/core/framework/user_op_registry.cpp
  oneflow/core/framework/user_op_registry.h
  oneflow/core/graph/boxing/hierarchical_sub_task_graph_builder_impl.cpp
  oneflow/core/graph/boxing/hierarchical_sub_task_graph_builder_impl.h
  oneflow/core/job/plan_util.cpp
  oneflow/core/job/sbp_parallel.cpp
  oneflow/core/job/sbp_parallel.h
  oneflow/core/operator/input_op.cpp
  oneflow/core/operator/input_op.h
  oneflow/core/operator/operator.cpp
  oneflow/core/operator/operator.h
  oneflow/core/operator/output_op.cpp
  oneflow/core/operator/output_op.h
  oneflow/core/operator/user_op.cpp
  oneflow/core/operator/user_op.h
  oneflow/core/operator/variable_op.cpp
  oneflow/user/ops/hierarchical_parallel_cast_op.cpp
  oneflow/user/ops/matmul_op.cpp
  oneflow/user/ops/ofrecord_reader_op.cpp
Labels: AutoParallel

#7077 More details of error of getting op matched sbp signature
  oneflow/api/common/sbp.h
  oneflow/api/python/symbol/sbp_symbol.cpp
  oneflow/core/boxing/eager_boxing_interpreter_mgr.cpp
  oneflow/core/framework/nd_sbp.cpp
  oneflow/core/framework/nd_sbp.h
  oneflow/core/framework/nn_graph.cpp
  oneflow/core/framework/op_interpreter/eager_consistent_op_interpreter.cpp
  oneflow/core/framework/placement_sbp_util.cpp
  oneflow/core/graph/boxing/boxing_logger.cpp
  oneflow/core/job/sbp_parallel.cpp
  oneflow/core/job/sbp_parallel.h
  oneflow/core/job_rewriter/insert_nccl_logical_op_pass.cpp
  oneflow/core/operator/operator.cpp
Labels: enhancement, graph

#7055 Module apply only once
  python/oneflow/nn/module.py
  python/oneflow/test/modules/test_module_to.py
  python/oneflow/test/modules/test_module_to_consistent.py
Labels: enhancement, automerge, eager

#7057 distributed test bugfix
  ci/test/2node_op_test_multi_client.sh
  ci/test/distributed_run.py
  python/oneflow/framework/env_util.py
Labels: automerge, bug, ci

#7066 fix promote_type matrix
  oneflow/core/framework/dtype.cpp
Labels: automerge, bug, system

#7073 fix chunk op dim=-1 bug
  oneflow/core/functional/impl/array_functor.cpp
  python/oneflow/framework/docstr/chunk.py
  python/oneflow/test/modules/test_chunk.py
Labels: automerge, bug, op, documentation

#7038 Fix resource desc dump cudnn conf bug
  oneflow/core/framework/tensor.cpp
  oneflow/core/framework/tensor_rpc_util.cpp
  oneflow/core/framework/tensor_rpc_util.h
  oneflow/core/job/resource_desc.cpp
Labels: automerge, bug, system, need-clean-ccache

#7075 fix concat bug
  oneflow/core/autograd/gradient_funcs/concat.cpp
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/user/ops/concat_op.cpp
  python/oneflow/test/modules/test_concat.py
Labels: enhancement, automerge, bug, eager

#7076 Clean TensorNameScope after graph build
  oneflow/core/framework/nn_graph.cpp
  oneflow/core/framework/tensor_name_scope.cpp
  oneflow/core/framework/tensor_name_scope.h
  python/oneflow/test/graph/test_graph_free_eager_tensor.py
Labels: automerge, bug, graph

#7099 fix_abnormal_printing
  python/oneflow/distributed/launch.py
Labels: enhancement, bottleneck, automerge, bug, eager

#7081 Fix bias add dropout fuse
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/user/ops/fused_bias_add_op.cpp
  python/oneflow/test/modules/test_fused_bias_add_dropout.py
Labels: enhancement, automerge, op

#7083 Support 1d to 2d eager boxing
  oneflow/core/boxing/boxing_dividor_util.cpp
  oneflow/core/boxing/boxing_dividor_util.h
  oneflow/core/boxing/eager_boxing_interpreter_mgr.cpp
  oneflow/core/boxing/unflatten_hierarchy.cpp
  python/oneflow/test/modules/test_eager_boxing.py
Labels: enhancement, automerge, system

#7054 Feat/debug pass
  oneflow/core/job/job_build_and_infer_ctx.cpp
  oneflow/core/job_rewriter/fuse_add_to_output_pass.cpp
Labels: feature, automerge, tooling, graph

#6930 Fix error message
  oneflow/core/autograd/gradient_funcs/dot.cpp
  oneflow/user/kernels/dot_kernel.cpp
  oneflow/user/ops/dot_op.cpp
  python/oneflow/framework/docstr/math_ops.py
Labels: enhancement, automerge, system

#7105 fix simple ci: add of_op_schema target to tidy check
  .github/workflows/simple.yml
Labels: automerge, bug, ci

#7109 Rename AnyType in .td
  oneflow/ir/include/OneFlow/OneFlowBase.td
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
Labels: enhancement, automerge, ir

#7080 Feat graph reuse var
  python/oneflow/nn/graph/block.py
  python/oneflow/nn/graph/graph.py
  python/oneflow/nn/graph/optimizer.py
  python/oneflow/nn/optimizer/optimizer.py
  python/oneflow/test/graph/test_graph_optimizer.py
  python/oneflow/test/graph/test_graph_reuse_var.py
Labels: enhancement, feature, automerge, bug, graph

#6940 Fix l2_normalize & add nn.functional.normalize
  docs/source/functional.rst
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  python/oneflow/framework/docstr/norm.py
  python/oneflow/nn/functional/__init__.py
  python/oneflow/nn/modules/norm.py
  python/oneflow/test/modules/test_normalize.py
Labels: enhancement, feature, bug, op

#7058 Align api in swin transformer
  oneflow/api/python/functional/py_function.cpp
  oneflow/core/functional/functional_api.yaml
  python/oneflow/__init__.py
  python/oneflow/framework/tensor.py
  python/oneflow/nn/modules/meshgrid.py
  python/oneflow/test/modules/test_meshgrid.py
  python/oneflow/test/tensor/test_tensor.py
Labels: enhancement, feature, automerge, bug, eager

#7063 set CMAKE_LINK_DEPENDS_NO_SHARED to YES in fast cmake init cache
  cmake/caches/cn/fast/cpu-clang.cmake
  cmake/caches/cn/fast/cpu.cmake
  cmake/caches/cn/fast/cuda-61-clang.cmake
  cmake/caches/cn/fast/cuda-61.cmake
  cmake/caches/cn/fast/cuda-75-clang.cmake
  cmake/caches/cn/fast/cuda-75.cmake
  cmake/caches/cn/fast/mlir-cuda-61.cmake
  cmake/caches/cn/fast/mlir-cuda-75.cmake
Labels: enhancement, automerge, build

#7091 Add other api graph autotest
  python/oneflow/test/modules/test_abs.py
  python/oneflow/test/modules/test_activation.py
  python/oneflow/test/modules/test_add.py
  python/oneflow/test/modules/test_addmm.py
  python/oneflow/test/modules/test_affine_grid.py
  python/oneflow/test/modules/test_arange.py
  python/oneflow/test/modules/test_argmax.py
  python/oneflow/test/modules/test_autograd.py
  python/oneflow/test/modules/test_constant.py
  python/oneflow/test/modules/test_constantpad.py
  python/oneflow/test/modules/test_diag.py
  python/oneflow/test/modules/test_dot.py
  python/oneflow/test/modules/test_erf.py
  python/oneflow/test/modules/test_erfc.py
  python/oneflow/test/modules/test_expand.py
  python/oneflow/test/modules/test_flatten.py
  python/oneflow/test/modules/test_flip.py
  python/oneflow/test/modules/test_gather.py
  python/oneflow/test/modules/test_glu.py
  python/oneflow/test/modules/test_groupnorm.py
  python/oneflow/test/modules/test_linear.py
  python/oneflow/test/modules/test_linspace.py
  python/oneflow/test/modules/test_log1p.py
  python/oneflow/test/modules/test_logical_and.py
  python/oneflow/test/modules/test_logical_not.py
  python/oneflow/test/modules/test_logical_or.py
  python/oneflow/test/modules/test_logical_xor.py
  python/oneflow/test/modules/test_masked_fill.py
  python/oneflow/test/modules/test_matmul.py
  python/oneflow/test/modules/test_maxpool.py
  python/oneflow/test/modules/test_mean.py
  python/oneflow/test/modules/test_norm.py
  python/oneflow/test/modules/test_permute.py
  python/oneflow/test/modules/test_prod.py
  python/oneflow/test/modules/test_randperm.py
  python/oneflow/test/modules/test_reciprocal.py
  python/oneflow/test/modules/test_repeat.py
  python/oneflow/test/modules/test_round.py
  python/oneflow/test/modules/test_sign.py
  python/oneflow/test/modules/test_squeeze.py
  python/oneflow/test/modules/test_stack.py
  python/oneflow/test/modules/test_std.py
  python/oneflow/test/modules/test_tile.py
  python/oneflow/test/modules/test_tril.py
  python/oneflow/test/modules/test_unfold_tensor.py
  python/oneflow/test/modules/test_unsqueeze.py
  python/oneflow/test/modules/test_var.py
  python/oneflow/test/modules/test_where.py
  python/oneflow/test/tensor/test_parameter.py
  python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py
Labels: enhancement, feature, automerge, test, graph

#7070 disable autograd in lazy mode
  oneflow/core/framework/op_interpreter/op_interpreter.cpp
Labels: enhancement, automerge, system

#7092 Fix/rand source op in graph
  oneflow/core/framework/user_op_registry.cpp
  oneflow/user/ops/distributions/uniform_int_op.cpp
  python/oneflow/test/modules/test_randint.py
Labels: automerge, bug, eager, op, graph

#7106 Fix powf
  oneflow/core/ndarray/binary_func.h
  python/oneflow/test/modules/test_math_ops.py
Labels: enhancement, automerge, bug, op

#7046 Dispatch stateful ops using functional api
  cmake/functional.cmake
  cmake/oneflow.cmake
  oneflow/api/python/framework/op_expr.cpp
  oneflow/api/python/functional/common.cpp
  oneflow/api/python/functional/common.h
  oneflow/api/python/functional/dispatch_stateful_ops.cpp
  oneflow/api/python/functional/dispatch_stateful_ops.yaml
  oneflow/api/python/functional/python_arg.cpp
  oneflow/api/python/functional/value_types.cpp
  oneflow/api/python/functional/value_types.h
  oneflow/core/framework/attr_value_accessor.cpp
  oneflow/core/framework/op_expr.cpp
  oneflow/core/functional/function_library.h
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/array_functor.cpp
  python/oneflow/__init__.py
  python/oneflow/compatible/single_client/__init__.py
  python/oneflow/compatible/single_client/framework/op_expr_util.py
  python/oneflow/compatible/single_client/framework/register_class_method_util.py
  python/oneflow/compatible/single_client/nn/optimizer/adam.py
  python/oneflow/compatible/single_client/nn/optimizer/adamw.py
  python/oneflow/compatible/single_client/nn/optimizer/rmsprop.py
  python/oneflow/compatible/single_client/nn/optimizer/sgd.py
  python/oneflow/compatible/single_client/ops/stateful_ops.py
  python/oneflow/framework/graph_build_util.py
  python/oneflow/framework/op_expr_util.py
  python/oneflow/framework/register_class_method_util.py
  python/oneflow/nn/modules/all_reduce.py
  python/oneflow/nn/modules/dataset.py
  python/oneflow/nn/modules/in_top_k.py
  python/oneflow/nn/modules/math_ops.py
  python/oneflow/nn/modules/tensor_buffer.py
  python/oneflow/nn/optimizer/adagrad.py
  python/oneflow/nn/optimizer/adam.py
  python/oneflow/nn/optimizer/adamw.py
  python/oneflow/nn/optimizer/rmsprop.py
  python/oneflow/nn/optimizer/sgd.py
  python/oneflow/nn/parallel/ddp.py
  python/oneflow/ops/stateful_ops.py
  python/oneflow/test/graph/test_input_op_expr.py
  python/oneflow/test/graph/test_output_op_expr.py
  python/oneflow/test/graph/test_user_op_expr.py
  python/oneflow/test/graph/test_variable_op_expr.py
  python/oneflow/test/modules/resnet50_model.py
  python/oneflow/test/modules/test_stateful_local_opkernel.py
  python/oneflow/test/tensor/test_tensor.py
  tools/functional/generate_dispatch_stateful_ops.py
  tools/functional/generator.py
Labels: enhancement, automerge, system, refactor, need-clean-ccache

#7115 Fix HWLoc memory affinity
  oneflow/core/hardware/node_device_descriptor.cpp
Labels: automerge, bug, system, need-clean-ccache

#7100 add_env_api_docs
  docs/source/env.rst
  docs/source/index.rst
  docs/source/oneflow.rst
  python/oneflow/env.py
Labels: automerge, documentation, system, need-clean-ccache

#7065 tmp skip s0 print because of slice
  python/oneflow/framework/tensor_str.py
  python/oneflow/test/modules/test_tensor_str.py
Labels: automerge, bug, eager, need-clean-ccache

#7125 fix maybe: add Maybe(T&&) to allow constructing from rvalue T
  oneflow/core/common/maybe.h
  oneflow/core/common/maybe_test.cpp
Labels: enhancement, automerge, system

#7126 autotest_add_graph_log
  python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py
Labels: enhancement, automerge, eager, graph

#7085 Meta info consistency check
  oneflow/api/python/utils/tensor_utils.cpp
  oneflow/core/autograd/gradient_funcs/consistent_cast.cpp
  oneflow/core/framework/consistency_check.cpp
  oneflow/core/framework/consistency_check.h
  oneflow/core/framework/data_consistency_check.cpp
  oneflow/core/framework/data_consistency_check.h
  oneflow/core/framework/op_interpreter/eager_consistent_op_interpreter.cpp
  oneflow/core/framework/op_interpreter/lazy_op_interpreter.cpp
  oneflow/core/functional/impl/consistent_cast.cpp
Labels: enhancement, automerge, system, need-clean-ccache

#7128 cmake: use interface target instead of include_directories in pybind11
  cmake/oneflow.cmake
  cmake/pybind11.cmake
Labels: enhancement, automerge, build

#7124 Import cmake dependence json and inja using FetchContent
  CMakeLists.txt
  cmake/third_party.cmake
  cmake/third_party/json.cmake
  cmake/util.cmake
  oneflow/core/hardware/cuda_device_descriptor.cpp
  oneflow/core/hardware/cuda_device_descriptor_class.cpp
  oneflow/core/hardware/net_ib_device_descriptor.cpp
  oneflow/core/hardware/net_ib_device_descriptor_class.cpp
  oneflow/core/hardware/net_socket_device_descriptor.cpp
  oneflow/core/hardware/net_socket_device_descriptor_class.cpp
  oneflow/core/hardware/node_device_descriptor.cpp
  oneflow/core/job/job_build_and_infer_ctx.cpp
  oneflow/core/job/job_build_and_infer_ctx_mgr.cpp
  oneflow/ir/install-llvm.cmake
  oneflow/user/data/coco_data_reader.h
  oneflow/user/summary/summary_converter.h
  tools/oneflow-tblgen/CMakeLists.txt
  tools/oneflow-tblgen/op_schema_emitter.cpp
Labels: enhancement, automerge, build

#7130 Add environment variable to set GRPC_ARG_MAX_MESSAGE_LENGTH
  oneflow/core/control/ctrl_service.cpp
Labels: enhancement, automerge, system

#6811 Fea/nhwc
  oneflow/core/autograd/gradient_funcs/deconv.cpp
  oneflow/core/framework/op_interpreter/lazy_op_interpreter.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  python/oneflow/framework/docstr/conv.py
  python/oneflow/nn/init.py
  python/oneflow/nn/modules/batchnorm.py
  python/oneflow/nn/modules/batchnorm_fused.py
  python/oneflow/nn/modules/conv.py
  python/oneflow/nn/modules/dataset.py
  python/oneflow/nn/modules/pooling.py
Labels: feature, automerge, op, interface

#7144 reduce memory usage due to slice grad
  oneflow/core/autograd/gradient_funcs/slice.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/ops/slice_op.cpp
Labels: enhancement, automerge, op, system

#7146 cmake: fix THIRD_PARTY build
  cmake/third_party/json.cmake
Labels: automerge, bug, build

#7156 Dev fix fold op
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
Labels: enhancement, automerge, bug, system

#7112 Support inplace for lazy consistent
  oneflow/api/python/job_build/job_build_and_infer.cpp
  oneflow/api/python/job_build/job_build_and_infer.h
  oneflow/api/python/job_build/job_build_and_infer_api.h
  oneflow/core/framework/op_interpreter/lazy_op_interpreter.cpp
  oneflow/core/job/job_build_and_infer_ctx.cpp
  oneflow/core/job/job_build_and_infer_ctx.h
  python/oneflow/test/graph/test_graph_inplace_add.py
Labels: enhancement, automerge, system, graph

#7118 fix prelu bug
  oneflow/core/functional/impl/activation_functor.cpp
  oneflow/user/kernels/prelu_kernel.cpp
  oneflow/user/kernels/prelu_kernel.cu
  python/oneflow/nn/modules/activation.py
Labels: enhancement, bug, op

#7155 Fix error message when couldn't find matched SBP inferring
  oneflow/core/operator/operator.cpp
Labels: automerge, bug, system

#7159 fix copy bug
  oneflow/user/ops/copy_op.cpp
  python/oneflow/test/modules/test_tensor_to.py
Labels: automerge, bug, system

#7164 Fix laynorm backward bug
  oneflow/core/autograd/gradient_funcs/layer_norm.cpp
  python/oneflow/test/modules/test_layernorm.py
Labels: automerge, bug, system

#6957 [Fix] graph support 0-Size tensor
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/core/job/plan_util.cpp
  oneflow/core/operator/interface_op_util.cpp
  python/oneflow/test/modules/test_abs.py
  python/oneflow/test/modules/test_activation.py
  python/oneflow/test/modules/test_add.py
  python/oneflow/test/modules/test_cast.py
  python/oneflow/test/modules/test_ceil.py
  python/oneflow/test/modules/test_clamp.py
  python/oneflow/test/modules/test_concat.py
  python/oneflow/test/modules/test_div.py
  python/oneflow/test/modules/test_eq.py
  python/oneflow/test/modules/test_expm1.py
  python/oneflow/test/modules/test_fmod.py
  python/oneflow/test/modules/test_greater.py
  python/oneflow/test/modules/test_ne.py
  python/oneflow/test/modules/test_negative.py
  python/oneflow/test/modules/test_reshape.py
  python/oneflow/test/modules/test_sign.py
  python/oneflow/test/modules/test_squeeze.py
  python/oneflow/test/modules/test_sub.py
  python/oneflow/test/modules/test_sum.py
  python/oneflow/test/modules/test_transpose.py
  python/oneflow/test/modules/test_triu.py
  python/oneflow/test/modules/test_unsqueeze.py
  python/oneflow/test/modules/test_var.py
  python/oneflow/test/tensor/test_tensor.py
  python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py
Labels: enhancement, automerge, system
