Repository Oneflow-Inc/oneflow, pull requests merged in 2021-06, with the labels that each got.

#5055 Restore eager R50
  oneflow/python/test/modules/test_resnet50_with_bn.py
  oneflow/python/test/modules/test_resnet50_without_bn.py
Labels: automerge, ci, enhancement

#5049 Add argmax softplus logsigmoid module backward
  oneflow/python/test/modules/test_activation.py
  oneflow/python/test/modules/test_argmax.py
Labels: automerge, eager, enhancement, python

#5046 add doctest
  oneflow/python/nn/modules/arange.py
  oneflow/python/nn/modules/batchnorm.py
  oneflow/python/nn/modules/cast.py
  oneflow/python/nn/modules/constant.py
  oneflow/python/nn/modules/dropout.py
  oneflow/python/nn/modules/eq.py
  oneflow/python/nn/modules/gather.py
  oneflow/python/nn/modules/linear.py
  oneflow/python/nn/modules/masked_fill.py
  oneflow/python/nn/modules/matmul.py
  oneflow/python/nn/modules/normalization.py
Labels: automerge, eager, enhancement, test

#5024 refactor DType
  oneflow/api/python/deprecated.cpp
  oneflow/api/python/framework/dtype.cpp
  oneflow/api/python/framework/tensor.cpp
  oneflow/core/autograd/autograd_meta.cpp
  oneflow/core/autograd/autograd_meta.h
  oneflow/core/autograd/gradient_funcs/cast.cpp
  oneflow/core/autograd/gradient_funcs/normalization.cpp
  oneflow/core/framework/dtype.cpp
  oneflow/core/framework/dtype.h
  oneflow/core/framework/op_interpreter/op_interpreter_util.cpp
  oneflow/core/framework/tensor.cpp
  oneflow/core/framework/tensor.h
  oneflow/core/framework/tensor_impl.cpp
  oneflow/core/framework/tensor_impl.h
Labels: automerge, enhancement, system

#5061 remove try_init_default_session in new save/load interface
  oneflow/python/framework/check_point_v2.py
Labels: automerge, bug, python

#5012 Rewrite batch broadcast matmul backward
  oneflow/core/autograd/gradient_funcs/matmul.cpp
  oneflow/core/framework/op_expr_helper.cpp
  oneflow/core/framework/op_expr_helper.h
  oneflow/python/test/modules/test_matmul.py
Labels: automerge, eager, enhancement, test

#5057 Lock cmake version in manylinux dockerfile
  docker/package/manylinux/Dockerfile
Labels: automerge, build, ci, enhancement

#4973 Doctest support in CI
  .github/workflows/test.yml
  ci/test/doctest.sh
  ci/test/parallel_run.py
  oneflow/init.py
  oneflow/python/nn/modules/activation.py
  oneflow/python/nn/modules/container.py
Labels: automerge, documentation, python

#4965 Update README for 0.4.0
  README.md
Labels: automerge, documentation, system

#5063 Add step lr and lambda lr
  docs/source/optim.rst
  oneflow/python/nn/optimizer/cosine_scheduler.py
  oneflow/python/nn/optimizer/lambda_lr.py
  oneflow/python/nn/optimizer/lr_scheduler.py
  oneflow/python/nn/optimizer/step_lr.py
  oneflow/python/test/modules/test_lr_scheduler.py
Labels: automerge, documentation, eager, feature

#5060 Release cuda 112
  .github/workflows/release.yml
Labels: automerge, ci, enhancement

#4955 add flow.asin, flow.Tensor.asin, flow.arcsin, flow.Tensor.arcsin, flow.asinh, flow.Tensor.asinh, flow.arcsinh, flow.Tensor.arcsinh
  docs/source/experimental.rst
  oneflow/python/nn/modules/math_ops.py
  oneflow/python/test/modules/test_asin.py
  oneflow/python/test/modules/test_asinh.py
  oneflow/python/test/tensor/test_tensor.py
Labels: api, automerge, enhancement, op

#5058 Add modules doctest bbuf
  oneflow/python/nn/modules/activation.py
  oneflow/python/nn/modules/argmax.py
  oneflow/python/nn/modules/concat.py
  oneflow/python/nn/modules/exp.py
  oneflow/python/nn/modules/expand.py
  oneflow/python/nn/modules/greater.py
  oneflow/python/nn/modules/less.py
  oneflow/python/nn/modules/linear.py
  oneflow/python/nn/modules/loss.py
  oneflow/python/nn/modules/matmul.py
  oneflow/python/nn/modules/negative.py
  oneflow/python/nn/modules/permute.py
  oneflow/python/nn/modules/prelu.py
  oneflow/python/nn/modules/repeat.py
  oneflow/python/nn/modules/reshape.py
  oneflow/python/nn/modules/squeeze.py
  oneflow/python/nn/modules/transpose.py
  oneflow/python/nn/modules/upsample.py
  oneflow/python/nn/modules/where.py
Labels: automerge, documentation, eager, python, test

#5068 Add tensor detach python api
  oneflow/python/test/tensor/test_tensor.py
Labels: automerge, documentation, eager, python

#5066 Remove redundant copyright header
  oneflow/core/graph/stream_index_getter_registry.cpp
  oneflow/core/graph/stream_index_getter_registry.h
  oneflow/core/graph/stream_index_getter_registry_manager.cpp
  oneflow/core/graph/stream_index_getter_registry_manager.h
Labels: automerge, bug, system

#5076 Fix scalar_div_by_tensor grad.
  oneflow/core/autograd/gradient_funcs/tensor_scalar_binary.cpp
  oneflow/core/framework/op_expr_helper.cpp
Labels: automerge, bug, system

#5070 fix warning about np.arcsin
  oneflow/python/nn/modules/math_ops.py
  oneflow/python/test/tensor/test_tensor.py
Labels: api, automerge, enhancement, op

#5078 wrap Receive by WithScopedRelease, only release/acquire gil when necessary
  oneflow/api/python/gil_foreign_lock_helper.cpp
  oneflow/core/vm/virtual_machine.cpp
Labels: automerge, bug, python

#5067 Add nllloss crossentroppy loss backward
  oneflow/python/nn/modules/loss.py
  oneflow/python/test/modules/test_crossentropyloss.py
  oneflow/python/test/modules/test_crossentropyloss_grad.py
  oneflow/python/test/modules/test_nllloss.py
  oneflow/python/test/modules/test_nllloss_grad.py
Labels: automerge, eager, feature, op, python

#4952 add math.abs (module)
  oneflow/core/graph/stream_index_getter_registry.cpp
  oneflow/core/graph/stream_index_getter_registry.h
  oneflow/core/graph/stream_index_getter_registry_manager.cpp
  oneflow/core/graph/stream_index_getter_registry_manager.h
  oneflow/python/nn/modules/abs.py
  oneflow/python/ops/math_unary_elementwise_ops.py
  oneflow/python/test/modules/test_abs.py
  oneflow/python/test/modules/test_math_ops.py
Labels: api, automerge, eager, enhancement, feature, op

#5082 Refine module backward tests
  oneflow/python/test/modules/test_add.py
  oneflow/python/test/modules/test_batchnorm.py
  oneflow/python/test/modules/test_broadcast_like.py
  oneflow/python/test/modules/test_cast.py
  oneflow/python/test/modules/test_constant.py
  oneflow/python/test/modules/test_flatten.py
  oneflow/python/test/tensor/test_tensor.py
Labels: automerge, eager, enhancement, test

#4987 Add acosh, sin and sign
  docs/source/experimental.rst
  oneflow/python/nn/modules/acosh.py
  oneflow/python/nn/modules/math_ops.py
  oneflow/python/nn/modules/sign.py
  oneflow/python/test/modules/test_acosh.py
  oneflow/python/test/modules/test_sign.py
Labels: automerge, enhancement, python

#5006 Add log1p module
  docs/source/experimental.rst
  oneflow/python/nn/modules/log1p.py
  oneflow/python/test/modules/test_log1p.py
Labels: automerge, enhancement, op, test

#4991 [Add] atan2 sinh softplus
  docs/source/experimental.rst
  oneflow/python/nn/modules/atan2.py
  oneflow/python/nn/modules/sinh.py
  oneflow/python/nn/modules/softplus.py
  oneflow/python/test/modules/test_atan2.py
  oneflow/python/test/modules/test_sinh.py
  oneflow/python/test/modules/test_softplus.py
Labels: automerge, enhancement, python

#5085 fix test_asin.py warining by limiting input in [-1,1]
  oneflow/python/test/modules/test_asin.py
  oneflow/python/test/modules/test_asinh.py
  oneflow/python/test/modules/test_math_ops.py
Labels: api, automerge, enhancement, op

#5021 dev maxpool module
  docs/source/experimental.rst
  oneflow/core/autograd/gradient_funcs/pool.cpp
  oneflow/core/framework/op_expr_helper.cpp
  oneflow/core/framework/op_expr_helper.h
  oneflow/python/nn/modules/pooling.py
  oneflow/python/test/modules/test_maxpool.py
  oneflow/python/test/modules/test_pooling.py
Labels: api, automerge, eager, feature, op

#5091 CI checks if license duplicated
  ci/check/run_license_format.py
  oneflow/core/graph/stream_index_getter_registry.cpp
  oneflow/core/graph/stream_index_getter_registry.h
  oneflow/core/graph/stream_index_getter_registry_manager.cpp
  oneflow/core/graph/stream_index_getter_registry_manager.h
  oneflow/python/nn/modules/dataset.py
  oneflow/python/test/modules/test_dropout.py
  oneflow/python/test/ops/test_logsoftmax.py
  oneflow/user/kernels/pad2d_kernels.cpp
Labels: automerge, ci, enhancement

#5092 add round module
  docs/source/experimental.rst
  oneflow/python/nn/modules/round.py
  oneflow/python/test/modules/test_round.py
  oneflow/python/test/tensor/test_tensor.py
Labels: automerge, documentation, eager, enhancement, feature, python

#5075 Fix module test bug
  oneflow/python/test/modules/test_div.py
  oneflow/python/test/modules/test_eq.py
  oneflow/python/test/modules/test_exp.py
  oneflow/python/test/modules/test_linear.py
  oneflow/python/test/tensor/test_tensor.py
Labels: automerge, bug, documentation, eager, enhancement, feature, python

#5088 Refine module backward tests 2
  oneflow/python/nn/modules/masked_fill.py
  oneflow/python/test/modules/test_gather.py
  oneflow/python/test/modules/test_masked_fill.py
  oneflow/python/test/modules/test_math_ops.py
  oneflow/python/test/modules/test_mean.py
  oneflow/python/test/modules/test_module_to.py
  oneflow/python/test/modules/test_normalization.py
  oneflow/python/test/modules/test_slice.py
  oneflow/python/test/tensor/test_tensor.py
Labels: automerge, eager, enhancement, test

#5079 Rewrite module backward bbuf 1
  oneflow/python/test/modules/test_mul.py
  oneflow/python/test/modules/test_ones_like.py
  oneflow/python/test/modules/test_reciprocal.py
  oneflow/python/test/modules/test_sparse.py
  oneflow/python/test/modules/test_sub.py
  oneflow/python/test/modules/test_sum.py
  oneflow/python/test/modules/test_tensor_to.py
Labels: automerge, eager, enhancement, test

#5094 Skip multi card eager
  ci/test/1node_test.sh
Labels: automerge, ci, enhancement

#5093 fix conv impl bug
  oneflow/python/nn/modules/conv.py
  oneflow/python/test/modules/test_conv.py
Labels: automerge, bug, eager, op, python

#5083 Fix tensor.detach
  oneflow/core/framework/op_expr_grad_function.h
  oneflow/core/framework/tensor.cpp
  oneflow/core/framework/tensor.h
  oneflow/core/framework/tensor_impl.cpp
  oneflow/core/framework/tensor_impl.h
  oneflow/python/test/tensor/test_tensor.py
Labels: automerge, bug, system

#5097 Add slice 4dim test case
  oneflow/python/test/modules/test_slice.py
Labels: automerge, eager, enhancement, test

#5100 Fix doctest not raising when failed
  ci/check/run_license_format.py
  oneflow/python/nn/modules/abs.py
  oneflow/python/nn/modules/acosh.py
  oneflow/python/nn/modules/activation.py
  oneflow/python/nn/modules/arange.py
  oneflow/python/nn/modules/argmax.py
  oneflow/python/nn/modules/atan2.py
  oneflow/python/nn/modules/batchnorm.py
  oneflow/python/nn/modules/cast.py
  oneflow/python/nn/modules/concat.py
  oneflow/python/nn/modules/constant.py
  oneflow/python/nn/modules/container.py
  oneflow/python/nn/modules/dropout.py
  oneflow/python/nn/modules/eq.py
  oneflow/python/nn/modules/exp.py
  oneflow/python/nn/modules/expand.py
  oneflow/python/nn/modules/gather.py
  oneflow/python/nn/modules/greater.py
  oneflow/python/nn/modules/less.py
  oneflow/python/nn/modules/linear.py
  oneflow/python/nn/modules/log1p.py
  oneflow/python/nn/modules/loss.py
  oneflow/python/nn/modules/masked_fill.py
  oneflow/python/nn/modules/math_ops.py
  oneflow/python/nn/modules/matmul.py
  oneflow/python/nn/modules/negative.py
  oneflow/python/nn/modules/normalization.py
  oneflow/python/nn/modules/permute.py
  oneflow/python/nn/modules/pooling.py
  oneflow/python/nn/modules/prelu.py
  oneflow/python/nn/modules/repeat.py
  oneflow/python/nn/modules/reshape.py
  oneflow/python/nn/modules/round.py
  oneflow/python/nn/modules/sign.py
  oneflow/python/nn/modules/sinh.py
  oneflow/python/nn/modules/softplus.py
  oneflow/python/nn/modules/squeeze.py
  oneflow/python/nn/modules/transpose.py
  oneflow/python/nn/modules/upsample.py
  oneflow/python/nn/modules/where.py
Labels: automerge, ci, enhancement

#5099 rewrite scalar_pow backward
  oneflow/core/autograd/gradient_funcs/scalar_pow.cpp
  oneflow/core/framework/op_expr_helper.cpp
  oneflow/core/framework/op_expr_helper.h
  oneflow/python/test/modules/test_math_ops.py
Labels: automerge, eager, enhancement, test

#5096 Don't upload bin in release because oneflow_worker has been removed
  .github/workflows/release.yml
  .github/workflows/test.yml
Labels: automerge, ci, enhancement

#4960 init atanh
  docs/source/experimental.rst
  oneflow/python/nn/modules/atanh.py
  oneflow/python/nn/modules/tan.py
  oneflow/python/test/modules/test_atanh.py
  oneflow/python/test/modules/test_tan.py
  oneflow/python/test/tensor/test_tensor.py
Labels: api, automerge, enhancement, feature, op

#5102 skip quantize op test for now
  oneflow/python/test/ops/test_quantize_op.py
Labels: automerge, bug, test

#5104 Fix atanh ci bug
  oneflow/python/test/modules/test_atanh.py
  oneflow/python/test/modules/test_tan.py
  oneflow/python/test/tensor/test_tensor.py
Labels: automerge, bug, eager, python, test

#5105 rewrite gather op backward
  oneflow/core/autograd/gradient_funcs/gather.cpp
  oneflow/core/framework/op_expr_helper.cpp
  oneflow/core/framework/op_expr_helper.h
Labels: automerge, eager, enhancement, test

#5103 Treat warning in docs as error when building docs
  .github/workflows/test.yml
  ci/test/build_docs.sh
  docker/ci/test/Dockerfile
  docker/ci/test/build.sh
  docker/ci/test/requirements.txt
  docs/requirements.txt
  docs/source/_static/.gitkeep
  docs/source/conf.py
  oneflow/python/nn/modules/atanh.py
  oneflow/python/nn/modules/conv.py
  oneflow/python/nn/modules/dropout.py
  oneflow/python/nn/modules/expand.py
  oneflow/python/nn/modules/gather.py
  oneflow/python/nn/modules/linear.py
  oneflow/python/nn/modules/math_ops.py
  oneflow/python/nn/modules/normalization.py
  oneflow/python/nn/modules/pooling.py
  oneflow/python/nn/modules/sparse.py
  oneflow/python/nn/modules/tan.py
  oneflow/python/nn/modules/to.py
  oneflow/python/nn/modules/where.py
  oneflow/python/ops/nn_ops.py
  oneflow/python/ops/tensor_buffer_ops.py
Labels: automerge, ci, enhancement

#5106 rewrite constant module
  oneflow/python/nn/modules/constant.py
  oneflow/python/test/modules/test_constant.py
Labels: automerge, eager, enhancement, test

#5109 Try to fix readthedocs build fail
  oneflow/python/nn/modules/activation.py
Labels: api, automerge, bug, build, documentation, test

#5108 Fix doctest for modules
  oneflow/python/nn/modules/activation.py
  oneflow/python/nn/modules/argwhere.py
  oneflow/python/nn/modules/conv.py
  oneflow/python/nn/modules/dropout.py
  oneflow/python/nn/modules/exp.py
  oneflow/python/nn/modules/flatten.py
  oneflow/python/nn/modules/normalization.py
  oneflow/python/nn/modules/slice.py
  oneflow/python/nn/modules/sparse.py
  oneflow/python/nn/modules/to.py
  oneflow/python/nn/modules/unsqueeze.py
Labels: api, automerge, documentation, eager, python, test

#4946 Add clamp&clip module
  docs/source/experimental.rst
  oneflow/python/nn/modules/math_ops.py
  oneflow/python/ops/math_ops.py
  oneflow/python/test/modules/test_clamp.py
  oneflow/python/test/tensor/test_tensor.py
Labels: api, automerge, documentation, eager, python

#5111 Update readme on how to build
  README.md
  cmake/oneflow.cmake
Labels: automerge, build, documentation

#5098 Refactor infer ctx shape for kernel
  oneflow/user/kernels/arg_sort_kernel.cu
  oneflow/user/kernels/arg_where_kernel.cpp
  oneflow/user/kernels/argmax_kernel.cu
  oneflow/user/kernels/ctc_loss_kernel.cpp
  oneflow/user/kernels/fused_self_attention_query_mul_key_and_value_kernel.cu
  oneflow/user/kernels/generate_random_batch_permutation_indices_kernel.cu
  oneflow/user/kernels/min_max_observer_kernel.cu
  oneflow/user/kernels/prelu_kernel.cpp
  oneflow/user/kernels/prelu_kernel.cu
  oneflow/user/kernels/radix_sort_top_k_kernel.cu
  oneflow/user/kernels/reduce_kernel.cpp
  oneflow/user/kernels/softmax_cross_entropy_kernel.h
  oneflow/user/kernels/softmax_kernel.cpp
  oneflow/user/kernels/sort_kernel.cu
  oneflow/user/kernels/sparse_softmax_cross_entropy_kernel.cpp
  oneflow/user/kernels/top_k_kernel.cpp
  oneflow/user/kernels/two_stage_reduce_kernel.cpp
Labels: automerge, enhancement, system

#5114 Fix docstring warning
  docs/source/experimental.rst
  oneflow/python/test/modules/test_math_ops.py
  oneflow/python/test/tensor/test_tensor.py
Labels: automerge, bug, documentation, eager, feature

#5123 modify OutputShape in infer_ctx to be const function
  oneflow/core/framework/infer_util.h
  oneflow/core/kernel/user_kernel.cpp
  oneflow/core/operator/user_op.cpp
  oneflow/user/kernels/stateful_local_opkernel.h
Labels: automerge, enhancement, system

#5126 Fix tensor greater less bug
  oneflow/python/nn/modules/greater.py
  oneflow/python/nn/modules/less.py
  oneflow/python/test/modules/test_greater.py
  oneflow/python/test/modules/test_less.py
Labels: automerge, bug, eager, interface, op, python

#4956 add atan atan-tensor arctan arctan-tensor
  docs/source/experimental.rst
  oneflow/python/nn/modules/math_ops.py
  oneflow/python/test/modules/test_atan.py
  oneflow/python/test/tensor/test_tensor.py
Labels: api, automerge, feature, interface, op

#5113 Use furo docs theme
  .github/workflows/test.yml
  ci/test/distributed_run.py
  docker/ci/test/build.sh
  docker/ci/test/launch.sh
  docker/ci/test/requirements.txt
  docs/requirements.txt
  docs/source/conf.py
Labels: api, automerge, documentation, enhancement, python

#5026 add erf and erfc
  docs/source/experimental.rst
  oneflow/python/nn/modules/math_ops.py
  oneflow/python/test/modules/test_erf.py
  oneflow/python/test/modules/test_erfc.py
Labels: api, automerge, enhancement, feature, interface, op

#5124 add nn.MarginRankingLoss&addmm module
  docs/source/experimental.rst
  oneflow/python/nn/modules/loss.py
  oneflow/python/nn/modules/math_ops.py
  oneflow/python/ops/nn_ops.py
  oneflow/python/test/modules/test_addmm.py
  oneflow/python/test/modules/test_marginrankingloss.py
  oneflow/python/test/tensor/test_tensor.py
Labels: api, automerge, eager, feature, interface

#5116 add mseloss module
  docs/source/experimental.rst
  oneflow/python/nn/modules/loss.py
  oneflow/python/ops/nn_ops.py
  oneflow/python/test/modules/test_mseloss.py
Labels: api, automerge, eager, feature, interface, op

#5128 implement tensor.register_hook
  oneflow/api/python/framework/tensor.cpp
  oneflow/core/autograd/autograd_engine.cpp
  oneflow/core/autograd/autograd_meta.h
  oneflow/python/framework/tensor.py
  oneflow/python/test/tensor/test_tensor.py
Labels: automerge, eager, feature

#5101 Add convtranspose module
  docs/source/experimental.rst
  oneflow/core/autograd/gradient_funcs/deconv.cpp
  oneflow/python/nn/modules/deconv.py
  oneflow/python/test/modules/test_deconv.py
Labels: automerge, eager, feature, interface, python

#5135 add pixel_shuffle module
  docs/source/experimental.rst
  oneflow/python/nn/modules/pixel_shuffle.py
  oneflow/python/ops/nn_ops.py
  oneflow/python/test/modules/test_pixel_shuffle.py
Labels: api, automerge, eager, feature, interface, op

#5130 Fix doctest for modules
  oneflow/python/nn/modules/math_ops.py
Labels: automerge, documentation, eager, interface, test

#4953 Add ceil & expm1 module
  docs/source/experimental.rst
  oneflow/python/nn/modules/math_ops.py
  oneflow/python/test/modules/test_ceil.py
  oneflow/python/test/modules/test_expm1.py
  oneflow/python/test/tensor/test_tensor.py
Labels: api, automerge, feature, interface, op

#5147 Compile C++, CUDA targets in parallel
  cmake/oneflow.cmake
  cmake/third_party.cmake
  cmake/third_party/FindCUDNN.cmake
Labels: automerge, build, enhancement

#5145 Refine optimizer interface
  oneflow/python/nn/optimizer/adam.py
  oneflow/python/nn/optimizer/adamw.py
  oneflow/python/nn/optimizer/lambda_lr.py
  oneflow/python/nn/optimizer/lr_scheduler.py
  oneflow/python/nn/optimizer/optimizer.py
  oneflow/python/nn/optimizer/rmsprop.py
  oneflow/python/nn/optimizer/sgd.py
  oneflow/python/nn/optimizer/step_lr.py
Labels: automerge, eager, enhancement, python

#5139 Add int8 support for expand and repeat
  .github/workflows/test.yml
  oneflow/python/nn/modules/expand.py
  oneflow/python/test/modules/test_expand.py
  oneflow/python/test/modules/test_repeat.py
Labels: automerge, bug, eager, interface, python

#5138 fix bert backward bug
  oneflow/core/autograd/gradient_funcs/broadcast_binary_ops.cpp
Labels: automerge, bug, eager, enhancement, interface

#5133 add eager experimental stack
  oneflow/python/experimental/stack.py
  oneflow/python/ops/array_ops.py
  oneflow/python/test/modules/test_stack.py
Labels: api, automerge, eager, enhancement, interface, op

#5117 Fix slice bug
  oneflow/python/framework/tensor.py
  oneflow/python/nn/modules/conv.py
  oneflow/python/nn/modules/slice.py
  oneflow/python/nn/modules/squeeze.py
  oneflow/python/test/modules/test_slice.py
  oneflow/python/test/modules/test_squeeze.py
Labels: automerge, bug, eager, enhancement, interface

#5150 Use cpu pip package in read the doc to prevent failure
  docs/requirements.txt
Labels: automerge, ci, enhancement

#5121 Add RecordingReplay debug tool
  oneflow/api/python/framework/instruction_replay.cpp
  oneflow/core/framework/instruction_replay.cpp
  oneflow/core/framework/instruction_replay.h
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/job/env_global_objects_scope.cpp
  oneflow/core/vm/instruction.cpp
  oneflow/core/vm/instruction.msg.h
  oneflow/python/test/modules/test_instruction_replay.py
Labels: automerge, eager, feature

#5157 refine and add test case
  oneflow/python/framework/tensor.py
  oneflow/python/test/modules/test_slice.py
Labels: automerge, eager, enhancement, interface, test

#5152 Dynamic link cudnn
  cmake/third_party/FindCUDNN.cmake
  docker/package/manylinux/Dockerfile
  docker/package/manylinux/build_wheel.py
Labels: automerge, build, ci, enhancement

#5149 Fix argwhere module bug
  oneflow/python/nn/modules/argwhere.py
  oneflow/python/test/modules/test_argwhere.py
Labels: automerge, bug, eager, enhancement, interface, python

#5156 Export Optimizer and _LRScheduler
  oneflow/python/nn/optimizer/lr_scheduler.py
  oneflow/python/nn/optimizer/optimizer.py
Labels: automerge, eager, feature, interface

#5154 Align dropout module with pytorch
  oneflow/python/nn/modules/dropout.py
Labels: automerge, bug, eager, interface, python

#4932 Dev functional interface.
  cmake/functional.cmake
  cmake/oneflow.cmake
  dev-requirements.txt
  oneflow/api/python/framework/throw.h
  oneflow/api/python/functional/common.h
  oneflow/api/python/functional/function_def.h
  oneflow/api/python/functional/py_function.h
  oneflow/api/python/functional/python_arg.cpp
  oneflow/api/python/functional/python_arg.h
  oneflow/api/python/functional/unpack_call.h
  oneflow/core/autograd/gradient_funcs/scalar_add.cpp
  oneflow/core/common/error.h
  oneflow/core/common/function_traits.h
  oneflow/core/common/type_traits.h
  oneflow/core/framework/tensor_tuple.h
  oneflow/core/functional/function_library.h
  oneflow/core/functional/function_signature.h
  oneflow/core/functional/functional.h
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/add_functor.cpp
  oneflow/core/functional/impl/normalization_functor.cpp
  oneflow/core/functional/packed_functor.h
  oneflow/core/functional/scalar.h
  oneflow/core/functional/value_types.h
  oneflow/python/framework/functional.py
  oneflow/python/framework/register_class_method_util.py
  oneflow/python/nn/modules/batchnorm.py
  oneflow/python/nn/modules/math_ops.py
  tools/generate_functional_api.py
Labels: api, automerge, feature, refactor, system

#5171 Use composed attrs when creating kernel state.
  oneflow/user/kernels/stateful_local_opkernel.cpp
Labels: automerge, eager, enhancement, interface, system

#5170 Use different tag for CI build and CI release
  .github/workflows/test.yml
Labels: automerge, ci, enhancement

#5166 Fix eq module bug
  oneflow/python/nn/modules/eq.py
  oneflow/python/test/modules/test_eq.py
Labels: automerge, eager, enhancement, interface, python

#5180 Fix unpack_call
  oneflow/api/python/functional/unpack_call.h
Labels: automerge, bug, build, system

#5142 Dev topk eager
  docs/source/experimental.rst
  oneflow/python/nn/modules/math_ops.py
  oneflow/python/test/modules/test_math_ops.py
Labels: automerge, eager, enhancement, interface, op, upload-core

#5161 Update version info 0.5.0
  README.md
  tools/generate_pip_version.py
Labels: automerge, documentation, system

#5177 Update generated functional files only if different.
  cmake/functional.cmake
  tools/cfg/template_convert.py
  tools/generate_functional_api.py
Labels: automerge, build, enhancement, tooling

#5134 L1_Loss
  docs/source/experimental.rst
  oneflow/python/nn/modules/l1loss.py
  oneflow/python/ops/nn_ops.py
  oneflow/python/test/modules/test_l1loss.py
Labels: api, automerge, eager, feature, interface

#5182 Forbid in-source build
  CMakeLists.txt
Labels: automerge, bug, build

#5184 Refine imports in package mirror
  cmake/python.cmake
  tools/package_mirror.py
Labels: automerge, build, enhancement

#5185 Fix target build dependency
  cmake/functional.cmake
  cmake/oneflow.cmake
Labels: automerge, build, enhancement

#5183 Delete squeeze and unsqueeze backward useless code
  oneflow/core/autograd/gradient_funcs/squeeze.cpp
  oneflow/core/autograd/gradient_funcs/unsqueeze.cpp
Labels: automerge, documentation, eager, interface

#5158 add backward op for flatten and softmax; fix bug for softmax in dim 1 case
  oneflow/core/autograd/gradient_funcs/flatten.cpp
  oneflow/core/autograd/gradient_funcs/softmax.cpp
  oneflow/core/framework/op_expr_helper.cpp
  oneflow/core/framework/op_expr_helper.h
  oneflow/python/nn/modules/activation.py
  oneflow/python/test/modules/test_activation.py
Labels: automerge, bug, interface, op

#5022 Dev sum/mean/min/max modules
  docs/source/experimental.rst
  oneflow/core/autograd/gradient_funcs/reduce_ops.cpp
  oneflow/python/nn/modules/l1loss.py
  oneflow/python/nn/modules/loss.py
  oneflow/python/nn/modules/math_ops.py
  oneflow/python/nn/modules/reduce_ops.py
  oneflow/python/test/modules/test_reduce_ops.py
Labels: automerge, enhancement, interface, op

#5186 Fix which nightly release read the doc uses
  .github/workflows/release.yml
Labels: automerge, ci, enhancement

#5031 Yejiaojiao/dev acos
  docs/source/experimental.rst
  oneflow/python/nn/modules/acos.py
  oneflow/python/test/modules/test_acos.py
Labels: api, automerge, eager, feature, interface, op

#5187 Always build test exe so CI can check it
  cmake/oneflow.cmake
  oneflow/core/control/ctrl_test.cpp
Labels: automerge, build, ci, enhancement

#5188 Add CMake argument PIP_INDEX_MIRROR
  .github/workflows/test.yml
  CMakeLists.txt
  README.md
  cmake/python.cmake
Labels: automerge, build, ci, enhancement

#5189 Skip building cares executables
  cmake/third_party/cares.cmake
Labels: automerge, build, enhancement

#5131 InstanceNorm module
  docs/source/experimental.rst
  oneflow/python/nn/modules/instancenorm.py
  oneflow/python/test/modules/test_instancenorm.py
Labels: api, automerge, eager, feature, interface

#5181 Dev fix slice bug
  oneflow/python/framework/tensor.py
  oneflow/python/test/modules/test_slice.py
Labels: automerge, bug, eager, enhancement, interface

#5167 Add adaptive avg pool2d op
  docs/source/experimental.rst
  oneflow/core/autograd/gradient_funcs/adaptive_pool.cpp
  oneflow/core/framework/op_expr_helper.cpp
  oneflow/core/framework/op_expr_helper.h
  oneflow/python/nn/modules/adaptive_pool.py
  oneflow/python/test/modules/test_adaptive_pool.py
  oneflow/user/kernels/adaptive_pool_cpu_kernel.cpp
  oneflow/user/kernels/adaptive_pool_gpu_kernel.cu
  oneflow/user/ops/adaptive_pool_op.cpp
Labels: api, automerge, eager, enhancement, interface

#5136 add conv backward module
  oneflow/core/autograd/gradient_funcs/conv.cpp
  oneflow/core/framework/op_expr_helper.cpp
  oneflow/core/framework/op_expr_helper.h
  oneflow/python/nn/modules/conv.py
  oneflow/python/nn/modules/slice.py
  oneflow/python/test/modules/test_conv.py
Labels: automerge, enhancement, interface, system

#5140 add ConstantPad2d
  docs/source/experimental.rst
  oneflow/python/nn/modules/constantpad2d.py
  oneflow/python/test/modules/test_constantpad2d.py
Labels: api, automerge, enhancement, interface, op

#5163 Rename dl => platform
  oneflow/core/comm_network/ibverbs/ibverbs_comm_network.cpp
  oneflow/core/comm_network/ibverbs/ibverbs_memory_desc.cpp
  oneflow/core/comm_network/ibverbs/ibverbs_qp.cpp
  oneflow/core/device/net_ib_device_descriptor.h
  oneflow/core/job/runtime.cpp
  oneflow/core/platform/include/ibv.h
  oneflow/core/platform/include/wrapper.h
  oneflow/core/platform/lib/ibv_wrapper.cpp
  oneflow/core/platform/lib/wrapper.cpp
Labels: automerge, enhancement, system

#5176 Fix constant module bug
  oneflow/python/nn/modules/constant.py
Labels: automerge, bug, eager, enhancement, interface

#5190 Fix eager test skipping
  .github/workflows/test.yml
  ci/test/1node_op_test.sh
  ci/test/generic_test.sh
Labels: automerge, bug, ci

#5191 Add auto cancel step for outdated commit
  .github/workflows/test.yml
Labels: automerge, ci, enhancement

#4964 Add floor module and the corresponding testcases
  docs/source/experimental.rst
  oneflow/python/nn/modules/floor.py
  oneflow/python/test/modules/test_floor.py
  oneflow/python/test/modules/test_math_ops.py
  oneflow/python/test/tensor/test_tensor.py
Labels: api, automerge, build, documentation, eager, feature, interface, op

#5155 add kldivloss module
  docs/source/experimental.rst
  oneflow/python/nn/modules/loss.py
  oneflow/python/ops/nn_ops.py
  oneflow/python/test/modules/test_kldivloss.py
Labels: api, automerge, eager, feature, interface, op

#5192 Refine CMake CUDA version handling
  .github/workflows/test.yml
  CMakeLists.txt
  docker/ci/make/Dockerfile
  docker/ci/third_party/Dockerfile
Labels: automerge, build, enhancement

#5148 add ReplicationPad2d
  docs/source/experimental.rst
  oneflow/python/nn/modules/replicationpad2d.py
  oneflow/python/test/modules/test_replicationpad2d.py
Labels: api, automerge, enhancement, interface, op

#5160 Add cmake option NCCL_STATIC
  cmake/third_party.cmake
  cmake/third_party/nccl.cmake
Labels: automerge, build, enhancement

#5194 add cpu version of upsampling
  oneflow/python/nn/modules/upsample.py
  oneflow/python/test/modules/test_upsample2d.py
  oneflow/user/kernels/upsample_kernel.cpp
Labels: automerge, enhancement, interface, op

#5196 delete const_cast in Output
  oneflow/core/kernel/user_kernel.cpp
  oneflow/core/operator/user_op.cpp
  oneflow/user/kernels/stateful_local_opkernel.h
Labels: automerge, purge, system

#5199 add magic method for pow
  oneflow/python/framework/tensor.py
  oneflow/python/test/tensor/test_tensor.py
Labels: automerge, enhancement, op

#5201 Add prefix when creating git archive
  .github/workflows/release.yml
Labels: automerge, build, documentation, enhancement

#5015 Support clang
  cmake/third_party/flatbuffers.cmake
  oneflow/core/cuda/softmax.cuh
  oneflow/user/kernels/layer_norm_gpu_kernel.cu
Labels: automerge, build, enhancement

#5200 Set lower precision avoid ci failing
  oneflow/python/test/modules/test_math_ops.py
Labels: automerge, ci, eager, enhancement

#5206 Cancel all workflow runs but the latest
  .github/workflows/test.yml
Labels: automerge, ci, enhancement

#5162 Decouple FileSystem and IOConf
  oneflow/core/common/str_util.cpp
  oneflow/core/common/str_util.h
  oneflow/core/job/file_system_conf.proto
  oneflow/core/job/job_set.proto
  oneflow/core/persistence/file_system.cpp
  oneflow/core/persistence/file_system.h
  oneflow/core/persistence/hadoop/hadoop_file_system.cpp
  oneflow/core/persistence/hadoop/hadoop_file_system.h
  oneflow/core/persistence/persistent_in_stream.cpp
  oneflow/python/framework/config_util.py
  oneflow/python/framework/session_util.py
  oneflow/python/test/modules/test_dataset.py
  oneflow/python/test/modules/test_resnet50_with_bn.py
  oneflow/python/test/modules/test_resnet50_without_bn.py
  oneflow/user/data/coco_data_reader.cpp
  oneflow/user/data/coco_dataset.cpp
  oneflow/user/data/ofrecord_dataset.h
Labels: api, automerge, eager, enhancement, upload-core

#5205 Add meshgrid module
  docs/source/experimental.rst
  oneflow/python/nn/modules/meshgrid.py
  oneflow/python/test/modules/test_meshgrid.py
Labels: automerge, eager, feature, interface, python

#5112 Rename CosineScheduler to CosineAnnealingLR
  docs/source/optim.rst
  oneflow/python/nn/optimizer/cosine_annealing_lr.py
  oneflow/python/test/modules/test_lr_scheduler.py
Labels: automerge, documentation, eager, interface, python

#5208 Fix meshgrid test bug
  oneflow/python/test/modules/test_meshgrid.py
Labels: automerge, bottleneck, bug, documentation, interface, python

#5203 Fix xla test case fail
  oneflow/xrt/launch_kernel.cpp
  oneflow/xrt/launch_op.cpp
Labels: enhancement, system

#5081 Wake up the heartbeat thread immediately
  oneflow/core/control/ctrl_client.cpp
  oneflow/core/rpc/include/grpc.h
Labels: automerge, enhancement, system

#5213 Speedup opencv build
  cmake/third_party/header_index/opencv_headers.txt
  cmake/third_party/opencv.cmake
Labels: automerge, build, ci, enhancement

#5215 Remove transport test main
  cmake/oneflow.cmake
  oneflow/core/transport/transport_test_main.cpp
Labels: automerge, build, ci, enhancement

#5168 Dev modules ctc loss
  docs/source/experimental.rst
  oneflow/core/autograd/gradient_funcs/ctc_loss.cpp
  oneflow/core/framework/op_expr_helper.cpp
  oneflow/core/framework/op_expr_helper.h
  oneflow/python/nn/modules/loss.py
  oneflow/python/test/modules/test_ctc_loss.py
  oneflow/user/kernels/ctc_loss_kernel.cpp
  oneflow/user/ops/ctc_loss_op.cpp
Labels: automerge, eager, feature, interface, op, python

#5202 Run exe test in CPU-only
  .github/workflows/test.yml
  cmake/oneflow.cmake
  oneflow/core/eager/init_symbol_instruction_type_test.cpp
  oneflow/core/eager/opkernel_instruction_type_test.cpp
  oneflow/core/eager/transport_blob_instruction_type_test.cpp
  oneflow/core/job/parallel_desc.cpp
  oneflow/core/transport/transport_test_main.cpp
Labels: automerge, ci, enhancement

#5210 Add nllloss backward
  oneflow/python/test/modules/test_nllloss_grad.py
Labels: api, automerge, bug, documentation, eager, enhancement, interface

#5217 Fix acos ci bug
  oneflow/python/test/modules/test_acos.py
Labels: automerge, bug, interface, test

#5214 Support different dtype of equal module
  oneflow/python/nn/modules/eq.py
Labels: automerge, eager, enhancement, feature

#5211 Refactor infer ctx input isdynamic
  oneflow/core/framework/infer_util.h
  oneflow/core/kernel/user_kernel.cpp
  oneflow/core/operator/user_op.cpp
  oneflow/user/kernels/stateful_local_opkernel.h
  oneflow/user/ops/acc_op.cpp
  oneflow/user/ops/adaptive_pool_op.cpp
  oneflow/user/ops/bias_add_op.cpp
  oneflow/user/ops/broadcast_div_grad_op.cpp
  oneflow/user/ops/buffer_op.cpp
  oneflow/user/ops/cast_like_op.cpp
  oneflow/user/ops/combined_margin_loss_op.cpp
  oneflow/user/ops/conv_op.cpp
  oneflow/user/ops/copy_op.cpp
  oneflow/user/ops/dropout_op.cpp
  oneflow/user/ops/fused_self_attention_query_mul_key_and_value_ops.cpp
  oneflow/user/ops/hierarchical_parallel_cast_op.cpp
  oneflow/user/ops/identity_op.cpp
  oneflow/user/ops/image_object_preprocess_ops.cpp
  oneflow/user/ops/l1_l2_regularize_gradient_op.cpp
  oneflow/user/ops/math_binary_broadcast_ops.cpp
  oneflow/user/ops/matmul_op.cpp
  oneflow/user/ops/model_update_ops.cpp
  oneflow/user/ops/nccl_logical_2d_sbp_ops.cpp
  oneflow/user/ops/nccl_logical_ops.cpp
  oneflow/user/ops/nvtx_range_op.cpp
  oneflow/user/ops/parallel_cast_op.cpp
  oneflow/user/ops/partial_fc_sample_op.cpp
  oneflow/user/ops/pool_op.cpp
  oneflow/user/ops/repeat_op.cpp
  oneflow/user/ops/same_padding_op.cpp
  oneflow/user/ops/scalar_add_op.cpp
  oneflow/user/ops/scalar_mul_op.cpp
  oneflow/user/ops/softmax_cross_entropy_op.cpp
  oneflow/user/ops/tuple_identity_op.cpp
  oneflow/user/ops/unsorted_segment_sum_op.cpp
Labels: automerge, enhancement, system

#5222 Fix stack module
  oneflow/python/nn/modules/stack.py
  oneflow/python/test/modules/test_stack.py
Labels: automerge, bug, eager, enhancement

#5220 Refactor infer ctx output isdynamic
  oneflow/core/framework/infer_util.cpp
  oneflow/core/framework/infer_util.h
  oneflow/core/kernel/user_kernel.cpp
  oneflow/core/operator/user_op.cpp
  oneflow/user/kernels/stateful_local_opkernel.h
  oneflow/user/ops/acc_op.cpp
  oneflow/user/ops/adaptive_pool_op.cpp
  oneflow/user/ops/bias_add_op.cpp
  oneflow/user/ops/broadcast_div_grad_op.cpp
  oneflow/user/ops/buffer_op.cpp
  oneflow/user/ops/cast_like_op.cpp
  oneflow/user/ops/conv_op.cpp
  oneflow/user/ops/copy_op.cpp
  oneflow/user/ops/dropout_op.cpp
  oneflow/user/ops/fused_bias_add_op.cpp
  oneflow/user/ops/fused_scale_tril_softmax_mask_scale_op.cpp
  oneflow/user/ops/hierarchical_parallel_cast_op.cpp
  oneflow/user/ops/identity_op.cpp
  oneflow/user/ops/image_object_preprocess_ops.cpp
  oneflow/user/ops/l1_l2_regularize_gradient_op.cpp
  oneflow/user/ops/math_binary_broadcast_ops.cpp
  oneflow/user/ops/matmul_op.cpp
  oneflow/user/ops/model_update_ops.cpp
  oneflow/user/ops/nccl_logical_2d_sbp_ops.cpp
  oneflow/user/ops/nccl_logical_ops.cpp
  oneflow/user/ops/nvtx_range_op.cpp
  oneflow/user/ops/parallel_cast_op.cpp
  oneflow/user/ops/partial_fc_sample_op.cpp
  oneflow/user/ops/pool_op.cpp
  oneflow/user/ops/prelu_op.cpp
  oneflow/user/ops/repeat_op.cpp
  oneflow/user/ops/same_padding_op.cpp
  oneflow/user/ops/scalar_add_op.cpp
  oneflow/user/ops/scalar_mul_op.cpp
  oneflow/user/ops/softmax_cross_entropy_op.cpp
  oneflow/user/ops/sparse_cross_entropy_op.cpp
  oneflow/user/ops/sparse_softmax_cross_entropy_op.cpp
Labels: automerge, enhancement, system

#5221 Fix acosh bug
  oneflow/python/test/modules/test_acosh.py
Labels: api, automerge, bug, eager, interface, python

#5223 Dev user op set default is_dynamic
  oneflow/core/operator/user_op.cpp
Labels: automerge, bug, ci, op

#5173 Yejiaojiao/dev bcewithlogitsloss
  docs/source/experimental.rst
  oneflow/python/nn/modules/loss.py
  oneflow/python/ops/nn_ops.py
  oneflow/python/test/modules/test_bcewithlogitsloss.py
Labels: api, automerge, eager, feature, interface, op

#5195 crossentropyloss and nllloss support ignore_index
  oneflow/python/nn/modules/loss.py
  oneflow/python/test/modules/test_crossentropyloss.py
  oneflow/python/test/modules/test_crossentropyloss_grad.py
  oneflow/python/test/modules/test_nllloss.py
  oneflow/python/test/modules/test_nllloss_grad.py
Labels: api, automerge, eager, feature, interface, op

#5207 Add Simple CI, runs CPU-only on GitHub hosted servers
  .github/workflows/simple.yml
  .github/workflows/test.yml
  ci/requirements.txt
  oneflow/python/test/ops/test_checkpoint.py
  oneflow/python/test/ops/test_gpt_data_loader.py
Labels: automerge, ci, enhancement

#5216 Refine protobuf cmake
  cmake/oneflow.cmake
  cmake/proto2cpp.cmake
  cmake/third_party.cmake
  cmake/third_party/glog.cmake
  cmake/third_party/grpc.cmake
  cmake/third_party/header_index/protobuf_headers.txt
  cmake/third_party/protobuf.cmake
Labels: automerge, build, enhancement

#5224 Add deconv cpu impl
  oneflow/python/test/modules/test_deconv.py
  oneflow/user/kernels/deconv_cpu_kernel.cpp
Labels: automerge, eager, feature, interface, op, python

#5225 Lazy construct functor to make sure that the operators has already been registered.
  oneflow/core/functional/function_library.h
  oneflow/core/functional/packed_functor.h
Labels: automerge, bug, system

#5178 Dev norm op
  docs/source/experimental.rst
  oneflow/python/nn/modules/norm.py
  oneflow/python/ops/nn_ops.py
  oneflow/python/test/modules/test_norm.py
  oneflow/python/test/tensor/test_tensor.py
Labels: api, automerge, eager, enhancement, feature, interface

#5144 module BCELoss
  docs/source/experimental.rst
  oneflow/python/nn/modules/loss.py
  oneflow/python/ops/nn_ops.py
  oneflow/python/test/modules/test_bce_loss.py
Labels: api, automerge, eager, feature, interface

#5064 Op expr infer tensor meta
  oneflow/core/framework/arg_tuple.cpp
  oneflow/core/framework/arg_tuple.h
  oneflow/core/framework/infer_util.h
  oneflow/core/framework/op_expr.cpp
  oneflow/core/framework/op_expr.h
  oneflow/core/framework/op_interpreter/eager_mirrored_op_interpreter.cpp
  oneflow/core/framework/op_interpreter/eager_mirrored_op_interpreter.h
  oneflow/core/framework/op_interpreter/op_interpreter_util.cpp
  oneflow/core/framework/op_interpreter/op_interpreter_util.h
  oneflow/core/framework/tensor.cpp
  oneflow/core/framework/tensor.h
  oneflow/core/framework/tensor_impl.cpp
  oneflow/core/framework/tensor_impl.h
  oneflow/core/kernel/user_kernel.cpp
  oneflow/core/operator/user_op.cpp
  oneflow/user/kernels/stateful_local_opkernel.h
  oneflow/user/ops/layer_norm_op.cpp
Labels: automerge, enhancement, system, upload-core

#5172 add ReflectionPad2d
  docs/source/experimental.rst
  oneflow/python/nn/modules/reflection_pad2d.py
  oneflow/python/ops/pad.py
  oneflow/python/test/modules/test_reflection_pad2d.py
Labels: api, automerge, enhancement, interface, op

#5232 Refine module test
  oneflow/python/nn/modules/acos.py
  oneflow/python/nn/modules/atan2.py
  oneflow/python/test/modules/test_acos.py
  oneflow/python/test/modules/test_acosh.py
  oneflow/python/test/modules/test_atan.py
  oneflow/python/test/modules/test_atan2.py
  oneflow/python/test/modules/test_atanh.py
  oneflow/python/test/modules/test_tan.py
  oneflow/python/test/tensor/test_tensor.py
Labels: api, automerge, bug, ci, interface

#5229 Refine deconv kernel
  oneflow/user/kernels/deconv_cpu_kernel.cpp
Labels: automerge, bug, enhancement, interface, op

#5230 Move default third party dir into build dir
  .github/workflows/simple.yml
  CMakeLists.txt
Labels: automerge, build, ci, enhancement

#5233 Fix protobuf debug postfix
  .github/workflows/simple.yml
  cmake/third_party/protobuf.cmake
Labels: automerge, bug, build

#5165 [Add] avgpool1d avgpool3d
  docs/source/experimental.rst
  oneflow/python/nn/modules/avgpooling.py
  oneflow/python/test/modules/test_avgpool.py
Labels: automerge, eager, enhancement, interface, python

#5175 Add GroupNorm
  docs/source/experimental.rst
  oneflow/python/nn/modules/groupnorm.py
  oneflow/python/ops/nn_ops.py
  oneflow/python/test/modules/test_groupnorm.py
Labels: automerge, enhancement, interface, python
