Repository Oneflow-Inc/oneflow, pull requests merged in 2021-01, with the labels that each got.

#4063 Refactor python blob desc
  cmake/cfg.cmake
  oneflow/api/python/framework/py_blob_desc.cpp
  oneflow/api/python/framework/py_distribute.cpp
  oneflow/api/python/framework/shape.cpp
  oneflow/core/common/container_util.h
  oneflow/core/common/type_traits.h
  oneflow/core/framework/py_blob_desc.h
  oneflow/core/framework/py_distribute.cpp
  oneflow/core/framework/py_distribute.h
  oneflow/core/framework/tensor.h
  oneflow/python/framework/blob_desc.py
  oneflow/python/framework/distribute.py
  oneflow/python/framework/input_blob_def.py
  oneflow/python/framework/ops.py
  oneflow/python/framework/remote_blob.py
  oneflow/python/ops/__init__.py
  oneflow/python/ops/get_variable.py
  oneflow/python/ops/layers.py
  oneflow/python/ops/nn_ops.py
  oneflow/python/ops/prelu.py
  oneflow/python/ops/two_stage_reduce.py
  oneflow/python/ops/watch.py
  oneflow/python/test/ops/test_dim_gather_dynamic.py
Labels: automerge, enhancement, system

#4067 Fix warning: moving a local object in a return statement prevents copy elision
  oneflow/core/common/protobuf.cpp
Labels: automerge, bug, system

#4043 Add hard sigmoid
  oneflow/python/ops/nn_ops.py
  oneflow/python/test/ops/test_hardsigmoid.py
  oneflow/user/kernels/hardsigmoid_kernel.cpp
  oneflow/user/kernels/hardsigmoid_kernel.cu
  oneflow/user/ops/hardsigmoid_op.cpp
Labels: automerge, enhancement, op, python

#4071 remove BlobDef
  oneflow/python/advanced/distribute_ops.py
  oneflow/python/experimental/dynamic_binary_split_concat_op.py
  oneflow/python/experimental/indexed_slices_ops.py
  oneflow/python/experimental/square_sum_op.py
  oneflow/python/experimental/ssp_variable_proxy_op.py
  oneflow/python/experimental/unique_op.py
  oneflow/python/framework/compiler.py
  oneflow/python/framework/ops.py
  oneflow/python/framework/remote_blob.py
  oneflow/python/framework/typing_util.py
  oneflow/python/ops/array_ops.py
  oneflow/python/ops/categorical_ordinal_encode_op.py
  oneflow/python/ops/combined_margin_loss.py
  oneflow/python/ops/constant_op.py
  oneflow/python/ops/count_not_finite.py
  oneflow/python/ops/data_ops.py
  oneflow/python/ops/eager_nccl_ops.py
  oneflow/python/ops/get_variable.py
  oneflow/python/ops/layers.py
  oneflow/python/ops/linalg.py
  oneflow/python/ops/loss_ops.py
  oneflow/python/ops/losses/add_loss.py
  oneflow/python/ops/math_binary_elementwise_ops.py
  oneflow/python/ops/math_ops.py
  oneflow/python/ops/math_unary_elementwise_ops.py
  oneflow/python/ops/nn_ops.py
  oneflow/python/ops/one_hot.py
  oneflow/python/ops/optimizer.py
  oneflow/python/ops/pad.py
  oneflow/python/ops/prelu.py
  oneflow/python/ops/quantize_ops.py
  oneflow/python/ops/random_ops.py
  oneflow/python/ops/reduce_mean.py
  oneflow/python/ops/reduce_ops.py
  oneflow/python/ops/sort_ops.py
  oneflow/python/ops/tensor_buffer_ops.py
  oneflow/python/ops/tensor_list_ops.py
  oneflow/python/ops/two_stage_reduce.py
  oneflow/python/ops/user_data_ops.py
  oneflow/python/ops/user_op_builder.py
  oneflow/python/ops/watch.py
Labels: automerge, enhancement, system

#4075 Quit docker after making ssh creadential
  ci/test/distributed_run.py
Labels: automerge, bug, ci

#4076 Dev hardsigmoid
  oneflow/python/ops/nn_ops.py
Labels: automerge, bug, documentation, python

#4059 Add Hardswish activation
  oneflow/python/ops/nn_ops.py
  oneflow/python/test/ops/test_hardswish.py
  oneflow/user/kernels/hardswish_kernel.cpp
  oneflow/user/kernels/hardswish_kernel.cu
  oneflow/user/ops/hardswish_op.cpp
Labels: automerge, enhancement, op

#4041 Update logsoftmax.py
  oneflow/python/ops/nn_ops.py
  oneflow/python/test/ops/test_logsoftmax.py
Labels: automerge, enhancement, op, python

#4065 Add ELU activation
  oneflow/python/ops/nn_ops.py
  oneflow/python/test/ops/test_elu.py
  oneflow/user/kernels/elu_kernel.cpp
  oneflow/user/kernels/elu_kernel.cu
  oneflow/user/ops/elu_op.cpp
Labels: automerge, enhancement, op

#4081 Refactor python remote blob
  oneflow/api/python/framework/py_blob_desc.cpp
  oneflow/api/python/framework/py_remote_blob.cpp
  oneflow/api/python/job_build/job_build_and_infer.cpp
  oneflow/api/python/job_build/job_build_and_infer.h
  oneflow/api/python/job_build/job_build_and_infer_api.h
  oneflow/core/framework/py_blob_desc.h
  oneflow/core/framework/py_remote_blob.h
  oneflow/core/framework/tensor.h
  oneflow/core/job/parallel_desc.h
  oneflow/init.py
  oneflow/python/advanced/distribute_ops.py
  oneflow/python/experimental/dynamic_binary_split_concat_op.py
  oneflow/python/framework/c_api_util.py
  oneflow/python/framework/input_blob_def.py
  oneflow/python/framework/local_blob.py
  oneflow/python/framework/pull_util.py
  oneflow/python/framework/remote_blob.py
  oneflow/python/framework/watcher.py
  oneflow/python/ops/__init__.py
  oneflow/python/ops/get_variable.py
  oneflow/python/ops/watch.py
  oneflow/python/test/ops/test_function_input_output.py
  oneflow/python/test/ops/test_reduce_ops.py
  oneflow/python/test/ops/test_reduce_opsV2.py
  oneflow/python/test/ops/test_reduce_sum.py
Labels: enhancement, system

#4049 Add Hardtanh activation
  oneflow/python/ops/nn_ops.py
  oneflow/python/test/ops/test_hardtanh.py
  oneflow/user/kernels/hardtanh_kernel.cpp
  oneflow/user/kernels/hardtanh_kernel.cu
  oneflow/user/ops/hardtanh_op.cpp
Labels: automerge, enhancement, op

#4085 Fix "hardsigmoid" eager test error
  oneflow/python/test/ops/test_hardsigmoid.py
Labels: automerge, bug, enhancement, python

#4084 Cfg hash
  oneflow/core/common/cfg_reflection_test.cpp
  oneflow/core/operator/op_conf.proto
  tools/cfg/template/template.cfg.cpp
  tools/cfg/template/template.cfg.h
Labels: automerge, enhancement, tooling

#4086 Mig py cfg sbp
  cmake/cfg.cmake
  oneflow/api/python/deprecated.cpp
  oneflow/api/python/framework/py_remote_blob.cpp
  oneflow/api/python/init.cpp
  oneflow/core/framework/py_blob_desc.h
  oneflow/core/framework/py_remote_blob.h
  oneflow/python/eager/boxing_util.py
  oneflow/python/eager/vm_util.py
  oneflow/python/framework/op_arg_util.py
  oneflow/python/framework/push_util.py
  oneflow/python/framework/remote_blob.py
  oneflow/python/lib/core/high_order_bool.py
  tools/cfg/template/template.cfg.cpp
  tools/cfg/template/template.cfg.pybind.cpp
Labels: automerge, enhancement, system

#4088 add remove_img_without_anno api for COCOReader
  oneflow/python/ops/user_data_ops.py
Labels: automerge, enhancement, op

#4091 fix hardtanh CI precision error
  oneflow/python/test/ops/test_elu.py
  oneflow/python/test/ops/test_hardsigmoid.py
  oneflow/python/test/ops/test_hardswish.py
  oneflow/python/test/ops/test_hardtanh.py
Labels: bug, op, python

#4093 Rename ont_hot_op.cpp to one_hot_op.cpp
  oneflow/user/ops/one_hot_op.cpp
Labels: automerge, bug, op

#4029 add Relu6 activation
  oneflow/python/ops/nn_ops.py
  oneflow/python/test/ops/test_relu6.py
Labels: automerge, enhancement, op, python

#4092 add float16 datatype for eager boxing
  oneflow/core/kernel/boxing_kernel.cpp
Labels: automerge, bug, eager

#3857 Distributed partial sampler
  oneflow/core/common/not_equal_to_previous_adjacent_iterator.h
  oneflow/core/kernel/unique_kernel_util.cu
  oneflow/python/ops/partial_fc_sample.py
  oneflow/python/test/ops/test_partial_fc.py
  oneflow/user/kernels/partial_fc_sample_kernel.cu
  oneflow/user/ops/partial_fc_sample_op.cpp
Labels: automerge, feature, op

#4090 Mig op arg para attr
  cmake/cfg.cmake
  oneflow/api/python/deprecated.cpp
  oneflow/api/python/framework/op_arg_util.cpp
  oneflow/core/framework/op_arg_util.h
  oneflow/core/operator/inter_face_blob_conf.proto
  oneflow/core/operator/op_conf.proto
  oneflow/python/eager/op_executor.py
  oneflow/python/eager/vm_util.py
  oneflow/python/framework/input_blob_def.py
  oneflow/python/framework/op_arg_util.py
  oneflow/python/framework/remote_blob.py
  tools/cfg/template/template.cfg.cpp
  tools/cfg/template/template.cfg.h
  tools/cfg/template/template.cfg.pybind.cpp
Labels: automerge, enhancement, system

#4099 Add CentOS specific info on README.md
  README.md
Labels: build, documentation

#4089 Add GroupNorm op
  oneflow/python/ops/nn_ops.py
  oneflow/python/test/ops/test_group_norm_op.py
Labels: automerge, feature, op

#4095 Migrate cast_to_static_shape to user op
  oneflow/core/job_rewriter/auto_mixed_precision_lists.cpp
  oneflow/core/job_rewriter/autograd.cpp
  oneflow/core/job_rewriter/prune_cast_to_static_shape_op_pass.cpp
  oneflow/core/kernel/cast_to_static_shape_kernel.cpp
  oneflow/core/operator/identity_op.cpp
  oneflow/core/operator/op_conf.proto
  oneflow/python/ops/array_ops.py
  oneflow/python/test/ops/test_cast_to_static_shape.py
  oneflow/user/kernels/cast_to_static_shape_kernel.cpp
  oneflow/user/ops/cast_to_static_shape_op.cpp
Labels: enhancement, op, refactor

#4094 Fix bug: mut_shape_view of static output maybe null in UserKernel::ForwardShape
  oneflow/core/kernel/user_kernel.cpp
  oneflow/python/test/ops/test_argwhere.py
Labels: automerge, bug, op

#4082 Add Scalar Pow
  oneflow/python/ops/math_binary_elementwise_ops.py
  oneflow/python/test/ops/test_scalar_pow.py
  oneflow/user/kernels/scalar_pow_kernel.cpp
  oneflow/user/kernels/scalar_pow_kernel.cu
  oneflow/user/ops/scalar_pow_op.cpp
Labels: automerge, enhancement, feature, op

#4105 Fix Code format warning in hardswish
  oneflow/user/kernels/hardswish_kernel.cpp
  oneflow/user/kernels/hardswish_kernel.cu
Labels: automerge, enhancement, op

#4069 Add elementwise maximum/minimum ops
  oneflow/python/ops/math_ops.py
  oneflow/python/test/ops/test_elementwise_maximum_minimum.py
  oneflow/python/test/ops/test_elementwise_maximum_minimum_dynamic.py
  oneflow/user/kernels/elementwise_maximum_minimum_kernel.cpp
  oneflow/user/kernels/elementwise_maximum_minimum_kernel.cu
  oneflow/user/ops/elementwise_maximum_minimum_ops.cpp
Labels: automerge, enhancement, op

#4103 Fix test kldivloss tolerance
  oneflow/python/test/ops/test_KLDivloss.py
Labels: automerge, bug, enhancement, python

#4072 Tensor Float 32 Support.
  oneflow/core/device/cuda_stream_handle.cpp
  oneflow/core/job/resource.proto
  oneflow/core/job/resource_desc.h
  oneflow/python/framework/config_util.py
  oneflow/python/test/ops/test_matmul.py
  oneflow/python/test/ops/test_nn_conv1d.py
  oneflow/python/test/ops/test_nn_conv2d.py
  oneflow/python/test/ops/test_nn_conv2d_padding.py
  oneflow/python/test/ops/test_nn_conv2d_padding_dynamic.py
  oneflow/python/test/ops/test_nn_conv3d.py
  oneflow/user/kernels/conv_cudnn_kernels.cpp
  oneflow/user/kernels/matmul_kernels.cpp
Labels: automerge, feature, system

#4104 Migrate `swish` and `mish` namespace from `math` to `nn`
  oneflow/python/ops/math_ops.py
  oneflow/python/ops/nn_ops.py
  oneflow/python/test/ops/test_mish.py
  oneflow/python/test/ops/test_swish.py
Labels: automerge, enhancement, op, python

#4096 indexed_slices update support weight_decay
  oneflow/core/job_rewriter/indexed_slices_optimizer_rewrite_pass.cpp
  oneflow/python/ops/optimizer.py
  oneflow/python/test/ops/test_optimizers.py
  oneflow/user/kernels/model_update_kernel_util.cpp
  oneflow/user/kernels/model_update_kernel_util.cu
  oneflow/user/kernels/model_update_kernel_util.h
  oneflow/user/kernels/model_update_kernels.cpp
  oneflow/user/ops/model_update_ops.cpp
Labels: automerge, enhancement, op

#4102 Mig op arg para attr
  cmake/cfg.cmake
  oneflow/api/python/deprecated.cpp
  oneflow/api/python/framework/op_arg_util.cpp
  oneflow/api/python/op/op_mgr.h
  oneflow/api/python/symbol/op_node_signature_symbol.cpp
  oneflow/api/python/symbol/symbol.cpp
  oneflow/core/eager/eager_oneflow.cpp
  oneflow/core/eager/eager_symbol.proto
  oneflow/core/eager/init_symbol_instruction_type.cpp
  oneflow/core/eager/opkernel_instruction_type_test.cpp
  oneflow/core/eager/transport_blob_instruction_type_test.cpp
  oneflow/core/framework/op_arg_util.cpp
  oneflow/core/framework/op_arg_util.h
  oneflow/core/framework/symbol_id_cache.cpp
  oneflow/core/operator/interface_blob_conf.proto
  oneflow/core/operator/op_attribute.proto
  oneflow/core/operator/op_conf.proto
  oneflow/core/operator/op_node_signature.proto
  oneflow/core/operator/op_node_signature_desc.cpp
  oneflow/core/operator/op_node_signature_desc.h
  oneflow/core/operator/operator.cpp
  oneflow/core/operator/operator.h
  oneflow/core/vm/symbol_storage.cpp
  oneflow/core/vm/symbol_storage.h
  oneflow/python/eager/boxing_middle.py
  oneflow/python/eager/boxing_util.py
  oneflow/python/eager/op_executor.py
  oneflow/python/eager/op_infer_util.py
  oneflow/python/eager/symbol_storage.py
  oneflow/python/eager/vm_util.py
  oneflow/python/framework/check_point_v2.py
  oneflow/python/framework/input_blob_def.py
  oneflow/python/framework/op_arg_util.py
  oneflow/python/framework/remote_blob.py
Labels: automerge, eager, enhancement, system

#4107 simplify cosface
  oneflow/user/kernels/combined_margin_loss_kernel.cu
Labels: automerge, enhancement, op

#4110 reduce sum half kernel
  oneflow/python/test/ops/test_reduce_sum.py
  oneflow/user/kernels/reduce_kernel.cpp
Labels: automerge, enhancement, op

#3817 quantization aware training pass
  oneflow/core/job/job_build_and_infer_ctx.cpp
  oneflow/core/job/job_conf.proto
  oneflow/core/job_rewriter/auto_mixed_precision.cpp
  oneflow/core/job_rewriter/do_parallel_cast_before_widening_type_cast_pass.cpp
  oneflow/core/job_rewriter/pass_util.cpp
  oneflow/core/job_rewriter/pass_util.h
  oneflow/core/job_rewriter/quantization_aware_training.cpp
  oneflow/python/framework/function_util.py
  oneflow/python/test/ops/test_quantization_aware_training.py
Labels: automerge, feature, system

#4113 Update readme adding depth=1 and bump version
  README.md
  oneflow/python/version.py
Labels: build, documentation

#4116 [XRT] support group convolution for tensorrt.
  oneflow/xrt/tensorrt/ops/convolution_op.cpp
Labels: enhancement, feature, op

#4118 fix ParallelDesc Constructor bug
  oneflow/core/job/parallel_desc.cpp
  oneflow/core/job/parallel_desc_test.cpp
Labels: automerge, bug, system

#4109 Mig blob object
  oneflow/api/python/framework/object.cpp
  oneflow/core/framework/object.cpp
  oneflow/core/framework/object.h
  oneflow/core/framework/op_arg_util.cpp
  oneflow/core/framework/op_arg_util.h
  oneflow/core/framework/py_blob_desc.cpp
  oneflow/core/framework/py_blob_desc.h
  oneflow/core/framework/py_remote_blob.cpp
  oneflow/core/framework/py_remote_blob.h
  oneflow/python/eager/blob_cache.py
  oneflow/python/eager/blob_register.py
  oneflow/python/eager/boxing_hob.py
  oneflow/python/eager/interpreter_callback.py
  oneflow/python/eager/object.py
  oneflow/python/eager/object_storage.py
  oneflow/python/eager/opkernel_object.py
  oneflow/python/eager/vm_util.py
  oneflow/python/framework/push_util.py
Labels: automerge, eager, enhancement

#4112 Fix bug: gather_nd grad op accesse invalid attritbute 'shape'
  oneflow/python/test/ops/test_gather_nd.py
  oneflow/user/ops/nd_index_slice_ops.cpp
Labels: automerge, bug, op

#4117 Dev matmul stride batched
  oneflow/core/device/cuda_stream_handle.cpp
  oneflow/core/device/cuda_util.cu
  oneflow/core/device/cuda_util.h
  oneflow/core/job/job_conf.proto
  oneflow/core/job/job_desc.h
  oneflow/core/kernel/util/cuda_blas_interface.cu
  oneflow/core/kernel/util/cuda_blas_interface.h
  oneflow/python/framework/function_util.py
  oneflow/user/kernels/matmul_kernels.cpp
Labels: automerge, enhancement, op

#4115 Modularized compilation of OneFlow's graph classes
  cmake/oneflow.cmake
  cmake/third_party.cmake
  oneflow/core/CMakeLists.txt
  oneflow/core/graph/CMakeLists.txt
  oneflow/core/graph_impl/acc_compute_task_node.cpp
  oneflow/core/graph_impl/callback_notify_compute_task_node.cpp
  oneflow/core/graph_impl/case_compute_task_node.cpp
  oneflow/core/graph_impl/device_tick_compute_task_node.cpp
  oneflow/core/graph_impl/esac_compute_task_node.cpp
  oneflow/core/graph_impl/foreign_input_compute_task_node.cpp
  oneflow/core/graph_impl/foreign_output_compute_task_node.cpp
  oneflow/core/graph_impl/logical_node.cpp
  oneflow/core/graph_impl/pack_compute_task_node.cpp
  oneflow/core/graph_impl/print_compute_task_node.cpp
  oneflow/core/graph_impl/reentrant_lock_compute_task_node.cpp
  oneflow/core/graph_impl/repeat_compute_task_node.cpp
  oneflow/core/graph_impl/source_tick_compute_task_node.cpp
  oneflow/core/graph_impl/ssp_variable_proxy_task_node.cpp
  oneflow/core/graph_impl/tick_compute_task_node.cpp
  oneflow/core/graph_impl/unpack_compute_task_node.cpp
Labels: automerge, build, enhancement

#4122 rm softmax_util BroadcastDivGpu
  oneflow/user/kernels/softmax_kernel_util.cu
Labels: enhancement, op

#4126 Fix nn docs error
  oneflow/python/ops/nn_ops.py
Labels: automerge, enhancement, python

#4106 Refine grad for maximum minimum
  oneflow/python/test/ops/test_elementwise_maximum_minimum.py
  oneflow/user/kernels/elementwise_maximum_minimum_kernel.cpp
  oneflow/user/kernels/elementwise_maximum_minimum_kernel.cu
  oneflow/user/kernels/elementwise_maximum_minimum_kernel.h
  oneflow/user/ops/elementwise_maximum_minimum_ops.cpp
Labels: automerge, enhancement, op

#4127 Change oneflow graph links to deps
  cmake/oneflow.cmake
  cmake/third_party.cmake
  oneflow/core/graph/CMakeLists.txt
  oneflow/python/test/ops/test_batch_normalization.py
Labels: automerge, build, enhancement

#4131 merge diag-op for eye-op implementation
  oneflow/core/kernel/diag_kernel.h
  oneflow/python/ops/diag_ops.py
  oneflow/python/test/ops/test_diag.py
  oneflow/user/kernels/diag_kernel.cpp
  oneflow/user/ops/diag_op.cpp
Labels: automerge, op

#4128 hot fix for conv3d padding
  oneflow/python/ops/layers.py
  oneflow/python/ops/nn_ops.py
Labels: automerge, bug, op, python

#4133 Mig blob register
  oneflow/api/python/framework/blob_register.cpp
  oneflow/core/framework/blob_register.cpp
  oneflow/core/framework/blob_register.h
  oneflow/python/eager/blob_register.py
  oneflow/python/eager/op_executor.py
  oneflow/python/framework/interpret_util.py
  oneflow/python/framework/session_util.py
  oneflow/python/ops/__init__.py
Labels: automerge, enhancement, system

#4121 Refine DestroyEnv
  oneflow/api/python/env/env.h
  oneflow/core/job/cluster.cpp
  oneflow/core/job/env_global_objects_scope.cpp
  oneflow/python/framework/env_util.py
Labels: enhancement, system

#4136 Mig eager util
  oneflow/api/python/framework/eager_blob_util.cpp
  oneflow/api/python/framework/py_remote_blob.cpp
  oneflow/core/framework/eager_blob_util.cpp
  oneflow/core/framework/eager_blob_util.h
  oneflow/core/framework/py_remote_blob.cpp
  oneflow/core/framework/py_remote_blob.h
  oneflow/python/eager/eager_blob_util.py
  oneflow/python/framework/remote_blob.py
Labels: eager, enhancement, system

#4139 Fix bug: cast_to_static_shape test raise unimplemented error in eager
  oneflow/python/test/ops/test_cast_to_static_shape.py
Labels: automerge, bug, op

#4149 Remove ConstBuf
  oneflow/core/actor/normal_forward_compute_actor.cpp
  oneflow/core/actor/normal_forward_compute_actor.h
  oneflow/core/graph/normal_forward_compute_task_node.cpp
  oneflow/core/graph/op_graph.cpp
  oneflow/core/graph/op_graph.h
  oneflow/core/job/job_build_and_infer_ctx.cpp
  oneflow/core/kernel/kernel.cpp
  oneflow/core/kernel/kernel.h
  oneflow/core/operator/op_attribute.proto
  oneflow/core/operator/operator.cpp
  oneflow/core/operator/operator.h
Labels: op, purge

#4140 Mig eager blob
  oneflow/api/python/framework/eager_blob_util.cpp
  oneflow/api/python/framework/py_distribute.cpp
  oneflow/api/python/framework/py_remote_blob.cpp
  oneflow/core/framework/blob_trait.cpp
  oneflow/core/framework/blob_trait.h
  oneflow/core/framework/eager_blob_util.cpp
  oneflow/core/framework/eager_blob_util.h
  oneflow/core/framework/py_distribute.h
  oneflow/core/framework/py_remote_blob.cpp
  oneflow/core/framework/py_remote_blob.h
  oneflow/init.py
  oneflow/python/eager/eager_blob_util.py
  oneflow/python/eager/op_executor.py
  oneflow/python/experimental/interface_op_read_and_write.py
  oneflow/python/framework/blob_trait.py
  oneflow/python/framework/check_point_v2.py
  oneflow/python/framework/local_blob.py
  oneflow/python/framework/pull_util.py
  oneflow/python/framework/push_util.py
  oneflow/python/framework/register_blob_method_util.py
  oneflow/python/framework/remote_blob.py
  oneflow/python/ops/get_variable.py
Labels: automerge, eager, enhancement, system

#4143 Remove excessive log print in ClusterInstruction
  oneflow/core/job/cluster_instruction.cpp
Labels: automerge, enhancement, system

#4142 MLIR ctrl edge
  oneflow/core/job/job_build_and_infer_ctx.cpp
  oneflow/core/job_rewriter/ir_pass.cpp
  oneflow/ir/include/OneFlow/OneFlowOps.td
  oneflow/ir/lib/OneFlow/OneFlowOps.cpp
  oneflow/ir/oneflow-translate/include/OneFlow/MLIROneFlowTranslation.h
  oneflow/ir/oneflow-translate/lib/OneFlow/MLIROneFlowTranslation.cpp
  oneflow/ir/test/OneFlow/relu.mlir
  oneflow/python/test/networks/bert.py
  oneflow/python/test/networks/pretrain.py
  oneflow/python/test/networks/test_bert.py
Labels: feature, system

#4148 Refactor string symbol
  oneflow/api/python/symbol/string_symbol.cpp
  oneflow/api/python/symbol/symbol.cpp
  oneflow/core/eager/eager_oneflow.cpp
  oneflow/core/framework/symbol_id_cache.cpp
  oneflow/core/vm/string_instruction_type.cpp
  oneflow/core/vm/string_instruction_type_test.cpp
  oneflow/core/vm/string_symbol.cpp
  oneflow/core/vm/string_symbol.h
  oneflow/core/vm/symbol_storage.cpp
  oneflow/core/vm/symbol_storage.h
  oneflow/core/vm/test_util.cpp
  oneflow/python/eager/symbol_storage.py
  oneflow/python/eager/vm_util.py
Labels: enhancement, system

#4144 Migrate parallel_cast to user op
  oneflow/core/graph/boxing/boxing_logger.cpp
  oneflow/core/job/sbp_parallel.cpp
  oneflow/core/job/sbp_parallel.h
  oneflow/core/job_rewriter/auto_mixed_precision.cpp
  oneflow/core/job_rewriter/auto_mixed_precision_lists.cpp
  oneflow/core/job_rewriter/autograd.cpp
  oneflow/core/job_rewriter/do_parallel_cast_before_widening_type_cast_pass.cpp
  oneflow/core/job_rewriter/indexed_slices_optimizer_rewrite_pass.cpp
  oneflow/core/job_rewriter/parallel_cast_grad.cpp
  oneflow/core/job_rewriter/prune_parallel_cast_op_pass.cpp
  oneflow/core/kernel/identity_kernel.cpp
  oneflow/core/operator/op_conf.proto
  oneflow/core/operator/parallel_cast_op.cpp
  oneflow/python/framework/ops.py
  oneflow/python/test/ops/test_parallel_cast.py
  oneflow/user/kernels/identity_kernel.cpp
  oneflow/user/ops/parallel_cast_op.cpp
Labels: automerge, enhancement, op, refactor

#4152 Remove useless logical2sorted_in/out_box
  oneflow/core/graph/logical_node.h
  oneflow/core/graph/task_graph.cpp
Labels: automerge, purge, system

#4145 add remove_images_without_annotations for coco api
  oneflow/python/ops/user_data_ops.py
Labels: automerge, enhancement, op

#4155 Skip install openssl without docs, html
  cmake/third_party/openssl.cmake
Labels: automerge, build, enhancement

#4154 Mig vm instruction build
  cmake/cfg.cmake
  oneflow/api/python/deprecated.cpp
  oneflow/api/python/framework/instructions_builder.cpp
  oneflow/api/python/vm/id_generator.cpp
  oneflow/api/python/vm/id_util.cpp
  oneflow/api/python/vm/id_util.h
  oneflow/api/python/vm/id_util_api.h
  oneflow/api/python/vm/run_instruction.h
  oneflow/core/eager/eager_oneflow.cpp
  oneflow/core/eager/eager_oneflow.h
  oneflow/core/framework/instructions_builder.h
  oneflow/core/framework/interpreter.cpp
  oneflow/python/eager/vm_util.py
  oneflow/python/framework/c_api_util.py
  oneflow/python/framework/session_util.py
  oneflow/python/ops/user_op_builder.py
  oneflow/python/vm/id_util.py
Labels: automerge, eager, enhancement

#4156 Mig instruction build symbol api
  oneflow/api/python/framework/instructions_builder.cpp
  oneflow/api/python/symbol/symbol.cpp
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/framework/instructions_builder.h
  oneflow/core/framework/symbol_storage_util.h
  oneflow/python/eager/vm_util.py
  oneflow/python/framework/scope_symbol.py
Labels: automerge, eager, enhancement

#4160 Fix github letter case
  README.md
Labels: documentation, system

#4157 Mig instruction rest api
  oneflow/api/python/framework/instructions_builder.cpp
  oneflow/api/python/vm/id_generator.cpp
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/framework/instructions_builder.h
  oneflow/python/eager/vm_util.py
Labels: automerge, eager, enhancement

#4158 Refactor python instr build
  oneflow/init.py
  oneflow/python/eager/vm_util.py
  oneflow/python/framework/register_class_method_util.py
Labels: automerge, eager, enhancement

#4163 fix lamb grad functor
  oneflow/user/kernels/model_update_kernel_util.h
Labels: api, bug, op

#4141 Refine manylinux dockerfile
  docker/package/manylinux/CentOS-Base.repo
  docker/package/manylinux/Dockerfile
  docker/package/manylinux/build_wheel.py
  oneflow/python/test/ops/test_unary_elementwise_ops.py
Labels: automerge, ci, enhancement
