Repository Oneflow-Inc/oneflow, pull requests merged in 2021-02, with the labels that each got.

#4166 Smaller shape in reduce sum to prevent FP16 overflow
  oneflow/python/test/ops/test_reduce_sum.py
Labels: automerge, enhancement, test

#4098 compile llvm with add_subdirectory for ir_pass branch
  oneflow/ir/CMakeLists.txt
Labels: build, enhancement

#4167 remove test_initializer.py
  oneflow/python/test/ops/test_initializer.py
Labels: automerge, bug, test

#4168 Mig parallel conf util
  oneflow/api/python/framework/instructions_builder.cpp
  oneflow/api/python/framework/parallel_conf_util.cpp
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/framework/instructions_builder.h
  oneflow/core/framework/parallel_conf_util.cpp
  oneflow/core/framework/parallel_conf_util.h
  oneflow/core/framework/parallel_conf_util_test.cpp
  oneflow/core/job/parallel_desc_test.cpp
  oneflow/python/eager/vm_util.py
  oneflow/python/framework/compiler.py
  oneflow/python/framework/parallel_conf_util.py
  oneflow/python/framework/placement_context.py
  oneflow/python/framework/placement_util.py
  oneflow/python/framework/scope_symbol.py
  oneflow/python/ops/assign_op.py
  oneflow/python/ops/watch.py
Labels: automerge, eager, enhancement

#4169 fix slice_boxing s2s multi-machine when empty intersection
  oneflow/core/graph/boxing/slice_boxing_sub_task_graph_builder.cpp
Labels: automerge, bug, system

#4176 Dev fix reflection pad
  oneflow/python/ops/pad.py
  oneflow/python/test/ops/test_reflection_pad2d.py
  oneflow/user/kernels/reflection_pad2d_kernel.cpp
  oneflow/user/ops/reflection_pad2d_op.cpp
Labels: automerge, enhancement, op

#4175 Quick fix gen api syntax err
  tools/generate_oneflow_api.py
Labels: automerge, bug, python

#4159 Refactor boxing sub_task_builder
  oneflow/core/actor/naive_actor.cpp
  oneflow/core/graph/boxing/b21_sub_task_graph_builder.cpp
  oneflow/core/graph/boxing/b21_sub_task_graph_builder.h
  oneflow/core/graph/boxing/boxing_logger.cpp
  oneflow/core/graph/boxing/boxing_logger.h
  oneflow/core/graph/boxing/chain_sub_task_graph_builder.cpp
  oneflow/core/graph/boxing/chain_sub_task_graph_builder.h
  oneflow/core/graph/boxing/collective_boxing_sub_task_graph_builder.cpp
  oneflow/core/graph/boxing/collective_boxing_sub_task_graph_builder.h
  oneflow/core/graph/boxing/naive_b2b_sub_task_graph_builder.cpp
  oneflow/core/graph/boxing/naive_b2b_sub_task_graph_builder.h
  oneflow/core/graph/boxing/naive_b2p_sub_task_graph_builder.cpp
  oneflow/core/graph/boxing/naive_b2p_sub_task_graph_builder.h
  oneflow/core/graph/boxing/one_to_one_sub_task_graph_builder.cpp
  oneflow/core/graph/boxing/one_to_one_sub_task_graph_builder.h
  oneflow/core/graph/boxing/slice_boxing_sub_task_graph_builder.cpp
  oneflow/core/graph/boxing/slice_boxing_sub_task_graph_builder.h
  oneflow/core/graph/boxing/sub_task_graph_builder.h
  oneflow/core/graph/boxing/sub_task_graph_builder_context.cpp
  oneflow/core/graph/boxing/sub_task_graph_builder_context.h
  oneflow/core/graph/boxing/sub_task_graph_builder_status_util.cpp
  oneflow/core/graph/boxing/sub_task_graph_builder_status_util.h
  oneflow/core/graph/boxing/sub_task_graph_builder_util.cpp
  oneflow/core/graph/boxing/sub_task_graph_builder_util.h
  oneflow/core/graph/boxing/to_interface_sub_task_graph_builder.cpp
  oneflow/core/graph/boxing/to_interface_sub_task_graph_builder.h
  oneflow/core/graph/boxing_identity_task_node.cpp
  oneflow/core/graph/boxing_identity_task_node.h
  oneflow/core/graph/boxing_s2s_all2all_pack_compute_task_node.h
  oneflow/core/graph/collective_boxing_pack_task_node.cpp
  oneflow/core/graph/collective_boxing_pack_task_node.h
  oneflow/core/graph/collective_boxing_unpack_task_node.cpp
  oneflow/core/graph/collective_boxing_unpack_task_node.h
  oneflow/core/graph/task_graph.cpp
  oneflow/core/job/task.proto
  oneflow/core/kernel/collective_boxing_pack_kernel.cpp
  oneflow/core/kernel/collective_boxing_unpack_kernel.cpp
  oneflow/core/operator/collective_boxing_pack_op.cpp
  oneflow/core/operator/collective_boxing_unpack_op.cpp
  oneflow/core/operator/op_conf.proto
Labels: automerge, enhancement, system

#4178 Check oneflow worker starts in remote docker
  oneflow/python/deprecated/init_cluster_env.py
Labels: automerge, ci, enhancement

#4173 Move flags from file generation to compile definition
  cmake/oneflow.cmake
  oneflow/api/python/flags.cpp
  oneflow/python/framework/config_util.py
  oneflow/python/framework/placement_util.py
  oneflow/python/framework/session_util.py
  oneflow/python/framework/sysconfig.py
  oneflow/python/test/ops/test_broadcast_normal.py
Labels: automerge, build, enhancement

#4179 Fix bug that get parallel_cast ouput in DoParallelCastBeforeWideningTypeCast pass
  oneflow/core/job_rewriter/do_parallel_cast_before_widening_type_cast_pass.cpp
Labels: automerge, bug, op

#4177 Fix typo in get_variable.py
  oneflow/python/ops/get_variable.py
Labels: automerge, documentation, op

#4183 Remove useless code
  oneflow/core/graph/exec_graph.h
  oneflow/core/graph/op_graph.cpp
  oneflow/core/graph/op_graph.h
  oneflow/core/job_rewriter/set_default_variable_conf.cpp
Labels: purge, system

#4185 Add some new Functions related to ToString.
  oneflow/core/framework/device_register_cpu.cpp
  oneflow/core/framework/device_register_gpu.cpp
  oneflow/core/framework/device_registry.cpp
  oneflow/core/framework/device_registry.h
  oneflow/core/framework/device_registry_manager.cpp
  oneflow/core/framework/device_registry_manager.h
  oneflow/core/framework/to_string.cpp
  oneflow/core/framework/to_string.h
  oneflow/core/graph/op_graph.cpp
Labels: enhancement, system

#4066 Implementation of SavedModel and InferenceSession
  .github/workflows/test.yml
  ci/test/1node_model_serve_test.sh
  cmake/cfg.cmake
  dev-requirements.txt
  oneflow/api/python/framework/framework.cpp
  oneflow/api/python/framework/framework.h
  oneflow/api/python/framework/framework_api.h
  oneflow/api/python/job_build/job_build_and_infer.cpp
  oneflow/api/python/job_build/job_build_and_infer.h
  oneflow/api/python/job_build/job_build_and_infer_api.h
  oneflow/core/common/protobuf.cpp
  oneflow/core/common/protobuf.h
  oneflow/core/job/job_build_and_infer_ctx.cpp
  oneflow/core/job/job_build_and_infer_ctx.h
  oneflow/core/job/job_conf.proto
  oneflow/core/job/oneflow.cpp
  oneflow/core/job_rewriter/add_input_output_ops_pass.cpp
  oneflow/core/serving/saved_model.proto
  oneflow/python/framework/c_api_util.py
  oneflow/python/framework/compiler.py
  oneflow/python/framework/pull_util.py
  oneflow/python/framework/session_util.py
  oneflow/python/serving/__init__.py
  oneflow/python/serving/inference_session.py
  oneflow/python/serving/saved_model_builder.py
  oneflow/python/test/serving/alexnet.py
  oneflow/python/test/serving/imagenet_record_dataset.py
  oneflow/python/test/serving/resnet_model.py
  oneflow/python/test/serving/test_alexnet_save_and_load.py
  oneflow/python/test/serving/test_resnet_save_and_load.py
Labels: automerge, feature, system

#4190 Add ReplicationPad2D op
  oneflow/python/ops/pad.py
  oneflow/python/test/ops/test_replication_pad2d.py
  oneflow/user/kernels/pad2d_kernels.cpp
  oneflow/user/kernels/pad2d_kernels_util.cpp
  oneflow/user/kernels/pad2d_kernels_util.cu
  oneflow/user/kernels/pad2d_kernels_util.h
  oneflow/user/kernels/reflection_pad2d_kernel.cpp
  oneflow/user/kernels/reflection_pad2d_kernel_util.cpp
  oneflow/user/kernels/reflection_pad2d_kernel_util.cu
  oneflow/user/kernels/reflection_pad2d_kernel_util.h
  oneflow/user/ops/pad2d_ops.cpp
  oneflow/user/ops/pad_2d_seq.h
  oneflow/user/ops/reflection_pad2d_op.cpp
Labels: enhancement, op

#4191 Add Operator::InferInplaceObn2IbnIf
  oneflow/core/graph/exec_graph.cpp
  oneflow/core/graph/exec_graph.h
  oneflow/core/graph/task_graph.cpp
  oneflow/core/operator/operator.cpp
  oneflow/core/operator/operator.h
  oneflow/core/operator/user_op.cpp
  oneflow/core/operator/user_op.h
Labels: enhancement, system

#4200 Remove OpContext
  oneflow/core/eager/opkernel_object.cpp
  oneflow/core/eager/opkernel_object.h
  oneflow/core/graph/exec_graph.cpp
  oneflow/core/graph/exec_graph.h
  oneflow/core/graph/op_graph.cpp
  oneflow/core/kernel/runtime_blob_shape_infer_helper.cpp
  oneflow/core/operator/constant_like_op.cpp
  oneflow/core/operator/operator.cpp
  oneflow/core/operator/operator.h
  oneflow/core/operator/shape_elem_cnt_op.cpp
  oneflow/core/operator/shape_elem_cnt_op.h
  oneflow/core/operator/tensor_buffer_to_tensor_list_op.cpp
  oneflow/core/operator/tensor_list_to_tensor_buffer_op.cpp
  oneflow/core/operator/user_op.cpp
  oneflow/core/operator/user_op.h
  oneflow/core/operator/user_op_util.h
Labels: automerge, purge, system

#4188 fp16 registration pseudocode
  oneflow/core/common/data_type.h
  oneflow/core/common/fp16_data_type.h
  oneflow/core/framework/device_register_cpu.h
  oneflow/core/framework/device_register_gpu.h
  oneflow/core/framework/device_registry_manager.cpp
  oneflow/core/framework/to_string.cpp
Labels: enhancement, system

#4171 Packed all separated mem block for allocate memory speed up
  oneflow/core/job/improver.cpp
  oneflow/core/memory/memory_block.proto
  oneflow/core/memory/memory_case_util.cpp
  oneflow/core/memory/memory_case_util.h
  oneflow/core/register/register_manager.cpp
Labels: enhancement, system

#4172 add weight_decay arguments
  oneflow/python/ops/optimizer.py
  oneflow/python/test/ops/test_lamb.py
Labels: api, feature, op, python

#4211 Print backtrace when distributed CI failed
  .dockerignore
  .github/workflows/test.yml
  .gitignore
  ci/test/distributed_run.py
  ci/test/print_stack_from_core.sh
Labels: automerge, ci, enhancement

#4214 fix layernorm error
  oneflow/python/ops/layers.py
Labels: automerge, bug, enhancement, op

#4034 Add CTC Loss
  oneflow/python/ops/loss_ops.py
  oneflow/python/test/ops/test_ctc_loss.py
  oneflow/user/kernels/ctc_loss_kernel.cpp
  oneflow/user/kernels/ctc_loss_kernel_util.cpp
  oneflow/user/kernels/ctc_loss_kernel_util.cu
  oneflow/user/kernels/ctc_loss_kernel_util.h
  oneflow/user/ops/ctc_loss_op.cpp
Labels: automerge, enhancement, op

#4213 Mig op conf sym
  cmake/cfg.cmake
  oneflow/api/python/deprecated.cpp
  oneflow/api/python/framework/instructions_builder.cpp
  oneflow/api/python/symbol/op_conf_symbol.cpp
  oneflow/core/eager/eager_oneflow.cpp
  oneflow/core/eager/init_symbol_instruction_type.cpp
  oneflow/core/eager/init_symbol_instruction_type_test.cpp
  oneflow/core/eager/opkernel_instruction_type.cpp
  oneflow/core/eager/opkernel_instruction_type_test.cpp
  oneflow/core/eager/transport_blob_instruction_type_test.cpp
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/framework/instructions_builder.h
  oneflow/core/framework/symbol_id_cache.cpp
  oneflow/core/operator/op_conf_symbol.cpp
  oneflow/core/operator/op_conf_symbol.h
  oneflow/core/vm/symbol_storage.cpp
  oneflow/core/vm/symbol_storage.h
  oneflow/python/eager/vm_util.py
Labels: automerge, eager, enhancement

#4216 increase rtol atol
  oneflow/python/test/ops/test_lamb.py
Labels: automerge, bug, ci, enhancement, test

#4212 Mig opkernel obj
  oneflow/api/python/framework/instructions_builder.cpp
  oneflow/api/python/framework/object.cpp
  oneflow/api/python/framework/object_storage.cpp
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/framework/instructions_builder.h
  oneflow/core/framework/object.cpp
  oneflow/core/framework/object.h
  oneflow/core/framework/object_storage.cpp
  oneflow/core/framework/object_storage.h
  oneflow/core/framework/opkernel_object.cpp
  oneflow/core/framework/opkernel_object.h
  oneflow/python/eager/object_storage.py
  oneflow/python/eager/opkernel_object.py
  oneflow/python/eager/vm_util.py
Labels: automerge, eager, enhancement

#4204 Tick per machine
  oneflow/core/graph_impl/logical_node.cpp
  oneflow/core/graph_impl/src_subset_tick_compute_task_node.cpp
  oneflow/core/job_rewriter/autotick.cpp
  oneflow/core/operator/op_conf.proto
  oneflow/core/operator/src_subset_tick_op.cpp
Labels: automerge, enhancement, system

#4207 Sink tick in main job
  oneflow/core/graph_impl/logical_node.cpp
  oneflow/core/job/critical_section.proto
  oneflow/core/job/critical_section_desc.cpp
  oneflow/core/job/critical_section_desc.h
  oneflow/core/job/oneflow.cpp
  oneflow/core/job_rewriter/autotick.cpp
  oneflow/core/job_rewriter/autotick.h
  oneflow/core/job_rewriter/job_completer.cpp
Labels: automerge, enhancement, system

#4223 Vectorized linking main job
  oneflow/core/graph_impl/logical_node.cpp
  oneflow/core/job/oneflow.cpp
  oneflow/core/job_rewriter/autotick.cpp
Labels: automerge, enhancement, system

#4225 Multi reentrant lock
  oneflow/core/actor/wait_and_send_ids_compute_actor.cpp
  oneflow/core/actor/wait_and_send_ids_compute_actor.h
  oneflow/core/common/range.cpp
  oneflow/core/common/range.h
  oneflow/core/graph_impl/logical_node.cpp
  oneflow/core/job/oneflow.cpp
  oneflow/core/job_rewriter/autotick.cpp
Labels: automerge, enhancement, system

#4219 Refactor InferBatchAxis
  oneflow/core/graph/op_graph.cpp
  oneflow/core/job/job_build_and_infer_ctx.cpp
  oneflow/core/operator/distribute_add_op.cpp
  oneflow/core/operator/distribute_clone_op.cpp
  oneflow/core/operator/distribute_concat_op.cpp
  oneflow/core/operator/distribute_split_op.cpp
  oneflow/core/operator/dynamic_binary_split_concat_op.cpp
  oneflow/core/operator/identity_op.cpp
  oneflow/core/operator/operator.cpp
  oneflow/core/operator/operator.h
  oneflow/core/operator/user_op.cpp
  oneflow/core/operator/user_op.h
Labels: automerge, enhancement, system

#4221 NCCL use compute stream to memory cost & speed up
  oneflow/core/graph/op_graph.h
  oneflow/core/graph/task_graph.cpp
  oneflow/core/job/resource.proto
  oneflow/core/job/resource_desc.cpp
  oneflow/core/job/resource_desc.h
  oneflow/core/job_rewriter/insert_nccl_logical_op_pass.cpp
  oneflow/core/job_rewriter/job_completer.cpp
  oneflow/python/framework/config_util.py
  oneflow/python/test/ops/test_nccl_use_compute_stream.py
  oneflow/user/kernels/nccl_logical_kernels.cpp
  oneflow/user/ops/nccl_logical_ops.cpp
Labels: automerge, bottleneck, enhancement, system

#4174 Mig instruction build api about op conf
  oneflow/api/python/framework/instructions_builder.cpp
  oneflow/api/python/framework/object_storage.cpp
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/framework/instructions_builder.h
  oneflow/core/framework/object_storage.cpp
  oneflow/core/framework/object_storage.h
  oneflow/core/framework/opkernel_object.cpp
  oneflow/python/eager/vm_util.py
  oneflow/python/ops/user_op_builder.py
Labels: automerge, eager, enhancement

#4230 Remove keep_header_only and BlobDesc::is_body_disabled
  oneflow/core/eager/lazy_ref_blob_object.h
  oneflow/core/graph/chain_graph.cpp
  oneflow/core/graph/op_graph.cpp
  oneflow/core/graph/task_graph.cpp
  oneflow/core/job/job_conf.proto
  oneflow/core/job/job_desc.h
  oneflow/core/job/oneflow.cpp
  oneflow/core/job_rewriter/add_keep_header_only_op_conf.cpp
  oneflow/core/job_rewriter/add_keep_header_only_op_conf.h
  oneflow/core/job_rewriter/auto_mixed_precision_lists.cpp
  oneflow/core/job_rewriter/job_completer.cpp
  oneflow/core/kernel/keep_header_only_kernel.cpp
  oneflow/core/kernel/keep_header_only_kernel.h
  oneflow/core/kernel/runtime_blob_shape_infer_helper.cpp
  oneflow/core/kernel/user_kernel.cpp
  oneflow/core/operator/arg_modifier_signature.proto
  oneflow/core/operator/broadcast_to_compatible_with_op.cpp
  oneflow/core/operator/dynamic_reshape_op.cpp
  oneflow/core/operator/keep_header_only_op.cpp
  oneflow/core/operator/keep_header_only_op.h
  oneflow/core/operator/op_conf.proto
  oneflow/core/operator/shape_elem_cnt_op.cpp
  oneflow/core/operator/user_op.cpp
  oneflow/core/register/blob_desc.cpp
  oneflow/core/register/blob_desc.h
  oneflow/core/register/blob_desc.proto
  oneflow/core/register/register_manager.cpp
  oneflow/core/register/runtime_blob_desc.cpp
  oneflow/core/register/runtime_blob_desc.h
  oneflow/core/register/runtime_register_desc.cpp
  oneflow/core/register/runtime_register_desc.h
  oneflow/python/framework/function_util.py
  oneflow/python/test/ops/test_TestReshape4KeepHeaderOnly.py
  oneflow/python/test/ops/test_keep_header_only_cpu.py
  oneflow/user/kernels/test_kernels.cpp
  oneflow/user/ops/broadcast_like_op.cpp
  oneflow/user/ops/cast_like_op.cpp
  oneflow/user/ops/conv_op.cpp
  oneflow/user/ops/dim_gather_op.cpp
  oneflow/user/ops/dropout_op.cpp
  oneflow/user/ops/generate_random_batch_permutation_indices_op.cpp
  oneflow/user/ops/nd_index_slice_ops.cpp
  oneflow/user/ops/reduce_like_ops.cpp
  oneflow/user/ops/reshape_like_op.cpp
  oneflow/user/ops/slice_op.cpp
  oneflow/user/ops/split_like_op.cpp
  oneflow/user/ops/test_ops.cpp
  oneflow/user/ops/unsorted_segment_sum_op.cpp
  oneflow/user/ops/zero_like_op.cpp
  oneflow/xrt/launch_op.cpp
Labels: automerge, purge, refactor, system

#4233 OpTest: add tf allow memory growth to prevent OOM
  oneflow/python/test/ops/test_batch_normalization.py
  oneflow/python/test/ops/test_broadcast_like.py
  oneflow/python/test/ops/test_cast.py
  oneflow/python/test/ops/test_deconv2d.py
  oneflow/python/test/ops/test_fuse_cast_scale.py
  oneflow/python/test/ops/test_reduce_ops.py
  oneflow/python/test/ops/test_reduce_opsV2.py
  oneflow/python/test/ops/test_reshapeV2.py
  oneflow/python/test/ops/test_summary.py
  oneflow/python/test/ops/test_transpose.py
  oneflow/python/test/ops/test_util.py
  oneflow/python/test/ops/test_watch_diff.py
Labels: automerge, bug, test

#4234 Refactor ctrl server and client
  oneflow/core/control/ctrl_client.cpp
  oneflow/core/control/ctrl_client.h
  oneflow/core/control/ctrl_server.cpp
  oneflow/core/control/ctrl_server.h
  oneflow/core/control/rpc_client.cpp
  oneflow/core/control/rpc_client.h
  oneflow/core/control/rpc_server.cpp
  oneflow/core/control/rpc_server.h
Labels: automerge, enhancement, system

#4227 Remove get local work stream id api
  oneflow/core/actor/actor.cpp
  oneflow/core/actor/actor.h
  oneflow/core/graph/boxing/sub_task_graph_builder_context.cpp
  oneflow/core/graph/copy_task_node.cpp
  oneflow/core/graph/copy_task_node.h
  oneflow/core/graph/task_graph.cpp
  oneflow/core/graph/task_node.cpp
  oneflow/core/graph/task_node.h
  oneflow/core/job/id_manager.cpp
  oneflow/core/job/id_manager.h
  oneflow/core/job/id_manager_test.cpp
Labels: automerge, purge, refactor, system

#4232 bugfix: nccl logical op/kernel when nccl version > 2.7
  oneflow/user/kernels/nccl_logical_kernels.cpp
Labels: automerge, bug, system

#4231 remove partial tick
  oneflow/core/graph/task_graph.cpp
  oneflow/core/kernel/partial_tick_kernel.cpp
  oneflow/core/kernel/partial_tick_kernel.h
  oneflow/core/operator/op_conf.proto
  oneflow/core/operator/partial_tick_op.cpp
  oneflow/core/operator/partial_tick_op.h
Labels: automerge, enhancement, refactor, system

#4237 Fix a small typo of typing.Numpy docs
  oneflow/python/framework/typing.py
Labels: automerge, documentation, op

#4235 Add ctrl conf
  oneflow/core/control/bootstrap_client.h
  oneflow/core/control/bootstrap_server.h
  oneflow/core/control/ctrl_bootstrap.cpp
  oneflow/core/control/ctrl_bootstrap.h
  oneflow/core/control/ctrl_bootstrap.proto
  oneflow/core/control/ctrl_client.cpp
  oneflow/core/control/ctrl_client.h
  oneflow/core/control/host_list_bootstrap_client.cpp
  oneflow/core/control/host_list_bootstrap_client.h
  oneflow/core/control/host_list_bootstrap_server.cpp
  oneflow/core/control/host_list_bootstrap_server.h
  oneflow/core/control/rpc_client.cpp
  oneflow/core/control/rpc_client.h
  oneflow/core/job/env_desc.h
Labels: automerge, enhancement, system

#4241 fix reduce_sum_like sbp
  oneflow/user/ops/reduce_like_ops.cpp
Labels: automerge, bug, op

#4243 Refine ci test and logging
  .github/workflows/test.yml
  ci/test/1node_op_test.sh
  oneflow/python/test/models/1node_test.py
  oneflow/python/test/ops/test_unary_elementwise_ops.py
Labels: automerge, ci, enhancement

#4206 Migrate sigmoid_cross_entropy_with_logits to user op
  oneflow/core/job_rewriter/sigmoid_cross_entropy_grad.cpp
  oneflow/core/kernel/sigmoid_cross_entropy_kernel.cu
  oneflow/core/operator/op_conf.proto
  oneflow/core/operator/sigmoid_cross_entropy_op.cpp
  oneflow/python/ops/nn_ops.py
  oneflow/python/test/ops/test_sigmoid_cross_entropy.py
  oneflow/user/kernels/sigmoid_cross_entropy_kernel.cpp
  oneflow/user/kernels/sigmoid_cross_entropy_kernel.cu
  oneflow/user/kernels/sigmoid_cross_entropy_kernel.h
  oneflow/user/ops/sigmoid_cross_entropy_op.cpp
Labels: api, automerge, enhancement, op, python

#4068 Optimize RngTruncatedNormal
  oneflow/python/ops/initializer_util.py
Labels: automerge, enhancement, op

#4244 Refactor InferParallelSignature
  oneflow/core/graph/op_graph.cpp
  oneflow/core/job/job_build_and_infer_ctx.cpp
  oneflow/core/operator/distribute_add_op.cpp
  oneflow/core/operator/distribute_clone_op.cpp
  oneflow/core/operator/distribute_concat_op.cpp
  oneflow/core/operator/distribute_split_op.cpp
  oneflow/core/operator/image_decoder_random_crop_resize_op.cpp
  oneflow/core/operator/operator.cpp
  oneflow/core/operator/operator.h
Labels: automerge, enhancement, system

#4240 Refactor ctrl server client
  oneflow/core/control/ctrl_bootstrap.cpp
  oneflow/core/control/ctrl_bootstrap.h
  oneflow/core/control/ctrl_bootstrap.proto
  oneflow/core/control/ctrl_client.cpp
  oneflow/core/control/ctrl_client.h
  oneflow/core/control/ctrl_server.cpp
  oneflow/core/control/ctrl_server.h
  oneflow/core/control/ctrl_test.cpp
  oneflow/core/control/rpc_client.cpp
  oneflow/core/job/env_global_objects_scope.cpp
  oneflow/core/transport/transport_test_main.cpp
Labels: automerge, enhancement, refactor, system

#4247 only write auto gen header if different
  cmake/oneflow.cmake
  cmake/util.cmake
Labels: automerge, build, enhancement

#4252 fix write_file_if_different cmake error when file doesn't exist
  cmake/util.cmake
Labels: bug, build

#4251 Reuse operator object
  oneflow/core/graph/decode_h2d_compute_task_node.cpp
  oneflow/core/graph/logical_graph.cpp
  oneflow/core/graph/logical_node.h
  oneflow/core/graph/op_graph.h
  oneflow/core/graph_impl/case_compute_task_node.cpp
  oneflow/core/graph_impl/esac_compute_task_node.cpp
  oneflow/core/graph_impl/logical_node.cpp
  oneflow/core/graph_impl/repeat_compute_task_node.cpp
Labels: automerge, enhancement, system

#4209 support custom scope and cambricon int8 op list in qat
  oneflow/core/job/job_conf.proto
  oneflow/core/job/qat_config_def.cpp
  oneflow/core/job_rewriter/quantization_aware_training.cpp
  oneflow/python/framework/function_util.py
  oneflow/python/ops/quantize_ops.py
  oneflow/python/test/ops/test_quantization_aware_training.py
  oneflow/python/test/ops/test_quantize_op.py
  oneflow/user/kernels/fake_quantization_kernel.cpp
  oneflow/user/kernels/fake_quantization_kernel.cu
  oneflow/user/kernels/min_max_observer_kernel.cpp
  oneflow/user/kernels/min_max_observer_kernel.cu
  oneflow/user/kernels/moving_average_min_max_observer_kernel.cpp
  oneflow/user/kernels/moving_average_min_max_observer_kernel.cu
  oneflow/user/ops/fake_quantization_op.cpp
  oneflow/user/ops/min_max_observer_op.cpp
  oneflow/user/ops/moving_average_min_max_observer_op.cpp
Labels: automerge, enhancement, system

#4250 fix reduce ops sbp
  oneflow/core/operator/reduce_sbp_util.cpp
  oneflow/core/operator/reduce_sbp_util.h
  oneflow/user/ops/broadcast_like_op.cpp
  oneflow/user/ops/reduce_like_ops.cpp
  oneflow/user/ops/reduce_ops.cpp
Labels: automerge, bug, op

#4255 1 node 2 node script add export PYTHONUNBUFFERED=1
  ci/test/1node_op_test.sh
  ci/test/2node_op_test.sh
Labels: automerge, ci, enhancement

#4236 disable_group_boxing and change nccl logical order to dst
  oneflow/core/job/resource.proto
  oneflow/core/job_rewriter/insert_nccl_logical_op_pass.cpp
  oneflow/core/job_rewriter/job_completer.cpp
  oneflow/python/framework/config_util.py
  oneflow/python/test/ops/test_nccl_use_compute_stream.py
Labels: api, automerge, enhancement, feature, system

#4194 New version tensor with blob combined
  oneflow/core/framework/device.h
  oneflow/core/framework/tensor.h
  oneflow/core/framework/tensor_impl.cpp
  oneflow/core/framework/tensor_impl.h
Labels: automerge, feature, system

#4253 Reduce unittest cost
  oneflow/python/test/ops/test_activations.py
  oneflow/python/test/ops/test_argmax.py
  oneflow/python/test/ops/test_argsort.py
  oneflow/python/test/ops/test_argwhere.py
  oneflow/python/test/ops/test_batch_normalization.py
  oneflow/python/test/ops/test_boxing_v2.py
  oneflow/python/test/ops/test_broadcast_logical_ops.py
  oneflow/python/test/ops/test_fused_scale_tril.py
  oneflow/python/test/ops/test_in_top_k.py
  oneflow/python/test/ops/test_instance_norm_op.py
  oneflow/python/test/ops/test_leaky_relu.py
  oneflow/python/test/ops/test_masked_fill.py
  oneflow/python/test/ops/test_moments.py
  oneflow/python/test/ops/test_prelu.py
  oneflow/python/test/ops/test_smooth_l1_loss.py
  oneflow/python/test/ops/test_softmax.py
  oneflow/python/test/ops/test_sort.py
  oneflow/python/test/ops/test_sync_dynamic_resize.py
  oneflow/python/test/ops/test_top_k.py
  oneflow/python/test/ops/test_tril.py
  oneflow/python/test/ops/test_two_stage_reduce.py
  oneflow/python/test/ops/test_unary_elementwise_ops.py
  oneflow/python/test/ops/test_unsorted_segment_sum_model_parallel.py
  oneflow/python/test/ops/test_where.py
Labels: automerge, enhancement, purge, test

#4215 Mig stateless call
  oneflow/api/python/deprecated.cpp
  oneflow/api/python/framework/eager_blob_util.cpp
  oneflow/api/python/framework/instructions_builder.cpp
  oneflow/core/framework/blob_trait.cpp
  oneflow/core/framework/blob_trait.h
  oneflow/core/framework/eager_blob_util.cpp
  oneflow/core/framework/eager_blob_util.h
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/framework/instructions_builder.h
  oneflow/core/framework/object.cpp
  oneflow/core/framework/object.h
  oneflow/python/eager/blob_register.py
  oneflow/python/eager/boxing_util.py
  oneflow/python/eager/op_executor.py
  oneflow/python/eager/vm_util.py
  oneflow/python/framework/check_point_v2.py
  oneflow/python/framework/push_util.py
  oneflow/python/ops/get_variable.py
  tools/cfg/template/template.cfg.cpp
  tools/cfg/template/template.cfg.h
Labels: automerge, eager, enhancement

#4228 replace 'if ... else ...' with DeviceTag4DeviceType function.
  oneflow/core/graph/boxing/boxing_logger.cpp
  oneflow/core/job_rewriter/optimizer_placement_optimization_pass.cpp
  oneflow/user/summary/plan_to_physical_graph.cpp
Labels: automerge, enhancement, system

#4261 Turn off Aliyun 3rd party backup
  .github/workflows/test.yml
Labels: bug, ci

#4239 Dev multi optimizer
  oneflow/core/job/job_build_and_infer_ctx.cpp
  oneflow/core/job/job_conf.proto
  oneflow/core/job_rewriter/adam_optm.cpp
  oneflow/core/job_rewriter/auto_learning_rate.cpp
  oneflow/core/job_rewriter/generate_backward_and_optimizer_op_confs.cpp
  oneflow/core/job_rewriter/lamb_optm.cpp
  oneflow/core/job_rewriter/lars_optm.cpp
  oneflow/core/job_rewriter/momentum_optm.cpp
  oneflow/core/job_rewriter/optimizer.cpp
  oneflow/core/job_rewriter/optimizer.h
  oneflow/core/job_rewriter/rmsprop_optm.cpp
  oneflow/core/job_rewriter/sgd_optm.cpp
  oneflow/python/framework/function_util.py
  oneflow/python/ops/optimizer.py
  oneflow/python/test/ops/test_multi_optimizer.py
Labels: automerge, feature, system

#4267 Remove old version ofrecord load / decode
  cmake/cfg.cmake
  oneflow/core/actor/decode_compute_actor.cpp
  oneflow/core/actor/decode_compute_actor.h
  oneflow/core/actor/record_load_actor.cpp
  oneflow/core/actor/record_load_actor.h
  oneflow/core/actor/wait_and_send_ids_compute_actor.h
  oneflow/core/graph/decode_compute_task_node.cpp
  oneflow/core/graph/decode_compute_task_node.h
  oneflow/core/graph/logical_node.h
  oneflow/core/graph/record_load_compute_task_node.cpp
  oneflow/core/graph/record_load_compute_task_node.h
  oneflow/core/graph_impl/logical_node.cpp
  oneflow/core/graph_impl/source_tick_compute_task_node.cpp
  oneflow/core/job/job_build_and_infer_ctx.cpp
  oneflow/core/job/task.proto
  oneflow/core/job_rewriter/complete_ofrecord_decoder.cpp
  oneflow/core/job_rewriter/record_load_autotick.cpp
  oneflow/core/kernel/decode_ofrecord_kernel.cpp
  oneflow/core/kernel/decode_ofrecord_kernel.h
  oneflow/core/kernel/kernel.proto
  oneflow/core/kernel/record_load_kernel.cpp
  oneflow/core/kernel/record_load_kernel.h
  oneflow/core/operator/decode_ofrecord_op.cpp
  oneflow/core/operator/decode_ofrecord_op.h
  oneflow/core/operator/op_conf.proto
  oneflow/core/operator/record_load_op.cpp
  oneflow/core/operator/record_load_op.h
  oneflow/core/record/encode_case_util.h
  oneflow/core/record/image.proto
  oneflow/core/record/image_preprocess.cpp
  oneflow/core/record/image_preprocess.h
  oneflow/core/record/ofrecord_bytes_list_decoder.cpp
  oneflow/core/record/ofrecord_bytes_list_decoder.h
  oneflow/core/record/ofrecord_bytes_list_encoder.cpp
  oneflow/core/record/ofrecord_bytes_list_encoder.h
  oneflow/core/record/ofrecord_decoder.cpp
  oneflow/core/record/ofrecord_decoder.h
  oneflow/core/record/ofrecord_encoder.cpp
  oneflow/core/record/ofrecord_encoder.h
  oneflow/core/record/ofrecord_jpeg_decoder.cpp
  oneflow/core/record/ofrecord_jpeg_decoder.h
  oneflow/core/record/ofrecord_jpeg_encoder.cpp
  oneflow/core/record/ofrecord_jpeg_encoder.h
  oneflow/core/record/ofrecord_raw_decoder.cpp
  oneflow/core/record/ofrecord_raw_decoder.h
  oneflow/core/record/ofrecord_raw_encoder.cpp
  oneflow/core/record/ofrecord_raw_encoder.h
  oneflow/core/record/ofrecord_reader.cpp
  oneflow/core/record/ofrecord_reader.h
  oneflow/python/ops/data_ops.py
Labels: automerge, purge, refactor, system

#4262 Refactor GenKernelConf
  oneflow/core/eager/opkernel_object.cpp
  oneflow/core/graph/exec_graph.cpp
  oneflow/core/graph/op_graph.h
  oneflow/core/operator/operator.cpp
  oneflow/core/operator/operator.h
  oneflow/core/operator/user_op.cpp
  oneflow/core/operator/user_op.h
Labels: automerge, enhancement, system

#4257 Tensor for autograd
  oneflow/core/framework/tensor.h
  oneflow/core/framework/tensor_arg.cpp
  oneflow/core/framework/tensor_arg.h
  oneflow/core/framework/tensor_impl.h
Labels: automerge, feature, system

#4271 Add InferLogicalOutBlobDescs for system ops
  oneflow/core/operator/assign_op.cpp
  oneflow/core/operator/broadcast_to_compatible_with_op.cpp
  oneflow/core/operator/callback_notify_op.cpp
  oneflow/core/operator/callback_notify_op.h
  oneflow/core/operator/case_op.cpp
  oneflow/core/operator/case_op.h
  oneflow/core/operator/constant_like_op.cpp
  oneflow/core/operator/device_tick_op.cpp
  oneflow/core/operator/device_tick_op.h
  oneflow/core/operator/distribute_add_op.cpp
  oneflow/core/operator/distribute_clone_op.cpp
  oneflow/core/operator/distribute_concat_op.cpp
  oneflow/core/operator/distribute_split_op.cpp
  oneflow/core/operator/dst_subset_tick_op.cpp
  oneflow/core/operator/esac_op.cpp
  oneflow/core/operator/esac_op.h
  oneflow/core/operator/foreign_input_op.cpp
  oneflow/core/operator/foreign_input_op.h
  oneflow/core/operator/foreign_output_op.cpp
  oneflow/core/operator/foreign_output_op.h
  oneflow/core/operator/foreign_watch_op.cpp
  oneflow/core/operator/foreign_watch_op.h
  oneflow/core/operator/identity_op.cpp
  oneflow/core/operator/indexed_slices_reduce_sum_op.cpp
  oneflow/core/operator/input_op.cpp
  oneflow/core/operator/input_op.h
  oneflow/core/operator/interface_op_util.cpp
  oneflow/core/operator/interface_op_util.h
  oneflow/core/operator/learning_rate_schedule_op.cpp
  oneflow/core/operator/model_init_op.cpp
  oneflow/core/operator/model_load_op.cpp
  oneflow/core/operator/model_save_op.cpp
  oneflow/core/operator/output_op.cpp
  oneflow/core/operator/output_op.h
  oneflow/core/operator/reentrant_lock_op.cpp
  oneflow/core/operator/reentrant_lock_op.h
  oneflow/core/operator/return_op.cpp
  oneflow/core/operator/return_op.h
  oneflow/core/operator/shape_elem_cnt_op.cpp
  oneflow/core/operator/shape_elem_cnt_op.h
  oneflow/core/operator/sink_tick_op.cpp
  oneflow/core/operator/sink_tick_op.h
  oneflow/core/operator/source_tick_op.cpp
  oneflow/core/operator/source_tick_op.h
  oneflow/core/operator/src_subset_tick_op.cpp
  oneflow/core/operator/sync_dynamic_resize_op.cpp
  oneflow/core/operator/tensor_buffer_to_tensor_list_op.cpp
  oneflow/core/operator/tensor_list_split_op.cpp
  oneflow/core/operator/tensor_list_to_tensor_buffer_op.cpp
  oneflow/core/operator/tick_op.cpp
  oneflow/core/operator/tick_op.h
  oneflow/core/operator/unique_with_counts_op.cpp
  oneflow/core/operator/variable_op.cpp
  oneflow/core/operator/variable_op.h
  oneflow/core/operator/wait_and_send_ids_op.cpp
  oneflow/core/operator/wait_and_send_ids_op.h
Labels: automerge, enhancement, system

#4218 Mig instruction build stateless call rel api
  oneflow/api/python/framework/instructions_builder.cpp
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/framework/instructions_builder.h
  oneflow/python/eager/boxing_util.py
  oneflow/python/eager/op_executor.py
  oneflow/python/eager/vm_util.py
  oneflow/python/framework/check_point_v2.py
  oneflow/python/framework/push_util.py
  oneflow/python/ops/__init__.py
  oneflow/python/ops/get_variable.py
Labels: eager, enhancement, system

#4274 Remove ChainGraph
  oneflow/core/graph/chain_graph.cpp
  oneflow/core/graph/chain_graph.h
  oneflow/core/graph/task_graph.cpp
  oneflow/core/job/id_manager.cpp
  oneflow/core/job/id_manager.h
Labels: automerge, purge, refactor, system

#4273 Add SetLogicalTensorDescInferFn for user ops
  oneflow/core/framework/infer_util.h
  oneflow/core/framework/user_op_registry.cpp
  oneflow/core/framework/user_op_registry.h
  oneflow/core/kernel/user_kernel.cpp
  oneflow/core/operator/boxing_op.cpp
  oneflow/core/operator/boxing_op.h
  oneflow/core/operator/cwise_op.cpp
  oneflow/core/operator/cwise_op.h
  oneflow/core/operator/dynamic_reshape_op.cpp
  oneflow/core/operator/user_op.cpp
  oneflow/core/operator/user_op.h
  oneflow/user/ops/categorical_ordinal_encode_op.cpp
  oneflow/user/ops/coco_reader_op.cpp
  oneflow/user/ops/conv_op.cpp
  oneflow/user/ops/deconv_op.cpp
  oneflow/user/ops/dim_gather_op.cpp
  oneflow/user/ops/image_preprocess_ops.cpp
  oneflow/user/ops/layer_norm_op.cpp
  oneflow/user/ops/nccl_logical_ops.cpp
  oneflow/user/ops/ofrecord_image_classification_reader_op.cpp
  oneflow/user/ops/ofrecord_reader_op.cpp
  oneflow/user/ops/onerec_reader_op.cpp
  oneflow/user/ops/partial_fc_sample_op.cpp
  oneflow/user/ops/reshape_op.cpp
  oneflow/user/ops/slice_op.cpp
  oneflow/user/ops/test_ops.cpp
  oneflow/user/ops/two_stage_reduce_ops.cpp
Labels: automerge, enhancement, op, system

#4245 tensor lazy init
  oneflow/core/common/error.cpp
  oneflow/core/common/error.h
  oneflow/core/common/error.proto
  oneflow/core/framework/tensor.cpp
  oneflow/core/framework/tensor.h
Labels: automerge, feature, system

#4270 GitHub workflow scheduler
  .github/workflows/test.yml
  oneflow/python/test/ops/test_quantize_op.py
Labels: automerge, ci, enhancement

#4281 fix xrt compile error, add InferLogicalOutBlobDescs
  oneflow/core/operator/op_conf.proto
  oneflow/xrt/launch_op.cpp
  oneflow/xrt/launch_op.h
  oneflow/xrt/passes/infer_shape_pass.cpp
  oneflow/xrt/passes/rebuild_job_pass.cpp
  oneflow/xrt/utility/message_attr.h
Labels: automerge, bug, system

#4282 fix XLA CI
  docker/package/manylinux/build_wheel.py
Labels: bug, ci

#4284 OpGraph use Operator::InferLogicalOutBlobDescsIf
  oneflow/core/graph/exec_graph.cpp
  oneflow/core/graph/exec_graph.h
  oneflow/core/graph/op_graph.cpp
  oneflow/core/graph/op_graph.h
  oneflow/core/job/job_build_and_infer_ctx.cpp
  oneflow/core/operator/boxing_op.h
  oneflow/core/operator/operator.cpp
  oneflow/core/operator/operator.h
Labels: enhancement, system

#4285 Allow XLA to fail and bump gpu workflow scheduler version
  .github/workflows/test.yml
Labels: automerge, ci, enhancement

#4287 Fix when no workflow pass scheduler
  .github/workflows/test.yml
Labels: bug, ci
