Repository Oneflow-Inc/oneflow, pull requests merged in 2021-07, with the labels that each got.

#5357 add missing JUST
  oneflow/api/python/framework/tensor.cpp
  oneflow/core/autograd/autograd_engine.cpp
  oneflow/core/autograd/autograd_engine.h
  oneflow/core/autograd/gradient_funcs/default.cpp
  oneflow/core/autograd/gradient_funcs/normalization.cpp
  oneflow/core/autograd/gradient_funcs/split_like.cpp
  oneflow/core/framework/attr_map_test.cpp
  oneflow/core/framework/instruction_replay.cpp
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/framework/op_expr.cpp
  oneflow/core/framework/op_interpreter/op_interpreter.cpp
  oneflow/core/framework/op_interpreter/op_interpreter_util.cpp
  oneflow/core/framework/tensor_impl.cpp
  oneflow/core/graph/exec_graph.cpp
  oneflow/core/graph/op_graph.cpp
  oneflow/core/job/cluster.cpp
  oneflow/core/job/job_build_and_infer_ctx.cpp
  oneflow/core/job/model_io_job.cpp
  oneflow/core/job/oneflow.cpp
  oneflow/core/job_rewriter/adam_optm.cpp
  oneflow/core/job_rewriter/dynamic_loss_scale_schedule_pass.cpp
  oneflow/core/job_rewriter/job_completer.cpp
  oneflow/core/job_rewriter/optimizer_placement_optimization_pass.cpp
  oneflow/core/operator/boxing_op.cpp
  oneflow/core/operator/broadcast_to_compatible_with_op.cpp
  oneflow/core/operator/distribute_add_op.cpp
  oneflow/core/operator/distribute_clone_op.cpp
  oneflow/core/operator/distribute_concat_op.cpp
  oneflow/core/operator/distribute_split_op.cpp
  oneflow/core/operator/image_decoder_random_crop_resize_op.cpp
  oneflow/core/operator/interface_op_util.cpp
  oneflow/core/operator/operator.cpp
  oneflow/core/rpc/lib/grpc.cpp
  oneflow/core/vm/vm_util.cpp
  oneflow/user/kernels/summary_kernels.cpp
  oneflow/user/ops/reshape_user_op_util.cpp
  oneflow/user/ops/scalar_by_tensor_op.cpp
  oneflow/user/ops/squeeze_op.cpp
  oneflow/user/ops/summary_ops.cpp
  oneflow/user/summary/event_writer_helper.cpp
  oneflow/user/summary/events_writer.cpp
Labels: automerge, bug, system

#5346 fix dropout module: return directly if not training
  oneflow/python/nn/modules/dropout.py
  oneflow/python/test/modules/test_dropout.py
Labels: automerge, bug, enhancement, system

#5354 Add pad grad func.
  oneflow/core/autograd/gradient_funcs/pad2d.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/core/functional/impl/nn_grad_functor.cpp
  oneflow/core/functional/scalar.h
  oneflow/python/nn/modules/padding.py
Labels: automerge, enhancement, op, system

#5118 Infer consistent tensor meta
  cmake/oneflow.cmake
  oneflow/core/framework/arg_tuple.cpp
  oneflow/core/framework/arg_tuple.h
  oneflow/core/framework/consistent_tensor_infer_cache.cpp
  oneflow/core/framework/consistent_tensor_infer_cache.h
  oneflow/core/framework/device.cpp
  oneflow/core/framework/device.h
  oneflow/core/framework/dtype.h
  oneflow/core/framework/op_expr.cpp
  oneflow/core/framework/op_expr.h
  oneflow/core/framework/op_interpreter/eager_consistent_op_interpreter.cpp
  oneflow/core/framework/op_interpreter/eager_mirrored_op_interpreter.cpp
  oneflow/core/framework/op_kernel.h
  oneflow/core/framework/py_blob_desc.h
  oneflow/core/framework/tensor.cpp
  oneflow/core/framework/tensor.h
  oneflow/core/framework/tensor_impl.cpp
  oneflow/core/framework/tensor_impl.h
  oneflow/core/framework/tensor_meta.h
  oneflow/core/framework/user_op_tensor.h
  oneflow/core/graph/op_graph.cpp
  oneflow/core/job/job_builder.cpp
  oneflow/core/job/oneflow.cpp
  oneflow/core/job/parallel_desc.cpp
  oneflow/core/job/parallel_desc.h
  oneflow/core/job/placement_scope.cpp
  oneflow/core/job/placement_scope.h
  oneflow/core/job/sbp_parallel.cpp
  oneflow/core/job/scope.cpp
  oneflow/core/job/scope.h
  oneflow/core/job_rewriter/split_sparse_softmax_cross_entropy_op_pass.cpp
  oneflow/core/kernel/blob_tensor_view.h
  oneflow/core/kernel/model_io_v2_kernel.cpp
  oneflow/core/kernel/user_kernel.cpp
  oneflow/core/kernel/user_kernel.h
  oneflow/core/operator/identity_op.cpp
  oneflow/core/operator/interface_op_util.cpp
  oneflow/core/operator/operator.cpp
  oneflow/core/operator/operator.h
  oneflow/extension/python/py_compute.cpp
  oneflow/user/image/image_util.h
  oneflow/xrt/launch_kernel.cpp
  oneflow/xrt/launch_op.cpp
  tools/cfg/template/template.cfg.h
Labels: automerge, eager, enhancement, system

#5329 Add triu op
  oneflow/core/autograd/gradient_funcs/triu.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/python/nn/modules/triu.py
  oneflow/python/test/modules/test_triu.py
  oneflow/python/test/tensor/test_tensor.py
  oneflow/user/kernels/triu_kernel.cpp
  oneflow/user/kernels/triu_kernel.cu
  oneflow/user/ops/triu_op.cpp
Labels: automerge, eager, enhancement, op, python

#5361 Add Latest News section in README
  README.md
Labels: automerge, documentation, system

#5362 Infer consistent tensor meta
  oneflow/core/framework/consistent_tensor_infer_cache.cpp
  oneflow/core/framework/consistent_tensor_infer_cache.h
  oneflow/core/framework/op_interpreter/eager_consistent_op_interpreter.cpp
Labels: automerge, enhancement, system

#5320 Dev remove default grad func
  oneflow/core/autograd/gradient_funcs/default.cpp
  oneflow/core/autograd/gradient_funcs/identity.cpp
  oneflow/core/framework/op_expr.cpp
  oneflow/core/framework/user_op_registry.cpp
  oneflow/core/framework/user_op_registry.h
  oneflow/core/framework/user_op_registry_manager.h
  oneflow/user/ops/arg_sort_op.cpp
  oneflow/user/ops/arg_where_op.cpp
  oneflow/user/ops/argmax_op.cpp
  oneflow/user/ops/assign_op.cpp
  oneflow/user/ops/bernoulli_op.cpp
  oneflow/user/ops/buffer_op.cpp
  oneflow/user/ops/cast_like_op.cpp
  oneflow/user/ops/cast_to_tick_op.cpp
  oneflow/user/ops/categorical_ordinal_encode_op.cpp
  oneflow/user/ops/coco_reader_op.cpp
  oneflow/user/ops/constant_op.cpp
  oneflow/user/ops/count_not_finite_op.cpp
  oneflow/user/ops/dropout_op.cpp
  oneflow/user/ops/eager_nccl_ops.cpp
  oneflow/user/ops/empty_op.cpp
  oneflow/user/ops/generate_random_batch_permutation_indices_op.cpp
  oneflow/user/ops/gpt_data_loader_op.cpp
  oneflow/user/ops/image_batch_align_op.cpp
  oneflow/user/ops/image_decode_op.cpp
  oneflow/user/ops/image_object_preprocess_ops.cpp
  oneflow/user/ops/image_preprocess_ops.cpp
  oneflow/user/ops/image_resize_ops.cpp
  oneflow/user/ops/image_target_resize_op.cpp
  oneflow/user/ops/in_top_k_op.cpp
  oneflow/user/ops/indexed_slices_reduce_sum_op.cpp
  oneflow/user/ops/l1_l2_regularize_gradient_op.cpp
  oneflow/user/ops/math_binary_broadcast_ops.cpp
  oneflow/user/ops/min_max_observer_op.cpp
  oneflow/user/ops/model_update_ops.cpp
  oneflow/user/ops/moving_average_min_max_observer_op.cpp
  oneflow/user/ops/nccl_logical_2d_sbp_ops.cpp
  oneflow/user/ops/nccl_logical_ops.cpp
  oneflow/user/ops/ofrecord_decoder_ops.cpp
  oneflow/user/ops/ofrecord_image_classification_reader_op.cpp
  oneflow/user/ops/ofrecord_reader_op.cpp
  oneflow/user/ops/one_hot_op.cpp
  oneflow/user/ops/onerec_decoder_op.cpp
  oneflow/user/ops/onerec_reader_op.cpp
  oneflow/user/ops/ones_like_op.cpp
  oneflow/user/ops/range_op.cpp
  oneflow/user/ops/reduce_like_ops.cpp
  oneflow/user/ops/sort_op.cpp
  oneflow/user/ops/ssp_variable_proxy_op.cpp
  oneflow/user/ops/summary_ops.cpp
  oneflow/user/ops/tensor_buffer_ops.cpp
  oneflow/user/ops/top_k_op.cpp
  oneflow/user/ops/unique_with_counts_op.cpp
  oneflow/user/ops/zero_like_op.cpp
Labels: automerge, enhancement, op, system

#5358 Use clang plugin to check Maybe variables are used
  .github/workflows/test.yml
  oneflow/core/framework/consistent_tensor_infer_cache.cpp
  oneflow/core/framework/instructions_builder.cpp
  tools/clang-plugin/.gitignore
  tools/clang-plugin/CMakeLists.txt
  tools/clang-plugin/CheckUnusedMaybe/CMakeLists.txt
  tools/clang-plugin/CheckUnusedMaybe/CheckUnusedMaybe.cpp
  tools/clang-plugin/CheckUnusedMaybe/unused_maybe_example.cpp
Labels: automerge, build, enhancement

#5363 Fix upsample bilinear bug
  oneflow/core/autograd/gradient_funcs/upsample.cpp
  oneflow/core/framework/op_expr_helper.cpp
  oneflow/python/test/modules/test_upsample2d.py
  oneflow/user/kernels/upsample_kernel.cpp
  oneflow/user/kernels/upsample_kernel.cu
  oneflow/user/ops/upsample_op.cpp
Labels: automerge, bug, ci, documentation, enhancement, feature, interface

#5364 Use functional api instead of op_expr_helper::XXXOp.
  oneflow/core/autograd/autograd_engine.cpp
  oneflow/core/autograd/autograd_meta.cpp
  oneflow/core/framework/tensor_arg.cpp
  oneflow/core/framework/tensor_arg.h
Labels: automerge, enhancement, system

#5367 Refine Simple CI and Clang analysis
  .github/workflows/simple.yml
  .github/workflows/test.yml
Labels: automerge, ci, enhancement

#5294 Add ctc_greedy_decoder op
  oneflow/python/ops/loss_ops.py
  oneflow/python/test/ops/test_ctc_greedy_decoder.py
  oneflow/user/kernels/ctc_greedy_decoder.cpp
  oneflow/user/kernels/ctc_greedy_decoder.cu
  oneflow/user/kernels/ctc_greedy_decoder.h
  oneflow/user/ops/ctc_loss_op.cpp
Labels: automerge, enhancement, op

#5368 Fix master not running Simple CI
  .github/workflows/simple.yml
Labels: automerge, ci, enhancement

#5351 Fix not contiguous ndarray to tensor bug
  oneflow/python/framework/input_blob_def.py
  oneflow/python/framework/push_util.py
  oneflow/python/framework/tensor.py
  oneflow/python/test/ops/test_global_function_input_output.py
  oneflow/python/test/tensor/test_tensor.py
Labels: automerge, bug, eager

#5291 Add hwloc for topology detection
  cmake/third_party.cmake
  cmake/third_party/hwloc.cmake
  oneflow/core/device/basic_device_descriptor_list.cpp
  oneflow/core/device/cuda_device_descriptor.cpp
  oneflow/core/device/cuda_device_descriptor.h
  oneflow/core/device/cuda_device_descriptor_class.cpp
  oneflow/core/device/cuda_util.cpp
  oneflow/core/device/device_descriptor_class.cpp
  oneflow/core/device/device_descriptor_class.h
  oneflow/core/device/net_ib_device_descriptor.cpp
  oneflow/core/device/net_ib_device_descriptor.h
  oneflow/core/device/net_ib_device_descriptor_class.cpp
  oneflow/core/device/net_socket_device_descriptor.cpp
  oneflow/core/device/net_socket_device_descriptor.h
  oneflow/core/device/net_socket_device_descriptor_class.cpp
  oneflow/core/device/node_device_descriptor.cpp
  oneflow/core/device/node_device_descriptor.h
  oneflow/core/device/topology_descriptor.cpp
  oneflow/core/device/topology_descriptor.h
  oneflow/core/job/resource.proto
  oneflow/core/job/resource_desc.h
  oneflow/core/kernel/image_decoder_random_crop_resize_kernel.cpp
  oneflow/core/memory/memory_allocator.cpp
  oneflow/core/thread/gpu_thread.cpp
  oneflow/python/framework/config_util.py
Labels: automerge, feature, system

#5280 Dev conv1d module
  docs/source/experimental.rst
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/python/nn/modules/conv.py
  oneflow/python/nn/modules/deconv.py
  oneflow/python/test/modules/test_conv.py
  oneflow/python/test/modules/test_conv1d.py
Labels: automerge, enhancement, feature, op

#5366 Fix upsample bilinear bug
  oneflow/python/test/modules/test_upsample2d.py
  oneflow/user/kernels/upsample_kernel.cpp
  oneflow/user/kernels/upsample_kernel.cu
  oneflow/user/kernels/upsample_kernel.h
Labels: api, automerge, bug, ci, documentation, eager, enhancement, feature

#5369 Add hint when apply FunctionNode second time
  oneflow/core/autograd/autograd_engine.cpp
Labels: automerge, documentation, eager

#5370 Use gh-action-scheduler-v2
  .github/workflows/test.yml
Labels: automerge, ci, enhancement

#5373 clang plugin skip more files
  .github/workflows/test.yml
Labels: automerge, bug, ci

#5376 Update readme for autoconf and libtool
  README.md
Labels: automerge, build, documentation

#5356 Add masked select module
  docs/source/experimental.rst
  oneflow/core/autograd/gradient_funcs/gather_nd.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/python/nn/modules/argwhere.py
  oneflow/python/nn/modules/masked_select.py
  oneflow/python/test/modules/test_masked_select.py
Labels: api, automerge, bug, ci, eager, enhancement, interface

#5360 [Random Generator] Part1: Dev random generator
  oneflow/api/python/framework/random_generator.cpp
  oneflow/core/framework/random_generator.cpp
  oneflow/core/framework/random_generator.cu
  oneflow/core/framework/random_generator.h
  oneflow/python/framework/generator.py
  oneflow/python/framework/register_class_method_util.py
  oneflow/python/test/generator/test_generator.py
Labels: automerge, feature, interface, system

#5381 Speedup reshape module by 5x.
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/python/nn/modules/reshape.py
Labels: automerge, enhancement, refactor, system

#5301 add flow.view
  docs/source/experimental.rst
  oneflow/python/nn/modules/reshape.py
  oneflow/python/test/modules/test_view.py
Labels: automerge, ci, eager, enhancement, interface

#5384 upload core when build with clang plugin
  .github/workflows/test.yml
Labels: automerge, bug, ci

#5374 replace ForeignJobInstance using JobInstance
  oneflow/api/python/framework/foreign_job_instance.cpp
  oneflow/api/python/framework/framework.h
  oneflow/api/python/framework/framework_api.h
  oneflow/api/python/framework/job_instance.cpp
  oneflow/core/job/job_instance.h
  oneflow/core/job/runtime_buffer_managers_scope.cpp
  oneflow/core/job/runtime_buffers_scope.cpp
  oneflow/core/job/session_global_objects_scope.cpp
  oneflow/core/kernel/callback_notify_kernel.cpp
  oneflow/core/kernel/foreign_input_kernel.cpp
  oneflow/core/kernel/foreign_output_kernel.cpp
  oneflow/python/framework/job_instance.py
Labels: automerge, enhancement, system

#5378 [Random Generator] Part2: Migrate functional dropout
  oneflow/api/python/functional/python_arg.cpp
  oneflow/core/autograd/gradient_funcs/adaptive_pool.cpp
  oneflow/core/autograd/gradient_funcs/bias_add.cpp
  oneflow/core/autograd/gradient_funcs/broadcast_binary_ops.cpp
  oneflow/core/autograd/gradient_funcs/deconv.cpp
  oneflow/core/autograd/gradient_funcs/squeeze.cpp
  oneflow/core/autograd/gradient_funcs/tensor_scalar_binary.cpp
  oneflow/core/autograd/gradient_funcs/unsqueeze.cpp
  oneflow/core/eager/eager_oneflow.cpp
  oneflow/core/eager/local_call_opkernel_phy_instr_operand.h
  oneflow/core/eager/opkernel_instruction_type.cpp
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/framework/instructions_builder.h
  oneflow/core/framework/op_interpreter.h
  oneflow/core/framework/op_interpreter/eager_consistent_op_interpreter.cpp
  oneflow/core/framework/op_interpreter/eager_mirrored_op_interpreter.cpp
  oneflow/core/framework/op_interpreter/op_interpreter.cpp
  oneflow/core/framework/op_interpreter/op_interpreter_util.cpp
  oneflow/core/framework/op_interpreter/op_interpreter_util.h
  oneflow/core/framework/random_generator.cpp
  oneflow/core/framework/random_generator.h
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/core/functional/value_types.h
  oneflow/python/nn/modules/dropout.py
  oneflow/user/kernels/dropout_kernel.cpp
  oneflow/user/kernels/random_mask_generator.cpp
  oneflow/user/kernels/random_mask_generator.cu
  oneflow/user/kernels/random_mask_generator.h
  oneflow/user/kernels/random_mask_like_kernel.cpp
  oneflow/user/kernels/random_mask_like_kernel.h
  oneflow/user/kernels/stateful_local_opkernel.h
  tools/generate_functional_api.py
Labels: automerge, enhancement, interface, system

#5380 Cast explicitily in unpack call to avoid confilt with Optional.
  oneflow/api/python/functional/py_function.h
  oneflow/api/python/functional/python_arg.h
  oneflow/api/python/functional/unpack_call.h
Labels: automerge, enhancement, refactor, system

#5388 hwloc disable shared
  cmake/third_party/hwloc.cmake
Labels: automerge, bug, build

#5387 NNGraphIf
  oneflow/core/framework/nn_graph.cpp
  oneflow/core/framework/nn_graph_if.h
Labels: automerge, enhancement, system

#5390 Fix clang plugin core file not found
  .github/workflows/simple.yml
  .github/workflows/test.yml
Labels: automerge, ci, enhancement

#5392 Delete useless code upsample
  oneflow/user/ops/upsample_op.cpp
Labels: automerge, bug, documentation, eager, enhancement, interface

#4130 Restruct Elementwise kernel
  oneflow/core/framework/user_op_kernel_registry.h
  oneflow/user/kernels/activation_kernels.cpp
  oneflow/user/kernels/activation_kernels.cu
  oneflow/user/kernels/activation_kernels.h
  oneflow/user/kernels/elementwise_xpu_kernel.cuh
  oneflow/user/kernels/elementwise_xpu_kernel.h
  oneflow/user/kernels/elu_kernel.cpp
  oneflow/user/kernels/elu_kernel.cu
  oneflow/user/kernels/hardsigmoid_kernel.cpp
  oneflow/user/kernels/hardsigmoid_kernel.cu
  oneflow/user/kernels/hardswish_kernel.cpp
  oneflow/user/kernels/hardswish_kernel.cu
  oneflow/user/kernels/hardtanh_kernel.cpp
  oneflow/user/kernels/hardtanh_kernel.cu
Labels: WIP, automerge, enhancement, op

#5385 Add conda env to Simple CI
  .github/workflows/simple.yml
Labels: automerge, ci, enhancement

#5396 Support uint dtype of constant op
  oneflow/core/kernel/util/cuda_arithemetic_interface.cu
  oneflow/core/kernel/util/cuda_arithemetic_interface.h
  oneflow/core/kernel/util/host_arithemetic_interface.cpp
  oneflow/core/kernel/util/host_arithemetic_interface.h
  oneflow/python/test/modules/test_constant.py
  oneflow/user/kernels/constant_kernel.cpp
Labels: automerge, bug, eager, enhancement

#5393 Fix bn track running stats
  oneflow/python/nn/modules/batchnorm.py
  oneflow/python/test/modules/test_batchnorm.py
Labels: bug, eager, enhancement, interface

#5391 add coco reader module
  oneflow/python/nn/modules/dataset.py
  oneflow/python/test/modules/test_dataset.py
Labels: automerge, eager, enhancement, op

#5398 fix-abs
  oneflow/user/kernels/math_unary_elementwise_func.h
Labels: automerge, bug, eager, enhancement

#5400 Add instruction on upgrade pip
  README.md
Labels: automerge, documentation, enhancement, python

#5402 add image normalize for eager
  oneflow/python/nn/modules/dataset.py
  oneflow/python/test/modules/test_image_normalize.py
Labels: automerge, eager, enhancement, op

#5324 Modules chunk
  docs/source/experimental.rst
  oneflow/python/nn/modules/chunk.py
  oneflow/python/nn/modules/slice.py
  oneflow/python/test/modules/test_chunk.py
Labels: api, automerge, eager, enhancement, feature, interface, op

#5408 Add new placement init func
  oneflow/api/python/symbol/placement_symbol.cpp
  oneflow/init.py
  oneflow/python/framework/env_util.py
  oneflow/python/oneflow_export.py
  tools/generate_oneflow_api.py
Labels: automerge, enhancement, system

#5306 flow.S/B/P
  oneflow/api/python/symbol/placement_symbol.cpp
  oneflow/api/python/symbol/sbp_symbol.cpp
  oneflow/core/object_msg/object_msg_core.h
  oneflow/init.py
  oneflow/python/framework/distribute.py
  oneflow/python/framework/env_util.py
  oneflow/python/oneflow_export.py
  tools/generate_oneflow_api.py
Labels: automerge, enhancement, python

#5379 Add tensor grad assginment
  docs/source/experimental.rst
  docs/source/optim.rst
  oneflow/api/python/framework/tensor.cpp
  oneflow/python/framework/tensor.py
  oneflow/python/nn/optimizer/optimizer.py
  oneflow/python/test/tensor/test_tensor.py
Labels: api, automerge, eager, enhancement

#5409 Delete maxpool failed test
  oneflow/python/test/modules/test_maxpool.py
Labels: automerge, bug, ci, documentation, eager, interface

#5386 Add flow xxx and tensor xxx autotest
  oneflow/python/test/modules/automated_test_util.py
  oneflow/python/test/modules/test_abs.py
  oneflow/python/test/modules/test_squeeze.py
Labels: api, automerge, ci, documentation, eager, enhancement, feature, interface, op

#5353 add bernoulli module
  docs/source/experimental.rst
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/random_functor.cpp
  oneflow/python/nn/modules/random_ops.py
  oneflow/python/test/modules/test_bernoulli.py
  oneflow/user/kernels/bernoulli_kernel.cpp
  oneflow/user/kernels/bernoulli_kernel.h
Labels: api, automerge, documentation, interface, op, python

#5204 Support inplace operations
  oneflow/api/python/framework/tensor.cpp
  oneflow/core/autograd/autograd_engine.cpp
  oneflow/core/eager/opkernel_instruction_type.cpp
  oneflow/core/framework/op_interpreter/eager_mirrored_op_interpreter.cpp
  oneflow/core/framework/tensor.cpp
  oneflow/core/framework/tensor.h
  oneflow/core/framework/tensor_impl.cpp
  oneflow/core/framework/tensor_impl.h
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/activation_functor.cpp
  oneflow/python/framework/tensor.py
  oneflow/python/nn/modules/activation.py
  oneflow/python/test/modules/test_activation.py
  oneflow/python/test/tensor/test_tensor.py
Labels: automerge, enhancement, system

#5423 Add arg skip_audit in build wheel
  ci/test/try_install.sh
  docker/package/manylinux/build_wheel.py
Labels: automerge, build, enhancement

#5426 Dev refine generator
  oneflow/api/python/framework/random_generator.cpp
  oneflow/core/framework/random_generator.h
  oneflow/core/framework/random_generator_impl.h
  oneflow/python/test/generator/test_generator.py
  oneflow/python/test/modules/test_bernoulli.py
  oneflow/python/test/modules/test_dropout.py
Labels: automerge, enhancement, system

#5427 Refactor build_wheel to support oneflowinc images
  .github/actions/whl/action.yml
  README.md
  docker/package/manylinux/build_wheel.py
Labels: automerge, build, enhancement

#5383 add pixelshufflev2 module
  oneflow/python/nn/modules/pixelshuffle.py
  oneflow/python/test/modules/test_pixel_shuffle.py
Labels: api, automerge, eager, feature, interface, op

#5419 Remove IOConf
  oneflow/core/job/job_set.proto
  oneflow/core/job/oneflow.cpp
  oneflow/core/job/resource.proto
  oneflow/core/job/session.cpp
  oneflow/core/job/session_global_objects_scope.cpp
  oneflow/python/framework/config_util.py
  oneflow/python/framework/session_util.py
  oneflow/python/serving/inference_session.py
Labels: automerge, purge, refactor, system

#5424 rm nn.Graph.train
  oneflow/python/nn/graph.py
  oneflow/python/test/graph/test_graph.py
Labels: automerge, bug, interface, python

#5431 remove --user
  README.md
Labels: automerge, documentation, python

#5434 remove device dtype params
  oneflow/python/nn/modules/batchnorm.py
  oneflow/python/test/modules/test_batchnorm.py
Labels: automerge, bottleneck, eager, enhancement

#5414 add launcher, update multi client launch and exit
  cmake/oneflow.cmake
  oneflow/api/python/env/env.cpp
  oneflow/api/python/env/env.h
  oneflow/api/python/env/env_api.h
  oneflow/core/control/ctrl_bootstrap.proto
  oneflow/core/job/env_global_objects_scope.cpp
  oneflow/core/job/env_global_objects_scope.h
  oneflow/core/job/global_for.cpp
  oneflow/core/job/global_for.h
  oneflow/core/rpc/lib/global_process_ctx.cpp
  oneflow/init.py
  oneflow/python/distributed/launch.py
  oneflow/python/framework/env_util.py
Labels: automerge, enhancement, feature, system

#5435 Refine Simple CI error output
  .github/workflows/simple.yml
  .github/workflows/test.yml
Labels: automerge, ci, enhancement

#5256 Smoothl1loss
  docs/source/experimental.rst
  oneflow/core/autograd/gradient_funcs/smoothl1_loss.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/core/functional/impl/nn_grad_functor.cpp
  oneflow/python/nn/modules/loss.py
  oneflow/python/test/modules/test_smoothl1loss.py
Labels: api, automerge, eager, feature, interface

#5413 Fea/nn graph/graph name
  oneflow/python/nn/graph.py
  oneflow/python/test/graph/test_graph.py
Labels: automerge, feature, interface, python

#5442 instruction builder return maybe
  oneflow/api/python/framework/instructions_builder.cpp
  oneflow/api/python/framework/tensor.cpp
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/framework/instructions_builder.h
Labels: api, automerge, enhancement, system

#5443 Fix concat backward bug
  oneflow/core/autograd/autograd_engine.cpp
  oneflow/core/autograd/gradient_funcs/concat.cpp
  oneflow/python/test/modules/test_concat.py
Labels: api, automerge, bug, ci, documentation, eager

#5446 fix pool gpu kernel
  oneflow/user/kernels/pool_gpu_kernel.cpp
Labels: automerge, bug, op

#5448 fix -1 index not support bug
  oneflow/python/framework/tensor.py
  oneflow/python/test/modules/test_slice.py
Labels: automerge, bottleneck, bug, eager, interface

#5407 MultiClientSession
  oneflow/init.py
  oneflow/python/framework/env_util.py
  oneflow/python/framework/multi_client_session.py
Labels: api, automerge, feature, python

#5432 Support inplace add
  docs/source/experimental.rst
  oneflow/core/autograd/autograd_engine.cpp
  oneflow/core/framework/tensor_arg.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/binary_functor.cpp
  oneflow/core/functional/impl/binary_functor.h
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/python/framework/tensor.py
  oneflow/python/nn/modules/activation.py
  oneflow/python/nn/modules/math_ops.py
  oneflow/python/nn/modules/utils.py
  oneflow/python/test/modules/test_add.py
Labels: automerge, eager, feature

#5450 ThreadMgr support AddPlan
  oneflow/core/job/runtime.cpp
  oneflow/core/thread/thread_manager.cpp
  oneflow/core/thread/thread_manager.h
Labels: automerge, enhancement, system

#5244 Dev maxpool series op 123d
  oneflow/core/autograd/gradient_funcs/pooling.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/core/functional/impl/nn_grad_functor.cpp
  oneflow/core/kernel/util/numeric_limits.cuh
  oneflow/core/kernel/util/numerics.cuh
  oneflow/python/nn/modules/pooling.py
  oneflow/python/ops/nn_ops.py
  oneflow/python/test/modules/test_pooling.py
  oneflow/user/kernels/pooling_kernel.cpp
  oneflow/user/kernels/pooling_kernel.cu
  oneflow/user/kernels/pooling_kernel_util.cpp
  oneflow/user/kernels/pooling_kernel_util.h
  oneflow/user/ops/pooling_op.cpp
Labels: automerge, eager, enhancement, interface, op

#5440 export Tensor only to python
  oneflow/api/python/framework/tensor.cpp
  oneflow/core/framework/tensor.cpp
  oneflow/core/framework/tensor.h
  oneflow/python/framework/tensor.py
  oneflow/python/framework/tensor_tuple_util.py
  oneflow/python/nn/modules/eq.py
  oneflow/python/nn/modules/ne.py
Labels: automerge, enhancement, system

#5452 Optimize reduce mean
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/python/nn/modules/activation.py
  oneflow/python/nn/modules/math_ops.py
  oneflow/python/nn/modules/reduce_ops.py
Labels: api, automerge, enhancement, system

#5457 Throw exception if check failed
  oneflow/api/python/functional/py_function.h
  oneflow/api/python/functional/unpack_call.h
  tools/generate_functional_api.py
Labels: automerge, enhancement, system

#5449 Dev add docstring
  docs/source/F.rst
  docs/source/index.rst
  oneflow/init.py
  oneflow/python/framework/docstr/__init__.py
  oneflow/python/framework/docstr/math_ops.py
  oneflow/python/framework/docstr/random.py
  oneflow/python/framework/docstr/utils.py
  oneflow/python/test/modules/test_functional_docstr.py
Labels: automerge, enhancement, python

#5460 Use functional copy instead of op_builder
  oneflow/core/framework/tensor.cpp
  oneflow/core/framework/tensor_arg.cpp
Labels: automerge, eager, enhancement

#5428 Add in_top_k function
  docs/source/experimental.rst
  oneflow/python/nn/modules/in_top_k.py
  oneflow/python/ops/math_ops.py
  oneflow/python/test/modules/test_in_top_k.py
Labels: automerge, enhancement, python

#5459 update HasAllMultiClientEnvVars()
  oneflow/python/framework/env_util.py
Labels: automerge, bug, enhancement, python

#5433 Optimize tensor getitem.
  oneflow/api/python/functional/common.cpp
  oneflow/api/python/functional/common.h
  oneflow/api/python/functional/python_arg.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/core/functional/tensor_index.cpp
  oneflow/core/functional/tensor_index.h
  oneflow/core/functional/value_types.h
  oneflow/python/framework/tensor.py
  tools/generate_functional_api.py
Labels: automerge, enhancement, op, refactor, system

#5436 Add autotest part1
  oneflow/python/test/modules/test_activation.py
  oneflow/python/test/modules/test_math_ops.py
Labels: automerge, documentation, eager, interface, test

#5461 hotfix image_batch_align
  oneflow/python/nn/modules/dataset.py
  oneflow/python/ops/user_data_ops.py
  oneflow/user/kernels/image_batch_align_kernel.cpp
  oneflow/user/ops/image_batch_align_op.cpp
Labels: automerge, bug, op

#5466 Rename now_grad_arg to current_grad
  oneflow/core/autograd/autograd_engine.cpp
  oneflow/core/autograd/autograd_meta.h
  oneflow/core/framework/tensor.h
  oneflow/core/framework/tensor_impl.cpp
  oneflow/core/framework/tensor_impl.h
Labels: automerge, eager, enhancement

#5462 Fix Tensor.grad setter bug
  oneflow/python/framework/tensor.py
  oneflow/python/nn/parameter.py
  oneflow/python/test/tensor/test_tensor.py
Labels: automerge, bug, eager

#5470 Remove cpu_op_eager and cuda_op_eager
  .github/workflows/test.yml
Labels: automerge, ci, enhancement

#5298 init of op diag
  docs/source/experimental.rst
  oneflow/core/autograd/gradient_funcs/diag.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/python/nn/modules/diag.py
  oneflow/python/ops/diag_ops.py
  oneflow/python/test/modules/test_diag.py
Labels: automerge, enhancement, interface, op

#5411 integrate nn.image.flip
  docs/source/experimental.rst
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/dataset_functor.cpp
  oneflow/python/nn/modules/dataset.py
  oneflow/python/test/modules/test_image_flip.py
Labels: automerge, feature, interface, python

#5473 fix param
  oneflow/python/nn/modules/pooling.py
  oneflow/python/test/modules/test_pooling.py
Labels: automerge, bug, eager, enhancement

#5467 Add autotest part2
  oneflow/python/test/modules/automated_test_util.py
  oneflow/python/test/modules/test_activation.py
  oneflow/python/test/modules/test_atan2.py
  oneflow/python/test/modules/test_math_ops.py
  oneflow/python/test/modules/test_sinh.py
Labels: api, automerge, feature, test

#5469 Fix issues in point of MultiClientSession
  oneflow/init.py
  oneflow/python/framework/env_util.py
  oneflow/python/framework/multi_client_session.py
  oneflow/python/framework/session_util.py
  oneflow/python/test/graph/test_multi_client_session.py
Labels: automerge, bug, python

#5471 add inplace method: Tensor.sin_
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/unary_functor.cpp
  oneflow/core/functional/impl/unary_functor.h
  oneflow/python/nn/modules/math_ops.py
  oneflow/python/test/modules/test_math_ops.py
Labels: automerge, enhancement, op

#5472 move generator test into ops folder to accelerate tests
  oneflow/python/test/ops/generator/test_generator.py
Labels: automerge, enhancement, test

#5420 Fea/nn graph/graph build ctx
  oneflow/api/python/framework/framework.h
  oneflow/api/python/functional/common.h
  oneflow/api/python/job_build/lazy_mode.cpp
  oneflow/api/python/symbol/scope_symbol.cpp
  oneflow/core/framework/attr_value_accessor.cpp
  oneflow/core/framework/consistent_tensor_infer_cache.cpp
  oneflow/core/framework/device.cpp
  oneflow/core/framework/op_interpreter/op_interpreter_util.cpp
  oneflow/core/framework/random_generator_impl.cpp
  oneflow/core/framework/tensor.cpp
  oneflow/core/framework/tensor_impl.cpp
  oneflow/core/framework/tensor_name_scope.cpp
  oneflow/core/job/job.proto
  oneflow/core/job/job_build_and_infer_ctx_mgr.cpp
  oneflow/core/job/lazy_mode.cpp
  oneflow/core/job/lazy_mode.h
  oneflow/python/framework/graph_build_util.py
  oneflow/python/framework/scope_util.py
  oneflow/python/nn/graph.py
  oneflow/python/test/graph/test_graph.py
  oneflow/xrt/tensorrt/trt_int8_calibrator.cpp
Labels: automerge, feature, interface, system

#5422 [Add] gather_nd scatter_nd
  docs/source/experimental.rst
  oneflow/core/autograd/gradient_funcs/scatter_nd.cpp
  oneflow/python/nn/modules/gather_nd.py
  oneflow/python/nn/modules/scatter_nd.py
  oneflow/python/ops/array_ops.py
  oneflow/python/test/modules/test_gather_nd.py
  oneflow/python/test/modules/test_scatter_nd.py
Labels: automerge, eager, enhancement, interface

#5480 fix ConstructOp without JUST
  oneflow/core/framework/consistent_tensor_infer_cache.cpp
  oneflow/core/operator/operator.cpp
Labels: automerge, enhancement, system

#5458 Lazy nn.Graph FeedInputOpExpr
  oneflow/api/python/framework/op_expr.cpp
  oneflow/core/framework/op_expr.cpp
  oneflow/core/framework/op_expr.h
  oneflow/core/framework/op_interpreter.h
  oneflow/core/framework/op_interpreter/lazy_op_interpreter.cpp
  oneflow/core/framework/op_interpreter/op_interpreter.cpp
  oneflow/core/job/job_build_and_infer_ctx.cpp
  oneflow/core/job/job_build_and_infer_ctx.h
  oneflow/core/operator/op_conf.proto
  oneflow/python/test/graph/test_input_op_expr.py
Labels: automerge, feature, interface, python, system

#5479 Multi-Client LogicalRun degenerate to PhysicalRun
  oneflow/core/eager/eager_oneflow.cpp
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/vm/id_generator.cpp
Labels: automerge, feature, system

#5481 Dev fix rmsprop ci fail
  oneflow/python/test/ops/test_optimizers.py
Labels: automerge, bug, ci, op, test

#5483 Fix default value not set bug
  oneflow/python/test/modules/automated_test_util.py
  oneflow/python/test/modules/test_constantpad2d.py
Labels: automerge, bug, documentation, eager, feature

#5332 jit_fuse_cast_scale
  cmake/oneflow.cmake
  oneflow/core/job_rewriter/ir_pass.cpp
  oneflow/ir/CMakeLists.txt
  oneflow/ir/include/OneFlow/CMakeLists.txt
  oneflow/ir/include/OneFlow/Conversion/OneFlowToTosa.h
  oneflow/ir/include/OneFlow/OneFlowOps.h
  oneflow/ir/include/OneFlow/OneFlowOps.td
  oneflow/ir/include/OneFlow/Passes.h
  oneflow/ir/lib/OneFlow/CMakeLists.txt
  oneflow/ir/lib/OneFlow/Conversion/OneFlowToTosa.cpp
  oneflow/ir/lib/OneFlow/OneFlowDialect.cpp
  oneflow/ir/lib/OneFlow/OneFlowOps.cpp
  oneflow/ir/lib/OneFlow/Passes.cpp
  oneflow/ir/oneflow-extension/CMakeLists.txt
  oneflow/ir/oneflow-extension/extension.cpp
  oneflow/ir/oneflow-opt/oneflow-opt.cpp
  oneflow/ir/oneflow-translate/lib/OneFlow/MLIROneFlowTranslation.cpp
  oneflow/ir/test/OneFlow/lower_to_llvm.mlir
  oneflow/ir/test/OneFlow/lower_to_tosa.mlir
  oneflow/ir/test/OneFlow/test_fuse_cast_scale.mlir
  oneflow/ir/test/OneFlow/test_fuse_cast_scale.mlir.py
Labels: feature, system

#5406 Dev flow.utils.data part1
  oneflow/python/test/dataloader/test_numpy_dataset.py
  oneflow/python/test/dataloader/test_tensor_dataset.py
  oneflow/python/utils/__init__.py
  oneflow/python/utils/data/__init__.py
  oneflow/python/utils/data/_utils/__init__.py
  oneflow/python/utils/data/_utils/collate.py
  oneflow/python/utils/data/_utils/fetch.py
  oneflow/python/utils/data/dataloader.py
  oneflow/python/utils/data/dataset.py
  oneflow/python/utils/data/decorator.py
  oneflow/python/utils/data/sampler.py
Labels: automerge, eager, enhancement, feature, interface

#5412 Dev ofrecord auto truncating
  oneflow/python/nn/modules/dataset.py
  oneflow/python/ops/data_ops.py
  oneflow/python/ops/user_data_ops.py
  oneflow/user/kernels/ofrecord_decoder_kernels.cpp
  oneflow/user/ops/ofrecord_decoder_ops.cpp
Labels: api, automerge, enhancement, interface, op

#5474 Fix tensor getitem bug
  oneflow/core/functional/tensor_index.cpp
  oneflow/python/framework/tensor.py
Labels: api, automerge, bug, eager

#5476 new static check based on clang-tidy
  .clang-tidy
  .github/workflows/test.yml
  tools/clang-plugin/.clang-format
  tools/clang-plugin/.gitignore
  tools/clang-plugin/CMakeLists.txt
  tools/clang-plugin/CheckUnusedMaybe/CMakeLists.txt
  tools/clang-plugin/CheckUnusedMaybe/CheckUnusedMaybe.cpp
  tools/clang-plugin/CheckUnusedMaybe/unused_maybe_example.cpp
Labels: automerge, ci, enhancement, feature

#5487 Add unique.cuh
  oneflow/core/cuda/unique.cuh
  oneflow/user/kernels/unique_kernel_util.cu
Labels: automerge, enhancement, op

#5489 add torchstyle unittest
  oneflow/python/test/modules/test_acosh.py
  oneflow/python/test/modules/test_activation.py
  oneflow/python/test/modules/test_atan2.py
  oneflow/python/test/modules/test_math_ops.py
Labels: automerge, enhancement, feature, python, test

#5497 Add timeout for wait_gpu_slot
  .github/workflows/test.yml
Labels: automerge, ci, enhancement

#5498 Fea/nn graph/block scope
  .github/workflows/test.yml
  oneflow/core/framework/instructions_builder.cpp
  oneflow/python/framework/graph_build_util.py
  oneflow/python/framework/scope_util.py
  oneflow/python/nn/graph.py
  oneflow/python/test/graph/test_graph.py
Labels: automerge, feature, interface, system

#5337 add dynamic_loss_scale in ci tests
  oneflow/python/benchmarks/cnn_benchmark/of_cnn_benchmarks.py
Labels: automerge, ci, enhancement

#5453 Input arg modifier return maybe
  oneflow/core/framework/user_op_registry.h
  oneflow/core/operator/user_op.cpp
  oneflow/user/kernels/stateful_local_opkernel.cpp
  oneflow/user/ops/assign_op.cpp
  oneflow/user/ops/batch_gather_op.cpp
  oneflow/user/ops/broadcast_like_op.cpp
  oneflow/user/ops/cast_like_op.cpp
  oneflow/user/ops/categorical_ordinal_encode_op.cpp
  oneflow/user/ops/combined_margin_loss_op.cpp
  oneflow/user/ops/dim_gather_op.cpp
  oneflow/user/ops/dropout_op.cpp
  oneflow/user/ops/dynamic_loss_scale_schedule_op.cpp
  oneflow/user/ops/fake_quantization_op.cpp
  oneflow/user/ops/fused_bias_add_op.cpp
  oneflow/user/ops/fused_scale_tril_softmax_mask_scale_op.cpp
  oneflow/user/ops/gather_op.cpp
  oneflow/user/ops/gpt_data_loader_op.cpp
  oneflow/user/ops/image_preprocess_ops.cpp
  oneflow/user/ops/min_max_observer_op.cpp
  oneflow/user/ops/model_update_ops.cpp
  oneflow/user/ops/moving_average_min_max_observer_op.cpp
  oneflow/user/ops/nd_index_slice_ops.cpp
  oneflow/user/ops/normalization_op.cpp
  oneflow/user/ops/ofrecord_decoder_ops.cpp
  oneflow/user/ops/one_hot_op.cpp
  oneflow/user/ops/onerec_decoder_op.cpp
  oneflow/user/ops/pad2d_ops.cpp
  oneflow/user/ops/partial_fc_sample_op.cpp
  oneflow/user/ops/reduce_like_ops.cpp
  oneflow/user/ops/reshape_like_op.cpp
  oneflow/user/ops/sigmoid_cross_entropy_op.cpp
  oneflow/user/ops/slice_op.cpp
  oneflow/user/ops/smooth_l1_loss_op.cpp
  oneflow/user/ops/softmax_cross_entropy_op.cpp
  oneflow/user/ops/sparse_cross_entropy_op.cpp
  oneflow/user/ops/sparse_softmax_cross_entropy_op.cpp
  oneflow/user/ops/split_like_op.cpp
  oneflow/user/ops/two_stage_reduce_ops.cpp
  oneflow/user/ops/unsorted_batch_segment_sum_op.cpp
  oneflow/user/ops/unsorted_segment_sum_op.cpp
  oneflow/user/ops/where_op.cpp
Labels: automerge, enhancement, system

#5490 LazyInterpret for FeedVariableOpExpr
  oneflow/core/framework/op_interpreter/lazy_op_interpreter.cpp
  oneflow/python/test/graph/test_variable_op_expr.py
Labels: automerge, feature, interface, system

#5499 register uint8 dtypeto support dataloader
  oneflow/user/kernels/empty_kernel.cpp
Labels: automerge, enhancement, op

#5517 piprepo->pipindex
  ci/test/try_install.sh
  docker/ci/test-v2/requirements.txt
  docker/ci/test/requirements.txt
Labels: automerge, ci, enhancement

#5382 Add more upsample kernel
  docs/source/experimental.rst
  oneflow/core/autograd/gradient_funcs/upsample.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/python/nn/modules/interpolate.py
  oneflow/python/test/modules/test_interpolate.py
  oneflow/user/kernels/upsample_bicubic2d_kernel.cpp
  oneflow/user/kernels/upsample_bicubic2d_kernel.cu
  oneflow/user/kernels/upsample_bilinear_2d_kernel.cpp
  oneflow/user/kernels/upsample_bilinear_2d_kernel.cu
  oneflow/user/kernels/upsample_kernel.h
  oneflow/user/kernels/upsample_linear_1d_kernel.cpp
  oneflow/user/kernels/upsample_linear_1d_kernel.cu
  oneflow/user/kernels/upsample_nearest_kernel.cpp
  oneflow/user/kernels/upsample_nearest_kernel.cu
  oneflow/user/kernels/upsample_trilinear_3d_kernel.cpp
  oneflow/user/kernels/upsample_trilinear_3d_kernel.cu
  oneflow/user/ops/upsample_op.cpp
Labels: automerge, eager, feature, interface, op, python

#5484 Refine module test using auto test by yaochi
  oneflow/python/nn/modules/masked_fill.py
  oneflow/python/nn/modules/math_ops.py
  oneflow/python/test/modules/test_div.py
  oneflow/python/test/modules/test_masked_fill.py
  oneflow/python/test/modules/test_mean.py
  oneflow/python/test/modules/test_mul.py
  oneflow/python/test/modules/test_reduce_ops.py
  oneflow/python/test/modules/test_sub.py
  oneflow/python/test/modules/test_sum.py
Labels: automerge, enhancement, test

#5502 Remove Plan::net_topo
  oneflow/core/job/compiler.cpp
  oneflow/core/job/compiler.h
  oneflow/core/job/oneflow.cpp
  oneflow/core/job/plan.proto
Labels: automerge, enhancement, system

#5503 Job pass maybe system
  oneflow/core/graph/task_graph.cpp
  oneflow/core/job/compiler.cpp
  oneflow/core/job_rewriter/autotick.cpp
  oneflow/core/job_rewriter/autotick.h
  oneflow/core/job_rewriter/group_boxing_by_dst_parallel.cpp
  oneflow/core/job_rewriter/group_boxing_by_dst_parallel.h
  oneflow/core/job_rewriter/job_completer.cpp
  oneflow/core/job_rewriter/job_completer.h
  oneflow/core/job_rewriter/xrt_compilation.h
Labels: automerge, enhancement, system

#5505 Add definition for CMAKE_BUILD_TYPE and print cmake_build_type in oneflow doctor
  CMakeLists.txt
  oneflow/__main__.py
  oneflow/api/python/flags.cpp
  oneflow/python/framework/sysconfig.py
Labels: automerge, build, enhancement

#5514 Prevent adding subdir in python/test
  .github/workflows/test.yml
  oneflow/python/test/demos/eager_nccl_all_reduce_demo.py
  oneflow/python/test/deprecated/constant_scalar.py
  oneflow/python/test/deprecated/enable_all_reduce_group.py
  oneflow/python/test/deprecated/variable_scope.py
  oneflow/python/test/ops/test_generator.py
  tools/check_src.py
Labels: automerge, ci, enhancement

#5523 GlobalMultiClientEnv and refine EagerExecution
  oneflow/core/eager/eager_oneflow.cpp
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/framework/multi_client_session_context.cpp
  oneflow/core/job/env_desc.cpp
  oneflow/core/job/env_desc.h
  oneflow/core/job/job_build_and_infer_ctx_mgr.cpp
  oneflow/core/vm/id_generator.cpp
  oneflow/python/test/graph/test_graph.py
  oneflow/python/test/graph/test_input_op_expr.py
  oneflow/python/test/graph/test_variable_op_expr.py
Labels: automerge, feature, interface, system

#5519 Remove automerge if cuda_new_interface failed
  .github/workflows/test.yml
Labels: automerge, ci, enhancement

#5478 split vector-matrix norm
  docs/source/experimental.rst
  oneflow/python/nn/modules/norm.py
Labels: automerge, enhancement, feature, python

#5501 Dev optimize tensor setitem
  oneflow/api/python/framework/throw.h
  oneflow/core/common/error.cpp
  oneflow/core/common/error.h
  oneflow/core/common/error.proto
  oneflow/core/common/exception.h
  oneflow/core/common/shape.cpp
  oneflow/core/common/shape.h
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/core/functional/tensor_index.cpp
  oneflow/core/functional/tensor_index.h
  oneflow/python/framework/tensor.py
  oneflow/python/nn/modules/expand.py
Labels: api, automerge, enhancement, op, refactor

#5509 Add scale size for resize
  oneflow/python/nn/modules/dataset.py
  oneflow/python/test/modules/image_test_util.py
  oneflow/python/test/modules/test_dataset.py
  oneflow/python/test/modules/test_image_resize.py
  oneflow/python/test/modules/test_resnet50_with_bn.py
  oneflow/python/test/modules/test_resnet50_without_bn.py
Labels: automerge, eager, enhancement, op

#5493 Fix maxpool1d params
  oneflow/python/nn/modules/pooling.py
  oneflow/python/nn/modules/utils.py
  oneflow/python/test/modules/test_pooling.py
Labels: automerge, bottleneck, bug, eager, enhancement, interface

#5486 Feat module repr
  oneflow/python/nn/module.py
  oneflow/python/nn/modules/activation.py
  oneflow/python/nn/modules/batchnorm.py
  oneflow/python/nn/modules/container.py
  oneflow/python/nn/modules/conv.py
  oneflow/python/nn/modules/flatten.py
  oneflow/python/nn/modules/linear.py
  oneflow/python/nn/modules/normalization.py
  oneflow/python/nn/modules/padding.py
  oneflow/python/nn/modules/pixelshuffle.py
  oneflow/python/nn/modules/pooling.py
  oneflow/python/nn/modules/upsampling.py
Labels: automerge, eager, feature

#5531 Fix Session TryClose
  oneflow/compatible_single_client_python/framework/session_util.py
  oneflow/python/framework/session_util.py
Labels: api, automerge, bug, python

#5455 bw_gen_fn return maybe
  oneflow/compatible_single_client_python/test/custom_ops/user_sigmoid/user_sigmoid_cpp_def.cpp
  oneflow/core/framework/user_op_grad_registry.h
  oneflow/core/job_rewriter/user_grad.cpp
  oneflow/user/ops/acc_op.cpp
  oneflow/user/ops/adaptive_pool_op.cpp
  oneflow/user/ops/broadcast_like_op.cpp
  oneflow/user/ops/ctc_loss_op.cpp
  oneflow/user/ops/diag_op.cpp
  oneflow/user/ops/dim_gather_op.cpp
  oneflow/user/ops/elementwise_maximum_minimum_ops.cpp
  oneflow/user/ops/elu_op.cpp
  oneflow/user/ops/fused_self_attention_query_mul_key_and_value_ops.cpp
  oneflow/user/ops/hardsigmoid_op.cpp
  oneflow/user/ops/hardswish_op.cpp
  oneflow/user/ops/hardtanh_op.cpp
  oneflow/user/ops/hierarchical_parallel_cast_op.cpp
  oneflow/user/ops/matmul_op.cpp
  oneflow/user/ops/normalization_op.cpp
  oneflow/user/ops/pack_op.cpp
  oneflow/user/ops/parallel_cast_op.cpp
  oneflow/user/ops/partial_fc_sample_op.cpp
  oneflow/user/ops/relu_op.cpp
  oneflow/user/ops/repeat_op.cpp
  oneflow/user/ops/scalar_pow_op.cpp
  oneflow/user/ops/slice_op.cpp
  oneflow/user/ops/unpack_op.cpp
  oneflow/user/ops/where_op.cpp
Labels: automerge, enhancement, system

#5528 Support sccache
  cmake/caches/cn/fast/cpu.cmake
  cmake/third_party/absl.cmake
  cmake/third_party/eigen.cmake
  cmake/third_party/gflags.cmake
  cmake/third_party/glog.cmake
  cmake/third_party/googletest.cmake
  cmake/third_party/grpc.cmake
  cmake/third_party/libjpeg-turbo.cmake
  cmake/third_party/opencv.cmake
  cmake/third_party/protobuf.cmake
  cmake/third_party/re2.cmake
  cmake/third_party/zlib.cmake
Labels: automerge, build, enhancement

#5456 registry_callback_fn return maybe
  oneflow/user/kernels/same_padding_kernel.cpp
  oneflow/user/ops/cast_to_tick_op.cpp
  oneflow/user/ops/conv_op.cpp
  oneflow/user/ops/deconv_op.cpp
  oneflow/user/ops/elu_op.cpp
  oneflow/user/ops/fused_scale_tril_softmax_mask_scale_op.cpp
  oneflow/user/ops/gelu_op.cpp
  oneflow/user/ops/hardsigmoid_op.cpp
  oneflow/user/ops/hardswish_op.cpp
  oneflow/user/ops/hardtanh_op.cpp
  oneflow/user/ops/layer_norm_op.cpp
  oneflow/user/ops/leaky_relu_op.cpp
  oneflow/user/ops/nn_util.cpp
  oneflow/user/ops/nn_util.h
  oneflow/user/ops/normalization_op.cpp
  oneflow/user/ops/pack_op.cpp
  oneflow/user/ops/pad_op.cpp
  oneflow/user/ops/parallel_cast_op.cpp
  oneflow/user/ops/relu_op.cpp
  oneflow/user/ops/reshape_user_op_util.cpp
  oneflow/user/ops/same_padding_op.cpp
  oneflow/user/ops/sigmoid_op.cpp
  oneflow/user/ops/softmax_op.cpp
  oneflow/user/ops/squeeze_op.cpp
  oneflow/user/ops/test_ops.cpp
  oneflow/user/ops/transpose_ops.cpp
  oneflow/user/ops/unpack_op.cpp
Labels: enhancement, system

#5535 Fix single client using same glog file
  oneflow/single_client_init.py
Labels: automerge, enhancement, python

#5492 Multi client push pull
  oneflow/core/eager/eager_blob_object.cpp
  oneflow/core/eager/eager_blob_object.h
  oneflow/core/kernel/input_kernel.cpp
  oneflow/core/kernel/output_kernel.cpp
  oneflow/core/kernel/return_kernel.cpp
  oneflow/core/kernel/wait_and_send_ids_kernel.cpp
Labels: automerge, enhancement, system

#5527 LazyInterpreter for FetchOutputOpExpr and set op parallel_distribution
  oneflow/core/framework/op_interpreter/lazy_op_interpreter.cpp
  oneflow/python/test/graph/test_output_op_expr.py
Labels: automerge, feature, interface, system

#5534 prevent endless loop
  .github/workflows/simple.yml
  tools/conver_single_client_name_space.py
Labels: automerge, bug, build

#5537 del default env init
  oneflow/api/python/env/env.cpp
  oneflow/api/python/env/env.h
  oneflow/api/python/env/env_api.h
  oneflow/api/python/session/session.cpp
  oneflow/api/python/session/session.h
  oneflow/api/python/session/session_api.h
  oneflow/compatible_single_client_python/framework/c_api_util.py
  oneflow/compatible_single_client_python/framework/env_util.py
  oneflow/compatible_single_client_python/framework/session_context.py
  oneflow/core/job/env.proto
  oneflow/core/job/env_global_objects_scope.cpp
  oneflow/core/job/env_global_objects_scope.h
  oneflow/init.py
  oneflow/python/framework/c_api_util.py
  oneflow/python/framework/env_util.py
  oneflow/python/framework/multi_client_session.py
  oneflow/single_client_init.py
Labels: api, automerge, enhancement, python

#5529 implementation of constantpad-3d op
  docs/source/experimental.rst
  oneflow/core/autograd/gradient_funcs/padding.cpp
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/core/functional/impl/nn_grad_functor.cpp
  oneflow/python/nn/modules/constantpad2d.py
  oneflow/python/nn/modules/padding.py
  oneflow/python/test/modules/test_constantpad.py
  oneflow/user/kernels/constantpad3d_kernel.cpp
  oneflow/user/kernels/constantpad3d_kernel_util.cpp
  oneflow/user/kernels/constantpad3d_kernel_util.cu
  oneflow/user/kernels/constantpad3d_kernel_util.h
  oneflow/user/ops/padding_ops.cpp
Labels: api, automerge, bottleneck, eager, enhancement, op

#5541 Add flip module
  docs/source/experimental.rst
  oneflow/core/autograd/gradient_funcs/flip.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/python/nn/modules/flip.py
  oneflow/python/test/modules/test_flip.py
  oneflow/user/kernels/flip_kernel.cpp
  oneflow/user/kernels/flip_kernel.cu
  oneflow/user/ops/flip_op.cpp
Labels: api, automerge, documentation, eager, enhancement, feature

#5543 Feat tensor stride property
  oneflow/api/python/framework/tensor.cpp
  oneflow/core/common/shape_vec.h
  oneflow/core/framework/stride.cpp
  oneflow/core/framework/stride.h
  oneflow/core/framework/tensor.h
  oneflow/core/framework/tensor_impl.cpp
  oneflow/core/framework/tensor_impl.h
  oneflow/core/framework/tensor_meta.h
  oneflow/core/framework/tensor_method.cpp
  oneflow/core/framework/tensor_method.h
  oneflow/python/framework/tensor.py
  oneflow/python/test/tensor/test_tensor.py
Labels: automerge, eager, feature, interface

#5542 Add ProfilerStart/ProfilerStop API
  oneflow/api/python/profiler.cpp
  oneflow/core/profiler/profiler.cpp
  oneflow/core/profiler/profiler.h
  oneflow/python/framework/profiler.py
Labels: automerge, enhancement, system

#5544 LazyInterpret for UserOpExpr
  oneflow/core/framework/op_interpreter/lazy_op_interpreter.cpp
  oneflow/core/job/job_build_and_infer_ctx.cpp
  oneflow/python/test/graph/test_user_op_expr.py
Labels: automerge, feature, interface, system

#5546 Reduce usage of Simple CI
  .github/workflows/simple.yml
Labels: automerge, ci, enhancement

#5548 fix return type
  oneflow/core/kernel/sink_tick_kernel.h
Labels: automerge, bug, system

#5525 Align pytorch maxpool
  oneflow/core/autograd/gradient_funcs/pooling.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/core/functional/impl/nn_grad_functor.cpp
  oneflow/python/nn/modules/pooling.py
  oneflow/user/kernels/pooling_kernel.cpp
  oneflow/user/kernels/pooling_kernel.cu
  oneflow/user/kernels/pooling_kernel_util.cpp
  oneflow/user/kernels/pooling_kernel_util.h
  oneflow/user/ops/pooling_op.cpp
Labels: automerge, enhancement, op

#5506 Refactor single client autotick
  oneflow/core/job_rewriter/autotick.cpp
  oneflow/core/job_rewriter/autotick.h
  oneflow/core/job_rewriter/job_completer.cpp
Labels: automerge, enhancement, system

#5551 Remove inplace broadcast_add
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/binary_functor.cpp
  oneflow/python/nn/modules/broadcast_like.py
  oneflow/python/nn/modules/math_ops.py
Labels: automerge, bug, eager

#5496 add speed test in ci
  .github/workflows/test.yml
  ci/test_multi_client/test_speed.sh
Labels: automerge, ci, feature

#5516 Fea/nn graph/forward graph
  oneflow/python/framework/graph_build_util.py
  oneflow/python/nn/graph.py
  oneflow/python/nn/graph_block.py
  oneflow/python/nn/graph_optimizer.py
  oneflow/python/nn/utils.py
  oneflow/python/test/graph/test_forward_graph.py
  oneflow/python/test/graph/test_graph.py
  oneflow/python/test/graph/test_input_op_expr.py
  oneflow/python/test/graph/test_multi_client_session.py
  oneflow/python/test/graph/test_output_op_expr.py
  oneflow/python/test/graph/test_user_op_expr.py
  oneflow/python/test/graph/test_variable_op_expr.py
Labels: automerge, feature, system

#5445 Add `nn.AdaptiveAvgPool1d` and `nn.AdaptiveAvgPool3d`
  docs/source/experimental.rst
  oneflow/core/autograd/gradient_funcs/adaptive_pool.cpp
  oneflow/core/framework/op_expr_helper.cpp
  oneflow/core/framework/op_expr_helper.h
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/core/functional/impl/nn_grad_functor.cpp
  oneflow/python/nn/modules/adaptive_pool.py
  oneflow/python/nn/modules/interpolate.py
  oneflow/python/test/modules/test_adaptive_pool.py
  oneflow/python/test/modules/test_interpolate.py
  oneflow/user/kernels/adaptive_pool_cpu_kernel.cpp
  oneflow/user/kernels/adaptive_pool_gpu_kernel.cu
  oneflow/user/ops/adaptive_pool_op.cpp
Labels: automerge, ci, enhancement, interface

#5560 Prevent upload logs automatically
  .github/workflows/simple.yml
Labels: automerge, ci, enhancement, need-simple-ci

#5567 Fix wrong test path under compatible
  oneflow/python/test/modules/test_generator.py
Labels: automerge, bug, ci

#5569 relax speed threshold
  ci/test_multi_client/test_speed.sh
Labels: automerge, ci, enhancement

#5558 NNGraph interface and implement for CompileAndRuntime
  oneflow/api/python/framework/nn_graph.cpp
  oneflow/core/framework/nn_graph.cpp
  oneflow/core/framework/nn_graph.h
  oneflow/core/framework/nn_graph_if.h
  oneflow/core/job/job_build_and_infer_ctx.h
  oneflow/core/job/oneflow.cpp
  oneflow/core/job/plan_util.cpp
  oneflow/core/job/plan_util.h
Labels: automerge, feature, interface, refactor, system
