Repository Oneflow-Inc/oneflow, pull requests merged in 2022-12, with the labels that each got.

#9485 add fused_get_intersection_area
  oneflow/core/autograd/gradient_funcs/fused_get_intersection_area.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/fused_get_intersection_area_kernel.cu
  oneflow/user/ops/fused_get_intersection_area_op.cpp
  python/oneflow/test/modules/test_fused_get_intersection_area.py
Labels: feature, automerge, op

#9487 FusedWeightedSum
  oneflow/core/autograd/gradient_funcs/fused_weighted_sum.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/core/job_rewriter/auto_mixed_precision_lists.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/fused_weighted_sum_kernel.cpp
  oneflow/user/kernels/fused_weighted_sum_kernel.cu
  oneflow/user/ops/fused_weighted_sum_op.cpp
  python/oneflow/test/modules/test_fused_weighted_sum.py
Labels: feature, automerge, op

#9498 yolov5 ema support multi_tensor
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/multi_tensor_model_update_kernel.cpp
  oneflow/user/kernels/multi_tensor_model_update_kernel_util.cu
  oneflow/user/kernels/multi_tensor_model_update_kernel_util.h
  oneflow/user/ops/multi_tensor_model_update_ops.cpp
  python/oneflow/test/modules/test_multi_tensor_yolov5_weight_update.py
Labels: enhancement, feature, automerge, eager, api

#9367 Add fused glu op
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/core/job_rewriter/auto_mixed_precision_lists.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/fused_glu_kernel.cu
  oneflow/user/ops/fused_glu_op.cpp
  python/oneflow/test/modules/test_fused_glu.py
Labels: feature, automerge, op

#9509 Add a switch for memory share strategy
  docs/source/graph.rst
  oneflow/core/job/intra_job_mem_sharing_util.cpp
  oneflow/core/job/job_conf.proto
  python/oneflow/nn/graph/graph_config.py
Labels: feature, automerge, graph

#9511 Fix scalar tensor dtype cast
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/core/functional/tensor_processor.cpp
Labels: automerge, bug, python

#9482 add flow.placement.all
  docs/source/tensor_attributes.rst
  oneflow/api/python/symbol/placement_symbol.cpp
  python/oneflow/comm/comm_ops.py
  python/oneflow/framework/docstr/tensor_attributes.py
  python/oneflow/framework/env_util.py
  python/oneflow/framework/tensor.py
  python/oneflow/framework/tensor_str_util.py
  python/oneflow/nn/modules/dataset.py
  python/oneflow/test/exceptions/test_global_branch_error_local_to_global_with_split_sbp.py
  python/oneflow/test/exceptions/test_global_branch_error_with_global_mean.py
  python/oneflow/test/exceptions/test_local_global_convert_error.py
  python/oneflow/test/exceptions/test_to_global_error.py
  python/oneflow/test/expensive/test_oneembedding.py
  python/oneflow/test/expensive/test_oneembedding_padding_idx.py
  python/oneflow/test/graph/test_alexnet_auto_parallel.py
  python/oneflow/test/graph/test_free_tensor_not_in_job.py
  python/oneflow/test/graph/test_graph_lr_scale.py
  python/oneflow/test/misc/test_placement.py
  python/oneflow/test/modules/test_clip_grad.py
  python/oneflow/test/modules/test_eager_boxing.py
  python/oneflow/test/modules/test_global_cast.py
  python/oneflow/test/modules/test_global_ctc_loss.py
  python/oneflow/test/modules/test_global_max.py
  python/oneflow/test/modules/test_global_min.py
  python/oneflow/test/modules/test_global_nms.py
  python/oneflow/test/modules/test_global_partical_fc.py
  python/oneflow/test/modules/test_global_reshape.py
  python/oneflow/test/modules/test_global_rnn.py
  python/oneflow/test/modules/test_global_roi_align.py
  python/oneflow/test/modules/test_global_scatter_nd.py
  python/oneflow/test/modules/test_global_scatter_ops.py
  python/oneflow/test/modules/test_global_sparse_softmax_cross_entropy.py
  python/oneflow/test/modules/test_global_stateful_kernel_with_cache.py
  python/oneflow/test/modules/test_global_transpose.py
  python/oneflow/test/modules/test_loss_global.py
  python/oneflow/test/modules/test_parital_fc.py
  python/oneflow/test/modules/test_stateful_kernel_with_cache.py
  python/oneflow/test/tensor/test_global_tensor_indexing.py
  python/oneflow/test/tensor/test_lazy_tensor_indexing.py
  python/oneflow/test/tensor/test_tensor_part_2.py
  python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py
  python/oneflow/utils/global_view/global_utils.py
Labels: enhancement, automerge, python

#9517 Group fused_matmul_bias
  oneflow/ir/include/OneFlow/OneFlowInterfaces.td
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/ir/lib/OneFlow/Transform/GroupMatMulOps.cpp
  oneflow/ir/lib/OneFlow/Transform/OutlineAndFuse.cpp
  oneflow/ir/oneflow-translate/lib/OneFlow/MLIROneFlowTranslation.cpp
  oneflow/ir/test/OneFlow/group_matmul.mlir
  oneflow/ir/test/OneFlow/kernel_launch/test_conv2d.py
  oneflow/ir/test/OneFlow/kernel_launch/test_fuse.py
  oneflow/ir/test/OneFlow/with_cuda/test_fused_matmul_bias.py
  oneflow/ir/test/OneFlow/with_cuda/test_graph_save_and_load.py
Labels: enhancement, automerge, ir

#9516 Fix yolov5 ema multi tensor bug
  oneflow/user/kernels/multi_tensor_model_update_kernel_util.cu
  oneflow/user/ops/multi_tensor_model_update_ops.cpp
  python/oneflow/test/modules/test_multi_tensor_yolov5_weight_update.py
Labels: enhancement, automerge, bug, eager, api

#9513 Add baddbmm api
  docs/source/oneflow.rst
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/array_functor.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/__init__.py
  python/oneflow/framework/docstr/baddbmm.py
  python/oneflow/test/modules/test_baddbmm.py
Labels: enhancement, feature, automerge, bug, eager, api

#9396 Fix module list block slice
  python/oneflow/nn/graph/proxy.py
  python/oneflow/nn/utils/container.py
  python/oneflow/test/graph/test_graph_block.py
Labels: automerge, bug, system, graph

#9520 Add glu dual gemm impl
  cmake/oneflow.cmake
  external/cutlass/CMakeLists.txt
  oneflow/user/kernels/fused_glu_kernel.cu
Labels: enhancement, automerge, op

#9518 Improve LayerNormBlockSMemImpl perfermance
  oneflow/core/cuda/layer_norm.cuh
  oneflow/user/kernels/group_norm_kernel.cu
  oneflow/user/kernels/layer_norm_gpu_kernel.cu
  python/oneflow/test/modules/test_layer_norm.py
Labels: enhancement, automerge, op

#9524 Add trt flasl attn impl
  .github/workflows/test.yml
  ci/check/run_clang_format.py
  cmake/oneflow.cmake
  oneflow/user/kernels/fmha_flash_attention/cudaDriverWrapper.cpp
  oneflow/user/kernels/fmha_flash_attention/cudaDriverWrapper.h
  oneflow/user/kernels/fmha_flash_attention/fmha.cpp
  oneflow/user/kernels/fmha_flash_attention/fmha.h
  oneflow/user/kernels/fmha_flash_attention/include/commonDatatype.h
  oneflow/user/kernels/fmha_flash_attention/include/fmha_flash_attention.h
  oneflow/user/kernels/fmha_flash_attention/include/sharedCubinLoader.h
  oneflow/user/kernels/fmha_flash_attention/src/fmha_v2_flash_attention_fp16_S_128_sm80.cubin.cpp
  oneflow/user/kernels/fmha_flash_attention/src/fmha_v2_flash_attention_fp16_S_128_sm86.cubin.cpp
  oneflow/user/kernels/fmha_flash_attention/src/fmha_v2_flash_attention_fp16_S_128_sm89.cubin.cpp
  oneflow/user/kernels/fmha_flash_attention/src/fmha_v2_flash_attention_fp16_S_160_sm80.cubin.cpp
  oneflow/user/kernels/fmha_flash_attention/src/fmha_v2_flash_attention_fp16_S_160_sm86.cubin.cpp
  oneflow/user/kernels/fmha_flash_attention/src/fmha_v2_flash_attention_fp16_S_160_sm89.cubin.cpp
  oneflow/user/kernels/fmha_flash_attention/src/fmha_v2_flash_attention_fp16_S_16_sm80.cubin.cpp
  oneflow/user/kernels/fmha_flash_attention/src/fmha_v2_flash_attention_fp16_S_16_sm86.cubin.cpp
  oneflow/user/kernels/fmha_flash_attention/src/fmha_v2_flash_attention_fp16_S_16_sm89.cubin.cpp
  oneflow/user/kernels/fmha_flash_attention/src/fmha_v2_flash_attention_fp16_S_256_sm80.cubin.cpp
  oneflow/user/kernels/fmha_flash_attention/src/fmha_v2_flash_attention_fp16_S_256_sm86.cubin.cpp
  oneflow/user/kernels/fmha_flash_attention/src/fmha_v2_flash_attention_fp16_S_256_sm89.cubin.cpp
  oneflow/user/kernels/fmha_flash_attention/src/fmha_v2_flash_attention_fp16_S_32_sm80.cubin.cpp
  oneflow/user/kernels/fmha_flash_attention/src/fmha_v2_flash_attention_fp16_S_32_sm86.cubin.cpp
  oneflow/user/kernels/fmha_flash_attention/src/fmha_v2_flash_attention_fp16_S_32_sm89.cubin.cpp
  oneflow/user/kernels/fmha_flash_attention/src/fmha_v2_flash_attention_fp16_S_40_sm80.cubin.cpp
  oneflow/user/kernels/fmha_flash_attention/src/fmha_v2_flash_attention_fp16_S_40_sm86.cubin.cpp
  oneflow/user/kernels/fmha_flash_attention/src/fmha_v2_flash_attention_fp16_S_40_sm89.cubin.cpp
  oneflow/user/kernels/fmha_flash_attention/src/fmha_v2_flash_attention_fp16_S_64_sm80.cubin.cpp
  oneflow/user/kernels/fmha_flash_attention/src/fmha_v2_flash_attention_fp16_S_64_sm86.cubin.cpp
  oneflow/user/kernels/fmha_flash_attention/src/fmha_v2_flash_attention_fp16_S_64_sm89.cubin.cpp
  oneflow/user/kernels/fmha_flash_attention/src/fmha_v2_flash_attention_fp16_S_80_sm80.cubin.cpp
  oneflow/user/kernels/fmha_flash_attention/src/fmha_v2_flash_attention_fp16_S_80_sm86.cubin.cpp
  oneflow/user/kernels/fmha_flash_attention/src/fmha_v2_flash_attention_fp16_S_80_sm89.cubin.cpp
  oneflow/user/kernels/fused_multi_head_attention_inference_kernel.cu
Labels: enhancement, op

#9527 hotfix for empty device bug
  oneflow/core/functional/impl/array_functor.cpp
Labels: enhancement, automerge, bug, eager, api, graph

#9528 optim baddbmm in stable diffusion
  oneflow/core/functional/impl/array_functor.cpp
  python/oneflow/test/modules/test_baddbmm.py
Labels: enhancement, automerge, eager, api

#9492 Refactor dataloader rdma
  python/oneflow/utils/data/dataloader.py
Labels: enhancement, automerge, bug, eager

#9474 Add FusedPadConv2d PDLL Pattern
  cmake/caches/cn/fast/mlir-cuda-86.cmake
  oneflow/ir/include/OneFlow/OneFlowPatternUtils.h
  oneflow/ir/include/OneFlow/OneFlowPatterns.td
  oneflow/ir/lib/OneFlow/OneFlowRewrites.cpp
  oneflow/ir/lib/OneFlow/PDLL/ForwardOpPatterns.pdll
  oneflow/ir/lib/OneFlow/Passes.cpp
  oneflow/ir/test/OneFlow/fuse_forward_ops.mlir
  oneflow/ir/test/OneFlow/test_fuse_pad_conv.py
Labels: enhancement, automerge, ir

#9531 Enable cuda graph support for kernels
  oneflow/user/kernels/binary_concat_kernel.cu
  oneflow/user/kernels/expand_kernel.cpp
  oneflow/user/kernels/slice_kernel.cpp
  oneflow/user/kernels/upsample_nearest_kernel.cu
Labels: enhancement, automerge, op

#9532 Add OF_DEVICE_FUNC attr to Scalar's constructors
  oneflow/core/common/scalar.h
Labels: enhancement, automerge, system

#9507 support from_dlpack
  oneflow/api/python/dlpack/converter.cpp
  oneflow/api/python/dlpack/converter.h
  oneflow/api/python/dlpack/dlpack.h
  oneflow/api/python/functional/tensor_api.cpp
  oneflow/api/python/functional/tensor_api.yaml
  python/oneflow/__init__.py
  python/oneflow/test/modules/test_from_dlpack.py
  python/oneflow/test/modules/test_from_torch.py
  python/oneflow/utils/tensor/from_or_to_torch_tensor.py
Labels: feature, automerge, system

#9554 DenseElementsAttrToTensor reuse managed tensor
  oneflow/ir/include/OneFlow/OneFlowSupport.h
  oneflow/ir/lib/OneFlow/OneFlowSupport.cpp
  oneflow/ir/lib/OneFlow/Passes.cpp
Labels: enhancement, automerge, graph

#9543 add quantile and logaddexp and fix flow.equal
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/ir/test/OneFlow/kernel_launch/test_okl_ops.py
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/logaddexp.py
  python/oneflow/framework/docstr/quantile.py
  python/oneflow/framework/tensor.py
  python/oneflow/nn/modules/equal.py
  python/oneflow/test/modules/test_logaddexp.py
  python/oneflow/test/modules/test_quantile.py
  python/oneflow/test/modules/test_sparse.py
Labels: enhancement, automerge, op, test, api

#9552 rm log dir default
  docs/source/environment_variables.rst
  oneflow/api/cpp/env_impl.cpp
  oneflow/core/job/env.proto
  oneflow/core/job/env_global_objects_scope.cpp
  oneflow/ir/oneflow-extension/ir_pass.cpp
  python/oneflow/distributed/launch.py
  python/oneflow/framework/env_util.py
Labels: enhancement, help wanted, automerge, system

#9564 Revert conv cudnn kernel
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/user/kernels/conv_cudnn_kernels.cpp
  oneflow/user/kernels/fused_multi_head_attention_inference_kernel.cu
Labels: enhancement, automerge, op

#9560 Fix group norm grad fp16
  oneflow/user/kernels/group_norm_kernel.cu
  python/oneflow/test/modules/test_groupnorm.py
Labels: automerge, bug, op

#9570 clear instruction list to fix item segfault
  oneflow/core/vm/virtual_machine.cpp
Labels: automerge, bug, eager, system, need-clean-ccache

#9571 fix where op data_type infer mismatch
  oneflow/user/kernels/where_kernel.cpp
  oneflow/user/ops/where_op.cpp
  python/oneflow/test/modules/test_where.py
Labels: enhancement, automerge, bug, api, python

#9569 conv cutlass impl
  CMakeLists.txt
  cmake/oneflow.cmake
  cmake/third_party.cmake
  cmake/third_party/cutlass.cmake
  external/CMakeLists.txt
  external/cutlass/CMakeLists.txt
  oneflow/user/kernels/conv_cutlass_kernels.cu
Labels: enhancement, automerge, op, need-all-tests-even-fail

#9574 glu dual gemm impl gelu
  oneflow/user/kernels/fused_glu_kernel.cu
Labels: enhancement, automerge, op, need-all-tests-even-fail

#9568 l2_normalize forward kernel support fp16
  oneflow/user/kernels/l2_normalize_kernel.cu
  oneflow/user/ops/l2_normalize_op.cpp
Labels: enhancement, automerge, op

#9565 Fix binary cross entropy inputs type
  oneflow/user/kernels/binary_cross_entropy_with_logits_kernel.cpp
  oneflow/user/kernels/binary_cross_entropy_with_logits_kernel.cu
  oneflow/user/kernels/binary_cross_entropy_with_logits_mean_kernel.cu
  oneflow/user/kernels/binary_cross_entropy_with_logits_reduce_mean.cpp
  oneflow/user/ops/binary_cross_entropy_with_logits_op.cpp
  oneflow/user/ops/binary_cross_entropy_with_logits_reduce_mean_op.cpp
  python/oneflow/test/modules/test_loss.py
Labels: automerge, bug, op

#9575 rm redundant output
  oneflow/core/job/env_global_objects_scope.cpp
  oneflow/core/platform/lib/wrapper.cpp
  python/oneflow/distributed/launch.py
Labels: enhancement, automerge, system

#9578 fix cutlass compile
  cmake/oneflow.cmake
  cmake/third_party.cmake
  cmake/third_party/cutlass.cmake
  oneflow/user/kernels/conv_cutlass_kernels.cu
  oneflow/user/kernels/fused_glu_kernel.cu
  oneflow/user/kernels/fused_multi_head_attention_inference_kernel.cu
  oneflow/user/kernels/group_norm_kernel.cu
Labels: automerge, bug, build, need-all-tests-even-fail

#9558 fix ddp load stuck
  python/oneflow/nn/module.py
  python/oneflow/nn/parallel/distributed.py
Labels: automerge, bug, python

#9579 support to_dlpack
  oneflow/api/python/dlpack/converter.cpp
  oneflow/api/python/dlpack/converter.h
  python/oneflow/__init__.py
  python/oneflow/test/modules/test_dlpack.py
  python/oneflow/test/modules/test_from_dlpack.py
  python/oneflow/test/modules/test_to_torch.py
  python/oneflow/utils/tensor/from_or_to_torch_tensor.py
Labels: feature, automerge, system

#9583 flow.full support numpy scalar
  python/oneflow/nn/modules/constant.py
  python/oneflow/test/modules/test_constant.py
Labels: automerge, bug, eager, api

#9577 optimize nccl archs
  cmake/third_party/nccl.cmake
Labels: enhancement, automerge, build

#9584 fix CUTLASS_LIBRARY_DEBUG_POSTFIX
  cmake/third_party/cutlass.cmake
Labels: automerge, bug, build

#9581 enable trt attn when d=64
  oneflow/user/kernels/fused_multi_head_attention_inference_kernel.cu
Labels: enhancement, automerge, op

#9589 Default set ENABLE_LOGICAL_CHAIN=false for hotfix bugs in OneEmbedding.
  oneflow/core/common/env_var/debug_mode.h
  python/oneflow/nn/graph/graph_config.py
Labels: bottleneck, bug, graph

#9596 Fix normal op inplace lazy mode
  oneflow/core/framework/op_interpreter/lazy_op_interpreter.cpp
  python/oneflow/test/graph/test_graph_normal_inplace.py
Labels: bug, op, graph

#9597 fix header guard
  oneflow/core/kernel/cuda_graph_support.h
Labels: automerge, bug, op

#9593 add unique functor
  docs/source/oneflow.rst
  docs/source/tensor.rst
  oneflow/api/python/framework/tensor_functions.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/unique_kernel.cpp
  oneflow/user/ops/unique_op.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/tensor.py
  python/oneflow/nn/modules/unique.py
  python/oneflow/test/modules/test_global_unique.py
  python/oneflow/test/modules/test_unique.py
Labels: enhancement, automerge, op, test, documentation, api, python

#9573 Fix var kernel bug and support half var
  oneflow/core/autograd/gradient_funcs/variance.cpp
  oneflow/core/common/data_type.cpp
  oneflow/core/common/data_type.h
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/user/kernels/variance_kernel.cpp
  oneflow/user/kernels/variance_kernel_util.cpp
  oneflow/user/kernels/variance_kernel_util.cu
  oneflow/user/kernels/variance_kernel_util.h
  python/oneflow/test/modules/test_var.py
Labels: enhancement, automerge, system, api

#9606 fix equal
  python/oneflow/nn/modules/equal.py
Labels: automerge, bug, eager, api

#9592 restore new .item() and change the modifier of .numpy() to 'const'
  oneflow/api/python/utils/tensor_utils.h
  python/oneflow/framework/tensor.py
Labels: enhancement, automerge, eager, need-clean-ccache

#9546 Refine eager local infer process
  oneflow/core/framework/op_expr.cpp
  oneflow/core/framework/op_expr.h
  oneflow/core/job/parallel_desc.cpp
  oneflow/core/job/parallel_desc.h
  oneflow/user/ops/p2p_comm_op.cpp
  oneflow/user/ops/reflection_pad_op.cpp
  oneflow/user/ops/replication_pad_op.cpp
Labels: enhancement, automerge, system

#9610 fix matmul bias heuristic search
  oneflow/user/kernels/fused_matmul_bias_kernel.cu
Labels: automerge, bug, op

#9497 AutoGrad: acc_grad use inplace add
  oneflow/api/python/framework/tensor.cpp
  oneflow/core/autograd/autograd_engine.cpp
  oneflow/core/autograd/autograd_engine.h
  oneflow/core/autograd/autograd_meta.cpp
  oneflow/core/autograd/autograd_meta.h
  python/oneflow/nn/parallel/distributed.py
  python/oneflow/test/modules/test_autograd.py
Labels: enhancement, automerge, eager

#9607 Refactor proxymodule param
  python/oneflow/nn/graph/graph.py
  python/oneflow/nn/graph/proxy.py
Labels: enhancement, automerge, python, graph

#9614 disable env cache
  oneflow/core/ep/cuda/primitive/broadcast_matmul.cpp
  oneflow/user/kernels/conv_cutlass_kernels.cu
  oneflow/user/kernels/cublas_fused_mlp_util.cuh
  oneflow/user/kernels/fused_glu_kernel.cu
  oneflow/user/kernels/fused_multi_head_attention_inference_kernel.cu
  oneflow/user/kernels/grouped_matmul_bias.cu
Labels: enhancement, op

#9613 CutlassConvTuningWarmupPass
  oneflow/core/job/job_build_and_infer_ctx.cpp
  oneflow/core/job_rewriter/cutlass_conv_tuning_warmup_pass.cpp
  oneflow/user/kernels/conv_cutlass_kernels.cu
  oneflow/user/kernels/cutlass_conv_tuner.cpp
Labels: enhancement, automerge, op, need-all-tests-even-fail

#9549 flow.load supports pytorch format
  python/oneflow/framework/check_point_v2.py
  python/oneflow/mock_torch/__init__.py
  python/oneflow/mock_torch/torch/__init__.py
  python/oneflow/nn/graph/util.py
  python/oneflow/test/exceptions/test_save_load.py
  python/oneflow/test/misc/test_mock_scope.py
  python/oneflow/test/modules/test_module.py
  python/oneflow/utils/global_view/to_global.py
Labels: feature, automerge, system, python

#9410 Refactor nn initializer
  python/oneflow/nn/init.py
  python/oneflow/ops/initializer_register.py
  python/oneflow/test/modules/test_initializer.py
Labels: enhancement, automerge, op, documentation, build

#9547 Add all gather into tensor and reduce scatter tensor api
  docs/source/distributed.rst
  oneflow/core/framework/op_interpreter/eager_local_op_interpreter.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/comm_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/ops/eager_nccl_ops.cpp
  python/oneflow/comm/__init__.py
  python/oneflow/comm/comm_ops.py
  python/oneflow/test/modules/test_comm_ops.py
Labels: enhancement, automerge, system, api

#9611 Add get worker info2
  python/oneflow/distributed/constants.py
  python/oneflow/utils/data/__init__.py
Labels: enhancement, python

#9612 support named tuple for return type for oneflow.min and oneflow.median
  oneflow/core/functional/functional_api.yaml
  python/oneflow/framework/docstr/math_ops.py
  python/oneflow/framework/docstr/reduce_ops.py
  python/oneflow/test/modules/test_median.py
  python/oneflow/test/modules/test_min.py
Labels: enhancement, feature, automerge, op, api

#9502 Session misc.
  oneflow/api/cpp/env_impl.cpp
  oneflow/api/python/env/env.h
  oneflow/api/python/framework/session_util.cpp
  oneflow/api/python/session/session.cpp
  oneflow/api/python/session/session.h
  oneflow/core/framework/multi_client_session_context.cpp
  oneflow/core/framework/session_util.cpp
  oneflow/core/framework/session_util.h
  oneflow/core/job/cluster.cpp
  oneflow/core/job/cluster.h
  oneflow/core/job/session_global_objects_scope.cpp
  oneflow/core/job/session_global_objects_scope.h
  python/oneflow/framework/c_api_util.py
  python/oneflow/framework/multi_client_session.py
  python/oneflow/framework/session_context.py
  python/oneflow/framework/unittest.py
  python/oneflow/test/expensive/test_session_reset_stream_index_state.py
Labels: enhancement, automerge, python, graph

#9618 add _flatten_dense_tensors and _unflatten_dense_tensors funcs in utils
  python/oneflow/_utils.py
  python/oneflow/test/modules/test_utils.py
Labels: enhancement, automerge, bug, eager, api

#9627 Add cuda.amp.autocast
  python/oneflow/cuda/amp/__init__.py
  python/oneflow/cuda/amp/autocast_mode.py
Labels: enhancement, automerge, python

#9626 regist oneflow.jit.script api for align
  python/oneflow/__init__.py
  python/oneflow/jit/__init__.py
  python/oneflow/jit/_script.py
  python/oneflow/test/modules/test_jit_script_api.py
Labels: enhancement, automerge, bug, eager, api

#9616 Refine error info of inconsistent input in lazy mode
  oneflow/core/framework/op_interpreter/op_interpreter_util.cpp
Labels: enhancement, automerge, system

#9557 Add FusedScaleTrilPattern PDLL Pattern
  oneflow/ir/include/OneFlow/OneFlowPatterns.td
  oneflow/ir/lib/OneFlow/PDLL/ForwardOpPatterns.pdll
  oneflow/ir/lib/OneFlow/Passes.cpp
  oneflow/ir/test/OneFlow/fuse_forward_ops.mlir
Labels: enhancement, automerge, ir

#8864 Record and print Python stack even in background thread
  cmake/oneflow.cmake
  oneflow/api/python/env/env.cpp
  oneflow/api/python/stack_getter.cpp
  oneflow/core/common/env_var/debug_mode.h
  oneflow/core/common/error.cpp
  oneflow/core/common/error.h
  oneflow/core/common/just.h
  oneflow/core/common/maybe_test.cpp
  oneflow/core/common/throw.h
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/test_functor.cpp
  oneflow/core/intrusive/shared_ptr.h
  oneflow/core/thread/is_main_thread_test.cpp
  oneflow/core/thread/thread_manager.h
  oneflow/core/vm/instruction.cpp
  oneflow/core/vm/instruction.h
  oneflow/core/vm/virtual_machine_engine.cpp
  oneflow/extension/stack/foreign_stack_getter.h
  oneflow/extension/stack/python/custom_eval_frame.c
  oneflow/extension/stack/python/custom_eval_frame.h
  oneflow/extension/stack/python/stack_getter.cpp
  oneflow/extension/stack/python/stack_getter.h
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/throw_error_kernel.cpp
  oneflow/user/ops/throw_error_op.cpp
  python/oneflow/__init__.py
  python/oneflow/test/exceptions/test_error_reported_in_thread.py
  python/oneflow/test/exceptions/throw_error.py
  python/oneflow/test/misc/test_stack_getter.py
Labels: feature, automerge, system

#9634 fix_pyobject_cast_error
  oneflow/api/python/caster/maybe.h
  oneflow/api/python/caster/optional.h
  oneflow/api/python/functional/common.h
  python/oneflow/test/tensor/test_tensor_part_3.py
Labels: enhancement, automerge, bug, system, api

#9630 Fix inplace div dtype bug and cpu scalar tensor auto-cast
  oneflow/core/functional/impl/binary_functor.cpp
  oneflow/core/functional/impl/binary_functor.h
Labels: automerge, bug, op

#9603 Dev suport tensor constant
  oneflow/core/ep/cpu/primitive/tensor_fill.cpp
  oneflow/core/ep/cuda/primitive/tensor_fill.cu
  oneflow/core/ep/include/primitive/tensor_fill.h
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/tensor_constant_kernel.cpp
  oneflow/user/ops/tensor_constant_op.cpp
  python/oneflow/nn/modules/constant.py
  python/oneflow/test/modules/test_constant.py
  python/oneflow/test/modules/test_global_full.py
Labels: enhancement, automerge, op, api

#9636 perf(slice): only memset in S to P in slice kernel
  oneflow/user/kernels/slice_kernel.cpp
Labels: enhancement, automerge, op

#9635 transfer oneflow.topk and oneflow.sort from python to C++
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/core/functional/impl/common.cpp
  oneflow/core/functional/impl/common.h
  oneflow/core/functional/impl/random_functor.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/sort.py
  python/oneflow/framework/docstr/topk.py
  python/oneflow/nn/modules/math_ops.py
  python/oneflow/nn/modules/sort.py
  python/oneflow/test/modules/test_math_ops.py
  python/oneflow/test/modules/test_sort.py
  python/oneflow/test/tensor/test_tensor_part_1.py
Labels: enhancement, feature, automerge, op, documentation, api, refactor

#9642 fix python3.9 compile error
  oneflow/extension/stack/python/custom_eval_frame.h
Labels: automerge, bug, build

#9629 Cuda align size
  oneflow/api/python/framework/device.cpp
  python/oneflow/nn/parallel/distributed.py
Labels: enhancement, TODO, automerge, api, python

#9640 Use pip cudnn/cublas
  .github/workflows/canary.yml
  .github/workflows/on_merge.yml
  .github/workflows/release.yml
  .github/workflows/simple.yml
  .github/workflows/test.yml
  ci/clang/build-llvm.sh
  ci/manylinux/build-gcc7.sh
  ci/manylinux/build.sh
  cmake/oneflow.cmake
  python/setup.py
Labels: enhancement, automerge, build

#9647 Fix canary release of cu117
  .github/workflows/canary.yml
Labels: bug, ci

#9623 add quick_gelu
  docs/source/nn.functional.rst
  docs/source/nn.rst
  docs/source/oneflow.rst
  oneflow/core/autograd/gradient_funcs/activation.cpp
  oneflow/core/ep/common/primitive/broadcast_elementwise_binary.h
  oneflow/core/ep/common/primitive/elementwise_unary.h
  oneflow/core/ep/cpu/primitive/binary_functor.h
  oneflow/core/ep/cpu/primitive/unary_functor.h
  oneflow/core/ep/cuda/primitive/binary_functor.cuh
  oneflow/core/ep/cuda/primitive/unary_functor.cuh
  oneflow/core/ep/include/primitive/binary_op.h
  oneflow/core/ep/include/primitive/unary_op.h
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/activation_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/activation_kernels.cpp
  oneflow/user/ops/quick_gelu_op.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/activation.py
  python/oneflow/nn/__init__.py
  python/oneflow/nn/functional/__init__.py
  python/oneflow/nn/modules/activation.py
  python/oneflow/test/modules/test_quick_gelu.py
Labels: automerge, op, documentation, api

#9650 remove useless print
  python/oneflow/utils/data/distributed.py
Labels: enhancement, automerge, eager, api

#9649 replace deprecated np.bool
  python/oneflow/framework/dtype.py
  python/oneflow/test/misc/test_np_dtype_converter.py
  python/oneflow/test/modules/test_as_tensor.py
  python/oneflow/test/modules/test_fused_scale_mask_softmax.py
  python/oneflow/test/modules/test_fused_scale_mask_softmax_dropout.py
  python/oneflow/test/tensor/test_tensor_part_2.py
Labels: enhancement, automerge, bug, python

#9651 README cu112 => cu117
  README.md
Labels: enhancement, python

#9639 Optimize LaunchLazyJobInstructionPolicy
  oneflow/core/vm/lazy_job_instruction_policy.h
Labels: enhancement, automerge, eager

#9652 Set CUDA_MODULE_LOADING to LAZY by default
  python/oneflow/__init__.py
Labels: enhancement, automerge, system

#9587 Add API doc for global mode.
  docs/source/utils.global_view.rst
  oneflow/core/job/global_mode.h
  python/oneflow/test/graph/test_graph_with_global.py
  python/oneflow/utils/global_view/__init__.py
  python/oneflow/utils/global_view/global_mode.py
Labels: automerge, documentation, python

#9655 fix undefined symbol by including header
  oneflow/extension/stack/python/custom_eval_frame.c
Labels: automerge, bug, build

#9273 Add stft op
  cmake/cuda.cmake
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/cufftplancache.h
  oneflow/user/kernels/pocketfft_hdronly.h
  oneflow/user/kernels/pocketfftplan.h
  oneflow/user/kernels/stft_kernel.cpp
  oneflow/user/kernels/stft_kernel.cu
  oneflow/user/ops/stft_op.cpp
  python/oneflow/__init__.py
  python/oneflow/test/exceptions/test_stft_op.py
  python/oneflow/test/modules/test_stft.py
Labels: enhancement, automerge, op, test, documentation, api

#9661 add jit.ignore api
  python/oneflow/jit/__init__.py
  python/oneflow/jit/_script.py
  python/oneflow/test/modules/test_jit_script_api.py
Labels: enhancement, automerge, bug, eager, api

#9663 align conv api with pytorch
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  python/oneflow/test/modules/test_conv2d.py
Labels: enhancement, feature, automerge, bug, eager, api

#9628 fix clang15 errors
  .github/workflows/test.yml
  ci/clang/build-llvm.sh
  cmake/caches/ci/llvm/cuda-75-clang.cmake
  cmake/third_party.cmake
  external/CMakeLists.txt
  oneflow/core/cuda/atomic.cuh
  oneflow/core/eager/eager_blob_object.cpp
  oneflow/core/eager/eager_blob_object.h
  oneflow/core/embedding/lru_cache.cu
  oneflow/core/intrusive/dss.h
  oneflow/core/intrusive/flat_msg.h
  oneflow/ir/oneflow-extension/include/PyAst/Ast.h
  oneflow/ir/oneflow-extension/lr_jit.cpp
  oneflow/user/kernels/tf_pool_gpu_kernel.cpp
  oneflow/user/kernels/unsorted_segment_sum_kernel_util.cu
Labels: enhancement, automerge, build

#9668 fix typo in distributed doc
  docs/source/distributed.rst
Labels: automerge, documentation, build

#9631 Add offload global tensor
  oneflow/api/python/env/env.cpp
  oneflow/core/common/mem_util.cpp
  oneflow/core/common/mem_util.h
  oneflow/core/framework/tensor.cpp
  oneflow/core/framework/tensor.h
  python/oneflow/test/modules/test_global_tensor_offload.py
  python/oneflow/test/modules/test_tensor_offload.py
Labels: feature

#9659 add sorted argument for oneflow.unique
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/indexed_slices_reduce_sum_kernel_util.cpp
  oneflow/user/kernels/unique_kernel.cpp
  oneflow/user/kernels/unique_kernel_util.cpp
  oneflow/user/kernels/unique_kernel_util.cu
  oneflow/user/kernels/unique_kernel_util.h
  oneflow/user/kernels/unique_with_counts_kernel.cpp
  python/oneflow/framework/docstr/tensor.py
  python/oneflow/nn/modules/unique.py
  python/oneflow/test/modules/test_global_unique.py
  python/oneflow/test/modules/test_unique.py
Labels: enhancement, feature, automerge, bug, op, interface

#9643 add pytorch fast atomic_add
  oneflow/core/kernel/kernel_util.cuh
  oneflow/user/kernels/upsample_bicubic_2d_kernel.cu
  oneflow/user/kernels/upsample_nearest_kernel.cu
Labels: enhancement, automerge, eager, api

#9658 Add heuristic search env
  python/oneflow/backends/cudnn/__init__.py
  python/oneflow/framework/config_util.py
  python/oneflow/nn/graph/graph_config.py
  python/oneflow/test/graph/test_optimization_conf.py
Labels: feature, automerge, eager, community

#9666 fix BinaryCrossEntropyWithLogitsMeanKernel
  oneflow/user/kernels/binary_cross_entropy_with_logits_mean_kernel.cu
Labels: bug, op

#9657 Refine normal cuda kernel impl
  oneflow/user/kernels/distributions/normal_distribution.cu
  python/oneflow/test/graph/test_long_add_n_pass.py
  python/oneflow/test/modules/test_generator.py
Labels: automerge, bug, op, need-highest-priority

#9669 Dev support inplace squeeze unsqueeze as strided
  docs/source/tensor.rst
  oneflow/core/framework/tensor_methods.cpp
  oneflow/core/framework/tensor_methods.h
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/core/functional/impl/math_functor.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/math_ops.py
  python/oneflow/framework/docstr/tensor.py
  python/oneflow/framework/tensor.py
  python/oneflow/test/modules/test_as_strided.py
  python/oneflow/test/modules/test_squeeze.py
  python/oneflow/test/modules/test_unsqueeze.py
Labels: enhancement, automerge, eager, api

#9656 fix: type_as
  oneflow/api/python/framework/tensor_functions.cpp
  python/oneflow/framework/tensor.py
  python/oneflow/nn/modules/constant.py
  python/oneflow/test/modules/test_global_tensor_ops.py
  python/oneflow/test/modules/test_tensor_ops.py
Labels: automerge, bug, op

#9665 autotest add random_dtype
  python/oneflow/test/modules/test_info.py
  python/oneflow/test_utils/automated_test_util/generators.py
  python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py
  python/oneflow/test_utils/test_util.py
Labels: enhancement, automerge, test, python
