Repository Oneflow-Inc/oneflow, pull requests merged in 2022-09, with the labels that each got.

#9034 install llvm headers
  cmake/third_party.cmake
Labels: enhancement, automerge, build, serving, xla

#8995 add saved tensor hooks
  oneflow/api/python/autograd/autograd.cpp
  oneflow/core/common/small_vector.h
  oneflow/core/framework/op_expr_grad_function.cpp
  oneflow/core/framework/op_expr_grad_function.h
  oneflow/core/framework/saved_tensor_hooks.h
  python/oneflow/__init__.py
  python/oneflow/autograd/__init__.py
  python/oneflow/autograd/graph.py
  python/oneflow/test/exceptions/test_saved_tensor_hooks.py
  python/oneflow/test/modules/test_saved_tensor_hooks.py
Labels: feature, automerge, eager

#9037 Enlarge SyncBatchnorm ci tests timeout threshold
  .github/workflows/test.yml
  ci/test/test_sync_batchnorm.sh
  python/oneflow/test/ddp/test_sync_batchnorm.py
  python/oneflow/test/ddp/test_sync_batchnorm_nhwc.py
Labels: automerge, bug, ci, op, test

#9038 install headers when building llvm in-tree
  cmake/third_party.cmake
  oneflow/ir/CMakeLists.txt
Labels: automerge, bug, build, system

#8988 add higher order derivative for pow
  oneflow/core/autograd/gradient_funcs/broadcast_binary_ops.cpp
  oneflow/core/autograd/higher_order_gradient_funcs/pow.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/broadcast_pow_grad_kernel.cpp
  oneflow/user/kernels/broadcast_pow_grad_kernel.cu
  oneflow/user/ops/broadcast_pow_grad_op.cpp
  python/oneflow/test/modules/test_global_higher_derivative_pow.py
  python/oneflow/test/modules/test_higher_derivative_pow.py
Labels: enhancement, automerge, op, test

#9022 Dev scream type kccl
  oneflow/api/python/functional/dispatch_stateful_ops.cpp
  oneflow/api/python/functional/dispatch_stateful_ops.yaml
  oneflow/core/common/stream_type.h
  oneflow/core/framework/stream_allocator_is_pinned.h
  oneflow/core/framework/stream_get_stream_type_name.h
  oneflow/core/framework/stream_is_comm_net_stream.h
  oneflow/core/framework/stream_need_soft_sync.h
  oneflow/core/framework/stream_on_independent_thread.h
  oneflow/core/framework/stream_support_stream_wait.h
  oneflow/core/functional/impl/comm_functor.cpp
  oneflow/core/vm/ep_record_event_instruction_policy.h
  oneflow/core/vm/release_tensor_instruction_policy.h
  oneflow/core/vm/stream_get_stream_policy.h
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/ops/comm_net_device_infer_util.cpp
  oneflow/user/ops/comm_net_device_infer_util.h
  oneflow/user/ops/eager_b_to_s_op.cpp
  oneflow/user/ops/eager_nccl_ops.cpp
  oneflow/user/ops/eager_p_to_b_op.cpp
  oneflow/user/ops/eager_p_to_s_op.cpp
  oneflow/user/ops/eager_s_to_b_op.cpp
  oneflow/user/ops/eager_s_to_p_op.cpp
  oneflow/user/ops/eager_s_to_s_op.cpp
  oneflow/user/ops/eager_symmetric_s_to_p_op.cpp
  oneflow/user/ops/nccl_logical_2d_sbp_ops.cpp
  oneflow/user/ops/nccl_logical_ops.cpp
  oneflow/user/ops/p2p_comm_op.cpp
Labels: enhancement, automerge, eager, system

#9033 Add higher order derivative for unary math op
  oneflow/core/autograd/higher_order_gradient_funcs/math_unary_op.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/higher_derivative_functor.cpp
  python/oneflow/test/modules/test_global_math_op_higher_derivative.py
  python/oneflow/test/modules/test_math_op_higher_derivative.py
Labels: enhancement, op, test

#8996 add oneembedding CI
  python/oneflow/test/expensive/test_oneembedding.py
Labels: enhancement, ci, test, embedding

#8942 Add iinfo / finfo
  docs/source/index.rst
  docs/source/type_info.rst
  oneflow/api/python/framework/typeinfo.cpp
  oneflow/api/python/framework/typeinfo.h
  oneflow/core/common/data_type.cpp
  oneflow/core/common/data_type.h
  python/oneflow/__init__.py
  python/oneflow/test/modules/test_info.py
Labels: enhancement, automerge, api, python

#9041 align worker seed
  python/oneflow/utils/data/_utils/worker.py
  python/oneflow/utils/data/dataloader.py
Labels: enhancement, automerge, eager, api

#9019 add higher order derivative for unary math op
  oneflow/core/autograd/higher_order_gradient_funcs/math_unary_op.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/higher_derivative_functor.cpp
  python/oneflow/test/modules/test_global_math_op_higher_derivative.py
  python/oneflow/test/modules/test_math_op_higher_derivative.py
Labels: enhancement, automerge, op, test

#9044 Remove disable chain merge optimizer subgraph with fw/bw pass
  oneflow/core/graph/task_graph.cpp
Labels: enhancement, automerge, bug, graph

#9049 add bfloat16 requires grad datatype
  oneflow/api/python/framework/tensor_functions.cpp
  oneflow/core/common/data_type.cpp
Labels: automerge, bug, system

#9024 Fix expand op
  oneflow/core/autograd/gradient_funcs/expand.cpp
  oneflow/core/ep/cuda/primitive/broadcast_elementwise_unary.cu
  oneflow/core/framework/tensor_methods.cpp
  oneflow/core/framework/tensor_methods.h
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/core/job_rewriter/auto_mixed_precision_lists.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/expand_kernel.cpp
  oneflow/user/kernels/expand_kernel.cu
  oneflow/user/kernels/expand_kernel_utils.cpp
  oneflow/user/kernels/expand_kernel_utils.h
  oneflow/user/ops/expand_op.cpp
  oneflow/user/ops/fused_gru_cell_op.cpp
  oneflow/user/ops/fused_lstm_cell_op.cpp
  python/oneflow/test/modules/test_expand_stride.py
  python/oneflow/test/modules/test_global_expand_op.py
Labels: automerge, bug, op, api

#9015 Upsample nearest 2d kernel regester half
  oneflow/user/kernels/upsample_nearest_kernel.cu
  python/oneflow/test/modules/test_upsample.py
Labels: enhancement, bug, eager

#8964 Refine vm deadlock report msg
  oneflow/core/vm/control_stream_policy.h
  oneflow/core/vm/critical_section_status_querier.h
  oneflow/core/vm/critical_section_stream_policy.cpp
  oneflow/core/vm/critical_section_stream_policy.h
  oneflow/core/vm/ep_optional_event_record_status_querier.h
  oneflow/core/vm/ep_stream_policy_base.cpp
  oneflow/core/vm/ep_stream_policy_base.h
  oneflow/core/vm/instruction.cpp
  oneflow/core/vm/instruction.h
  oneflow/core/vm/lazy_job_stream_policy.cpp
  oneflow/core/vm/lazy_job_stream_policy.h
  oneflow/core/vm/naive_instruction_status_querier.h
  oneflow/core/vm/stream_policy.h
  oneflow/core/vm/virtual_machine_engine.cpp
Labels: enhancement, automerge, bug, system

#9055 Fix no_grad domain call backward segfault bug
  oneflow/api/python/autograd/autograd.cpp
  oneflow/api/python/framework/thread.cpp
  oneflow/core/autograd/autograd_engine.cpp
  oneflow/core/common/env_var/autograd.h
  oneflow/core/framework/stream.cpp
  oneflow/core/framework/stream.h
  python/oneflow/test/modules/test_autograd.py
Labels: automerge, bug, eager

#9057 support_build_bfloat16_tensor_from_numpy
  oneflow/api/python/framework/tensor.cpp
  oneflow/api/python/utils/tensor_utils.cpp
  oneflow/core/common/data_type_seq.h
  python/oneflow/test/tensor/test_new_tensor.py
Labels: enhancement, automerge, system

#9062 fix module delattr bug
  python/oneflow/nn/module.py
  python/oneflow/test/modules/test_module.py
Labels: enhancement, automerge, bug, eager, api

#8992 Dev add flow.cuda.get_device_properties series api
  docs/source/cuda.rst
  oneflow/api/python/env/env.cpp
  oneflow/core/device/cuda_util.cpp
  oneflow/core/device/cuda_util.h
  python/oneflow/cuda/__init__.py
  python/oneflow/test/misc/test_env_cuda.py
Labels: enhancement, automerge, documentation, api, python, need-clean-ccache

#9071 Part-4: merge acc op in to chain for reuse memory acc input
  oneflow/core/graph/task_graph.cpp
  oneflow/core/job_rewriter/logical_chain_pass.cpp
Labels: enhancement, graph

#9045 Support dynamic attr for autograd.Function ctx
  docs/source/autograd.rst
  oneflow/api/common/sbp.h
  oneflow/api/python/autograd/autograd_function.cpp
  oneflow/api/python/autograd/autograd_function_state.cpp
  oneflow/api/python/autograd/autograd_function_state.h
  oneflow/api/python/caster/autograd_function_state.h
  oneflow/api/python/caster/common.h
  oneflow/api/python/caster/tensor.h
  oneflow/api/python/of_api_registry.h
  oneflow/api/python/symbol/sbp_symbol.cpp
  oneflow/core/framework/op_expr_grad_function.h
  python/oneflow/autograd/autograd_function.py
  python/oneflow/framework/docstr/autograd.py
  python/oneflow/test/modules/test_autograd_function.py
Labels: enhancement, automerge, system

#7427 Add more consistent test
  python/oneflow/test/modules/test_global_broadcast_matmul.py
  python/oneflow/test/modules/test_global_inv.py
  python/oneflow/test/modules/test_global_reciprocal.py
  python/oneflow/test/modules/test_global_reflection_pad2d.py
  python/oneflow/test/modules/test_global_repeat.py
  python/oneflow/test/modules/test_global_replication_pad2d.py
  python/oneflow/test/modules/test_global_roll.py
  python/oneflow/test/modules/test_global_round.py
  python/oneflow/test/modules/test_global_sort.py
  python/oneflow/test/modules/test_global_vector_matrix_product.py
Labels: enhancement, automerge, eager, test

#9053 implement flow.utils.checkpoint
  python/oneflow/test/modules/test_checkpointing.py
  python/oneflow/utils/__init__.py
  python/oneflow/utils/checkpoint.py
Labels: feature, automerge, eager

#9030 Add unary log10
  docs/source/oneflow.rst
  docs/source/tensor.rst
  oneflow/api/python/framework/tensor_functions.cpp
  oneflow/core/ep/common/primitive/binary_functor.h
  oneflow/core/ep/common/primitive/broadcast_elementwise_binary.h
  oneflow/core/ep/common/primitive/elementwise_unary.h
  oneflow/core/ep/common/primitive/unary_functor.h
  oneflow/core/ep/cuda/primitive/binary_functor.cuh
  oneflow/core/ep/cuda/primitive/unary_functor.cuh
  oneflow/core/ep/include/primitive/binary_op.h
  oneflow/core/ep/include/primitive/unary_op.h
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/unary_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/math_unary_elementwise_primitive_kernel.cpp
  oneflow/user/ops/math_unary_elementwise_seq.h
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/math_ops.py
  python/oneflow/framework/docstr/tensor.py
  python/oneflow/test/modules/test_math_ops.py
  python/oneflow/test/tensor/test_tensor_part_1.py
Labels: enhancement, automerge, op, documentation, api, python

#9054 default disable opt ss merge with fw pass
  oneflow/core/graph/task_graph.cpp
Labels: enhancement, automerge, graph

#9082 Fix 8768 broadcast like op throw std::bad_alloc
  oneflow/core/functional/impl/array_functor.cpp
  python/oneflow/test/exceptions/test_array_functor.py
Labels: automerge, bug, op, test

#9078 fix scalar_div divided by zero bug, and optimize scalar_sub
  oneflow/core/functional/impl/math_functor.cpp
Labels: enhancement, automerge, op

#9085 support free eager tensor in graph state dict
  python/oneflow/nn/graph/graph.py
Labels: enhancement, feature, automerge, bug, eager, api

#9087 Disabled ZeRO when enabled AutoParallel
  oneflow/core/job_rewriter/auto_parallel.cpp
  oneflow/core/job_rewriter/job_completer.cpp
  oneflow/core/job_rewriter/optimizer_placement_optimization_pass.cpp
Labels: AutoParallel

#9065 Speed up advance indexing when only one dim has value
  oneflow/core/functional/tensor_index.cpp
Labels: enhancement, automerge, op

#9091 Fix global cumprod_grad sbp bug
  oneflow/user/ops/cum_ops.cpp
  python/oneflow/test/modules/test_global_cumprod.py
Labels: automerge, bug, op

#9090 Dev refine sync bn tests
  .github/workflows/test.yml
  ci/test/test_sync_batchnorm.sh
  python/oneflow/nn/__init__.py
  python/oneflow/test/ddp/test_sync_batchnorm.py
  python/oneflow/test/ddp/test_sync_batchnorm_nhwc.py
  python/oneflow/test/modules/sync_batchnorm_test_util.py
  python/oneflow/test/modules/test_sync_batchnorm.py
Labels: enhancement, automerge, ci, test

#9079 Add nn.functional.kl_div
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  python/oneflow/framework/docstr/loss.py
  python/oneflow/nn/functional/__init__.py
  python/oneflow/nn/modules/loss.py
  python/oneflow/test/modules/test_loss.py
Labels: enhancement, automerge, documentation, api, python

#9005 one_embedding eager forward
  oneflow/core/autograd/gradient_funcs/one_embedding_lookup.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/core/job_rewriter/replace_embedding_ops_pass.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/data_shuffle_kernel.cu
  oneflow/user/kernels/one_embedding_data_shuffle.cuh
  oneflow/user/kernels/one_embedding_kernels.cu
  python/oneflow/one_embedding.py
Labels: enhancement, automerge, op

#8620 Use Primitive in Scalar Pow Grad
  oneflow/core/ep/common/primitive/binary_functor.h
  oneflow/core/ep/common/primitive/broadcast_elementwise_binary.h
  oneflow/core/ep/cpu/primitive/binary_functor.h
  oneflow/core/ep/cuda/primitive/binary_functor.cuh
  oneflow/core/ep/include/primitive/binary_op.h
  oneflow/user/kernels/scalar_math_kernels.cpp
  oneflow/user/kernels/scalar_math_kernels.cu
Labels: enhancement, automerge, op, primitive

#9070 Add higher order derivative for loss function
  oneflow/core/autograd/gradient_funcs/binary_cross_entropy.cpp
  oneflow/core/autograd/gradient_funcs/binary_cross_entropy_with_logits.cpp
  oneflow/core/autograd/gradient_funcs/binary_cross_entropy_with_logits_reduce_mean.cpp
  oneflow/core/autograd/gradient_funcs/kl_div.cpp
  oneflow/core/autograd/gradient_funcs/smooth_l1_loss.cpp
  oneflow/core/autograd/higher_order_gradient_funcs/binary_cross_entropy_loss.cpp
  oneflow/core/autograd/higher_order_gradient_funcs/binary_cross_entropy_with_logits.cpp
  oneflow/core/autograd/higher_order_gradient_funcs/binary_cross_entropy_with_logits_reduce_mean.cpp
  oneflow/core/autograd/higher_order_gradient_funcs/kl_div_loss.cpp
  oneflow/core/autograd/higher_order_gradient_funcs/nll_loss.cpp
  oneflow/core/autograd/higher_order_gradient_funcs/smooth_l1_loss.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_grad_functor.cpp
  oneflow/user/ops/loss_op_util.cpp
  python/oneflow/test/modules/test_global_higher_derivative_loss.py
  python/oneflow/test/modules/test_higher_derivative_loss.py
Labels: enhancement, automerge, op, test

#9032 Add higher order derivative for softmax and activation
  oneflow/core/autograd/gradient_funcs/log_softmax.cpp
  oneflow/core/autograd/higher_order_gradient_funcs/activation.cpp
  oneflow/core/autograd/higher_order_gradient_funcs/log_softmax.cpp
  oneflow/core/autograd/higher_order_gradient_funcs/softmax.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/activation_functor.cpp
  oneflow/core/functional/impl/higher_derivative_functor.cpp
  python/oneflow/test/modules/test_global_higher_derivative_activation.py
  python/oneflow/test/modules/test_global_higher_derivative_softmax.py
  python/oneflow/test/modules/test_higher_derivative_activation.py
  python/oneflow/test/modules/test_higher_derivative_softmax.py
Labels: enhancement, automerge, op, test

#9096 add higher order derivative for pool
  oneflow/core/autograd/higher_order_gradient_funcs/avg_pool.cpp
  oneflow/core/autograd/higher_order_gradient_funcs/max_pool.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/higher_derivative_functor.cpp
  oneflow/core/functional/impl/nn_grad_functor.cpp
  python/oneflow/test/modules/test_global_higher_derivative_pool.py
  python/oneflow/test/modules/test_higher_derivative_pool.py
Labels: enhancement, automerge, op, test

#9064 Cross Encropy 支持 probability 的 target
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  python/oneflow/nn/modules/loss.py
  python/oneflow/test/modules/test_loss.py
Labels: enhancement, automerge, api, python

#9101 Fix nvjpegDecodeParamsSetROI
  oneflow/core/kernel/image_decoder_random_crop_resize_kernel.cpp
Labels: automerge, bug, op

#9023 add series op : adaptive_max_pool1d/2d/3d
  docs/source/nn.functional.rst
  docs/source/nn.rst
  oneflow/core/autograd/gradient_funcs/adaptive_avg_pool.cpp
  oneflow/core/autograd/gradient_funcs/adaptive_max_pool.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/core/functional/impl/nn_grad_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowBase.td
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/adaptive_avg_pool_cpu_kernel.cpp
  oneflow/user/kernels/adaptive_avg_pool_gpu_kernel.cu
  oneflow/user/kernels/adaptive_max_pool_cpu_kernel.cpp
  oneflow/user/kernels/adaptive_max_pool_gpu_kernel.cu
  oneflow/user/kernels/adaptive_pool_kernel_util.h
  oneflow/user/ops/adaptive_max_pool_op.cpp
  python/oneflow/nn/__init__.py
  python/oneflow/nn/functional/__init__.py
  python/oneflow/nn/functional/functional_maxpool.py
  python/oneflow/nn/modules/pooling.py
  python/oneflow/test/modules/test_adaptive_max_pool.py
Labels: feature, automerge, op

#9017 one_embedding physical_block_size change to 4096
  docs/source/one_embedding.rst
  python/oneflow/one_embedding.py
Labels: enhancement, automerge, op

#9098 OneEmbedding add ONEFLOW_ONE_EMBEDDING_DISABLE_PIPELINE
  oneflow/core/graph_impl/normal_forward_compute_task_node.cpp
  oneflow/core/job/job_build_and_infer_ctx.cpp
  oneflow/core/job_rewriter/replace_embedding_ops_pass.cpp
  oneflow/core/job_rewriter/sequential_one_embedding_shuffle_ops_pass.cpp
  oneflow/core/operator/operator.h
  oneflow/user/ops/data_shuffle_op.cpp
Labels: enhancement, automerge, op

#9102 refine worker seed
  python/oneflow/nn/init.py
  python/oneflow/test/modules/test_generator.py
  python/oneflow/utils/data/_utils/worker.py
  python/oneflow/utils/data/dataloader.py
Labels: enhancement, bug, eager

#7784 Dev GroupNorm
  oneflow/core/autograd/gradient_funcs/group_norm.cpp
  oneflow/core/cuda/layer_norm.cuh
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/core/functional/impl/nn_grad_functor.cpp
  oneflow/core/job_rewriter/auto_mixed_precision_lists.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/group_norm_kernel.cu
  oneflow/user/ops/group_norm_op.cpp
  python/oneflow/nn/modules/normalization.py
  python/oneflow/test/modules/test_global_groupnorm.py
Labels: enhancement, automerge, op

#9067 Introduce bfloat16 type
  oneflow/api/python/utils/tensor_utils.cpp
  oneflow/core/common/bfloat16.h
  oneflow/core/common/bfloat16_math.h
  oneflow/core/common/bfloat16_test.cpp
  oneflow/core/common/data_type.cpp
  oneflow/core/common/data_type.h
  oneflow/core/common/data_type_seq.h
  oneflow/core/device/cuda_util.h
  oneflow/core/ep/cpu/primitive/binary_functor.h
  oneflow/core/ep/cpu/primitive/broadcast_elementwise_binary.cpp
  oneflow/core/ep/cpu/primitive/cast.cpp
  oneflow/core/ep/cpu/primitive/constant_pad.cpp
  oneflow/core/ep/cpu/primitive/elementwise_unary.cpp
  oneflow/core/ep/cpu/primitive/fill.cpp
  oneflow/core/ep/cpu/primitive/type_seq.h
  oneflow/core/ep/cpu/primitive/unary_functor.h
  oneflow/core/kernel/util/numeric_limits.cuh
  python/oneflow/test/tensor/test_bfloat16_activation.py
  python/oneflow/test/tensor/test_new_tensor.py
Labels: enhancement, automerge, system

#8974 Refine check in ibverbs
  oneflow/core/comm_network/ibverbs/ibverbs_comm_network.cpp
  oneflow/core/comm_network/ibverbs/ibverbs_memory_desc.cpp
  oneflow/core/comm_network/ibverbs/ibverbs_qp.cpp
  oneflow/core/platform/include/ibv.h
  oneflow/core/platform/lib/ibv_wrapper.cpp
Labels: purge, automerge, system

#8998 Support padding_idx in OneEmbedding
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/core/job_rewriter/replace_embedding_ops_pass.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/data_shuffle_kernel.cu
  oneflow/user/kernels/one_embedding_data_shuffle.cuh
  oneflow/user/kernels/one_embedding_kernels.cu
  python/oneflow/one_embedding.py
  python/oneflow/test/expensive/test_oneembedding_padding_idx.py
Labels: enhancement, automerge, op, embedding

#9118 interpolate api align
  python/oneflow/nn/modules/interpolate.py
  python/oneflow/test/modules/test_interpolate.py
Labels: enhancement, automerge, bug, eager, api

#9120 Fix masked select op bug
  python/oneflow/nn/modules/masked_select.py
  python/oneflow/test/modules/test_masked_select.py
Labels: enhancement, automerge, bug, eager, api

#9111 align with pytorch RANK env
  python/oneflow/framework/env_util.py
Labels: enhancement, automerge, bug, eager, api

#9116 Add oneflow hub
  docs/source/hub.rst
  docs/source/index.rst
  python/oneflow/__init__.py
  python/oneflow/hub.py
  python/oneflow/test/modules/test_hub.py
Labels: enhancement, feature, automerge, bug, eager, documentation, api

#9123 Fix ones like sbp bug and fix test import error in CI
  oneflow/core/auto_parallel/sbp_constructor.cpp
  python/oneflow/test/graph/test_alexnet_auto_parallel.py
Labels: AutoParallel

#9121 fix where op data_type infer bug
  oneflow/core/functional/impl/array_functor.cpp
  python/oneflow/test/modules/test_where.py
Labels: enhancement, automerge, bug, eager, api

#9127 fix like op infer dtype
  oneflow/user/ops/broadcast_like_op.cpp
  oneflow/user/ops/reduce_like_ops.cpp
  oneflow/user/ops/unsorted_segment_sum_op.cpp
Labels: automerge, bug, op

#9128 elementwise.cuh remove template parameter tail
  oneflow/core/cuda/elementwise.cuh
Labels: enhancement, automerge, op

#9134 fix_global_tensor_detach_bug
  oneflow/core/framework/tensor_impl.cpp
  oneflow/core/framework/tensor_impl.h
  python/oneflow/test/tensor/test_tensor_part_2.py
Labels: automerge, bug, system

#9095 Add deform_conv2d op
  docs/source/nn.functional.rst
  oneflow/core/autograd/gradient_funcs/deform_conv.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/core/functional/impl/nn_grad_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/deform_conv_kernel.cpp
  oneflow/user/kernels/deform_conv_kernel.cu
  oneflow/user/ops/deform_conv_op.cpp
  python/oneflow/__init__.py
  python/oneflow/nn/functional/__init__.py
  python/oneflow/nn/functional/functional_deform_conv.py
  python/oneflow/test/exceptions/test_deform_conv2d_op.py
  python/oneflow/test/modules/test_deform_conv2d.py
  python/oneflow/test/modules/test_global_deform_conv2d.py
Labels: enhancement, automerge, op, documentation, build

#9132 Fix inplace mul 0size check bug
  oneflow/core/functional/impl/common.cpp
  python/oneflow/test/modules/test_mul.py
Labels: enhancement, feature, automerge, bug, eager, api

#9135 Align round op to support round half to even
  oneflow/core/ep/common/primitive/unary_functor.h
  python/oneflow/framework/docstr/math_ops.py
  python/oneflow/test/modules/test_global_round.py
  python/oneflow/test/modules/test_round.py
Labels: enhancement, automerge, op, test, documentation

#9137 rm dict in module apply
  python/oneflow/nn/module.py
Labels: automerge, bug, eager, python

#9109 one_embedding support broadcast table_ids
  oneflow/core/functional/impl/nn_functor.cpp
Labels: enhancement, automerge, op

#9104 refine error message for framework
  oneflow/core/framework/arg_tuple.cpp
  oneflow/core/framework/attr_map.cpp
  oneflow/core/framework/config_def.cpp
  oneflow/core/framework/consistency_check.cpp
  oneflow/core/framework/device.cpp
  oneflow/core/framework/infer_util.cpp
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/framework/local_tensor_infer_cache.cpp
  oneflow/core/framework/multi_client_session_context.cpp
  oneflow/core/framework/nd_sbp.cpp
  oneflow/core/framework/nn_graph.cpp
  oneflow/core/framework/sync_symbol_parallel_desc.cpp
  oneflow/core/functional/impl/array_functor.cpp
  python/oneflow/test/exceptions/test_placement.py
Labels: feature, automerge, eager, graph, need-check-error-message

#9126 Fix loss scale precision
  oneflow/core/autograd/gradient_funcs/amp_white_identity.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/core/job_rewriter/auto_mixed_precision_lists.cpp
  oneflow/core/job_rewriter/autograd.cpp
  oneflow/core/job_rewriter/prune_amp_white_identity_op_pass.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/copy_data_content_kernel.cpp
  oneflow/user/ops/amp_white_identity_op.cpp
Labels: automerge, bug, graph

#8984 one embedding eager
  oneflow/core/autograd/gradient_funcs/one_embedding_fused_lookup.cpp
  oneflow/core/embedding/embedding_manager.cpp
  oneflow/core/embedding/embedding_manager.h
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/core/job_rewriter/auto_mixed_precision.cpp
  oneflow/core/job_rewriter/auto_mixed_precision_lists.cpp
  oneflow/core/job_rewriter/replace_embedding_ops_pass.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/data_shuffle_kernel.cu
  oneflow/user/kernels/one_embedding_kernels.cu
  oneflow/user/kernels/one_embedding_update_kernels.cu
  oneflow/user/ops/data_shuffle_op.cpp
  oneflow/user/ops/one_embedding_ops.cpp
  python/oneflow/one_embedding.py
  python/oneflow/test/expensive/test_id_shuffle.py
  python/oneflow/test/modules/test_one_embedding_adagrad.py
  python/oneflow/test/modules/test_one_embedding_adam.py
  python/oneflow/test/modules/test_one_embedding_ftrl.py
  python/oneflow/test/modules/test_one_embedding_sgd.py
Labels: enhancement, automerge, op

#9083 module.to aligned with pytorch
  python/oneflow/nn/module.py
  python/oneflow/test/modules/test_module_to.py
Labels: enhancement, automerge, python

#8853 eager global zero_grad update sbp from b to p
  oneflow/api/python/framework/tensor.cpp
  oneflow/core/autograd/autograd_engine.cpp
  python/oneflow/nn/optimizer/optimizer.py
  python/oneflow/test/modules/test_optim_sgd.py
Labels: enhancement, automerge, eager

#8979 Dev linalg cross
  docs/source/linalg.rst
  docs/source/oneflow.rst
  docs/source/tensor.rst
  oneflow/core/autograd/gradient_funcs/linalg_cross.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/common.cpp
  oneflow/core/functional/impl/common.h
  oneflow/core/functional/impl/linalg_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/linalg_cross_kernel.cpp
  oneflow/user/kernels/linalg_cross_kernel.cu
  oneflow/user/ops/linalg_cross_op.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/__init__.py
  python/oneflow/framework/docstr/linalg.py
  python/oneflow/framework/docstr/tensor.py
  python/oneflow/framework/tensor.py
  python/oneflow/linalg.py
  python/oneflow/test/exceptions/test_linalg.py
  python/oneflow/test/modules/test_global_linalg_cross.py
  python/oneflow/test/modules/test_linalg_cross.py
Labels: enhancement, feature, op, api

#9113 add nansum
  docs/source/oneflow.rst
  oneflow/core/autograd/gradient_funcs/reduce_ops.cpp
  oneflow/core/ep/common/primitive/elementwise_unary.h
  oneflow/core/ep/common/primitive/unary_functor.h
  oneflow/core/ep/cuda/primitive/unary_functor.cuh
  oneflow/core/ep/include/primitive/unary_op.h
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/core/ndarray/binary_func.h
  oneflow/core/ndarray/ndarray_reduce_impl.cpp
  oneflow/core/ndarray/ndarray_reduce_impl.cu
  oneflow/core/ndarray/ndarray_reduce_impl.h
  oneflow/core/ndarray/xpu_ndarray_assign.h
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/reduce_kernel.cpp
  oneflow/user/ops/math_binary_broadcast_ops.cpp
  oneflow/user/ops/reduce_ops.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/reduce_ops.py
  python/oneflow/test/modules/test_global_nansum.py
  python/oneflow/test/modules/test_nansum.py
Labels: automerge, op, documentation, api, python

#9138 Feat eager global tensor indexing
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/core/functional/tensor_index.cpp
  oneflow/core/functional/tensor_index.h
  python/oneflow/test/tensor/test_global_tensor_indexing.py
Labels: feature, automerge, eager

#9008 Add lr_scale for optimizers
  oneflow/core/job/job_conf.proto
  oneflow/core/job_rewriter/adadelta_optim.cpp
  oneflow/core/job_rewriter/adagrad_optm.cpp
  oneflow/core/job_rewriter/adam_optm.cpp
  oneflow/core/job_rewriter/ftrl_optm.cpp
  oneflow/core/job_rewriter/fuse_model_update_cast_pass.cpp
  oneflow/core/job_rewriter/fuse_update_ops_pass.cpp
  oneflow/core/job_rewriter/indexed_slices_optimizer_rewrite_pass.cpp
  oneflow/core/job_rewriter/lamb_optm.cpp
  oneflow/core/job_rewriter/lars_optm.cpp
  oneflow/core/job_rewriter/momentum_optm.cpp
  oneflow/core/job_rewriter/rmsprop_optm.cpp
  oneflow/core/job_rewriter/sgd_optm.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/model_update_kernel_util.cpp
  oneflow/user/kernels/model_update_kernel_util.cu
  oneflow/user/kernels/model_update_kernel_util.h
  oneflow/user/kernels/model_update_kernels.cpp
  oneflow/user/kernels/multi_tensor_model_update_kernel.cpp
  oneflow/user/kernels/multi_tensor_model_update_kernel_util.cu
  oneflow/user/kernels/multi_tensor_model_update_kernel_util.h
  python/oneflow/nn/optimizer/adadelta.py
  python/oneflow/nn/optimizer/adagrad.py
  python/oneflow/nn/optimizer/adam.py
  python/oneflow/nn/optimizer/adamw.py
  python/oneflow/nn/optimizer/lamb.py
  python/oneflow/nn/optimizer/optimizer.py
  python/oneflow/nn/optimizer/rmsprop.py
  python/oneflow/nn/optimizer/sgd.py
  python/oneflow/one_embedding.py
  python/oneflow/test/graph/test_graph_lr_scale.py
Labels: feature, automerge, api, graph

#9143 fix_ctc_loss_error_with_float_target_input
  oneflow/core/autograd/gradient_funcs/ctc_loss.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/core/functional/impl/nn_grad_functor.cpp
  oneflow/user/kernels/ctc_loss_kernel.cpp
  oneflow/user/kernels/ctc_loss_kernel_util.cpp
  oneflow/user/kernels/ctc_loss_kernel_util.cu
  oneflow/user/kernels/ctc_loss_kernel_util.h
  oneflow/user/ops/ctc_loss_op.cpp
  python/oneflow/test/modules/test_ctc_loss.py
Labels: enhancement, automerge, system

#9133 Inplace masked fill
  docs/source/tensor.rst
  oneflow/api/python/framework/tensor_functions.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/array_functor.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/tensor.py
  python/oneflow/test/modules/test_masked_fill.py
Labels: feature, automerge, op

#9139 Fix numpy>=1.23.0 advance indexing code
  python/oneflow/test/tensor/test_tensor_indexing.py
Labels: bug, test

#9140 Feat full auto parallel
  oneflow/core/framework/op_interpreter/lazy_op_interpreter.cpp
  oneflow/core/job/job_build_and_infer_ctx.cpp
  oneflow/core/job/job_desc.h
Labels: bug, AutoParallel

#9149 add_tensor_new_full_func
  docs/source/tensor.rst
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/tensor.py
  python/oneflow/framework/tensor.py
  python/oneflow/nn/modules/constant.py
  python/oneflow/test/modules/test_constant.py
  python/oneflow/test/modules/test_global_constant.py
Labels: enhancement, automerge, system

#9150 As strided regist more dtype
  oneflow/user/kernels/as_strided_kernel.cpp
  oneflow/user/kernels/as_strided_kernel.cu
  python/oneflow/test/modules/test_as_stride.py
Labels: enhancement, automerge, bug, eager, api, community

#9155 refine oneflow op infer dtype error message
  oneflow/user/ops/binary_cross_entropy_op.cpp
  oneflow/user/ops/binary_cross_entropy_with_logits_op.cpp
  oneflow/user/ops/binary_cross_entropy_with_logits_reduce_mean_op.cpp
  oneflow/user/ops/categorical_ordinal_encode_op.cpp
  oneflow/user/ops/celu_op.cpp
  oneflow/user/ops/concat_op.cpp
  oneflow/user/ops/conv_op.cpp
  oneflow/user/ops/count_not_finite_op.cpp
  oneflow/user/ops/cublas_bias_add_relu_matmul_grad_op.cpp
  oneflow/user/ops/cublas_fused_matmul_bias_add_grad_op.cpp
  oneflow/user/ops/cublas_fused_mlp_op.cpp
  oneflow/user/ops/dim_scatter_ops.cpp
  oneflow/user/ops/dropout_op.cpp
  oneflow/user/ops/elu_op.cpp
  oneflow/user/ops/embedding_op.cpp
  oneflow/user/ops/fused_dot_feature_interaction_op.cpp
  oneflow/user/ops/fused_matmul_bias_add_relu_dropout_op.cpp
  oneflow/user/ops/fused_scale_mask_softmax_dropout_op.cpp
  oneflow/user/ops/math_binary_broadcast_ops.cpp
  oneflow/user/ops/mish_op.cpp
  oneflow/user/ops/model_update_ops.cpp
  oneflow/user/ops/normalization_op.cpp
  oneflow/user/ops/stack_op.cpp
  oneflow/user/ops/tensor_buffer_ops.cpp
  oneflow/user/ops/tf_prelu_op.cpp
  oneflow/user/ops/threshold_op.cpp
  oneflow/user/ops/two_stage_reduce_ops.cpp
  oneflow/user/ops/unsorted_segment_sum_op.cpp
  oneflow/user/ops/where_op.cpp
Labels: enhancement, automerge, bug, eager, api

#9158 Fix to_global PyArg_ParseTupleAndKeywords
  oneflow/api/python/framework/tensor_functions.cpp
Labels: automerge, bug, eager, api

#9073 Implement exponential_ and multinomial
  docs/source/distributions.rst
  docs/source/index.rst
  docs/source/nn.rst
  docs/source/oneflow.rst
  oneflow/core/framework/random_generator_impl.cpp
  oneflow/core/framework/random_generator_impl.h
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/random_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/distributions/exponential_distribution.cpp
  oneflow/user/kernels/distributions/exponential_distribution.cu
  oneflow/user/kernels/distributions/exponential_distribution.h
  oneflow/user/kernels/distributions/exponential_kernel.cpp
  oneflow/user/kernels/distributions/exponential_kernel.h
  oneflow/user/kernels/distributions/multinomial_with_replacement_kernel.cpp
  oneflow/user/kernels/distributions/multinomial_with_replacement_kernel.cu
  oneflow/user/ops/distributions/exponential_op.cpp
  oneflow/user/ops/distributions/multinomial_with_replacement_op.cpp
  python/oneflow/__init__.py
  python/oneflow/distributions/__init__.py
  python/oneflow/distributions/categorical.py
  python/oneflow/distributions/distribution.py
  python/oneflow/distributions/utils.py
  python/oneflow/framework/docstr/random.py
  python/oneflow/framework/tensor.py
  python/oneflow/test/modules/test_multinomial.py
  python/oneflow/test/tensor/test_tensor_exponential.py
Labels: feature, automerge, op, api, python, need-clean-ccache

#9115 Disable IB when there no active IB devices
  oneflow/core/job/env_global_objects_scope.cpp
Labels: enhancement, automerge, system

#9162 fix lru_cache offset
  oneflow/core/embedding/lru_cache.cu
Labels: automerge, bug, system

#9151 Rename cast to global and cast from global
  oneflow/core/autograd/gradient_funcs/global_cast.cpp
  oneflow/core/framework/op_expr.cpp
  oneflow/core/framework/op_expr.h
  oneflow/core/framework/op_interpreter.h
  oneflow/core/framework/op_interpreter/eager_global_op_interpreter.cpp
  oneflow/core/framework/op_interpreter/eager_local_op_interpreter.cpp
  oneflow/core/framework/op_interpreter/op_interpreter.cpp
  oneflow/core/functional/impl/global_cast.cpp
Labels: enhancement, automerge, system

#9168 Refine datatype error message part2
  oneflow/user/ops/binary_cross_entropy_with_logits_op.cpp
  oneflow/user/ops/binary_cross_entropy_with_logits_reduce_mean_op.cpp
  oneflow/user/ops/fused_self_attention_query_mul_key_and_value_ops.cpp
  oneflow/user/ops/gelu_op.cpp
  oneflow/user/ops/group_norm_op.cpp
  oneflow/user/ops/hardshrink_op.cpp
  oneflow/user/ops/hardsigmoid_op.cpp
  oneflow/user/ops/hardswish_op.cpp
  oneflow/user/ops/hardtanh_op.cpp
  oneflow/user/ops/image_object_preprocess_ops.cpp
  oneflow/user/ops/image_preprocess_ops.cpp
  oneflow/user/ops/in_top_k_op.cpp
  oneflow/user/ops/kl_div_op.cpp
  oneflow/user/ops/l1_l2_regularize_gradient_op.cpp
  oneflow/user/ops/l2_normalize_op.cpp
  oneflow/user/ops/layer_norm_op.cpp
  oneflow/user/ops/leaky_relu_op.cpp
  oneflow/user/ops/log_softmax_op.cpp
  oneflow/user/ops/matmul_op.cpp
  oneflow/user/ops/matrix_vector_product_op.cpp
  oneflow/user/ops/normalization_op.cpp
  oneflow/user/ops/one_embedding_ops.cpp
  oneflow/user/ops/relu_op.cpp
  oneflow/user/ops/tensor_buffer_ops.cpp
Labels: enhancement, automerge, bug, eager, api

#9159 support tensor.triu_
  oneflow/api/python/framework/tensor_functions.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/array_functor.cpp
  python/oneflow/test/modules/test_triu.py
Labels: enhancement, eager, api

#9142 tensor.copy_ support stride
  python/oneflow/framework/tensor.py
  python/oneflow/test/modules/test_copy.py
Labels: enhancement, bug, eager

#9145 PersistentTable add read_only flag
  oneflow/api/python/framework/one_embedding.cpp
  oneflow/core/embedding/persistent_table.cpp
  oneflow/core/embedding/persistent_table.h
Labels: enhancement, automerge, system, need-all-tests-even-fail, need-clean-ccache

#9170 avg_pool_nd support half
  oneflow/user/kernels/avg_pool_kernel.cpp
  oneflow/user/kernels/avg_pool_kernel.cu
  oneflow/user/kernels/avg_pool_kernel_util.h
  python/oneflow/test/modules/test_avgpool.py
Labels: enhancement, automerge, eager, op

#9161 fix new_ones size paramater
  python/oneflow/framework/tensor.py
Labels: automerge, bug, op, python

#9191 hot-fix
  python/oneflow/test/modules/test_avgpool.py
Labels: bug, eager

#9183 skip env var check and calculate local rank if not given
  oneflow/core/rpc/lib/global_process_ctx.cpp
  python/oneflow/framework/env_util.py
Labels: automerge, bug, python, need-highest-priority

#9171 set to_contiguous to amp clear list
  oneflow/core/common/data_type.h
  oneflow/core/job_rewriter/auto_mixed_precision_lists.cpp
  oneflow/user/kernels/to_contiguous_kernel.cpp
  oneflow/user/kernels/to_contiguous_kernel.cu
  oneflow/user/kernels/to_contiguous_kernel.h
  python/oneflow/test/modules/test_contiguous.py
Labels: enhancement, automerge, op, system

#9182 add tensor.nansum
  docs/source/tensor.rst
  oneflow/api/python/framework/tensor_functions.cpp
  python/oneflow/framework/docstr/tensor.py
  python/oneflow/test/tensor/test_tensor_part_2.py
Labels: enhancement, automerge, documentation, api, python

#9172 Add slight cost for different sbp in 1 device
  oneflow/core/auto_parallel/sbp_constructor.cpp
  oneflow/core/framework/sbp_infer_util.cpp
  oneflow/core/job_rewriter/auto_parallel.cpp
Labels: bug, graph, AutoParallel

#9196 refine_to_contiguous_dtype_register
  oneflow/core/job_rewriter/auto_mixed_precision_lists.cpp
  oneflow/user/kernels/to_contiguous_kernel.cpp
  oneflow/user/kernels/to_contiguous_kernel.cu
  oneflow/user/kernels/to_contiguous_kernel.h
  python/oneflow/test/modules/test_contiguous.py
Labels: enhancement, automerge, eager, op

#9199 skip autocast for non-user op
  oneflow/core/framework/autocast.h
  oneflow/core/functional/tensor_processor.cpp
  oneflow/core/job_rewriter/auto_mixed_precision_lists.cpp
  python/oneflow/test/tensor/test_autocast.py
Labels: automerge, bug, system

#9189 `copy_` support numpy fp16
  oneflow/api/python/framework/tensor.cpp
  oneflow/api/python/utils/tensor_utils.cpp
  oneflow/api/python/utils/tensor_utils.h
  python/oneflow/framework/tensor.py
  python/oneflow/test/modules/test_copy.py
Labels: automerge, bug, python
