Repository Oneflow-Inc/oneflow, pull requests merged in 2022-10, with the labels that each got.

#9147 fix matmul 0 size input error
  oneflow/user/kernels/matmul_kernels.cpp
Labels: automerge, bug, op

#8865 Fix broadcast fmod grad
  oneflow/core/autograd/gradient_funcs/broadcast_binary_ops.cpp
  oneflow/core/autograd/gradient_funcs/scalar_floordiv.cpp
  oneflow/core/autograd/gradient_funcs/scalar_truncdiv.cpp
  oneflow/core/ep/common/primitive/binary_functor.h
  oneflow/core/ep/common/primitive/broadcast_elementwise_binary.h
  oneflow/core/ep/cpu/primitive/binary_functor.h
  oneflow/core/ep/cuda/primitive/binary_functor.cuh
  oneflow/core/ep/include/primitive/binary_op.h
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/binary_functor.cpp
  oneflow/core/functional/impl/binary_grad_functor.cpp
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/math_binary_elementwise_func.h
  oneflow/user/kernels/math_binary_elementwise_kernel.cpp
  oneflow/user/kernels/math_binary_elementwise_kernel.cu
  oneflow/user/kernels/scalar_math_kernels.cpp
  oneflow/user/ops/math_binary_elementwise_seq.h
  oneflow/user/ops/scalar_math_op.cpp
  python/oneflow/test/modules/test_fmod.py
  python/oneflow/test/modules/test_global_fmod.py
  python/oneflow/test/modules/test_math_ops.py
  python/oneflow/test/modules/test_trunc_divide.py
Labels: automerge, bug, op

#9094 Feat straighten compress memory
  docs/source/graph.rst
  oneflow/core/graph/straighten_nodes.cpp
  oneflow/core/graph/task_graph.cpp
  oneflow/core/graph/task_graph.h
  oneflow/core/job/compiler.cpp
  oneflow/core/job/intra_job_mem_sharing_util.cpp
  oneflow/core/job/job_conf.proto
  oneflow/core/job/memory_share_strategy.cpp
  oneflow/core/job/memory_share_strategy.h
  python/oneflow/nn/graph/graph_config.py
Labels: feature, automerge, graph

#9185 Add contains magic method
  python/oneflow/framework/tensor.py
  python/oneflow/test/tensor/test_tensor_part_1.py
Labels: enhancement, automerge, bug, eager, api

#9204 Build cuda 11.8
  CMakeLists.txt
  cmake/third_party/nccl.cmake
Labels: enhancement, build

#9206 export unsorted segment sum
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/array_functor.cpp
  python/oneflow/one_embedding.py
Labels: enhancement, automerge, op

#9112 Optimize OneEmbedding Save Snapshot
  oneflow/core/embedding/cache.h
  oneflow/core/embedding/cached_key_value_store.cu
  oneflow/core/embedding/full_cache.cu
  oneflow/core/embedding/lru_cache.cu
Labels: enhancement, automerge, system, embedding

#9201 Add Tensor.scatter_add & refine scatter
  docs/source/tensor.rst
  oneflow/core/functional/functional_api.yaml
  python/oneflow/framework/docstr/tensor.py
  python/oneflow/framework/tensor.py
  python/oneflow/nn/modules/scatter.py
  python/oneflow/test/modules/test_scatter_ops.py
  python/oneflow/test/tensor/test_tensor_part_3.py
Labels: enhancement, feature, op

#9195 optimize layernorm need padding cols perf
  oneflow/core/cuda/layer_norm.cuh
Labels: enhancement, op

#9200 Support Inplace behavior in Type Promotion
  oneflow/core/functional/impl/binary_functor.cpp
  oneflow/core/functional/tensor_processor.cpp
  oneflow/core/functional/tensor_processor.h
  python/oneflow/test/modules/test_add.py
Labels: enhancement, automerge, op, system

#9213 Fix Broadcast Matmul check
  oneflow/user/ops/matmul_op.cpp
Labels: enhancement, automerge, bug, op

#9209 Export MultiTensor Update and FuseUpdateCast to GraphConfig
  oneflow/core/job/job_conf.proto
  oneflow/core/job/job_desc.h
  oneflow/core/job_rewriter/fuse_model_update_cast_pass.cpp
  oneflow/core/job_rewriter/multi_tensor_model_update.cpp
  python/oneflow/nn/graph/graph_config.py
  python/oneflow/test/graph/test_multi_tensor_adam_update_with_cast.py
  python/oneflow/test/graph/test_multi_tensor_sgd_update_with_cast.py
Labels: enhancement, automerge, system

#9215 fix bug of matmul dim check in `oneflow.bmm`
  oneflow/core/functional/impl/nn_functor.cpp
Labels: enhancement, automerge, op, api

#9211 Fix graph out argstree type judge
  python/oneflow/nn/graph/util.py
  python/oneflow/test/graph/test_graph_io_check.py
Labels: automerge, bug, graph

#9225 fix ConcatFunctor error message
  oneflow/core/functional/impl/array_functor.cpp
Labels: automerge, bug, op

#9226 Check async errors after kernel launched
  oneflow/core/ep/cuda/cuda_stream.cpp
  oneflow/core/ep/cuda/cuda_stream.h
  oneflow/core/ep/include/stream.h
  oneflow/core/lazy/actor/actor.cpp
  oneflow/core/lazy/actor/light_actor.cpp
  oneflow/user/kernels/stateful_opkernel.cpp
Labels: enhancement, op

#9219 Skip unnecessary passes
  oneflow/core/job_rewriter/cudnn_fused_normalization_add_relu_pass.cpp
  oneflow/core/job_rewriter/do_parallel_cast_before_widening_type_cast_pass.cpp
  oneflow/core/job_rewriter/job_completer.cpp
  oneflow/core/job_rewriter/prune_amp_white_identity_op_pass.cpp
  oneflow/core/job_rewriter/prune_parallel_cast_op_pass.cpp
  oneflow/core/job_rewriter/split_sparse_softmax_cross_entropy_op_pass.cpp
Labels: enhancement, system, graph

#9230 one_embedding fix typo
  oneflow/core/embedding/embedding_manager.cpp
  python/oneflow/one_embedding.py
Labels: enhancement, automerge, op

#9228 [GetAsyncError] Add op name to error message
  oneflow/core/lazy/actor/actor.cpp
  oneflow/core/lazy/actor/light_actor.cpp
Labels: enhancement, automerge, op

#9229 [JobBuildAndInferCtx]Remove an inefficient check
  oneflow/core/job/job_build_and_infer_ctx.cpp
Labels: enhancement, graph

#9232 Fix linalg cross 0-size input error
  oneflow/user/kernels/linalg_cross_kernel.cu
Labels: automerge, bug, op

#9233 Add silu to amp list
  oneflow/core/job_rewriter/auto_mixed_precision_lists.cpp
Labels: enhancement, automerge, op

#9236 Disable CUDA virtual arch compilation
  CMakeLists.txt
Labels: enhancement, build

#9227 Support set/get_default_dtype interface
  docs/source/oneflow.rst
  oneflow/api/python/framework/dtype.cpp
  oneflow/api/python/functional/tensor_api.cpp
  oneflow/api/python/utils/tensor_utils.cpp
  oneflow/core/framework/dtype.cpp
  oneflow/core/framework/dtype.h
  oneflow/core/functional/impl/random_functor.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/oneflow.py
  python/oneflow/framework/dtype.py
  python/oneflow/nn/modules/constant.py
  python/oneflow/nn/modules/empty.py
  python/oneflow/test/modules/test_default_dtype.py
Labels: feature, automerge, eager

#9237 Enhance doctest error message
  python/oneflow/test/modules/test_functional_docstr.py
Labels: automerge, test, documentation

#9160 Feat: script to import oneflow as torch globally
  .github/workflows/test.yml
  ci/test/test_mock.sh
  oneflow/core/common/error.cpp
  python/oneflow/mock_torch/__init__.py
  python/oneflow/mock_torch/__main__.py
  python/oneflow/mock_torch/torch/__init__.py
  python/oneflow/test/misc/test_mock_torch.py
  python/setup.py
Labels: feature, automerge, python

#9164 add time and mem log tools
  oneflow/core/common/mem_util.cpp
  oneflow/core/common/mem_util.h
  oneflow/core/common/time_util.h
  oneflow/core/framework/nn_graph.cpp
Labels: enhancement, feature, automerge, tooling

#9234 support bool for `oneflow.nn.functional.pad`
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/user/kernels/pad_kernel.cpp
  python/oneflow/test/modules/test_constant_pad.py
Labels: enhancement, automerge, bug, test, api

#9238 Feat: rand/randn support float16 kernel
  oneflow/core/functional/impl/random_functor.cpp
  oneflow/user/kernels/distributions/common.h
  oneflow/user/kernels/distributions/normal_distribution.cpp
  oneflow/user/kernels/distributions/normal_distribution.cu
  oneflow/user/kernels/distributions/normal_kernel.cpp
  oneflow/user/kernels/distributions/uniform_distribution.cpp
  oneflow/user/kernels/distributions/uniform_distribution.cu
  oneflow/user/kernels/distributions/uniform_kernel.cpp
  python/oneflow/test/modules/test_rand.py
  python/oneflow/test/modules/test_randn.py
Labels: feature, automerge, op

#9247 TensorIndexing support float16
  oneflow/user/kernels/gather_kernel.cpp
  oneflow/user/kernels/gather_kernel_util.cpp
  oneflow/user/kernels/nd_index_slice_kernels.cpp
  oneflow/user/kernels/nd_index_slice_kernels.cu
  oneflow/user/kernels/slice_kernel.cpp
  oneflow/user/kernels/slice_util.cpp
  oneflow/user/kernels/slice_util.cu
  oneflow/user/kernels/slice_util.h
  python/oneflow/framework/tensor.py
  python/oneflow/test/tensor/test_tensor_indexing2.py
Labels: enhancement, automerge, op

#9243 Add cudnn handle pool
  oneflow/core/device/cudnn_conv_util.cpp
  oneflow/core/device/cudnn_util.cpp
  oneflow/core/device/cudnn_util.h
  oneflow/core/job/env_global_objects_scope.cpp
  oneflow/user/kernels/normalization_kernel.cu
  oneflow/user/ops/normalization_op.cpp
Labels: enhancement, automerge, system

#9250 Added error message for CUDA device incompatibility
  cmake/oneflow.cmake
  oneflow/core/hardware/cuda_device_descriptor.cpp
Labels: enhancement, automerge, build

#9249 Fix autograd.Function memory leak
  oneflow/api/python/autograd/autograd_function_state.cpp
  oneflow/api/python/autograd/autograd_function_state.h
  python/oneflow/test/modules/test_autograd_function.py
Labels: automerge, bug, eager

#9210 Feat speed up mem reuse
  oneflow/core/job/intra_job_mem_sharing_util.cpp
  oneflow/core/job/job_conf.proto
  oneflow/core/job/memory_share_strategy.cpp
  oneflow/core/job/memory_share_strategy.h
Labels: feature, automerge, graph

#9242 fix bug: segfult when argmax has 0 size tensor as input
  oneflow/user/kernels/argmax_kernel.cpp
  oneflow/user/kernels/argmax_kernel.cu
Labels: automerge, bug, op

#9014 fix_half_check_of_reduce_mean
  oneflow/core/functional/impl/math_functor.cpp
  python/oneflow/test/modules/test_mean.py
Labels: enhancement, automerge, bug, eager

#9253 Support float16 for initializer operators
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/user/kernels/fill_kernel.cpp
  oneflow/user/kernels/fill_kernel.cu
  python/oneflow/ops/initializer_register.py
  python/oneflow/test/tensor/test_tensor_part_1.py
Labels: enhancement, automerge, eager

#9241 Add half clamp
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/user/kernels/clip_by_value_kernel.cpp
  oneflow/user/kernels/clip_by_value_kernel.cu
  oneflow/user/kernels/clip_by_value_kernel.h
  python/oneflow/test/modules/test_clamp.py
Labels: enhancement, automerge, op

#9257 [CUDA]CheckVersionCompatibility
  oneflow/core/ep/cuda/cuda_stream.cpp
Labels: enhancement, automerge, system

#9256 Feat: monkeypatching pytorch
  .github/workflows/test.yml
  ci/test/test_mock.sh
  ci/test/test_mock_function.sh
  ci/test/test_mock_script.sh
  python/oneflow/mock_torch/__init__.py
  python/oneflow/mock_torch/torch/__init__.py
  python/oneflow/test/misc/test_mock.py
  python/oneflow/test/misc/test_mock_simple.py
Labels: feature, automerge, python

#9246 support destory_rdma
  oneflow/api/python/env/env.cpp
  oneflow/core/job/env_global_objects_scope.cpp
  oneflow/core/job/env_global_objects_scope.h
  python/oneflow/env.py
  python/oneflow/utils/data/dataloader.py
Labels: enhancement, bug, eager

#9156 add bincount
  docs/source/oneflow.rst
  docs/source/tensor.rst
  oneflow/api/python/framework/tensor_functions.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/bincount_kernel.cpp
  oneflow/user/kernels/bincount_kernel.cu
  oneflow/user/ops/bincount_op.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/array_ops.py
  python/oneflow/framework/docstr/tensor.py
  python/oneflow/test/modules/test_bincount.py
  python/oneflow/test/modules/test_global_bincount.py
  python/oneflow/test/modules/test_tensor_ops.py
Labels: enhancement, op, documentation, api, python

#9205 ONEFLOW_STREAM_ENABLE_H2D_STREAM
  oneflow/core/common/env_var/stream.h
  oneflow/user/ops/copy_op.cpp
Labels: enhancement, automerge, system

#9262 Modify generator.manual_seed to return generator rather than None
  oneflow/api/python/framework/random_generator.cpp
  python/oneflow/framework/docstr/random.py
Labels: enhancement, automerge, system, api

#9261 Dev add tensor bernoulli
  docs/source/tensor.rst
  oneflow/api/python/framework/tensor_functions.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/core/functional/impl/random_functor.cpp
  python/oneflow/framework/docstr/tensor.py
Labels: enhancement, automerge, documentation, api, python

#9270 support nested asyncs.thread
  python/oneflow/asyncs/thread.py
Labels: automerge, bug, system

#9176 OneEmbedding add smart decay sparse adam
  oneflow/core/job/job_conf.proto
  oneflow/core/job_rewriter/replace_embedding_ops_pass.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/one_embedding_kernels.cu
  oneflow/user/kernels/one_embedding_update_kernels.cu
  oneflow/user/ops/one_embedding_ops.cpp
  python/oneflow/one_embedding.py
Labels: enhancement, automerge, op

#9263 upgrade clang-tidy used in ninja of_tidy
  ci/check/run_clang_tidy.py
Labels: enhancement, automerge, build

#9245 Feat/compile time count
  oneflow/core/common/time_util.h
  oneflow/core/framework/nn_graph.cpp
  oneflow/core/job/compiler.cpp
  oneflow/core/job/job_build_and_infer_ctx.cpp
  oneflow/core/job_rewriter/job_completer.cpp
Labels: feature, automerge, tooling, graph

#9274 fix random_normal
  oneflow/user/kernels/distributions/normal_distribution.cu
Labels: automerge, bug, op

#9284 Flip and upsample bilinear support fp16
  oneflow/user/kernels/flip_kernel.cu
  oneflow/user/kernels/upsample_bilinear_2d_kernel.cu
Labels: enhancement, automerge, bug, eager, api

#9276 Fix PruneAmpWhiteIdentityOpPass
  oneflow/core/job_rewriter/prune_amp_white_identity_op_pass.cpp
Labels: automerge, bug, graph

#9283 support api flow.randn_like
  docs/source/oneflow.rst
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/random_functor.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/random.py
  python/oneflow/test/modules/test_randn_like.py
Labels: enhancement, automerge, eager, api

#8670 remove dry run, add sanitizers to ci
  .github/workflows/canary.yml
  .github/workflows/on_merge.yml
  .github/workflows/release.yml
  .github/workflows/simple.yml
  .github/workflows/test.yml
  .lsan-suppressions
  .tsan-suppressions
  .ubsan-suppressions
  CMakeLists.txt
  ci/test/dry_run_test.sh
  cmake/caches/ci/cpu-asan-ubsan.cmake
  cmake/caches/ci/cpu-tsan.cmake
  oneflow/core/job/compiler.cpp
  oneflow/core/job/env_global_objects_scope.cpp
  oneflow/core/job/job_build_and_infer_ctx.cpp
  oneflow/core/job/oneflow.cpp
  oneflow/core/job/resource_desc.cpp
  oneflow/core/job/resource_desc.h
  oneflow/ir/lib/OneFlow/Passes.cpp
Labels: feature, automerge, ci

#9290 add build config for RTX 40xx GPUs
  CMakeLists.txt
Labels: automerge, bug, build

#9291 Bool support for triu
  oneflow/user/kernels/triu_kernel.cpp
  oneflow/user/kernels/triu_kernel.cu
Labels: enhancement, automerge, op

#9294 Refix PruneAmpWhiteIdentityOpPass
  oneflow/core/job_rewriter/prune_amp_white_identity_op_pass.cpp
Labels: automerge, bug, graph

#9275 fix concat #8833
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/user/ops/concat_op.cpp
  python/oneflow/test/modules/test_concat.py
  python/oneflow/test/modules/test_global_concat.py
Labels: enhancement, feature, purge, automerge, bug, op, documentation

#9292 support half for masked_fill
  oneflow/core/functional/impl/array_functor.cpp
Labels: enhancement, automerge, op

#9298 Fix BatchNorm performance
  oneflow/user/kernels/normalization_kernel.cu
Labels: automerge, bug, op

#9264 slice update cpu kernel multi_thread loop
  oneflow/user/kernels/slice_util.cpp
Labels: enhancement, feature, automerge, bug, ci, eager, api

#9295 fix inplace bug in `tensor.masked_fill_`
  oneflow/api/python/framework/tensor_functions.cpp
  python/oneflow/test/modules/test_masked_fill.py
Labels: enhancement, automerge, bug, test, api

#9301 fix_inplace_copy_bug
  oneflow/api/python/functional/tensor_api.cpp
  oneflow/user/ops/assign_op.cpp
  python/oneflow/test/modules/test_copy.py
Labels: enhancement, automerge, bug, system

#9287 FusedMultiHeadAttentionInference
  CMakeLists.txt
  cmake/oneflow.cmake
  external/CMakeLists.txt
  external/cutlass/CMakeLists.txt
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/core/job_rewriter/auto_mixed_precision_lists.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/fused_multi_head_attention_inference_kernel.cu
  oneflow/user/ops/fused_multi_head_attention_inference_op.cpp
  python/oneflow/test/modules/test_fused_multi_head_attention_inference.py
Labels: feature, automerge, op

#9306 Set the default value of CUDA_STATIC to OFF when CUDA version is greater than or equal to 11.8
  cmake/cuda.cmake
Labels: enhancement, build

#9281 Reduce pass time cost
  oneflow/core/graph/boxing/boxing_logger.cpp
  oneflow/core/graph/op_graph.cpp
  oneflow/core/job/job_build_and_infer_ctx.cpp
  oneflow/core/job_rewriter/cudnn_fused_normalization_add_relu_pass.cpp
  oneflow/core/job_rewriter/fix_pipeline_stage_id_pass.cpp
  oneflow/core/job_rewriter/fuse_consecutive_add_pass.cpp
  oneflow/core/job_rewriter/pipeline_buffer_pass.cpp
  oneflow/core/job_rewriter/prune_amp_white_identity_op_pass.cpp
  oneflow/core/job_rewriter/prune_cast_to_static_shape_op_pass.cpp
  oneflow/core/job_rewriter/prune_parallel_cast_op_pass.cpp
  oneflow/core/job_rewriter/prune_pinned_identity_op_pass.cpp
  oneflow/core/job_rewriter/replace_embedding_ops_pass.cpp
  oneflow/core/job_rewriter/split_sparse_softmax_cross_entropy_op_pass.cpp
  python/oneflow/framework/graph_build_util.py
  python/oneflow/test/graph/test_comb1to2d.py
  python/oneflow/test/graph/test_comb2d.py
  python/oneflow/test/graph/test_gbc1to2d.py
  python/oneflow/test/graph/test_gbc2d.py
  python/oneflow/test/graph/test_gbc2to1d.py
  python/oneflow/test/graph/test_gbc2to2d.py
  python/oneflow/test/graph/test_long_add_n_pass.py
  python/oneflow/test/graph/test_nccl_logical_send_recv.py
  python/oneflow/test/modules/test_comb2to2d.py
Labels: enhancement, automerge, graph

#9304 Refactor get sbp signature
  oneflow/core/framework/sbp_context.h
  oneflow/core/framework/sbp_infer_util.cpp
  oneflow/core/framework/sbp_infer_util.h
  oneflow/core/job_rewriter/optimizer_placement_optimization_pass.cpp
  oneflow/core/operator/dynamic_reshape_op.cpp
  oneflow/core/operator/operator.cpp
  oneflow/core/operator/operator.h
  oneflow/core/operator/user_op.cpp
  oneflow/core/operator/user_op.h
  oneflow/user/ops/reshape_op.cpp
  oneflow/user/ops/reshape_user_op_util.cpp
  oneflow/user/ops/reshape_user_op_util.h
Labels: automerge, bug, eager, refactor, need-clean-ccache, graph

#9316 Fix type error for entering a single tensor using concat op
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/core/functional/tensor_processor.cpp
  python/oneflow/test/modules/test_concat.py
Labels: automerge, bug, op

#9293 Add more sbp signature print functions for log and debug
  oneflow/core/job/sbp_parallel.cpp
  oneflow/core/job/sbp_parallel.h
  oneflow/core/operator/operator.cpp
  oneflow/user/ops/reshape_like_op.cpp
Labels: automerge, bug, graph

#9308 Release/nightly cu118
  .github/workflows/canary.yml
  .github/workflows/on_merge.yml
  .github/workflows/release.yml
  .github/workflows/simple.yml
  .github/workflows/test.yml
Labels: enhancement, automerge, ci

#9331 Fix different dtype in slice_update
  oneflow/core/functional/impl/array_functor.cpp
  python/oneflow/test/modules/test_slice.py
Labels: enhancement, automerge, op

#9322 Fix FlattenOp GetSbp
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/core/job_rewriter/auto_mixed_precision_lists.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/ir/lib/OneFlow/Conversion/OneFlowToTosa.cpp
  oneflow/ir/test/Frontend/OneFlowToIree.mlir
  oneflow/ir/test/OneFlow/conversion/OneFlowToTosa.mlir
  oneflow/user/kernels/copy_data_content_kernel.cpp
  oneflow/user/ops/flatten_op.cpp
Labels: automerge, bug, op

#9335 Refactor ONEFLOW_MLIR_PREFER_NHWC to support more ops
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/ir/include/OneFlow/Transform/TransposeHelpers.h
  oneflow/ir/lib/OneFlow/CMakeLists.txt
  oneflow/ir/lib/OneFlow/OneFlowOps.cpp
  oneflow/ir/lib/OneFlow/Passes.cpp
  oneflow/ir/lib/OneFlow/TransposeHelpers.cpp
Labels: enhancement, automerge, ir

#9332 distributions.Categorical support logits not None
  python/oneflow/distributions/categorical.py
Labels: automerge, bug, op, python

#9328 avoid extra gpu memory usage in flow.save
  python/oneflow/framework/check_point_v2.py
Labels: automerge, bug, python

#9311 Use primitive to replace Ndarray::BroadcastBinary
  oneflow/core/ndarray/ndarray_apply_binary_core.cpp
  oneflow/core/ndarray/ndarray_apply_binary_core.cu
  oneflow/core/ndarray/ndarray_apply_broadcast_binary_core.cpp
  oneflow/core/ndarray/ndarray_apply_broadcast_binary_core.cu
  oneflow/core/ndarray/ndarray_apply_unary_core.cpp
  oneflow/core/ndarray/ndarray_apply_unary_core.cu
  oneflow/user/kernels/binary_cross_entropy_with_logits_kernel.cpp
  oneflow/user/kernels/binary_cross_entropy_with_logits_kernel.cu
  oneflow/user/kernels/broadcast_div_grad_kernel.cpp
  oneflow/user/kernels/two_stage_reduce_kernel.cpp
Labels: enhancement, automerge, op

#9336 Block forward support modification
  python/oneflow/nn/graph/block.py
  python/oneflow/test/graph/test_modify_module_forward.py
Labels: enhancement, automerge, graph

#9333 Add log sum exp api
  docs/source/oneflow.rst
  docs/source/tensor.rst
  oneflow/api/python/framework/tensor_functions.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/math_functor.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/reduce_ops.py
  python/oneflow/framework/docstr/tensor.py
  python/oneflow/test/modules/test_logsumexp.py
Labels: enhancement, automerge, system
