Repository Oneflow-Inc/oneflow, pull requests merged in 2022-01, with the labels that each got.

#7050 Cumsum op implementation
  docs/source/oneflow.rst
  oneflow/core/autograd/gradient_funcs/cumsum.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/user/kernels/cumsum_kernel.cpp
  oneflow/user/kernels/cumsum_kernel.cu
  oneflow/user/ops/cumsum_op.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/math_ops.py
  python/oneflow/test/modules/test_cumsum.py
Labels: enhancement, feature, automerge, op

#7116 Logical slice in tenosr str
  docs/source/oneflow.rst
  oneflow/user/kernels/slice_kernel.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/tensor.py
  python/oneflow/framework/tensor_str.py
  python/oneflow/framework/tensor_str_util.py
  python/oneflow/nn/modules/slice.py
  python/oneflow/test/modules/test_tensor_str.py
Labels: enhancement, automerge, system

#7107 Add install for oneflow py
  CMakeLists.txt
  cmake/cfg.cmake
  cmake/oneflow.cmake
  cmake/third_party.cmake
  cmake/third_party/absl.cmake
  cmake/third_party/eigen.cmake
  cmake/third_party/flatbuffers.cmake
  cmake/third_party/gflags.cmake
  cmake/third_party/glog.cmake
  cmake/third_party/googletest.cmake
  cmake/third_party/grpc.cmake
  cmake/third_party/oneDNN.cmake
  cmake/third_party/opencv.cmake
  cmake/third_party/protobuf.cmake
  cmake/third_party/re2.cmake
  cmake/third_party/zlib.cmake
  oneflow/ir/install-llvm.cmake
Labels: enhancement, automerge, build, python

#7139 fix bug: output key not exists when SavaJobToIR
  oneflow/ir/oneflow-translate/lib/OneFlow/Importer.cpp
  oneflow/ir/test/OneFlow/test_graph_save_and_load.py
Labels: automerge, bug, system

#7160 Add linalg 2d norm op for clip_grad
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/sqrt_square_sum_kernel.cpp
  oneflow/user/kernels/sqrt_square_sum_kernel_util.cpp
  oneflow/user/kernels/sqrt_square_sum_kernel_util.cu
  oneflow/user/kernels/sqrt_square_sum_kernel_util.h
  oneflow/user/ops/sqrt_square_sum_op.cpp
  python/oneflow/nn/utils/clip_grad.py
  python/oneflow/test/modules/test_sqrt_square_sum.py
  python/oneflow/test_utils/automated_test_util/generators.py
Labels: enhancement, automerge, bug, eager, api

#7111 refine nn.graph autotest
  python/oneflow/framework/tensor_str.py
  python/oneflow/test/modules/test_tensor_str.py
  python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py
Labels: enhancement, automerge, eager, test, graph

#7172 add oneflow/pytorch cudnn.deterministic
  python/oneflow/test/modules/test_adaptive_pool.py
  python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py
Labels: enhancement, feature, automerge, bug, eager, api

#7178 fix linalg vector norm scalar tensor print bug
  oneflow/user/ops/sqrt_square_sum_op.cpp
  python/oneflow/nn/utils/clip_grad.py
  python/oneflow/test/modules/test_sqrt_square_sum.py
Labels: enhancement, automerge, bug, ci, eager, op, api, interface

#7175 use op schema for cumsum
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/cumsum_kernel.cpp
  oneflow/user/kernels/cumsum_kernel.cu
  oneflow/user/ops/cumsum_op.cpp
Labels: enhancement, feature, automerge, op

#7184 fix get_sbp for scalar math ops
  oneflow/user/ops/scalar_by_tensor_op.cpp
Labels: automerge, bug, op, system

#7179 Add swapaxes op
  docs/source/oneflow.rst
  docs/source/tensor.rst
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/math_functor.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/__init__.py
  python/oneflow/framework/docstr/swapaxes.py
  python/oneflow/framework/docstr/tensor.py
  python/oneflow/framework/tensor.py
  python/oneflow/test/modules/test_swapaxes.py
  python/oneflow/test/tensor/test_tensor.py
Labels: automerge, op, documentation

#7191 fix install cuda include
  cmake/third_party.cmake
Labels: automerge, bug, build

#7123 Support uneven split in eager slice boxing
  oneflow/core/boxing/asymmetric_broadcast.cpp
  oneflow/core/boxing/asymmetric_x_to_b.cpp
  oneflow/core/boxing/ccl_boxing_function.cpp
  oneflow/core/boxing/cuda_copy_boxing_interpreter.cpp
  oneflow/core/boxing/eager_boxing_interpreter.cpp
  oneflow/core/boxing/eager_boxing_interpreter.h
  oneflow/core/boxing/eager_boxing_interpreter_mgr.cpp
  oneflow/core/boxing/eager_boxing_interpreter_mgr.h
  oneflow/core/boxing/flatten_hierarchy.cpp
  oneflow/core/boxing/identity_boxing_interpreter.cpp
  oneflow/core/boxing/naive_1_to_p_boxing.cpp
  oneflow/core/boxing/naive_b_to_1_boxing.cpp
  oneflow/core/boxing/naive_b_to_s_boxing.cpp
  oneflow/core/boxing/naive_p_to_b_boxing.cpp
  oneflow/core/boxing/naive_p_to_s_boxing.cpp
  oneflow/core/boxing/naive_s_to_b_boxing.cpp
  oneflow/core/boxing/naive_s_to_s_boxing.cpp
  oneflow/core/boxing/nccl_boxing_function.cpp
  oneflow/core/boxing/one_to_one_boxing.cpp
  oneflow/core/boxing/symmetric_b_to_p_boxing.cpp
  oneflow/core/boxing/symmetric_b_to_s_boxing.cpp
  oneflow/core/boxing/symmetric_nd_sbp_boxing.cpp
  oneflow/core/boxing/symmetric_s_to_p_boxing.cpp
  oneflow/core/boxing/symmetric_x_to_b.cpp
  oneflow/core/boxing/unflatten_hierarchy.cpp
  oneflow/core/framework/op_interpreter/eager_consistent_op_interpreter.cpp
  oneflow/user/kernels/eager_b_to_s_kernel.cpp
  oneflow/user/kernels/eager_p_to_s_kernel.cpp
  oneflow/user/kernels/eager_s_to_b_kernel.cpp
  oneflow/user/kernels/eager_s_to_s_kernel.cpp
  oneflow/user/ops/eager_b_to_s_op.cpp
  oneflow/user/ops/eager_p_to_s_op.cpp
  oneflow/user/ops/eager_s_to_s_op.cpp
  python/oneflow/compatible/single_client/framework/balanced_splitter.py
  python/oneflow/framework/balanced_splitter.py
  python/oneflow/test/modules/test_eager_boxing.py
Labels: enhancement, automerge, system, need-clean-ccache

#7152 Add stack kernel
  oneflow/core/autograd/gradient_funcs/stack.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/stack_kernel.cpp
  oneflow/user/ops/concat_op.cpp
  oneflow/user/ops/stack_op.cpp
  python/oneflow/test/modules/test_stack.py
Labels: enhancement, automerge, op

#7163 Add erfinv op
  docs/source/oneflow.rst
  docs/source/tensor.rst
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/erfinv_kernel.cpp
  oneflow/user/kernels/erfinv_kernel.cu
  oneflow/user/ops/erfinv_op.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/__init__.py
  python/oneflow/framework/docstr/erfinv.py
  python/oneflow/framework/docstr/tensor.py
  python/oneflow/framework/tensor.py
  python/oneflow/test/modules/test_erfinv.py
  python/oneflow/test/tensor/test_tensor.py
Labels: enhancement, automerge, op

#7193 add doc for pybind type
  oneflow/api/python/framework/doc.cpp
Labels: enhancement, automerge, documentation, system

#7185 fix linspace bug
  python/oneflow/nn/modules/linspace.py
  python/oneflow/test/modules/test_adaptive_pool.py
  python/oneflow/test/modules/test_linspace.py
Labels: enhancement, automerge, bug, eager, api

#7187 Add floor inplace version
  docs/source/oneflow.rst
  docs/source/tensor.rst
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/unary_functor.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/math_ops.py
  python/oneflow/framework/docstr/tensor.py
  python/oneflow/framework/tensor.py
  python/oneflow/test/modules/test_floor.py
Labels: enhancement, automerge, eager, documentation, api

#7190 remove is_lazy check in nn.Graph inplace output
  oneflow/core/framework/op_interpreter/lazy_op_interpreter.cpp
Labels: automerge, bug, graph

#7194 Fix test case about eye
  python/oneflow/test/modules/test_eye.py
Labels: automerge, bug, op

#7195 Fix consistent narrow gradient bug
  oneflow/core/autograd/gradient_funcs/narrow.cpp
Labels: automerge, bug, eager

#6977 Fused kernel with broadcast
  oneflow/user/kernels/fused_scale_mask_softmax.cu
  oneflow/user/kernels/fused_scale_mask_softmax.cuh
  oneflow/user/kernels/fused_scale_mask_softmax_dropout.cu
  oneflow/user/ops/fused_scale_mask_softmax_dropout_op.cpp
  oneflow/user/ops/fused_scale_mask_softmax_op.cpp
  python/oneflow/test/modules/test_fused_scale_mask_softmax.py
  python/oneflow/test/modules/test_fused_scale_mask_softmax_dropout.py
Labels: enhancement, automerge, op, api

#7186 skip drop if drop rate is zero
  oneflow/core/functional/impl/nn_functor.cpp
Labels: enhancement, automerge, system

#7182 Dev inplace clamp
  docs/source/tensor.rst
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/math_functor.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/__init__.py
  python/oneflow/framework/docstr/clamp.py
  python/oneflow/framework/docstr/math_ops.py
  python/oneflow/framework/docstr/tensor.py
  python/oneflow/framework/tensor.py
  python/oneflow/nn/modules/math_ops.py
  python/oneflow/test/modules/test_adaptive_pool.py
  python/oneflow/test/tensor/test_tensor.py
Labels: enhancement, automerge, eager, op

#7207 Revert "Fused kernel with broadcast (#6977)"
  oneflow/user/kernels/fused_scale_mask_softmax.cu
  oneflow/user/kernels/fused_scale_mask_softmax.cuh
  oneflow/user/kernels/fused_scale_mask_softmax_dropout.cu
  oneflow/user/ops/fused_scale_mask_softmax_dropout_op.cpp
  oneflow/user/ops/fused_scale_mask_softmax_op.cpp
  python/oneflow/test/modules/test_fused_scale_mask_softmax.py
  python/oneflow/test/modules/test_fused_scale_mask_softmax_dropout.py
Labels: bottleneck, automerge, bug, eager

#7142 [BUG] Fixed graph autotest bug with sub op
  oneflow/core/job/intra_job_mem_sharing_util.cpp
  python/oneflow/test/modules/test_randperm.py
  python/oneflow/test/modules/test_sub.py
Labels: enhancement, system

#7024 var kernel
  oneflow/core/autograd/gradient_funcs/variance.cpp
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/user/kernels/variance_kernel.cpp
  oneflow/user/kernels/variance_kernel_util.cpp
  oneflow/user/kernels/variance_kernel_util.cu
  oneflow/user/kernels/variance_kernel_util.h
  oneflow/user/ops/variance_op.cpp
  python/oneflow/comm/comm_ops.py
  python/oneflow/nn/modules/normalization.py
  python/oneflow/test/modules/test_var.py
  python/oneflow/test/tensor/test_tensor.py
Labels: enhancement, automerge, system

#7202 update readme 0.6.0
  README.md
  tools/generate_pip_version.py
Labels: automerge, documentation, system

#7197 Fix check graph bug part1
  python/oneflow/test/modules/test_constant.py
  python/oneflow/test/modules/test_eye.py
  python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py
Labels: enhancement, feature, automerge, bug, eager, graph

#7181 Add documentation file for nn.init.xxxx
  docs/source/index.rst
  docs/source/nn.init.rst
  docs/source/nn.rst
Labels: automerge, op, documentation

#7209 flow._C.stream_touch
  oneflow/core/common/container_util.h
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/framework/instructions_builder.h
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/comm_functor.cpp
  oneflow/core/vm/consume_local_dep_object_phy_instr_operand.cpp
  oneflow/core/vm/consume_local_dep_object_phy_instr_operand.h
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/eager_nccl_kernels.cpp
  oneflow/user/kernels/eager_nccl_kernels.cu
  oneflow/user/ops/eager_nccl_ops.cpp
  python/oneflow/nn/parallel/ddp.py
Labels: enhancement, automerge, system

#7097 Refactor to numpy
  oneflow/api/python/framework/tensor.cpp
  oneflow/api/python/utils/tensor_utils.h
  oneflow/extension/python/numpy.cpp
  oneflow/extension/python/numpy_internal.h
  python/oneflow/framework/docstr/tensor.py
  python/oneflow/framework/tensor.py
  python/oneflow/test/graph/test_graph_optim_adagrad.py
  python/oneflow/test/graph/test_graph_optim_adam.py
  python/oneflow/test/graph/test_graph_optim_adamw.py
  python/oneflow/test/graph/test_graph_optim_rmsprop.py
  python/oneflow/test/graph/test_graph_optim_sgd.py
Labels: enhancement, automerge, system

#7196 Fix eager boxing bug
  oneflow/core/boxing/asymmetric_x_to_b.cpp
  oneflow/core/boxing/eager_boxing_interpreter.cpp
  oneflow/core/boxing/eager_boxing_interpreter.h
  oneflow/core/boxing/eager_boxing_interpreter_mgr.cpp
  oneflow/core/boxing/symmetric_x_to_b.cpp
  oneflow/core/framework/consistency_check.cpp
  oneflow/core/framework/op_interpreter/eager_consistent_op_interpreter.cpp
  oneflow/user/kernels/eager_b_to_s_kernel.cpp
  oneflow/user/kernels/eager_p_to_s_kernel.cpp
  oneflow/user/kernels/eager_s_to_s_kernel.cpp
Labels: automerge, bug, eager, system

#7143 Feat eager consistent 2d sbp infer
  oneflow/core/framework/consistent_tensor_infer_cache.cpp
  oneflow/core/framework/sbp_infer_util.cpp
  oneflow/core/framework/sbp_infer_util.h
  oneflow/core/job/sbp_parallel.cpp
  oneflow/core/job/sbp_parallel.h
  oneflow/core/operator/operator.cpp
  oneflow/core/operator/operator.h
Labels: feature, automerge, eager

#7222 fix split default arg
  python/oneflow/framework/tensor.py
Labels: automerge, bug, eager, op

#7220 fix no grad inplace clamp
  oneflow/core/functional/impl/math_functor.cpp
  python/oneflow/test/tensor/test_tensor.py
Labels: automerge, bug, eager, op

#7223 Fix readthedocs auto update
  docs/requirements.txt
Labels: automerge, bug, ci

#7227 Fix interpolate Docs
  python/oneflow/nn/modules/interpolate.py
Labels: automerge, eager, documentation

#7231 Allow file schema in mirror third party
  cmake/util.cmake
Labels: enhancement, automerge, ci, build

#7210 support_symmetric_cyclic_nd_sbp_boxing
  oneflow/core/boxing/boxing_dividor_util.cpp
  oneflow/core/boxing/boxing_dividor_util.h
  oneflow/core/boxing/eager_boxing_interpreter_mgr.cpp
  oneflow/core/boxing/symmetric_acyclic_nd_sbp_boxing.cpp
  oneflow/core/framework/consistency_check.cpp
  oneflow/core/framework/placement_sbp_util.cpp
  oneflow/core/framework/placement_sbp_util.h
  oneflow/core/framework/tensor_rpc_util.cpp
Labels: enhancement, automerge, system, need-clean-ccache

#7217 Fix erfinv and swapaxes
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/user/kernels/erfinv_kernel.cpp
  python/oneflow/test/modules/test_erfinv.py
Labels: automerge, bug, op

#7230 Support nd sbp dim reduce
  oneflow/core/boxing/eager_boxing_interpreter_mgr.cpp
  oneflow/core/boxing/nd_sbp_dim_reduce_boxing.cpp
  python/oneflow/test/modules/test_eager_boxing.py
Labels: enhancement, automerge, system

#7021 fix comm test cases
  python/oneflow/comm/comm_ops.py
  python/oneflow/test/modules/test_comm_ops.py
Labels: enhancement, automerge, op, test

#7224 fix_backward_bug_in_1d_to_2d_boxing
  oneflow/core/functional/impl/consistent_cast.cpp
Labels: automerge, bug, system, need-clean-ccache

#7243 Skip layernorm warp test
  python/oneflow/test/modules/test_layernorm.py
Labels: automerge, bug, ci

#7228 Print warning for non localhost proxy
  python/oneflow/framework/env_util.py
Labels: enhancement, automerge, python

#7232 add ddp return type
  python/oneflow/nn/parallel/ddp.py
Labels: enhancement, automerge, eager, python

#7161 Auto parallel/support 2d sbp combination
  oneflow/core/auto_parallel/boxing_collector.cpp
  oneflow/core/auto_parallel/boxing_collector.h
  oneflow/core/auto_parallel/sbp_constructor.cpp
  oneflow/core/auto_parallel/sbp_util.cpp
  oneflow/core/auto_parallel/sbp_util.h
  oneflow/core/job/sbp_parallel.cpp
  oneflow/core/job/sbp_parallel.h
  oneflow/core/job_rewriter/boxing_with_middle_nodes.cpp
  oneflow/core/job_rewriter/boxing_with_middle_nodes.h
  oneflow/core/job_rewriter/job_completer.cpp
  oneflow/core/operator/operator.cpp
  python/oneflow/test/modules/test_sbp_comb.py
Labels: AutoParallel

#7249 Parameter support both inplace op and setter
  oneflow/core/framework/tensor.h
  python/oneflow/test/tensor/test_parameter.py
Labels: feature, automerge, eager

#7240 fix docs error
  python/oneflow/utils/data/_utils/collate.py
  python/oneflow/utils/data/_utils/signal_handling.py
  python/oneflow/utils/data/dataloader.py
Labels: automerge, documentation, api, python

#7150 Eager boxing status
  oneflow/core/boxing/boxing_interpreter_status.cpp
  oneflow/core/boxing/boxing_interpreter_status.h
  oneflow/core/boxing/eager_boxing_interpreter.cpp
  oneflow/core/boxing/eager_boxing_interpreter.h
  oneflow/core/boxing/eager_boxing_interpreter_mgr.cpp
  oneflow/core/boxing/eager_boxing_logger.cpp
  oneflow/core/boxing/eager_boxing_logger.h
  oneflow/core/boxing/nd_sbp_dim_reduce_boxing.cpp
  oneflow/core/boxing/symmetric_acyclic_nd_sbp_boxing.cpp
  oneflow/core/framework/op_interpreter/eager_consistent_op_interpreter.cpp
Labels: enhancement, automerge, eager, system

#7239 fix empty bug
  oneflow/core/common/data_type.cpp
  oneflow/user/kernels/empty_kernel.cpp
Labels: enhancement, automerge, bug, op

#7245 fix empty debug str of hob primitive
  oneflow/core/common/high_order_bool.h
Labels: automerge, bug, system

#7233 Add VSCode dev container
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  cmake/caches/cn/fast/cpu-clang.cmake
  cmake/caches/cn/fast/cpu.cmake
  cmake/caches/cn/fast/cuda-61-clang.cmake
  cmake/caches/cn/fast/cuda-61.cmake
  cmake/caches/cn/fast/cuda-75-clang.cmake
  cmake/caches/cn/fast/cuda-75.cmake
  cmake/caches/cn/fast/mlir-cuda-61.cmake
  cmake/caches/cn/fast/mlir-cuda-75.cmake
Labels: feature, automerge, build

#7255 Skip send and recv if dst and src are same.
  oneflow/core/boxing/one_to_one_boxing.cpp
Labels: enhancement, automerge, eager, system

#7214 Maxpool op nhwc
  oneflow/user/kernels/pooling_kernel.cpp
  oneflow/user/kernels/pooling_kernel.cu
  oneflow/user/kernels/pooling_kernel_util.h
  python/oneflow/nn/modules/pooling.py
  python/oneflow/test/modules/test_maxpool.py
Labels: enhancement, automerge, eager, op, interface

#7265 Implement consistent tensor detach
  oneflow/core/framework/tensor.cpp
  oneflow/core/framework/tensor_impl.cpp
  oneflow/core/framework/tensor_impl.h
Labels: enhancement, automerge, bug, system

#7165 Feat/zero optimization in nn.Graph
  oneflow/core/framework/nn_graph.cpp
  oneflow/core/framework/nn_graph.h
  oneflow/core/job/oneflow.cpp
  oneflow/core/job/plan_util.cpp
  oneflow/core/job_rewriter/optimizer_placement_optimization_pass.cpp
  oneflow/core/operator/operator.cpp
  python/oneflow/nn/graph/graph_config.py
  python/oneflow/test/graph/test_graph_linear_train.py
  python/oneflow/test/graph/test_graph_zero.py
  python/oneflow/test/graph/test_optimization_conf.py
Labels: feature, automerge, system, graph

#7236 fix linspace limit bug
  python/oneflow/framework/docstr/tensor.py
  python/oneflow/nn/modules/constant.py
  python/oneflow/nn/modules/linspace.py
  python/oneflow/test/modules/test_linspace.py
Labels: enhancement, feature, automerge, bug, eager, documentation, api

#7121 replace throw by OF_UNIMPLEMENTED or UNIMPLEMENTED, refine error message, replace CHECK by CHECK_OR_RETURN
  oneflow/user/kernels/dim_scatter_kernel_util.h
  oneflow/user/kernels/dim_scatter_kernels.cpp
  oneflow/user/kernels/dim_scatter_scalar_kernel_util.h
  oneflow/user/kernels/dim_scatter_scalar_kernels.cpp
  oneflow/user/ops/dim_scatter_ops.cpp
  oneflow/user/ops/mish_op.cpp
  oneflow/user/ops/roi_align_op.cpp
  oneflow/user/ops/selu_op.cpp
  oneflow/user/ops/silu_op.cpp
  oneflow/user/ops/softsign_op.cpp
Labels: enhancement, automerge, op

#7274 Remove single client from CI
  .github/workflows/canary.yml
  .github/workflows/release.yml
  .github/workflows/simple.yml
  .github/workflows/test.yml
  CHANGELOG.md
Labels: enhancement, automerge, ci

#7254 Feat/eager tensor to graph out and inplace
  oneflow/core/framework/op_interpreter/lazy_op_interpreter.cpp
  python/oneflow/framework/graph_build_util.py
  python/oneflow/test/graph/test_graph_free_eager_tensor.py
  python/oneflow/test/modules/test_flatten.py
  python/oneflow/test/tensor/test_parameter.py
  python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py
Labels: feature, automerge, test, system, graph

#6996 Optimize LayerNorm backward param grad
  oneflow/core/autograd/gradient_funcs/layer_norm.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/core/functional/impl/nn_grad_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/layer_norm_gpu_kernel.cu
  oneflow/user/ops/layer_norm_op.cpp
  oneflow/xrt/xla/ops/layer_norm_op.cpp
  python/oneflow/compatible/single_client/ops/layers.py
  python/oneflow/compatible/single_client/ops/nn_ops.py
  python/oneflow/compatible/single_client/test/xrt/test_layer_norm_param_grad.py
Labels: enhancement, automerge, op, need-clean-ccache

#7113 Use normalize instead of l2_normalize
  docs/source/functional.rst
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  python/oneflow/framework/docstr/norm.py
  python/oneflow/nn/functional/__init__.py
  python/oneflow/test/modules/test_normalize.py
Labels: enhancement, automerge, op

#7203 add_eager_naive_s_to_p_boxing
  oneflow/core/boxing/eager_boxing_interpreter_mgr.cpp
  oneflow/core/boxing/naive_s_to_p_boxing.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/slice_boxing_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/eager_s_to_p_kernel.cpp
  oneflow/user/ops/eager_s_to_p_op.cpp
  python/oneflow/test/modules/test_eager_boxing.py
Labels: enhancement, automerge, system, need-clean-ccache

#7286 add timeout for distributed run
  .github/workflows/test.yml
  oneflow/core/vm/virtual_machine.cpp
Labels: enhancement, automerge, ci

#7176 cmake: import gflags and glog using FetchContent
  .github/workflows/test.yml
  cmake/oneflow.cmake
  cmake/op_schema.cmake
  cmake/pybind11.cmake
  cmake/third_party.cmake
  cmake/third_party/gflags-config.cmake
  cmake/third_party/gflags.cmake
  cmake/third_party/glog.cmake
  oneflow/core/common/util.h
  oneflow/ir/CMakeLists.txt
  oneflow/xrt/api.cpp
  oneflow/xrt/launch_kernel.cpp
  tools/oneflow-tblgen/CMakeLists.txt
Labels: enhancement, automerge, build

#7257 Prune parallel dim with val eq one in parallel dim reduce
  oneflow/core/graph/boxing/hierarchical_sub_task_graph_builder_impl.cpp
Labels: enhancement, automerge, system

#7294 Dirty workaround for forked process testing
  python/oneflow/test/modules/test_fork_sub_process.py
Labels: automerge, bug, ci

#7260 add polynomial scheduler
  docs/source/optim.rst
  python/oneflow/nn/optimizer/polynomial_lr.py
  python/oneflow/optim/lr_scheduler.py
  python/oneflow/test/graph/test_graph_lrs.py
  python/oneflow/test/modules/test_lr_scheduler.py
Labels: feature, automerge, python

#7276 Fix autotest inplace bug, hardsigmod
  docs/source/oneflow.rst
  python/oneflow/__init__.py
  python/oneflow/nn/modules/is_tensor.py
  python/oneflow/test/modules/test_activation.py
  python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py
Labels: bug, op, graph

#6612 Use flowvision replace flow.utils.vision
  dev-requirements.txt
  docs/source/utils.rst
  python/oneflow/__init__.py
  python/oneflow/test/dataloader/data_utils.py
  python/oneflow/test/dataloader/test_cifar_dataset_multiprocess.py
  python/oneflow/test/dataloader/test_cifar_dataset_singleprocess.py
  python/oneflow/test/dataloader/test_mnist_dataset.py
  python/oneflow/test/dataloader/test_transforms.py
  python/oneflow/utils/vision/__init__.py
  python/oneflow/utils/vision/datasets/__init__.py
  python/oneflow/utils/vision/datasets/cifar.py
  python/oneflow/utils/vision/datasets/coco.py
  python/oneflow/utils/vision/datasets/folder.py
  python/oneflow/utils/vision/datasets/imagenet.py
  python/oneflow/utils/vision/datasets/mnist.py
  python/oneflow/utils/vision/datasets/utils.py
  python/oneflow/utils/vision/datasets/vision.py
  python/oneflow/utils/vision/datasets/voc.py
  python/oneflow/utils/vision/requirement.txt
  python/oneflow/utils/vision/transforms/__init__.py
  python/oneflow/utils/vision/transforms/functional.py
  python/oneflow/utils/vision/transforms/functional_pil.py
  python/oneflow/utils/vision/transforms/functional_tensor.py
  python/oneflow/utils/vision/transforms/transforms.py
  python/setup.py
Labels: feature, automerge, eager, interface

#7304 align clip grad with torch in error_if_nonfinite
  python/oneflow/nn/utils/clip_grad.py
Labels: enhancement, feature, automerge, bug, eager, api

#7269 Add_Tensor.T_and_Tensor.t()_ops
  docs/source/oneflow.rst
  docs/source/tensor.rst
  oneflow/api/python/framework/doc.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/array_functor.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/__init__.py
  python/oneflow/framework/docstr/tensor.py
  python/oneflow/framework/docstr/tensor_t.py
  python/oneflow/framework/tensor.py
  python/oneflow/test/modules/test_t.py
  python/oneflow/test/tensor/test_tensor.py
Labels: enhancement, automerge, eager, op

#7071 Refactor release tensor
  ci/test/test_speed_multi_client.sh
  oneflow/core/eager/blob_instruction_type.cpp
  oneflow/core/eager/release_tensor_arg_phy_instr_operand.h
  oneflow/core/eager/release_tensor_instruction_type.cpp
  oneflow/core/eager/release_tensor_instruction_type.h
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/framework/tensor_impl.cpp
Labels: enhancement, system

#7237 Fix functional dropout and Docs
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  python/oneflow/framework/docstr/dropout.py
  python/oneflow/nn/modules/dropout.py
  python/oneflow/test/modules/test_generator.py
Labels: automerge, eager, op, documentation

#7208 Modify graph and 0-D Tensor
  oneflow/core/common/shape.cpp
  oneflow/core/common/shape.h
  oneflow/core/common/shape_view.cpp
  oneflow/user/ops/flatten_op.cpp
  oneflow/user/ops/slice_op.cpp
  oneflow/user/ops/unfold_tensor_op.cpp
  python/oneflow/test/modules/test_abs.py
  python/oneflow/test/modules/test_activation.py
  python/oneflow/test/modules/test_adaptive_pool.py
  python/oneflow/test/modules/test_add.py
  python/oneflow/test/modules/test_argmin.py
  python/oneflow/test/modules/test_argsort.py
  python/oneflow/test/modules/test_autograd.py
  python/oneflow/test/modules/test_avgpool.py
  python/oneflow/test/modules/test_ceil.py
  python/oneflow/test/modules/test_clamp.py
  python/oneflow/test/modules/test_constant.py
  python/oneflow/test/modules/test_div.py
  python/oneflow/test/modules/test_dropout.py
  python/oneflow/test/modules/test_eq.py
  python/oneflow/test/modules/test_erf.py
  python/oneflow/test/modules/test_erfc.py
  python/oneflow/test/modules/test_expm1.py
  python/oneflow/test/modules/test_eye.py
  python/oneflow/test/modules/test_flatten.py
  python/oneflow/test/modules/test_flip.py
  python/oneflow/test/modules/test_floor.py
  python/oneflow/test/modules/test_fmod.py
  python/oneflow/test/modules/test_glu.py
  python/oneflow/test/modules/test_greater.py
  python/oneflow/test/modules/test_less.py
  python/oneflow/test/modules/test_log1p.py
  python/oneflow/test/modules/test_masked_fill.py
  python/oneflow/test/modules/test_meshgrid.py
  python/oneflow/test/modules/test_ne.py
  python/oneflow/test/modules/test_negative.py
  python/oneflow/test/modules/test_nonzero.py
  python/oneflow/test/modules/test_permute.py
  python/oneflow/test/modules/test_reciprocal.py
  python/oneflow/test/modules/test_repeat.py
  python/oneflow/test/modules/test_reshape.py
  python/oneflow/test/modules/test_round.py
  python/oneflow/test/modules/test_scatter_ops.py
  python/oneflow/test/modules/test_sign.py
  python/oneflow/test/modules/test_split.py
  python/oneflow/test/modules/test_sub.py
  python/oneflow/test/modules/test_sum.py
  python/oneflow/test/modules/test_tensor_ops.py
  python/oneflow/test/modules/test_tile.py
  python/oneflow/test/modules/test_transpose.py
  python/oneflow/test/modules/test_unfold_tensor.py
  python/oneflow/test/modules/test_var.py
  python/oneflow/test/modules/test_where.py
  python/oneflow/test_utils/automated_test_util/generators.py
Labels: automerge, bug, test, graph

#7271 Refactor OneRecReader to stateful op and provide Module api
  docs/source/oneflow.rst
  oneflow/api/python/functional/dispatch_stateful_ops.cpp
  oneflow/api/python/functional/dispatch_stateful_ops.yaml
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/dataset_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/data/coco_data_reader.cpp
  oneflow/user/data/distributed_util.h
  oneflow/user/data/onerec_dataset.h
  oneflow/user/kernels/gpt_data_loader_kernel.cpp
  oneflow/user/ops/onerec_reader_op.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/dataset.py
  python/oneflow/nn/__init__.py
  python/oneflow/nn/modules/dataset.py
  python/oneflow/test/modules/test_one_rec_ops.py
Labels: automerge, bug, op

#7318 [bug] Adam align torch params
  python/oneflow/compatible/single_client/nn/optimizer/adam.py
  python/oneflow/nn/optimizer/adam.py
Labels: automerge, bug, op, documentation

#7253 add channel-last to resnet50 graph ci test
  .github/workflows/test.yml
  ci/test/test_resnet50_graph_ddp.sh
Labels: enhancement, ci, graph

#7213 Add oneTBB
  .github/workflows/test.yml
  CMakeLists.txt
  cmake/oneflow.cmake
  cmake/third_party/oneDNN.cmake
  cmake/util.cmake
  external/CMakeLists.txt
  external/onetbb/CMakeLists.txt
Labels: enhancement, system, need-clean-ccache

#7331 Fix leaf tensor backward error
  oneflow/api/python/autograd/autograd.cpp
  python/oneflow/test/modules/test_autograd.py
Labels: feature, automerge, eager

#7315 Create tensor in jobpass after pulling plan
  oneflow/core/framework/nn_graph.cpp
  oneflow/core/framework/nn_graph.h
  oneflow/core/job/sbp_parallel.cpp
  oneflow/user/ops/adaptive_pool_op.cpp
Labels: automerge, bug, graph

#7333 Use cudnn maxpool when possible
  oneflow/core/autograd/gradient_funcs/pool.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/core/functional/impl/nn_grad_functor.cpp
  oneflow/user/kernels/pooling_kernel.cu
  python/oneflow/nn/modules/pooling.py
Labels: enhancement, automerge, eager, op, api

#7306 Remove `register_tensor_op` decorator and use `add_docstr`[part]
  docs/source/oneflow.rst
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/comparison.py
  python/oneflow/framework/docstr/tensor.py
  python/oneflow/framework/tensor.py
  python/oneflow/nn/modules/argwhere.py
  python/oneflow/nn/modules/comparison.py
  python/oneflow/nn/modules/consistent_cast.py
Labels: automerge, op, documentation

#7341 disable nccl release_tensor sequential
  oneflow/core/framework/instructions_builder.cpp
Labels: enhancement, automerge, system

#7131 Rm local dep object pool
  oneflow/api/python/functional/tensor_api.cpp
  oneflow/core/common/container_util.h
  oneflow/core/eager/critical_section_phy_instr_operand.cpp
  oneflow/core/eager/eager_blob_object.cpp
  oneflow/core/eager/eager_blob_object.h
  oneflow/core/eager/lazy_job_phy_instr_operand.cpp
  oneflow/core/eager/local_call_opkernel_phy_instr_operand.cpp
  oneflow/core/eager/local_dep_object.cpp
  oneflow/core/eager/local_dep_object.h
  oneflow/core/eager/release_tensor_arg_phy_instr_operand.h
  oneflow/core/framework/device.cpp
  oneflow/core/framework/device.h
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/framework/instructions_builder.h
  oneflow/core/framework/op_interpreter/eager_mirrored_op_interpreter.cpp
  oneflow/core/framework/tensor_impl.cpp
  oneflow/core/framework/tensor_impl.h
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/comm_functor.cpp
  oneflow/core/vm/access_blob_arg_cb_phy_instr_operand.cpp
  oneflow/core/vm/access_blob_arg_cb_phy_instr_operand.h
  oneflow/core/vm/consume_local_dep_object_phy_instr_operand.cpp
  oneflow/core/vm/consume_local_dep_object_phy_instr_operand.h
  oneflow/core/vm/tensor_view_operand.cpp
  oneflow/core/vm/tensor_view_operand.h
  oneflow/core/vm/virtual_machine_engine.cpp
  oneflow/core/vm/vm_object.cpp
  oneflow/core/vm/vm_object.h
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/eager_nccl_kernels.cpp
  oneflow/user/kernels/eager_nccl_kernels.cu
  oneflow/user/ops/eager_nccl_ops.cpp
  python/oneflow/nn/parallel/ddp.py
Labels: enhancement, automerge, system

#7270 Autotest add graph backward
  python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py
Labels: enhancement, feature, automerge, eager, test, graph

#7278 Cumprod
  docs/source/oneflow.rst
  oneflow/core/autograd/gradient_funcs/cum_ops.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/cum_backward_kernel.cpp
  oneflow/user/kernels/cum_backward_kernel.cu
  oneflow/user/kernels/cum_forward_kernel.cpp
  oneflow/user/kernels/cum_forward_kernel.cu
  oneflow/user/kernels/cumsum_kernel.cpp
  oneflow/user/kernels/cumsum_kernel.cu
  oneflow/user/ops/cum_ops.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/math_ops.py
  python/oneflow/test/modules/test_cum_ops.py
Labels: enhancement, automerge, op

#7287 Release tensor storage as soon as possible
  oneflow/core/eager/eager_blob_object.h
Labels: enhancement, automerge, system, need-clean-ccache

#7204 Dev eager consistent autotest
  oneflow/api/python/symbol/placement_symbol.cpp
  oneflow/api/python/symbol/sbp_symbol.cpp
  oneflow/core/job/parallel_desc.cpp
  python/oneflow/framework/check_point_v2.py
  python/oneflow/framework/docstr/placement.py
  python/oneflow/framework/env_util.py
  python/oneflow/framework/tensor.py
  python/oneflow/test/modules/test_consistent_add.py
  python/oneflow/test/modules/test_consistent_concat.py
  python/oneflow/test/modules/test_consistent_linear.py
  python/oneflow/test/modules/test_eager_boxing.py
  python/oneflow/test_utils/automated_test_util/consistent_scope.py
  python/oneflow/test_utils/automated_test_util/generators.py
  python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py
  python/oneflow/test_utils/automated_test_util/util.py
Labels: enhancement, automerge, eager, test

#7292 cmake: import gtest using FetchContent
  cmake/oneflow.cmake
  cmake/third_party.cmake
  cmake/third_party/glog.cmake
  cmake/third_party/googletest.cmake
  cmake/third_party/header_index/gmock_headers.txt
  cmake/third_party/header_index/gtest_headers.txt
  oneflow/core/common/balanced_splitter_test.cpp
  oneflow/core/common/cfg_reflection_test.cpp
  oneflow/core/common/channel_test.cpp
  oneflow/core/common/cpp_attribute.h
  oneflow/core/common/data_type.h
  oneflow/core/common/data_type_converter_test.cpp
  oneflow/core/common/decorator_test.cpp
  oneflow/core/common/maybe_test.cpp
  oneflow/core/common/nd_index_offset_helper_test.cpp
  oneflow/core/common/single_thread_obj_pool_test.cpp
  oneflow/core/common/symbol_test.cpp
  oneflow/core/common/util.h
  oneflow/core/control/ctrl_test.cpp
  oneflow/core/eager/init_symbol_instruction_type_test.cpp
  oneflow/core/eager/opkernel_instruction_type_test.cpp
  oneflow/core/framework/attr_map_test.cpp
  oneflow/core/framework/interpreter_test.cpp
  oneflow/core/framework/parallel_conf_util_test.cpp
  oneflow/core/framework/placement_sbp_util_test.cpp
  oneflow/core/intrusive/channel_test.cpp
  oneflow/core/intrusive/cpp_attribute.h
  oneflow/core/intrusive/dss_test.cpp
  oneflow/core/intrusive/flat_msg_test.cpp
  oneflow/core/intrusive/flat_msg_view_test.cpp
  oneflow/core/intrusive/force_standard_layout_test.cpp
  oneflow/core/intrusive/head_free_list_test.cpp
  oneflow/core/intrusive/intrusive_core_test.cpp
  oneflow/core/intrusive/list_hook_test.cpp
  oneflow/core/intrusive/list_test.cpp
  oneflow/core/intrusive/object_pool_test.cpp
  oneflow/core/intrusive/skiplist_hook_test.cpp
  oneflow/core/intrusive/skiplist_test.cpp
  oneflow/core/intrusive/static_counter_test.cpp
  oneflow/core/intrusive/struct_traits_test.cpp
  oneflow/core/job/eager_nccl_comm_manager.cpp
  oneflow/core/job/id_manager_test.cpp
  oneflow/core/job/parallel_desc_test.cpp
  oneflow/core/job/rank_group_scope_test.cpp
  oneflow/core/job/rank_group_test.cpp
  oneflow/core/vm/control_stream_type_test.cpp
  oneflow/core/vm/cuda_allocator_test.cpp
  oneflow/core/vm/instruction_test.cpp
  oneflow/core/vm/object_instruction_type_test.cpp
  oneflow/core/vm/phy_instr_operand.h
  oneflow/core/vm/sequential_instruction_type_test.cpp
  oneflow/core/vm/stream_type_id_test.cpp
  oneflow/core/vm/string_instruction_type_test.cpp
  oneflow/core/vm/virtual_machine_engine_test.cpp
Labels: enhancement, automerge, build

#7353 skip test cumprod
  python/oneflow/test/modules/test_cum_ops.py
Labels: automerge, bug, op, test

#7328 make scalar tensor check failed in ccl S2B/P2S/S2S boxing
  oneflow/core/boxing/ccl_boxing_function.cpp
  oneflow/core/boxing/nccl_boxing_function.cpp
  oneflow/user/ops/reshape_user_op_util.cpp
  python/oneflow/test_utils/automated_test_util/generators.py
Labels: enhancement, automerge, eager, system

#7330 Fix tbb cmake error
  CMakeLists.txt
  cmake/third_party/oneDNN.cmake
  external/onetbb/CMakeLists.txt
Labels: enhancement, automerge, bug, build

#7348 do not create a new tensor for inplaced output
  oneflow/core/framework/op_interpreter/eager_consistent_op_interpreter.cpp
  oneflow/core/framework/tensor_impl.h
Labels: enhancement, automerge, eager, system

#7321 document_register_method_change
  docs/source/oneflow.rst
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/__init__.py
  python/oneflow/framework/docstr/consistent_cast.py
  python/oneflow/framework/docstr/constant.py
  python/oneflow/framework/docstr/expand.py
  python/oneflow/framework/docstr/flip.py
  python/oneflow/framework/docstr/in_top_k.py
  python/oneflow/framework/docstr/index_select.py
  python/oneflow/framework/docstr/tensor.py
  python/oneflow/framework/tensor.py
  python/oneflow/nn/modules/consistent_cast.py
  python/oneflow/nn/modules/constant.py
  python/oneflow/nn/modules/expand.py
  python/oneflow/nn/modules/flip.py
  python/oneflow/nn/modules/index_select.py
Labels: automerge, op, documentation

#7351 Optimize Gather CUDA Kernel
  oneflow/user/kernels/gather_kernel_util.cu
Labels: enhancement, automerge, op, need-clean-ccache

#7358 Increase rtol atol for cumprod
  python/oneflow/test/modules/test_cum_ops.py
Labels: automerge, bug, op

#6982 Resolve inefficiency of data reader releasing
  oneflow/core/common/buffer.h
  oneflow/core/common/tensor_buffer.cpp
  oneflow/core/common/tensor_buffer.h
  oneflow/core/common/util.cpp
  oneflow/core/common/util.h
  oneflow/core/job/env_global_objects_scope.cpp
  oneflow/user/data/batch_dataset.h
  oneflow/user/data/batch_random_shuffle_dataset.h
  oneflow/user/data/coco_data_reader.cpp
  oneflow/user/data/coco_data_reader.h
  oneflow/user/data/coco_dataset.cpp
  oneflow/user/data/coco_dataset.h
  oneflow/user/data/coco_parser.cpp
  oneflow/user/data/coco_parser.h
  oneflow/user/data/data_reader.h
  oneflow/user/data/dataset.h
  oneflow/user/data/distributed_training_dataset.h
  oneflow/user/data/group_batch_dataset.h
  oneflow/user/data/ofrecord_data_reader.h
  oneflow/user/data/ofrecord_dataset.h
  oneflow/user/data/ofrecord_image_classification_data_reader.h
  oneflow/user/data/ofrecord_image_classification_dataset.cpp
  oneflow/user/data/ofrecord_image_classification_dataset.h
  oneflow/user/data/ofrecord_image_classification_parser.h
  oneflow/user/data/ofrecord_parser.h
  oneflow/user/data/onerec_data_reader.h
  oneflow/user/data/onerec_dataset.h
  oneflow/user/data/onerec_parser.h
  oneflow/user/data/parser.h
  oneflow/user/data/random_shuffle_dataset.h
Labels: enhancement, automerge, system, need-clean-ccache

#7329 remove register_tensor_op decorator and replace by add_docstr [part]
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/__init__.py
  python/oneflow/framework/docstr/masked_fill.py
  python/oneflow/framework/docstr/tensor.py
  python/oneflow/framework/tensor.py
  python/oneflow/nn/modules/logical_ops.py
  python/oneflow/nn/modules/masked_select.py
  python/oneflow/nn/modules/math_ops.py
Labels: automerge, op, documentation

#7342 Upload speed stats
  .github/workflows/test.yml
  python/oneflow/__init__.py
Labels: enhancement, automerge, ci, need-all-tests-even-fail

#7357 Batchnorm check graph
  python/oneflow/nn/modules/batchnorm.py
  python/oneflow/test/modules/test_batchnorm.py
  python/oneflow/test/modules/test_instancenorm.py
  python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py
Labels: enhancement, automerge, op, graph

#7354 Fix Fold channel last out of bound Bug
  oneflow/user/kernels/fold_kernel_util.h
Labels: enhancement, automerge, bug, op

#7366 Dev ccl kernel support bool
  oneflow/core/device/nccl_util.h
  oneflow/core/job/collective_boxing/nccl_executor_backend.cu
  oneflow/user/kernels/eager_nccl_kernels.cpp
  oneflow/user/kernels/eager_nccl_kernels.cu
  oneflow/user/kernels/nccl_logical_kernels.cpp
  python/oneflow/test/modules/test_consistent_greater.py
Labels: enhancement, automerge, system

#7177 cmake: add auto format & ci: check cmake format
  .cmake-format.py
  .github/workflows/test.yml
  CMakeLists.txt
  ci/check/run_cmake_format.py
  cmake/cfg.cmake
  cmake/functional.cmake
  cmake/git_version.cmake
  cmake/oneflow-config.cmake
  cmake/oneflow.cmake
  cmake/op_schema.cmake
  cmake/proto2cpp.cmake
  cmake/pybind11.cmake
  cmake/python.cmake
  cmake/third_party.cmake
  cmake/third_party/FindBLAS.cmake
  cmake/third_party/FindCUDNN.cmake
  cmake/third_party/absl.cmake
  cmake/third_party/cares.cmake
  cmake/third_party/cocoapi.cmake
  cmake/third_party/cub.cmake
  cmake/third_party/eigen.cmake
  cmake/third_party/flatbuffers.cmake
  cmake/third_party/glog.cmake
  cmake/third_party/googletest.cmake
  cmake/third_party/grpc.cmake
  cmake/third_party/half.cmake
  cmake/third_party/hwloc.cmake
  cmake/third_party/json.cmake
  cmake/third_party/libjpeg-turbo.cmake
  cmake/third_party/lz4.cmake
  cmake/third_party/nccl.cmake
  cmake/third_party/oneDNN.cmake
  cmake/third_party/opencv.cmake
  cmake/third_party/openssl.cmake
  cmake/third_party/openvino.cmake
  cmake/third_party/protobuf.cmake
  cmake/third_party/re2.cmake
  cmake/third_party/tensorflow.cmake
  cmake/third_party/tensorrt.cmake
  cmake/third_party/zlib.cmake
  cmake/util.cmake
  dev-requirements.txt
  oneflow/ir/CMakeLists.txt
  oneflow/ir/include/OneFlow/CMakeLists.txt
  oneflow/ir/install-llvm.cmake
  oneflow/ir/lib/OneFlow/CMakeLists.txt
  oneflow/ir/llvm-in-tree.cmake
  oneflow/ir/oneflow-extension/CMakeLists.txt
  oneflow/ir/oneflow-extension/include/OneFlow/CMakeLists.txt
  oneflow/ir/oneflow-opt/CMakeLists.txt
  oneflow/ir/oneflow-runtime/lib/CMakeLists.txt
  oneflow/ir/oneflow-translate/CMakeLists.txt
  oneflow/ir/oneflow-translate/include/OneFlow/CMakeLists.txt
  oneflow/ir/oneflow-translate/lib/OneFlow/CMakeLists.txt
  oneflow/ir/test/CMakeLists.txt
  tools/oneflow-tblgen/CMakeLists.txt
Labels: enhancement, automerge, build

#7317 skip_release_cuda_tensor_in_fork_process
  oneflow/core/framework/instructions_builder.cpp
Labels: automerge, bug, system

#7371 Revert "Increase rtol atol for cumprod"
  python/oneflow/test/modules/test_cum_ops.py
Labels: automerge, bug, op

#7363 Fix stack backward
  oneflow/core/autograd/gradient_funcs/stack.cpp
  oneflow/core/functional/impl/array_functor.cpp
Labels: automerge, bug, eager, op

#7368 Auto parallel/cost for middle nodes
  oneflow/core/auto_parallel/boxing_collector.cpp
  oneflow/core/auto_parallel/boxing_collector.h
  oneflow/core/auto_parallel/sbp_collector.cpp
  oneflow/core/auto_parallel/sbp_edge.h
  oneflow/core/auto_parallel/sbp_graph.h
  oneflow/core/common/util.cpp
  oneflow/core/common/util.h
  oneflow/core/framework/sbp_infer_util.cpp
  oneflow/core/framework/sbp_infer_util.h
  oneflow/core/job_rewriter/boxing_with_middle_nodes.cpp
  oneflow/core/operator/operator.cpp
Labels: AutoParallel

#7367 remove_from_torch
  python/oneflow/framework/docstr/consistent_cast.py
Labels: feature, automerge, bug, documentation, python

#7238 Fix advance indexing bug and zeros_like sbp bug
  oneflow/core/framework/op_interpreter/eager_consistent_op_interpreter.cpp
  oneflow/core/functional/tensor_index.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/ops/ones_like_op.cpp
  oneflow/user/ops/zero_like_op.cpp
Labels: automerge, bug, eager

#7372 Run exe test on gpu in ci
  .github/workflows/test.yml
Labels: enhancement, ci, build

#7267 Feat/mut resource eagerly
  oneflow/api/python/session/session.cpp
  oneflow/api/python/session/session.h
  oneflow/api/python/session/session_api.h
  oneflow/core/framework/multi_client_session_context.cpp
  oneflow/core/framework/multi_client_session_context.h
  oneflow/core/job/resource_desc.cpp
  oneflow/core/job/resource_desc.h
  python/oneflow/framework/config_util.py
  python/oneflow/framework/multi_client_session.py
  python/oneflow/test/graph/test_optimization_conf.py
Labels: enhancement, feature, automerge, graph

#7275 implement as strided
  docs/source/oneflow.rst
  oneflow/core/autograd/gradient_funcs/as_strided.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/as_strided_kernel.cpp
  oneflow/user/kernels/as_strided_kernel.cu
  oneflow/user/ops/as_strided_op.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/math_ops.py
  python/oneflow/test/modules/test_as_stride.py
Labels: enhancement, automerge, op

#7361 [ddp] allreduce after add_n
  oneflow/api/python/framework/tensor.cpp
  oneflow/api/python/utils/tensor_utils.cpp
  oneflow/api/python/utils/tensor_utils.h
  oneflow/core/autograd/autograd_engine.cpp
  oneflow/core/autograd/autograd_meta.h
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/comm_functor.cpp
  python/oneflow/nn/parallel/ddp.py
  python/oneflow/test/modules/test_ddp.py
  python/oneflow/test/tensor/test_tensor.py
Labels: enhancement, automerge, system

#7345 remove register_tensor_op decorator and replace by add_docstr [part 6]
  docs/source/oneflow.rst
  docs/source/tensor.rst
  python/oneflow/framework/docstr/__init__.py
  python/oneflow/framework/docstr/nms.py
  python/oneflow/framework/docstr/nonzero.py
  python/oneflow/framework/docstr/reduce_ops.py
  python/oneflow/framework/docstr/tensor.py
  python/oneflow/framework/docstr/topk.py
  python/oneflow/framework/tensor.py
  python/oneflow/nn/modules/math_ops.py
  python/oneflow/nn/modules/nms.py
  python/oneflow/nn/modules/nonzero.py
  python/oneflow/nn/modules/reduce_ops.py
Labels: automerge, op, documentation

#7375 check the absolute time of large bs in ci speed test
  ci/test/test_speed_multi_client.sh
Labels: enhancement, automerge, ci

#7378 Feat storage delete hook
  oneflow/api/python/framework/tensor.cpp
  oneflow/core/eager/eager_blob_object.h
  oneflow/core/framework/tensor.h
  oneflow/core/framework/tensor_impl.cpp
  oneflow/core/framework/tensor_impl.h
Labels: feature, eager

#7258 tensorsplit_op
  docs/source/oneflow.rst
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/math_functor.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/math_ops.py
  python/oneflow/test/modules/test_hsplit.py
  python/oneflow/test/modules/test_tensor_split.py
  python/oneflow/test/modules/test_vsplit.py
Labels: enhancement, automerge, op

#7344 optimize consistent timeout message
  .github/workflows/test.yml
  oneflow/api/python/framework/transport_util.cpp
  oneflow/core/framework/sync_symbol_nd_sbp.cpp
  oneflow/core/framework/transport_util.cpp
  oneflow/core/framework/transport_util.h
  oneflow/core/transport/transport.cpp
  python/oneflow/test/exceptions/test_consistent_branch_error.py
  tools/check_src.py
Labels: enhancement, automerge, bug, eager

#7393 upgrade clang-tidy in ci
  .github/workflows/simple.yml
  .github/workflows/test.yml
  ci/check/run_clang_tidy.py
Labels: enhancement, automerge, ci

#7380 remove register_tensor_op decorator and replace by add_docstr [part 7]
  docs/source/oneflow.rst
  python/oneflow/framework/docstr/__init__.py
  python/oneflow/framework/docstr/is_floating_point.py
  python/oneflow/framework/docstr/sort.py
  python/oneflow/framework/docstr/tensor.py
  python/oneflow/framework/tensor.py
  python/oneflow/nn/modules/reshape.py
  python/oneflow/nn/modules/sort.py
  python/oneflow/nn/modules/tensor_ops.py
Labels: automerge, op, documentation

#7132 Rm local dep object pool++
  oneflow/api/python/eager/multi_client.cpp
  oneflow/api/python/framework/instruction_replay.cpp
  oneflow/core/eager/local_call_opkernel_phy_instr_operand.cpp
  oneflow/core/eager/opkernel_instruction_type.cpp
  oneflow/core/eager/opkernel_instruction_type.h
  oneflow/core/eager/release_tensor_instruction_type.cpp
  oneflow/core/framework/instruction_replay.cpp
  oneflow/core/framework/instruction_replay.h
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/vm/async_cuda_stream_type.cpp
  oneflow/core/vm/async_cuda_stream_type.h
  oneflow/core/vm/cpu_stream_type.cpp
  oneflow/core/vm/cuda_stream_type.cpp
  oneflow/core/vm/instruction.cpp
  oneflow/core/vm/instruction.h
  oneflow/core/vm/instruction_type.h
  oneflow/core/vm/virtual_machine_engine.cpp
  oneflow/core/vm/virtual_machine_engine.h
  oneflow/user/kernels/stateful_local_opkernel.h
  python/oneflow/nn/optimizer/optimizer.py
  python/oneflow/test/modules/test_instruction_replay.py
Labels: enhancement, automerge, system

#7376 Add inplace support for CastKernel
  oneflow/user/kernels/cast_kernel.cpp
Labels: enhancement, automerge, op, need-clean-ccache

#7389 add lamb optimizer
  docs/source/optim.rst
  oneflow/api/python/functional/dispatch_stateful_ops.cpp
  oneflow/api/python/functional/dispatch_stateful_ops.yaml
  oneflow/core/job/job_conf.proto
  oneflow/core/job_rewriter/adam_optm.cpp
  oneflow/core/job_rewriter/lamb_optm.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/model_update_kernel_util.cpp
  oneflow/user/kernels/model_update_kernel_util.cu
  oneflow/user/kernels/model_update_kernel_util.h
  oneflow/user/kernels/model_update_kernels.cpp
  oneflow/user/ops/model_update_ops.cpp
  python/oneflow/nn/optimizer/lamb.py
  python/oneflow/optim/__init__.py
  python/oneflow/test/graph/test_graph_optim_lamb.py
  python/oneflow/test/modules/test_optim_lamb.py
Labels: feature, automerge, op

#6820 Standalone Maybe: refactor Variant, Optional, Maybe and more
  cmake/oneflow.cmake
  cmake/third_party.cmake
  cmake/third_party/string_view.cmake
  oneflow/maybe/config.h
  oneflow/maybe/error.h
  oneflow/maybe/error_test.cpp
  oneflow/maybe/just.h
  oneflow/maybe/just_test.cpp
  oneflow/maybe/maybe.h
  oneflow/maybe/maybe_test.cpp
  oneflow/maybe/optional.h
  oneflow/maybe/optional_test.cpp
  oneflow/maybe/string_view.h
Labels: feature, automerge, system, refactor

#7385 remove_flowvision_in_requiresment
  .github/workflows/test.yml
  dev-requirements.txt
  oneflow/core/ndarray/ndarray_assign_core.cpp
  oneflow/core/ndarray/ndarray_assign_core.cu
  oneflow/core/ndarray/ndarray_reduce_impl.cpp
  oneflow/core/ndarray/ndarray_reduce_impl.cu
  oneflow/core/ndarray/xpu_ndarray_assign.cu
  oneflow/user/kernels/reduce_kernel.cpp
  python/oneflow/test/modules/test_logical_reduce.py
  python/setup.py
Labels: automerge, bug, eager, api, interface

#7295 timed blocking counter
  oneflow/core/common/blocking_counter.cpp
  oneflow/core/common/blocking_counter.h
  oneflow/core/common/env_var.h
  oneflow/core/job/cluster.cpp
  oneflow/core/job/compiler.cpp
  oneflow/core/job/intra_job_mem_sharing_util.cpp
  oneflow/core/job/runtime_context.cpp
  oneflow/core/kernel/boxing_kernel.cpp
  oneflow/core/kernel/image_decoder_random_crop_resize_kernel.cpp
  oneflow/core/rpc/lib/local.cpp
  oneflow/core/thread/thread_manager.h
  oneflow/core/vm/sequential_instruction_type_test.cpp
  oneflow/core/vm/virtual_machine.cpp
  oneflow/core/vm/virtual_machine.h
  oneflow/core/vm/virtual_machine_engine.cpp
  oneflow/core/vm/virtual_machine_engine.h
  oneflow/core/vm/vm_util.cpp
  oneflow/user/kernels/argmax_kernel.cpp
  oneflow/user/kernels/top_k_kernel.cpp
Labels: enhancement, automerge, system, need-clean-ccache

#7364 Remove `register_tensor_op` decorator and use `add_docstr`[part 4]
  python/oneflow/framework/docstr/tensor.py
  python/oneflow/framework/tensor.py
  python/oneflow/nn/modules/math_ops.py
Labels: automerge, eager, documentation

#7400 change_document_register_method_part8
  docs/source/oneflow.rst
  python/oneflow/framework/docstr/__init__.py
  python/oneflow/framework/docstr/tensor.py
  python/oneflow/framework/docstr/where.py
  python/oneflow/framework/tensor.py
  python/oneflow/nn/modules/tensor_ops.py
  python/oneflow/nn/modules/trigonometric_ops.py
  python/oneflow/nn/modules/where.py
Labels: automerge, documentation, python

#7401 reapply missing commits and update clang-tidy
  .github/workflows/simple.yml
  .github/workflows/test.yml
  ci/check/run_clang_tidy.py
Labels: enhancement, automerge, ci

#7404 standalone maybe: fix compile error in clang 10
  .github/workflows/canary.yml
  .github/workflows/release.yml
  .github/workflows/simple.yml
  .github/workflows/test.yml
  oneflow/maybe/variant.h
Labels: automerge, bug, system

#7241 OpKernel::has_state_or_cache_
  oneflow/core/eager/opkernel_instruction_type.cpp
  oneflow/core/framework/op_kernel.h
  oneflow/core/kernel/user_kernel.cpp
  oneflow/user/kernels/activation_kernels.h
  oneflow/user/kernels/avg_pooling_kernel.cpp
  oneflow/user/kernels/combined_margin_loss_kernel.cu
  oneflow/user/kernels/conv_cudnn_kernels.cpp
  oneflow/user/kernels/conv_kernels.cpp
  oneflow/user/kernels/deconv_cpu_kernel.cpp
  oneflow/user/kernels/eager_b_to_s_kernel.cpp
  oneflow/user/kernels/eager_nccl_kernels.cpp
  oneflow/user/kernels/eager_nccl_kernels.cu
  oneflow/user/kernels/eager_p_to_b_kernel.cpp
  oneflow/user/kernels/eager_p_to_s_kernel.cpp
  oneflow/user/kernels/eager_s_to_b_kernel.cpp
  oneflow/user/kernels/eager_s_to_p_kernel.cpp
  oneflow/user/kernels/eager_s_to_s_kernel.cpp
  oneflow/user/kernels/eager_symmetric_s_to_p_kernel.cpp
  oneflow/user/kernels/elementwise_xpu_kernel.h
  oneflow/user/kernels/group_conv_kernel.cpp
  oneflow/user/kernels/group_deconv_kernel.cpp
  oneflow/user/kernels/pool_cpu_kernel.cpp
  oneflow/user/kernels/pool_gpu_kernel.cpp
  oneflow/user/kernels/pooling_kernel.cpp
  oneflow/user/kernels/stateful_local_opkernel.cpp
Labels: enhancement, automerge, system, need-clean-ccache

#7377 ipc Shared memory
  oneflow/api/python/multiprocessing/shared_memory.cpp
  oneflow/core/common/pcheck.h
  oneflow/core/common/str_util.cpp
  oneflow/core/common/str_util.h
  oneflow/core/ipc/shared_memory.cpp
  oneflow/core/ipc/shared_memory.h
  python/oneflow/multiprocessing/shared_memory/__init__.py
Labels: enhancement, automerge, system

#7384 Feat sbp comb half auto
  oneflow/core/auto_parallel/boxing_collector.cpp
  oneflow/core/auto_parallel/boxing_collector.h
  oneflow/core/framework/consistent_tensor_infer_cache.cpp
  oneflow/core/framework/sbp_infer_util.cpp
  oneflow/core/framework/sbp_infer_util.h
  oneflow/core/graph/boxing/hierarchical_sub_task_graph_builder_impl.cpp
  oneflow/core/graph/boxing/hierarchical_sub_task_graph_builder_impl.h
  oneflow/core/graph/op_graph.cpp
  oneflow/core/job/job_build_and_infer_ctx.cpp
  oneflow/core/job/sbp_parallel.h
  oneflow/core/job_rewriter/boxing_with_middle_nodes.cpp
  oneflow/core/job_rewriter/boxing_with_middle_nodes.h
  oneflow/core/job_rewriter/job_completer.cpp
  oneflow/core/operator/operator.cpp
  oneflow/core/operator/operator.h
Labels: enhancement, automerge, system, AutoParallel

#7403 fix install tbb
  cmake/oneflow.cmake
Labels: enhancement, automerge, bug, build, need-simple-ci

#7379 change_document_register_method_part_5
  docs/source/oneflow.rst
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/math_ops.py
  python/oneflow/framework/docstr/tensor.py
  python/oneflow/framework/tensor.py
  python/oneflow/nn/modules/math_ops.py
Labels: automerge, documentation, api, python

#7408 container_util: fix VectorAt with pointer arguments
  oneflow/core/common/container_util.h
Labels: automerge, bug, system

#7411 Refine configures of release
  .github/workflows/canary.yml
  .github/workflows/release.yml
  .github/workflows/simple.yml
  .github/workflows/test.yml
Labels: enhancement, automerge, ci

#7414 Update readme on installation
  CHANGELOG.md
  README.md
Labels: automerge, documentation, build

#7417 Fix TBB_INCLUDE_DIRS
  external/onetbb/CMakeLists.txt
Labels: automerge, bug, build

#7396 Use local static variable to hold parsed env
  oneflow/core/common/tensor_buffer.cpp
Labels: automerge, bug, system
