Repository Oneflow-Inc/oneflow, pull requests merged in 2022-03, with the labels that each got.

#7598 Add graph advanced features docstr example
  docs/source/graph.rst
  oneflow/xrt/README.md
  python/oneflow/nn/graph/block_config.py
  python/oneflow/nn/graph/graph.py
  python/oneflow/nn/graph/graph_config.py
  python/oneflow/test/modules/test_select.py
Labels: automerge, op, documentation, graph

#7450 consistent max min test cases
  python/oneflow/test/modules/test_consistent_max.py
  python/oneflow/test/modules/test_consistent_min.py
Labels: enhancement, automerge, op, test

#7536 eager global nms
  python/oneflow/test/modules/test_consistent_nms.py
Labels: enhancement, automerge, eager, op

#7601 metaInfo sync check using debue mode
  oneflow/core/common/check_level.h
  oneflow/core/framework/consistency_check.cpp
  oneflow/core/framework/consistency_check.h
  oneflow/core/framework/op_interpreter/eager_consistent_op_interpreter.cpp
  oneflow/core/framework/op_interpreter/lazy_op_interpreter.cpp
  oneflow/core/functional/impl/consistent_cast.cpp
Labels: enhancement, automerge, ci, eager

#7332 Consistent transpose and triplet margin loss test
  python/oneflow/test/modules/test_consistent_TripletMarginLoss.py
  python/oneflow/test/modules/test_consistent_transpose.py
Labels: enhancement, automerge, eager, test, system

#7634 fix leaky relu grad bug
  oneflow/user/kernels/activation_kernels.h
Labels: enhancement, automerge, bug, eager, api

#7503 Dev add contiguous view ops
  oneflow/core/framework/tensor_methods.cpp
  oneflow/core/framework/tensor_methods.h
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/core/functional/impl/common.cpp
  oneflow/core/functional/impl/common.h
  python/oneflow/framework/tensor.py
  python/oneflow/nn/modules/reshape.py
  python/oneflow/test/modules/test_view.py
Labels: enhancement, feature, automerge, op

#7589 delete unittest skip
  python/oneflow/comm/comm_ops.py
  python/oneflow/test/modules/test_comm_ops.py
Labels: purge, automerge, eager

#7308 consistent_tensor_scatter_nd_update_test
  python/oneflow/test/modules/test_consistent_tensor_scatter_nd_update.py
  python/oneflow/test_utils/automated_test_util/generators.py
  python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py
Labels: enhancement, automerge, test, system

#7465 consistent matmul test case
  python/oneflow/test/modules/test_consistent_matmul.py
Labels: enhancement, automerge, test

#7593 refine and align with pytorch
  oneflow/api/python/utils/tensor_utils.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/core/functional/impl/nn_functor.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/tensor.py
  python/oneflow/linalg.py
  python/oneflow/nn/modules/dropout.py
  python/oneflow/nn/modules/reduce_ops.py
  python/oneflow/test/modules/test_consistent_max.py
  python/oneflow/test/modules/test_consistent_min.py
  python/oneflow/test/modules/test_dropout.py
  python/oneflow/test/modules/test_generator.py
  python/oneflow/test/modules/test_max.py
  python/oneflow/test/modules/test_min.py
Labels: enhancement, automerge, system

#7322 Consistent tile and tril test
  python/oneflow/test/modules/test_consistent_tile.py
  python/oneflow/test/modules/test_consistent_tril.py
Labels: enhancement, automerge, test, system

#7596 Control the number of thread pools
  docs/source/oneflow.rst
  oneflow/api/python/multiprocessing/init.cpp
  oneflow/core/ep/cpu/cpu_stream.h
  oneflow/core/job/env_global_objects_scope.cpp
  python/oneflow/__init__.py
  python/oneflow/distributed/launch.py
  python/oneflow/framework/docstr/__init__.py
  python/oneflow/framework/docstr/oneflow.py
  python/oneflow/utils/data/_utils/worker.py
Labels: enhancement, automerge, python, primitive

#7641 purge old code
  oneflow/api/python/framework/tensor.cpp
  oneflow/api/python/utils/tensor_utils.h
Labels: enhancement, purge, automerge, eager

#7632 fix return bug
  oneflow/core/ipc/shared_memory.cpp
Labels: enhancement, automerge, bug, eager, api, need-simple-ci

#7523 finish bool type
  oneflow/api/cpp/framework/tensor.cpp
  oneflow/api/python/functional/indexing.cpp
  oneflow/core/ndarray/unary_func.h
  oneflow/extension/python/py_compute.cpp
  oneflow/user/kernels/as_strided_kernel.cpp
  oneflow/user/kernels/dim_scatter_kernel_util.h
  oneflow/user/kernels/dim_scatter_kernels.cpp
  oneflow/user/kernels/dropout_kernel.cpp
  oneflow/user/kernels/dropout_kernel.cu
  oneflow/user/kernels/eye_kernel.cpp
  oneflow/user/kernels/eye_kernel_util.cpp
  oneflow/user/kernels/eye_kernel_util.cu
  oneflow/user/kernels/eye_kernel_util.h
  oneflow/user/kernels/fused_bias_add_kernel.cu
  oneflow/user/kernels/fused_scale_mask_softmax.cu
  oneflow/user/kernels/fused_scale_mask_softmax_dropout.cu
  oneflow/user/kernels/fused_tril_scale_softmax_mask_scale_kernel.cu
  oneflow/user/kernels/in_top_k_kernel.cpp
  oneflow/user/kernels/in_top_k_kernel_util.cpp
  oneflow/user/kernels/in_top_k_kernel_util.cu
  oneflow/user/kernels/in_top_k_kernel_util.h
  oneflow/user/kernels/logical_not_kernel.cpp
  oneflow/user/kernels/logical_not_kernel.cu
  oneflow/user/kernels/logical_not_kernel.h
  oneflow/user/kernels/nccl_logical_2d_sbp_kernels.cpp
  oneflow/user/kernels/nccl_logical_kernels.cpp
  oneflow/user/kernels/nd_index_slice_kernels.cpp
  oneflow/user/kernels/nd_index_slice_kernels.cu
  oneflow/user/kernels/nd_index_slice_kernels.h
  oneflow/user/kernels/random_mask_generator.cpp
  oneflow/user/kernels/random_mask_generator.cu
  oneflow/user/kernels/random_mask_generator.h
  oneflow/user/kernels/random_mask_like_kernel.h
  oneflow/user/kernels/roll_kernel.cpp
  oneflow/user/kernels/roll_kernel.cu
  oneflow/user/kernels/tril_kernel.cpp
  oneflow/user/kernels/tril_kernel.cu
  oneflow/user/ops/dropout_op.cpp
  oneflow/user/ops/fused_scale_mask_softmax_dropout_op.cpp
  oneflow/user/ops/fused_scale_mask_softmax_op.cpp
  oneflow/user/ops/in_top_k_op.cpp
  oneflow/user/ops/logical_not_op.cpp
  python/oneflow/framework/docstr/comparison.py
  python/oneflow/framework/docstr/in_top_k.py
  python/oneflow/framework/docstr/math_ops.py
  python/oneflow/test/modules/test_fused_scale_mask_softmax.py
  python/oneflow/test/modules/test_fused_scale_mask_softmax_dropout.py
Labels: feature, automerge, eager, op

#7664 cast gather unsorted_segment_sum nccl support uint32
  oneflow/core/device/nccl_util.h
  oneflow/core/ep/cpu/primitive/cast.cpp
  oneflow/core/ep/cpu/primitive/type_seq.h
  oneflow/core/ep/cuda/primitive/cast.cu
  oneflow/core/ep/cuda/primitive/type_seq.h
  oneflow/user/kernels/gather_kernel_util.cpp
  oneflow/user/kernels/gather_kernel_util.cu
  oneflow/user/kernels/gather_kernel_util.h
  oneflow/user/kernels/unsorted_segment_sum_kernel_util.cpp
  oneflow/user/kernels/unsorted_segment_sum_kernel_util.cu
  oneflow/user/kernels/unsorted_segment_sum_kernel_util.h
Labels: enhancement, automerge, op

#7642 eager global ne
  python/oneflow/test/modules/test_consistent_ne.py
Labels: enhancement, automerge, op, test, system

#7644 eager global negative
  python/oneflow/test/modules/test_consistent_negative.py
Labels: enhancement, automerge, system

#7645 eager global nozero
  python/oneflow/test/modules/test_consistent_nozero.py
Labels: enhancement, automerge, system

#7668 Fix from_numpy non-contigous input bug
  oneflow/api/python/functional/tensor_api.cpp
  python/oneflow/test/modules/test_from_numpy.py
Labels: automerge, bug, eager

#7461 consistent math ops
  python/oneflow/test/modules/test_consistent_math_ops.py
  python/oneflow/test/modules/test_consistent_nms.py
Labels: enhancement, automerge, eager, op, test

#7637 Add graph debug function of LR and step
  oneflow/core/kernel/learning_rate_schedule_kernel.cpp
  python/oneflow/nn/graph/graph.py
  python/oneflow/nn/graph/graph_config.py
Labels: feature, automerge, graph

#7557 Fix/sbp error
  oneflow/core/job/job_build_and_infer_ctx.cpp
  oneflow/core/job_rewriter/autograd.cpp
  oneflow/core/job_rewriter/generate_backward_and_optimizer_op_confs.cpp
  oneflow/core/operator/operator.cpp
Labels: automerge, bug, system, graph

#7678 remove global_param_grad_no_sync interface
  python/oneflow/nn/module.py
Labels: enhancement, automerge, eager, api

#7638 [BUG] fixed random op generater bug
  oneflow/user/kernels/distributions/uniform_int_kernel.h
  oneflow/user/kernels/distributions/uniform_kernel.h
  oneflow/user/kernels/random_seed_util.cpp
  oneflow/user/kernels/random_seed_util.h
Labels: automerge, bug, graph

#7647 eager global narrow
  python/oneflow/test/modules/test_consistent_narrow.py
Labels: enhancement, automerge, eager, op, test

#7663 in forked process, run instrutions directly instead of dispatching to vm
  oneflow/core/eager/blob_instruction_type.cpp
  oneflow/core/eager/blob_instruction_type.h
  oneflow/core/platform/lib/pthread_fork.cpp
  oneflow/core/vm/sequential_instruction_type.cpp
  oneflow/core/vm/virtual_machine.cpp
Labels: automerge, bug, system

#7277 consistent_split_and_sqrt_square_sum_test
  python/oneflow/test/modules/test_consistent_split.py
  python/oneflow/test/modules/test_consistent_sqrt_square_sum.py
Labels: enhancement, automerge, test, system

#7687 Speed up CI distributed
  .github/workflows/test.yml
  ci/test/2node_op_test_multi_client.sh
  ci/test/expensive_generic_test_multi_client.sh
  ci/test/generic_test_multi_client.sh
  ci/test/multi_launch.py
  ci/test/test_resnet50_graph_ddp.sh
  oneflow/core/auto_parallel/boxing_collector.cpp
  oneflow/core/framework/sbp_infer_util.cpp
  python/oneflow/test/modules/test_comb2to2d.py
Labels: enhancement, automerge, bug, ci, need-all-tests-even-fail, need-highest-priority

#7661 Add CI DDP TEST OMP_NUM_THREADS=1 ENV
  ci/test/test_speed_multi_client.sh
Labels: enhancement, automerge, ci

#7651 Copy hook when set_data
  oneflow/api/python/framework/tensor.cpp
  oneflow/api/python/utils/tensor_utils.cpp
Labels: automerge, bug, eager

#7672 Use onednn by default
  CMakeLists.txt
Labels: enhancement, automerge, build

#7692 ci(Mergify): configuration update
  .mergify.yml
Labels: enhancement, automerge, ci

#7534 export partical_fc using stateful ops
  oneflow/api/python/functional/dispatch_stateful_ops.cpp
  oneflow/api/python/functional/dispatch_stateful_ops.yaml
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  python/oneflow/__init__.py
  python/oneflow/nn/__init__.py
  python/oneflow/nn/modules/distributed_partial_fc_sample.py
  python/oneflow/test/modules/test_consistent_partical_fc.py
Labels: automerge, bug, ci, interface

#7694 ci(Mergify): configuration update
  .mergify.yml
Labels: enhancement, automerge, ci

#7695 ci(Mergify): configuration update
  .mergify.yml
Labels: enhancement, ci

#7639 Fix coco dataset type in MLIR
  .github/workflows/test.yml
  ci/manylinux/build-gcc7.sh
  ci/manylinux/build.sh
  oneflow/core/graph/op_graph.cpp
  oneflow/core/graph/op_graph.h
  oneflow/core/job_rewriter/cudnn_fused_normalization_add_relu_pass.cpp
  oneflow/core/job_rewriter/insert_nccl_logical_op_pass.cpp
  oneflow/ir/include/OneFlow/OneFlowBase.td
  oneflow/ir/include/OneFlow/OneFlowOps.h
  oneflow/ir/include/OneFlow/OneFlowOps.td
  oneflow/ir/include/OneFlow/OneFlowTypes.h
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/ir/lib/OneFlow/CMakeLists.txt
  oneflow/ir/lib/OneFlow/OneFlowDialect.cpp
  oneflow/ir/lib/OneFlow/OneFlowOpGetGen.cpp.in
  oneflow/ir/lib/OneFlow/OneFlowOps.cpp
  oneflow/ir/lib/OneFlow/OneFlowTypes.cpp
  oneflow/ir/oneflow-extension/ir_pass.cpp
  oneflow/ir/oneflow-translate/include/OneFlow/MLIROneFlowTranslation.h
  oneflow/ir/oneflow-translate/lib/OneFlow/Importer.cpp
  oneflow/ir/oneflow-translate/lib/OneFlow/MLIROneFlowTranslation.cpp
  python/oneflow/test/graph/test_graph_io_check.py
  python/oneflow/test/graph/test_graph_ofrecord_reader.py
  python/oneflow/test/modules/test_coco_reader.py
Labels: automerge, bug, ci, need-all-tests-even-fail

#7696 ci(Mergify): configuration update
  .github/workflows/test.yml
  .mergify.yml
Labels: enhancement, automerge, ci

#7693 Enable LIGHT_ACTOR/LOCAL_MESSAGE_QUEUE by default
  oneflow/core/job/env_global_objects_scope.cpp
  oneflow/core/thread/thread.cpp
Labels: enhancement, system

#7677 fix exception in shm destruction
  python/oneflow/multiprocessing/shared_memory/__init__.py
Labels: automerge, bug, python

#7686 Auto parallel/refine cost
  oneflow/core/auto_parallel/boxing_collector.cpp
  oneflow/core/framework/sbp_infer_util.cpp
  oneflow/core/framework/sbp_infer_util.h
Labels: enhancement, bottleneck, automerge, bug, system, graph, AutoParallel, need-highest-priority

#7526 Add einsum
  docs/source/oneflow.rst
  oneflow/core/common/util.h
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/core/ndarray/xpu_broadcast_ndarray.h
  oneflow/core/ndarray/xpu_shape.h
  oneflow/core/ndarray/xpu_util.h
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/__init__.py
  python/oneflow/framework/docstr/einsum.py
  python/oneflow/nn/modules/einsum.py
  python/oneflow/test/expensive/test_einsum.py
  python/oneflow/test/modules/test_consistent_einsum.py
Labels: feature, automerge, op, system, api, python

#7662 Refine glog level
  oneflow/api/python/env/env.h
  oneflow/api/python/session/session.h
  oneflow/core/comm_network/epoll/epoll_comm_network.cpp
  oneflow/core/comm_network/epoll/io_event_poller.cpp
  oneflow/core/comm_network/ibverbs/ibverbs_comm_network.cpp
  oneflow/core/common/global.h
  oneflow/core/control/ctrl_bootstrap.cpp
  oneflow/core/control/rpc_client.cpp
  oneflow/core/framework/attr_map.cpp
  oneflow/core/framework/blob_register.cpp
  oneflow/core/framework/multi_client_session_context.cpp
  oneflow/core/framework/nn_graph.cpp
  oneflow/core/framework/op_kernel.h
  oneflow/core/graph/task_graph.cpp
  oneflow/core/hardware/net_ib_device_descriptor.cpp
  oneflow/core/job/cluster_instruction.cpp
  oneflow/core/job/eager_nccl_comm_manager.cpp
  oneflow/core/job/env_global_objects_scope.cpp
  oneflow/core/job/improver.cpp
  oneflow/core/job/plan_util.cpp
  oneflow/core/job/runtime.cpp
  oneflow/core/job/runtime_context.cpp
  oneflow/core/job_rewriter/auto_mixed_precision.cpp
  oneflow/core/job_rewriter/fix_pipeline_stage_id_pass.cpp
  oneflow/core/job_rewriter/gradient_accumulation_rewrite_pass.cpp
  oneflow/core/job_rewriter/insert_nccl_logical_op_pass.cpp
  oneflow/core/job_rewriter/momentum_optm.cpp
  oneflow/core/job_rewriter/pipeline_buffer_pass.cpp
  oneflow/core/kernel/user_kernel.cpp
  oneflow/core/lazy/actor/actor.h
  oneflow/core/persistence/binary_in_stream_with_local_copy.cpp
  oneflow/core/rpc/lib/local.cpp
  oneflow/core/thread/thread.cpp
  oneflow/core/thread/thread_manager.cpp
  oneflow/core/vm/cuda_allocator.cpp
  oneflow/core/vm/virtual_machine.cpp
  oneflow/extension/python/py_compute.cpp
  oneflow/user/data/gpt_dataset.cpp
  oneflow/xrt/utility/registry.h
Labels: enhancement, automerge, refactor, graph

#7698 Fix merge -> squash
  .mergify.yml
Labels: automerge, bug, ci

#7689 Added scalar_div/narrow to amp list
  oneflow/core/job_rewriter/auto_mixed_precision_lists.cpp
Labels: enhancement, automerge, op

#7697 Print core dump if distributed fails
  .github/workflows/test.yml
  ci/test/2node_op_test_multi_client.sh
  ci/test/generic_test_multi_client.sh
  ci/test/multi_launch.py
Labels: enhancement, automerge, ci, need-all-tests-even-fail

#7701 ci(Mergify): configuration update
  .mergify.yml
Labels: bug, ci

#7658 Refactor graph sparse optimizer api
  python/oneflow/nn/graph/graph.py
  python/oneflow/nn/graph/optimizer.py
  python/oneflow/nn/optimizer/sparse_optimizer.py
  python/oneflow/optim/__init__.py
  python/oneflow/optim/utils.py
  python/oneflow/test/graph/test_graph_sparse_optimizer.py
Labels: feature, automerge, graph

#7653 Added const buffer for ep::CudaDevice
  oneflow/core/device/cuda_util.cpp
  oneflow/core/ep/cuda/cuda_device.cpp
  oneflow/core/ep/cuda/cuda_device.h
  oneflow/user/kernels/reduce_kernel.cpp
  python/oneflow/test/modules/test_sum.py
Labels: enhancement, automerge, system

#7705 update code owners
  .github/CODEOWNERS
Labels: enhancement, automerge, ci

#7684 Optimize ReduceSumFloatCudaKernel with GEMM
  oneflow/user/kernels/reduce_kernel.cpp
Labels: enhancement, op

#7713 split einsum global tests
  python/oneflow/test/modules/test_consistent_einsum.py
  python/oneflow/test/modules/test_consistent_einsum_alphaflod_usecase1.py
  python/oneflow/test/modules/test_consistent_einsum_alphaflod_usecase10.py
  python/oneflow/test/modules/test_consistent_einsum_alphaflod_usecase11.py
  python/oneflow/test/modules/test_consistent_einsum_alphaflod_usecase2.py
  python/oneflow/test/modules/test_consistent_einsum_alphaflod_usecase3.py
  python/oneflow/test/modules/test_consistent_einsum_alphaflod_usecase4.py
  python/oneflow/test/modules/test_consistent_einsum_alphaflod_usecase5.py
  python/oneflow/test/modules/test_consistent_einsum_alphaflod_usecase6.py
  python/oneflow/test/modules/test_consistent_einsum_alphaflod_usecase7.py
  python/oneflow/test/modules/test_consistent_einsum_alphaflod_usecase8.py
  python/oneflow/test/modules/test_consistent_einsum_alphaflod_usecase9.py
  python/oneflow/test/modules/test_consistent_einsum_attention.py
  python/oneflow/test/modules/test_consistent_einsum_batch_matmul.py
  python/oneflow/test/modules/test_consistent_einsum_batch_matmul2.py
  python/oneflow/test/modules/test_consistent_einsum_batch_matmul3.py
  python/oneflow/test/modules/test_consistent_einsum_batch_matmul4.py
  python/oneflow/test/modules/test_consistent_einsum_batch_matrix_vector_multiply.py
  python/oneflow/test/modules/test_consistent_einsum_batch_permute.py
  python/oneflow/test/modules/test_consistent_einsum_bilinear_transformation.py
  python/oneflow/test/modules/test_consistent_einsum_eltwise_mul_sum_row.py
  python/oneflow/test/modules/test_consistent_einsum_eltwise_mul_then_reduce_sum.py
  python/oneflow/test/modules/test_consistent_einsum_eltwise_multiply.py
  python/oneflow/test/modules/test_consistent_einsum_get_diagonal.py
  python/oneflow/test/modules/test_consistent_einsum_matmul.py
  python/oneflow/test/modules/test_consistent_einsum_matmul2.py
  python/oneflow/test/modules/test_consistent_einsum_matrix_column_sum.py
  python/oneflow/test/modules/test_consistent_einsum_matrix_transpose.py
  python/oneflow/test/modules/test_consistent_einsum_matrix_vector_multiply.py
  python/oneflow/test/modules/test_consistent_einsum_reduce_sum.py
  python/oneflow/test/modules/test_consistent_einsum_tensor_contraction.py
  python/oneflow/test/modules/test_consistent_einsum_tensor_contraction2.py
  python/oneflow/test/modules/test_consistent_einsum_vector_inner_product.py
  python/oneflow/test/modules/test_consistent_einsum_vector_outer_product.py
Labels: enhancement, automerge, test, refactor

#7700 Fix NNGraph GenRegisterHint
  oneflow/core/framework/nn_graph.cpp
  oneflow/core/job/plan_util.cpp
Labels: automerge, bug, system, need-all-tests-even-fail, need-clean-ccache

#7708 Fix ddp allreduce
  python/oneflow/nn/parallel/ddp.py
  python/oneflow/test/modules/test_ddp.py
Labels: automerge, bug, eager, system

#7616 lazy init scope in ThreadLocalScopeStack()
  oneflow/api/common/scope.h
  oneflow/api/cpp/env.cpp
  oneflow/api/cpp/framework/graph.cpp
  oneflow/core/framework/scope_util.cpp
  oneflow/core/framework/scope_util.h
  python/oneflow/__init__.py
  python/oneflow/framework/env_util.py
  python/oneflow/framework/scope_util.py
  python/oneflow/test/graph/test_graph.py
Labels: automerge, bug, system

#6907 Use turbojpeg to achieve partial decoding
  cmake/third_party/libjpeg-turbo.cmake
  oneflow/core/kernel/image_decoder_random_crop_resize_kernel.cpp
  oneflow/user/image/jpeg_decoder.cpp
  oneflow/user/image/jpeg_decoder.h
  oneflow/user/image/jpeg_decoder_test.cpp
  oneflow/user/kernels/ofrecord_decoder_kernels.cpp
Labels: enhancement, automerge, system, refactor

#7669 Remove IsMultiClient() and related code
  ci/test/distributed_run.py
  docs/source/env.rst
  oneflow/api/cpp/env.cpp
  oneflow/api/python/eager/eager.cpp
  oneflow/api/python/eager/multi_client.cpp
  oneflow/api/python/env/env.cpp
  oneflow/api/python/env/env.h
  oneflow/api/python/env/env_api.h
  oneflow/core/common/multi_client.h
  oneflow/core/device/cuda_util.cpp
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/framework/multi_client_session_context.cpp
  oneflow/core/framework/sbp_infer_util.cpp
  oneflow/core/functional/impl/random_functor.cpp
  oneflow/core/graph/task_graph.cpp
  oneflow/core/job/job_build_and_infer_ctx.cpp
  oneflow/core/job/job_build_and_infer_ctx_mgr.cpp
  oneflow/core/job/parallel_desc.cpp
  oneflow/core/job/plan_util.cpp
  oneflow/core/job_rewriter/autotick.cpp
  oneflow/core/job_rewriter/autotick.h
  oneflow/core/job_rewriter/gradient_accumulation_rewrite_pass.cpp
  oneflow/core/job_rewriter/job_completer.cpp
  oneflow/core/job_rewriter/set_default_variable_conf.cpp
  oneflow/core/kernel/callback_notify_kernel.cpp
  oneflow/core/kernel/critical_section_callback_tick_kernel.cpp
  oneflow/core/kernel/critical_section_wait_tick_kernel.cpp
  oneflow/core/kernel/input_kernel.cpp
  oneflow/core/kernel/output_kernel.cpp
  oneflow/core/kernel/return_kernel.cpp
  oneflow/core/kernel/wait_and_send_ids_kernel.cpp
  oneflow/core/operator/output_op.cpp
  oneflow/core/rpc/lib/grpc.cpp
  oneflow/core/vm/id_generator.cpp
  oneflow/core/vm/virtual_machine.cpp
  oneflow/core/vm/vm_util.cpp
  oneflow/user/data/distributed_util.h
  oneflow/user/data/ofrecord_dataset.h
  python/oneflow/__init__.py
  python/oneflow/__main__.py
  python/oneflow/comm/comm_ops.py
  python/oneflow/env.py
  python/oneflow/framework/c_api_util.py
  python/oneflow/framework/env_util.py
  python/oneflow/framework/graph_build_util.py
  python/oneflow/framework/unittest.py
  python/oneflow/nn/graph/graph.py
  python/oneflow/nn/optimizer/optimizer.py
  python/oneflow/test/graph/test_graph.py
  python/oneflow/test/graph/test_input_op_expr.py
  python/oneflow/test/graph/test_multi_client_session.py
  python/oneflow/test/graph/test_output_op_expr.py
  python/oneflow/test/graph/test_user_op_expr.py
  python/oneflow/test/graph/test_variable_op_expr.py
  python/oneflow/test/modules/test_fork_sub_process.py
  python/oneflow/test/modules/test_sparse_softmax_cross_entropy.py
  python/oneflow/utils/data/distributed.py
Labels: purge, automerge, system, python

#7723 fix bug
  python/oneflow/test/modules/test_consistent_narrow.py
Labels: automerge, bug, eager

#7685 call hook in get_acc_tensor
  oneflow/core/autograd/autograd_engine.cpp
  oneflow/core/autograd/autograd_meta.cpp
  oneflow/core/autograd/autograd_meta.h
  oneflow/core/framework/tensor_arg.cpp
  oneflow/core/framework/tensor_arg.h
  python/oneflow/test/tensor/test_tensor_part_1.py
  tools/functional/generate_dispatch_stateful_ops.py
Labels: automerge, bug, eager, system

#7712 fix reduction when tensor nbytes is 0
  python/oneflow/multiprocessing/reductions.py
Labels: enhancement, automerge, bug, eager

#7719 use_env_variable_control_view_ops
  oneflow/core/framework/tensor_methods.cpp
  oneflow/core/framework/tensor_methods.h
Labels: enhancement, feature, automerge, eager

#7714 Added PersistentTable
  CMakeLists.txt
  cmake/third_party.cmake
  cmake/third_party/liburing.cmake
  external/CMakeLists.txt
  external/robin-hood-hashing/CMakeLists.txt
  oneflow/core/embedding/persistent_table.cpp
  oneflow/core/embedding/persistent_table.h
  oneflow/core/embedding/posix_file.h
Labels: feature, automerge, system

#7749 Temporary disable ReduceSumFloatCudaKernel
  oneflow/user/kernels/reduce_kernel.cpp
Labels: automerge, bug, op

#7748 Fix optional MAX_V
  oneflow/core/job_rewriter/adam_optm.cpp
  oneflow/core/job_rewriter/fuse_update_ops_pass.cpp
  oneflow/core/job_rewriter/indexed_slices_optimizer_rewrite_pass.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/model_update_kernels.cpp
  oneflow/user/ops/model_update_ops.cpp
  python/oneflow/nn/optimizer/adam.py
  python/oneflow/nn/optimizer/adamw.py
  python/oneflow/test/modules/test_optim_adam.py
Labels: enhancement, automerge, bug, system

#7746 fix shared_memory open bug
  oneflow/api/python/multiprocessing/shared_memory.cpp
  oneflow/core/ipc/shared_memory.cpp
  oneflow/core/ipc/shared_memory.h
Labels: enhancement, bug, eager, api, need-highest-priority

#7770 skip some tests
  python/oneflow/test/modules/test_consistent_einsum_alphaflod_usecase10.py
  python/oneflow/test/modules/test_consistent_einsum_attention.py
Labels: automerge, bug, ci, test, python

#7729 scalar_reverse_pow op/kernel
  oneflow/core/autograd/gradient_funcs/scalar_pow.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/scalar_math_kernels.cpp
  oneflow/user/kernels/scalar_math_kernels.cu
  oneflow/user/kernels/scalar_math_kernels.h
  oneflow/user/ops/scalar_math_op.cpp
  python/oneflow/framework/tensor.py
  python/oneflow/test/modules/test_math_ops.py
Labels: enhancement, automerge, eager, op

#7747 Close TBB thread pool
  CMakeLists.txt
  cmake/caches/ci/cpu.cmake
  cmake/caches/ci/cuda.cmake
Labels: automerge, bug, build

#7734 Added FullCache
  oneflow/core/embedding/cache.cpp
  oneflow/core/embedding/cache.h
  oneflow/core/embedding/cache_test.cpp
  oneflow/core/embedding/full_cache.cu
  oneflow/core/embedding/full_cache.h
  oneflow/core/embedding/hash_functions.cuh
  oneflow/core/embedding/kv_iterator.h
  oneflow/core/embedding/lru_cache.cu
  oneflow/core/embedding/lru_cache.h
Labels: feature, automerge, system

#7670 Dev add to contiguous kernel
  oneflow/api/python/framework/tensor.cpp
  oneflow/core/autograd/to_contiguous.cpp
  oneflow/core/framework/tensor.cpp
  oneflow/core/framework/tensor.h
  oneflow/core/framework/tensor_impl.h
  oneflow/core/framework/tensor_meta.cpp
  oneflow/core/framework/tensor_meta.h
  oneflow/core/framework/tensor_methods.cpp
  oneflow/core/framework/tensor_methods.h
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/to_contiguous_kernel.cpp
  oneflow/user/kernels/to_contiguous_kernel.cu
  oneflow/user/kernels/to_contiguous_kernel.h
  oneflow/user/ops/to_contiguous_op.cpp
  python/oneflow/framework/tensor.py
  python/oneflow/test/modules/test_contiguous.py
Labels: enhancement, automerge, op, api

#7733 Fix adamw Args name
  python/oneflow/nn/optimizer/adamw.py
Labels: automerge, op, documentation

#7774 Hotfix lru cache compile error
  oneflow/core/embedding/cache_test.cpp
  oneflow/core/embedding/lru_cache.cu
Labels: automerge, bug, build, need-all-tests-even-fail, need-highest-priority

#7391 Dev Fused MLP Kernel
  docs/source/nn.rst
  oneflow/core/autograd/gradient_funcs/cublas_fused_mlp.cpp
  oneflow/core/device/cuda_util.h
  oneflow/core/ep/cuda/cuda_stream.cpp
  oneflow/core/ep/cuda/cuda_stream.h
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/core/functional/impl/nn_grad_functor.cpp
  oneflow/core/job_rewriter/auto_mixed_precision_lists.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/cublas_bias_add_relu_matmul_grad_kernel.cu
  oneflow/user/kernels/cublas_fused_mlp_kernel.cu
  oneflow/user/kernels/cublas_fused_mlp_util.cuh
  oneflow/user/ops/cublas_bias_add_relu_matmul_grad_op.cpp
  oneflow/user/ops/cublas_fused_mlp_op.cpp
  python/oneflow/nn/__init__.py
  python/oneflow/nn/modules/fused_mlp.py
  python/oneflow/test/modules/test_cublas_fused_mlp.py
Labels: enhancement, automerge, op

#7755 Support BN affine=False
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  python/oneflow/test/modules/test_batchnorm.py
Labels: enhancement, automerge, op

#7709 add fuse bias_add_dropout pass
  oneflow/ir/include/OneFlow/OneFlowPatterns.td
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/ir/lib/OneFlow/OneFlowOps.cpp
  oneflow/ir/lib/OneFlow/Passes.cpp
  oneflow/ir/test/OneFlow/ops/test_adaptive_pool.py
  oneflow/ir/test/OneFlow/test_fuse_bias_add_dropout.py
Labels: enhancement, feature, automerge, api, ir

#7764 Fix IndexedSlicesAdamUpdateKernel max_v
  oneflow/user/kernels/model_update_kernels.cpp
Labels: automerge, bug, op

#7635 eager global sucessfully in 1card and 2card
  python/oneflow/test/modules/test_consistent_normalize.py
  python/oneflow/test/modules/test_consistent_ones_like.py
  python/oneflow/test/modules/test_consistent_permute.py
  python/oneflow/test/modules/test_consistent_prod.py
Labels: enhancement, automerge, ci, test

#7739 Added embedding kv store
  oneflow/core/embedding/key_value_store.h
  oneflow/core/embedding/persistent_table_key_value_store.cu
  oneflow/core/embedding/persistent_table_key_value_store.h
Labels: feature, automerge, system

#7706 [cpp api] input output infos
  .github/workflows/pr.yml
  oneflow/api/cpp/framework/graph.cpp
  oneflow/api/cpp/framework/graph.h
  oneflow/api/cpp/tests/graph_test.cpp
Labels: enhancement, automerge, ci, serving

#7778 move_grad_fn_to_right_place
  oneflow/core/autograd/gradient_funcs/to_contiguous.cpp
Labels: enhancement, automerge, op, refactor

#7676 Nms test with split tensor
  python/oneflow/test/modules/test_consistent_nms.py
Labels: purge, automerge, bug, test

#7646 embedding data shuffle ops
  cmake/op_schema.cmake
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/ir/include/OneFlow/CMakeLists.txt
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/ir/lib/OneFlow/CMakeLists.txt
  oneflow/ir/lib/OneFlow/OneFlowDialect.cpp
  oneflow/ir/oneflow-translate/lib/OneFlow/Importer.cpp
  oneflow/user/kernels/data_shuffle_kernel.cu
  oneflow/user/ops/data_shuffle_op.cpp
  python/oneflow/test/expensive/test_id_shuffle.py
  python/oneflow/test/modules/test_id_shuffle_global.py
Labels: enhancement, automerge, op

#7650 eager global mean
  python/oneflow/test/modules/test_consistent_mean.py
Labels: enhancement, automerge, op

#7736 support swin dataloader speed test in ci
  .github/workflows/test.yml
  ci/test/test_speed_multi_client.sh
Labels: feature, automerge, ci, api

#7674 export SequentialLR
  python/oneflow/optim/lr_scheduler.py
Labels: enhancement, automerge, op

#7803 one_embedding update kernels
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/one_embedding_update_kernels.cu
  oneflow/user/ops/one_embedding_ops.cpp
Labels: enhancement, op

#7791 Added CacheKeyValueStore
  oneflow/core/embedding/cached_key_value_store.cu
  oneflow/core/embedding/cached_key_value_store.h
  oneflow/core/embedding/key_value_store_test.cpp
Labels: enhancement, automerge, system

#7760 pybind11 maybe optional type caster
  oneflow/api/python/caster/common.h
  oneflow/api/python/caster/maybe.h
  oneflow/api/python/caster/optional.h
  oneflow/api/python/caster/test.cpp
  oneflow/api/python/eager/eager.cpp
  oneflow/api/python/env/env.cpp
  oneflow/api/python/env/env_api.h
  oneflow/api/python/framework/dtype.cpp
  oneflow/api/python/framework/tensor.cpp
  oneflow/api/python/of_api_registry.h
  oneflow/api/python/rpc/ccl.cpp
  python/oneflow/test/misc/test_pybind11_caster.py
  tools/check_src.py
Labels: enhancement, automerge, system

#7790 Added WarpMutexSemaphoreImpl for LruCache
  oneflow/core/embedding/cache_test.cpp
  oneflow/core/embedding/lru_cache.cu
Labels: enhancement, automerge, system

#7754 Add graph debug function[verbose] of LR and step
  oneflow/api/python/env/env.cpp
  oneflow/api/python/env/env.h
  oneflow/core/job/graph_verbose_step_lr_util.cpp
  oneflow/core/job/graph_verbose_step_lr_util.h
  oneflow/core/kernel/learning_rate_schedule_kernel.cpp
  python/oneflow/framework/graph_build_util.py
  python/oneflow/nn/graph/graph.py
Labels: feature, automerge, documentation, graph, need-highest-priority

#7796 Add nn functional cross entropy
  docs/source/functional.rst
  oneflow/core/functional/functional_api.yaml
  python/oneflow/framework/docstr/loss.py
  python/oneflow/nn/functional/__init__.py
  python/oneflow/test/modules/test_loss.py
Labels: automerge, bug, documentation, api, python

#7745 Migrate pixel_shuffle python layer to functor
  docs/source/nn.rst
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  python/oneflow/nn/modules/pixelshuffle.py
Labels: enhancement, automerge, eager, op

#7798 one embedding managers
  oneflow/api/python/framework/one_embedding_handler.cpp
  oneflow/core/embedding/embedding_manager.cpp
  oneflow/core/embedding/embedding_manager.h
  oneflow/core/embedding/key_value_store_options.h
  oneflow/core/job/env_global_objects_scope.cpp
  python/oneflow/__init__.py
  python/oneflow/one_embedding.py
Labels: enhancement, automerge, system

#7816 Enable FusedMLP use TF32
  oneflow/user/kernels/cublas_fused_mlp_util.cuh
Labels: automerge, bug, op

#7783 Fix param name in optim
  python/oneflow/nn/optimizer/lamb.py
  python/oneflow/nn/optimizer/rmsprop.py
  python/oneflow/nn/optimizer/sgd.py
Labels: automerge, op, documentation

#7824 Fix LruCache value_memory_kind
  oneflow/core/embedding/lru_cache.cu
Labels: automerge, bug, op

#7805 Remove omp.h header file from persistent_table_key_value_store.cu
  oneflow/core/embedding/persistent_table_key_value_store.cu
Labels: automerge, bug, system

#7786 embedding prefetch/lookup/update op
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/core/job/job_build_and_infer_ctx.cpp
  oneflow/core/job_rewriter/autograd.cpp
  oneflow/core/job_rewriter/autograd.h
  oneflow/core/job_rewriter/replace_embedding_ops_pass.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/data_shuffle_kernel.cu
  oneflow/user/kernels/one_embedding_kernels.cu
  oneflow/user/kernels/one_embedding_update_kernels.cu
  oneflow/user/ops/data_shuffle_op.cpp
  oneflow/user/ops/one_embedding_ops.cpp
  python/oneflow/test/expensive/test_id_shuffle.py
Labels: enhancement, automerge, op

#7767 auto nhwc with mlir
  oneflow/ir/include/OneFlow/OneFlowBase.td
  oneflow/ir/include/OneFlow/OneFlowInterfaces.td
  oneflow/ir/include/OneFlow/OneFlowOpTraits.h
  oneflow/ir/include/OneFlow/OneFlowOps.h
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/ir/lib/OneFlow/OneFlowOps.cpp
  oneflow/ir/lib/OneFlow/Passes.cpp
  oneflow/ir/test/OneFlow/auto_nhwc/test_nhwc_batchnorm.py
  oneflow/ir/test/OneFlow/auto_nhwc/test_nhwc_bias_add.py
  oneflow/ir/test/OneFlow/auto_nhwc/test_nhwc_conv.py
  oneflow/ir/test/OneFlow/auto_nhwc/test_nhwc_lenet.py
  oneflow/ir/test/OneFlow/auto_nhwc/test_nhwc_maxpool_2d.py
  oneflow/user/kernels/normalization_kernel.cpp
Labels: enhancement, feature, automerge, bug, api, ir

#7836 [LightActor] Fix regst lifecycle
  oneflow/core/lazy/actor/light_actor.cpp
Labels: bottleneck, automerge, bug, system, need-all-tests-even-fail, need-highest-priority

#7832 Add version v0.8.0
  CHANGELOG.md
  README.md
  tools/generate_pip_version.py
Labels: automerge, documentation, system

#7835 align next function
  python/oneflow/utils/data/dataloader.py
Labels: enhancement, automerge, eager, api

#7823 refine tensor doc and add module to_global doc
  docs/source/index.rst
  docs/source/module.rst
  docs/source/oneflow.rst
  docs/source/placement.rst
  docs/source/sbp.rst
  docs/source/tensor.rst
  docs/source/tensor_attributes.rst
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/__init__.py
  python/oneflow/framework/docstr/global_cast.py
  python/oneflow/framework/docstr/module.py
  python/oneflow/framework/docstr/placement.py
  python/oneflow/framework/docstr/sbp.py
  python/oneflow/framework/docstr/tensor.py
  python/oneflow/framework/docstr/tensor_attributes.py
  python/oneflow/framework/env_util.py
  python/oneflow/test/modules/test_functional_docstr.py
Labels: automerge, documentation, python

#7198 Add exhaustive eager boxing test
  python/oneflow/test/modules/test_eager_boxing_exhaustive.py
Labels: enhancement, automerge, system

#7815 Update bug report templates
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: automerge, ci, documentation, community

#7633 Clear empty thread when graph destroy
  .github/workflows/test.yml
  oneflow/core/framework/multi_client_session_context.cpp
  oneflow/core/framework/nn_graph.cpp
  oneflow/core/job/runtime.cpp
  oneflow/core/job/runtime.h
  oneflow/core/thread/thread.cpp
  oneflow/core/thread/thread.h
  oneflow/core/thread/thread_manager.cpp
  oneflow/core/thread/thread_manager.h
Labels: enhancement, blocked, bug, system, graph

#7858 Optimizer decorator
  .github/workflows/test.yml
  oneflow/core/boxing/asymmetric_broadcast.cpp
  oneflow/core/boxing/boxing_dividor_util.cpp
  oneflow/core/boxing/boxing_interpreter_status.cpp
  oneflow/core/boxing/ccl_boxing_function.cpp
  oneflow/core/boxing/eager_boxing_interpreter.cpp
  oneflow/core/boxing/eager_boxing_interpreter_mgr.cpp
  oneflow/core/boxing/flatten_hierarchy.cpp
  oneflow/core/boxing/identity_boxing_interpreter.cpp
  oneflow/core/boxing/naive_1_to_p_boxing.cpp
  oneflow/core/boxing/naive_b_to_1_boxing.cpp
  oneflow/core/boxing/naive_b_to_s_boxing.cpp
  oneflow/core/boxing/naive_p_to_b_boxing.cpp
  oneflow/core/boxing/naive_p_to_s_boxing.cpp
  oneflow/core/boxing/naive_s_to_b_boxing.cpp
  oneflow/core/boxing/naive_s_to_p_boxing.cpp
  oneflow/core/boxing/naive_s_to_s_boxing.cpp
  oneflow/core/boxing/nccl_boxing_function.cpp
  oneflow/core/boxing/nd_sbp_dim_reduce_boxing.cpp
  oneflow/core/boxing/one_to_one_boxing.cpp
  oneflow/core/boxing/symmetric_acyclic_nd_sbp_boxing.cpp
  oneflow/core/boxing/symmetric_b_to_p_boxing.cpp
  oneflow/core/boxing/symmetric_b_to_s_boxing.cpp
  oneflow/core/boxing/symmetric_s_to_p_boxing.cpp
  oneflow/core/boxing/unflatten_hierarchy.cpp
  oneflow/core/common/decorator.h
  oneflow/core/common/env_var.h
Labels: enhancement, automerge, system

#7821 optimize global tensor err msg
  oneflow/core/framework/tensor.h
Labels: automerge, documentation, api, graph

#7753 Support pass excess key-value from optimizer
  python/oneflow/nn/optimizer/optimizer.py
Labels: feature, automerge, eager

#7827 fix addn 0shape
  oneflow/user/kernels/add_n_kernel.cpp
Labels: automerge, bug, eager, op

#7537 Add libai CI steps
  .github/workflows/test.yml
Labels: enhancement, automerge, ci

#7772 make eager test cases
  python/oneflow/test/modules/test_consistent_cumsum.py
  python/oneflow/test/modules/test_consistent_deconv2d.py
  python/oneflow/test/modules/test_consistent_diagonal.py
  python/oneflow/test/modules/test_consistent_dropout.py
  python/oneflow/test/modules/test_consistent_fold.py
Labels: enhancement, automerge, eager

#7852 Add cu115 to nightly
  .github/workflows/canary.yml
  .github/workflows/release.yml
  .github/workflows/simple.yml
  .github/workflows/test.yml
Labels: feature, automerge, ci

#7298 consistent_sparse_softmax_cross_entropy
  .github/workflows/test.yml
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/core/job_rewriter/split_sparse_softmax_cross_entropy_op_pass.cpp
  python/oneflow/test/modules/test_consistent_sparse_softmax_cross_entropy.py
Labels: enhancement, automerge, test, system

#7289 consistent_squeeze_stack_stateful_kernel_with_cache_test
  oneflow/user/ops/reshape_user_op_util.cpp
  python/oneflow/test/modules/test_consistent_squeeze.py
  python/oneflow/test/modules/test_consistent_stack.py
  python/oneflow/test/modules/test_consistent_stateful_kernel_with_cache.py
Labels: enhancement, automerge, test, system

#7831 fix nms error that comes from sorting of scores
  python/oneflow/test/modules/test_nms.py
Labels: automerge, bug, op, test

#7846 Added DISABLE_NUMA_AWARE_ALLOCATION/PERSISTENT_TABLE_NUM_WORKERS
  oneflow/core/embedding/embedding_manager.cpp
  oneflow/core/embedding/full_cache.cu
  oneflow/core/embedding/key_value_store_options.h
  oneflow/core/embedding/lru_cache.cu
  oneflow/core/embedding/persistent_table.cpp
  oneflow/core/embedding/persistent_table.h
  python/oneflow/one_embedding.py
Labels: enhancement, automerge, system

#7876 add fuse_scale_tril_pass's test case
  oneflow/ir/test/OneFlow/test_fuse_scale_tril.py
Labels: enhancement, automerge, test, ir

#7761 add view_as, split_with_sizes op
  docs/source/oneflow.rst
  docs/source/tensor.rst
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/array_functor.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/__init__.py
  python/oneflow/framework/docstr/split_with_sizes.py
  python/oneflow/framework/docstr/tensor.py
  python/oneflow/framework/docstr/view_as.py
  python/oneflow/framework/tensor.py
  python/oneflow/test/modules/test_split_with_sizes.py
  python/oneflow/test/modules/test_view_as.py
  python/oneflow/test/tensor/test_tensor_part_2.py
Labels: op, documentation

#7891 fix_var_bug_and_add_global_var_test
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/user/kernels/variance_kernel_util.cu
  oneflow/user/ops/reshape_user_op_util.cpp
  oneflow/user/ops/variance_op.cpp
  python/oneflow/test/modules/test_consistent_var.py
Labels: enhancement, automerge, system

#7679 eager global movedim
  python/oneflow/test/modules/test_consistent_movedim.py
Labels: enhancement, automerge, test

#7883 fix_unfold_tensor_sbp_and_add_global_test
  oneflow/user/ops/unfold_tensor_op.cpp
  python/oneflow/test/modules/test_consistent_unfold.py
  python/oneflow/test/modules/test_consistent_unfold_tensor.py
Labels: enhancement, automerge, system

#7683 eager global maxpool
  python/oneflow/test/modules/test_consistent_maxpool.py
Labels: enhancement, automerge, eager, test

#7881 fix grid sample get sbp and add global test
  oneflow/user/ops/grid_sample_op.cpp
  python/oneflow/test/modules/test_consistent_grid_sample.py
Labels: automerge, bug, op

#7840 refine swin-transformer speed test info in ci
  .github/workflows/test.yml
Labels: enhancement, automerge, bug, ci, api

#7841 fix tensor method docstr bug
  python/oneflow/framework/docstr/tensor.py
Labels: enhancement, automerge, bug, ci, documentation, api

#7785 Fix is_contiguous init
  oneflow/core/framework/tensor_impl.cpp
  oneflow/core/framework/tensor_meta.cpp
Labels: automerge, bug, eager

#7866 fix reduce_sum scalar check bug
  oneflow/core/common/shape.cpp
  oneflow/user/ops/reduce_ops.cpp
  python/oneflow/test/modules/test_sum.py
Labels: enhancement, automerge, bug, eager, api

#7882 add_unsqueeze_and_triu_global_test
  oneflow/user/ops/reshape_user_op_util.cpp
  python/oneflow/test/modules/test_consistent_triu.py
  python/oneflow/test/modules/test_consistent_unsqueeze.py
Labels: enhancement, automerge, system

#7826 Add op softshrink
  docs/source/functional.rst
  docs/source/nn.rst
  oneflow/core/autograd/gradient_funcs/activation.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/activation_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/activation_kernels.cpp
  oneflow/user/kernels/activation_kernels.cu
  oneflow/user/kernels/activation_kernels.h
  oneflow/user/ops/softshrink_op.cpp
  python/oneflow/__init__.py
  python/oneflow/nn/__init__.py
  python/oneflow/nn/functional/__init__.py
  python/oneflow/nn/modules/activation.py
  python/oneflow/test/modules/test_activation.py
  python/oneflow/test/modules/test_consistent_activation.py
Labels: enhancement, automerge, op, python

#7871 update speed test threshold
  ci/test/test_speed_multi_client.sh
Labels: enhancement, automerge, ci, need-highest-priority

#7863 Fix var op negative dim bug
  oneflow/core/functional/impl/math_functor.cpp
  python/oneflow/test/modules/test_var.py
Labels: enhancement, automerge, bug, eager, api

#7853 Align to api with torch
  python/oneflow/framework/tensor.py
  python/oneflow/test/modules/test_tensor_to.py
Labels: enhancement, automerge, bug, eager, api

#7838 fix one embedding stream name
  oneflow/core/job_rewriter/replace_embedding_ops_pass.cpp
Labels: enhancement, automerge, system

#7837 Cast op optimal pass
  oneflow/ir/include/OneFlow/OneFlowPatterns.td
  oneflow/ir/lib/OneFlow/Passes.cpp
  oneflow/ir/test/OneFlow/test_cast_optimal_pass.py
Labels: feature, automerge, ir

#7888 Fix softplus op
  oneflow/core/autograd/gradient_funcs/activation.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/activation_functor.cpp
  oneflow/core/functional/impl/unary_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/activation_kernels.cpp
  oneflow/user/kernels/activation_kernels.cu
  oneflow/user/kernels/activation_kernels.h
  oneflow/user/kernels/math_unary_elementwise_func.h
  oneflow/user/ops/math_unary_elementwise_seq.h
  oneflow/user/ops/softplus_op.cpp
  python/oneflow/framework/docstr/activation.py
  python/oneflow/nn/modules/activation.py
  python/oneflow/test/modules/test_activation.py
  python/oneflow/test/modules/test_consistent_activation.py
Labels: automerge, bug, eager, op

#7717 Eager global mul
  python/oneflow/test/modules/test_consistent_mul.py
Labels: enhancement, automerge, test

#7849 Add more documentation
  oneflow/api/python/framework/doc.cpp
  python/oneflow/autograd/autograd.py
  python/oneflow/framework/docstr/tensor.py
Labels: automerge, bug, eager, documentation

#7808 Dev fix high order derivative
  oneflow/api/python/framework/tensor.cpp
  oneflow/core/autograd/autograd_captured_tensor.h
  oneflow/core/framework/op_expr_grad_function.h
  oneflow/core/framework/op_interpreter/eager_mirrored_op_interpreter.cpp
  oneflow/core/framework/op_interpreter/op_interpreter.cpp
  oneflow/core/framework/tensor.cpp
  oneflow/core/framework/tensor.h
  oneflow/core/functional/impl/math_functor.cpp
  python/oneflow/test/modules/test_autograd.py
Labels: enhancement, automerge, system

#7894 Auto upload docs built in CI
  .github/workflows/test.yml
  ci/test/build_docs.sh
Labels: enhancement, automerge, ci, need-all-tests-even-fail

#7901 Update requirements.txt
  docs/requirements.txt
Labels: automerge, bug, ci, documentation

#7726 eager global moving average max min observer
  python/oneflow/test/modules/test_consistent_moving_average_max_min_observer.py
Labels: enhancement, automerge, op, test

#7812 remove Get(Ptr)OrThrow in python api
  oneflow/api/python/autograd/autograd.cpp
  oneflow/api/python/autograd/autograd_function.cpp
  oneflow/api/python/calibration/calibration.cpp
  oneflow/api/python/calibration/calibration_api.h
  oneflow/api/python/deprecated.cpp
  oneflow/api/python/framework/attr_map.cpp
  oneflow/api/python/framework/blob_register.cpp
  oneflow/api/python/framework/foreign_boxing_util.cpp
  oneflow/api/python/framework/framework.cpp
  oneflow/api/python/framework/framework_api.h
  oneflow/api/python/framework/id_util.cpp
  oneflow/api/python/framework/instructions_builder.cpp
  oneflow/api/python/framework/nn_graph.cpp
  oneflow/api/python/framework/object_storage.cpp
  oneflow/api/python/framework/op_builder.cpp
  oneflow/api/python/framework/parallel_conf_util.cpp
  oneflow/api/python/framework/py_kernel_registry.cpp
  oneflow/api/python/framework/py_remote_blob.cpp
  oneflow/api/python/framework/random_generator.cpp
  oneflow/api/python/framework/scope_util.cpp
  oneflow/api/python/framework/session_util.cpp
  oneflow/api/python/framework/tensor.cpp
  oneflow/api/python/job_build/job_build_and_infer.cpp
  oneflow/api/python/job_build/job_build_and_infer_api.h
  oneflow/api/python/multiprocessing/shared_memory.cpp
  oneflow/api/python/numpy/init_numpy_c_api.cpp
  oneflow/api/python/registry/registry.cpp
  oneflow/api/python/rpc/consistent_rpc_token_scope.cpp
  oneflow/api/python/rpc/rank_group.cpp
  oneflow/api/python/session/session.cpp
  oneflow/api/python/session/session.h
  oneflow/api/python/session/session_api.h
  oneflow/api/python/symbol/placement_symbol.cpp
  oneflow/api/python/symbol/sbp_symbol.cpp
  oneflow/api/python/symbol/scope_symbol.cpp
  oneflow/api/python/vm/id_generator.cpp
Labels: enhancement, automerge, python

#7844 Fix docstr[lixiang]
  python/oneflow/framework/docstr/__init__.py
  python/oneflow/framework/docstr/argsort.py
  python/oneflow/framework/docstr/array_ops.py
  python/oneflow/framework/docstr/expand.py
  python/oneflow/framework/docstr/repeat.py
  python/oneflow/framework/docstr/sort.py
  python/oneflow/framework/docstr/tensor.py
  python/oneflow/nn/modules/argwhere.py
  python/oneflow/nn/modules/loss.py
  python/oneflow/nn/modules/roll.py
Labels: automerge, bug, op, documentation

#7763 replace cudaMemset with cudaMemsetAsync
  oneflow/user/kernels/slice_kernel.cpp
  oneflow/user/kernels/softmax_cross_entropy_kernel.cu
Labels: enhancement, automerge, op

#7913 Fix expand flow size bug
  python/oneflow/nn/modules/constant.py
  python/oneflow/nn/modules/expand.py
  python/oneflow/test/modules/test_expand.py
Labels: enhancement, automerge, bug, eager, api

#7925 relax speed test threshold
  ci/test/test_speed_multi_client.sh
Labels: enhancement, automerge, build

#7908 fix randperm infer buffer
  oneflow/user/kernels/randperm_kernel.cu
  python/oneflow/test/modules/test_randperm.py
Labels: automerge, bug, op

#7725 eager global min_max oberver
  python/oneflow/test/modules/test_consistent_min_max_observer.py
Labels: enhancement, automerge, eager
