Repository Oneflow-Inc/oneflow, pull requests merged in 2022-11, with the labels that each got.

#9280 Feat: isclose and allclose
  docs/source/oneflow.rst
  docs/source/tensor.rst
  oneflow/api/python/framework/tensor_functions.cpp
  oneflow/core/ep/common/primitive/binary_functor.h
  oneflow/core/ep/common/primitive/broadcast_elementwise_binary.h
  oneflow/core/ep/cuda/primitive/binary_functor.cuh
  oneflow/core/ep/include/primitive/binary_op.h
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/binary_functor.cpp
  oneflow/core/ndarray/binary_func.h
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/math_binary_broadcast_kernels.cpp
  oneflow/user/ops/math_binary_broadcast_seq.h
  python/oneflow/_C/__init__.py
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/comparison.py
  python/oneflow/framework/tensor.py
  python/oneflow/test/modules/test_allclose.py
  python/oneflow/test/modules/test_isclose.py
Labels: enhancement, automerge, op, documentation, api, python

#9299 Refactor random op with consistent data
  oneflow/core/functional/impl/common.cpp
  oneflow/core/functional/impl/common.h
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/core/functional/impl/random_functor.cpp
  oneflow/user/kernels/random_seed_util.cpp
  oneflow/user/kernels/random_seed_util.h
  python/oneflow/test/modules/test_global_random_op_data.py
Labels: enhancement, automerge, op, need-clean-ccache

#9324 bool tensor slice_update use masked_fill when possible
  oneflow/api/python/framework/tensor_functions.cpp
  python/oneflow/test/tensor/test_global_tensor_indexing.py
Labels: enhancement, automerge, eager, api

#9303 Move tensor apis to cpython
  oneflow/api/python/framework/tensor.cpp
  oneflow/api/python/framework/tensor_functions.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/array_functor.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/is_floating_point.py
  python/oneflow/framework/dtype.py
  python/oneflow/framework/tensor.py
  python/oneflow/nn/modules/flip.py
  python/oneflow/nn/modules/tensor_ops.py
Labels: enhancement, automerge, eager

#9343 Add gelu_tanh op and kernel
  oneflow/core/autograd/gradient_funcs/activation.cpp
  oneflow/core/ep/common/primitive/broadcast_elementwise_binary.h
  oneflow/core/ep/common/primitive/elementwise_unary.h
  oneflow/core/ep/cpu/primitive/binary_functor.h
  oneflow/core/ep/cpu/primitive/unary_functor.h
  oneflow/core/ep/cuda/primitive/binary_functor.cuh
  oneflow/core/ep/cuda/primitive/unary_functor.cuh
  oneflow/core/ep/include/primitive/binary_op.h
  oneflow/core/ep/include/primitive/unary_op.h
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/activation_functor.cpp
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/activation_kernels.cpp
  oneflow/user/ops/gelu_op.cpp
  python/oneflow/test/modules/test_activation.py
Labels: enhancement, automerge, op

#9344 fix_test_maxpool2d_channel_last
  oneflow/user/kernels/max_pool_kernel.cu
  python/oneflow/test/modules/test_global_maxpool.py
  python/oneflow/test/modules/test_maxpool.py
Labels: enhancement, bug, eager

#9307 Refactor normal initializer
  oneflow/core/job/initializer_conf.proto
  python/oneflow/nn/init.py
  python/oneflow/ops/initializer_register.py
  python/oneflow/test/modules/test_initializer.py
  python/oneflow/test/tensor/test_tensor_part_1.py
Labels: enhancement, automerge, eager

#9337 Support fp16 in constant folding
  oneflow/api/common/variable_tensor_mgr.h
  oneflow/api/python/framework/variable_tensor_mgr.cpp
  oneflow/core/framework/variable_tensor_mgr.cpp
  oneflow/core/framework/variable_tensor_mgr.h
  oneflow/ir/include/OneFlow/OneFlowOps.h
  oneflow/ir/include/OneFlow/OneFlowOps.td
  oneflow/ir/include/OneFlow/OneFlowPatterns.td
  oneflow/ir/include/OneFlow/OneFlowSupport.h
  oneflow/ir/lib/OneFlow/Conversion/OneFlowToTosa.cpp
  oneflow/ir/lib/OneFlow/OneFlowOpFolders.cpp
  oneflow/ir/lib/OneFlow/OneFlowOpGetGen.cpp.in
  oneflow/ir/lib/OneFlow/OneFlowSupport.cpp
  oneflow/ir/lib/OneFlow/Passes.cpp
  oneflow/ir/oneflow-extension/kernel_launch_op.cpp
  oneflow/ir/oneflow-extension/mlir_jit_op_infer.cpp
  oneflow/ir/oneflow-translate/lib/OneFlow/Importer.cpp
  oneflow/ir/oneflow-translate/lib/OneFlow/MLIROneFlowTranslation.cpp
  oneflow/ir/test/OneFlow/folding/test_simple_multiply.py
  python/oneflow/nn/graph/graph.py
Labels: enhancement, feature, automerge, system

#9353 fix exp overflow with minus max trick
  python/oneflow/distributions/categorical.py
Labels: automerge, bug, eager

#9355 Feat speed up cost computation
  oneflow/core/framework/sbp_infer_util.cpp
Labels: feature, eager, graph, AutoParallel

#9354 Fix occasional bug in random_op data test
  python/oneflow/test/modules/test_global_random_op_data.py
Labels: bug, eager, global

#9208 Dev add gumbel softmax
  docs/source/nn.functional.rst
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/activation_functor.cpp
  oneflow/user/kernels/argmax_kernel.cpp
  oneflow/user/kernels/argmax_kernel.cu
  oneflow/user/kernels/dim_scatter_kernel_util.cpp
  oneflow/user/kernels/dim_scatter_kernel_util.cu
  oneflow/user/kernels/dim_scatter_kernel_util.h
  oneflow/user/kernels/dim_scatter_kernels.cpp
  oneflow/user/kernels/dim_scatter_scalar_kernel_util.cpp
  oneflow/user/kernels/dim_scatter_scalar_kernel_util.cu
  oneflow/user/kernels/dim_scatter_scalar_kernel_util.h
  oneflow/user/kernels/dim_scatter_scalar_kernels.cpp
  oneflow/user/kernels/log_softmax_kernel.cpp
  python/oneflow/framework/docstr/activation.py
  python/oneflow/nn/functional/__init__.py
  python/oneflow/test/modules/test_gumbel_softmax.py
Labels: automerge, op, test, documentation

#9321 Fix the inconsistent behavior of slice update
  oneflow/api/python/functional/common.cpp
  oneflow/core/framework/tensor_util.cpp
  oneflow/core/framework/tensor_util.h
  oneflow/core/functional/tensor_index.cpp
  python/oneflow/test/modules/test_slice.py
Labels: enhancement, automerge, op, test, documentation

#9362 enable autocast for that op which has nocast arguments
  oneflow/core/functional/tensor_processor.cpp
Labels: automerge, bug, eager, system

#9368 Add NHWC format for group norm
  oneflow/core/autograd/gradient_funcs/group_norm.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/ir/lib/OneFlow/OneFlowOps.cpp
  oneflow/user/kernels/group_norm_kernel.cu
  oneflow/user/ops/group_norm_op.cpp
  python/oneflow/test/modules/test_groupnorm.py
Labels: enhancement, automerge, op

#9288 Enable ZeRO with auto parallel
  docs/source/auto_parallel.rst
  oneflow/core/auto_parallel/sbp_collector.cpp
  oneflow/core/auto_parallel/sbp_constructor.cpp
  oneflow/core/auto_parallel/sbp_constructor.h
  oneflow/core/auto_parallel/sbp_edge.cpp
  oneflow/core/auto_parallel/sbp_edge.h
  oneflow/core/auto_parallel/sbp_graph.cpp
  oneflow/core/auto_parallel/sbp_graph.h
  oneflow/core/auto_parallel/sbp_node.cpp
  oneflow/core/auto_parallel/sbp_node.h
  oneflow/core/graph/straighten_nodes.cpp
  oneflow/core/job/job_conf.proto
  oneflow/core/job_rewriter/optimizer_placement_optimization_pass.cpp
  python/oneflow/nn/graph/graph_config.py
  python/oneflow/test/graph/test_alexnet_auto_parallel.py
Labels: feature, automerge, bug, graph, AutoParallel

#9310 Feat unbalanced split nd sbp
  oneflow/core/boxing/nd_sbp_dim_reduce_boxing.cpp
  oneflow/core/framework/sbp_infer_util.cpp
  oneflow/core/framework/sbp_infer_util.h
  oneflow/core/graph/boxing/hierarchical_sub_task_graph_builder_impl.cpp
  oneflow/core/job/job_build_and_infer_ctx.cpp
  oneflow/core/job/nd_sbp_util.cpp
  oneflow/core/job_rewriter/group_boxing_by_dst_parallel.cpp
  oneflow/core/job_rewriter/insert_nccl_logical_op_pass.cpp
  oneflow/core/job_rewriter/optimizer_placement_optimization_pass.cpp
  oneflow/core/operator/operator.cpp
  python/oneflow/test/graph/test_gbc1to2d.py
  python/oneflow/test/graph/test_gbc2d.py
  python/oneflow/test/graph/test_gbc2to1d.py
Labels: feature, automerge, graph

#9366 Add upsample_nearest_2d to amp clear list
  oneflow/core/job_rewriter/auto_mixed_precision_lists.cpp
Labels: enhancement, automerge, op

#9346 fix cuda integral type closeness computation
  oneflow/core/ep/cuda/primitive/binary_functor.cuh
Labels: automerge, bug, op

#9369 Add fused linear
  python/oneflow/nn/modules/linear.py
Labels: enhancement, automerge, op

#9374 Support fp16 on some cpu operators
  oneflow/user/kernels/reduce_kernel.cpp
  oneflow/user/kernels/triu_kernel.cpp
  python/oneflow/test/modules/test_triu.py
Labels: feature, automerge, eager, graph

#9372 Scalar math kernels support inplace
  oneflow/user/kernels/scalar_math_kernels.cpp
Labels: enhancement, automerge, op

#9373 Optimize GroupNorm NHWC with FastDivmod
  oneflow/core/cuda/layer_norm.cuh
  oneflow/user/kernels/group_norm_kernel.cu
Labels: enhancement, op

#8961 GradAcc Mem V5: Part 0-4
  oneflow/core/common/env_var/debug_mode.h
  oneflow/core/framework/nn_graph.cpp
  oneflow/core/graph/plan_task_graph.cpp
  oneflow/core/graph/sharable_mem_block_graph.cpp
  oneflow/core/graph/sharable_mem_block_graph.h
  oneflow/core/graph/straighten_nodes.cpp
  oneflow/core/graph/task_graph.cpp
  oneflow/core/graph/task_graph.h
  oneflow/core/graph/task_node.cpp
  oneflow/core/graph/task_node.h
  oneflow/core/graph_impl/acc_ctrl_tick_compute_task_node.cpp
  oneflow/core/graph_impl/repeat_compute_task_node.cpp
  oneflow/core/job/compiler.cpp
  oneflow/core/job/intra_job_mem_sharing_util.cpp
  oneflow/core/job/job.proto
  oneflow/core/job/job_builder.h
  oneflow/core/job/plan_util.cpp
  oneflow/core/job/plan_util.h
  oneflow/core/job/task.proto
  oneflow/core/job_rewriter/autograd.cpp
  oneflow/core/job_rewriter/group_boxing_by_dst_parallel.cpp
  oneflow/core/job_rewriter/insert_nccl_logical_op_pass.cpp
  oneflow/core/job_rewriter/job_completer.cpp
  oneflow/core/job_rewriter/logical_chain_pass.cpp
  oneflow/core/lazy/actor/acc_ctrl_tick_actor.cpp
  oneflow/core/lazy/actor/register_slot.cpp
  oneflow/core/lazy/actor/register_slot.h
  oneflow/core/lazy/actor/repeat_actor.cpp
  oneflow/core/operator/device_tick_op.cpp
  oneflow/core/operator/op_conf.proto
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/nop_kernel.cpp
  oneflow/user/kernels/repeat_kernel.cpp
  oneflow/user/ops/acc_ctrl_tick_op.cpp
  python/oneflow/nn/graph/graph_config.py
Labels: enhancement, automerge, graph

#9375 fix the bug of fill_tensor_ of support fp16 & autocast
  oneflow/core/functional/impl/array_functor.cpp
Labels: automerge, bug, graph

#9376 Disable conv algorithm search in eager mode
  oneflow/core/job/compiler.cpp
  oneflow/core/thread/thread.cpp
  oneflow/user/kernels/conv_cudnn_kernels.cpp
Labels: automerge, bug, op

#9387 Add FusedGroupNormSilu
  oneflow/core/autograd/gradient_funcs/group_norm.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/group_norm_kernel.cu
Labels: enhancement, automerge, op

#9392 Update fmt
  CMakeLists.txt
Labels: automerge, bug, build

#9395 FusedConvBias
  oneflow/core/autograd/gradient_funcs/conv.cpp
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/core/job_rewriter/fuse_add_to_output_pass.cpp
  oneflow/ir/include/OneFlow/OneFlowBase.td
  oneflow/ir/include/OneFlow/OneFlowPatterns.td
  oneflow/ir/lib/OneFlow/OneFlowOps.cpp
  oneflow/ir/lib/OneFlow/Passes.cpp
  oneflow/user/kernels/conv_cudnn_kernels.cpp
  oneflow/user/kernels/conv_kernels.cpp
  oneflow/user/ops/conv_op.cpp
Labels: enhancement, op

#9388 fix batchnorm infer dtype failed in half inference
  oneflow/core/functional/impl/nn_functor.cpp
  python/oneflow/test/modules/test_batchnorm.py
Labels: enhancement, automerge, bug, eager, documentation, api

#9385 fix_logsumexp_overflow_error
  oneflow/core/functional/impl/math_functor.cpp
  python/oneflow/test/modules/test_logsumexp.py
Labels: enhancement, automerge, bug, system

#9384 Refactor uniform initializer
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/random_functor.cpp
  oneflow/core/job/initializer_conf.proto
  python/oneflow/nn/init.py
  python/oneflow/ops/initializer_register.py
  python/oneflow/test/modules/test_initializer.py
Labels: enhancement, automerge, op, test, documentation

#9400 Feat module to local
  python/oneflow/nn/module.py
  python/oneflow/test/modules/test_module_to_global_or_local.py
Labels: feature, automerge, eager

#9404 Update tensor contrustor to fix issue #9403
  oneflow/api/python/utils/tensor_utils.cpp
  python/oneflow/test/tensor/test_tensor_part_1.py
Labels: automerge, bug, eager

#9408 Optimize fast_gelu half specialization
  oneflow/core/ep/cuda/primitive/unary_functor.cuh
Labels: enhancement, automerge, op

#9401 Impl of fused_bias_add_scale_mask_softmax_dropout
  oneflow/core/autograd/gradient_funcs/fused_bias_add_scale_mask_softmax_dropout.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/core/job_rewriter/auto_mixed_precision_lists.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/fused_bias_add_scale_mask_softmax_dropout.cu
  oneflow/user/kernels/fused_scale_mask_softmax.cu
  oneflow/user/kernels/fused_scale_mask_softmax_dropout.cu
  oneflow/user/kernels/fused_softmax.cuh
  oneflow/user/ops/fused_bias_add_scale_mask_softmax_dropout_op.cpp
  python/oneflow/test/modules/test_fused_bias_add_scale_mask_softmax_dropout.py
Labels: enhancement, automerge, op

#9402 Fix bug when autograd.grad meet tensor.grad is not None
  oneflow/api/python/framework/tensor.cpp
  oneflow/core/autograd/autograd_engine.cpp
  oneflow/core/autograd/autograd_engine.h
  oneflow/core/autograd/autograd_meta.cpp
  oneflow/core/autograd/autograd_meta.h
  oneflow/core/framework/tensor.h
  oneflow/core/framework/tensor_arg.cpp
  oneflow/core/framework/tensor_arg.h
  oneflow/core/framework/tensor_impl.cpp
  python/oneflow/test/modules/test_autograd.py
Labels: enhancement, automerge, bug, eager

#9415 Optimize UpsampleNearest2D 2X
  oneflow/user/kernels/upsample_nearest_kernel.cu
Labels: enhancement, op, need-all-tests-even-fail

#9309 Add MaxUnpool op
  docs/source/nn.functional.rst
  docs/source/nn.rst
  oneflow/core/autograd/gradient_funcs/max_unpool.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/core/functional/impl/nn_grad_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowBase.td
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/max_pool_kernel_util.cpp
  oneflow/user/kernels/max_unpool_kernel.cpp
  oneflow/user/kernels/max_unpool_kernel.cu
  oneflow/user/kernels/max_unpool_kernel_util.cpp
  oneflow/user/kernels/max_unpool_kernel_util.h
  oneflow/user/ops/max_unpool_op.cpp
  oneflow/user/utils/pool_util.cpp
  oneflow/user/utils/pool_util.h
  python/oneflow/framework/docstr/pooling.py
  python/oneflow/nn/__init__.py
  python/oneflow/nn/functional/__init__.py
  python/oneflow/nn/modules/pooling.py
  python/oneflow/test/modules/test_global_maxunpool.py
  python/oneflow/test/modules/test_maxunpool.py
Labels: enhancement, automerge, op, test, documentation, api

#9393 bypass StopIteration error in dataloader delete_shm
  python/oneflow/multiprocessing/reductions.py
Labels: automerge, bug, python

#9397 Impl of fused_fast_gelu_mul
  oneflow/core/autograd/gradient_funcs/fused_fast_gelu_mul.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/core/job_rewriter/auto_mixed_precision_lists.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/fused_gelu_mul_kernel.cu
  oneflow/user/ops/gelu_op.cpp
  python/oneflow/test/modules/test_fused_gelu_mul.py
Labels: enhancement, automerge, op, api

#9412 Add autograd engine debug graph
  oneflow/core/autograd/autograd_engine.cpp
  oneflow/core/autograd/autograd_engine.h
Labels: enhancement, feature, automerge, eager

#9416 Optimize transpose identity
  oneflow/user/kernels/transpose_kernel.cpp
Labels: enhancement, automerge, op

#9417 Optimize fmha transpose
  CMakeLists.txt
  oneflow/user/kernels/fused_multi_head_attention_inference_kernel.cu
Labels: enhancement, op

#9421 Fix the usage of argument end_factor in LinearLR
  oneflow/core/kernel/learning_rate_schedule_kernel.cpp
  python/oneflow/nn/optimizer/linear_lr.py
  python/oneflow/test/graph/test_graph_lr_scheduler.py
  python/oneflow/test/modules/test_lr_scheduler.py
Labels: automerge, bug, api, python

#9420 Fix lazy scalar tensor indexing
  oneflow/core/framework/tensor_util.cpp
  oneflow/core/functional/tensor_index.cpp
Labels: automerge, bug, graph

#9413 GroupedMatmulBias
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/core/job_rewriter/auto_mixed_precision_lists.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/grouped_matmul_bias.cu
  oneflow/user/ops/grouped_matmul_bias_op.cpp
  python/oneflow/test/modules/test_grouped_matmul_bias.py
Labels: enhancement, automerge, op, need-all-tests-even-fail

#9424 Optim upsample backward
  oneflow/user/kernels/upsample_nearest_kernel.cu
Labels: enhancement, automerge, eager, api

#9278 Speed up the training
  oneflow/core/graph/straighten_nodes.cpp
  oneflow/core/graph/task_graph.cpp
  oneflow/core/job/job_conf.proto
  python/oneflow/nn/graph/graph_config.py
Labels: feature, automerge, graph

#9394 Profiling item
  oneflow/api/cpp/framework/tensor.cpp
  oneflow/api/python/framework/tensor.cpp
  oneflow/api/python/utils/tensor_utils.cpp
  oneflow/api/python/utils/tensor_utils.h
  oneflow/core/common/blocking_then_busy.h
  oneflow/core/common/data_type.h
  oneflow/core/common/notifier.cpp
  oneflow/core/common/notifier.h
  oneflow/core/common/spin_counter.cpp
  oneflow/core/common/spin_counter.h
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/framework/instructions_builder.h
  oneflow/core/framework/op_interpreter/eager_local_op_interpreter.cpp
  oneflow/core/framework/tensor_util.cpp
  oneflow/core/framework/tensor_util.h
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/core/thread/thread_manager.h
  oneflow/core/vm/stream.cpp
  oneflow/core/vm/stream.h
  oneflow/core/vm/sync_access_instruction_policy.cpp
  oneflow/core/vm/sync_access_instruction_policy.h
  oneflow/core/vm/virtual_machine.cpp
  oneflow/core/vm/virtual_machine.h
  oneflow/core/vm/virtual_machine_engine.cpp
  python/oneflow/framework/tensor.py
Labels: enhancement, automerge, system

#9351 Graph rename v2
  .github/workflows/test.yml
  docs/source/graph.rst
  oneflow/api/python/eager/eager.cpp
  oneflow/core/auto_parallel/sbp_graph.cpp
  oneflow/core/auto_parallel/sbp_node.cpp
  oneflow/core/auto_parallel/sbp_node.h
  oneflow/core/graph/straighten_nodes.cpp
  oneflow/core/job_rewriter/optimizer_placement_optimization_pass.cpp
  python/oneflow/comm/comm_ops.py
  python/oneflow/framework/check_point_v2.py
  python/oneflow/framework/graph_build_util.py
  python/oneflow/nn/graph/__init__.py
  python/oneflow/nn/graph/block_config.py
  python/oneflow/nn/graph/graph.py
  python/oneflow/nn/graph/graph_block.py
  python/oneflow/nn/graph/graph_config.py
  python/oneflow/nn/graph/proxy.py
  python/oneflow/nn/optimizer/optimizer.py
  python/oneflow/test/graph/test_graph.py
  python/oneflow/test/graph/test_graph_activation_checkpoint.py
  python/oneflow/test/graph/test_graph_block.py
  python/oneflow/test/graph/test_graph_clip_grad_norm.py
  python/oneflow/test/graph/test_graph_debug.py
  python/oneflow/test/graph/test_graph_io_check.py
  python/oneflow/test/graph/test_graph_linear.py
  python/oneflow/test/graph/test_graph_linear_train.py
  python/oneflow/test/graph/test_graph_lr_with_warmup.py
  python/oneflow/test/graph/test_graph_lrs.py
  python/oneflow/test/graph/test_graph_non_contiguous_tensors.py
  python/oneflow/test/graph/test_graph_pipeline.py
  python/oneflow/test/graph/test_graph_pipeline_delay.py
  python/oneflow/test/graph/test_graph_reshape_acc.py
  python/oneflow/test/graph/test_graph_save_load_global_b_s.py
  python/oneflow/test/graph/test_graph_zero.py
  python/oneflow/test/graph/test_neq_device_process_num.py
  python/oneflow/test/modules/test_global_slice.py
  python/oneflow/test/modules/test_global_slice_update.py
  python/oneflow/test/modules/test_slice.py
  python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py
Labels: enhancement, automerge, bug, api, python

#9436 [hotfix] remove cuda half unittest in maxunpool
  python/oneflow/test/modules/test_maxunpool.py
Labels: enhancement, automerge, bug, test, python

#9437 Fix checkpoint v2
  python/oneflow/framework/check_point_v2.py
Labels: automerge, bug, graph

#9141 Support broadcast ops
  docs/source/oneflow.rst
  docs/source/tensor.rst
  oneflow/api/python/framework/tensor_functions.cpp
  oneflow/api/python/functional/value_types.h
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/core/functional/impl/comm_functor.cpp
  oneflow/core/functional/impl/common.cpp
  oneflow/core/functional/impl/common.h
  oneflow/core/functional/impl/linalg_functor.cpp
  python/oneflow/__init__.py
  python/oneflow/comm/comm_ops.py
  python/oneflow/framework/docstr/tensor.py
  python/oneflow/framework/tensor.py
  python/oneflow/nn/modules/broadcast_ops.py
  python/oneflow/nn/parallel/ddp.py
  python/oneflow/test/exceptions/test_broadcast_ops.py
  python/oneflow/test/modules/test_broadcast_ops.py
  python/oneflow/test/modules/test_global_broadcast_ops.py
  tools/functional/generator.py
Labels: enhancement, automerge, op

#9320 Reduce print op graph cost
  python/oneflow/nn/graph/graph.py
  python/oneflow/nn/graph/graph_block.py
  python/oneflow/nn/graph/util.py
  python/oneflow/test/graph/test_long_add_n_pass.py
Labels: enhancement, automerge, graph

#9442 Fix torch mocking test in GH action
  .github/workflows/test.yml
Labels: automerge, bug, ci

#9380 Performant RMSNorm
  docs/source/nn.rst
  oneflow/core/autograd/gradient_funcs/rms_norm.cpp
  oneflow/core/cuda/rms_norm.cuh
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/core/functional/impl/nn_grad_functor.cpp
  oneflow/core/job_rewriter/auto_mixed_precision_lists.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/rms_norm_gpu_kernel.cu
  oneflow/user/ops/rms_norm_op.cpp
  python/oneflow/nn/__init__.py
  python/oneflow/nn/modules/normalization.py
  python/oneflow/test/expensive/test_rmsnorm.py
Labels: enhancement, op

#9433 Ciou get bounding boxes coord fuse kernel
  oneflow/api/python/utils/tensor_utils.h
  oneflow/core/autograd/gradient_funcs/fused_get_boundding_boxes_coord.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/fused_get_bounding_boxes_coord_kernel.cu
  oneflow/user/ops/fused_get_boundding_boxes_coord_op.cpp
  python/oneflow/test/modules/test_fused_get_boundding_boxes_coord.py
Labels: enhancement, feature, automerge, eager, api

#9349 fix matmul of cpu in int32&int64
  oneflow/core/functional/impl/nn_functor.cpp
  python/oneflow/test/modules/test_matmul.py
Labels: automerge, bug, op

#9446 Fuse center kernel
  oneflow/core/autograd/gradient_funcs/fused_center.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/fused_center_kernel.cu
  oneflow/user/ops/fused_center_op.cpp
  python/oneflow/test/modules/test_fused_center.py
Labels: enhancement, feature, automerge, eager, op, api

#9448 Reduce rmsnorm test time
  python/oneflow/test/modules/test_rmsnorm.py
Labels: automerge, bug, ci

#9360 Fix div dtype & atan2
  oneflow/core/functional/impl/binary_functor.cpp
  oneflow/core/functional/impl/math_functor.cpp
  python/oneflow/test/modules/test_div.py
  python/oneflow/test/modules/test_math_ops.py
Labels: automerge, bug, op

#9452 [Hotfix]Temporarily disable fuse_add_to_output for conv
  oneflow/core/job_rewriter/fuse_add_to_output_pass.cpp
Labels: automerge, bug, op, need-all-tests-even-fail

#9447 Bump cutlass from 2.10 to 2.11
  CMakeLists.txt
  external/cutlass/CMakeLists.txt
  oneflow/user/kernels/fused_multi_head_attention_inference_kernel.cu
Labels: enhancement, automerge, build

#9455 Fix binary math op wrong dtype
  oneflow/core/functional/impl/binary_functor.h
  python/oneflow/test/modules/test_binary_math_ops_dtype.py
Labels: enhancement, automerge, bug, op

#9444 Add index add api
  docs/source/oneflow.rst
  docs/source/tensor.rst
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/index_add_kernel.cpp
  oneflow/user/kernels/index_add_kernel.cu
  oneflow/user/ops/index_add_op.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/__init__.py
  python/oneflow/framework/docstr/index_add.py
  python/oneflow/framework/tensor.py
  python/oneflow/test/modules/test_as_strided.py
  python/oneflow/test/modules/test_index_add.py
Labels: enhancement, feature, automerge, bug, eager, op, api

#9327 mock with scope
  ci/test/test_mock_function.sh
  python/oneflow/__init__.py
  python/oneflow/mock_torch/__init__.py
  python/oneflow/test/misc/test_mock.py
  python/oneflow/test/misc/test_mock_scope.py
  python/oneflow/test/misc/test_mock_simple.py
Labels: feature, automerge, python

#9456 revert item
  python/oneflow/framework/tensor.py
Labels: automerge, bug, system

#9267 Multi tensor optimizer
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/multi_tensor_model_update_kernel.cpp
  oneflow/user/kernels/multi_tensor_model_update_kernel_util.cu
  oneflow/user/kernels/multi_tensor_model_update_kernel_util.h
  oneflow/user/ops/multi_tensor_model_update_ops.cpp
  python/oneflow/nn/optimizer/adam.py
  python/oneflow/nn/optimizer/adamw.py
  python/oneflow/nn/optimizer/sgd.py
  python/oneflow/test/modules/optimizer_test_util.py
  python/oneflow/test/modules/test_multi_tensor_adam_update.py
  python/oneflow/test/modules/test_multi_tensor_adamw_update.py
  python/oneflow/test/modules/test_multi_tensor_sgd_update.py
  python/oneflow/test/modules/test_optim_adam.py
  python/oneflow/test/modules/test_optim_adamw.py
  python/oneflow/test/modules/test_optim_sgd.py
Labels: feature, automerge, eager, test, python

#9406 Add PDLL example
  cmake/oneflow.cmake
  oneflow/ir/CMakeLists.txt
  oneflow/ir/include/OneFlow/OneFlowOps.td
  oneflow/ir/include/OneFlow/OneFlowPDLLPatterns.h
  oneflow/ir/include/OneFlow/OneFlowPatternUtils.h
  oneflow/ir/include/OneFlow/OneFlowPatterns.td
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/ir/include/OneFlow/Passes.h
  oneflow/ir/lib/OneFlow/CMakeLists.txt
  oneflow/ir/lib/OneFlow/OneFlowCanonicalizers.cpp
  oneflow/ir/lib/OneFlow/OneFlowRewrites.cpp
  oneflow/ir/lib/OneFlow/PDLL/CMakeLists.txt
  oneflow/ir/lib/OneFlow/PDLL/ForwardOpPatterns.cpp
  oneflow/ir/lib/OneFlow/PDLL/ForwardOpPatterns.pdll
  oneflow/ir/lib/OneFlow/Passes.cpp
  oneflow/ir/oneflow-opt/oneflow-opt.cpp
  oneflow/ir/oneflow-translate/lib/OneFlow/MLIROneFlowTranslation.cpp
  oneflow/ir/test/OneFlow/fuse_forward_ops.mlir
  oneflow/ir/test/OneFlow/with_cuda/test_fuse_bias_add_dropout.py
  oneflow/ir/test/OneFlow/with_cuda/test_fuse_scale_tril.py
Labels: feature, automerge, ir

#9462 Fuse get ciou result
  oneflow/core/autograd/gradient_funcs/fused_get_ciou_result.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/fused_get_ciou_result_kernel.cu
  oneflow/user/ops/fused_get_ciou_result_op.cpp
  python/oneflow/test/modules/test_fused_get_ciou_result.py
Labels: enhancement, feature, automerge, eager, op, api

#9464 Add FusedBiasAddGelu PDLL Pattern
  .github/workflows/canary.yml
  .github/workflows/on_merge.yml
  .github/workflows/release.yml
  .github/workflows/simple.yml
  .github/workflows/test.yml
  oneflow/ir/include/OneFlow/OneFlowPatterns.td
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/ir/lib/OneFlow/OneFlowOps.cpp
  oneflow/ir/lib/OneFlow/PDLL/ForwardOpPatterns.pdll
  oneflow/ir/lib/OneFlow/Passes.cpp
  oneflow/ir/test/OneFlow/fuse_forward_ops.mlir
  oneflow/ir/test/OneFlow/with_cuda/test_fuse_bias_add_gelu.py
Labels: enhancement, automerge, ir

#9451 Fix as strided backward
  oneflow/core/autograd/gradient_funcs/as_strided.cpp
  oneflow/core/framework/tensor_methods.cpp
  oneflow/core/framework/tensor_methods.h
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/core/functional/tensor_index.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/as_strided_kernel.cpp
  oneflow/user/kernels/as_strided_kernel.cu
  oneflow/user/ops/as_strided_op.cpp
Labels: enhancement, automerge, bug, eager

#9468 Support cpu scalar tensor auto cast in binary broadcast op
  oneflow/core/functional/impl/binary_functor.cpp
  oneflow/core/functional/impl/binary_functor.h
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/user/kernels/math_binary_broadcast_kernels.cpp
  python/oneflow/test/modules/test_broadcast_ops.py
Labels: feature, automerge, op

#9471 Disable EIGEN_NO_MALLOC
  cmake/third_party/eigen.cmake
Labels: automerge, bug, build

#9472 align ddp filename
  python/oneflow/nn/parallel/distributed.py
Labels: automerge, bug, python

#9476 Revert "align ddp filename"
  python/oneflow/nn/parallel/ddp.py
Labels: bug, python

#9479 hot fix for fused_get_boundding_boxes_coord
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/ops/fused_get_boundding_boxes_coord_op.cpp
Labels: enhancement, automerge, bug, eager, api

#9473 fix wrong mock of torchvision
  python/oneflow/mock_torch/__init__.py
Labels: bug, python

#9483 set default param log_target=False in kl_div
  oneflow/core/functional/functional_api.yaml
  python/oneflow/test/modules/test_loss.py
Labels: enhancement, automerge, bug, op, api

#9480 [resubmit] align ddp filename
  python/oneflow/nn/parallel/__init__.py
  python/oneflow/nn/parallel/distributed.py
  python/oneflow/test/modules/test_ddp.py
Labels: automerge, bug, python

#9484 Enable --use-fast-math for fmha
  CMakeLists.txt
  cmake/oneflow.cmake
Labels: enhancement, automerge, op, build

#9407 Refactor global-random functor
  oneflow/core/functional/impl/random_functor.cpp
  python/oneflow/test/modules/test_global_random_op_data.py
Labels: enhancement, automerge, op

#9363 support named tuple for return type
  oneflow/api/python/functional/python_return_types.h
  oneflow/core/functional/functional_api.yaml
  python/oneflow/nn/graph/util.py
  python/oneflow/test/modules/test_max.py
  tools/functional/generate_functional_api.py
  tools/functional/generator.py
Labels: enhancement, system, api

#9481 Add fuse get convex diagonal squared
  oneflow/core/autograd/gradient_funcs/fused_get_convex_diagonal_squared.cpp
  oneflow/core/common/math_util.h
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/fused_get_convex_diagonal_squared_kernel.cu
  oneflow/user/ops/fused_get_convex_diagonal_squared_op.cpp
  python/oneflow/test/modules/test_fused_get_convex_diagonal_squared.py
Labels: enhancement, feature, automerge, eager, api

#9441 Add FusedMatmulBias
  oneflow/core/autograd/gradient_funcs/fused_matmul_bias.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/core/job_rewriter/auto_mixed_precision_lists.cpp
  oneflow/core/job_rewriter/fuse_add_to_output_pass.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/cublas_fused_mlp_util.cuh
  oneflow/user/kernels/fused_matmul_bias_kernel.cu
  oneflow/user/ops/fused_matmul_bias_op.cpp
  python/oneflow/test/modules/test_fused_matmul_bias.py
Labels: enhancement, feature, automerge, op

#9491 Disable CUDA_STATIC for cu116
  cmake/cuda.cmake
Labels: automerge, bug, build

#9494 Use fused_matmul_bias as the implementation of FusedLinear
  python/oneflow/nn/modules/linear.py
Labels: enhancement, automerge, op
