Repository Oneflow-Inc/oneflow, pull requests merged in 2022-08, with the labels that each got.

#8787 Remove template for sbp signature
  oneflow/core/auto_parallel/boxing_collector.cpp
  oneflow/core/auto_parallel/boxing_collector.h
  oneflow/core/auto_parallel/sbp_collector.cpp
  oneflow/core/auto_parallel/sbp_collector.h
  oneflow/core/auto_parallel/sbp_constructor.cpp
  oneflow/core/auto_parallel/sbp_constructor.h
  oneflow/core/auto_parallel/sbp_edge.cpp
  oneflow/core/auto_parallel/sbp_edge.h
  oneflow/core/auto_parallel/sbp_graph.cpp
  oneflow/core/auto_parallel/sbp_graph.h
  oneflow/core/auto_parallel/sbp_node.cpp
  oneflow/core/auto_parallel/sbp_node.h
Labels: AutoParallel

#8804 _shutdown_workers does nothing if _utils is freed
  python/oneflow/utils/data/dataloader.py
Labels: automerge, bug, python

#8806 mv id_shuffle testcase to expensive dir
  python/oneflow/test/expensive/test_id_shuffle_global.py
Labels: enhancement, op

#8811 Fix bug of init_tmp_buffer_ptr in CallContext
  oneflow/core/eager/call_context.h
  oneflow/core/vm/op_call_instruction_policy.cpp
Labels: enhancement, automerge, bug, system, need-highest-priority

#8813 Fix global tensor clone
  oneflow/core/functional/impl/global_cast.cpp
  python/oneflow/test/graph/test_graph_clip_grad_norm.py
  python/oneflow/test/graph/test_graph_pipeline.py
  python/oneflow/test/graph/test_graph_scalar.py
  python/oneflow/test/modules/test_tensor_to.py
Labels: automerge, bug, op, need-highest-priority, global

#8794 relax cuda.set_device requirement
  python/oneflow/cuda/__init__.py
Labels: automerge, bug, python

#8745 Broadcast tensors
  oneflow/core/common/tensor_meta.cpp
  oneflow/core/framework/local_tensor_infer_cache.cpp
  oneflow/core/framework/op_interpreter/eager_local_op_interpreter.cpp
  oneflow/core/framework/op_interpreter/eager_local_op_interpreter.h
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/comm_functor.cpp
  oneflow/user/kernels/eager_nccl_kernels.cpp
  oneflow/user/kernels/eager_nccl_kernels.cu
  oneflow/user/ops/comm_net_device_infer_util.h
  oneflow/user/ops/eager_nccl_ops.cpp
  python/oneflow/nn/parallel/ddp.py
Labels: enhancement, automerge, eager

#8815 Remove PhyInstrOperand and InstructionType
  oneflow/core/framework/instructions_builder.h
  oneflow/core/vm/fuse_instruction_policy.h
  oneflow/core/vm/instruction.cpp
  oneflow/core/vm/instruction.h
  oneflow/core/vm/instruction_policy.h
  oneflow/core/vm/instruction_type.cpp
  oneflow/core/vm/instruction_type.h
  oneflow/core/vm/phy_instr_operand.h
  oneflow/core/vm/virtual_machine.cpp
  oneflow/core/vm/virtual_machine_engine.cpp
  oneflow/core/vm/vm_util.cpp
Labels: enhancement, automerge, system, refactor

#8570 Tmp compute
  oneflow/core/autograd/autograd_engine.cpp
  oneflow/core/common/env_var/autograd.h
  oneflow/core/common/stream_role.h
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/framework/instructions_builder.h
  oneflow/core/framework/stream_allocator_is_pinned.h
  oneflow/core/framework/stream_get_stream_role_name.h
  oneflow/core/framework/stream_is_comm_net_stream.h
  oneflow/core/framework/stream_need_soft_sync.h
  oneflow/core/framework/stream_on_independent_thread.h
  oneflow/core/framework/tensor_methods.cpp
  oneflow/core/framework/tensor_methods.h
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/core/vm/ep_record_event_instruction_policy.h
  oneflow/core/vm/release_tensor_instruction_policy.h
  oneflow/core/vm/stream_get_stream_policy.h
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/ops/copy_op.cpp
Labels: enhancement, automerge, system

#8784 add double grad for slice op
  oneflow/core/autograd/higher_order_gradient_funcs/leaky_relu.cpp
  oneflow/core/autograd/higher_order_gradient_funcs/math_unary_op.cpp
  oneflow/core/autograd/higher_order_gradient_funcs/slice.cpp
  python/oneflow/test/modules/test_global_higher_derivative_slice.py
  python/oneflow/test/modules/test_higher_derivative_slice.py
Labels: enhancement, automerge, op, test

#8612 scalar math kernel use primitive
  oneflow/core/ep/common/primitive/binary_functor.h
  oneflow/core/ep/common/primitive/broadcast_elementwise_binary.h
  oneflow/core/ep/cpu/primitive/binary_functor.h
  oneflow/core/ep/cuda/primitive/binary_functor.cuh
  oneflow/core/ep/include/primitive/binary_op.h
  oneflow/user/kernels/math_binary_broadcast_kernels.cpp
  oneflow/user/kernels/scalar_math_kernels.cpp
  oneflow/user/kernels/scalar_math_kernels.cu
  oneflow/user/kernels/scalar_math_kernels.h
  python/oneflow/test/modules/test_math_ops.py
Labels: enhancement, automerge, op

#8816 Rename StreamRole to StreamType
  oneflow/core/autograd/autograd_engine.cpp
  oneflow/core/common/stream_type.h
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/framework/stream.cpp
  oneflow/core/framework/stream.h
  oneflow/core/framework/stream_allocator_is_pinned.h
  oneflow/core/framework/stream_get_stream_type_name.h
  oneflow/core/framework/stream_is_comm_net_stream.h
  oneflow/core/framework/stream_need_soft_sync.h
  oneflow/core/framework/stream_on_independent_thread.h
  oneflow/core/framework/tensor_impl.cpp
  oneflow/core/framework/user_op_registry.cpp
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/core/vm/control_stream_policy.h
  oneflow/core/vm/ep_record_event_instruction_policy.h
  oneflow/core/vm/ep_stream_policy.cpp
  oneflow/core/vm/instruction.cpp
  oneflow/core/vm/op_call_instruction_policy.cpp
  oneflow/core/vm/pinned_ep_stream_policy.cpp
  oneflow/core/vm/release_tensor_instruction_policy.h
  oneflow/core/vm/stream.cpp
  oneflow/core/vm/stream.h
  oneflow/core/vm/stream_get_stream_policy.h
  oneflow/core/vm/stream_policy.cpp
  oneflow/core/vm/stream_policy.h
  oneflow/core/vm/virtual_machine.cpp
  oneflow/core/vm/virtual_machine.h
  oneflow/user/ops/cast_op.cpp
  oneflow/user/ops/comm_net_device_infer_util.cpp
  oneflow/user/ops/copy_op.cpp
  oneflow/user/ops/empty_op.cpp
Labels: enhancement, automerge, system, refactor

#8808 Tensor from numpy support stride
  oneflow/api/python/functional/tensor_api.cpp
  python/oneflow/test/modules/test_from_numpy.py
Labels: enhancement, automerge, eager, api

#8212 Sync vm mode guard
  oneflow/core/common/thread_local_guard.h
  oneflow/core/common/thread_local_guard_test.cpp
  oneflow/core/platform/lib/pthread_fork.cpp
  oneflow/core/thread/thread_pool.cpp
  oneflow/core/vm/sync_vm_mode_guard.h
  oneflow/core/vm/virtual_machine.cpp
Labels: automerge, bug, system

#8773 Fix copy not support broadcast
  python/oneflow/framework/tensor.py
  python/oneflow/test/modules/test_copy.py
Labels: enhancement, feature, automerge, bug, eager, api

#8752 fix get default cpu device
  oneflow/core/framework/op_interpreter/eager_local_op_interpreter.cpp
Labels: automerge, bug, eager

#8826 separate lazy and eager tensor names
  oneflow/core/framework/tensor_name_scope.cpp
  oneflow/core/framework/tensor_name_scope.h
Labels: automerge, bug, system

#8807 Add Cross Feature Interaction in AMP List[OneEmbedding]
  oneflow/core/job_rewriter/auto_mixed_precision_lists.cpp
Labels: enhancement, automerge, op, embedding

#8687 Env var compute on worker thread
  oneflow/core/common/env_var/vm.h
  oneflow/core/profiler/profiler.h
  oneflow/core/vm/stream_policy.cpp
Labels: enhancement, automerge, system

#8796 Schedule yield
  oneflow/core/common/env_var/vm.h
  oneflow/core/vm/virtual_machine.cpp
Labels: enhancement, automerge, system

#8688 add conv higher order derivative
  oneflow/core/autograd/higher_order_gradient_funcs/conv.cpp
  oneflow/core/functional/impl/nn_grad_functor.cpp
  python/oneflow/test/modules/test_global_higher_derivative_conv.py
  python/oneflow/test/modules/test_higher_derivative_conv.py
Labels: enhancement, automerge, op, test

#8829 refine graph lr scheduler test
  oneflow/core/kernel/learning_rate_schedule_kernel.cpp
  python/oneflow/test/graph/test_graph_lr_scheduler.py
Labels: enhancement, automerge, test

#8825 Fix nn init eye bug
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/eye_functor.cpp
  python/oneflow/nn/init.py
  python/oneflow/test/tensor/test_tensor_part_1.py
Labels: enhancement, feature, automerge, bug, eager, api

#8819 Fix binary cross entropy with logits op bug
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/user/ops/binary_cross_entropy_with_logits_op.cpp
  python/oneflow/test/modules/test_loss.py
Labels: enhancement, automerge, bug, op, api

#8839 Fix build failure when accessing https://docs.python.org/3/objects.inv
  docs/source/conf.py
Labels: automerge, bug, ci

#8835 Refactor auto parallel class object stuff
  oneflow/core/auto_parallel/sbp_collector.cpp
  oneflow/core/auto_parallel/sbp_constructor.cpp
  oneflow/core/auto_parallel/sbp_edge.cpp
  oneflow/core/auto_parallel/sbp_edge.h
  oneflow/core/auto_parallel/sbp_graph.h
  oneflow/core/auto_parallel/sbp_node.cpp
  oneflow/core/auto_parallel/sbp_node.h
Labels: AutoParallel

#8827 Primitives check n_dims gt 0
  oneflow/core/ep/common/primitive/copy_nd.h
  oneflow/core/ep/cpu/primitive/broadcast_elementwise_unary.cpp
  oneflow/core/ep/cpu/primitive/constant_pad.cpp
  oneflow/core/ep/cuda/primitive/broadcast_elementwise_unary.cu
  oneflow/core/ep/cuda/primitive/constant_pad.cu
Labels: enhancement, automerge, bug, system

#8830 Default copy eager boxing expr
  oneflow/api/python/framework/tensor_functions.cpp
  oneflow/core/boxing/asymmetric_broadcast.cpp
  oneflow/core/boxing/cuda_copy_boxing_interpreter.cpp
  oneflow/core/boxing/flatten_hierarchy.cpp
  oneflow/core/boxing/identity_boxing_interpreter.cpp
  oneflow/core/boxing/naive_1_to_p_boxing.cpp
  oneflow/core/boxing/naive_b_to_1_boxing.cpp
  oneflow/core/boxing/one_to_one_boxing.cpp
  oneflow/core/boxing/symmetric_b_to_p_boxing.cpp
  oneflow/core/boxing/unflatten_hierarchy.cpp
  oneflow/core/framework/op_interpreter/eager_local_op_interpreter.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/ops/eager_nccl_ops.cpp
  python/oneflow/framework/docstr/tensor.py
  python/oneflow/nn/modules/global_cast.py
Labels: enhancement, automerge, system

#8681 Support OneEmbedding in cpp api[OneEmbedding]
  .github/workflows/test.yml
  oneflow/api/cpp/embedding/embedding.cpp
  oneflow/api/cpp/embedding/embedding.h
  oneflow/api/cpp/framework/graph.cpp
  oneflow/api/cpp/tests/one_embedding_test.cpp
  python/oneflow/framework/check_point_v2.py
  python/oneflow/one_embedding.py
Labels: enhancement, automerge, system, serving, embedding

#8571 Stream wait
  oneflow/core/common/env_var/vm.h
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/framework/instructions_builder.h
  oneflow/core/framework/stream_support_stream_wait.h
  oneflow/core/vm/instruction.cpp
  oneflow/core/vm/instruction_policy.h
  oneflow/core/vm/stream_wait_instruction_policy.cpp
  oneflow/core/vm/stream_wait_instruction_policy.h
  oneflow/core/vm/virtual_machine_engine.cpp
  python/oneflow/nn/parallel/ddp.py
Labels: enhancement, automerge, system

#8738 Bump nccl up to 2.13.4
  cmake/third_party/nccl.cmake
Labels: enhancement, automerge, system

#8762 modify reduce_like_ops.cpp and broadcast_like_op.cpp
  oneflow/user/ops/broadcast_like_op.cpp
  oneflow/user/ops/reduce_like_ops.cpp
  python/oneflow/test/modules/test_global_broadcase_like.py
Labels: enhancement, automerge, op, test, documentation

#8755 Refactor 1n1d sbp
  oneflow/core/operator/operator.cpp
  oneflow/core/operator/operator.h
  oneflow/core/operator/sink_tick_op.cpp
  oneflow/user/ops/flatten_op.cpp
  oneflow/user/ops/reduce_like_ops.cpp
  oneflow/user/ops/reshape_user_op_util.cpp
  python/oneflow/test/modules/test_global_slice.py
  python/oneflow/test/modules/test_global_slice_update.py
Labels: enhancement, automerge, test, refactor

#8788 Fix auto parallel copy cost infer2
  oneflow/core/auto_parallel/sbp_constructor.cpp
  oneflow/core/framework/sbp_infer_util.cpp
  oneflow/core/operator/operator.cpp
  oneflow/core/operator/operator.h
Labels: AutoParallel

#8849 Refactor prune identity as much as possible
  oneflow/core/job_rewriter/auto_parallel.cpp
Labels: AutoParallel

#8860 Prevent benchmark failure
  .github/workflows/test.yml
Labels: bug, ci

#8741 Feat support more tensor setitem
  oneflow/api/python/functional/indexing.cpp
  oneflow/core/common/tensor_meta.cpp
  oneflow/core/common/tensor_meta.h
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/core/functional/tensor_index.cpp
  oneflow/core/functional/tensor_index.h
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/nd_index_slice_kernels.cpp
  oneflow/user/kernels/nd_index_slice_kernels.cu
  oneflow/user/kernels/nd_index_slice_kernels.h
  oneflow/user/kernels/nd_index_slice_util.h
  oneflow/user/ops/nd_index_slice_ops.cpp
  python/oneflow/test/modules/test_slice.py
  python/oneflow/test/modules/test_tensor_scatter_nd_update.py
  python/oneflow/test/tensor/test_tensor_indexing.py
  python/oneflow/test/tensor/test_tensor_indexing2.py
  python/oneflow/test/tensor/test_tensor_part_1.py
Labels: enhancement, feature, automerge, eager

#8818 libai support bfloat16
  oneflow/core/common/data_type.h
  oneflow/core/cuda/atomic.cuh
  oneflow/core/job/job_conf.proto
  oneflow/core/job/job_desc.h
  oneflow/core/job_rewriter/auto_mixed_precision.cpp
  oneflow/core/job_rewriter/do_parallel_cast_before_widening_type_cast_pass.cpp
  oneflow/core/job_rewriter/fuse_cast_scale_pass.cpp
  oneflow/user/kernels/fused_bias_add_kernel.cu
  oneflow/user/kernels/fused_cast_scale_kernel.cu
  oneflow/user/kernels/gather_kernel.cpp
  oneflow/user/kernels/gather_kernel_util.cu
  oneflow/user/kernels/layer_norm_gpu_kernel.cu
  oneflow/user/kernels/reduce_kernel.cpp
  oneflow/user/kernels/reduce_like_kernels.cpp
  oneflow/user/kernels/slice_kernel.cpp
  oneflow/user/kernels/slice_util.cu
  oneflow/user/kernels/unsorted_segment_sum_kernel.cpp
  oneflow/user/kernels/unsorted_segment_sum_kernel_util.cu
  oneflow/user/ops/layer_norm_op.cpp
  python/oneflow/nn/graph/graph_config.py
Labels: enhancement, automerge, op

#8812 resnet50 support amp data_type bfloat16
  oneflow/core/device/cudnn_conv_util.cpp
  oneflow/core/device/cudnn_util.cpp
  oneflow/core/device/cudnn_util.h
  oneflow/core/job_rewriter/cudnn_fused_normalization_add_relu_pass.cpp
  oneflow/user/kernels/conv_cudnn_kernels.cpp
  oneflow/user/kernels/normalization_kernel.cu
  oneflow/user/kernels/tf_pool_gpu_kernel.cpp
  oneflow/user/ops/normalization_op.cpp
Labels: enhancement, automerge, system

#8851 fix wrong paths to keep for op repr locations
  oneflow/core/job/graph_scope_vars.cpp
Labels: automerge, bug, api, graph

#8823 Refactor ccl reduce and broadcast
  oneflow/api/python/rpc/ccl.cpp
  oneflow/core/autograd/gradient_funcs/eager_ccl_broadcast.cpp
  oneflow/core/boxing/asymmetric_broadcast.cpp
  oneflow/core/ccl/ccl.cpp
  oneflow/core/ccl/ccl.h
  oneflow/core/framework/op_interpreter/eager_local_op_interpreter.cpp
  oneflow/core/functional/impl/comm_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/collective_communication/cpu/cpu_broadcast.cpp
  oneflow/user/kernels/collective_communication/cpu/cpu_reduce.cpp
  oneflow/user/kernels/collective_communication/cuda/cuda_broadcast.cpp
  oneflow/user/kernels/collective_communication/cuda/cuda_communication_context.cpp
  oneflow/user/kernels/collective_communication/cuda/cuda_communication_context.h
  oneflow/user/kernels/collective_communication/cuda/cuda_reduce.cpp
  oneflow/user/kernels/collective_communication/include/broadcast.h
  oneflow/user/kernels/collective_communication/include/reduce.h
  oneflow/user/kernels/eager_ccl_kernel.cpp
  oneflow/user/kernels/eager_nccl_kernels.cpp
  oneflow/user/kernels/eager_nccl_kernels.cu
  oneflow/user/ops/eager_nccl_ops.cpp
Labels: enhancement, automerge, system

#8862 fix build for cuda_bf16
  oneflow/user/kernels/normalization_kernel.cu
Labels: bug, op

#8781 remove old serving code
  oneflow/core/serving/saved_model.proto
Labels: purge, automerge, serving

#8836 add module.requires_grad_ api
  docs/source/nn.rst
  python/oneflow/nn/module.py
Labels: enhancement, eager, api

#8863 register l2_normalize double dtype
  oneflow/user/kernels/l2_normalize_kernel.cpp
  oneflow/user/kernels/l2_normalize_kernel.cu
  python/oneflow/test/modules/test_normalize.py
Labels: enhancement, automerge, bug, eager, api

#8876 Fix auto parallel low throughput
  oneflow/core/auto_parallel/algorithm_util.h
  oneflow/core/auto_parallel/sbp_constructor.cpp
Labels: AutoParallel

#8824 Support parameter `p` for flow.bernoulli
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/random_functor.cpp
  oneflow/user/kernels/bernoulli_kernel.cpp
  python/oneflow/framework/docstr/random.py
  python/oneflow/test/modules/test_bernoulli.py
Labels: enhancement, api, python

#8879 Revert "Add clamp_min/max and inplace version functor"
  docs/source/oneflow.rst
  oneflow/api/python/framework/tensor_functions.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/math_functor.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/clamp.py
Labels: bug, ci

#8567 develop grad acc functional apis
  oneflow/api/python/functional/dispatch_stateful_ops.cpp
  oneflow/core/autograd/gradient_funcs/gradient_accumulation.cpp
  oneflow/core/framework/op_interpreter/lazy_op_interpreter.cpp
  oneflow/core/framework/op_interpreter/lazy_op_interpreter.h
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/gradient_accumulation_functor.cpp
Labels: enhancement, automerge, system, graph

#8875 fix gather not support negative axis
  oneflow/core/functional/impl/array_functor.cpp
  python/oneflow/test/modules/test_gather.py
Labels: enhancement, automerge, bug, eager, documentation, api

#8872 Fix not requires grad tensor inplace
  oneflow/api/python/autograd/autograd.cpp
  oneflow/core/framework/op_interpreter/op_interpreter.cpp
  python/oneflow/test/exceptions/test_autograd.py
  python/oneflow/test/modules/test_autograd.py
Labels: feature, automerge, bug, eager

#8861 Add empty like op
  docs/source/oneflow.rst
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/constant.py
  python/oneflow/nn/modules/empty.py
  python/oneflow/test/modules/test_empty.py
  python/oneflow/test/modules/test_global_empty.py
Labels: enhancement, automerge, bug, eager, documentation, api

#8887 Refactor auto parallel final check
  oneflow/core/auto_parallel/sbp_collector.cpp
  oneflow/core/auto_parallel/sbp_constructor.cpp
  oneflow/core/auto_parallel/sbp_edge.cpp
  oneflow/core/auto_parallel/sbp_graph.cpp
  oneflow/core/auto_parallel/sbp_node.cpp
  oneflow/core/auto_parallel/sbp_util.cpp
Labels: AutoParallel

#8878 Only initialize out_grads for those requires_grad outputs
  oneflow/core/autograd/autograd_engine.cpp
Labels: enhancement, automerge, system

#8809 Move copy h2d/d2h to user op
  .github/workflows/test.yml
  cmake/op_schema.cmake
  oneflow/core/graph/copy_task_node.cpp
  oneflow/core/graph/copy_task_node.h
  oneflow/core/graph/task_graph.cpp
  oneflow/core/kernel/copy_hd_kernel.cpp
  oneflow/core/lazy/actor/light_actor.cpp
  oneflow/core/operator/copy_hd_op.cpp
  oneflow/core/operator/op_conf.proto
  oneflow/core/operator/user_op.cpp
  oneflow/ir/include/OneFlow/CMakeLists.txt
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/ir/lib/OneFlow/CMakeLists.txt
  oneflow/ir/lib/OneFlow/OneFlowDialect.cpp
  oneflow/ir/oneflow-extension/extension.cpp
  oneflow/user/kernels/copy_hd_kernel.cpp
  oneflow/user/ops/copy_hd_op.cpp
  python/oneflow/nn/graph/graph.py
Labels: purge, automerge, system, need-all-tests-even-fail

#8897 Fix deadlock in instruction done
  oneflow/core/vm/instruction.cpp
  oneflow/core/vm/instruction.h
  oneflow/core/vm/virtual_machine_engine.cpp
Labels: bug, system, need-highest-priority

#8892 refine usage of maybe_wrap_dim
  oneflow/core/framework/tensor_methods.cpp
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/core/functional/impl/math_functor.cpp
Labels: enhancement, automerge, bug, eager

#8899 fix nn.init.constant_
  oneflow/api/python/utils/tensor_utils.h
  python/oneflow/nn/init.py
Labels: enhancement, automerge, bug, eager

#8900 infer output stride in lazy mode for the ops which do not support non…
  oneflow/core/operator/operator.cpp
  oneflow/core/operator/user_op.cpp
  oneflow/user/kernels/slice_kernel.cpp
Labels: automerge, bug, system, graph

#8575 Fix set_acc_grad and backward wrong value
  oneflow/core/framework/tensor.h
  python/oneflow/test/modules/test_autograd.py
Labels: automerge, bug, eager

#8902 fix bug in cosine_similarity when inputs have different dims
  oneflow/core/functional/impl/nn_functor.cpp
  python/oneflow/test/modules/test_cosine_similarity.py
Labels: enhancement, automerge, bug, op

#8895 register reduce_sum_like backward function and add testcase
  oneflow/core/autograd/gradient_funcs/reduce_sum_like.cpp
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  python/oneflow/test/modules/test_reduce_sum_like.py
Labels: enhancement, automerge, op, test

#8867 support non contiguous inplace
  oneflow/core/functional/tensor_processor.cpp
  oneflow/core/functional/tensor_processor.h
  python/oneflow/test/modules/test_add.py
  python/oneflow/test/modules/test_div.py
  python/oneflow/test/modules/test_mul.py
  python/oneflow/test/modules/test_sub.py
Labels: enhancement, automerge, system

#8885 Default no vm sync in clip grad
  python/oneflow/nn/optimizer/optimizer.py
Labels: enhancement, automerge, bug, api, python

#8882 Add clamp_min/max and inplace version functor
  docs/source/oneflow.rst
  oneflow/api/python/framework/tensor_functions.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/math_functor.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/clamp.py
  python/oneflow/test/modules/test_clamp.py
  python/oneflow/test/tensor/test_tensor_part_2.py
Labels: enhancement, automerge, api, python

#8844 Add double grad for broadcast_matmul_grad_b op
  oneflow/core/autograd/higher_order_gradient_funcs/conv.cpp
  oneflow/core/autograd/higher_order_gradient_funcs/matmul.cpp
  python/oneflow/test/modules/test_global_higher_derivative_conv.py
  python/oneflow/test/modules/test_global_higher_derivative_matmul.py
  python/oneflow/test/modules/test_higher_derivative_conv.py
  python/oneflow/test/modules/test_higher_derivative_matmul.py
Labels: enhancement, automerge, op, test

#8907 Fix non-contiguous tensor initialize functions
  python/oneflow/nn/init.py
  python/oneflow/test/tensor/test_tensor_part_1.py
Labels: automerge, bug, eager

#8908 Add pairwise_distance api
  docs/source/nn.functional.rst
  docs/source/nn.rst
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  python/oneflow/framework/docstr/distance.py
  python/oneflow/nn/__init__.py
  python/oneflow/nn/functional/__init__.py
  python/oneflow/nn/modules/distance.py
  python/oneflow/test/modules/test_pairwise_distance.py
Labels: enhancement, automerge, documentation, api, python

#8894 Add error msg for local/global mismatch when loading state_dict
  python/oneflow/nn/module.py
Labels: enhancement, automerge, documentation, python

#8183 Dev linalg inv
  cmake/op_schema.cmake
  docs/source/linalg.rst
  oneflow/core/autograd/gradient_funcs/inv.cpp
  oneflow/core/common/blas.h
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/ir/include/OneFlow/CMakeLists.txt
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/ir/lib/OneFlow/CMakeLists.txt
  oneflow/ir/lib/OneFlow/OneFlowDialect.cpp
  oneflow/user/kernels/inv_kernels.cpp
  oneflow/user/kernels/inv_kernels.cu
  oneflow/user/ops/inv_op.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/__init__.py
  python/oneflow/framework/docstr/inv.py
  python/oneflow/framework/tensor.py
  python/oneflow/linalg.py
  python/oneflow/test/exceptions/test_inv.py
  python/oneflow/test/modules/test_consistent_inv.py
  python/oneflow/test/modules/test_inv.py
Labels: feature, automerge, eager, op, api, need-clean-ccache

#8884 add mse_loss and ls_loss interface
  docs/source/nn.functional.rst
  oneflow/core/functional/functional_api.yaml
  python/oneflow/framework/docstr/loss.py
  python/oneflow/nn/functional/__init__.py
  python/oneflow/test/modules/test_loss.py
Labels: automerge, documentation, api, python

#8886 modify setitem to support scalar tensor
  oneflow/api/python/framework/tensor_functions.cpp
  oneflow/core/functional/impl/array_functor.cpp
  python/oneflow/test/tensor/test_tensor_indexing2.py
Labels: enhancement, automerge, op, documentation, build

#8870 Migrate MLIR JIT Op to User Op TableGen
  cmake/oneflow.cmake
  cmake/op_schema.cmake
  oneflow/ir/include/OneFlow/CMakeLists.txt
  oneflow/ir/include/OneFlow/Conversion/OneFlowToTosa.h
  oneflow/ir/include/OneFlow/OneFlowOps.td
  oneflow/ir/include/OneFlow/OneFlowSupport.h
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/ir/lib/OneFlow/CMakeLists.txt
  oneflow/ir/lib/OneFlow/Conversion/OneFlowToTosa.cpp
  oneflow/ir/lib/OneFlow/OneFlowDialect.cpp
  oneflow/ir/lib/OneFlow/OneFlowSupport.cpp
  oneflow/ir/lib/OneFlow/Passes.cpp
  oneflow/ir/oneflow-extension/CMakeLists.txt
  oneflow/ir/oneflow-extension/extension.cpp
  oneflow/ir/oneflow-extension/mlir_jit_op.cpp
  oneflow/ir/oneflow-opt/oneflow-opt.cpp
  oneflow/ir/oneflow-translate/lib/OneFlow/Importer.cpp
  oneflow/ir/oneflow-translate/lib/OneFlow/MLIROneFlowTranslation.cpp
  oneflow/ir/test/OneFlow/lower_to_tosa_signed.mlir
  tools/oneflow-tblgen/op_schema_emitter.cpp
Labels: enhancement, need-all-tests-even-fail, ir

#8925 fix amp pass
  oneflow/core/job_rewriter/auto_mixed_precision.cpp
  oneflow/user/kernels/nd_index_slice_kernels.cu
Labels: automerge, bug, system, graph

#8927 Fix stack bug for 129inputs
  oneflow/core/functional/impl/array_functor.cpp
  python/oneflow/test/modules/test_stack.py
Labels: automerge, bug, eager

#8923 support tosa make broadcastable pass
  oneflow/ir/lib/OneFlow/Conversion/OneFlowToTosa.cpp
  oneflow/ir/lib/OneFlow/Passes.cpp
  oneflow/ir/oneflow-translate/lib/OneFlow/MLIROneFlowTranslation.cpp
  oneflow/ir/test/Frontend/OneFlowToIree.mlir
  oneflow/ir/test/OneFlow/cuda_code_gen/fuse_cast_scale.mlir
  oneflow/ir/test/OneFlow/cuda_code_gen/gpu_copy_arg.mlir
  oneflow/ir/test/OneFlow/lower_to_tosa.mlir
  oneflow/ir/test/OneFlow/lower_to_tosa_signed.mlir
Labels: feature, automerge, need-all-tests-even-fail, ir

#8929 Fix cumprod grad get sbp
  oneflow/user/ops/cum_ops.cpp
  python/oneflow/test/modules/test_global_cumprod.py
Labels: automerge, bug, op

#8939 Fix get sbp bug
  oneflow/core/operator/user_op.cpp
  oneflow/user/ops/coco_reader_op.cpp
  oneflow/user/ops/distributions/uniform_op.cpp
  oneflow/user/ops/ofrecord_image_classification_reader_op.cpp
  oneflow/user/ops/ofrecord_reader_op.cpp
  oneflow/user/ops/onerec_reader_op.cpp
  oneflow/user/ops/raw_reader_op.cpp
Labels: bug, op, AutoParallel

#8909 add double grad for activation
  oneflow/core/autograd/higher_order_gradient_funcs/activation.cpp
  oneflow/core/autograd/higher_order_gradient_funcs/leaky_relu.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/activation_functor.cpp
  oneflow/core/functional/impl/higher_derivative_functor.cpp
  python/oneflow/test/modules/test_global_higher_derivative_activation.py
  python/oneflow/test/modules/test_global_higher_derivative_leaky_relu.py
  python/oneflow/test/modules/test_higher_derivative_activation.py
  python/oneflow/test/modules/test_higher_derivative_leaky_relu.py
Labels: enhancement, automerge, op, test

#8962 nccl logical kernels support nv_bfloat16
  oneflow/user/kernels/nccl_logical_2d_sbp_kernels.cpp
  oneflow/user/kernels/nccl_logical_kernels.cpp
Labels: enhancement, automerge, op

#8922 align repr of nn.Embedding
  python/oneflow/nn/modules/sparse.py
Labels: enhancement, automerge, eager, api

#8932 replace xor with HashCombine
  oneflow/core/boxing/boxing_interpreter_status.h
  oneflow/core/common/error.h
  oneflow/core/common/hash.h
  oneflow/core/common/protobuf.h
  oneflow/core/common/tensor_meta.cpp
  oneflow/core/common/util.h
  oneflow/core/framework/attr_map.cpp
  oneflow/core/framework/device.cpp
  oneflow/core/framework/global_tensor_infer_cache.cpp
  oneflow/core/framework/stream.h
  oneflow/core/graph/task_graph.h
  oneflow/core/job/parallel_desc.h
  oneflow/core/job/placement_scope.h
  oneflow/core/job_rewriter/adam_optm.cpp
  oneflow/core/job_rewriter/lamb_optm.cpp
  oneflow/core/operator/op_infer_cache.h
Labels: enhancement, bug, system, need-highest-priority

#8960 fix docstring of oneflow.pow
  python/oneflow/framework/docstr/math_ops.py
Labels: automerge, documentation, build, api

#8948 Support empty ndim advancedindexing
  oneflow/api/python/functional/indexing.cpp
  oneflow/user/ops/nd_index_slice_ops.cpp
  python/oneflow/test/tensor/test_tensor_indexing2.py
Labels: enhancement, automerge, op, documentation, build

#8956 Fix bug when retain_grad for leaf_tensor
  oneflow/api/python/framework/tensor.cpp
  python/oneflow/test/modules/test_autograd.py
Labels: automerge, bug, system

#8953 support throttle to fix ninja c1 oom
  dev-requirements.txt
  oneflow/ir/test/OneFlow/auto_nhwc/test_nhwc_batchnorm_relu.py
  oneflow/ir/test/OneFlow/auto_nhwc/test_nhwc_bias_add.py
  oneflow/ir/test/OneFlow/auto_nhwc/test_nhwc_conv.py
  oneflow/ir/test/OneFlow/auto_nhwc/test_nhwc_conv2d_maxpool2d.py
  oneflow/ir/test/OneFlow/auto_nhwc/test_nhwc_conv_relu_add.py
  oneflow/ir/test/OneFlow/auto_nhwc/test_nhwc_lenet.py
  oneflow/ir/test/OneFlow/auto_nhwc/test_nhwc_maxpool_2d.py
  oneflow/ir/test/OneFlow/auto_nhwc/test_nhwc_resnet.py
  oneflow/ir/test/OneFlow/auto_nhwc/test_nhwc_transpose_eliminate.py
  oneflow/ir/test/OneFlow/auto_nhwc/test_resnet101_benchmark.py
  oneflow/ir/test/OneFlow/cuda_code_gen/test_fuser_cast_scale.py
  oneflow/ir/test/OneFlow/folding/test_simple_multiply.py
  oneflow/ir/test/OneFlow/test_fuse_pad_conv.py
  oneflow/ir/test/OneFlow/with_cuda/test_conv_bn_auto_nhwc.py
  oneflow/ir/test/lit.cfg.py
  python/oneflow/test_utils/throttle.py
Labels: feature, automerge, test, need-all-tests-even-fail

#8973 Add relative threshold while testing inversing
  python/oneflow/test/modules/test_inv.py
Labels: bug, ci

#8877 add double grad for div
  oneflow/core/autograd/higher_order_gradient_funcs/div.cpp
  oneflow/core/functional/functional_api.yaml
  python/oneflow/test/modules/test_global_higher_derivative_div.py
  python/oneflow/test/modules/test_higher_derivative_div.py
Labels: enhancement, automerge, op, test

#8941 Dev fix bug of linespace
  python/oneflow/nn/modules/linspace.py
  python/oneflow/test/modules/test_linspace.py
Labels: enhancement, automerge, bug, eager

#8919 Split axis according to grouped axises
  oneflow/user/ops/reshape_user_op_util.cpp
  python/oneflow/test/modules/test_reshape_sbp.py
Labels: automerge, bug, eager, graph

#8901 Add stack series api
  docs/source/oneflow.rst
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/array_functor.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/array_ops.py
  python/oneflow/test/modules/test_atleast.py
  python/oneflow/test/modules/test_global_atleast.py
  python/oneflow/test/modules/test_stack.py
Labels: enhancement, automerge, documentation, api, python

#8963 fix requires_grad check and precison in higher derivative
  oneflow/core/autograd/higher_order_gradient_funcs/activation.cpp
  python/oneflow/test/modules/test_global_higher_derivative_div.py
  python/oneflow/test/modules/test_higher_derivative_div.py
Labels: automerge, bug, op

#8889 Lx add profile
  docs/source/autograd.rst
  docs/source/cuda.rst
  docs/source/nn.rst
  docs/source/oneflow.rst
  docs/source/tensor.rst
  python/oneflow/test/README.md
  python/oneflow/test/gen_ops_process.py
  python/oneflow/test/modules/test_abs.py
  python/oneflow/test/modules/test_activation.py
  python/oneflow/test/modules/test_adaptive_pool.py
  python/oneflow/test/modules/test_add.py
  python/oneflow/test/modules/test_addcdiv.py
  python/oneflow/test/modules/test_addcmul.py
  python/oneflow/test/modules/test_addmm.py
  python/oneflow/test/modules/test_affine_grid.py
  python/oneflow/test/modules/test_amax.py
  python/oneflow/test/modules/test_amin.py
  python/oneflow/test/modules/test_arange.py
  python/oneflow/test/modules/test_argsort.py
Labels: enhancement, automerge, bug, op, documentation

#8880 Add dropout1d/2d/3d api
  docs/source/nn.functional.rst
  docs/source/nn.rst
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/core/functional/impl/random_functor.cpp
  python/oneflow/framework/docstr/dropout.py
  python/oneflow/nn/__init__.py
  python/oneflow/nn/functional/__init__.py
  python/oneflow/nn/modules/dropout.py
  python/oneflow/test/modules/test_dropout.py
Labels: enhancement, automerge, bug, eager, documentation, api

#8924 Fix scalar logical equal of bool
  oneflow/core/functional/impl/math_functor.cpp
  python/oneflow/test/tensor/test_tensor_part_2.py
Labels: enhancement, automerge, eager, api

#8968 Refine elementwise.cuh
  oneflow/core/cuda/elementwise.cuh
Labels: automerge, bug, system

#8950 Add lib path for KINETO
  external/kineto/CMakeLists.txt
Labels: enhancement, automerge, build

#8938 support tensor indexer with negative
  oneflow/user/kernels/nd_index_slice_util.h
  python/oneflow/test/tensor/test_tensor_indexing2.py
Labels: enhancement, automerge, op, test

#8930 Fix bug of scalar tensor device in binary ops
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/core/functional/impl/binary_functor.cpp
  oneflow/core/functional/impl/binary_functor.h
  oneflow/core/functional/impl/common.cpp
  oneflow/core/functional/impl/common.h
  python/oneflow/test/modules/test_add.py
  python/oneflow/test/modules/test_div.py
  python/oneflow/test/modules/test_math_ops.py
  python/oneflow/test/modules/test_mul.py
  python/oneflow/test/modules/test_sub.py
Labels: enhancement, automerge, bug, eager

#8921 batchnorm cudnn fall back to CUDNN_BATCHNORM_SPATIAL
  oneflow/user/kernels/normalization_kernel.cu
Labels: automerge, bug, WIP, op, test

#8983 move_storage_offset_to_tensor_impl
  oneflow/api/python/functional/tensor_api.cpp
  oneflow/core/common/env_var/eager.h
  oneflow/core/common/tensor_meta.cpp
  oneflow/core/common/tensor_meta.h
  oneflow/core/framework/global_tensor_infer_cache.cpp
  oneflow/core/framework/local_tensor_infer_cache.cpp
  oneflow/core/framework/op_interpreter/eager_local_op_interpreter.cpp
  oneflow/core/framework/tensor_impl.cpp
  oneflow/core/framework/tensor_impl.h
  oneflow/core/framework/tensor_methods.cpp
  oneflow/core/functional/impl/array_functor.cpp
Labels: enhancement, automerge, system

#8981 Support partial requires_grad inputs
  oneflow/api/python/autograd/autograd_function.cpp
  oneflow/core/framework/op_expr.cpp
  oneflow/core/framework/op_expr_grad_function.h
  python/oneflow/test/modules/test_autograd_function.py
Labels: enhancement, automerge, bug, op

#8928 Support scalar tensor indexed with scalar number
  oneflow/user/kernels/slice_kernel.cpp
  python/oneflow/test/tensor/test_tensor_indexing2.py
Labels: enhancement, automerge, op, test, documentation

#8970 fix scalar tensor.mean
  oneflow/core/common/wrap_dim_utils.h
  oneflow/core/functional/impl/common.cpp
  python/oneflow/test/modules/test_mean.py
Labels: enhancement, automerge, bug, eager

#8947 one_embedding export constant_initializer
  python/oneflow/one_embedding.py
Labels: enhancement, automerge, op

#8954 Profile test
  python/oneflow/test/README.md
  python/oneflow/test/modules/test_argwhere.py
  python/oneflow/test/modules/test_as_stride.py
  python/oneflow/test/modules/test_batchnorm.py
  python/oneflow/test/modules/test_bernoulli.py
  python/oneflow/test/modules/test_bmm.py
  python/oneflow/test/modules/test_ceil.py
  python/oneflow/test/modules/test_chunk.py
  python/oneflow/test/modules/test_clamp.py
  python/oneflow/test/modules/test_concat.py
  python/oneflow/test/modules/test_constant.py
  python/oneflow/test/modules/test_constant_pad.py
  python/oneflow/test/modules/test_contiguous.py
  python/oneflow/test/modules/test_conv1d.py
  python/oneflow/test/modules/test_conv2d.py
Labels: enhancement, automerge, op, documentation

#8993 one_embedding save param in state_dict
  python/oneflow/one_embedding.py
Labels: automerge, bug, op

#8994 Support reshape_like grad
  oneflow/core/autograd/gradient_funcs/reshape.cpp
  python/oneflow/test/modules/test_reshape.py
Labels: feature, automerge, op

#8990 add higher order derivative for scalar_pow
  oneflow/core/autograd/gradient_funcs/scalar_pow.cpp
  oneflow/core/autograd/higher_order_gradient_funcs/scalar_pow.cpp
  oneflow/core/common/scalar.cpp
  oneflow/core/common/scalar.h
  python/oneflow/test/modules/test_global_higher_derivative_scalar_pow.py
  python/oneflow/test/modules/test_higher_derivative_scalar_pow.py
Labels: enhancement, automerge, op, test

#8934 Fix 0size tensor getitem kernel bug
  oneflow/user/kernels/nd_index_slice_kernels.h
  python/oneflow/test/tensor/test_tensor_indexing2.py
Labels: automerge, bug, op

#9001 add static Maybe<OpCallInstructionPolicy> New(Args&&... args)
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/vm/op_call_instruction_policy.cpp
  oneflow/core/vm/op_call_instruction_policy.h
Labels: enhancement, automerge, system, refactor

#8854 Implement sync batchnorm
  .github/workflows/test.yml
  ci/test/test_sync_batchnorm.sh
  oneflow/core/framework/op_expr_grad_function.h
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/batch_norm_backward_elemt_kernel.cu
  oneflow/user/kernels/batch_norm_backward_reduce_kernel.cu
  oneflow/user/kernels/batch_norm_elemt_kernel.cu
  oneflow/user/kernels/batch_norm_gather_stats_with_counts_kernel.cu
  oneflow/user/kernels/batch_norm_kernel_utils.h
  oneflow/user/kernels/batch_norm_stats_kernel.cu
  oneflow/user/ops/batch_norm_backward_elemt_op.cpp
  oneflow/user/ops/batch_norm_backward_reduce_op.cpp
  oneflow/user/ops/batch_norm_elemt_op.cpp
  oneflow/user/ops/batch_norm_gather_stats_with_counts_op.cpp
  oneflow/user/ops/batch_norm_stats_op.cpp
  python/oneflow/nn/__init__.py
  python/oneflow/nn/modules/batchnorm.py
  python/oneflow/test/ddp/test_sync_batchnorm.py
  python/oneflow/test/ddp/test_sync_batchnorm_nhwc.py
  tools/check_src.py
Labels: enhancement, feature, automerge, eager, op, api

#8944 Refine check failed msg
  oneflow/core/common/error.h
  oneflow/core/common/maybe.h
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/user/ops/affine_grid_op.cpp
  oneflow/user/ops/stack_op.cpp
Labels: automerge, bug, system

#8982 create stream on main thread
  oneflow/core/vm/virtual_machine.cpp
Labels: enhancement, automerge, system

#7266 Numeric limits support half
  oneflow/core/kernel/util/numeric_limits.cuh
  oneflow/core/kernel/util/numerics.cuh
  oneflow/user/kernels/max_pool_kernel.cpp
  oneflow/user/kernels/max_pool_kernel_util.h
  python/oneflow/test/modules/test_maxpool.py
Labels: enhancement, automerge, op, refactor

#8905 Refine GroupNorm
  python/oneflow/nn/modules/normalization.py
Labels: enhancement, automerge, op

#9007 remove EagerKernel
  oneflow/core/kernel/eager_kernel.h
  oneflow/core/kernel/user_kernel.cpp
  oneflow/core/kernel/user_kernel.h
Labels: enhancement, automerge, eager, refactor

#8943 develop cached mutable attr map
  oneflow/api/python/functional/dispatch_stateful_ops.cpp
  oneflow/core/autograd/gradient_funcs/dim_scatter.cpp
  oneflow/core/autograd/gradient_funcs/expand.cpp
  oneflow/core/autograd/gradient_funcs/global_cast.cpp
  oneflow/core/autograd/gradient_funcs/upsample.cpp
  oneflow/core/common/small_vector.h
  oneflow/core/framework/attr_map.cpp
  oneflow/core/framework/attr_map.h
  oneflow/core/framework/attr_map_test.cpp
  oneflow/core/framework/attr_value.h
  oneflow/core/framework/mutable_attr_map.h
  oneflow/core/framework/op_attrs.cpp
  oneflow/core/framework/op_attrs.h
  oneflow/core/framework/op_definition.h
  oneflow/core/framework/op_interp_ctx.cpp
  oneflow/core/framework/op_interp_ctx.h
  oneflow/core/framework/op_interpreter/eager_local_op_interpreter.cpp
  oneflow/core/framework/ordered_string_list.h
  oneflow/core/framework/system_ops.cpp
  oneflow/core/framework/system_ops.h
  oneflow/core/framework/user_op_conf.h
  oneflow/core/functional/impl/activation_functor.cpp
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/core/functional/impl/comm_functor.cpp
  oneflow/core/functional/impl/dataset_functor.cpp
  oneflow/core/functional/impl/eye_functor.cpp
  oneflow/core/functional/impl/global_cast.cpp
  oneflow/core/functional/impl/gradient_accumulation_functor.cpp
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/core/functional/impl/nn_grad_functor.cpp
  oneflow/core/functional/impl/quantization.cpp
  oneflow/core/functional/impl/random_functor.cpp
  oneflow/core/functional/tensor_index.cpp
  oneflow/core/job/placement_scope.h
  tools/oneflow-tblgen/op_schema_header.inc
  tools/oneflow-tblgen/op_schema_source.inc
Labels: enhancement, automerge, op

#9004 fix ctc loss not support global when zero_infinity set to true
  oneflow/core/functional/impl/nn_functor.cpp
  python/oneflow/test/modules/test_global_ctc_loss.py
Labels: enhancement, automerge, bug, op

#8936 Restruct Math Elementwise Kernel
  oneflow/core/autograd/gradient_funcs/math_unary_op.cpp
  oneflow/core/autograd/higher_order_gradient_funcs/math_unary_op.cpp
  oneflow/core/ep/common/primitive/binary_functor.h
  oneflow/core/ep/common/primitive/broadcast_elementwise_binary.h
  oneflow/core/ep/common/primitive/elementwise_unary.h
  oneflow/core/ep/common/primitive/unary_functor.h
  oneflow/core/ep/cpu/primitive/binary_functor.h
  oneflow/core/ep/cpu/primitive/broadcast_elementwise_binary.cpp
  oneflow/core/ep/cpu/primitive/elementwise_unary.cpp
  oneflow/core/ep/cpu/primitive/type_seq.h
  oneflow/core/ep/cpu/primitive/unary_functor.h
  oneflow/core/ep/cuda/primitive/binary_functor.cuh
  oneflow/core/ep/cuda/primitive/broadcast_elementwise_binary.cu
  oneflow/core/ep/cuda/primitive/elementwise_unary.cu
  oneflow/core/ep/cuda/primitive/math_elementwise_unary_math_grad.cu
  oneflow/core/ep/cuda/primitive/type_seq.h
  oneflow/core/ep/cuda/primitive/unary_functor.cuh
  oneflow/core/ep/include/primitive/binary_op.h
  oneflow/core/ep/include/primitive/unary_op.h
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/higher_derivative_functor.cpp
  oneflow/core/functional/impl/unary_functor.cpp
  oneflow/core/job_rewriter/auto_mixed_precision_lists.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/math_unary_elementwise_kernel.cpp
  oneflow/user/kernels/math_unary_elementwise_kernel.cu
  oneflow/user/kernels/math_unary_elementwise_primitive_kernel.cpp
  oneflow/user/ops/math_unary_elementwise_op.cpp
  oneflow/user/ops/math_unary_elementwise_seq.h
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/math_ops.py
  python/oneflow/test/modules/test_arange.py
  python/oneflow/test/modules/test_global_higher_derivative_neg.py
  python/oneflow/test/modules/test_math_ops.py
Labels: enhancement, automerge, op, primitive

#9010 fix one_embedding _save_to_state_dict param
  python/oneflow/one_embedding.py
Labels: bug, op

#9011 Fix PrunePinnedIdentityOpPass is_train
  oneflow/core/ep/cuda/primitive/unary_functor.cuh
  oneflow/core/job_rewriter/prune_pinned_identity_op_pass.cpp
Labels: automerge, bug, system

#8989 add oneflow.trunc op
  docs/source/oneflow.rst
  docs/source/tensor.rst
  oneflow/core/autograd/gradient_funcs/trunc.cpp
  oneflow/core/ep/common/primitive/elementwise_unary.h
  oneflow/core/ep/common/primitive/unary_functor.h
  oneflow/core/ep/cpu/primitive/unary_functor.h
  oneflow/core/ep/cuda/primitive/unary_functor.cuh
  oneflow/core/ep/include/primitive/unary_op.h
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/activation_kernels.cpp
  oneflow/user/ops/trunc_op.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/math_ops.py
  python/oneflow/framework/tensor.py
  python/oneflow/test/modules/test_trunc.py
Labels: enhancement, op, documentation

#9006 nn.Linear_align_dtype_device_params
  python/oneflow/nn/modules/linear.py
  python/oneflow/test/modules/test_linear.py
Labels: bug, eager, api

#9009 Recompute cost with time shape
  oneflow/core/auto_parallel/sbp_constructor.cpp
  oneflow/core/auto_parallel/sbp_edge.cpp
Labels: AutoParallel

#9012 Add performance test for OP
  python/oneflow/test/README.md
  python/oneflow/test/modules/test_cosine_similarity.py
  python/oneflow/test/modules/test_cum_ops.py
  python/oneflow/test/modules/test_deconv2d.py
  python/oneflow/test/modules/test_diag.py
  python/oneflow/test/modules/test_diagonal.py
  python/oneflow/test/modules/test_div.py
  python/oneflow/test/modules/test_dot.py
  python/oneflow/test/modules/test_dropout.py
  python/oneflow/test/modules/test_eq.py
  python/oneflow/test/modules/test_erf.py
  python/oneflow/test/modules/test_erfc.py
  python/oneflow/test/modules/test_erfinv.py
  python/oneflow/test/modules/test_expm1.py
  python/oneflow/test/modules/test_eye.py
  python/oneflow/test/modules/test_flatten.py
  python/oneflow/test/modules/test_flip.py
  python/oneflow/test/modules/test_floor.py
  python/oneflow/test/modules/test_fmod.py
  python/oneflow/test/modules/test_fold.py
  python/oneflow/test/modules/test_gather.py
  python/oneflow/test/modules/test_glu.py
  python/oneflow/test/modules/test_greater.py
  python/oneflow/test/modules/test_grid_sample.py
  python/oneflow/test/modules/test_hann_window.py
Labels: enhancement, automerge, op, documentation

#8866 flow.tmp_compute_stream
  oneflow/api/python/framework/stream.cpp
  oneflow/core/autograd/autograd_engine.cpp
  oneflow/core/common/env_var/stream.h
  oneflow/core/common/stream_type.h
  oneflow/core/common/thread_local_guard.h
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/framework/stream.cpp
  oneflow/core/framework/stream.h
  oneflow/core/framework/stream_allocator_is_pinned.h
  oneflow/core/framework/stream_get_stream_type_name.h
  oneflow/core/framework/stream_guard.h
  oneflow/core/framework/stream_is_comm_net_stream.h
  oneflow/core/framework/stream_need_soft_sync.h
  oneflow/core/framework/stream_on_independent_thread.h
  oneflow/core/framework/stream_set.cpp
  oneflow/core/framework/stream_set.h
  oneflow/core/framework/stream_support_stream_wait.h
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/core/thread/thread_global_id.cpp
  oneflow/core/thread/thread_global_id.h
  oneflow/core/vm/ep_record_event_instruction_policy.h
  oneflow/core/vm/release_tensor_instruction_policy.h
  oneflow/core/vm/stream_get_stream_policy.h
  oneflow/core/vm/virtual_machine.cpp
  oneflow/core/vm/virtual_machine.h
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/ops/copy_op.cpp
  python/oneflow/__init__.py
  python/oneflow/asyncs/__init__.py
  python/oneflow/asyncs/thread.py
  python/oneflow/experimental/__init__.py
  python/oneflow/test/modules/test_asyncs_thread.py
Labels: enhancement, system

#8843 support autograd function in graph
  oneflow/core/framework/op_interpreter/lazy_op_interpreter.cpp
  python/oneflow/test/modules/test_autograd_function.py
Labels: feature, automerge, graph

#9003 optimize mutable attr map and pybind type check and cast
  oneflow/api/python/functional/common.cpp
  oneflow/api/python/functional/common.h
  oneflow/api/python/functional/dispatch_stateful_ops.cpp
  oneflow/api/python/functional/python_arg.cpp
  oneflow/api/python/functional/python_arg.h
  oneflow/api/python/functional/python_arg_parser.cpp
  oneflow/core/autograd/gradient_funcs/global_cast.cpp
  oneflow/core/framework/attr_map.cpp
  oneflow/core/framework/attr_map_test.cpp
  oneflow/core/framework/attr_value.h
  oneflow/core/framework/attr_value_accessor.cpp
  oneflow/core/framework/attr_value_accessor.h
  oneflow/core/framework/device.cpp
  oneflow/core/framework/device.h
  oneflow/core/framework/infer_util.h
  oneflow/core/framework/mutable_attr_map.h
  oneflow/core/framework/op_builder.cpp
  oneflow/core/framework/op_interpreter/eager_local_op_interpreter.cpp
  oneflow/core/framework/op_kernel.h
  oneflow/core/framework/user_op_conf.cpp
  oneflow/core/framework/user_op_def.cpp
  oneflow/core/functional/impl/activation_functor.cpp
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/core/functional/impl/comm_functor.cpp
  oneflow/core/functional/impl/dataset_functor.cpp
  oneflow/core/functional/impl/eye_functor.cpp
  oneflow/core/functional/impl/global_cast.cpp
  oneflow/core/functional/impl/gradient_accumulation_functor.cpp
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/core/functional/impl/nn_grad_functor.cpp
  oneflow/core/functional/impl/quantization.cpp
  oneflow/core/functional/impl/random_functor.cpp
  oneflow/core/job/scope.h
Labels: enhancement, op

#9027 Larger timeout for exe tests
  .github/workflows/test.yml
Labels: enhancement, automerge, ci

#9020 Tensor processor support promote integer inputs to float dtype
  oneflow/core/framework/dtype.cpp
  oneflow/core/framework/dtype.h
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/core/functional/impl/unary_functor.h
  oneflow/core/functional/tensor_processor.cpp
  oneflow/core/functional/tensor_processor.h
  python/oneflow/test/modules/test_activation.py
Labels: enhancement, bug, eager

#9029 enable sync vm mode for lazy kernel
  oneflow/core/kernel/kernel.cpp
Labels: automerge, bug, system

#9026 Dev refine cast error msg
  oneflow/api/python/functional/common.cpp
  oneflow/core/functional/impl/array_functor.cpp
Labels: enhancement, automerge, python

#8959 Add label smoothing in functor
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  python/oneflow/framework/docstr/loss.py
  python/oneflow/nn/modules/loss.py
  python/oneflow/test/modules/test_loss.py
Labels: enhancement, automerge, documentation, api, python
