Repository Oneflow-Inc/oneflow, pull requests merged in 2022-02, with the labels that each got.

#7420 Run wait gpu on gh-hosted
  .github/workflows/test.yml
Labels: enhancement, automerge, ci

#7388 add eager test case, 1card/2card successful
  python/oneflow/test/modules/test_consistent_diag.py
  python/oneflow/test/modules/test_consistent_div.py
  python/oneflow/test/modules/test_consistent_dot.py
  python/oneflow/test/modules/test_consistent_eq.py
  python/oneflow/test/modules/test_consistent_erf.py
  python/oneflow/test/modules/test_consistent_expm1.py
  python/oneflow/test/modules/test_consistent_flatten.py
  python/oneflow/test/modules/test_consistent_floor.py
  python/oneflow/test/modules/test_consistent_fmod.py
  python/oneflow/test/modules/test_consistent_greater_equal.py
Labels: enhancement, feature, automerge, eager

#7423 Distributed run timeout 15 -> 30
  .github/workflows/test.yml
Labels: enhancement, automerge, ci

#7433 Revert "add eager test case, 1card/2card successful (#7388)"
  .github/workflows/test.yml
  python/oneflow/test/modules/test_consistent_diag.py
  python/oneflow/test/modules/test_consistent_div.py
  python/oneflow/test/modules/test_consistent_dot.py
  python/oneflow/test/modules/test_consistent_eq.py
  python/oneflow/test/modules/test_consistent_erf.py
  python/oneflow/test/modules/test_consistent_expm1.py
  python/oneflow/test/modules/test_consistent_flatten.py
  python/oneflow/test/modules/test_consistent_floor.py
  python/oneflow/test/modules/test_consistent_fmod.py
  python/oneflow/test/modules/test_consistent_greater.py
  python/oneflow/test/modules/test_consistent_greater_equal.py
Labels: enhancement, automerge, ci

#7430 delete shared_memory.cpp useless include
  oneflow/api/python/multiprocessing/shared_memory.cpp
Labels: enhancement, feature, automerge, bug, ci, api

#7381 Optimize UnsortedSegmentSum CUDA Kernel
  oneflow/core/cuda/atomic.cuh
  oneflow/user/kernels/unsorted_segment_sum_kernel_util.cu
Labels: enhancement, automerge, op, need-clean-ccache

#7399 Fuse instruction
  oneflow/core/eager/cpu_opkernel_instruction_type.cpp
  oneflow/core/eager/critical_section_stream_type.h
  oneflow/core/eager/cuda_blob_instruction_type.cpp
  oneflow/core/eager/cuda_opkernel_instruction_type.cpp
  oneflow/core/eager/lazy_job_phy_instr_operand.h
  oneflow/core/eager/lazy_job_stream_type.h
  oneflow/core/eager/local_call_opkernel_phy_instr_operand.cpp
  oneflow/core/eager/local_call_opkernel_phy_instr_operand.h
  oneflow/core/eager/opkernel_instruction_type.cpp
  oneflow/core/eager/opkernel_instruction_type.h
  oneflow/core/eager/release_tensor_arg_phy_instr_operand.h
  oneflow/core/eager/release_tensor_instruction_type.cpp
  oneflow/core/intrusive/channel.h
  oneflow/core/vm/access_blob_arg_cb_phy_instr_operand.h
  oneflow/core/vm/async_cuda_stream_type.h
  oneflow/core/vm/consume_local_dep_object_phy_instr_operand.h
  oneflow/core/vm/control_stream_type.h
  oneflow/core/vm/cpu_stream_type.h
  oneflow/core/vm/cuda_copy_d2h_stream_type.h
  oneflow/core/vm/cuda_copy_h2d_stream_type.h
  oneflow/core/vm/cuda_stream_type.h
  oneflow/core/vm/device_helper_stream_type.h
  oneflow/core/vm/fuse_instruction_type.cpp
  oneflow/core/vm/fuse_phy_instr_operand.h
  oneflow/core/vm/host_stream_type.h
  oneflow/core/vm/infer_stream_type.h
  oneflow/core/vm/instruction.h
  oneflow/core/vm/instruction_type.h
  oneflow/core/vm/no_arg_cb_phy_instr_operand.h
  oneflow/core/vm/phy_instr_operand.h
  oneflow/core/vm/stream_type.h
  oneflow/core/vm/tensor_view_operand.h
  oneflow/core/vm/thread_ctx.cpp
  oneflow/core/vm/thread_ctx.h
  oneflow/core/vm/transport_stream_type.h
  oneflow/core/vm/virtual_machine.cpp
  oneflow/core/vm/virtual_machine_engine.cpp
  oneflow/core/vm/virtual_machine_engine.h
Labels: enhancement, automerge, system

#7424 [BUG] fixed flow rand init as global tensor bug
  oneflow/user/ops/distributions/uniform_op.cpp
  python/oneflow/test/modules/test_rand.py
Labels: automerge, bug, op, test, need-clean-ccache

#7337 Refactor lr schedulers to solve WarmupLR defects
  oneflow/core/job/learning_rate_schedule_conf.proto
  oneflow/core/kernel/learning_rate_schedule_kernel.cpp
  python/oneflow/nn/graph/graph.py
  python/oneflow/nn/graph/optimizer.py
  python/oneflow/nn/optimizer/constant_lr.py
  python/oneflow/nn/optimizer/cosine_annealing_lr.py
  python/oneflow/nn/optimizer/cosine_decay_lr.py
  python/oneflow/nn/optimizer/exponential_lr.py
  python/oneflow/nn/optimizer/lambda_lr.py
  python/oneflow/nn/optimizer/linear_lr.py
  python/oneflow/nn/optimizer/lr_scheduler.py
  python/oneflow/nn/optimizer/multistep_lr.py
  python/oneflow/nn/optimizer/optimizer.py
  python/oneflow/nn/optimizer/polynomial_lr.py
  python/oneflow/nn/optimizer/sequential_lr.py
  python/oneflow/nn/optimizer/step_lr.py
  python/oneflow/nn/optimizer/warm_up_lr.py
  python/oneflow/nn/optimizer/warmup_lr.py
  python/oneflow/optim/lr_scheduler.py
  python/oneflow/test/graph/test_graph_lr_scheduler.py
  python/oneflow/test/modules/test_lr_scheduler.py
Labels: automerge, bug, eager

#7418 Fix Parallel miscellaneous compile option errors
  CMakeLists.txt
  cmake/caches/ci/cpu.cmake
  cmake/caches/ci/cuda.cmake
  cmake/oneflow.cmake
  cmake/third_party/oneDNN.cmake
  oneflow/core/ep/cpu/cpu_stream.h
Labels: automerge, bug, ci, build

#7373 Op check graph test
  oneflow/extension/python/numpy.cpp
  python/oneflow/test/modules/test_chunk.py
  python/oneflow/test/modules/test_diagonal.py
  python/oneflow/test/modules/test_floor.py
  python/oneflow/test/modules/test_gather.py
  python/oneflow/test/modules/test_greater.py
  python/oneflow/test/modules/test_grid_sample.py
  python/oneflow/test/modules/test_index_select.py
  python/oneflow/test/modules/test_linear.py
  python/oneflow/test/modules/test_logical_reduce.py
  python/oneflow/test/modules/test_math_ops.py
  python/oneflow/test/modules/test_mul.py
  python/oneflow/test/modules/test_sort.py
  python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py
Labels: automerge, bug, op, test, graph

#7435 Simple CI CPU_THREADING_RUNTIME=SEQ
  .github/workflows/canary.yml
  .github/workflows/release.yml
  .github/workflows/simple.yml
  .github/workflows/test.yml
Labels: enhancement, automerge, ci, need-simple-ci

#7324 make sbp property callable
  python/oneflow/__init__.py
  python/oneflow/test/modules/test_sbp_symbol.py
Labels: feature, automerge, system, api, need-clean-ccache

#7309 Feat/graph kwargs and generic io
  python/oneflow/nn/graph/block.py
  python/oneflow/nn/graph/graph.py
  python/oneflow/nn/graph/util.py
  python/oneflow/test/graph/test_graph_io_check.py
  python/oneflow/test/modules/test_affine_grid.py
  python/oneflow/test/modules/test_grid_sample.py
Labels: feature, automerge, python, graph

#7225 clip grad support eager consistent
  python/oneflow/nn/utils/clip_grad.py
  python/oneflow/test/modules/test_clip_grad.py
Labels: enhancement, automerge, eager, python

#7436 Garbage instr msg list
  oneflow/api/python/functional/common.h
  oneflow/api/python/functional/indexing.cpp
  oneflow/api/python/functional/tensor_api.cpp
  oneflow/api/python/utils/tensor_utils.h
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/intrusive/mutexed_list.h
  oneflow/core/vm/instruction.cpp
  oneflow/core/vm/virtual_machine.cpp
  oneflow/core/vm/virtual_machine.h
  oneflow/core/vm/virtual_machine_engine.cpp
  oneflow/core/vm/virtual_machine_engine.h
Labels: enhancement, automerge, system

#7438 Graph support Op test
  python/oneflow/test/modules/test_argsort.py
  python/oneflow/test/modules/test_diag.py
  python/oneflow/test/modules/test_eq.py
  python/oneflow/test/modules/test_expand.py
  python/oneflow/test/modules/test_eye.py
  python/oneflow/test/modules/test_flatten.py
  python/oneflow/test/modules/test_flip.py
  python/oneflow/test/modules/test_gather.py
  python/oneflow/test/modules/test_less.py
  python/oneflow/test/modules/test_logical_and.py
  python/oneflow/test/modules/test_logical_not.py
  python/oneflow/test/modules/test_logical_or.py
  python/oneflow/test/modules/test_logical_reduce.py
  python/oneflow/test/modules/test_logical_xor.py
  python/oneflow/test/modules/test_nonzero.py
  python/oneflow/test/modules/test_tile.py
  python/oneflow/test/modules/test_where.py
  python/oneflow/test/tensor/test_parameter.py
  python/oneflow/test/tensor/test_tensor.py
  python/oneflow/test/tensor/test_tensor_part_1.py
  python/oneflow/test/tensor/test_tensor_part_2.py
  python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py
Labels: automerge, bug, test, graph

#7441 add dataloader shared_memory impl
  oneflow/api/python/framework/tensor.cpp
  python/oneflow/multiprocessing/reductions.py
  python/oneflow/test/dataloader/data_utils.py
Labels: enhancement, feature, automerge, eager, refactor

#7326 Support 0 size eager boxing
  oneflow/core/framework/op_interpreter/eager_consistent_op_interpreter.cpp
  oneflow/core/framework/tensor_impl.cpp
  python/oneflow/test/modules/test_eager_boxing.py
Labels: enhancement, automerge, system

#7432 support float16 tensor's numpy method
  oneflow/api/python/framework/tensor.cpp
  oneflow/api/python/utils/tensor_utils.h
  python/oneflow/test/tensor/test_tensor_part_1.py
Labels: enhancement, automerge, system

#7439 Upgrade llvm and fix bugs
  ci/test/test_xla.sh
  cmake/caches/cn/fast/mlir-cuda-61.cmake
  cmake/caches/cn/fast/mlir-cuda-75.cmake
  cmake/oneflow.cmake
  external/CMakeLists.txt
  oneflow/ir/CMakeLists.txt
  oneflow/ir/include/OneFlow/CMakeLists.txt
  oneflow/ir/include/OneFlow/OneFlowBase.td
  oneflow/ir/include/OneFlow/OneFlowInterfaces.td
  oneflow/ir/include/OneFlow/OneFlowOps.h
  oneflow/ir/include/OneFlow/OneFlowOps.td
  oneflow/ir/include/OneFlow/OneFlowPatterns.td
  oneflow/ir/include/OneFlow/Passes.h
  oneflow/ir/include/OneFlow/Transform/BufferHostRegister.h
  oneflow/ir/lib/OneFlow/CMakeLists.txt
  oneflow/ir/lib/OneFlow/Conversion/OneFlowToTosa.cpp
  oneflow/ir/lib/OneFlow/Conversion/PTXToCubin.cpp
  oneflow/ir/lib/OneFlow/Conversion/SCFToGPU.cpp
  oneflow/ir/lib/OneFlow/OneFlowOpGetGen.cpp.in
  oneflow/ir/lib/OneFlow/OneFlowOpTraits.cpp
  oneflow/ir/lib/OneFlow/OneFlowOps.cpp
  oneflow/ir/lib/OneFlow/Passes.cpp
  oneflow/ir/lib/OneFlow/Transform/BufferHostRegister.cpp
  oneflow/ir/llvm-in-tree.cmake
  oneflow/ir/oneflow-extension/extension.cpp
  oneflow/ir/oneflow-opt/CMakeLists.txt
  oneflow/ir/oneflow-opt/oneflow-opt.cpp
  oneflow/ir/oneflow-runner/CMakeLists.txt
  oneflow/ir/oneflow-runner/oneflow-runner.cpp
  oneflow/ir/oneflow-runtime/lib/CMakeLists.txt
  oneflow/ir/oneflow-translate/CMakeLists.txt
  oneflow/ir/oneflow-translate/lib/OneFlow/Importer.cpp
  oneflow/ir/oneflow-translate/lib/OneFlow/MLIROneFlowTranslation.cpp
  oneflow/ir/test/CMakeLists.txt
  oneflow/ir/test/OneFlow/CUDA/fuse_cast_scale.mlir
  oneflow/ir/test/OneFlow/CUDA/gpu_copy_arg.mlir
  oneflow/ir/test/OneFlow/CUDA/gpu_runner.mlir
  oneflow/ir/test/OneFlow/CUDA/lit.local.cfg
  oneflow/ir/test/OneFlow/lower_to_tosa.mlir
  oneflow/ir/test/OneFlow/networks/bert.py
  oneflow/ir/test/OneFlow/networks/pretrain.py
  oneflow/ir/test/OneFlow/networks/test_bert.py
  oneflow/ir/test/OneFlow/networks/test_resnet50.py
  oneflow/ir/test/OneFlow/ops/test_adaptive_pool.py
  oneflow/ir/test/OneFlow/test_fuse_bn_add_relu.py
  oneflow/ir/test/OneFlow/test_fuse_cast_scale.py
  oneflow/ir/test/OneFlow/test_fuse_tril_scale.py
  oneflow/ir/test/OneFlow/test_graph_save_and_load.py
  oneflow/ir/test/OneFlow/test_mlir_opt.py
  oneflow/ir/test/OneFlow/test_util.py
  oneflow/ir/test/lit.cfg.py
  tools/extract_oneflow_export.py
  tools/generate_oneflow_api.py
Labels: enhancement, ci, ir

#7390 logical slice kernel support bool type
  oneflow/user/kernels/slice_kernel.cpp
Labels: enhancement, automerge, system, need-clean-ccache

#7448 Graph support op test && Fix bug
  python/oneflow/test/exceptions/test_consistent_branch_error.py
  python/oneflow/test/modules/test_as_stride.py
  python/oneflow/test/modules/test_concat.py
  python/oneflow/test/modules/test_hsplit.py
  python/oneflow/test/modules/test_instancenorm.py
  python/oneflow/test/modules/test_masked_fill.py
  python/oneflow/test/modules/test_narrow.py
  python/oneflow/test/modules/test_permute.py
  python/oneflow/test/modules/test_prod.py
  python/oneflow/test/modules/test_repeat.py
  python/oneflow/test/modules/test_reshape.py
  python/oneflow/test/modules/test_sign.py
  python/oneflow/test/modules/test_split.py
  python/oneflow/test/modules/test_squeeze.py
  python/oneflow/test/modules/test_stack.py
  python/oneflow/test/modules/test_t.py
  python/oneflow/test/modules/test_tensor_ops.py
  python/oneflow/test/modules/test_tensor_split.py
  python/oneflow/test/modules/test_transpose.py
  python/oneflow/test/modules/test_unsqueeze.py
  python/oneflow/test/modules/test_vsplit.py
  python/oneflow/test/tensor/test_tensor_part_2.py
Labels: bug, test, graph

#7365 Save and load graph states
  docs/source/graph.rst
  oneflow/api/python/framework/nn_graph.cpp
  oneflow/core/framework/nn_graph.cpp
  oneflow/core/framework/nn_graph.h
  oneflow/core/framework/op_interpreter/lazy_op_interpreter.cpp
  oneflow/core/functional/impl/consistent_cast.cpp
  oneflow/core/job/plan_util.cpp
  oneflow/core/job_rewriter/auto_train_step.cpp
  oneflow/core/register/register_manager.cpp
  python/oneflow/framework/graph_build_util.py
  python/oneflow/nn/graph/graph.py
  python/oneflow/test/graph/test_graph_save_load.py
  python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py
Labels: feature, automerge, system, graph

#7460 set requires_grad at last, otherwise it causes non leaf tensor
  oneflow/api/python/utils/tensor_utils.cpp
Labels: enhancement, automerge, bug, system

#7455 Fix test of lr scheduler in graph mode
  python/oneflow/test/graph/test_graph_lr_scheduler.py
  python/oneflow/test/tensor/test_tensor_part_2.py
Labels: automerge, bug, op

#7456 change models commit of ci test
  .github/workflows/test.yml
Labels: enhancement, ci, test

#7469 fix_tensor_numpy_bug
  python/oneflow/framework/tensor.py
Labels: automerge, bug, system

#7458 Fix add tensor inplace op's check graph bug
  python/oneflow/test/modules/test_add.py
  python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py
Labels: automerge, bug, op, graph

#7472 ReshapeOp support any sbp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/ops/reshape_op.cpp
  python/oneflow/test/modules/test_consistent_reshape.py
Labels: enhancement, automerge, eager, graph

#7475 Op check graph, MaxPool and weight_norm
  python/oneflow/test/modules/test_maxpool.py
  python/oneflow/test/modules/test_weight_norm.py
Labels: automerge, bug, op, graph

#7457 eager consistent masked fill test case
  oneflow/user/ops/masked_fill_op.cpp
  python/oneflow/test/modules/test_consistent_masked_fill.py
  python/oneflow/test/modules/test_masked_fill.py
Labels: enhancement, automerge, eager, test

#7476 fix bce loss half grad functor
  oneflow/user/kernels/binary_cross_entropy_kernel.cu
Labels: automerge, bug, op, need-clean-ccache

#7482 fix typo of python/oneflow/framework/tensor.py#L63
  python/oneflow/framework/tensor.py
Labels: automerge, documentation, python

#7407 revise tensor_split,vsplit,hsplit
  oneflow/core/functional/impl/math_functor.cpp
  python/oneflow/framework/docstr/math_ops.py
  python/oneflow/test/modules/test_hsplit.py
  python/oneflow/test/modules/test_tensor_split.py
  python/oneflow/test/modules/test_vsplit.py
Labels: enhancement, automerge, op

#7279 [ddp] allreduce grouping
  oneflow/api/python/framework/tensor.cpp
  oneflow/core/autograd/autograd_engine.cpp
  oneflow/core/autograd/autograd_meta.h
  oneflow/core/eager/blob_instruction_type.cpp
  oneflow/core/eager/eager_blob_object.cpp
  oneflow/core/eager/eager_blob_object.h
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/framework/tensor.h
  oneflow/core/framework/tensor_impl.cpp
  oneflow/core/framework/tensor_impl.h
  oneflow/core/framework/tensor_methods.cpp
  oneflow/core/framework/tensor_methods.h
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/core/register/blob.cpp
  oneflow/core/register/blob.h
  python/oneflow/nn/parallel/ddp.py
  python/oneflow/test/modules/test_ddp.py
Labels: feature, automerge, system, python

#7479 fix advanced index when input index is scalar
  oneflow/core/functional/impl/array_functor.cpp
  python/oneflow/test/tensor/test_tensor_indexing.py
Labels: automerge, bug, system

#7478 Refactor mlir codegen
  oneflow/core/common/error.cpp
  oneflow/ir/include/OneFlow/CMakeLists.txt
  oneflow/ir/include/OneFlow/OneFlowPatterns.td
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/ir/lib/OneFlow/Conversion/OneFlowToTosa.cpp
  oneflow/ir/lib/OneFlow/Passes.cpp
  oneflow/ir/oneflow-translate/lib/OneFlow/Importer.cpp
  oneflow/ir/test/OneFlow/CUDA/fuse_cast_scale.mlir
  oneflow/ir/test/OneFlow/lower_to_tosa.mlir
  oneflow/ir/test/OneFlow/test_fuser_cast_scale.py
  python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py
Labels: enhancement, automerge, ir

#7405 fix broadcast_like sbp infer
  oneflow/user/ops/broadcast_like_op.cpp
Labels: enhancement, automerge, bug, system

#7481 upgrade clang-tidy
  .github/workflows/test.yml
  ci/check/run_clang_tidy.py
Labels: automerge, bug, ci

#7409 auto exit worker process by prctl(PR_SET_PDEATHSIG, ...)
  python/oneflow/distributed/launch.py
  python/oneflow/utils/data/_utils/worker.py
Labels: automerge, bug, python

#7488 Fix api docs not building
  .github/workflows/release.yml
Labels: automerge, bug, ci

#7454 fix batchnorm nhwc errors
  python/oneflow/nn/modules/batchnorm.py
  python/oneflow/nn/modules/batchnorm_fused.py
Labels: feature, automerge, op

#7449 Fix bug of nn.Graph to_consistent with hierarchy
  oneflow/core/framework/op_interpreter/lazy_op_interpreter.cpp
  python/oneflow/test/graph/test_to_consistent.py
Labels: automerge, bug, graph

#7443 add specific interface of tensor
  docs/source/cuda.rst
  docs/source/oneflow.rst
  python/oneflow/__init__.py
  python/oneflow/cuda/__init__.py
  python/oneflow/cuda/type_tensor.py
  python/oneflow/framework/type_tensor.py
  python/oneflow/test/modules/test_type_tensor.py
Labels: enhancement, automerge, ci, api, interface

#7319 Add oneDNN binary op
  oneflow/core/common/preprocessor.h
  oneflow/core/common/preprocessor_internal.h
  oneflow/core/ep/cpu/primitive/add.cpp
  oneflow/core/ep/cpu/primitive/broadcast_elementwise_binary.cpp
  oneflow/core/ep/cpu/primitive/type_seq.h
  oneflow/user/kernels/math_binary_broadcast_kernels.cpp
Labels: enhancement, automerge, op, primitive

#7493 fix norm bug
  oneflow/core/functional/impl/math_functor.cpp
Labels: enhancement, automerge, bug, system

#7495 fix memory alignment in ddp grad grouping
  python/oneflow/nn/parallel/ddp.py
Labels: automerge, bug, eager, system, python

#7490 Fix tensor deepcopy bug
  python/oneflow/framework/check_point_v2.py
  python/oneflow/test/modules/test_loss.py
  python/oneflow/test/modules/test_tensor_split.py
  python/oneflow/test/tensor/test_tensor_part_1.py
  python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py
Labels: automerge, bug, op, need-clean-ccache, graph

#7501 read CMAKE_BUILD_TYPE after project()
  CMakeLists.txt
Labels: automerge, bug, build

#7498 raise with error msg if module to_consistent is called
  python/oneflow/framework/tensor.py
  python/oneflow/nn/module.py
Labels: enhancement, automerge, system, python

#7499 Implement GetSizeOfDataType for all types
  oneflow/core/common/data_type.cpp
Labels: enhancement, automerge, system, need-clean-ccache

#7514 Distributed CI V2
  .github/workflows/canary.yml
  .github/workflows/release.yml
  .github/workflows/simple.yml
  .github/workflows/test.yml
  ci/test/2node_op_test_multi_client.sh
Labels: enhancement, automerge, ci

#7507 check numerics dump data, count not finite support half
  oneflow/core/ep/cuda/cuda_stream.cpp
  oneflow/core/ep/cuda/cuda_stream.h
  oneflow/core/kernel/cpu_numerics_kernel_observer.cpp
  oneflow/core/kernel/cuda_check_numerics_kernel_observer.cu
  oneflow/user/kernels/count_not_finite_kernel.cu
Labels: enhancement, automerge, system

#7505 refine graph doc
  python/oneflow/nn/graph/graph.py
Labels: enhancement, automerge, documentation, api, python

#7515 Update Oneflow-Inc/gh-action-scheduler-v2@fix-for-new-distributed
  .github/workflows/test.yml
Labels: enhancement, automerge, ci

#7511 add test case to check to_consistent use
  python/oneflow/framework/tensor.py
  python/oneflow/nn/module.py
  python/oneflow/test/exceptions/test_to_consistent_error.py
Labels: enhancement, automerge, bug, eager

#7494 Fix reshapae like sbp infer
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/ops/reshape_like_op.cpp
  python/oneflow/test/modules/test_consistent_reshape.py
Labels: enhancement, automerge, op, need-clean-ccache

#7442 Grad Acc v2
  oneflow/core/framework/op_interpreter/lazy_op_interpreter.cpp
  oneflow/core/framework/user_op_conf.cpp
  oneflow/core/framework/user_op_conf.h
  oneflow/core/job_rewriter/gradient_accumulation_rewrite_pass.cpp
  python/oneflow/test/graph/test_graph_grad_acc.py
Labels: automerge, bug, system, refactor, graph

#7528 GPU wait => 60 minutes
  .github/workflows/test.yml
Labels: enhancement, automerge, ci

#7512 support_1_to_n_and_n_to_1_with_diff_dim
  oneflow/core/boxing/eager_boxing_interpreter_mgr.cpp
  python/oneflow/test/modules/test_eager_boxing.py
Labels: enhancement, automerge, system

#7508 Fix all source op when using nd sbp in graph
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/ops/constant_op.cpp
  oneflow/user/ops/distributions/uniform_int_op.cpp
  oneflow/user/ops/distributions/uniform_op.cpp
  oneflow/user/ops/empty_op.cpp
  python/oneflow/test/modules/test_consistent_constant.py
  python/oneflow/test/modules/test_consistent_empty.py
  python/oneflow/test/modules/test_consistent_rand.py
  python/oneflow/test/modules/test_consistent_randint.py
  python/oneflow/test/modules/test_constant.py
  python/oneflow/test/modules/test_empty.py
  python/oneflow/test/modules/test_rand.py
  python/oneflow/test/modules/test_randint.py
Labels: automerge, bug, test, need-clean-ccache, graph

#7529 Fix/graph fuse add
  oneflow/core/job/job_builder.cpp
  oneflow/core/job/job_builder.h
  oneflow/core/job_rewriter/fuse_add_to_output_pass.cpp
Labels: automerge, bug, system, graph

#7533 meshgrid support eager global
  oneflow/core/functional/impl/array_functor.cpp
  python/oneflow/test/modules/test_consistent_meshgrid.py
Labels: enhancement, automerge, op

#7518 Refactor GetDualObject code
  python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py
Labels: enhancement, automerge, op, graph

#7530 ONEFLOW_TIMEOUT_SECONDS->2hour
  oneflow/core/common/env_var.h
Labels: automerge, bug, system

#7545 Fix nn.graph concat backward bug
  oneflow/user/ops/split_like_op.cpp
  python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py
Labels: automerge, bug, op, graph

#7425 Support graph other api run backward
  oneflow/user/ops/split_like_op.cpp
Labels: feature, automerge, eager, graph

#7459 create autograd meta by default, remove redundant is_leaf and require…
  oneflow/api/python/framework/tensor.cpp
  oneflow/core/autograd/autograd_engine.cpp
  oneflow/core/framework/tensor.h
  oneflow/core/framework/tensor_impl.cpp
  oneflow/core/framework/tensor_impl.h
  python/oneflow/test/modules/test_consistent_expand_op.py
  python/oneflow/test/modules/test_consistent_reshape.py
  python/oneflow/test/modules/test_loss_consistent.py
  python/oneflow/test/modules/test_sparse_softmax_cross_entropy.py
Labels: enhancement, automerge, system

#7492 eager global masked select
  python/oneflow/nn/modules/argwhere.py
  python/oneflow/nn/modules/masked_select.py
  python/oneflow/test/modules/test_consistent_masked_select.py
  python/oneflow/test/modules/test_consistent_meshgrid.py
Labels: enhancement, automerge, op

#7395 support bool tensor in eager nccl kernels
  oneflow/core/job/collective_boxing/nccl_executor_backend.cu
  oneflow/user/kernels/eager_nccl_kernels.cpp
  oneflow/user/kernels/eager_nccl_kernels.cu
  oneflow/user/kernels/nccl_logical_kernels.cpp
  python/oneflow/test/modules/test_consistent_slice.py
Labels: enhancement, automerge, system

#7531 Refine global time out message
  .github/workflows/test.yml
  ci/test/multi_client_exception_test.sh
  oneflow/core/framework/consistency_check.cpp
  oneflow/core/framework/sync_symbol_parallel_desc.cpp
  python/oneflow/test/exceptions/test_global_branch_error_with_global_mean.py
  python/oneflow/test/exceptions/test_global_branch_error_with_local_to_global.py
Labels: enhancement, automerge, system

#7426 Optimize nchw MaxPooling
  oneflow/user/kernels/pooling_kernel.cpp
  oneflow/user/kernels/pooling_kernel.cu
  oneflow/user/kernels/pooling_kernel_util.h
  oneflow/user/ops/pooling_op.cpp
Labels: enhancement, automerge, bug, op

#7451 Optimize nchw Avgpool
  oneflow/core/autograd/gradient_funcs/avg_pooling.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/core/functional/impl/nn_grad_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowBase.td
  oneflow/user/kernels/avg_pooling_kernel.cpp
  oneflow/user/kernels/avg_pooling_kernel.cu
  oneflow/user/kernels/avg_pooling_kernel_util.cpp
  oneflow/user/kernels/avg_pooling_kernel_util.h
  oneflow/user/ops/pooling_op.cpp
Labels: enhancement, automerge, op

#7462 implement select op in functor,remove cuda kernel
  docs/source/oneflow.rst
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/math_functor.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/math_ops.py
  python/oneflow/test/modules/test_select.py
Labels: enhancement, automerge, op

#7496 Fix flip consistent test bug
  oneflow/core/boxing/eager_boxing_interpreter_mgr.cpp
  oneflow/core/framework/placement_sbp_util.cpp
  oneflow/core/framework/placement_sbp_util_test.cpp
  oneflow/user/ops/flip_op.cpp
  python/oneflow/test/modules/test_consistent_flip.py
Labels: automerge, bug, system

#7559 align num_workers = 1
  python/oneflow/utils/data/dataloader.py
Labels: enhancement, automerge, python

#7563 add global adaptive pool unittest
  python/oneflow/test/modules/test_consistent_adaptive_pool.py
Labels: enhancement, automerge, op, test

#7568 Crash if found priority
  .github/workflows/canary.yml
  .github/workflows/release.yml
  .github/workflows/simple.yml
  .github/workflows/test.yml
Labels: enhancement, automerge, ci

#7554 quick fix sbp of layer_norm_param_grad
  .github/workflows/test.yml
  oneflow/core/job/sbp_parallel.cpp
  oneflow/user/ops/layer_norm_op.cpp
Labels: automerge, bug, op, need-highest-priority

#7570 reduce loop count to reduce test time
  python/oneflow/test/modules/test_consistent_concat.py
  python/oneflow/test/modules/test_consistent_masked_fill.py
  python/oneflow/test/modules/test_consistent_masked_select.py
  python/oneflow/test/modules/test_consistent_meshgrid.py
Labels: enhancement, automerge, op, test, need-highest-priority

#7553 if ONEFLOW_DEBUG_MODE is nullptr, no metainfo sync
  oneflow/core/ccl/ccl.cpp
  oneflow/core/common/constant.h
  oneflow/core/framework/consistency_check.cpp
  oneflow/core/framework/sync_symbol_nd_sbp.cpp
  oneflow/core/framework/sync_symbol_parallel_desc.cpp
  oneflow/core/framework/tensor_rpc_util.cpp
  oneflow/core/functional/impl/consistent_cast.cpp
  python/oneflow/test/exceptions/test_global_branch_error_local_to_global_with_broadcast_sbp_1n2d.py
  python/oneflow/test/exceptions/test_global_branch_error_local_to_global_with_broadcast_sbp_1n4d.py
  python/oneflow/test/exceptions/test_global_branch_error_local_to_global_with_split_sbp.py
Labels: enhancement, automerge, system

#7540 add abs, activation and 0 dim tensor tests
  python/oneflow/test/modules/test_consistent_0_dim_tensor.py
  python/oneflow/test/modules/test_consistent_abs.py
  python/oneflow/test/modules/test_consistent_activation.py
  python/oneflow/test/modules/test_consistent_add.py
Labels: enhancement, automerge, test, system

#7468 Lxq stream
  oneflow/api/python/functional/tensor_api.cpp
  oneflow/core/common/static_global.h
  oneflow/core/common/stream_role.h
  oneflow/core/eager/critical_section_phy_instr_operand.cpp
  oneflow/core/eager/eager_blob_object.h
  oneflow/core/eager/lazy_job_phy_instr_operand.cpp
  oneflow/core/eager/local_call_opkernel_phy_instr_operand.cpp
  oneflow/core/eager/local_dep_object.cpp
  oneflow/core/eager/local_dep_object.h
  oneflow/core/eager/release_tensor_arg_phy_instr_operand.h
  oneflow/core/framework/consistent_tensor_infer_cache.cpp
  oneflow/core/framework/consistent_tensor_infer_cache.h
  oneflow/core/framework/device.cpp
  oneflow/core/framework/device.h
  oneflow/core/framework/infer_util.h
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/framework/instructions_builder.h
  oneflow/core/framework/op_expr.cpp
  oneflow/core/framework/op_expr.h
  oneflow/core/framework/op_interpreter/eager_consistent_op_interpreter.cpp
  oneflow/core/framework/op_interpreter/eager_mirrored_op_interpreter.cpp
  oneflow/core/framework/stream.cpp
  oneflow/core/framework/stream.h
  oneflow/core/framework/stream_get_call_instruction_name.h
  oneflow/core/framework/stream_get_release_instruction_name.h
  oneflow/core/framework/stream_is_comm_net_stream.h
  oneflow/core/framework/stream_need_soft_sync.h
  oneflow/core/framework/tensor_impl.cpp
  oneflow/core/framework/user_op_registry.cpp
  oneflow/core/framework/user_op_registry.h
  oneflow/ir/include/OneFlow/OneFlowBase.td
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/stateful_local_opkernel.cpp
  oneflow/user/kernels/stateful_local_opkernel.h
  oneflow/user/ops/comm_net_device_infer_util.cpp
  oneflow/user/ops/comm_net_device_infer_util.h
  oneflow/user/ops/copy_op.cpp
  oneflow/user/ops/eager_b_to_s_op.cpp
  oneflow/user/ops/eager_nccl_ops.cpp
  oneflow/user/ops/eager_p_to_b_op.cpp
  oneflow/user/ops/eager_p_to_s_op.cpp
  oneflow/user/ops/eager_s_to_b_op.cpp
  oneflow/user/ops/eager_s_to_p_op.cpp
  oneflow/user/ops/eager_s_to_s_op.cpp
  oneflow/user/ops/eager_symmetric_s_to_p_op.cpp
  oneflow/user/ops/nccl_logical_2d_sbp_ops.cpp
  oneflow/user/ops/nccl_logical_ops.cpp
  oneflow/user/ops/p2p_comm_op.cpp
  tools/oneflow-tblgen/op_schema_emitter.cpp
  tools/oneflow-tblgen/op_schema_header.inc
  tools/oneflow-tblgen/op_schema_source.inc
Labels: enhancement, automerge, system, refactor

#7577 Only run TestForkSubProcess on 1n1d
  .github/workflows/test.yml
  python/oneflow/test/modules/test_fork_sub_process.py
Labels: enhancement, automerge, ci

#7502 Fix bilinear upsample
  oneflow/user/kernels/upsample_bilinear_2d_kernel.cpp
  oneflow/user/kernels/upsample_bilinear_2d_kernel.cu
  python/oneflow/test/modules/test_upsample.py
Labels: automerge, bug, op, api, need-clean-ccache

#7517 fix var bug
  oneflow/user/kernels/variance_kernel.cpp
  oneflow/user/kernels/variance_kernel_util.cu
  python/oneflow/test/tensor/test_tensor_part_2.py
Labels: automerge, bug, op

#7524 Refactor lr scheduler around CosineAnnealingWarmRestarts
  oneflow/core/job/job_conf.proto
  oneflow/core/job/learning_rate_schedule_conf.proto
  oneflow/core/job_rewriter/auto_learning_rate.cpp
  oneflow/core/job_rewriter/model_update_conf_compatible_pass.cpp
  oneflow/core/kernel/learning_rate_schedule_kernel.cpp
  oneflow/core/operator/op_conf.proto
  python/oneflow/nn/graph/graph.py
  python/oneflow/nn/graph/optimizer.py
  python/oneflow/nn/optimizer/chained_scheduler.py
  python/oneflow/nn/optimizer/constant_lr.py
  python/oneflow/nn/optimizer/cosine_annealing_lr.py
  python/oneflow/nn/optimizer/cosine_annealing_warm_restarts.py
  python/oneflow/nn/optimizer/cosine_decay_lr.py
  python/oneflow/nn/optimizer/exponential_lr.py
  python/oneflow/nn/optimizer/lambda_lr.py
  python/oneflow/nn/optimizer/linear_lr.py
  python/oneflow/nn/optimizer/lr_scheduler.py
  python/oneflow/nn/optimizer/multistep_lr.py
  python/oneflow/nn/optimizer/polynomial_lr.py
  python/oneflow/nn/optimizer/sequential_lr.py
  python/oneflow/nn/optimizer/step_lr.py
  python/oneflow/nn/optimizer/warmup_lr.py
  python/oneflow/optim/lr_scheduler.py
  python/oneflow/test/graph/test_graph_lr_scheduler.py
  python/oneflow/test/modules/test_lr_scheduler.py
Labels: feature, automerge, eager, api, graph

#7575 Add graph and block config docstr
  docs/source/graph.rst
  python/oneflow/nn/graph/block_config.py
  python/oneflow/nn/graph/graph_config.py
Labels: automerge, op, documentation, graph

#7566 Fix data transform slow
  oneflow/core/ep/cpu/primitive/broadcast_elementwise_binary.cpp
Labels: enhancement, automerge, bug, op, system

#7525 support boxing when excuting loss.backward() in eager mode
  oneflow/api/python/autograd/autograd_engine.cpp
  oneflow/core/autograd/autograd_engine.cpp
  oneflow/core/autograd/autograd_meta.h
  oneflow/core/framework/global_param_grad_sync_mode.cpp
  oneflow/core/framework/global_param_grad_sync_mode.h
  python/oneflow/nn/module.py
Labels: enhancement, feature, automerge, bug, eager, api, need-clean-ccache

#7565 add global addmm, argmax, argmin, argsort and argwhere unittest
  python/oneflow/test/modules/test_consistent_addmm.py
  python/oneflow/test/modules/test_consistent_argmax.py
  python/oneflow/test/modules/test_consistent_argmin.py
  python/oneflow/test/modules/test_consistent_argsort.py
  python/oneflow/test/modules/test_consistent_argwhere.py
Labels: enhancement, automerge, test

#7539 fix graph return unpack
  python/oneflow/nn/graph/block.py
  python/oneflow/nn/graph/graph.py
  python/oneflow/nn/graph/util.py
  python/oneflow/test/graph/test_graph_io_check.py
Labels: automerge, bug, python, graph

#7552 fix save global tensor when global_dst_rank doesn't have data
  python/oneflow/framework/check_point_v2.py
  python/oneflow/test/modules/test_module.py
Labels: automerge, bug, python

#7561 fix data loader segfault
  oneflow/core/ipc/shared_memory.cpp
Labels: automerge, bug, system

#7556 Fix SbpParallel4ArgNameAndIndex bug
  oneflow/core/operator/operator.cpp
  oneflow/user/kernels/image_preprocess_kernels.cpp
  oneflow/user/kernels/random_crop_kernel_state.cpp
  oneflow/user/kernels/random_seed_util.cpp
  oneflow/user/kernels/random_seed_util.h
  oneflow/user/ops/coco_reader_op.cpp
  oneflow/user/ops/eager_nccl_ops.cpp
  oneflow/user/ops/image_preprocess_ops.cpp
  oneflow/user/ops/normalization_op.cpp
  oneflow/user/ops/ofrecord_image_classification_reader_op.cpp
  oneflow/user/ops/ofrecord_reader_op.cpp
  oneflow/user/ops/test_ops.cpp
  python/oneflow/nn/modules/dataset.py
  python/oneflow/test/modules/test_coin_flip.py
  python/oneflow/test/modules/test_consistent_coin_flip.py
Labels: bug, graph, need-highest-priority

#7421 add eager test case, fix origin error cases
  python/oneflow/test/modules/test_consistent_diag.py
  python/oneflow/test/modules/test_consistent_div.py
  python/oneflow/test/modules/test_consistent_dot.py
  python/oneflow/test/modules/test_consistent_eq.py
  python/oneflow/test/modules/test_consistent_erf.py
  python/oneflow/test/modules/test_consistent_erfc.py
  python/oneflow/test/modules/test_consistent_expm1.py
  python/oneflow/test/modules/test_consistent_eye.py
  python/oneflow/test/modules/test_consistent_flatten.py
  python/oneflow/test/modules/test_consistent_floor.py
  python/oneflow/test/modules/test_consistent_fmod.py
  python/oneflow/test/modules/test_consistent_greater_equal.py
Labels: enhancement, automerge, eager

#7562 Use different steps in CI for distributed tests with/without IB
  .github/workflows/test.yml
  ci/test/2node_op_test_multi_client.sh
Labels: enhancement, automerge, ci

#7519 fix maximum minimum backward bug
  oneflow/user/kernels/elementwise_maximum_minimum_kernel.h
  python/oneflow/test/modules/test_consistent_maximum_minimum.py
Labels: automerge, bug, op

#7587 add module.zero_grad
  python/oneflow/nn/module.py
Labels: enhancement, automerge, eager, api

#7592 Fix PadFunctor half input
  oneflow/core/autograd/gradient_funcs/padding.cpp
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/core/functional/impl/nn_grad_functor.cpp
Labels: automerge, bug, op

#7595 Fix the bug of judging whether a data type supports boxing
  oneflow/core/common/data_type.cpp
  oneflow/core/common/data_type.h
  oneflow/core/common/data_type_seq.h
  oneflow/core/operator/operator.cpp
Labels: automerge, bug, graph, AutoParallel

#7600 optimize prelu alpha grad
  oneflow/core/functional/impl/activation_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/prelu_kernel.cu
  oneflow/user/ops/prelu_op.cpp
Labels: enhancement, automerge, op

#7599 fuse pad conv in mlir
  oneflow/ir/include/OneFlow/CMakeLists.txt
  oneflow/ir/include/OneFlow/OneFlowBase.td
  oneflow/ir/include/OneFlow/OneFlowPatterns.td
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/ir/lib/OneFlow/Passes.cpp
  oneflow/ir/test/OneFlow/test_fuse_pad_conv.py
Labels: enhancement, automerge, api, ir

#7500 autotest support mlir
  .github/workflows/test.yml
  oneflow/core/framework/nn_graph.cpp
  oneflow/ir/include/OneFlow/OneFlowBase.td
  oneflow/ir/include/OneFlow/OneFlowOpTraits.h
  oneflow/ir/include/OneFlow/OneFlowOps.td
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/ir/oneflow-translate/lib/OneFlow/Importer.cpp
  oneflow/ir/oneflow-translate/lib/OneFlow/MLIROneFlowTranslation.cpp
  oneflow/user/ops/variance_op.cpp
  python/oneflow/nn/graph/graph_config.py
  python/oneflow/test/modules/test_coco_reader.py
  python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py
Labels: feature, automerge, system, api

#7564 Fix shared memory leak
  oneflow/api/python/multiprocessing/shared_memory.cpp
  oneflow/core/common/env_var.h
  oneflow/core/common/pcheck.h
  oneflow/core/ipc/shared_memory.cpp
  oneflow/core/ipc/shared_memory.h
  python/oneflow/multiprocessing/__init__.py
  python/oneflow/multiprocessing/reductions.py
  python/oneflow/multiprocessing/shared_memory/__init__.py
  python/oneflow/utils/data/_utils/worker.py
Labels: automerge, bug, eager, api

#7578 fix affine_grid and add global unittest
  oneflow/user/kernels/affine_grid_kernel.cpp
  oneflow/user/ops/affine_grid_op.cpp
  python/oneflow/test/modules/test_consistent_affine_grid.py
Labels: enhancement, automerge, bug, op, system

#7303 consistent_std_sub_sum_test
  python/oneflow/test/modules/test_consistent_std.py
  python/oneflow/test/modules/test_consistent_sub.py
  python/oneflow/test/modules/test_consistent_sum.py
Labels: enhancement, automerge, test, system

#7627 Remove MLIR conf from graph and autotest
  .github/workflows/canary.yml
  python/oneflow/nn/graph/graph_config.py
  python/oneflow/test/modules/test_coco_reader.py
  python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py
Labels: enhancement, automerge, bug, ci

#7628 fix shared memory mac build bug
  oneflow/core/ipc/shared_memory.cpp
Labels: enhancement, automerge, bug, build

#7608 Support mix 1d 2d eager boxing with diff placement
  oneflow/core/boxing/boxing_dividor_util.cpp
  oneflow/core/boxing/eager_boxing_interpreter_mgr.cpp
  oneflow/core/boxing/identity_boxing_interpreter.cpp
  oneflow/core/boxing/symmetric_acyclic_nd_sbp_boxing.cpp
  oneflow/core/ccl/ccl.cpp
  python/oneflow/test/modules/test_eager_boxing.py
Labels: enhancement, automerge, system

#7631 add nhwc pad conv fuse pattern in mlir
  oneflow/ir/include/OneFlow/OneFlowPatterns.td
  oneflow/ir/lib/OneFlow/Passes.cpp
  oneflow/ir/test/OneFlow/test_fuse_pad_conv.py
Labels: enhancement, automerge, bug, eager, api, ir
