Repository Oneflow-Inc/oneflow, pull requests merged in 2022-05, with the labels that each got.

#7879 fix bug
  python/oneflow/nn/utils/clip_grad.py
Labels: enhancement, automerge, bug, eager, api, python

#8111 Rename pooling ops
  oneflow/core/autograd/gradient_funcs/avg_pool.cpp
  oneflow/core/autograd/gradient_funcs/max_pool.cpp
  oneflow/core/autograd/gradient_funcs/tf_pool.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/core/functional/impl/nn_grad_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/ir/lib/OneFlow/OneFlowOps.cpp
  oneflow/ir/lib/OneFlow/OneFlowSupport.cpp
  oneflow/user/kernels/avg_pool_kernel.cpp
  oneflow/user/kernels/avg_pool_kernel.cu
  oneflow/user/kernels/avg_pool_kernel_util.cpp
  oneflow/user/kernels/avg_pool_kernel_util.h
  oneflow/user/kernels/max_pool_kernel.cpp
  oneflow/user/kernels/max_pool_kernel.cu
  oneflow/user/kernels/max_pool_kernel_util.cpp
  oneflow/user/kernels/max_pool_kernel_util.h
  oneflow/user/kernels/tf_pool_cpu_kernel.cpp
  oneflow/user/kernels/tf_pool_gpu_kernel.cpp
  oneflow/user/ops/avg_pool_op.cpp
  oneflow/user/ops/max_pool_op.cpp
  oneflow/user/ops/tf_pool_op.cpp
  oneflow/xrt/api.cpp
  oneflow/xrt/tensorrt/ops/pooling_op.cpp
  python/oneflow/test/graph/test_tvm_frontend_dependency_on_graph.py
Labels: enhancement, automerge, op, refactor

#8078 [OneEmbedding] support clip by global norm
  oneflow/core/job_rewriter/autograd.cpp
  oneflow/core/job_rewriter/autograd.h
  oneflow/core/job_rewriter/clip_by_global_norm_job_pass_state.h
  oneflow/core/job_rewriter/generate_backward_and_optimizer_op_confs.cpp
  oneflow/core/job_rewriter/replace_embedding_ops_pass.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/one_embedding_kernels.cu
  oneflow/user/kernels/one_embedding_update_kernels.cu
  python/oneflow/one_embedding.py
Labels: enhancement, automerge, op, embedding

#8094 expand op support 0-size and advanced_index support 0-size
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/core/functional/tensor_index.cpp
  oneflow/core/functional/tensor_index.h
  oneflow/user/kernels/expand_kernel.cpp
  oneflow/user/kernels/expand_kernel.cu
  oneflow/user/kernels/expand_kernel_utils.cpp
  oneflow/user/kernels/variance_kernel_util.cu
  python/oneflow/test/modules/test_expand.py
  python/oneflow/test/tensor/test_tensor_indexing.py
Labels: enhancement, automerge, bug, op

#8058 Modify reference info
  python/oneflow/autograd/autograd.py
  python/oneflow/cuda/__init__.py
  python/oneflow/framework/docstr/conv.py
  python/oneflow/framework/docstr/dropout.py
  python/oneflow/framework/docstr/index_select.py
  python/oneflow/framework/docstr/loss.py
  python/oneflow/framework/docstr/math_ops.py
  python/oneflow/framework/docstr/meshgrid.py
  python/oneflow/framework/docstr/tensor.py
  python/oneflow/framework/docstr/tensor_attributes.py
  python/oneflow/framework/docstr/tile.py
  python/oneflow/framework/generator.py
  python/oneflow/nn/init.py
  python/oneflow/nn/modules/activation.py
  python/oneflow/nn/modules/affine_grid.py
  python/oneflow/nn/modules/conv.py
  python/oneflow/nn/modules/grid_sample.py
  python/oneflow/nn/modules/instancenorm.py
  python/oneflow/nn/modules/interpolate.py
  python/oneflow/nn/modules/loss.py
  python/oneflow/nn/modules/normalization.py
  python/oneflow/nn/modules/padding.py
  python/oneflow/nn/modules/pixelshuffle.py
  python/oneflow/nn/modules/pooling.py
  python/oneflow/nn/modules/rnn.py
  python/oneflow/nn/modules/upsampling.py
  python/oneflow/nn/optimizer/cosine_annealing_lr.py
  python/oneflow/nn/optimizer/optimizer.py
  python/oneflow/nn/utils/weight_norm.py
Labels: automerge, eager, documentation

#8080 Add activation functor exception
  oneflow/core/functional/impl/activation_functor.cpp
  oneflow/core/functional/impl/common.cpp
  python/oneflow/framework/tensor.py
  python/oneflow/nn/modules/activation.py
  python/oneflow/nn/modules/utils.py
  python/oneflow/test/exceptions/test_activation.py
Labels: automerge, bug, eager, api, need-check-error-message

#7751 [Feat.] Support tensor set item in graph
  docs/source/oneflow.rst
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/slice_kernel.cpp
  oneflow/user/ops/slice_op.cpp
  python/oneflow/__init__.py
  python/oneflow/nn/graph/graph.py
  python/oneflow/nn/modules/slice.py
  python/oneflow/test/README.md
  python/oneflow/test/graph/test_graph_linear.py
  python/oneflow/test/modules/test_consistent_slice_assign.py
  python/oneflow/test/modules/test_slice.py
Labels: feature, automerge, op, graph, global

#8049 Fix warning in DualObject __del__
  python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py
Labels: automerge, bug, test

#7571 source op support s and fixed generator bug
  oneflow/user/kernels/distributions/uniform_kernel.h
  oneflow/user/kernels/randperm_kernel.cpp
  oneflow/user/kernels/randperm_kernel.cu
  oneflow/user/ops/randperm_op.cpp
  python/oneflow/test/modules/test_consistent_arange.py
  python/oneflow/test/modules/test_consistent_randperm.py
Labels: enhancement, automerge, op, test, graph, global

#8067 Refine local global convert error msg
  oneflow/api/python/symbol/sbp_symbol.cpp
  oneflow/core/common/flat_shape.cpp
  oneflow/core/functional/impl/consistent_cast.cpp
  python/oneflow/nn/modules/global_cast.py
  python/oneflow/test/exceptions/test_local_global_convert_error.py
  python/oneflow/test/modules/test_eager_boxing_exhaustive.py
Labels: enhancement, automerge, system, need-clean-ccache

#7895 Remove almost all usage of `Blob` in EagerBlobObject
  oneflow/api/python/functional/tensor_api.cpp
  oneflow/api/python/utils/tensor_utils.cpp
  oneflow/core/common/shape.cpp
  oneflow/core/common/shape.h
  oneflow/core/common/util.h
  oneflow/core/eager/blob_instruction_type.cpp
  oneflow/core/eager/blob_instruction_type.h
  oneflow/core/eager/blob_object.cpp
  oneflow/core/eager/blob_object.h
  oneflow/core/eager/cpu_blob_instruction_type.cpp
  oneflow/core/eager/cpu_opkernel_instruction_type.cpp
  oneflow/core/eager/critical_section_phy_instr_operand.cpp
  oneflow/core/eager/cuda_blob_instruction_type.cpp
  oneflow/core/eager/cuda_opkernel_instruction_type.cpp
  oneflow/core/eager/eager_blob_object.cpp
  oneflow/core/eager/eager_blob_object.h
  oneflow/core/eager/lazy_ref_blob_object.h
  oneflow/core/eager/opkernel_instruction_type.cpp
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/framework/instructions_builder.h
  oneflow/core/framework/nn_graph.cpp
  oneflow/core/framework/nn_graph.h
  oneflow/core/framework/op_kernel.cpp
  oneflow/core/framework/op_kernel.h
  oneflow/core/framework/tensor.h
  oneflow/core/framework/tensor_impl.cpp
  oneflow/core/framework/tensor_impl.h
  oneflow/core/framework/tensor_methods.cpp
  oneflow/core/framework/user_op_tensor.h
  oneflow/core/job/oneflow.cpp
  oneflow/core/job/runtime.cpp
  oneflow/core/job/runtime.h
  oneflow/core/kernel/blob_tensor_view.cpp
  oneflow/core/kernel/blob_tensor_view.h
  oneflow/core/kernel/user_kernel.cpp
  oneflow/core/memory/memory_allocator.cpp
  oneflow/core/memory/memory_allocator.h
  oneflow/core/register/blob_desc.cpp
  oneflow/core/register/blob_desc.h
  oneflow/core/register/register_manager.cpp
  oneflow/core/register/register_manager.h
  oneflow/core/vm/tensor_view_operand.cpp
  oneflow/core/vm/tensor_view_operand.h
  oneflow/user/data/coco_parser.cpp
  oneflow/user/data/ofrecord_parser.h
  oneflow/user/kernels/concat_kernel.cpp
  oneflow/user/kernels/image_batch_align_kernel.cpp
  oneflow/user/kernels/onerec_decoder_kernels.cpp
  oneflow/user/kernels/split_like_kernel.cpp
  oneflow/user/kernels/stack_kernel.cpp
  oneflow/user/kernels/stateful_local_opkernel.cpp
  oneflow/user/kernels/stateful_local_opkernel.h
  oneflow/user/kernels/tensor_buffer_kernels.cpp
  oneflow/user/kernels/test_kernels.cpp
Labels: enhancement, system, refactor

#8125 Fix cuda version limit for CUBLASLT_EPILOGUE_BGRADB
  oneflow/user/kernels/cublas_bias_add_relu_matmul_grad_kernel.cu
  oneflow/user/kernels/cublas_fused_matmul_bias_add_grad.cu
  oneflow/user/kernels/cublas_fused_mlp_kernel.cu
  oneflow/user/kernels/cublas_fused_mlp_util.cuh
Labels: enhancement, automerge, build

#8013 Improve VectorAt
  oneflow/core/common/container_util.h
  oneflow/core/common/container_util_test.cpp
Labels: enhancement, automerge, system

#8126 Cherry pick changes in add-multi-gpu-back
  .devcontainer/devcontainer.json
  .gitignore
  ci/manylinux/build-gcc7.sh
  oneflow/ir/oneflow-translate/lib/OneFlow/Importer.cpp
Labels: automerge, bug, ci

#8128 add std::inclusive_scan/exclusive_scan for c++14, and other changes
  cmake/third_party.cmake
  oneflow/core/common/cplusplus_17.h
  oneflow/core/common/cplusplus_17_test.cpp
  oneflow/core/intrusive/struct_traits.h
Labels: enhancement, automerge, build, system

#8085 Modify reduce ops
  docs/source/oneflow.rst
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/common.cpp
  oneflow/core/functional/impl/common.h
  oneflow/core/functional/impl/math_functor.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/math_ops.py
  python/oneflow/framework/docstr/reduce_ops.py
  python/oneflow/framework/docstr/tensor.py
  python/oneflow/framework/docstr/tensor_ops.py
  python/oneflow/framework/tensor.py
  python/oneflow/nn/modules/reduce_ops.py
  python/oneflow/nn/modules/roll.py
  python/oneflow/test/exceptions/test_reduce_ops.py
  python/oneflow/test/modules/test_logical_reduce.py
Labels: enhancement, automerge, eager, op

#8132 [primitive] add log_softmax/softmax and copynd test
  oneflow/core/ep/test/primitive/copy_nd_test.cpp
  oneflow/core/ep/test/primitive/softmax_backward_test.cpp
  oneflow/core/ep/test/primitive/softmax_test.cpp
Labels: enhancement, automerge, op

#8138 add ONEFLOW_TEST_GC_INTERVAL
  python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py
Labels: enhancement, automerge, ci

#8117 Add multi gpu back in CI
  .devcontainer/devcontainer.json
  .github/workflows/simple.yml
  .github/workflows/test.yml
  ci/test/2node_op_test_multi_client.sh
  ci/test/expensive_generic_test_multi_client.sh
  ci/test/generic_test_multi_client.sh
  ci/test/multi_launch.py
  python/oneflow/test/graph/test_comb1to2d.py
  python/oneflow/test/graph/test_comb2d.py
  python/oneflow/test/graph/test_graph_clip_grad_norm.py
  python/oneflow/test/modules/test_comb2to2d.py
  python/oneflow/test/modules/test_consistent_cumsum.py
  python/oneflow/test/modules/test_consistent_einsum_alphaflod_usecase5.py
  python/oneflow/test/modules/test_consistent_median.py
  python/oneflow/test/modules/test_consistent_randperm.py
  python/oneflow/test/modules/test_parital_fc.py
  python/oneflow/test/modules/test_shutting_down.py
Labels: enhancement, automerge, ci, need-all-tests-even-fail

#8139 Memcpy/Memset use primitive
  oneflow/core/kernel/new_kernel_util.cpp
  oneflow/core/kernel/new_kernel_util.cu
  oneflow/core/kernel/new_kernel_util.h
Labels: enhancement, automerge, system, primitive

#8144 Fix permute testcase
  python/oneflow/test/modules/test_chunk.py
  python/oneflow/test/tensor/test_tensor_part_2.py
Labels: automerge, bug, op, test

#8137 [primitive] add matmul test
  oneflow/core/ep/test/primitive/matmul_test.cpp
Labels: enhancement, automerge, op

#8136 fix cumprod bug
  oneflow/user/kernels/cum_backward_kernel.cu
  python/oneflow/test/modules/test_cum_ops.py
Labels: automerge, bug, op

#8119 dev cosine_similarity
  docs/source/functional.rst
  docs/source/nn.rst
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  python/oneflow/framework/docstr/distance.py
  python/oneflow/nn/__init__.py
  python/oneflow/nn/functional/__init__.py
  python/oneflow/nn/modules/distance.py
  python/oneflow/test/exceptions/test_cosine_similarity.py
  python/oneflow/test/modules/test_cosine_similarity.py
Labels: enhancement, automerge, eager, op, api

#8140 Aligned tensor.add method
  python/oneflow/framework/docstr/math_ops.py
  python/oneflow/framework/tensor.py
Labels: enhancement, automerge, op

#8156 fix one embedding update kernel
  oneflow/user/kernels/one_embedding_update_kernels.cu
Labels: automerge, bug, op

#8127 Enable nhwc and constant folding in ci
  .github/workflows/test.yml
  oneflow/ir/lib/OneFlow/Passes.cpp
Labels: enhancement, ci, ir

#8153 Fix consistent bug of GetItem
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/core/functional/tensor_index.cpp
  oneflow/core/functional/tensor_index.h
Labels: enhancement, automerge, bug, op

#8109 [primitive] add binary tests
  oneflow/core/ep/cpu/primitive/broadcast_elementwise_binary.cpp
  oneflow/core/ep/test/primitive/binary_test.cpp
  oneflow/core/thread/thread_manager.h
Labels: enhancement, automerge, op, primitive

#8047 Add profiler
  dev-requirements.txt
  oneflow/api/python/profiler.cpp
  oneflow/core/eager/opkernel_instruction_type.cpp
  oneflow/core/profiler/collection.cpp
  oneflow/core/profiler/collection.h
  oneflow/core/profiler/profiler.cpp
  oneflow/core/profiler/profiler.h
  oneflow/core/profiler/util.h
  python/oneflow/profiler/__init__.py
  python/oneflow/profiler/events.py
  python/oneflow/profiler/profiler.py
  python/oneflow/profiler/util.py
  python/oneflow/test/profiler/test_events.py
  python/oneflow/test/profiler/test_profile_lenet.py
  python/setup.py
  tools/check_src.py
Labels: feature, automerge, system

#8143 [primitive] add cast test
  .github/workflows/test.yml
  oneflow/core/ep/test/primitive/cast_test.cpp
Labels: enhancement, automerge, op

#8141 Remove NewKernelUtil::DnnIf
  oneflow/core/autograd/gradient_funcs/cublas_fused_mlp.cpp
  oneflow/core/job_rewriter/auto_mixed_precision_lists.cpp
  oneflow/core/kernel/new_kernel_util.h
  oneflow/core/kernel/util/cuda_dnn_interface.cu
  oneflow/core/kernel/util/cuda_dnn_interface.h
  oneflow/core/kernel/util/host_dnn_interface.cpp
  oneflow/core/kernel/util/host_dnn_interface.h
  oneflow/core/kernel/util/interface_bridge.h
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/sigmoid_kernel.cpp
  oneflow/user/kernels/test_kernels.cpp
  oneflow/user/ops/sigmoid_op.cpp
  oneflow/user/ops/test_ops.cpp
  oneflow/xrt/api.cpp
Labels: purge, automerge, system

#8071 Use onednn softmax
  oneflow/core/ep/cpu/primitive/softmax.cpp
  python/oneflow/nn/modules/sparse_softmax_cross_entropy.py
Labels: enhancement, automerge, op, primitive

#8145 Remove AvailableMemDesc
  oneflow/core/job/available_memory_desc.proto
  oneflow/core/job/improver.cpp
  oneflow/core/job/improver.h
  oneflow/core/job/oneflow.cpp
  oneflow/core/job/session_global_objects_scope.cpp
Labels: purge, automerge, system

#8157 Remove NewKernelUitl::ArithemeticIf
  oneflow/core/kernel/new_kernel_util.h
  oneflow/core/kernel/util/arithemetic_interface.h
  oneflow/core/kernel/util/cuda_arithemetic_interface.cu
  oneflow/core/kernel/util/cuda_arithemetic_interface.h
  oneflow/core/kernel/util/host_arithemetic_interface.cpp
  oneflow/core/kernel/util/host_arithemetic_interface.h
  oneflow/core/kernel/util/interface_bridge.h
  oneflow/user/kernels/scalar_by_tensor_kernel.cpp
Labels: enhancement, automerge, system

#8108 Add Permute and Elementwise primitive test[Primitive]
  oneflow/core/ep/cpu/primitive/elementwise_unary.cpp
  oneflow/core/ep/test/primitive/elementwise_unary_test.cpp
  oneflow/core/ep/test/primitive/permute_test.cpp
Labels: enhancement, automerge, op, test

#8073 Dev support tensor pin memory
  docs/source/tensor.rst
  oneflow/api/cpp/framework/graph.cpp
  oneflow/api/cpp/framework/tensor.cpp
  oneflow/api/python/framework/tensor.cpp
  oneflow/api/python/functional/indexing.cpp
  oneflow/api/python/functional/tensor_api.cpp
  oneflow/api/python/functional/tensor_api.yaml
  oneflow/api/python/utils/tensor_utils.cpp
  oneflow/core/autograd/gradient_funcs/narrow.cpp
  oneflow/core/boxing/asymmetric_broadcast.cpp
  oneflow/core/boxing/cuda_copy_boxing_interpreter.cpp
  oneflow/core/device/cpu_device_context.h
  oneflow/core/eager/eager_blob_object.cpp
  oneflow/core/eager/eager_blob_object.h
  oneflow/core/eager/opkernel_instruction_type.cpp
  oneflow/core/framework/op_interpreter.h
  oneflow/core/framework/op_interpreter/eager_mirrored_op_interpreter.cpp
  oneflow/core/framework/op_interpreter/eager_mirrored_op_interpreter.h
  oneflow/core/framework/random_generator_impl.cpp
  oneflow/core/framework/tensor.cpp
  oneflow/core/framework/tensor.h
  oneflow/core/framework/tensor_impl.cpp
  oneflow/core/framework/tensor_impl.h
  oneflow/core/framework/tensor_methods.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/core/functional/impl/common.cpp
  oneflow/core/vm/cuda_host_allocator.cpp
  oneflow/ir/lib/OneFlow/OneFlowSupport.cpp
  python/oneflow/framework/docstr/tensor.py
  python/oneflow/nn/modules/empty.py
  python/oneflow/test/tensor/test_tensor_pin_memory.py
Labels: enhancement, eager, op, api

#8051 optimize dot check msg
  oneflow/user/ops/dot_op.cpp
  python/oneflow/test/exceptions/test_dot.py
Labels: enhancement, automerge, op, need-check-error-message

#8165 Revert cublas_fused_mlp.cpp
  oneflow/core/autograd/gradient_funcs/cublas_fused_mlp.cpp
Labels: automerge, bug, op

#8151 Remove legacy model io
  oneflow/core/job/model_io_job.cpp
  oneflow/core/job/model_io_job.h
  oneflow/core/job/model_io_v2_job.cpp
  oneflow/core/job/model_io_v2_job.h
  oneflow/core/job/oneflow.cpp
  oneflow/core/job/resource.proto
  oneflow/core/kernel/kernel_util.cpp
  oneflow/core/kernel/kernel_util.cu
  oneflow/core/kernel/kernel_util.h
  oneflow/core/kernel/model_init_kernel.cpp
  oneflow/core/kernel/model_io_v2_kernel.cpp
  oneflow/core/kernel/model_load_kernel.cpp
  oneflow/core/kernel/model_save_kernel.cpp
  oneflow/core/kernel/new_kernel_util.cpp
  oneflow/core/kernel/new_kernel_util.h
  oneflow/core/operator/model_init_op.cpp
  oneflow/core/operator/model_io_v2_op.cpp
  oneflow/core/operator/model_load_op.cpp
  oneflow/core/operator/model_save_op.cpp
  oneflow/core/operator/op_conf.proto
  oneflow/core/persistence/snapshot.cpp
  oneflow/core/persistence/snapshot.h
Labels: purge, automerge, system

#7818 Add more eager global test
  oneflow/user/kernels/slice_kernel.cpp
  python/oneflow/test/modules/test_consistent_sign.py
  python/oneflow/test/modules/test_consistent_slice.py
Labels: enhancement, automerge, eager, test

#8154 [primitive] add broadcast matmul and batch_matmul test
  oneflow/core/ep/test/primitive/batch_matmul_test.cpp
  oneflow/core/ep/test/primitive/broadcast_matmul_test.cpp
Labels: enhancement, automerge, op

#8163 Add sin/cos higher order derivative and fix autograd bugs
  oneflow/api/python/autograd/function_node.cpp
  oneflow/core/autograd/autograd_engine.cpp
  oneflow/core/autograd/gradient_funcs/math_unary_op.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/core/functional/impl/binary_functor.cpp
  oneflow/core/functional/impl/higher_derivative_functor.cpp
  python/oneflow/test/modules/test_consistent_math_op_higher_derivative.py
  python/oneflow/test/modules/test_math_op_higher_derivative.py
Labels: feature, automerge, bug, eager

#7794 Fix RoiAlign sbp infer bug and add eager global test
  oneflow/user/ops/roi_align_op.cpp
  python/oneflow/test/modules/test_consistent_roi_align.py
Labels: automerge, bug, eager, test

#8166 Remove GpuDeviceNum
  oneflow/api/python/env/env.h
  oneflow/api/python/symbol/placement_symbol.cpp
  oneflow/core/ep/common/device_manager_registry.cpp
  oneflow/core/ep/include/device_manager_registry.h
  oneflow/core/job/id_manager.cpp
  oneflow/core/job/id_manager.h
  oneflow/core/job/job_desc.cpp
  oneflow/core/job/parallel_desc.cpp
  oneflow/core/job/plan_util.cpp
  oneflow/core/job/resource_desc.h
Labels: enhancement, automerge, system

#8178 shape.elem_cnt() use int64_t
  oneflow/core/common/shape.h
  oneflow/core/common/shape_test.cpp
Labels: enhancement, automerge, bug, system, need-highest-priority

#8118 Add fill test
  oneflow/core/ep/test/primitive/fill_test.cpp
Labels: enhancement, op

#8185 Fix linalg norm shape bug
  oneflow/core/functional/impl/math_functor.cpp
  python/oneflow/test/modules/test_norm.py
Labels: automerge, bug, eager, api

#8184 Handle cudaErrorNoDevice
  oneflow/core/ep/cuda/cuda_device_manager.cpp
Labels: automerge, bug, system

#8175 Add FTRL optimizer Docs [OneEmbedding]
  python/oneflow/one_embedding.py
Labels: automerge, op, documentation, embedding

#8026 sub support alpha arg
  oneflow/core/autograd/gradient_funcs/variance.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/binary_functor.cpp
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/ir/lib/OneFlow/OneFlowOpFolders.cpp
  python/oneflow/test/modules/test_sub.py
Labels: enhancement, automerge, op

#8187 Fix global module to_global bug
  python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py
Labels: automerge, bug, eager, test

#8198 add protobuf < 4.0
  .devcontainer/devcontainer.json
  dev-requirements.txt
  python/setup.py
Labels: enhancement, automerge, ci, build

#8191 Remove the pointer version of VectorAt&MapAt
  oneflow/core/autograd/autograd_engine.cpp
  oneflow/core/autograd/gradient_funcs/activation.cpp
  oneflow/core/autograd/gradient_funcs/cublas_fused_mlp.cpp
  oneflow/core/autograd/gradient_funcs/fused_dot_feature_interaction.cpp
  oneflow/core/autograd/gradient_funcs/median.cpp
  oneflow/core/autograd/gradient_funcs/scalar_div.cpp
  oneflow/core/common/container_util.h
  oneflow/core/framework/dtype.cpp
  oneflow/core/framework/nn_graph.cpp
  oneflow/core/framework/placement_sbp_util.cpp
  oneflow/core/framework/tensor_methods.cpp
  oneflow/core/functional/impl/activation_functor.cpp
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/core/job/job_builder.cpp
  oneflow/core/job/job_builder.h
  oneflow/core/job_rewriter/fuse_add_to_output_pass.cpp
Labels: enhancement, automerge, system

#8186 fix bbm check info
  oneflow/core/functional/impl/nn_functor.cpp
  python/oneflow/test/exceptions/test_bmm.py
Labels: automerge, bug, eager, api

#8205 fix python arg parser error report
  oneflow/api/python/functional/python_arg_parser.cpp
  oneflow/api/python/functional/python_arg_parser.h
Labels: bug, system

#8174 one_embedding amp default fp16
  oneflow/core/job_rewriter/auto_mixed_precision_lists.cpp
  oneflow/core/job_rewriter/replace_embedding_ops_pass.cpp
  oneflow/user/ops/add_n_op.cpp
  oneflow/user/ops/one_embedding_ops.cpp
Labels: automerge, bug, op, embedding

#8190 Add docs for nn.Module
  python/oneflow/nn/module.py
Labels: enhancement, automerge, eager, documentation

#8208 Fix concat and split_like grad bug
  oneflow/core/autograd/gradient_funcs/split_like.cpp
  oneflow/core/functional/impl/array_functor.cpp
Labels: automerge, bug, eager, op

#8148 Optimize slice and tensor getitem
  oneflow/core/autograd/gradient_funcs/deconv.cpp
  oneflow/core/autograd/gradient_funcs/slice.cpp
  oneflow/core/boxing/symmetric_b_to_s_boxing.cpp
  oneflow/core/framework/op_interpreter/op_interpreter.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/core/functional/tensor_index.cpp
  oneflow/core/functional/tensor_index.h
  oneflow/user/kernels/as_strided_kernel.cu
  python/oneflow/framework/docstr/math_ops.py
  python/oneflow/test/tensor/test_tensor_indexing.py
Labels: enhancement, feature, automerge, eager

#8176 Dev tensor construct support pin memory
  oneflow/api/python/functional/indexing.cpp
  oneflow/api/python/functional/tensor_api.cpp
  oneflow/api/python/functional/tensor_api.yaml
  oneflow/api/python/utils/tensor_utils.cpp
  oneflow/api/python/utils/tensor_utils.h
  oneflow/core/autograd/gradient_funcs/cast.cpp
  oneflow/core/autograd/gradient_funcs/copy.cpp
  oneflow/core/autograd/gradient_funcs/normalization.cpp
  oneflow/core/framework/tensor.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/core/functional/impl/consistent_cast.cpp
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/core/functional/tensor_index.cpp
  oneflow/core/functional/tensor_processor.cpp
  python/oneflow/framework/docstr/tensor.py
  python/oneflow/test/modules/test_view.py
  python/oneflow/test/tensor/test_tensor_pin_memory.py
  python/oneflow/test_utils/automated_test_util/generators.py
  python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py
Labels: enhancement, eager, api

#8211 patch
  oneflow/core/functional/impl/array_functor.cpp
Labels: enhancement, automerge, eager, api

#8066 optimize operations about dataloader
  oneflow/api/python/utils/tensor_utils.cpp
  oneflow/core/functional/impl/array_functor.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/dtype.py
  python/oneflow/nn/modules/as_tensor.py
  python/oneflow/test/expensive/test_util.py
  python/oneflow/test/graph/test_util.py
  python/oneflow/test/modules/test_as_tensor.py
  python/oneflow/test/modules/test_tensor_ops.py
  python/oneflow/test/tensor/test_tensor_part_1.py
  python/oneflow/test_utils/test_util.py
Labels: enhancement, automerge, op

#8177 disable large tensor in autotest
  .devcontainer/devcontainer.json
  .github/workflows/test.yml
  python/oneflow/test/expensive/test_conv3d.py
  python/oneflow/test/expensive/test_permute.py
  python/oneflow/test/modules/test_consistent_addcmul.py
  python/oneflow/test/modules/test_consistent_maxpool.py
  python/oneflow/test/modules/test_consistent_normalize.py
  python/oneflow/test/modules/test_contiguous.py
  python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py
Labels: enhancement, automerge, ci, need-all-tests-even-fail

#8116 Add array functor exception
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/array_functor.cpp
  python/oneflow/framework/docstr/array_ops.py
  python/oneflow/framework/docstr/index_select.py
  python/oneflow/test/exceptions/test_array_functor.py
  python/oneflow/test/modules/test_gather.py
Labels: automerge, bug, eager, api, need-check-error-message

#8195 Support profiling cuda
  oneflow/core/eager/opkernel_instruction_type.cpp
  oneflow/core/profiler/collection.cpp
  oneflow/core/profiler/collection.h
  oneflow/core/profiler/profiler.cpp
  oneflow/core/profiler/profiler.h
  python/oneflow/profiler/__init__.py
  python/oneflow/profiler/events.py
  python/oneflow/profiler/profiler.py
  python/oneflow/test/profiler/test_events.py
  python/oneflow/test/profiler/test_profile_lenet.py
Labels: feature, automerge, system

#8204 [OneEmbedding] optimize unsorted_segment_sum when col is odd
  oneflow/user/kernels/data_shuffle_kernel.cu
  python/oneflow/test/expensive/test_id_shuffle.py
  python/oneflow/test/modules/test_id_shuffle_global.py
Labels: enhancement, automerge, op, embedding

#8161 Add binary functor exception
  cmake/caches/cn/fast/cuda-75-clang.cmake
  oneflow/core/functional/impl/binary_functor.cpp
  oneflow/core/functional/impl/common.cpp
  python/oneflow/test/exceptions/test_binary_functor_exception.py
Labels: enhancement, automerge, bug, eager, api

#8209 Reduce layer norm template size
  oneflow/core/cuda/layer_norm.cuh
Labels: enhancement, op

#8201 Fix hardcoded device type
  oneflow/api/python/utils/tensor_utils.cpp
  oneflow/core/ep/common/device_manager_registry.cpp
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/user/ops/copy_op.cpp
Labels: enhancement, automerge, system

#8223 Fix eigen url
  cmake/third_party/absl.cmake
  cmake/third_party/cocoapi.cmake
  cmake/third_party/eigen.cmake
  cmake/third_party/half.cmake
  cmake/third_party/opencv.cmake
  cmake/third_party/re2.cmake
Labels: automerge, bug, build, need-all-tests-even-fail, need-highest-priority

#8215 Refine instantnorm test cases
  python/oneflow/nn/modules/batchnorm.py
  python/oneflow/test/modules/test_instancenorm.py
Labels: bug, eager, test

#8155 test op grad using random data
  oneflow/core/autograd/gradient_funcs/cum_ops.cpp
  oneflow/core/autograd/gradient_funcs/flip.cpp
  oneflow/core/ep/test/primitive/fill_test.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/cum_backward_kernel.cpp
  oneflow/user/kernels/cum_backward_kernel.cu
  oneflow/user/kernels/flip_kernel.cpp
  oneflow/user/kernels/flip_kernel.cu
  oneflow/user/kernels/slice_util.cu
  oneflow/user/ops/cum_ops.cpp
  oneflow/user/ops/flip_op.cpp
  python/oneflow/test/modules/test_consistent_stack.py
  python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py
Labels: enhancement, automerge, test

#7997 add copy button
  .github/workflows/test.yml
  docker/ci/test-v2/requirements.txt
  docker/ci/test/requirements.txt
  docs/requirements.txt
  docs/source/conf.py
Labels: documentation, build

#8217 fix cublas_fused_mlp vectorAt
  oneflow/core/autograd/gradient_funcs/cublas_fused_mlp.cpp
Labels: automerge, bug, op

#8229 Remove unused build to speedup
  .github/workflows/test.yml
  python/oneflow/test/expensive/test_rnn.py
Labels: enhancement, automerge, build

#8181 Fix Stack SBP
  oneflow/user/ops/stack_op.cpp
  python/oneflow/one_embedding.py
Labels: automerge, bug, op

#8242 larger leaky_relu half test tol
  python/oneflow/test/modules/test_activation.py
Labels: enhancement, op

#8218 Remove cfg tools and cfg in cmake
  .github/workflows/simple.yml
  .github/workflows/test.yml
  cmake/cfg.cmake
  cmake/oneflow.cmake
  cmake/op_schema.cmake
  oneflow/api/python/framework/attr_map.cpp
  oneflow/api/python/init.cpp
  oneflow/core/common/cfg.cpp
  oneflow/core/common/cfg.h
  oneflow/core/common/cfg_reflection_test.cpp
  oneflow/core/common/cfg_reflection_test.proto
  oneflow/core/framework/attr_map.cpp
  oneflow/core/framework/attr_map.h
  oneflow/core/framework/attr_map_test.cpp
  oneflow/core/framework/attr_value_accessor.cpp
  oneflow/ir/llvm-in-tree.cmake
  oneflow/xrt/launch_kernel.cpp
  oneflow/xrt/launch_op.cpp
  python/oneflow/support/high_order_bool.py
  python/oneflow/support/pb_util.py
  python/oneflow/test/graph/test_input_op_expr.py
  tools/cfg/copy_proto_python_file.py
  tools/cfg/generate_cfg_head_dir_and_convert_src.py
  tools/cfg/include/oneflow/cfg/map_field.h
  tools/cfg/include/oneflow/cfg/message.h
  tools/cfg/include/oneflow/cfg/pybind_module_registry.h
  tools/cfg/include/oneflow/cfg/repeated_field.h
  tools/cfg/include/oneflow/cfg/shared_pair_iterator.h
  tools/cfg/pybind_module_registry.cpp
  tools/cfg/template/template.cfg.cpp
  tools/cfg/template/template.cfg.h
  tools/cfg/template/template.cfg.pybind.cpp
  tools/cfg/template_convert.py
  tools/cfg/util/__init__.py
  tools/cfg/util/proto_reflect_util.py
Labels: enhancement, automerge, system, need-clean-ccache

#8152 Dev Constant Pad Primitive [Primitve]
  oneflow/core/autograd/gradient_funcs/padding.cpp
  oneflow/core/ep/common/primitive/constant_pad.h
  oneflow/core/ep/cpu/primitive/constant_pad.cpp
  oneflow/core/ep/cuda/primitive/constant_pad.cu
  oneflow/core/ep/include/primitive/constant_pad.h
  oneflow/core/ep/include/primitive/fast_integer_math.h
  oneflow/core/ep/test/primitive/constant_pad_test.cpp
  oneflow/core/functional/impl/nn_grad_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/pad_kernel.cpp
  oneflow/user/ops/pad_op.cpp
  python/oneflow/test/modules/test_constantpad.py
Labels: enhancement, automerge, op, primitive

#8207 auto profiler
  .gitignore
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/core/profiler/collection.cpp
  oneflow/core/profiler/collection.h
  python/oneflow/__init__.py
  python/oneflow/autoprof/__main__.py
  python/oneflow/profiler/profiler.py
  python/oneflow/test/modules/test_activation.py
  python/oneflow/test/modules/test_argmax.py
  python/oneflow/test/modules/test_avgpool.py
  python/oneflow/test/modules/test_conv2d.py
  python/oneflow/test/modules/test_maxpool.py
  python/oneflow/test_utils/automated_test_util/__init__.py
  python/oneflow/test_utils/automated_test_util/profiler.py
  python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py
Labels: feature, automerge, op

#8210 Add exception check for nn grad functor
  oneflow/core/functional/impl/nn_grad_functor.cpp
Labels: enhancement, automerge, eager, op, need-check-error-message

#8243 disable_view_slice_optimization
  oneflow/core/autograd/gradient_funcs/deconv.cpp
  oneflow/core/autograd/gradient_funcs/slice.cpp
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/core/functional/tensor_index.cpp
  python/oneflow/framework/docstr/math_ops.py
Labels: bug, eager, refactor

#8252 Fix blob desc segfault
  oneflow/core/framework/op_interpreter/eager_mirrored_op_interpreter.cpp
  oneflow/core/framework/tensor_meta.h
  oneflow/core/register/blob_desc.cpp
  oneflow/core/register/blob_desc.h
Labels: automerge, bug, system

#8250 add more error info for nn.Graph build
  python/oneflow/nn/graph/graph.py
Labels: enhancement, automerge, api, graph

#8257 annotate cpu bn random backward
  python/oneflow/test/modules/test_batchnorm.py
Labels: enhancement, python

#8214 Dev dataloader support pin memory
  python/oneflow/utils/data/_utils/__init__.py
  python/oneflow/utils/data/_utils/pin_memory.py
  python/oneflow/utils/data/dataloader.py
Labels: enhancement, eager, api

#8228 remove_depreciated_code
  oneflow/api/python/framework/blob_register.cpp
  oneflow/api/python/framework/eager_blob_util.cpp
  oneflow/api/python/framework/foreign_boxing_util.cpp
  oneflow/api/python/framework/instructions_builder.cpp
  oneflow/api/python/framework/object.cpp
  oneflow/api/python/framework/object_storage.cpp
  oneflow/api/python/framework/py_remote_blob.cpp
  oneflow/core/boxing/generic_symmetric_nd_sbp_boxing.cpp
  oneflow/core/eager/foreign_boxing_util.h
  oneflow/core/framework/blob_register.cpp
  oneflow/core/framework/blob_register.h
  oneflow/core/framework/blob_trait.cpp
  oneflow/core/framework/blob_trait.h
  oneflow/core/framework/eager_blob_util.cpp
  oneflow/core/framework/eager_blob_util.h
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/framework/instructions_builder.h
  oneflow/core/framework/object.cpp
  oneflow/core/framework/object.h
  oneflow/core/framework/object_storage.cpp
  oneflow/core/framework/object_storage.h
  oneflow/core/framework/op_arg_util.cpp
  oneflow/core/framework/op_arg_util.h
  oneflow/core/framework/op_interpreter/eager_consistent_op_interpreter.cpp
  oneflow/core/framework/op_interpreter/eager_mirrored_op_interpreter.cpp
  oneflow/core/framework/op_interpreter/lazy_op_interpreter.cpp
  oneflow/core/framework/op_interpreter/op_interpreter.cpp
  oneflow/core/framework/op_interpreter/op_interpreter_util.cpp
  oneflow/core/framework/op_interpreter/op_interpreter_util.h
  oneflow/core/framework/opkernel_object.cpp
  oneflow/core/framework/opkernel_object.h
  oneflow/core/framework/py_blob_desc.cpp
  oneflow/core/framework/py_blob_desc.h
  oneflow/core/framework/py_distribute.cpp
  oneflow/core/framework/py_distribute.h
  oneflow/core/framework/py_remote_blob.cpp
  oneflow/core/framework/py_remote_blob.h
  oneflow/core/framework/tensor_impl.h
  python/oneflow/__init__.py
  tools/functional/generate_functional_api.py
  tools/functional/generate_tensor_api.py
Labels: enhancement, automerge, system

#8254 Record bandwidth in profiler
  oneflow/core/eager/opkernel_instruction_type.cpp
  oneflow/core/profiler/collection.cpp
  oneflow/core/profiler/collection.h
  oneflow/core/profiler/profiler.cpp
  oneflow/core/profiler/profiler.h
  python/oneflow/profiler/events.py
  python/oneflow/profiler/profiler.py
  python/oneflow/test/profiler/test_events.py
  python/oneflow/test/profiler/test_profile_lenet.py
Labels: feature, automerge, system

#8124 Support constant folding in cpp api
  .github/workflows/test.yml
  oneflow/api/common/variable_tensor_mgr.h
  oneflow/api/cpp/framework/graph.cpp
  oneflow/api/python/framework/variable_tensor_mgr.cpp
  oneflow/ir/lib/OneFlow/OneFlowOpFolders.cpp
  oneflow/ir/lib/OneFlow/Passes.cpp
  python/oneflow/nn/graph/graph.py
  python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py
Labels: enhancement, automerge, serving

#8135 Print operators info under modules and graphs
  oneflow/core/job/job.proto
  oneflow/core/job/job_build_and_infer_ctx.cpp
  oneflow/core/job/module_conf.proto
  oneflow/core/job/scope.proto
  python/oneflow/framework/graph_build_util.py
  python/oneflow/nn/graph/block.py
  python/oneflow/nn/graph/graph.py
  python/oneflow/nn/graph/util.py
Labels: enhancement, feature, automerge, graph

#8264 Skip consistent cases might fail
  python/oneflow/test/modules/test_consistent_argmax.py
  python/oneflow/test/modules/test_consistent_median.py
Labels: enhancement, automerge, ci

#8266 Update timeout of module API and gpu wait
  .github/workflows/test.yml
Labels: automerge, bug, ci

#8220 refactor shape proto
  oneflow/core/common/protobuf.cpp
  oneflow/core/common/sequential.proto
  oneflow/core/common/shape.h
  oneflow/core/common/shape.proto
  oneflow/core/common/stride.h
  oneflow/core/framework/user_op_attr.proto
  oneflow/core/register/blob_desc.proto
Labels: enhancement, system, refactor

#8262 Handle cudaErrorNoDevice
  oneflow/core/ep/cuda/cuda_device_manager.cpp
  oneflow/core/job/collective_boxing/scheduler.cpp
Labels: bug, system

#8268 fix circular import issue
  python/oneflow/framework/graph_build_util.py
Labels: automerge, bug, graph

#8251 Fix autotest framework bug
  python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py
Labels: enhancement, feature, automerge, bug, eager, api

#8245 fix consistent median
  oneflow/user/kernels/median_with_indices_kernel.cpp
  oneflow/user/kernels/median_with_indices_kernel.cu
  oneflow/user/ops/median_with_indices_op.cpp
  python/oneflow/test/modules/test_consistent_median.py
Labels: automerge, bug, op, global

#8239 [OneEmbedding] dot feature interaction pooling sum
  oneflow/core/autograd/gradient_funcs/fused_dot_feature_interaction.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/core/functional/impl/nn_grad_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/fused_dot_feature_interaction_kernel.cu
  oneflow/user/ops/fused_dot_feature_interaction_op.cpp
  python/oneflow/one_embedding.py
  python/oneflow/test/modules/test_fused_dot_feature_interaction.py
Labels: enhancement, automerge, op

#8105 fix upsample shape infer bug
  .github/workflows/test.yml
  oneflow/core/autograd/gradient_funcs/activation.cpp
  oneflow/core/autograd/gradient_funcs/upsample.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/upsample_bicubic_2d_kernel.cpp
  oneflow/user/kernels/upsample_bicubic_2d_kernel.cu
  oneflow/user/kernels/upsample_bilinear_2d_kernel.cpp
  oneflow/user/kernels/upsample_bilinear_2d_kernel.cu
  oneflow/user/kernels/upsample_kernel.h
  oneflow/user/kernels/upsample_linear_1d_kernel.cpp
  oneflow/user/kernels/upsample_linear_1d_kernel.cu
  oneflow/user/kernels/upsample_nearest_kernel.cpp
  oneflow/user/kernels/upsample_nearest_kernel.cu
  oneflow/user/kernels/upsample_trilinear_3d_kernel.cpp
  oneflow/user/kernels/upsample_trilinear_3d_kernel.cu
  oneflow/user/ops/upsample_op.cpp
  python/oneflow/nn/modules/interpolate.py
  python/oneflow/nn/modules/upsampling.py
  python/oneflow/test/modules/test_upsample.py
Labels: feature, bug, eager, api

#8057 add TypeException and refine error message
  oneflow/api/python/exception/exception.cpp
  oneflow/api/python/exception/exception.h
  oneflow/api/python/symbol/placement_symbol.cpp
  oneflow/core/common/device_type.h
  oneflow/core/common/error.cpp
  oneflow/core/common/exception.h
  oneflow/core/common/throw.h
  oneflow/core/framework/device.cpp
  oneflow/core/framework/random_generator.cpp
  python/oneflow/test/exceptions/test_device.py
  python/oneflow/test/exceptions/test_pad.py
  python/oneflow/test/modules/test_consistent_argmax.py
Labels: enhancement, automerge, system

#8275 Dev inplace to contiguous
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/array_functor.cpp
  python/oneflow/framework/tensor.py
  python/oneflow/test/modules/test_contiguous.py
Labels: enhancement, automerge, op

#8232 Add SliceBoxingFunctor exception
  oneflow/core/functional/impl/slice_boxing_functor.cpp
Labels: enhancement, eager, need-check-error-message

#8180 Use cpu for slice boxing if device is not cpu and cuda
  oneflow/core/boxing/cuda_copy_boxing_interpreter.cpp
  oneflow/core/boxing/eager_boxing_interpreter_mgr.cpp
  oneflow/core/boxing/naive_b_to_s_boxing.cpp
  oneflow/core/boxing/naive_p_to_b_boxing.cpp
  oneflow/core/boxing/naive_p_to_s_boxing.cpp
  oneflow/core/boxing/naive_s_to_b_boxing.cpp
  oneflow/core/boxing/naive_s_to_p_boxing.cpp
  oneflow/core/boxing/naive_s_to_s_boxing.cpp
  oneflow/core/boxing/slice_boxing_util.cpp
  oneflow/core/boxing/slice_boxing_util.h
Labels: enhancement, automerge, system

#7307 consistent_tensor_ops_test
  oneflow/core/functional/impl/array_functor.cpp
  python/oneflow/test/modules/test_consistent_tensor_ops.py
  python/oneflow/test/modules/test_eager_boxing_exhaustive.py
Labels: enhancement, automerge, test, system, need-clean-ccache

#8288 update readme about xrt
  README.md
Labels: automerge, documentation, system

#8279 fix_autotest_fake_program_bug
  python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py
Labels: automerge, bug, test, api

#8290 fix extra print in autotest
  python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py
Labels: automerge, bug, system

#8270 Use unary primitive in kernel
  oneflow/core/ep/common/primitive/elementwise_unary.h
  oneflow/core/ep/common/primitive/unary_functor.h
  oneflow/core/ep/cpu/primitive/elementwise_unary.cpp
  oneflow/core/ep/cpu/primitive/unary_functor.h
  oneflow/core/ep/cuda/primitive/elementwise_unary.cu
  oneflow/core/ep/cuda/primitive/unary_functor.cuh
  oneflow/core/ep/include/primitive/elementwise_unary.h
  oneflow/core/ep/include/primitive/unary_op.h
  oneflow/core/ep/test/primitive/elementwise_unary_test.cpp
  oneflow/user/kernels/activation_kernels.cpp
  oneflow/user/kernels/activation_kernels.cu
  oneflow/user/kernels/activation_kernels.h
  oneflow/user/kernels/elementwise_xpu_kernel.h
  oneflow/user/kernels/gelu_kernel.cpp
  oneflow/user/kernels/relu_kernel.cpp
  oneflow/user/kernels/tanh_kernel.cpp
  python/oneflow/test/modules/test_activation.py
Labels: enhancement, automerge, system, primitive

#8291 revert fill test deleted by mistake
  oneflow/core/ep/test/primitive/fill_test.cpp
Labels: enhancement, automerge, op, primitive

#8064 refine broadcast ops error message
  oneflow/user/ops/math_binary_broadcast_ops.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/logical_ops.py
  python/oneflow/test/exceptions/test_broadcast_ops.py
Labels: enhancement, automerge, op, need-check-error-message

#8129 add tensor.type function
  docs/source/tensor.rst
  oneflow/api/python/framework/tensor.cpp
  oneflow/api/python/framework/tensortype.cpp
  oneflow/api/python/framework/tensortype.h
  python/oneflow/cuda/type_tensor.py
  python/oneflow/framework/docstr/tensor.py
  python/oneflow/framework/type_tensor.py
  python/oneflow/nn/modules/sparse.py
  python/oneflow/test/modules/test_tensor_ops.py
Labels: enhancement, automerge, system, api, interface

#8292 Dev cast op support stride
  oneflow/core/framework/op_interpreter/eager_mirrored_op_interpreter.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/ops/cast_op.cpp
  python/oneflow/test/modules/test_cast.py
Labels: enhancement, eager, op

#8293 larger fused_dot_feature_interaction_sum tol
  python/oneflow/test/modules/test_fused_dot_feature_interaction.py
Labels: enhancement, automerge, op

#7968 Add oneflow.tensordot interface
  docs/source/oneflow.rst
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/__init__.py
  python/oneflow/framework/docstr/tensordot.py
  python/oneflow/nn/modules/tensordot.py
  python/oneflow/test/exceptions/test_tensordot.py
  python/oneflow/test/modules/test_consistent_tensordot.py
  python/oneflow/test/modules/test_tensordot.py
Labels: enhancement, automerge, op, interface

#8299 Add check for parsed module
  oneflow/ir/oneflow-translate/lib/OneFlow/MLIROneFlowTranslation.cpp
Labels: automerge, bug, serving, ir

#8289 fix tensor size limit resulted from shared memory size
  oneflow/user/kernels/cum_backward_kernel.cu
Labels: automerge, bug, op

#8213 Add no_addend_op_ in NormalizationAddReluGradFunctor
  oneflow/core/autograd/gradient_funcs/normalization_add_relu.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_grad_functor.cpp
Labels: enhancement, automerge, op

#8303 refine autoprof display
  python/oneflow/autoprof/__init__.py
  python/oneflow/autoprof/__main__.py
  python/oneflow/test_utils/automated_test_util/profiler.py
  python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py
Labels: enhancement, automerge, op

#8233 Support out_grad in different dtype with output
  oneflow/api/python/autograd/autograd.cpp
  python/oneflow/test/modules/test_autograd.py
Labels: enhancement, feature, automerge, eager

#8309 Fix different dtype backward bug
  python/oneflow/test/modules/test_autograd.py
Labels: automerge, bug, eager

#8304 refactor reshape use python c api
  oneflow/api/python/framework/tensor.cpp
  oneflow/api/python/framework/tensor_functions.cpp
  python/oneflow/framework/tensor.py
  python/oneflow/test/tensor/test_tensor_part_1.py
Labels: enhancement, eager, op

#7930 Merge ccl and nccl boxing function
  oneflow/core/boxing/ccl_boxing_function.cpp
  oneflow/core/boxing/eager_boxing_interpreter_mgr.cpp
  oneflow/core/boxing/nccl_boxing_function.cpp
  python/oneflow/test/modules/test_consistent_cast.py
Labels: enhancement, automerge, system

#8258 move pybind11/Python api to cpython
  oneflow/api/python/framework/tensor.cpp
  oneflow/api/python/framework/tensor_functions.cpp
  python/oneflow/framework/tensor.py
  python/oneflow/nn/modules/math_ops.py
Labels: enhancement, automerge, system, api, python

#8310 fix libai load checkpoint with extra memory occupy on gpu 0
  python/oneflow/nn/optimizer/optimizer.py
Labels: automerge, bug, eager

#8319 Add skip for test_functional_conv_transpose3d
  python/oneflow/test/expensive/test_convtranspose.py
Labels: automerge, bug, python

#8312 liboneflow as shared
  cmake/oneflow.cmake
  python/oneflow/framework/sysconfig.py
  python/oneflow/sysconfig.py
  tools/generate_pip_version.py
Labels: enhancement, automerge, build, system

#8306 upgrade clang-tidy
  .github/workflows/simple.yml
  .github/workflows/test.yml
Labels: enhancement, automerge, ci

#8314 fix flow.load in multi nodes and add test
  python/oneflow/framework/check_point_v2.py
  python/oneflow/test/modules/test_module.py
Labels: automerge, bug, system

#8320 Fix autoprof when no kernel, and fix input shapes
  python/oneflow/autoprof/__main__.py
  python/oneflow/test/modules/test_activation.py
  python/oneflow/test/modules/test_avgpool.py
  python/oneflow/test/modules/test_conv2d.py
  python/oneflow/test/modules/test_maxpool.py
  python/oneflow/test/modules/test_reshape.py
Labels: enhancement, automerge, op

#8297 move logical op dostring, and refine docstr file
  python/oneflow/framework/docstr/__init__.py
  python/oneflow/framework/docstr/logical_ops.py
  python/oneflow/framework/docstr/math_ops.py
Labels: automerge, eager, documentation, python

#8164 Move RNN implementation to C++ & add RNNCell modules
  oneflow/core/autograd/gradient_funcs/fused_gru_cell.cpp
  oneflow/core/autograd/gradient_funcs/fused_lstm_cell.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/core/functional/impl/rnn_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/fused_gru_cell_kernel.cu
  oneflow/user/kernels/fused_lstm_cell_kernel.cu
  oneflow/user/kernels/fused_rnn_cell_kernel_util.h
  oneflow/user/ops/fused_gru_cell_op.cpp
  oneflow/user/ops/fused_lstm_cell_op.cpp
  oneflow/user/ops/stack_op.cpp
  python/oneflow/nn/__init__.py
  python/oneflow/nn/modules/rnn.py
  python/oneflow/nn/utils/rnn.py
  python/oneflow/test/expensive/test_rnn.py
  python/oneflow/test/expensive/test_rnn_cell.py
  python/oneflow/test/expensive/test_rnn_pack_sequence.py
  python/oneflow/test/expensive/test_rnn_utils.py
  python/oneflow/test/modules/test_consistent_rnn.py
  python/oneflow/test/modules/test_consistent_rnn_cell.py
  python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py
Labels: feature, automerge, eager, op, api

#8317 Refactor more ops use python c api
  oneflow/api/python/framework/tensor.cpp
  oneflow/api/python/framework/tensor_functions.cpp
  oneflow/core/functional/impl/common.cpp
  python/oneflow/framework/tensor.py
  python/oneflow/test/tensor/test_tensor_part_1.py
Labels: enhancement, automerge, eager, op

#8322 Add cuda synchronize api
  docs/source/cuda.rst
  oneflow/api/python/env/env.cpp
  oneflow/core/device/cuda_util.cpp
  oneflow/core/device/cuda_util.h
  python/oneflow/cuda/__init__.py
  python/oneflow/cuda/_utils.py
  python/oneflow/test/misc/test_env_cuda.py
Labels: enhancement, automerge, op, api

#8226 Fix Swin-T 3D parallel deadlock
  oneflow/core/job_rewriter/insert_nccl_logical_op_pass.cpp
  oneflow/core/lazy/actor/repeat_actor.cpp
Labels: automerge, bug, graph

#8300 Use primitive in all activation kernels
  oneflow/core/ep/common/primitive/elementwise_unary.h
  oneflow/core/ep/common/primitive/unary_functor.h
  oneflow/core/ep/cuda/primitive/unary_functor.cuh
  oneflow/core/ep/include/primitive/unary_op.h
  oneflow/user/kernels/activation_kernels.cpp
  oneflow/user/kernels/activation_kernels.cu
  oneflow/user/kernels/activation_kernels.h
Labels: enhancement, automerge, op, system, primitive

#8326 make of_pyext_obj and of_protoobj shared library
  cmake/oneflow.cmake
  python/oneflow/framework/sysconfig.py
Labels: automerge, bug, build

#7926 Add runtime error info in eager boxing
  oneflow/core/boxing/asymmetric_broadcast.cpp
  oneflow/core/boxing/boxing_dividor_util.cpp
  oneflow/core/boxing/boxing_interpreter_status.cpp
  oneflow/core/boxing/ccl_boxing_function.cpp
  oneflow/core/boxing/cuda_copy_boxing_interpreter.cpp
  oneflow/core/boxing/eager_boxing_interpreter.cpp
  oneflow/core/boxing/eager_boxing_interpreter_mgr.cpp
  oneflow/core/boxing/flatten_hierarchy.cpp
  oneflow/core/boxing/generic_symmetric_nd_sbp_boxing.cpp
  oneflow/core/boxing/identity_boxing_interpreter.cpp
  oneflow/core/boxing/naive_1_to_p_boxing.cpp
  oneflow/core/boxing/naive_b_to_1_boxing.cpp
  oneflow/core/boxing/naive_b_to_s_boxing.cpp
  oneflow/core/boxing/naive_p_to_b_boxing.cpp
  oneflow/core/boxing/naive_p_to_s_boxing.cpp
  oneflow/core/boxing/naive_s_to_b_boxing.cpp
  oneflow/core/boxing/naive_s_to_p_boxing.cpp
  oneflow/core/boxing/naive_s_to_s_boxing.cpp
  oneflow/core/boxing/nd_sbp_dim_reduce_boxing.cpp
  oneflow/core/boxing/one_to_one_boxing.cpp
  oneflow/core/boxing/symmetric_acyclic_nd_sbp_boxing.cpp
  oneflow/core/boxing/symmetric_b_to_p_boxing.cpp
  oneflow/core/boxing/symmetric_b_to_s_boxing.cpp
  oneflow/core/boxing/symmetric_s_to_p_boxing.cpp
  oneflow/core/boxing/unflatten_hierarchy.cpp
Labels: enhancement, automerge, system, need-check-error-message

#8336 Update libunwind information
  docs/source/troubleshooting.md
Labels: automerge, documentation, system

#8313 Logical slice ops support all nd_sbp
  oneflow/core/boxing/asymmetric_broadcast.cpp
  oneflow/core/boxing/ccl_boxing_function.cpp
  oneflow/core/boxing/naive_b_to_1_boxing.cpp
  oneflow/core/boxing/nccl_boxing_function.cpp
  oneflow/core/boxing/symmetric_b_to_p_boxing.cpp
  oneflow/core/framework/op_interpreter/lazy_op_interpreter.cpp
  oneflow/core/functional/impl/comm_functor.cpp
  oneflow/core/job/nd_sbp_util.cpp
  oneflow/core/job/nd_sbp_util.h
  oneflow/user/kernels/fused_self_attention_query_mul_key_and_value_kernel.cu
  oneflow/user/kernels/slice_kernel.cpp
  oneflow/user/kernels/slice_util.cpp
  oneflow/user/kernels/slice_util.h
  oneflow/user/ops/slice_op.cpp
  python/oneflow/framework/tensor.py
  python/oneflow/test/modules/test_consistent_slice.py
  python/oneflow/test/modules/test_consistent_slice_assign.py
  python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py
Labels: feature, automerge, eager, graph

#8307 [OneEmbedding] fused dot feature interaction tensor core impl
  oneflow/core/autograd/gradient_funcs/fused_dot_feature_interaction.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/core/functional/impl/nn_grad_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/fused_dot_feature_interaction_kernel.cu
  oneflow/user/ops/fused_dot_feature_interaction_op.cpp
  python/oneflow/test/modules/test_fused_dot_feature_interaction.py
Labels: enhancement, automerge, op

#8331 Merge id cache and symbol storage
  oneflow/core/eager/opkernel_instruction_type.cpp
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/framework/instructions_builder.h
  oneflow/core/framework/symbol_id_cache.cpp
  oneflow/core/framework/symbol_id_cache.h
  oneflow/core/framework/symbol_storage_util.cpp
  oneflow/core/framework/symbol_storage_util.h
  oneflow/core/job/env_global_objects_scope.cpp
  oneflow/core/job/job_desc.h
  oneflow/core/job/parallel_desc.h
  oneflow/core/job/scope.cpp
  oneflow/core/job/scope.h
  oneflow/core/job_rewriter/generate_backward_and_optimizer_op_confs.cpp
  oneflow/core/operator/op_conf_symbol.cpp
  oneflow/core/operator/op_conf_symbol.h
  oneflow/core/operator/op_node_signature_desc.cpp
  oneflow/core/operator/op_node_signature_desc.h
  oneflow/core/vm/symbol_storage.cpp
  oneflow/core/vm/symbol_storage.h
Labels: enhancement, automerge, system
