Repository Oneflow-Inc/oneflow, pull requests merged in 2022-06, with the labels that each got.

#8318 Feat/logical nccl send recv
  oneflow/core/auto_parallel/boxing_collector.cpp
  oneflow/core/boxing/asymmetric_broadcast.cpp
  oneflow/core/boxing/ccl_boxing_function.cpp
  oneflow/core/boxing/naive_1_to_p_boxing.cpp
  oneflow/core/boxing/naive_b_to_1_boxing.cpp
  oneflow/core/boxing/nccl_boxing_function.cpp
  oneflow/core/boxing/symmetric_b_to_p_boxing.cpp
  oneflow/core/functional/impl/comm_functor.cpp
  oneflow/core/job/nd_sbp_util.cpp
  oneflow/core/job/nd_sbp_util.h
  oneflow/core/job_rewriter/boxing_with_middle_nodes.cpp
  oneflow/core/job_rewriter/insert_nccl_logical_op_pass.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/nccl_logical_send_recv_kernel.cpp
  oneflow/user/ops/nccl_logical_ops.cpp
  python/oneflow/test/graph/test_nccl_logical_send_recv.py
Labels: feature, automerge, op, graph, global

#8332 Refine profiler
  oneflow/core/profiler/collection.cpp
  oneflow/core/profiler/collection.h
  oneflow/core/profiler/event.cpp
  oneflow/core/profiler/event.h
  python/oneflow/autoprof/__main__.py
  python/oneflow/profiler/events.py
  python/oneflow/test/profiler/test_events.py
  python/oneflow/test/profiler/test_profile_lenet.py
  python/oneflow/test_utils/automated_test_util/profiler.py
Labels: enhancement, automerge, system

#8315 Move pybind/python api to cpython [part2]
  oneflow/api/python/framework/tensor_functions.cpp
  oneflow/core/functional/functional_api.yaml
  python/oneflow/framework/tensor.py
Labels: enhancement, automerge, api, python

#8075 Add onednn softmax backward
  oneflow/core/ep/cpu/primitive/softmax.cpp
  oneflow/core/ep/cpu/primitive/softmax_backward.cpp
Labels: enhancement, automerge, op, primitive

#8324 Add repeat interleave op
  docs/source/oneflow.rst
  docs/source/tensor.rst
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/cum_forward_kernel.cpp
  oneflow/user/kernels/cum_forward_kernel.cu
  oneflow/user/kernels/repeat_interleave_kernel.cpp
  oneflow/user/kernels/repeat_interleave_kernel.cu
  oneflow/user/ops/repeat_interleave_op.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/__init__.py
  python/oneflow/framework/docstr/repeat_interleave.py
  python/oneflow/framework/docstr/tensor.py
  python/oneflow/framework/tensor.py
  python/oneflow/test/exceptions/test_repeat_interleave.py
  python/oneflow/test/modules/test_repeat_interleave.py
  python/oneflow/test/tensor/test_tensor_part_2.py
Labels: enhancement, feature, eager, api

#8346 Fix UnaryFunctor NaN propagation
  oneflow/core/ep/common/primitive/unary_functor.h
Labels: automerge, bug, op, primitive

#8348 Scalar::As() support being called in device
  oneflow/api/python/functional/dispatch_stateful_ops.cpp
  oneflow/core/common/scalar.cpp
  oneflow/core/common/scalar.h
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/core/functional/impl/eye_functor.cpp
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/core/functional/impl/nn_functor.cpp
Labels: enhancement, automerge, system, primitive

#8340 Fix constant folding test
  oneflow/ir/test/OneFlow/folding/test_simple_multiply.py
Labels: enhancement, automerge, bug, test

#8345 Make libproto shared to prevent collision of static global variables
  cmake/third_party/protobuf.cmake
Labels: enhancement, automerge, build

#8354 remove pad ndim check
  oneflow/core/functional/impl/nn_functor.cpp
Labels: automerge, bug, eager

#8234 Add Tensor Index exception
  oneflow/core/functional/tensor_index.cpp
  python/oneflow/test/exceptions/test_tensor_index.py
Labels: automerge, bug, eager, need-check-error-message

#8360 optimize index_select/repeat_interleave performance
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/user/kernels/gather_kernel_util.h
Labels: enhancement, bug, eager, api

#8361 add nccl logical 1d P to S(i)
  oneflow/core/job_rewriter/insert_nccl_logical_op_pass.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/nccl_logical_kernels.cpp
  oneflow/user/ops/nccl_logical_ops.cpp
  python/oneflow/test/graph/test_nccl_logical_send_recv.py
Labels: enhancement, op, graph

#8359 rm multiply op
  oneflow/core/autograd/gradient_funcs/multiply.cpp
  oneflow/core/functional/impl/binary_functor.cpp
  oneflow/core/job_rewriter/auto_mixed_precision_lists.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/ir/lib/OneFlow/OneFlowOpFolders.cpp
  oneflow/ir/lib/OneFlow/Passes.cpp
  oneflow/ir/test/OneFlow/folding/test_simple_multiply.py
  oneflow/user/kernels/multiply_kernel.cpp
  oneflow/user/kernels/multiply_kernel.cu
  oneflow/user/kernels/multiply_kernel.h
  oneflow/user/ops/median_op.cpp
  oneflow/user/ops/multiply_op.cpp
  oneflow/user/ops/reduce_ops.cpp
  oneflow/user/ops/scalar_by_tensor_op.cpp
Labels: enhancement, automerge, op

#8193 Disable vm gc cache
  oneflow/core/common/thread_local_guard.h
  oneflow/core/common/thread_local_guard_test.cpp
  oneflow/core/vm/barrier_phy_instr_operand.h
  oneflow/core/vm/instruction.h
  oneflow/core/vm/sequential_instruction_type.cpp
  oneflow/core/vm/virtual_machine.cpp
  oneflow/core/vm/virtual_machine.h
  oneflow/core/vm/virtual_machine_engine.cpp
  oneflow/core/vm/virtual_machine_engine.h
Labels: automerge, bug, system

#8110 Implement oneflow.embedding op
  oneflow/core/autograd/gradient_funcs/embedding.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/core/functional/impl/nn_grad_functor.cpp
  oneflow/core/job/job_build_and_infer_ctx.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/embedding_kernel.cpp
  oneflow/user/kernels/embedding_kernel.cu
  oneflow/user/kernels/embedding_kernel_util.cpp
  oneflow/user/kernels/embedding_kernel_util.cu
  oneflow/user/kernels/embedding_kernel_util.h
  oneflow/user/ops/embedding_op.cpp
  python/oneflow/nn/modules/sparse.py
  python/oneflow/test/modules/test_consistent_sparse.py
  python/oneflow/test/modules/test_sparse.py
Labels: enhancement, automerge, op

#8337 Feat logical slice ops grad
  oneflow/core/autograd/gradient_funcs/logical_slice.cpp
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/user/ops/slice_op.cpp
  python/oneflow/test/modules/test_consistent_slice.py
  python/oneflow/test/modules/test_consistent_slice_assign.py
Labels: feature, automerge, eager, graph

#8272 Refactor IONode in graph util.py
  python/oneflow/nn/graph/block.py
  python/oneflow/nn/graph/graph.py
  python/oneflow/nn/graph/util.py
  python/oneflow/test/graph/test_graph_io_check.py
Labels: enhancement, refactor, graph

#8372 Add distributed optional run
  .github/workflows/test.yml
  python/oneflow/test/modules/test_consistent_diagonal.py
Labels: enhancement, ci, need-test-distributed

#8367 autoprof supports bandwidth
  python/oneflow/autoprof/__main__.py
Labels: enhancement, automerge, op

#7910 Add nn_functor Check
  oneflow/core/functional/impl/nn_functor.cpp
  python/oneflow/test/exceptions/test_nn_functor.py
  python/oneflow/test/modules/test_conv2d.py
Labels: enhancement, automerge, eager, documentation, need-check-error-message

#8370 add api to apply external job pass
  oneflow/api/cpp/framework/graph.cpp
  oneflow/api/cpp/framework/graph.h
Labels: enhancement, automerge, api, serving

#8387 Add condition to find-test-cache-distributed
  .github/workflows/test.yml
Labels: enhancement, automerge, ci, need-test-distributed

#8382 warp dim util
  oneflow/api/python/framework/tensor_functions.cpp
  oneflow/core/common/wrap_dim_utils.h
  oneflow/core/framework/tensor_methods.cpp
  oneflow/core/functional/function_library.h
  oneflow/core/functional/impl/activation_functor.cpp
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/core/functional/impl/common.cpp
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/core/functional/impl/nn_functor.cpp
Labels: enhancement, automerge, eager

#8379 fix_bug_in_broadcast_min_max_grad_and_broadcast_like
  oneflow/core/autograd/gradient_funcs/broadcast_binary_ops.cpp
  oneflow/core/functional/impl/array_functor.cpp
  python/oneflow/test/exceptions/test_array_functor.py
  python/oneflow/test/modules/test_max.py
Labels: automerge, bug, system

#8388 fix bug about index
  oneflow/user/kernels/cum_backward_kernel.cpp
  python/oneflow/test/modules/test_cum_ops.py
Labels: automerge, bug, op

#8344 LogicalSliceAssign support full slice sbp
  oneflow/user/kernels/slice_kernel.cpp
  oneflow/user/ops/slice_op.cpp
  python/oneflow/test/modules/test_consistent_slice.py
  python/oneflow/test/modules/test_consistent_slice_assign.py
Labels: feature, automerge, eager, graph, need-test-distributed

#8391 fix_tensor_from_numpy_mem_leak_bug
  oneflow/api/python/framework/tensor.cpp
  oneflow/api/python/functional/tensor_api.cpp
Labels: automerge, bug, system, need-clean-ccache

#8393 Make of_pyext_obj static only to make sure only a python ext so has python symbols
  cmake/oneflow.cmake
  python/oneflow/framework/sysconfig.py
Labels: automerge, bug, build

#8394 Adjust tolerance setting in embedding_renorm unit test
  python/oneflow/test/modules/test_sparse.py
Labels: automerge, bug, op

#8249 support front end compile for job to iree
  oneflow/api/python/framework/nn_graph.cpp
  oneflow/core/job/job_ir.cpp
  oneflow/core/job/job_ir.h
  oneflow/ir/lib/OneFlow/Conversion/OneFlowToTosa.cpp
  oneflow/ir/lib/OneFlow/OneFlowSupport.cpp
  oneflow/ir/oneflow-extension/ir_pass.cpp
  oneflow/ir/oneflow-translate/include/OneFlow/MLIROneFlowTranslation.h
  oneflow/ir/oneflow-translate/lib/OneFlow/MLIROneFlowTranslation.cpp
  oneflow/ir/test/Frontend/OneFlowToIree.mlir
  oneflow/ir/test/Frontend/lit.local.cfg
  oneflow/ir/test/Frontend/test_iree_resnet.py
  oneflow/ir/test/Frontend/test_iree_runner.py
  oneflow/ir/test/Frontend/test_tosa_to_elf.mlir
  oneflow/ir/test/OneFlow/conversion/OneFlowToTosa.mlir
  oneflow/ir/test/lit.cfg.py
Labels: feature, automerge, ir

#8036 Feat/zero mix with mp
  docs/source/graph.rst
  oneflow/core/job/eager_nccl_comm_manager.cpp
  oneflow/core/job/job_build_and_infer_ctx.cpp
  oneflow/core/job/job_builder.cpp
  oneflow/core/job/job_conf.proto
  oneflow/core/job_rewriter/optimizer_placement_optimization_pass.cpp
  oneflow/user/ops/stack_op.cpp
  python/oneflow/framework/multi_client_session.py
  python/oneflow/nn/graph/graph_config.py
  python/oneflow/test/graph/test_graph_zero.py
  python/oneflow/test/graph/test_optimization_conf.py
Labels: enhancement, automerge, system, graph

#8374 Revert embedding normal path and fix amp list
  oneflow/core/job_rewriter/auto_mixed_precision_lists.cpp
  oneflow/user/kernels/gather_kernel_util.cpp
  python/oneflow/nn/modules/sparse.py
Labels: enhancement, automerge, op

#8365 replace fixed_vector with small_vector and make Shape inherit from it
  cmake/oneflow.cmake
  cmake/op_schema.cmake
  cmake/util.cmake
  oneflow/core/autograd/gradient_funcs/normalization.cpp
  oneflow/core/common/fixed_vector.h
  oneflow/core/common/fixed_vector_test.cpp
  oneflow/core/common/shape.cpp
  oneflow/core/common/shape.h
  oneflow/core/common/shape_vec.h
  oneflow/core/common/shape_view.cpp
  oneflow/core/common/small_vector.h
  oneflow/core/ep/cpu/primitive/broadcast_elementwise_binary.cpp
  oneflow/core/framework/tensor_methods.cpp
  oneflow/extension/python/numpy_internal.h
  oneflow/ir/install-llvm.cmake
  oneflow/user/kernels/arg_where_kernel_util.cpp
  oneflow/user/kernels/arg_where_kernel_util.cu
  oneflow/user/kernels/avg_pool_kernel_util.h
  oneflow/user/kernels/dim_gather_kernels.cpp
  oneflow/user/kernels/dim_scatter_kernels.cpp
  oneflow/user/kernels/dim_scatter_scalar_kernels.cpp
  oneflow/user/kernels/image_preprocess_kernels.cu
  oneflow/user/kernels/max_pool_kernel_util.h
  oneflow/user/ops/arange_op.cpp
  oneflow/user/ops/constant_op.cpp
  oneflow/user/ops/distributions/normal_op.cpp
  oneflow/user/ops/distributions/uniform_int_op.cpp
  oneflow/user/ops/distributions/uniform_op.cpp
  oneflow/user/ops/eager_nccl_ops.cpp
  oneflow/user/ops/empty_op.cpp
  oneflow/user/ops/image_preprocess_ops.cpp
  oneflow/user/ops/randperm_op.cpp
  oneflow/user/utils/pool_util.h
Labels: enhancement, automerge, system, refactor

#8396 Light plan for debug
  oneflow/core/framework/nn_graph.cpp
  oneflow/core/job/plan_util.cpp
  oneflow/core/job/plan_util.h
Labels: feature, automerge, graph

#8400 disable terminfo to fix missing terminfo symbols
  oneflow/ir/install-llvm.cmake
  oneflow/ir/llvm-in-tree.cmake
Labels: automerge, bug, build

#8404 fix bug of ZeRO MP in complex case
  oneflow/core/graph/op_graph.cpp
  oneflow/core/job_rewriter/optimizer_placement_optimization_pass.cpp
Labels: automerge, bug, graph

#8409 Remove redundant output_lbns in ir
  oneflow/ir/lib/OneFlow/OneFlowOps.cpp
  oneflow/ir/test/OneFlow/cuda_code_gen/test_fuser_cast_scale.py
Labels: enhancement, automerge, ir

#8335 Dev FusedCrossInteraction[OneEmbedding]
  oneflow/core/autograd/gradient_funcs/fused_cross_interaction.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/core/functional/impl/nn_grad_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/fused_cross_feature_interaction.cu
  oneflow/user/kernels/fused_cross_feature_interaction_grad.cu
  oneflow/user/ops/fused_cross_feature_interaction_op.cpp
  python/oneflow/test/modules/test_fused_cross_interaction.py
Labels: enhancement, automerge, op, embedding

#8002 add exe graph physical shape check msg
  oneflow/core/common/error_util.cpp
  oneflow/core/graph/exec_graph.cpp
Labels: feature, automerge, tooling, graph

#8385 add batch_matmul sbp
  oneflow/user/ops/matmul_op.cpp
Labels: enhancement, automerge, op

#8401 suppress gcc11 false positive warning
  oneflow/core/common/cached_caller.h
Labels: automerge, bug, build

#8412 fix variable op conversion to tosa error in ninja c1
  oneflow/api/common/variable_tensor_mgr.h
  oneflow/api/python/framework/variable_tensor_mgr.cpp
  oneflow/core/framework/variable_tensor_mgr.cpp
  oneflow/core/framework/variable_tensor_mgr.h
  oneflow/ir/include/OneFlow/OneFlowOps.td
  oneflow/ir/lib/OneFlow/Conversion/OneFlowToTosa.cpp
  oneflow/ir/test/Frontend/test_iree_resnet.py
  python/oneflow/nn/graph/graph.py
Labels: automerge, bug, ir

#8413 Fix eval error in FusedMLP
  python/oneflow/nn/modules/fused_mlp.py
Labels: enhancement, automerge, op, embedding

#8420 Refine hardcoded attr setting/getting in ir
  oneflow/ir/lib/OneFlow/OneFlowOpFolders.cpp
  oneflow/ir/lib/OneFlow/Passes.cpp
  oneflow/ir/oneflow-translate/lib/OneFlow/Importer.cpp
Labels: enhancement, automerge, ir

#8423 Replace cu115 with cu116 in nightly
  .github/workflows/canary.yml
  .github/workflows/on_merge.yml
  .github/workflows/release.yml
  .github/workflows/simple.yml
  .github/workflows/test.yml
Labels: enhancement, automerge, ci

#8414 fix repeat interleave 0-size tensor bug
  oneflow/core/functional/impl/array_functor.cpp
  python/oneflow/test/modules/test_repeat_interleave.py
Labels: enhancement, automerge, bug, eager, api

#8383 Autotest support print input in ci
  python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py
Labels: automerge, bug, eager, test, api

#8131 Feat/graph logical op debug repr
  oneflow/api/python/framework/dtype.cpp
  oneflow/api/python/framework/nn_graph.cpp
  oneflow/api/python/symbol/placement_symbol.cpp
  oneflow/core/framework/dtype.cpp
  oneflow/core/job/job_build_and_infer_ctx.cpp
  oneflow/core/job/job_builder.cpp
  oneflow/core/job/job_builder.h
  oneflow/core/job/module_conf.proto
  oneflow/core/job/plan_util.cpp
  python/oneflow/framework/graph_build_util.py
  python/oneflow/nn/graph/block.py
  python/oneflow/nn/graph/graph.py
  python/oneflow/nn/graph/util.py
  python/oneflow/test/expensive/test_id_shuffle.py
  python/oneflow/test/graph/test_graph_linear_train.py
  python/oneflow/test/graph/test_graph_zero.py
Labels: feature, automerge, tooling, graph

#8425 rm some test case in test_fused_dot_feature_interaction_pooling_sum
  python/oneflow/test/modules/test_fused_dot_feature_interaction.py
Labels: enhancement, automerge, op

#8426 Remove unused linkages
  cmake/oneflow.cmake
Labels: automerge, bug, ci

#8402 refactor stride
  oneflow/api/python/framework/tensor.cpp
  oneflow/api/python/functional/tensor_api.cpp
  oneflow/api/python/utils/tensor_utils.h
  oneflow/core/common/stride.cpp
  oneflow/core/common/stride.h
  oneflow/core/framework/placement_sbp_util.cpp
  oneflow/core/framework/tensor_meta.cpp
  oneflow/core/framework/tensor_methods.cpp
  oneflow/core/functional/impl/common.cpp
  oneflow/core/functional/impl/consistent_cast.cpp
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/core/functional/tensor_index.cpp
  oneflow/extension/python/numpy.cpp
  oneflow/extension/python/numpy_internal.h
  oneflow/user/kernels/to_contiguous_kernel.cpp
Labels: enhancement, automerge, op, system

#8375 Move Tensor.__setitem__ and global related api to Python/C api
  oneflow/api/python/framework/tensor.cpp
  oneflow/api/python/framework/tensor_functions.cpp
  python/oneflow/framework/tensor.py
  python/oneflow/test/exceptions/test_local_global_convert_error.py
Labels: enhancement, automerge, api, python

#8427 cuda add default error msg
  oneflow/core/device/cuda_util.cpp
Labels: enhancement, automerge, system

#8302 turn on view slice
  oneflow/core/framework/op_interpreter.h
  oneflow/core/framework/op_interpreter/op_interpreter.cpp
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/core/functional/impl/consistent_cast.cpp
  oneflow/core/functional/impl/math_functor.cpp
Labels: bug, eager, op

#8415 Add flow env init rdma api
  docs/source/env.rst
  oneflow/api/python/env/env.cpp
  oneflow/core/job/env_global_objects_scope.cpp
  oneflow/core/job/env_global_objects_scope.h
  python/oneflow/env.py
  python/oneflow/utils/data/dataloader.py
Labels: enhancement, automerge, system

#8419 Support iree ci
  .github/workflows/test.yml
  ci/manylinux/build-gcc7.sh
  ci/manylinux/build.sh
  cmake/caches/cn/fast/mlir-cpu.cmake
  oneflow/ir/test/Frontend/test_iree_resnet.py
  oneflow/ir/test/OneFlow/folding/test_conv_bn.py
  oneflow/ir/test/OneFlow/folding/test_simple_multiply.py
  oneflow/ir/test/OneFlow/with_cuda/test_conv_bn_auto_nhwc.py
Labels: feature, automerge, ci

#8347 Feat straighten task nodes
  docs/source/graph.rst
  oneflow/core/graph/graph.h
  oneflow/core/graph/op_graph.cpp
  oneflow/core/graph/straighten_nodes.cpp
  oneflow/core/graph/straighten_nodes.h
  oneflow/core/graph/task_graph.cpp
  oneflow/core/graph/task_graph.h
  oneflow/core/job/compiler.cpp
  oneflow/core/job/job_conf.proto
  python/oneflow/nn/graph/graph_config.py
Labels: feature, automerge, graph

#8380 Refactor NLLLoss to support split class dim
  oneflow/core/autograd/gradient_funcs/nll.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/core/functional/impl/nn_grad_functor.cpp
  oneflow/core/job_rewriter/split_sparse_softmax_cross_entropy_op_pass.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/nll_kernel.cpp
  oneflow/user/kernels/nll_kernel.cu
  oneflow/user/kernels/nll_kernel_util.cpp
  oneflow/user/kernels/nll_kernel_util.cu
  oneflow/user/kernels/nll_kernel_util.h
  oneflow/user/ops/nll_op.cpp
  python/oneflow/nn/modules/loss.py
  python/oneflow/test/modules/test_nll_loss.py
Labels: enhancement, automerge, op

#8441 Strict ordering in memory reuse algorithm
  oneflow/core/job/intra_job_mem_sharing_util.cpp
Labels: enhancement, automerge, graph

#8321 Support broadcast in fused_softmax kernel
  oneflow/core/cuda/softmax.cuh
  oneflow/ir/test/OneFlow/folding/test_conv_bn.py
  oneflow/user/kernels/fused_scale_mask_softmax.cu
  oneflow/user/kernels/fused_scale_mask_softmax.cuh
  oneflow/user/kernels/fused_scale_mask_softmax_dropout.cu
  oneflow/user/ops/fused_scale_mask_softmax_dropout_op.cpp
  oneflow/user/ops/fused_scale_mask_softmax_op.cpp
  python/oneflow/test/modules/test_fused_scale_mask_softmax.py
  python/oneflow/test/modules/test_fused_scale_mask_softmax_dropout.py
Labels: enhancement, feature, automerge, op

#8416 Merge slice and logical slice
  docs/source/oneflow.rst
  oneflow/core/autograd/gradient_funcs/logical_slice.cpp
  oneflow/core/autograd/gradient_funcs/slice.cpp
  oneflow/core/boxing/symmetric_b_to_s_boxing.cpp
  oneflow/core/framework/tensor_methods.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/core/functional/tensor_index.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/slice_kernel.cpp
  oneflow/user/kernels/slice_util.h
  oneflow/user/ops/slice_op.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/math_ops.py
  python/oneflow/framework/tensor_str_util.py
  python/oneflow/nn/modules/slice.py
  python/oneflow/test/README.md
  python/oneflow/test/gen_ops_process.py
  python/oneflow/test/modules/test_consistent_slice.py
  python/oneflow/test/modules/test_consistent_slice_update.py
  python/oneflow/test/modules/test_consistent_stateful_kernel_with_cache.py
  python/oneflow/test/modules/test_hsplit.py
  python/oneflow/test/modules/test_slice.py
  python/oneflow/test/modules/test_stateful_kernel_with_cache.py
  python/oneflow/test/tensor/test_tensor_part_1.py
Labels: feature, automerge, eager, graph, global, need-test-distributed

#8448 Fix a bug in the old version group boxing with 2D SBP
  oneflow/core/boxing/nd_sbp_dim_reduce_boxing.cpp
  oneflow/core/framework/sbp_infer_util.cpp
  oneflow/core/framework/sbp_infer_util.h
  oneflow/core/graph/boxing/hierarchical_sub_task_graph_builder_impl.cpp
  oneflow/core/graph/boxing/hierarchical_sub_task_graph_builder_impl.h
  oneflow/core/job_rewriter/group_boxing_by_dst_parallel.cpp
  oneflow/core/job_rewriter/insert_nccl_logical_op_pass.cpp
  oneflow/core/operator/operator.cpp
Labels: bug, graph

#8442 Graph block.config.set_stage() for recommended Pipeline api.
  docs/source/graph.rst
  python/oneflow/nn/graph/block.py
  python/oneflow/nn/graph/block_config.py
Labels: enhancement, feature, automerge, graph

#8430 Update PolynomialLR's doc and paramater
  python/oneflow/nn/optimizer/polynomial_lr.py
  python/oneflow/test/graph/test_graph_lr_scheduler.py
  python/oneflow/test/graph/test_graph_lrs.py
Labels: automerge, documentation, python

#8456 Fix bugs of patch-sbp_cost
  oneflow/core/framework/sbp_infer_util.cpp
  oneflow/core/job_rewriter/group_boxing_by_dst_parallel.cpp
Labels: bug, graph

#8445 Add mv op
  docs/source/oneflow.rst
  docs/source/tensor.rst
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/math_ops.py
  python/oneflow/framework/docstr/tensor.py
  python/oneflow/framework/tensor.py
  python/oneflow/test/exceptions/test_mv.py
  python/oneflow/test/modules/test_consistent_mv.py
  python/oneflow/test/modules/test_matmul.py
  python/oneflow/test/tensor/test_tensor_part_1.py
Labels: enhancement, automerge, bug, eager, api

#8447 Dev tensor is pinned api
  docs/source/tensor.rst
  oneflow/api/python/framework/tensor.cpp
  oneflow/api/python/functional/tensor_api.cpp
  oneflow/core/framework/tensor.cpp
  oneflow/core/framework/tensor.h
  oneflow/core/framework/tensor_impl.cpp
  oneflow/core/framework/tensor_impl.h
  oneflow/core/framework/tensor_methods.cpp
  oneflow/core/functional/impl/array_functor.cpp
  python/oneflow/framework/docstr/tensor.py
  python/oneflow/test/tensor/test_tensor_pin_memory.py
Labels: enhancement, eager, op, api

#8378 Patch sbp cost
  oneflow/core/boxing/nd_sbp_dim_reduce_boxing.cpp
  oneflow/core/framework/sbp_infer_util.cpp
  oneflow/core/framework/sbp_infer_util.h
  oneflow/core/graph/boxing/hierarchical_sub_task_graph_builder_impl.cpp
  oneflow/core/graph/boxing/hierarchical_sub_task_graph_builder_impl.h
  oneflow/core/job_rewriter/group_boxing_by_dst_parallel.cpp
  oneflow/core/job_rewriter/insert_nccl_logical_op_pass.cpp
  oneflow/core/operator/operator.cpp
Labels: feature, automerge, bug, eager, graph

#8468 speedup global test
  python/oneflow/test/modules/test_consistent_adaptive_pool.py
  python/oneflow/test/modules/test_consistent_rnn_cell.py
  python/oneflow/test/modules/test_consistent_slice.py
  python/oneflow/test/modules/test_consistent_slice_update.py
  python/oneflow/test/modules/test_consistent_var.py
Labels: enhancement, automerge, test

#8451 Set the minimum mtu value for IB communication connection
  oneflow/core/comm_network/ibverbs/ibverbs_comm_network.cpp
  oneflow/core/comm_network/ibverbs/ibverbs_qp.cpp
  oneflow/core/comm_network/ibverbs/ibverbs_qp.h
Labels: enhancement, automerge, bug, system

#8464 [Feat.] Support ZeRO-DP with Pipeline Parallelism
  oneflow/core/job_rewriter/group_boxing_by_dst_parallel.cpp
  oneflow/core/job_rewriter/insert_nccl_logical_op_pass.cpp
  oneflow/core/job_rewriter/optimizer_placement_optimization_pass.cpp
Labels: feature, automerge, graph

#8478 ONEFLOW_EP_CUDA_CUBLAS_WORKSPACE_SIZE_MB
  oneflow/core/ep/cuda/cuda_stream.cpp
Labels: enhancement, automerge, system

#7923 Vm ep
  oneflow/core/common/env_var/env_var.h
  oneflow/core/common/of_unused.h
  oneflow/core/eager/blob_instruction_type.h
  oneflow/core/eager/lazy_job_instruction_type.h
  oneflow/core/eager/release_tensor_instruction_type.h
  oneflow/core/framework/stream_need_soft_sync.h
  oneflow/core/vm/bin_allocator.cpp
  oneflow/core/vm/bin_allocator_test.cpp
  oneflow/core/vm/cpu_stream_type.cpp
  oneflow/core/vm/cpu_stream_type.h
  oneflow/core/vm/cuda_backend_allocator.cpp
  oneflow/core/vm/cuda_copy_d2h_device_context.h
  oneflow/core/vm/cuda_copy_d2h_stream_type.cpp
  oneflow/core/vm/cuda_copy_h2d_stream_type.cpp
  oneflow/core/vm/cuda_optional_event_record_status_querier.cpp
  oneflow/core/vm/cuda_optional_event_record_status_querier.h
  oneflow/core/vm/cuda_stream_handle_device_context.h
  oneflow/core/vm/cuda_stream_type.cpp
  oneflow/core/vm/cuda_stream_type.h
  oneflow/core/vm/ep_backend_allocator.cpp
  oneflow/core/vm/ep_backend_allocator.h
  oneflow/core/vm/ep_backend_host_allocator.cpp
  oneflow/core/vm/ep_backend_host_allocator.h
  oneflow/core/vm/ep_d2h_stream_type.cpp
  oneflow/core/vm/ep_d2h_stream_type.h
  oneflow/core/vm/ep_device_context.h
  oneflow/core/vm/ep_event.cpp
  oneflow/core/vm/ep_event.h
  oneflow/core/vm/ep_optional_event_record_status_querier.cpp
  oneflow/core/vm/ep_optional_event_record_status_querier.h
  oneflow/core/vm/ep_stream_type.cpp
  oneflow/core/vm/ep_stream_type.h
  oneflow/core/vm/event_recorded_cuda_stream_type.cpp
  oneflow/core/vm/event_recorded_ep_stream_type.cpp
  oneflow/core/vm/event_recorded_ep_stream_type.h
  oneflow/core/vm/stream_get_stream_type.h
Labels: enhancement, automerge, eager, system

#8459 Strict order of subgraph after acc
  oneflow/core/job_rewriter/insert_nccl_logical_op_pass.cpp
Labels: automerge, bug, graph

#8455 NCCL logical kernel launch and bool dtype
  oneflow/core/framework/nn_graph.cpp
  oneflow/core/job/compiler.cpp
  oneflow/core/job/compiler.h
  oneflow/core/job/eager_nccl_comm_manager.h
  oneflow/core/job/oneflow.cpp
  oneflow/core/job_rewriter/insert_nccl_logical_op_pass.cpp
  oneflow/user/kernels/nccl_logical_2d_sbp_kernels.cpp
  oneflow/user/kernels/nccl_logical_kernels.cpp
  oneflow/user/kernels/nccl_logical_send_recv_kernel.cpp
  python/oneflow/test/modules/test_sparse.py
Labels: enhancement, automerge, graph

#8461 Update llvm version and refine IREE cases
  ci/manylinux/build.sh
  cmake/oneflow.cmake
  oneflow/ir/include/OneFlow/Passes.h
  oneflow/ir/lib/OneFlow/Passes.cpp
  oneflow/ir/test/Frontend/OneFlowToIree.mlir
  oneflow/ir/test/lit.cfg.py
Labels: enhancement, automerge, ci, ir

#8452 Manually eager mem gc
  oneflow/core/framework/nn_graph.cpp
  oneflow/core/vm/bin_allocator.h
  oneflow/core/vm/lazy_job_device_context.h
  oneflow/core/vm/shrinkable_cache.h
  oneflow/core/vm/thread_safe_allocator.h
  oneflow/core/vm/virtual_machine.cpp
  oneflow/core/vm/virtual_machine.h
Labels: enhancement, feature, bottleneck, automerge, system, graph

#8283 Fix fill_
  oneflow/core/autograd/gradient_funcs/fill.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/fill_kernel.cpp
  oneflow/user/kernels/fill_kernel.cu
  oneflow/user/ops/fill_op.cpp
  python/oneflow/framework/docstr/tensor.py
  python/oneflow/framework/tensor.py
  python/oneflow/test/modules/test_consistent_fill.py
  python/oneflow/test/tensor/test_tensor_part_1.py
Labels: enhancement, automerge, eager

#8481 Force zlib built as shared
  cmake/third_party/zlib.cmake
Labels: automerge, bug, build

#7623 Merge instruction msg to instruction
  oneflow/core/eager/blob_instruction_type.cpp
  oneflow/core/eager/blob_instruction_type.h
  oneflow/core/eager/critical_section_instruction_type.h
  oneflow/core/eager/lazy_job_instruction_type.h
  oneflow/core/eager/op_call_instruction_type.cpp
  oneflow/core/eager/op_call_instruction_type.h
  oneflow/core/eager/release_tensor_instruction_type.h
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/framework/instructions_builder.h
  oneflow/core/framework/session_util.cpp
  oneflow/core/framework/session_util.h
  oneflow/core/vm/barrier_instruction_type.h
  oneflow/core/vm/control_stream_type.cpp
  oneflow/core/vm/control_stream_type.h
  oneflow/core/vm/critical_section_stream_type.cpp
  oneflow/core/vm/critical_section_stream_type.h
  oneflow/core/vm/ep_d2h_stream_type.cpp
  oneflow/core/vm/ep_d2h_stream_type.h
  oneflow/core/vm/ep_stream_type.cpp
  oneflow/core/vm/ep_stream_type.h
  oneflow/core/vm/event_recorded_ep_stream_type.cpp
  oneflow/core/vm/event_recorded_ep_stream_type.h
  oneflow/core/vm/fuse_instruction_type.h
  oneflow/core/vm/fuse_phy_instr_operand.h
  oneflow/core/vm/instruction.cpp
  oneflow/core/vm/instruction.h
  oneflow/core/vm/instruction_type.h
  oneflow/core/vm/lazy_job_stream_type.cpp
  oneflow/core/vm/lazy_job_stream_type.h
  oneflow/core/vm/stream.cpp
  oneflow/core/vm/stream.h
  oneflow/core/vm/stream_type.h
  oneflow/core/vm/thread_ctx.cpp
  oneflow/core/vm/thread_ctx.h
  oneflow/core/vm/virtual_machine.cpp
  oneflow/core/vm/virtual_machine.h
  oneflow/core/vm/virtual_machine_engine.cpp
  oneflow/core/vm/virtual_machine_engine.h
  oneflow/core/vm/vm_object.h
  oneflow/core/vm/vm_util.cpp
  oneflow/core/vm/vm_util.h
Labels: enhancement, automerge, eager, system

#8472 fix softmax, math unary/binary kernel int overflow
  oneflow/core/device/cuda_util.h
  oneflow/user/kernels/math_binary_elementwise_kernel.cu
  oneflow/user/kernels/math_unary_elementwise_kernel.cu
  oneflow/user/kernels/sparse_cross_entropy_kernel_util.cu
  oneflow/user/kernels/sparse_softmax_cross_entropy_kernel.cu
  oneflow/user/kernels/sparse_softmax_cross_entropy_kernel_util.cu
Labels: automerge, bug, op

#8484 remove useless pipeline buffer between cpu to stage 0
  oneflow/core/job_rewriter/pipeline_buffer_pass.cpp
Labels: enhancement, automerge, bug, graph

#8483 Close straigthen with 1 devices only
  oneflow/core/graph/straighten_nodes.cpp
  oneflow/core/graph/task_graph.cpp
Labels: automerge, bug, graph

#8474 CUDA Graphs delayed capture
  oneflow/core/kernel/cuda_graph_support.h
  oneflow/core/kernel/user_kernel.cpp
  oneflow/core/kernel/user_kernel.h
  oneflow/core/lazy/actor/light_actor.cpp
Labels: enhancement, system

#7617 eager::CallContext
  oneflow/core/eager/call_context.h
  oneflow/core/eager/critical_section_phy_instr_operand.cpp
  oneflow/core/eager/eager_blob_object.h
  oneflow/core/eager/op_call_instruction_type.cpp
  oneflow/core/eager/op_call_phy_instr_operand.cpp
  oneflow/core/eager/op_call_phy_instr_operand.h
  oneflow/core/framework/attr_map.h
  oneflow/core/vm/virtual_machine.cpp
  oneflow/user/kernels/stateful_opkernel.cpp
  oneflow/user/kernels/stateful_opkernel.h
Labels: enhancement, automerge, system

#8429 fix tensor ctor
  oneflow/api/python/functional/tensor_api.cpp
  python/oneflow/test/tensor/test_consistent_tensor.py
  python/oneflow/test/tensor/test_tensor_part_1.py
Labels: automerge, bug, system

#8130 add oneflow_face to ci
  .github/workflows/test.yml
Labels: enhancement, automerge, ci

#8494 optimize eager test speed by relax autotest in some key eager tests
  python/oneflow/test/modules/test_activation.py
  python/oneflow/test/modules/test_loss.py
  python/oneflow/test/modules/test_math_ops.py
  python/oneflow/test/tensor/test_tensor_part_1.py
  python/oneflow/test/tensor/test_tensor_part_2.py
Labels: enhancement, automerge, ci, eager, test, api

#8502 fix autotest bug and optimize eager test speed in ci
  python/oneflow/test/modules/test_abs.py
  python/oneflow/test/modules/test_adaptive_pool.py
  python/oneflow/test/modules/test_add.py
  python/oneflow/test/modules/test_addmm.py
  python/oneflow/test/modules/test_amax.py
  python/oneflow/test/modules/test_amin.py
  python/oneflow/test/modules/test_avgpool.py
  python/oneflow/test/modules/test_ceil.py
  python/oneflow/test/modules/test_clamp.py
  python/oneflow/test/modules/test_concat.py
  python/oneflow/test/modules/test_conv1d.py
  python/oneflow/test/modules/test_conv2d.py
  python/oneflow/test/modules/test_div.py
  python/oneflow/test/modules/test_eq.py
  python/oneflow/test/modules/test_erf.py
  python/oneflow/test/modules/test_erfc.py
  python/oneflow/test/modules/test_expm1.py
  python/oneflow/test/modules/test_flatten.py
  python/oneflow/test/modules/test_flip.py
  python/oneflow/test/modules/test_greater.py
  python/oneflow/test/modules/test_linear.py
  python/oneflow/test/modules/test_linspace.py
  python/oneflow/test/modules/test_norm.py
  python/oneflow/test/modules/test_prod.py
  python/oneflow/test/modules/test_reshape.py
  python/oneflow/test/modules/test_sign.py
  python/oneflow/test/modules/test_split.py
  python/oneflow/test/modules/test_tril.py
  python/oneflow/test/modules/test_where.py
  python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py
Labels: enhancement, automerge, bug, eager, api

#8493 Remove cuda_event.h/cpp
  oneflow/core/device/cuda_event.cpp
  oneflow/core/device/cuda_event.h
  oneflow/core/device/device_context.h
  oneflow/core/eager/blob_instruction_type.h
  oneflow/core/vm/lazy_job_device_context.h
Labels: purge, automerge, system

#8501 Full cache support fusion
  oneflow/core/embedding/cache.h
  oneflow/core/embedding/cache_test.cpp
  oneflow/core/embedding/cached_key_value_store.cu
  oneflow/core/embedding/full_cache.cu
  oneflow/core/embedding/key_value_store.h
  oneflow/core/embedding/key_value_store_options.h
  oneflow/core/embedding/lru_cache.cu
  python/oneflow/one_embedding.py
Labels: enhancement, automerge, system, embedding

#8479 fix undefined reference culibosTlsSetValue
  cmake/third_party.cmake
Labels: automerge, bug, system

#8495 Rename straighten algo interface
  docs/source/graph.rst
  oneflow/core/graph/task_graph.cpp
  oneflow/core/graph/task_graph.h
  oneflow/core/job/compiler.cpp
  oneflow/core/job/job_conf.proto
  python/oneflow/nn/graph/graph_config.py
Labels: feature, automerge, documentation, graph

#8491 Modify add_n_op.cpp and add test_add_n_op.py
  oneflow/user/ops/add_n_op.cpp
  python/oneflow/test/exceptions/test_add_n_op.py
Labels: enhancement, automerge, op, test, documentation

#8498 fix lazy tensor detach and clone
  oneflow/core/framework/tensor.cpp
  oneflow/core/framework/tensor.h
  oneflow/core/framework/tensor_impl.h
  oneflow/core/framework/tensor_name_scope.cpp
  oneflow/core/framework/tensor_name_scope.h
  python/oneflow/test/graph/test_graph_tensor_clone.py
  python/oneflow/test/graph/test_graph_tensor_detach.py
Labels: enhancement, automerge, bug, system

#8512 BiasAddkernel use primitive
  oneflow/user/kernels/bias_add_kernel.cpp
  oneflow/user/kernels/bias_add_kernel.cu
  oneflow/user/kernels/bias_add_kernel.h
Labels: enhancement, automerge, op, primitive

#8504 optimize ci speed in expensive eager test
  python/oneflow/test/expensive/test_convtranspose.py
  python/oneflow/test/expensive/test_einsum.py
  python/oneflow/test/expensive/test_sqrt_square_sum.py
  python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py
Labels: enhancement, automerge, bug, eager, api

#8519 Primitive always use device_type
  oneflow/core/ep/include/primitive/primitive.h
  oneflow/core/kernel/boxing_zeros_kernel.cpp
  oneflow/core/kernel/constant_like_kernel.cpp
  oneflow/core/kernel/copy_hd_kernel.cpp
Labels: purge, automerge, system, primitive

#8520 add tensor dot api and delete useless api in tensor.py
  docs/source/tensor.rst
  oneflow/api/python/framework/tensor_functions.cpp
  python/oneflow/framework/docstr/tensor.py
  python/oneflow/framework/tensor.py
  python/oneflow/test/modules/test_dot.py
  python/oneflow/test/tensor/test_tensor_part_1.py
Labels: enhancement, automerge, bug, eager, documentation, api

#8521 SliceOp support S->S, not support S->P(TODO)
  oneflow/user/kernels/slice_kernel.cpp
  oneflow/user/ops/slice_op.cpp
Labels: automerge, bug, op

#8480 fix maybe error stack and graph duplicated exception
  oneflow/core/common/error.cpp
  oneflow/core/common/error.h
  oneflow/core/common/error_util.cpp
  oneflow/core/common/maybe.h
  oneflow/core/common/throw.h
  oneflow/core/job/job_build_and_infer_ctx.cpp
  oneflow/core/job_rewriter/user_grad.cpp
  python/oneflow/nn/graph/graph.py
  python/oneflow/test/modules/test_exception_reshape.py
Labels: automerge, bug, tooling

#8513 Modify /user/ops/arg_sort_op.cpp , supplement the error information
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/user/kernels/arg_sort_kernel.cpp
  oneflow/user/ops/arg_sort_op.cpp
  python/oneflow/test/exceptions/test_arg_sort_op.py
Labels: enhancement, automerge, op, test, documentation, need-check-error-message

#8524 Modify bias_add_op.cpp,delete unnecessary checks and improve the error message
  oneflow/user/ops/bias_add_op.cpp
  python/oneflow/test/exceptions/test_bias_add_op.py
Labels: enhancement, automerge, op, test, documentation, need-check-error-message

#8499 Remove OFGEMM
  oneflow/core/common/blas.h
  oneflow/core/kernel/kernel_util.cuh
  oneflow/core/kernel/new_kernel_util.h
  oneflow/core/kernel/util/blas_interface.h
  oneflow/core/kernel/util/cuda_blas_interface.cu
  oneflow/core/kernel/util/cuda_blas_interface.h
  oneflow/core/kernel/util/dnn_interface.h
  oneflow/core/kernel/util/host_blas_interface.cpp
  oneflow/core/kernel/util/host_blas_interface.h
  oneflow/core/kernel/util/interface_bridge.h
  oneflow/user/kernels/affine_grid_kernel.cpp
  oneflow/user/kernels/conv_kernels.cpp
  oneflow/user/kernels/deconv_cpu_kernel.cpp
  oneflow/user/kernels/fill_kernel.cu
  oneflow/user/kernels/flip_kernel.cu
  oneflow/user/kernels/fused_self_attention_query_mul_key_and_value_kernel.cu
  oneflow/user/kernels/group_conv_kernel.cpp
  oneflow/user/kernels/group_deconv_kernel.cpp
  oneflow/user/kernels/reduce_kernel.cpp
  oneflow/user/kernels/reduce_like_kernels.cpp
Labels: enhancement, automerge, op

#8496 Refine error msg: core/autograd/gradient_funcs
  oneflow/core/autograd/gradient_funcs/adaptive_pool.cpp
  oneflow/core/autograd/gradient_funcs/add_n.cpp
  oneflow/core/autograd/gradient_funcs/concat.cpp
  oneflow/core/autograd/gradient_funcs/consistent_cast.cpp
  oneflow/core/autograd/gradient_funcs/consistent_to_consistent.cpp
Labels: enhancement, automerge, op, test, documentation, need-check-error-message

#8444 update other resource config eagerly
  oneflow/api/python/framework/framework.cpp
  oneflow/api/python/session/session.cpp
  oneflow/core/framework/multi_client_session_context.cpp
  oneflow/core/framework/multi_client_session_context.h
  oneflow/core/job/job_set.proto
  oneflow/core/job/resource.proto
  oneflow/core/job/resource_desc.cpp
  oneflow/core/job/session_global_objects_scope.cpp
  python/oneflow/framework/attr_util.py
  python/oneflow/framework/config_util.py
  python/oneflow/framework/multi_client_session.py
  python/oneflow/test/graph/test_optimization_conf.py
  python/oneflow/utils/__init__.py
Labels: enhancement, automerge, eager, api

#8533 Modify batch_gather_op.cpp and improve the error message
  oneflow/user/ops/batch_gather_op.cpp
  python/oneflow/test/exceptions/test_batch_gather_op.py
Labels: enhancement, automerge, op, test, documentation, need-check-error-message

#8531 ScalarLogicalKernel use primitive
  oneflow/user/kernels/scalar_logical_kernels.cpp
  oneflow/user/kernels/scalar_logical_kernels.cu
  oneflow/user/kernels/scalar_logical_kernels.h
Labels: enhancement, automerge, op

#8417 Use kineto
  .github/workflows/test.yml
  CMakeLists.txt
  cmake/cuda.cmake
  cmake/third_party.cmake
  dev-requirements.txt
  external/CMakeLists.txt
  external/fmt/CMakeLists.txt
  external/kineto/CMakeLists.txt
  oneflow/core/eager/op_call_instruction_type.cpp
  oneflow/core/profiler/collection.cpp
  oneflow/core/profiler/event.cpp
  oneflow/core/profiler/event.h
  oneflow/core/profiler/event_recorder.cpp
  oneflow/core/profiler/event_recorder.h
  oneflow/core/profiler/kineto_shim.cpp
  oneflow/core/profiler/kineto_shim.h
  oneflow/core/profiler/profile_manager.cpp
  oneflow/core/profiler/profile_manager.h
  oneflow/core/profiler/profiler.cpp
  oneflow/user/kernels/stateful_opkernel.cpp
  python/oneflow/autoprof/__main__.py
  python/oneflow/autoprof/util.py
  python/oneflow/profiler/events.py
  python/oneflow/profiler/profiler.py
  python/oneflow/test/profiler/test_events.py
  python/oneflow/test/profiler/test_profile_lenet.py
  python/oneflow/test_utils/automated_test_util/profiler.py
  python/setup.py
Labels: enhancement, automerge, system, need-clean-ccache
