Repository Oneflow-Inc/oneflow, pull requests merged in 2022-04, with the labels that each got.

#7944 Fix opencv copy files failure
  cmake/third_party.cmake
  cmake/third_party/opencv.cmake
Labels: enhancement, automerge, build, need-simple-ci

#7924 Fix nccl logical kernels
  oneflow/core/framework/op_kernel.h
  oneflow/core/kernel/user_kernel.h
  oneflow/user/kernels/nccl_logical_2d_sbp_kernels.cpp
  oneflow/user/kernels/nccl_logical_kernels.cpp
Labels: automerge, bug, graph

#7933 Fix meshgrid op
  python/oneflow/nn/modules/meshgrid.py
  python/oneflow/test/modules/test_meshgrid.py
  python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py
Labels: enhancement, automerge, bug, eager, api

#7945 Add ops template auto gen
  python/oneflow/test/README.md
  python/oneflow/test/exceptions/test_reshape.py
  python/oneflow/test/gen_ops_process.py
Labels: enhancement, automerge, bug, eager, documentation, api

#7906 add tensor log2 api
  python/oneflow/framework/tensor.py
  python/oneflow/test/tensor/test_tensor_part_1.py
Labels: enhancement, automerge, eager, api

#7792 Export env to python
  oneflow/api/python/env/env.cpp
  oneflow/api/python/env/env.h
  oneflow/api/python/init.cpp
  oneflow/api/python/session/session.h
  oneflow/core/framework/random_generator_impl.cpp
  oneflow/core/intrusive/channel.h
  oneflow/core/intrusive/channel_test.cpp
  oneflow/core/job/env_global_objects_scope.cpp
  oneflow/core/job/env_global_objects_scope.h
  oneflow/core/vm/thread_ctx.cpp
  oneflow/core/vm/thread_ctx.h
  oneflow/core/vm/virtual_machine.cpp
  oneflow/core/vm/virtual_machine.h
  oneflow/core/vm/virtual_machine_engine.cpp
  oneflow/core/vm/virtual_machine_engine.h
  python/oneflow/__init__.py
  python/oneflow/env.py
  python/oneflow/framework/c_api_util.py
  python/oneflow/framework/env_util.py
  python/oneflow/framework/hob.py
  python/oneflow/framework/tensor.py
  python/oneflow/framework/unittest.py
  python/oneflow/serving/inference_session.py
  python/oneflow/test/modules/test_exception_reshape.py
  python/oneflow/test/modules/test_shutting_down.py
Labels: automerge, bug, system

#7939 add unittest and int32 support for branch feat-param_support_np_scalar
  oneflow/api/python/functional/indexing.cpp
  python/oneflow/test/tensor/test_tensor_indexing.py
Labels: enhancement, test, api

#7918 Add module information in error message when type mismatch
  oneflow/api/python/functional/py_function.cpp
  python/oneflow/test/exceptions/test_error_msg.py
Labels: enhancement, automerge, system, api

#7937 add tensor.new_zeros op
  docs/source/tensor.rst
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/tensor.py
  python/oneflow/framework/tensor.py
  python/oneflow/nn/modules/constant.py
  python/oneflow/test/modules/test_consistent_constant.py
  python/oneflow/test/modules/test_constant.py
  python/oneflow/test_utils/automated_test_util/generators.py
Labels: automerge, eager, op, documentation, api

#7952 Print pip list in CI
  .github/workflows/test.yml
Labels: enhancement, automerge, ci

#7892 Fix nn functional conv2d bug
  oneflow/core/functional/functional_api.yaml
  python/oneflow/test/modules/test_conv1d.py
  python/oneflow/test/modules/test_conv2d.py
  python/oneflow/test/modules/test_conv3d.py
Labels: enhancement, automerge, bug, eager, api

#7914 Fix rand/randn bug
  python/oneflow/nn/modules/random_ops.py
  python/oneflow/test/modules/test_rand.py
  python/oneflow/test/modules/test_randn.py
Labels: automerge, bug, eager, documentation, api

#7938 Fix eq none bug
  python/oneflow/framework/tensor.py
  python/oneflow/test/tensor/test_tensor_part_1.py
Labels: enhancement, feature, automerge, bug, eager, documentation, api

#7868 comment CMAKE_LINK_DEPENDS_NO_SHARED
  cmake/caches/ci/serving/cuda-75.cmake
  cmake/caches/ci/serving/openvino.cmake
  cmake/caches/cn/fast/cpu-clang.cmake
  cmake/caches/cn/fast/cpu.cmake
  cmake/caches/cn/fast/cuda-61-clang.cmake
  cmake/caches/cn/fast/cuda-61.cmake
  cmake/caches/cn/fast/cuda-75-clang.cmake
  cmake/caches/cn/fast/cuda-75.cmake
  cmake/caches/cn/fast/cuda-86.cmake
  cmake/caches/cn/fast/mlir-cuda-61.cmake
  cmake/caches/cn/fast/mlir-cuda-75.cmake
Labels: automerge, bug, build

#7855 Support as tensor op
  docs/source/oneflow.rst
  python/oneflow/framework/docstr/__init__.py
  python/oneflow/framework/docstr/as_tensor.py
  python/oneflow/nn/modules/as_tensor.py
  python/oneflow/test/modules/test_as_tensor.py
Labels: enhancement, feature, automerge, bug, eager, api

#7893 fix slice boxing add
  oneflow/core/kernel/slice_boxing_kernel.cpp
Labels: automerge, bug, op

#7959 relax speed test threshold
  ci/test/test_speed_multi_client.sh
Labels: enhancement, automerge, build

#7943 add isnan isinf
  docs/source/oneflow.rst
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/util_ops_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/util_ops_kernels.cpp
  oneflow/user/kernels/util_ops_kernels.cu
  oneflow/user/kernels/util_ops_kernels.h
  oneflow/user/ops/util_ops.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/__init__.py
  python/oneflow/framework/docstr/tensor.py
  python/oneflow/framework/docstr/util_ops.py
  python/oneflow/framework/tensor.py
  python/oneflow/test/modules/test_util_ops.py
Labels: feature, automerge, op, api

#7896 fix bug about randn because get wrong device id
  oneflow/user/kernels/distributions/normal_distribution.cu
  oneflow/user/kernels/distributions/uniform_distribution.cu
  oneflow/user/kernels/distributions/uniform_int_distribution.cu
  oneflow/user/kernels/dropout_kernel.cu
  oneflow/user/kernels/one_embedding_kernels.cu
  oneflow/user/kernels/random_mask_generator.h
  oneflow/user/kernels/random_mask_like_kernel.h
  oneflow/user/kernels/randperm_kernel.cu
  python/oneflow/test/modules/test_dropout.py
  python/oneflow/test/modules/test_rand.py
  python/oneflow/test/modules/test_randint.py
  python/oneflow/test/modules/test_randn.py
  python/oneflow/test/modules/test_randperm.py
Labels: automerge, bug, op

#7903 fix global inplace
  oneflow/core/framework/op_interpreter/eager_consistent_op_interpreter.cpp
  oneflow/core/framework/tensor.h
  oneflow/core/framework/tensor_impl.h
  python/oneflow/test/modules/test_consistent_linear.py
Labels: automerge, bug, eager, global

#7538 Mock device
  oneflow/api/cpp/framework/graph.cpp
  oneflow/api/python/symbol/placement_symbol.cpp
  oneflow/core/boxing/asymmetric_broadcast.cpp
  oneflow/core/boxing/cuda_copy_boxing_interpreter.cpp
  oneflow/core/boxing/naive_1_to_p_boxing.cpp
  oneflow/core/boxing/symmetric_b_to_p_boxing.cpp
  oneflow/core/common/device_type.h
  oneflow/core/common/device_type.proto
  oneflow/core/eager/cuda_blob_instruction_type.cpp
  oneflow/core/eager/cuda_opkernel_instruction_type.cpp
  oneflow/core/eager/release_tensor_instruction_type.cpp
  oneflow/core/ep/cpu/cpu_device_manager_factory.cpp
  oneflow/core/ep/cuda/cuda_device_manager_factory.cpp
  oneflow/core/framework/device.cpp
  oneflow/core/framework/device.h
  oneflow/core/framework/op_expr.cpp
  oneflow/core/framework/op_interpreter/eager_mirrored_op_interpreter.cpp
  oneflow/core/framework/op_interpreter/lazy_op_interpreter.cpp
  oneflow/core/framework/placement_utils.cpp
  oneflow/core/framework/random_generator.cpp
  oneflow/core/framework/random_generator_impl.cpp
  oneflow/core/framework/scope_util.cpp
  oneflow/core/framework/stream_get_call_instruction_name.h
  oneflow/core/framework/user_op_registry.cpp
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/core/functional/impl/comm_functor.cpp
  oneflow/core/functional/impl/consistent_cast.cpp
  oneflow/core/job/parallel_desc.cpp
  oneflow/core/job_rewriter/decode_random_autotick.cpp
  oneflow/core/kernel/decode_random_kernel.cpp
  oneflow/core/kernel/image_decoder_random_crop_resize_kernel.cpp
  oneflow/core/kernel/sync_dynamic_resize_kernel.cpp
  oneflow/core/operator/decode_random_op.cpp
  oneflow/core/operator/op_conf.proto
  oneflow/core/thread/thread.cpp
  oneflow/core/vm/fuse_instruction_type.cpp
  oneflow/core/vm/vm_resource_desc.cpp
  oneflow/ir/include/OneFlow/OneFlowPatterns.td
  oneflow/ir/test/OneFlow/CUDA/fuse_cast_scale.mlir
  oneflow/ir/test/OneFlow/CUDA/gpu_copy_arg.mlir
  oneflow/ir/test/OneFlow/jit-outline-func.mlir
  oneflow/ir/test/OneFlow/traits.mlir
  oneflow/user/ops/comm_net_device_infer_util.h
  oneflow/user/ops/copy_op.cpp
  python/oneflow/framework/tensor_str.py
  python/oneflow/serving/inference_session.py
  python/oneflow/test/expensive/test_util.py
  python/oneflow/test/graph/test_util.py
  python/oneflow/test/modules/test_mock.py
  python/oneflow/test/modules/test_weight_norm.py
  python/oneflow/test_utils/test_util.py
Labels: enhancement, automerge, system

#7969 disable conv3d test
  python/oneflow/test/modules/test_conv3d.py
Labels: automerge, bug, ci

#7941 skip layernorm random_data_warp test
  python/oneflow/test/expensive/test_layernorm.py
Labels: automerge, bug, op

#7967 Lock click version
  .github/workflows/test.yml
  dev-requirements.txt
Labels: automerge, bug, ci

#7585 add global avgpool unittest
  python/oneflow/test/modules/test_consistent_avgpool.py
Labels: enhancement, automerge, op, test, global

#7978 fix layernorm warp shfl_down
  oneflow/core/cuda/layer_norm.cuh
  python/oneflow/test/expensive/test_layernorm.py
Labels: automerge, bug, op

#7934 Support negative dim in scatter op
  oneflow/core/functional/impl/array_functor.cpp
  python/oneflow/test/modules/test_scatter_ops.py
Labels: enhancement, automerge, op

#7702 run barrier callback in BarrierPhyInstrOperand::~BarrierPhyInstrOperand
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/vm/barrier_phy_instr_operand.h
  oneflow/core/vm/instruction.h
  oneflow/core/vm/sequential_instruction_type.cpp
  oneflow/core/vm/stream.cpp
  oneflow/core/vm/virtual_machine.cpp
  oneflow/core/vm/virtual_machine_engine.cpp
  oneflow/core/vm/virtual_machine_engine.h
  python/oneflow/test/modules/test_shutting_down.py
Labels: enhancement, bottleneck, automerge, system

#7972 Fix add conv grad cost
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/ops/conv_op.cpp
Labels: AutoParallel

#7975 Fix one hot scalar tensor bug
  oneflow/user/ops/one_hot_op.cpp
  python/oneflow/test/modules/test_one_hot.py
Labels: enhancement, feature, automerge, bug, eager, api

#7970 support ctor np array from of tensor
  python/oneflow/framework/tensor.py
  python/oneflow/test/tensor/test_tensor_part_1.py
Labels: feature, automerge, python

#7957 add_manual_seed_all_api
  docs/source/cuda.rst
  docs/source/oneflow.rst
  oneflow/api/python/framework/random_generator.cpp
  oneflow/api/python/functional/common.cpp
  oneflow/api/python/functional/common.h
  oneflow/core/framework/random_generator.cpp
  oneflow/core/framework/random_generator.h
  oneflow/core/framework/random_generator_impl.cpp
  python/oneflow/__init__.py
  python/oneflow/cuda/__init__.py
  python/oneflow/framework/docstr/constant.py
  python/oneflow/framework/docstr/math_ops.py
  python/oneflow/framework/generator.py
  python/oneflow/nn/modules/empty.py
  python/oneflow/test/misc/test_manual_seed_api.py
Labels: enhancement, automerge, system

#7902 one_embedding add doc string
  docs/source/index.rst
  docs/source/one_embedding.rst
  python/oneflow/one_embedding.py
Labels: enhancement, automerge, op

#7935 Support numpy scalar parameters
  oneflow/api/python/functional/common.cpp
  oneflow/api/python/functional/indexing.cpp
  oneflow/api/python/functional/python_arg.cpp
  oneflow/api/python/utils/tensor_utils.h
  oneflow/extension/python/numpy.cpp
  oneflow/extension/python/numpy_internal.h
  python/oneflow/test/tensor/test_tensor_indexing.py
Labels: enhancement, feature, automerge, eager

#7953 fix tensor_scatter_nd_update
  oneflow/user/kernels/nd_index_slice_kernels.cpp
  oneflow/user/kernels/nd_index_slice_kernels.cu
  oneflow/user/kernels/nd_index_slice_kernels.h
  oneflow/user/kernels/nd_index_slice_util.h
  python/oneflow/test/tensor/test_tensor_part_1.py
Labels: automerge, bug, op

#7974 fix one_embedding adam
  oneflow/user/kernels/one_embedding_kernels.cu
  oneflow/user/ops/one_embedding_ops.cpp
Labels: automerge, bug, op

#7990 soft speed test
  ci/test/test_speed_multi_client.sh
Labels: enhancement, automerge, ci, need-highest-priority

#7986 [PersistentTable] Fix num blocks
  oneflow/core/embedding/persistent_table.cpp
Labels: automerge, bug, system

#7806 Add auto benchmark for flowvision
  .github/workflows/canary.yml
  .github/workflows/on_merge.yml
  .github/workflows/release.yml
  .github/workflows/simple.yml
  .github/workflows/test.yml
Labels: feature, ci, need-all-tests-even-fail

#7946 [PersistentTable] Async write
  oneflow/core/embedding/persistent_table.cpp
Labels: enhancement, automerge, system, need-all-tests-even-fail

#7825 save log in separate dir by default
  python/oneflow/distributed/launch.py
  python/oneflow/test/modules/test_eager_boxing_exhaustive.py
Labels: enhancement, bottleneck, automerge, python

#7884 Fix upsample sbp infer bug and add global test
  oneflow/user/kernels/upsample_bicubic2d_kernel.cpp
  oneflow/user/kernels/upsample_bicubic2d_kernel.cu
  oneflow/user/kernels/upsample_kernel.h
  oneflow/user/ops/upsample_op.cpp
  python/oneflow/test/modules/test_consistent_upsample.py
  python/oneflow/test/modules/test_upsample.py
Labels: enhancement, automerge, system, need-clean-ccache

#7886 Add view weight norm where zeropad2d global test
  oneflow/user/ops/where_op.cpp
  python/oneflow/test/modules/test_consistent_view.py
  python/oneflow/test/modules/test_consistent_weight_norm.py
  python/oneflow/test/modules/test_consistent_where.py
  python/oneflow/test/modules/test_consistent_zeropad2d.py
Labels: enhancement, automerge, system, need-clean-ccache

#7984 Fix masked select broadcast bug
  python/oneflow/nn/modules/masked_select.py
  python/oneflow/test/modules/test_masked_select.py
Labels: enhancement, automerge, bug, eager, api

#8012 Skip distributed
  .github/workflows/test.yml
Labels: enhancement, automerge, ci, need-highest-priority

#7807 Fix scatter ops eager global bug and add test
  oneflow/user/ops/dim_scatter_ops.cpp
  python/oneflow/test/modules/test_consistent_scatter_nd.py
  python/oneflow/test/modules/test_consistent_scatter_ops.py
Labels: automerge, bug, eager

#7822 Bump NCCL from 2.11.4 to 2.12.10
  cmake/third_party/nccl.cmake
Labels: enhancement, automerge, system

#8020 Skip multi gpu for now
  .github/workflows/test.yml
  ci/test/expensive_generic_test_multi_client.sh
  ci/test/generic_test_multi_client.sh
Labels: enhancement, automerge, ci

#8022 Skip some benchmark in flowvision
  .github/workflows/test.yml
Labels: enhancement, automerge, ci

#7730 Add unbind op
  docs/source/oneflow.rst
  docs/source/tensor.rst
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/array_functor.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/__init__.py
  python/oneflow/framework/docstr/tensor.py
  python/oneflow/framework/docstr/unbind.py
  python/oneflow/framework/tensor.py
  python/oneflow/test/modules/test_consistent_unbind.py
  python/oneflow/test/modules/test_unbind.py
  python/oneflow/test/tensor/test_tensor_part_2.py
  python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py
Labels: automerge, op, documentation, api

#8004 Fix PReLU dispatch num_blocks
  oneflow/user/kernels/prelu_kernel.cu
  python/oneflow/test/modules/test_prelu.py
Labels: automerge, bug, op

#7964 add assert about global_dst_rank type and range
  python/oneflow/framework/check_point_v2.py
Labels: enhancement, automerge, system, python

#8006 [CachedKeyValueStore] Remove SyncCacheToStore from destructor
  oneflow/core/embedding/cached_key_value_store.cu
Labels: enhancement, automerge, system, embedding

#7963 Fix from_numpy use inplace op check
  oneflow/core/eager/eager_blob_object.cpp
Labels: automerge, bug, eager

#7993 fix cycle import of scope and session
  python/oneflow/framework/env_util.py
Labels: automerge, bug, python, interface

#8024 Fix flowvision skip leads to crash
  .github/workflows/test.yml
Labels: enhancement, automerge, ci

#7548 Supply configurable clip_grad_max_norm and clip_grad_norm_type in graph
  oneflow/core/job/job_conf.proto
  oneflow/core/job_rewriter/autograd.cpp
  oneflow/core/job_rewriter/insert_nccl_logical_op_pass.cpp
  oneflow/core/operator/operator.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/multi_reduce_kernel_util.h
  oneflow/user/kernels/multi_reduce_kernels.cpp
  oneflow/user/kernels/multi_reduce_kernels.cu
  oneflow/user/kernels/multi_reduce_kernels.h
  oneflow/user/ops/model_update_ops.cpp
  oneflow/user/ops/multi_reduce_ops.cpp
  python/oneflow/nn/optimizer/optimizer.py
  python/oneflow/test/graph/test_graph_clip_grad_norm.py
Labels: feature, automerge, graph

#8010 change input data range
  python/oneflow/test/modules/test_consistent_math_ops.py
  python/oneflow/test/modules/test_math_ops.py
Labels: enhancement, automerge, python

#7987 Fix sparse_softmax_cross_entropy_ms subgraph
  oneflow/core/job_rewriter/split_sparse_softmax_cross_entropy_op_pass.cpp
  python/oneflow/test/graph/test_graph_sparse_softmax_cross_entropy.py
Labels: automerge, bug, graph

#7988 Fix high memory usage in autotest
  python/oneflow/test/modules/test_conv3d.py
  python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py
Labels: automerge, bug, test

#7887 Add op hardshrink
  docs/source/functional.rst
  docs/source/nn.rst
  oneflow/core/autograd/gradient_funcs/activation.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/activation_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/activation_kernels.cpp
  oneflow/user/kernels/activation_kernels.cu
  oneflow/user/kernels/activation_kernels.h
  oneflow/user/ops/hardshrink_op.cpp
  python/oneflow/nn/__init__.py
  python/oneflow/nn/functional/__init__.py
  python/oneflow/nn/modules/activation.py
  python/oneflow/test/modules/test_activation.py
  python/oneflow/test/modules/test_consistent_activation.py
Labels: enhancement, automerge, op, python

#7955 Enable maybe-need-error-msg check
  .github/workflows/simple.yml
  .github/workflows/test.yml
  CMakeLists.txt
  ci/check/run_clang_tidy.py
  cmake/oneflow.cmake
  cmake/util.cmake
  oneflow/core/common/just.h
  oneflow/core/framework/consistency_check.cpp
  oneflow/core/framework/tensor_rpc_util.cpp
  oneflow/core/profiler/kernel.h
  oneflow/core/vm/control_stream_type.h
  oneflow/core/vm/instruction.h
  oneflow/core/vm/instruction_type.h
  oneflow/core/vm/phy_instr_operand.h
  oneflow/core/vm/stream.h
  oneflow/core/vm/stream_runtime_desc.h
  oneflow/core/vm/stream_type.h
  oneflow/core/vm/virtual_machine_engine.h
  oneflow/core/vm/vm_object.h
  oneflow/core/vm/vm_util.h
Labels: enhancement, automerge, ci

#7942 add more vision model compatibility tests
  python/oneflow/framework/docstr/tensor.py
  python/oneflow/framework/tensor.py
  python/oneflow/nn/functional/__init__.py
  python/oneflow/nn/modules/conv.py
  python/oneflow/nn/modules/normalization.py
  python/oneflow/test/expensive/pytorch_alexnet.py
  python/oneflow/test/expensive/pytorch_convmixer.py
  python/oneflow/test/expensive/pytorch_convnext.py
  python/oneflow/test/expensive/pytorch_crossformer.py
  python/oneflow/test/expensive/pytorch_densenet.py
  python/oneflow/test/expensive/pytorch_efficientnet.py
  python/oneflow/test/expensive/pytorch_ghostnet.py
  python/oneflow/test/expensive/pytorch_googlenet.py
  python/oneflow/test/expensive/pytorch_inception_v3.py
  python/oneflow/test/expensive/pytorch_levit.py
  python/oneflow/test/expensive/pytorch_mnasnet.py
  python/oneflow/test/expensive/pytorch_poolformer.py
  python/oneflow/test/expensive/pytorch_pvt.py
  python/oneflow/test/expensive/pytorch_res2net.py
  python/oneflow/test/expensive/pytorch_resmlp.py
  python/oneflow/test/expensive/pytorch_resnet.py
  python/oneflow/test/expensive/pytorch_rexnet.py
  python/oneflow/test/expensive/pytorch_rexnetv1_lite.py
  python/oneflow/test/expensive/pytorch_senet.py
  python/oneflow/test/expensive/pytorch_shufflenetv2.py
  python/oneflow/test/expensive/pytorch_squeezenet.py
  python/oneflow/test/expensive/pytorch_swin_transformer.py
  python/oneflow/test/expensive/pytorch_uniformer.py
  python/oneflow/test/expensive/pytroch_mlp_mixer.py
  python/oneflow/test/expensive/test_compatibility.py
  python/oneflow/test/expensive/test_compatiblity.py
  python/oneflow/test_utils/oneflow_pytorch_compatibility/__init__.py
  python/oneflow/test_utils/oneflow_pytorch_compatibility/oneflow_pytorch_compatiblity_test.py
Labels: enhancement, automerge, ci, eager, api

#8035 Make passing speed test optional
  .github/workflows/test.yml
Labels: enhancement, automerge, ci

#7965 transfer index select op and fix numpy bug
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/array_functor.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/index_select.py
  python/oneflow/nn/modules/index_select.py
  python/oneflow/test/modules/test_index_select.py
  python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py
Labels: enhancement, automerge, bug, eager, api

#8001 fix conv deconv 0size
  oneflow/user/kernels/bias_add_kernel.h
  oneflow/user/kernels/conv_cudnn_kernels.cpp
  oneflow/user/kernels/deconv_cudnn_kernel.cpp
  oneflow/user/ops/deconv_op.cpp
  python/oneflow/test/modules/test_conv2d.py
  python/oneflow/test/modules/test_deconv2d.py
Labels: automerge, bug, eager, op

#7973 align torch new tensor
  python/oneflow/framework/tensor.py
  python/oneflow/test/tensor/test_new_tensor.py
Labels: enhancement, automerge, api, python

#7992 [OneEmbedding] MockKeyValueStore
  oneflow/core/embedding/key_value_store_test.cpp
  oneflow/core/embedding/mock_key_value_store.cu
  oneflow/core/embedding/mock_key_value_store.h
Labels: feature, automerge, system, embedding

#8011 [OneEmbedding] Add CUDA Graph Support for FusedMLP
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/user/kernels/cublas_bias_add_relu_matmul_grad_kernel.cu
  oneflow/user/kernels/cublas_fused_mlp_kernel.cu
Labels: enhancement, automerge, op, embedding

#7951 Dev roc_auc_score on CPU
  .github/workflows/test.yml
  docs/source/oneflow.rst
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/roc_auc_score_kernel.cpp
  oneflow/user/ops/roc_auc_score_op.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/roc_auc_score.py
  python/oneflow/test/modules/test_roc_auc_score.py
Labels: enhancement, automerge, ci, op, api, embedding

#7979 Fix gather kernel check
  oneflow/user/kernels/dim_gather_kernel_util.cpp
  oneflow/user/kernels/dim_gather_kernel_util.cu
  oneflow/user/kernels/dim_gather_kernel_util.h
  oneflow/user/kernels/dim_gather_kernels.cpp
Labels: enhancement, automerge, bug, eager, api

#7932 add prod dtype
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/math_functor.cpp
  python/oneflow/nn/modules/reduce_ops.py
  python/oneflow/test/modules/test_prod.py
Labels: enhancement, automerge, ci, eager, api

#7872 Use onednn to optimize permute
  oneflow/core/ep/cpu/primitive/permute.cpp
Labels: enhancement, automerge, op, primitive

#7998 OneEmbedding support multi column embedding
  docs/source/one_embedding.rst
  oneflow/core/embedding/embedding_manager.cpp
  oneflow/core/embedding/key_value_store_options.h
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/core/job_rewriter/replace_embedding_ops_pass.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/data_shuffle_kernel.cu
  oneflow/user/kernels/one_embedding_kernels.cu
  oneflow/user/ops/data_shuffle_op.cpp
  oneflow/user/ops/one_embedding_ops.cpp
  python/oneflow/one_embedding.py
  python/oneflow/test/expensive/test_id_shuffle.py
  python/oneflow/test/modules/test_id_shuffle_global.py
Labels: enhancement, automerge, op, need-all-tests-even-fail, embedding

#8040 skip global argsort test
  python/oneflow/test/modules/test_consistent_argsort.py
Labels: automerge

#8007 Fix linalg vector norm and clip grad bug
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/core/functional/impl/unary_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/math_unary_elementwise_func.h
  oneflow/user/ops/math_unary_elementwise_seq.h
  python/oneflow/nn/utils/clip_grad.py
  python/oneflow/test/modules/test_norm.py
Labels: enhancement, automerge, bug, eager, api

#8030 [OneEmbedding] table ids default use uint8
  oneflow/core/device/nccl_util.h
  oneflow/user/kernels/data_shuffle_kernel.cu
  oneflow/user/kernels/one_embedding_kernels.cu
  oneflow/user/ops/data_shuffle_op.cpp
Labels: enhancement, op, embedding

#8031 support to run multiple times if the grad function node does not capt…
  oneflow/api/python/autograd/function_node.cpp
  oneflow/core/autograd/autograd_engine.cpp
  oneflow/core/autograd/autograd_engine.h
  oneflow/core/framework/op_expr_grad_function.h
  oneflow/core/framework/op_interpreter/op_interpreter.cpp
  oneflow/core/framework/tensor_methods.cpp
  python/oneflow/test/modules/test_autograd.py
Labels: enhancement, automerge, system

#8043 Alleviate benchmark failure
  .github/workflows/canary.yml
  .github/workflows/on_merge.yml
  .github/workflows/release.yml
  .github/workflows/simple.yml
  .github/workflows/test.yml
  .gitignore
Labels: enhancement, automerge, ci

#8021 Fix min max dtype promotion
  oneflow/core/functional/impl/math_functor.cpp
  python/oneflow/test/modules/test_consistent_argsort.py
  python/oneflow/test/modules/test_max.py
  python/oneflow/test/modules/test_min.py
Labels: enhancement, feature, automerge, bug, eager, api

#7019 Use docker img built with pytorch 1.10
  .github/workflows/test.yml
  python/oneflow/test/expensive/test_permute.py
Labels: enhancement, automerge, ci

#8037 Fix swin dataloader bug
  .github/workflows/test.yml
  ci/test/test_speed_multi_client.sh
Labels: automerge, bug, test

#7920 Add num batches tracked
  python/oneflow/nn/modules/batchnorm.py
  python/oneflow/test/modules/test_resnet_load_torch_weight_compatibile.py
Labels: enhancement, automerge, bug, eager, api

#8014 one embedding update add weight decay
  oneflow/core/job_rewriter/replace_embedding_ops_pass.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/one_embedding_update_kernels.cu
Labels: enhancement, automerge, op, embedding

#7999 OneEmbedding update kernel add adagrad
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/core/job_rewriter/replace_embedding_ops_pass.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/model_update_kernel_util.h
  oneflow/user/kernels/one_embedding_update_kernels.cu
  oneflow/user/ops/one_embedding_ops.cpp
  python/oneflow/test/modules/test_one_embedding_adagrad.py
  python/oneflow/test/modules/test_one_embedding_adam.py
  python/oneflow/test/modules/test_one_embedding_sgd.py
Labels: enhancement, op, embedding

#8041 Fix partial_fc gradient_funcs bug
  oneflow/core/autograd/autograd_engine.cpp
  oneflow/core/autograd/gradient_funcs/partial_fc_sample.cpp
  python/oneflow/test/modules/test_parital_fc.py
Labels: automerge, bug, eager, op

#7912 [OneEmbedding] Try quantize in Embedding Shuffle
  oneflow/user/kernels/data_shuffle_kernel.cu
  oneflow/user/kernels/gather_kernel.cpp
  oneflow/user/kernels/gather_kernel_util.cu
  oneflow/user/kernels/gather_kernel_util.h
  python/oneflow/test/expensive/test_id_shuffle.py
  python/oneflow/test/modules/test_id_shuffle_global.py
Labels: enhancement, automerge, op, embedding

#8032 [OneEmbedding] add multi-level cache api
  python/oneflow/one_embedding.py
Labels: enhancement, automerge, op, embedding

#8072 Add note on linux
  README.md
Labels: automerge, documentation, system

#8055 [OneEmbedding] rm identity and set id_shuffle regst num 2
  oneflow/core/job_rewriter/replace_embedding_ops_pass.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/fused_dot_feature_interaction_kernel.cu
Labels: enhancement, automerge, op, embedding

#7282 implement addcmul op
  docs/source/oneflow.rst
  docs/source/tensor.rst
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/binary_functor.cpp
  oneflow/core/functional/impl/math_functor.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/math_ops.py
  python/oneflow/framework/docstr/tensor.py
  python/oneflow/framework/tensor.py
  python/oneflow/test/modules/test_addcmul.py
  python/oneflow/test/modules/test_consistent_addcmul.py
Labels: enhancement, automerge, op

#7971 add tensor half
  docs/source/tensor.rst
  python/oneflow/framework/docstr/tensor.py
  python/oneflow/framework/tensor.py
  python/oneflow/test/expensive/test_compatibility.py
  python/oneflow/test/tensor/test_tensor_part_1.py
Labels: enhancement, automerge, bug, eager, api

#7862 Clear independent thread when graph destroy
  .github/workflows/test.yml
  oneflow/core/framework/multi_client_session_context.cpp
  oneflow/core/job/runtime.cpp
  oneflow/core/job/runtime.h
  oneflow/core/thread/thread.cpp
  oneflow/core/thread/thread_manager.cpp
  oneflow/core/thread/thread_manager.h
  python/oneflow/framework/env_util.py
Labels: enhancement, automerge, bug, ci, graph

#8028 改进Op的Python Stack Trace的Debug信息
  oneflow/api/python/env/env.cpp
  oneflow/api/python/env/env.h
  oneflow/api/python/functional/py_function.h
  oneflow/core/job/graph_scope_vars.cpp
  oneflow/core/job/graph_scope_vars.h
  oneflow/core/kernel/learning_rate_schedule_kernel.cpp
  python/oneflow/framework/graph_build_util.py
  python/oneflow/nn/graph/block.py
  python/oneflow/nn/graph/graph.py
  python/oneflow/test/graph/test_graph_debug.py
Labels: feature, automerge, tooling, graph

#8050 cuda_check_numerics skip 0 size tensor
  oneflow/core/kernel/cuda_check_numerics_kernel_observer.cu
Labels: enhancement, automerge, system

#8060 support inplace for LeakyReLU
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/activation_functor.cpp
  python/oneflow/nn/modules/activation.py
  python/oneflow/test/modules/test_activation.py
Labels: enhancement, automerge, eager, api

#7911 Modify the return type of cpu stream device
  oneflow/core/ep/cpu/cpu_device_manager.cpp
  oneflow/core/ep/cpu/cpu_device_manager.h
  oneflow/core/ep/cpu/cpu_stream.cpp
  oneflow/core/ep/cpu/cpu_stream.h
  oneflow/core/ep/cpu/primitive/add.cpp
  oneflow/core/ep/cpu/primitive/broadcast_elementwise_binary.cpp
  oneflow/core/ep/cuda/cuda_device_manager.cpp
  oneflow/core/ep/cuda/cuda_device_manager.h
  oneflow/core/ep/cuda/cuda_stream.cpp
  oneflow/core/ep/cuda/cuda_stream.h
Labels: enhancement, automerge, system, primitive

#8016 Feat set grad enabled
  docs/source/oneflow.rst
  python/oneflow/__init__.py
  python/oneflow/autograd/__init__.py
  python/oneflow/autograd/autograd_mode.py
  python/oneflow/test/modules/test_autograd_mode.py
Labels: automerge, eager, documentation

#8045 [OneEmbedding] PersistentTableReader/Writer
  docs/source/one_embedding.rst
  oneflow/api/python/framework/one_embedding.cpp
  oneflow/api/python/framework/one_embedding_handler.cpp
  oneflow/core/embedding/hash_functions.cuh
  oneflow/core/embedding/persistent_table.cpp
  oneflow/core/embedding/persistent_table.h
  python/oneflow/one_embedding.py
Labels: feature, automerge, system, embedding

#7991 Add functional conv transpose
  docs/source/functional.rst
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  python/oneflow/framework/docstr/__init__.py
  python/oneflow/framework/docstr/conv.py
  python/oneflow/framework/docstr/deconv.py
  python/oneflow/nn/functional/__init__.py
  python/oneflow/nn/modules/conv.py
  python/oneflow/test/expensive/test_convtranspose.py
Labels: feature, automerge, build, api

#8059 Add module half
  python/oneflow/framework/docstr/tensor.py
  python/oneflow/nn/module.py
  python/oneflow/test/modules/test_module_to_half.py
Labels: enhancement, feature, automerge, bug, eager, api

#8034 [OneEmbedding] Fix ReserveQueryLength
  oneflow/core/embedding/cached_key_value_store.cu
  oneflow/core/embedding/embedding_manager.cpp
Labels: automerge, bug, system, embedding

#8065 Add dtype for cumop
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/math_functor.cpp
  python/oneflow/framework/tensor.py
  python/oneflow/test/modules/test_cum_ops.py
Labels: enhancement, automerge, op

#8083 Fix permute wrong test case
  python/oneflow/test/expensive/test_permute.py
Labels: automerge, bug, eager, op

#8027 Add check meta args in to global api
  docs/source/tensor.rst
  oneflow/api/python/utils/tensor_utils.cpp
  oneflow/core/autograd/autograd_engine.cpp
  oneflow/core/autograd/gradient_funcs/consistent_cast.cpp
  oneflow/core/autograd/gradient_funcs/consistent_to_consistent.cpp
  oneflow/core/framework/consistency_check.cpp
  oneflow/core/framework/consistency_check.h
  oneflow/core/framework/nn_graph.cpp
  oneflow/core/framework/op_interpreter/eager_consistent_op_interpreter.cpp
  oneflow/core/framework/op_interpreter/lazy_op_interpreter.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/consistent_cast.cpp
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/core/functional/tensor_index.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/tensor.py
  python/oneflow/framework/tensor.py
  python/oneflow/nn/modules/global_cast.py
Labels: enhancement, automerge, system, api

#7985 Extend Tensor with python c api and optimize python functions
  oneflow/api/python/autograd/autograd_function.cpp
  oneflow/api/python/caster/tensor.h
  oneflow/api/python/exception/exception.h
  oneflow/api/python/framework/doc.cpp
  oneflow/api/python/framework/tensor.cpp
  oneflow/api/python/framework/tensor.h
  oneflow/api/python/functional/common.cpp
  oneflow/api/python/functional/common.h
  oneflow/api/python/functional/function_def.h
  oneflow/api/python/functional/indexing.cpp
  oneflow/api/python/functional/indexing.h
  oneflow/api/python/functional/py_function.cpp
  oneflow/api/python/functional/py_function.h
  oneflow/api/python/functional/python_arg.cpp
  oneflow/api/python/functional/python_arg.h
  oneflow/api/python/functional/python_arg_parser.cpp
  oneflow/api/python/functional/python_arg_parser.h
  oneflow/api/python/functional/python_frame.h
  oneflow/api/python/functional/tensor_api.cpp
  oneflow/api/python/functional/unpack_call.h
  oneflow/api/python/functional/value_types.cpp
  oneflow/api/python/functional/value_types.h
  oneflow/api/python/of_api_registry.h
  oneflow/api/python/utils/tensor_utils.h
  oneflow/core/framework/op_interpreter/dispatch_frame.cpp
  oneflow/core/framework/op_interpreter/dispatch_frame.h
  oneflow/core/framework/tensor.h
  python/oneflow/framework/tensor.py
  python/oneflow/nn/module.py
  python/oneflow/nn/optimizer/optimizer.py
  python/oneflow/test/exceptions/test_error_msg.py
  python/oneflow/test/tensor/test_tensor_part_1.py
  python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py
  tools/functional/generate_dispatch_stateful_ops.py
  tools/functional/generate_functional_api.py
  tools/functional/generate_tensor_api.py
  tools/functional/generator.py
Labels: enhancement, automerge, system, api, interface

#7980 Dev optimize pooling grad
  oneflow/core/autograd/gradient_funcs/avg_pooling.cpp
  oneflow/core/autograd/gradient_funcs/pooling.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_grad_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowBase.td
  oneflow/user/kernels/pool_gpu_kernel.cpp
  oneflow/user/ops/pooling_op.cpp
Labels: enhancement, automerge, op, refactor

#7996 add the flow.amax operator
  docs/source/oneflow.rst
  docs/source/tensor.rst
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/math_functor.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/__init__.py
  python/oneflow/framework/docstr/amax.py
  python/oneflow/framework/docstr/tensor.py
  python/oneflow/framework/tensor.py
  python/oneflow/test/modules/test_amax.py
Labels: enhancement, feature, automerge, op

#7904 fix the seed of tensor init
  python/oneflow/framework/tensor.py
  python/oneflow/test/modules/test_generator.py
Labels: automerge, bug, python

#8056 Add FunctionNode deleter prevent stack overflow
  oneflow/core/autograd/autograd_engine.cpp
  oneflow/core/autograd/autograd_engine.h
Labels: automerge, bug, eager, system

#7960 randn op support global tensor
  oneflow/user/kernels/distributions/normal_kernel.h
  oneflow/user/ops/distributions/normal_op.cpp
  python/oneflow/test/modules/test_consistent_randn.py
Labels: enhancement, automerge, bug, op, test

#8093 Fix import oneflow segmentation fault
  oneflow/api/python/env/env.h
  oneflow/api/python/functional/python_frame.h
  oneflow/core/job/graph_scope_vars.cpp
  oneflow/core/job/graph_scope_vars.h
Labels: automerge, bug, build, need-highest-priority

#8101 Fix format caused in pushing by mistake
  .github/workflows/test.yml
  oneflow/ir/test/OneFlow/test_graph_save_and_load.py
  oneflow/ir/test/lit.cfg.py
Labels: automerge, bug, ci

#7813 Dev non-contiguous view ops
  oneflow/core/framework/op_expr.cpp
  oneflow/core/framework/op_expr.h
  oneflow/core/framework/op_interpreter/op_interpreter.cpp
  oneflow/core/framework/tensor_methods.cpp
  oneflow/core/framework/tensor_methods.h
  oneflow/core/framework/user_op_registry.cpp
  oneflow/core/framework/user_op_registry.h
  oneflow/core/functional/impl/activation_functor.cpp
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/core/functional/tensor_index.cpp
  oneflow/ir/include/OneFlow/OneFlowInterfaces.td
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/copy_kernel.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/activation.py
  python/oneflow/framework/docstr/chunk.py
  python/oneflow/framework/tensor.py
  python/oneflow/test/expensive/test_permute.py
  python/oneflow/test/graph/test_graph_loss.py
  python/oneflow/test/modules/test_as_stride.py
  python/oneflow/test/modules/test_chunk.py
  python/oneflow/test/modules/test_hsplit.py
  python/oneflow/test/modules/test_movedim.py
  python/oneflow/test/modules/test_narrow.py
  python/oneflow/test/modules/test_select.py
  python/oneflow/test/modules/test_slice.py
  python/oneflow/test/modules/test_split.py
  python/oneflow/test/modules/test_swapaxes.py
  python/oneflow/test/modules/test_tensor_split.py
  python/oneflow/test/modules/test_transpose.py
  python/oneflow/test/modules/test_unfold_tensor.py
  python/oneflow/test/modules/test_upsample.py
  python/oneflow/test/modules/test_vsplit.py
  tools/oneflow-tblgen/op_schema_emitter.cpp
  tools/oneflow-tblgen/op_schema_source.inc
Labels: enhancement, automerge, eager, op, api

#8106 Use typed op
  oneflow/ir/oneflow-translate/include/OneFlow/MLIROneFlowTranslation.h
  oneflow/ir/oneflow-translate/lib/OneFlow/Importer.cpp
  oneflow/ir/oneflow-translate/lib/OneFlow/MLIROneFlowTranslation.cpp
Labels: enhancement, automerge, ir

#8096 dev_align_chunk_to_torch
  python/oneflow/test/exceptions/test_chunk.py
  python/oneflow/test/modules/test_chunk.py
Labels: automerge, bug, eager, api

#8061 [OneEmbedding] Optimize FullCache memory usage
  oneflow/core/embedding/full_cache.cu
Labels: enhancement, automerge, system, embedding

#8068 Update LLVM/MLIR version to support iree
  cmake/oneflow.cmake
  oneflow/ir/CMakeLists.txt
  oneflow/ir/include/OneFlow/OneFlowDialect.h
  oneflow/ir/include/OneFlow/OneFlowDialect.td
  oneflow/ir/include/OneFlow/OneFlowEnums.td
  oneflow/ir/include/OneFlow/OneFlowOpTraits.h
  oneflow/ir/include/OneFlow/OneFlowOps.h
  oneflow/ir/include/OneFlow/OneFlowOps.td
  oneflow/ir/include/OneFlow/OneFlowPatterns.td
  oneflow/ir/include/OneFlow/Passes.h
  oneflow/ir/lib/OneFlow/Conversion/OneFlowToTosa.cpp
  oneflow/ir/lib/OneFlow/Conversion/SCFToGPU.cpp
  oneflow/ir/lib/OneFlow/OneFlowOpGetGen.cpp.in
  oneflow/ir/lib/OneFlow/OneFlowOpTraits.cpp
  oneflow/ir/lib/OneFlow/OneFlowOps.cpp
  oneflow/ir/lib/OneFlow/Passes.cpp
  oneflow/ir/oneflow-extension/CMakeLists.txt
  oneflow/ir/oneflow-extension/extension.cpp
  oneflow/ir/oneflow-opt/oneflow-opt.cpp
  oneflow/ir/oneflow-runner/oneflow-runner.cpp
  oneflow/ir/oneflow-translate/CMakeLists.txt
  oneflow/ir/oneflow-translate/include/OneFlow/MLIROneFlowTranslation.h
  oneflow/ir/oneflow-translate/lib/OneFlow/CMakeLists.txt
  oneflow/ir/oneflow-translate/lib/OneFlow/Importer.cpp
  oneflow/ir/oneflow-translate/lib/OneFlow/MLIROneFlowTranslation.cpp
  oneflow/ir/oneflow-translate/oneflow-translate.cpp
  oneflow/ir/test/CMakeLists.txt
  oneflow/ir/test/OneFlow/auto_nhwc/lit.local.cfg
  oneflow/ir/test/OneFlow/auto_nhwc/test_nhwc_batchnorm.py
  oneflow/ir/test/OneFlow/auto_nhwc/test_nhwc_bias_add.py
  oneflow/ir/test/OneFlow/cuda_code_gen/fuse_cast_scale.mlir
  oneflow/ir/test/OneFlow/cuda_code_gen/gpu_copy_arg.mlir
  oneflow/ir/test/OneFlow/cuda_code_gen/gpu_runner.mlir
  oneflow/ir/test/OneFlow/cuda_code_gen/lit.local.cfg
  oneflow/ir/test/OneFlow/jit-outline-func.mlir
  oneflow/ir/test/OneFlow/lower_to_tosa.mlir
  oneflow/ir/test/OneFlow/test_fuse_pad_conv.py
  oneflow/ir/test/OneFlow/test_fuser_cast_scale.py
  oneflow/ir/test/OneFlow/with_cuda/lit.local.cfg
  oneflow/ir/test/OneFlow/with_cuda/test_fuse_bias_add_dropout.py
  oneflow/ir/test/OneFlow/with_cuda/test_fuse_scale_tril.py
  oneflow/ir/test/OneFlow/with_cuda/test_graph_save_and_load.py
  oneflow/ir/test/lit.cfg.py
  oneflow/ir/test/lit.site.cfg.py.in
Labels: enhancement, automerge, ir

#8009 Add nn init orthogonal
  docs/source/nn.init.rst
  python/oneflow/framework/tensor.py
  python/oneflow/nn/init.py
  python/oneflow/test/tensor/test_tensor_part_1.py
Labels: feature, automerge, build, api

#8069 dev_median
  docs/source/oneflow.rst
  oneflow/core/autograd/gradient_funcs/median.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/median_kernel.cpp
  oneflow/user/kernels/median_kernel.cu
  oneflow/user/kernels/median_with_indices_kernel.cpp
  oneflow/user/kernels/median_with_indices_kernel.cu
  oneflow/user/ops/median_op.cpp
  oneflow/user/ops/median_with_indices_op.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/math_ops.py
  python/oneflow/framework/tensor.py
  python/oneflow/test/exceptions/test_median.py
  python/oneflow/test/modules/test_consistent_median.py
  python/oneflow/test/modules/test_median.py
Labels: feature, automerge, eager, op, api

#8052 fix bug: P2B task graph edge bind lbi
  oneflow/core/graph/boxing/naive_b2p_sub_task_graph_builder.cpp
Labels: bug, graph

#8090 fix layernorm check bug
  python/oneflow/nn/modules/normalization.py
  python/oneflow/test/exceptions/test_layernorm.py
Labels: enhancement, automerge, bug, eager, api

#7956 Add normal op
  docs/source/oneflow.rst
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/tensor.py
  python/oneflow/nn/modules/random_ops.py
  python/oneflow/test/modules/test_consistent_normal.py
  python/oneflow/test/modules/test_normal.py
Labels: enhancement, automerge, op

#8053 Add tensor byte
  docs/source/tensor.rst
  python/oneflow/framework/docstr/tensor.py
  python/oneflow/framework/tensor.py
  python/oneflow/test/tensor/test_tensor_part_1.py
Labels: feature, automerge, op, api

#7799 constant folding and fuse conv+bn
  .github/workflows/canary.yml
  .github/workflows/on_merge.yml
  .github/workflows/release.yml
  .github/workflows/simple.yml
  .github/workflows/test.yml
  cmake/caches/ci/serving/openvino.cmake
  oneflow/api/python/framework/variable_tensor_mgr.cpp
  oneflow/core/framework/multi_client_session_context.cpp
  oneflow/core/framework/nn_graph.cpp
  oneflow/core/framework/nn_graph.h
  oneflow/core/framework/variable_tensor_mgr.cpp
  oneflow/core/framework/variable_tensor_mgr.h
  oneflow/ir/include/OneFlow/OneFlowDialect.td
  oneflow/ir/include/OneFlow/OneFlowOps.td
  oneflow/ir/include/OneFlow/OneFlowPatterns.td
  oneflow/ir/include/OneFlow/OneFlowSupport.h
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/ir/include/OneFlow/Passes.h
  oneflow/ir/include/OneFlow/Transform/ConvertInferenceOp.h
  oneflow/ir/lib/OneFlow/CMakeLists.txt
  oneflow/ir/lib/OneFlow/OneFlowDialect.cpp
  oneflow/ir/lib/OneFlow/OneFlowOpFolders.cpp
  oneflow/ir/lib/OneFlow/OneFlowOps.cpp
  oneflow/ir/lib/OneFlow/OneFlowSupport.cpp
  oneflow/ir/lib/OneFlow/Passes.cpp
  oneflow/ir/lib/OneFlow/Transform/ConvertInferenceOp.cpp
  oneflow/ir/oneflow-translate/lib/OneFlow/MLIROneFlowTranslation.cpp
  oneflow/ir/test/OneFlow/folding/test_conv_bn.py
  oneflow/ir/test/OneFlow/folding/test_conv_bn_auto_nhwc.py
  oneflow/ir/test/OneFlow/folding/test_simple_multiply.py
  python/oneflow/nn/graph/graph.py
Labels: feature, automerge, system, need-clean-ccache, ir

#8042 Add flow amin
  docs/source/oneflow.rst
  docs/source/tensor.rst
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/math_functor.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/__init__.py
  python/oneflow/framework/docstr/amin.py
  python/oneflow/framework/docstr/tensor.py
  python/oneflow/framework/tensor.py
  python/oneflow/test/modules/test_amin.py
Labels: feature, automerge, eager, op, api

#7949 add searchsorted op
  docs/source/oneflow.rst
  oneflow/core/common/shape.cpp
  oneflow/core/common/shape.h
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/search_sorted_kernel.cpp
  oneflow/user/kernels/search_sorted_kernel.cu
  oneflow/user/kernels/search_sorted_kernel_util.h
  oneflow/user/ops/search_sorted_op.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/__init__.py
  python/oneflow/framework/docstr/searchsorted.py
  python/oneflow/test/modules/test_consistent_searchsorted.py
  python/oneflow/test/modules/test_searchsorted.py
Labels: enhancement, automerge, op

#8063 Add CUBLAS Matmul BiasAdd Grad Kernel
  oneflow/core/autograd/gradient_funcs/cublas_fused_mlp.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_grad_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/cublas_fused_matmul_bias_add_grad.cu
  oneflow/user/kernels/cublas_fused_mlp_util.cuh
  oneflow/user/ops/cublas_fused_matmul_bias_add_grad_op.cpp
  oneflow/user/ops/cublas_fused_mlp_op.cpp
Labels: enhancement, automerge, op, embedding

#7909 Arange kernel support global tensor
  oneflow/user/kernels/arange_kernel.cpp
  oneflow/user/ops/arange_op.cpp
  python/oneflow/test/modules/test_consistent_arange.py
Labels: enhancement, automerge, op, test, global

#8113 rm useless constantpad ops
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/constantpad_kernel.cpp
  oneflow/user/kernels/constantpad_kernel_util.cpp
  oneflow/user/kernels/constantpad_kernel_util.cu
  oneflow/user/kernels/constantpad_kernel_util.h
  oneflow/user/kernels/pad2d_kernels.cpp
  oneflow/user/kernels/pad2d_kernels_util.cpp
  oneflow/user/kernels/pad2d_kernels_util.cu
  oneflow/user/kernels/pad2d_kernels_util.h
  oneflow/user/ops/padding_ops.cpp
  python/oneflow/test/modules/test_constantpad.py
Labels: enhancement, automerge, op

#8054 refine_error_info_with_diff_device_input_and_fix_typo
  oneflow/api/python/symbol/placement_symbol.cpp
  oneflow/core/framework/consistent_tensor_infer_cache.cpp
  oneflow/core/framework/op_interpreter/eager_mirrored_op_interpreter.cpp
  oneflow/core/framework/op_interpreter/lazy_op_interpreter.cpp
  oneflow/core/framework/sbp_infer_util.cpp
  oneflow/core/job/parallel_desc.cpp
  oneflow/core/job_rewriter/pipeline_buffer_pass.cpp
  python/oneflow/test/exceptions/test_multi_input_with_diff_device_or_placement.py
Labels: enhancement, automerge, system

#7768 Feat support balanced spliter nd sbp eager boxing
  oneflow/core/boxing/eager_boxing_interpreter_mgr.cpp
  oneflow/core/boxing/flatten_hierarchy.cpp
  oneflow/core/boxing/generic_symmetric_nd_sbp_boxing.cpp
  oneflow/core/boxing/nd_sbp_dim_reduce_boxing.cpp
  oneflow/core/boxing/symmetric_acyclic_nd_sbp_boxing.cpp
  oneflow/core/boxing/unflatten_hierarchy.cpp
  oneflow/core/common/flat_shape.cpp
  oneflow/core/common/flat_shape.h
  oneflow/core/framework/consistency_check.cpp
  oneflow/core/framework/consistency_check.h
  oneflow/core/framework/nd_sbp.cpp
  oneflow/core/framework/nd_sbp.h
  oneflow/core/framework/placement_sbp_util.cpp
  oneflow/core/framework/placement_sbp_util.h
  oneflow/core/functional/impl/consistent_cast.cpp
  oneflow/core/operator/operator.cpp
  python/oneflow/test/modules/test_eager_boxing.py
Labels: feature, automerge, eager, system

#8121 Update profiler guard
  oneflow/core/eager/opkernel_instruction_type.cpp
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/profiler/profiler.cpp
  oneflow/core/vm/async_cuda_stream_type.cpp
  oneflow/core/vm/cpu_stream_type.cpp
  oneflow/core/vm/fuse_instruction_type.cpp
  oneflow/core/vm/instruction.cpp
  oneflow/core/vm/virtual_machine.cpp
  oneflow/core/vm/virtual_machine_engine.cpp
Labels: enhancement, automerge, system

#7907 fix nonzero dtype
  python/oneflow/framework/docstr/nonzero.py
  python/oneflow/nn/modules/nonzero.py
  python/oneflow/test/modules/test_nonzero.py
Labels: automerge, bug, eager, api

#8114 [nn.Graph] Fix eager tensor not in job bug
  oneflow/core/framework/nn_graph.cpp
  python/oneflow/test/graph/test_free_tensor_not_in_job.py
Labels: automerge, bug, eager, api, graph

#7977 Align getitem with pytorch when index on different devices
  oneflow/core/framework/device.cpp
  oneflow/core/functional/impl/array_functor.cpp
  python/oneflow/test/tensor/test_tensor_indexing.py
Labels: enhancement, automerge, op
