Repository Oneflow-Inc/oneflow, pull requests merged in 2022-07, with the labels that each got.

#8522 arange api support input scalar type
  python/oneflow/nn/modules/arange.py
  python/oneflow/test/modules/test_arange.py
Labels: enhancement, automerge, bug, eager, api

#8532 Fix stringop-truncation compile error for gcc9
  oneflow/api/python/framework/tensortype.cpp
Labels: automerge, bug, op

#8476 Fused bce logits reduce mean
  oneflow/core/autograd/gradient_funcs/binary_cross_entropy_with_logits_reduce_mean.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/core/functional/impl/nn_grad_functor.cpp
  oneflow/core/job_rewriter/auto_mixed_precision_lists.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/binary_cross_entropy_kernel.cpp
  oneflow/user/kernels/binary_cross_entropy_with_logits_kernel.cpp
  oneflow/user/kernels/binary_cross_entropy_with_logits_kernel.cu
  oneflow/user/kernels/binary_cross_entropy_with_logits_mean_kernel.cu
  oneflow/user/kernels/binary_cross_entropy_with_logits_mean_kernel_util.h
  oneflow/user/kernels/binary_cross_entropy_with_logits_reduce_mean.cpp
  oneflow/user/kernels/fused_cross_feature_interaction.cu
  oneflow/user/kernels/fused_cross_feature_interaction_grad.cu
  oneflow/user/ops/binary_cross_entropy_with_logits_reduce_mean_op.cpp
Labels: enhancement, automerge, op, embedding

#8529 Decouple user_kernel and device_tag
  oneflow/core/framework/infer_util.h
  oneflow/core/framework/op_expr.cpp
  oneflow/core/framework/op_kernel.h
  oneflow/core/framework/user_op_kernel_registry.h
  oneflow/core/kernel/user_kernel.cpp
  oneflow/core/operator/user_op.cpp
  oneflow/user/kernels/arg_where_kernel.cpp
  oneflow/user/kernels/stateful_opkernel.cpp
Labels: enhancement, automerge, system

#8206 add formula of CombinedMarginLoss
  python/oneflow/nn/modules/loss.py
Labels: enhancement, automerge, documentation, api, python

#8544 LogicalNot primitive based kernel
  oneflow/user/kernels/logical_not_kernel.cpp
  oneflow/user/kernels/logical_not_kernel.cu
  oneflow/user/kernels/logical_not_kernel.h
Labels: enhancement, automerge, op

#8537 REGISTER_COPY_DATA_CONTENT_KERNEL
  oneflow/user/kernels/amp_white_identity_kernel.cpp
  oneflow/user/kernels/cast_to_static_shape_kernel.cpp
  oneflow/user/kernels/copy_data_content_kernel.cpp
  oneflow/user/kernels/copy_data_content_kernel.h
  oneflow/user/kernels/expand_dims_kernel.cpp
  oneflow/user/kernels/flatten_kernel.cpp
  oneflow/user/kernels/identity_kernel.cpp
  oneflow/user/kernels/reshape_kernel.cpp
  oneflow/user/kernels/reshape_like_kernel.cpp
  oneflow/user/kernels/squeeze_kernel.cpp
Labels: enhancement, automerge, op

#8482 Add manually mem gc python api
  docs/source/cuda.rst
  oneflow/api/python/env/env.cpp
  oneflow/api/python/env/env.h
  oneflow/core/device/cuda_util.cpp
  oneflow/core/device/cuda_util.h
  python/oneflow/cuda/__init__.py
  python/oneflow/test/misc/test_empty_cache.py
Labels: feature, automerge, documentation, api, python

#8547 fix reduce all functor bug
  oneflow/core/functional/impl/math_functor.cpp
  python/oneflow/test/modules/test_logical_reduce.py
Labels: enhancement, automerge, bug, eager, api, community

#8506 Fix randn
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/core/functional/impl/random_functor.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/random.py
  python/oneflow/nn/modules/random_ops.py
  python/oneflow/test/modules/test_consistent_normal.py
  python/oneflow/test/modules/test_normal.py
  python/oneflow/test/modules/test_rand.py
  python/oneflow/test/modules/test_randn.py
Labels: enhancement, automerge, bug, eager, api

#8536 SliceOp support S->P and fix reduce nd_sbp infer
  oneflow/core/operator/operator.cpp
  oneflow/user/kernels/slice_kernel.cpp
  oneflow/user/ops/slice_op.cpp
  python/oneflow/test/modules/test_consistent_slice.py
Labels: feature, automerge, eager, graph

#8540 Fix real path memory leak
  oneflow/core/hardware/net_socket_device_descriptor.cpp
Labels: automerge, bug, system

#8541 refine error msg for some autograd code
  oneflow/core/autograd/gradient_funcs/cublas_fused_mlp.cpp
  oneflow/core/autograd/gradient_funcs/layer_norm.cpp
  oneflow/core/autograd/gradient_funcs/max_pool.cpp
  oneflow/core/autograd/gradient_funcs/nll.cpp
  oneflow/core/autograd/gradient_funcs/normalization.cpp
  oneflow/core/autograd/gradient_funcs/normalization_add_relu.cpp
  oneflow/core/autograd/gradient_funcs/select_top_n.cpp
  oneflow/core/autograd/gradient_funcs/split_like.cpp
  oneflow/core/autograd/gradient_funcs/stack.cpp
  oneflow/core/autograd/gradient_funcs/variance.cpp
Labels: enhancement, automerge, op, test, documentation, need-check-error-message

#8373 Multi Tensor apply Optimizer
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/core/graph/inplace_lbi_graph.cpp
  oneflow/core/job/job_build_and_infer_ctx.cpp
  oneflow/core/job_rewriter/adam_optm.cpp
  oneflow/core/job_rewriter/fuse_model_update_cast_pass.cpp
  oneflow/core/job_rewriter/fuse_update_ops_pass.cpp
  oneflow/core/job_rewriter/multi_tensor_model_update.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/model_update_kernel_util.cpp
  oneflow/user/kernels/model_update_kernel_util.cu
  oneflow/user/kernels/model_update_kernel_util.h
  oneflow/user/kernels/model_update_kernels.cpp
  oneflow/user/kernels/multi_tensor_model_update_kernel.cpp
  oneflow/user/kernels/multi_tensor_model_update_kernel_util.cu
  oneflow/user/kernels/multi_tensor_model_update_kernel_util.h
  oneflow/user/kernels/mutable_cast_once_kernel.cpp
  oneflow/user/ops/model_update_ops.cpp
  oneflow/user/ops/multi_tensor_model_update_ops.cpp
  oneflow/user/ops/mutable_cast_once_op.cpp
  python/oneflow/test/graph/test_multi_tensor_adam_update_with_cast.py
  python/oneflow/test/graph/test_multi_tensor_sgd_update_with_cast.py
  python/oneflow/test/modules/test_multi_tensor_adam_update.py
  python/oneflow/test/modules/test_multi_tensor_sgd_update.py
Labels: enhancement, automerge, op, embedding

#8546 Fix doc and ops template auto gen
  docs/source/functional.rst
  docs/source/nn.rst
  docs/source/one_embedding.rst
  docs/source/oneflow.rst
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  python/oneflow/nn/functional/__init__.py
  python/oneflow/nn/modules/rnn.py
  python/oneflow/test/README.md
  python/oneflow/test/gen_ops_process.py
  python/oneflow/test/modules/test_contiguous.py
Labels: enhancement, automerge, bug, eager, documentation, api

#8557 fix diag 0size tensr shape infer bug
  oneflow/user/ops/diag_op.cpp
  python/oneflow/test/modules/test_diag.py
Labels: enhancement, automerge, bug, eager, api

#8548 Format tensor on cpu
  python/oneflow/framework/tensor_str.py
Labels: enhancement, automerge, eager

#8562 Remove useless WITH_CUDAs
  oneflow/core/common/blas.h
  oneflow/core/device/cuda_util.cu
  oneflow/core/device/cuda_util.h
  oneflow/core/graph_impl/decode_h2d_compute_task_node.cpp
  oneflow/core/job/job_build_and_infer_ctx.cpp
  oneflow/core/lazy/actor/naive_actor.cpp
  oneflow/user/kernels/acc_kernel.cpp
  oneflow/user/kernels/fused_self_attention_query_mul_key_and_value_kernel.cu
  oneflow/user/kernels/zero_like_kernel.cpp
Labels: purge, automerge, system

#8509 unique identity
  python/oneflow/framework/graph_build_util.py
  python/oneflow/nn/graph/block.py
  python/oneflow/nn/graph/graph.py
Labels: enhancement, automerge, graph

#8560 Add GenericStreamContext
  oneflow/core/lazy/actor/actor.cpp
  oneflow/core/lazy/actor/actor_context.h
  oneflow/core/lazy/actor/light_actor.cpp
  oneflow/core/lazy/stream_context/common/generic_stream_context.cpp
  oneflow/core/lazy/stream_context/cpu/cpu_stream_context.cpp
  oneflow/core/lazy/stream_context/cuda/cuda_stream_context.cpp
  oneflow/core/lazy/stream_context/include/generic_stream_context.h
  oneflow/core/lazy/stream_context/include/stream_context.h
  oneflow/core/thread/thread.cpp
Labels: enhancement, automerge, system, need-clean-ccache

#8556 Modify some file and add test
  oneflow/user/ops/randperm_op.cpp
  oneflow/user/ops/reduce_like_ops.cpp
  oneflow/user/ops/relu_op.cpp
  oneflow/user/ops/reshape_like_op.cpp
  python/oneflow/test/exceptions/test_randperm_op.py
  python/oneflow/test/exceptions/test_reduce_like_ops.py
  python/oneflow/test/exceptions/test_reshape_like_op.py
Labels: enhancement, automerge, op, test, documentation

#8564 one_embedding fused_lookup_init_cast and fused_update_put
  oneflow/core/embedding/cached_key_value_store.cu
  oneflow/core/embedding/embedding_manager.cpp
  oneflow/core/embedding/embedding_manager.h
  oneflow/core/embedding/full_cache.cu
  oneflow/core/job_rewriter/replace_embedding_ops_pass.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/one_embedding_kernels.cu
  oneflow/user/ops/one_embedding_ops.cpp
Labels: enhancement, op

#8545 Move some op into amp gray list
  oneflow/core/job_rewriter/auto_mixed_precision_lists.cpp
Labels: automerge, bug, graph

#8561 Refine inplace expand runtime_error
  oneflow/core/functional/impl/binary_functor.cpp
  oneflow/core/functional/impl/binary_functor.h
  oneflow/core/functional/impl/common.cpp
  oneflow/core/functional/impl/common.h
  python/oneflow/test/exceptions/test_binary_functor_exception.py
Labels: enhancement, automerge, eager

#8569 fix cpu aligned_alloc size
  oneflow/core/ep/cpu/cpu_device.cpp
Labels: automerge, bug, system

#8535 Add flow norm
  docs/source/oneflow.rst
  python/oneflow/__init__.py
  python/oneflow/nn/modules/norm.py
  python/oneflow/test/modules/test_norm.py
Labels: automerge, eager, op, documentation, api

#8574 fix pad_packed_sequence method input requires_grad==True
  python/oneflow/nn/utils/rnn.py
  python/oneflow/test/expensive/test_rnn_utils.py
Labels: automerge, bug, eager, tooling, python

#8585 fix embedding manager tmp buffer
  oneflow/core/embedding/embedding_manager.cpp
  oneflow/core/embedding/embedding_manager.h
  oneflow/core/job_rewriter/replace_embedding_ops_pass.cpp
  oneflow/user/kernels/one_embedding_kernels.cu
Labels: automerge, bug, op

#8551 fix reduce_ops 0size bug
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/user/kernels/reduce_kernel.cpp
  python/oneflow/test/modules/test_logical_reduce.py
Labels: enhancement, automerge, bug, eager, api

#8549 Align Momentum Optimizer
  oneflow/api/python/functional/dispatch_stateful_ops.cpp
  oneflow/api/python/functional/dispatch_stateful_ops.yaml
  oneflow/core/job/job_conf.proto
  oneflow/core/job_rewriter/fuse_update_ops_pass.cpp
  oneflow/core/job_rewriter/indexed_slices_optimizer_rewrite_pass.cpp
  oneflow/core/job_rewriter/momentum_optm.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/model_update_kernel_util.cpp
  oneflow/user/kernels/model_update_kernel_util.cu
  oneflow/user/kernels/model_update_kernel_util.h
  oneflow/user/kernels/model_update_kernels.cpp
  oneflow/user/kernels/one_embedding_update_kernels.cu
  python/oneflow/nn/optimizer/sgd.py
  python/oneflow/test/graph/test_graph_optim_sgd.py
  python/oneflow/test/modules/test_one_embedding_sgd.py
  python/oneflow/test/modules/test_optim_sgd.py
Labels: enhancement, automerge, bug, op

#8576 Fill GetSbp bug and consistent test bug
  oneflow/user/ops/fill_op.cpp
  python/oneflow/test/modules/test_consistent_fill.py
Labels: automerge, bug, eager, global, need-test-distributed

#8462 Dev Fully fused MLP Grad[OneEmbedding]
  oneflow/core/autograd/gradient_funcs/cublas_fused_mlp.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_grad_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/cublas_fused_mlp_grad_kernel.cu
  oneflow/user/kernels/cublas_fused_mlp_util.cuh
  oneflow/user/ops/cublas_fused_mlp_grad_op.cpp
  oneflow/user/ops/cublas_fused_mlp_op.cpp
Labels: enhancement, automerge, op, embedding

#8384 Implement BroadcastElementwiseUnary primitive
  oneflow/core/ep/common/primitive/broadcast_elementwise_binary.h
  oneflow/core/ep/common/primitive/broadcast_elementwise_unary.h
  oneflow/core/ep/common/primitive/unary_functor.h
  oneflow/core/ep/common/primitive/util.h
  oneflow/core/ep/cpu/primitive/broadcast_elementwise_binary.cpp
  oneflow/core/ep/cpu/primitive/broadcast_elementwise_unary.cpp
  oneflow/core/ep/cpu/primitive/unary_functor.h
  oneflow/core/ep/cuda/primitive/broadcast_elementwise_binary.cuh
  oneflow/core/ep/cuda/primitive/broadcast_elementwise_unary.cu
  oneflow/core/ep/cuda/primitive/unary_functor.cuh
  oneflow/core/ep/include/primitive/broadcast_elementwise_unary.h
  oneflow/core/ep/include/primitive/unary_op.h
Labels: enhancement, automerge, system, primitive

#8593 skip cpu autotest for graph global
  python/oneflow/test/modules/test_consistent_0_dim_tensor.py
  python/oneflow/test/modules/test_consistent_abs.py
  python/oneflow/test/modules/test_consistent_adaptive_pool.py
  python/oneflow/test/modules/test_consistent_chunk.py
  python/oneflow/test/modules/test_consistent_diag.py
  python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py
Labels: automerge, bug, graph, global

#8241 Add function_library.h Exception
  oneflow/core/functional/function_library.h
Labels: enhancement, automerge, eager, need-check-error-message

#8573 Refactor shrink
  oneflow/core/vm/bin_allocator.cpp
  oneflow/core/vm/bin_allocator.h
  oneflow/core/vm/bin_allocator_test.cpp
  oneflow/core/vm/caching_allocator.h
  oneflow/core/vm/cpu_allocator.cpp
  oneflow/core/vm/cuda_backend_allocator.cpp
  oneflow/core/vm/cuda_host_allocator.cpp
  oneflow/core/vm/cuda_host_allocator.h
  oneflow/core/vm/ep_d2h_stream_type.cpp
  oneflow/core/vm/ep_device_context.h
  oneflow/core/vm/ep_stream_type.cpp
  oneflow/core/vm/event_recorded_ep_stream_type.cpp
  oneflow/core/vm/pinned_ep_stream_type.cpp
  oneflow/core/vm/shrinkable_cache.h
  oneflow/core/vm/thread_safe_allocator.cpp
  oneflow/core/vm/thread_safe_allocator.h
  oneflow/core/vm/thread_safe_guard.h
  oneflow/core/vm/virtual_machine.cpp
  oneflow/core/vm/virtual_machine_engine.cpp
Labels: enhancement, automerge, system

#8589 Speed up SliceKernel
  oneflow/user/kernels/slice_kernel.cpp
  oneflow/user/kernels/slice_util.cpp
  oneflow/user/kernels/slice_util.cu
  oneflow/user/kernels/slice_util.h
Labels: enhancement, automerge, op

#8600 Update readme and vsn for 0.8.0
  .github/actions/whl/action.yml
  .github/workflows/canary.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  CHANGELOG.md
  CMakeLists.txt
  README.md
  tools/generate_pip_version.py
Labels: automerge, documentation, system

#8592 modify some file and improve error message
  oneflow/user/ops/same_padding_op.cpp
  oneflow/user/ops/scalar_by_tensor_op.cpp
  oneflow/user/ops/scalar_math_op.cpp
  oneflow/user/ops/selu_op.cpp
  oneflow/user/ops/slice_op.cpp
  python/oneflow/test/exceptions/test_slice_op.py
Labels: enhancement, automerge, op, test, documentation, need-check-error-message

#8580 add module releated container docs
  python/oneflow/nn/modules/container.py
Labels: enhancement, automerge, eager, documentation, api

#8603 fix rnn util extra memory usage when requires_grad=False
  python/oneflow/nn/utils/rnn.py
  python/oneflow/test/expensive/test_rnn_utils.py
Labels: enhancement, automerge, tooling, python

#8489 use bracket format slice in tensor str
  python/oneflow/__init__.py
  python/oneflow/framework/tensor_str.py
  python/oneflow/framework/tensor_str_util.py
Labels: enhancement, automerge, system

#8606 Perf TensorInfo constructor
  oneflow/core/autograd/autograd_meta.cpp
Labels: enhancement, automerge, eager

#8558 print operators' python location when print nn_graph
  CMakeLists.txt
  oneflow/api/python/env/env.cpp
  oneflow/api/python/functional/python_frame.h
  oneflow/core/job/graph_scope_vars.cpp
  oneflow/core/job/graph_scope_vars.h
  python/oneflow/framework/graph_build_util.py
  python/oneflow/nn/graph/block.py
  python/oneflow/nn/graph/graph.py
  python/oneflow/nn/graph/graph_config.py
  python/oneflow/nn/graph/util.py
  python/oneflow/test/graph/test_alexnet_graph.py
  python/oneflow/test/graph/test_graph_linear.py
Labels: enhancement, automerge, graph

#8598 Add randint like
  docs/source/oneflow.rst
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/random_functor.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/random.py
  python/oneflow/test/modules/test_global_randint_like.py
  python/oneflow/test/modules/test_randint_like.py
Labels: enhancement, automerge, bug, eager, documentation, api

#8595 Add full_like api
  docs/source/oneflow.rst
  python/oneflow/__init__.py
  python/oneflow/nn/modules/constant.py
  python/oneflow/test/modules/test_consistent_full.py
  python/oneflow/test/modules/test_consistent_full_like.py
  python/oneflow/test/modules/test_constant.py
Labels: enhancement, automerge, eager, documentation, api

#8604 fix cumsum GenBackwardOpConfFn
  oneflow/user/ops/cum_ops.cpp
  python/oneflow/test/modules/test_cum_ops.py
Labels: automerge, bug, op

#8613 revert change
  oneflow/core/functional/impl/nn_functor.cpp
Labels: bottleneck, automerge, bug, eager, need-highest-priority

#8617 fix test graph optimization conf CI bug
  oneflow/core/framework/multi_client_session_context.h
  python/oneflow/test/graph/test_optimization_conf.py
Labels: automerge, bug, graph, need-highest-priority

#8552 Release pod tensor
  oneflow/core/eager/release_tensor_instruction_type.h
  oneflow/core/framework/instructions_builder.cpp
Labels: enhancement, automerge, system

#8611 Add param group for optimizer
  python/oneflow/nn/optimizer/optimizer.py
  python/oneflow/test/exceptions/test_optim_add_param_group.py
  python/oneflow/test/modules/test_optim_add_param_group.py
Labels: enhancement, automerge, bug, eager, documentation, api

#8625 fix broadcast_elementwise_binary cpu
  oneflow/core/ep/cpu/primitive/broadcast_elementwise_binary.cpp
Labels: automerge, bug, op

#8627 align exception msg to torch
  oneflow/core/common/maybe.h
  oneflow/core/functional/impl/array_functor.cpp
  python/oneflow/test/exceptions/test_view.py
Labels: enhancement, automerge, eager

#8635 skip unstable global test in ci, reduce failture rate
  python/oneflow/test/modules/test_global_argmin.py
  python/oneflow/test/modules/test_global_tensor_ops.py
Labels: enhancement, automerge, bug, ci, api

#8586 fuse embedding interaction
  oneflow/core/job/job_build_and_infer_ctx.cpp
  oneflow/core/job_rewriter/fuse_embedding_interaction_pass.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/data_shuffle_kernel.cu
  oneflow/user/kernels/fused_dot_feature_interaction_kernel.cu
  oneflow/user/ops/fused_dot_feature_interaction_op.cpp
Labels: enhancement, automerge, op

#8605 fix flip gen backward opconf
  oneflow/user/ops/flip_op.cpp
Labels: automerge, bug, op

#8597 Add ONEFLOW_ONE_EMBEDDING_PERSISTENT_TABLE_SNAPSHOT_LOAD_MMAP_LOCKED
  oneflow/core/embedding/embedding_manager.cpp
  oneflow/core/embedding/persistent_table.cpp
  oneflow/core/embedding/posix_file.h
Labels: enhancement, automerge, system, embedding

#8565 Fully Memory Log V2 with more details
  oneflow/core/framework/op_interpreter/lazy_op_interpreter.cpp
  oneflow/core/job/plan_util.cpp
  oneflow/core/job_rewriter/checkpointing_pass.cpp
  oneflow/user/ops/repeat_op.cpp
  python/oneflow/test/graph/test_graph_activation_checkpoint.py
Labels: feature, automerge, graph

#6937 Add fully support for broadcast matmul
  oneflow/core/autograd/gradient_funcs/matmul.cpp
  oneflow/core/autograd/gradient_funcs/matrix_vector_product.cpp
  oneflow/core/autograd/gradient_funcs/vector_matrix_product.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/core/functional/impl/nn_grad_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/matmul_kernels.cpp
  oneflow/user/kernels/matrix_vector_product_kernel.cpp
  oneflow/user/kernels/vector_matrix_product_kernel.cpp
  oneflow/user/ops/matmul_op.cpp
  oneflow/user/ops/matrix_vector_product_op.cpp
  oneflow/user/ops/vector_matrix_product_op.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/tensor.py
  python/oneflow/test/exceptions/test_nn_functor.py
  python/oneflow/test/modules/test_consistent_broadcast_matmul.py
  python/oneflow/test/modules/test_consistent_vector_matrix_product.py
  python/oneflow/test/modules/test_matmul.py
Labels: enhancement, automerge, op

#8608 Revert "skip cpu autotest for graph global"
  python/oneflow/test/modules/test_global_0_dim_tensor.py
  python/oneflow/test/modules/test_global_abs.py
  python/oneflow/test/modules/test_global_adaptive_pool.py
  python/oneflow/test/modules/test_global_chunk.py
  python/oneflow/test/modules/test_global_diag.py
Labels: automerge, bug, ci

#8588 OneEmbedding add tmp_buffer allocator
  oneflow/core/embedding/embedding_manager.cpp
  oneflow/core/embedding/embedding_manager.h
  oneflow/user/kernels/data_shuffle_kernel.cu
  oneflow/user/kernels/one_embedding_kernels.cu
Labels: enhancement, automerge, op

#8579 refine error msg for some user ops
  oneflow/user/ops/sigmoid_cross_entropy_op.cpp
  oneflow/user/ops/silu_op.cpp
  oneflow/user/ops/smooth_l1_loss_op.cpp
  oneflow/user/ops/softmax_cross_entropy_op.cpp
  oneflow/user/ops/softmax_op.cpp
  oneflow/user/ops/softplus_op.cpp
  oneflow/user/ops/softshrink_op.cpp
  oneflow/user/ops/softsign_op.cpp
  oneflow/user/ops/sort_op.cpp
  oneflow/user/ops/sparse_cross_entropy_op.cpp
  oneflow/user/ops/sparse_softmax_cross_entropy_op.cpp
  oneflow/user/ops/split_like_op.cpp
  oneflow/user/ops/square_sum_op.cpp
  python/oneflow/test/exceptions/test_smooth_l1_loss_op.py
  python/oneflow/test/exceptions/test_softmax_cross_entropy_op.py
  python/oneflow/test/exceptions/test_sparse_cross_entropy_op.py
  python/oneflow/test/exceptions/test_sparse_softmax_cross_entropy_op.py
  python/oneflow/test/exceptions/test_split_like_op.py
Labels: enhancement, automerge, op, test, documentation, need-check-error-message

#8655 Add tril fill value
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
Labels: enhancement, automerge, op

#8657 fix_non_pod_data_allocate_bug
  oneflow/core/eager/eager_blob_object.cpp
  oneflow/core/eager/eager_blob_object.h
  oneflow/core/eager/op_call_instruction_type.cpp
  oneflow/core/eager/op_call_phy_instr_operand.cpp
  oneflow/core/eager/op_call_phy_instr_operand.h
Labels: automerge, bug, system, need-highest-priority

#8661 fix_decorate_mem_leak_bug_in_eager_boxing
  oneflow/core/boxing/symmetric_acyclic_nd_sbp_boxing.cpp
Labels: automerge, bug, system

#8643 add higher order derivative for leaky_relu and negative op
  oneflow/core/autograd/gradient_funcs/higher_derivative_grad.cpp
  python/oneflow/test/modules/test_global_higher_derivative_leaky_relu.py
  python/oneflow/test/modules/test_global_higher_derivative_neg.py
  python/oneflow/test/modules/test_higher_derivative_leaky_relu.py
  python/oneflow/test/modules/test_higher_derivative_neg.py
Labels: enhancement, automerge, op, test

#8669 update oneflow intro to show the difference
  README.md
Labels: enhancement, automerge, documentation, build

#8671 Stacked error
  oneflow/api/python/caster/maybe.h
  oneflow/api/python/framework/tensor_functions.cpp
  oneflow/core/common/error.cpp
  oneflow/core/common/error.h
  oneflow/core/common/error.proto
  oneflow/core/common/error_util.cpp
  oneflow/core/common/error_util.h
  oneflow/core/common/just.h
  oneflow/core/common/maybe.h
  oneflow/core/common/maybe_test.cpp
  oneflow/core/common/registry_error.cpp
  oneflow/core/common/symbol.h
  oneflow/core/common/throw.h
  oneflow/core/device/cuda_util.h
  oneflow/core/framework/attr_map.cpp
  oneflow/core/framework/op_interpreter/eager_local_op_interpreter.cpp
  oneflow/core/framework/user_op_registry_manager.cpp
  oneflow/core/job_rewriter/autograd.cpp
  oneflow/extension/python/numpy.cpp
Labels: enhancement, automerge, system, need-all-tests-even-fail

#8626 Refactor tensor initializer
  oneflow/core/job/initializer_conf.proto
  python/oneflow/__init__.py
  python/oneflow/framework/tensor.py
  python/oneflow/nn/init.py
  python/oneflow/ops/initializer_register.py
  python/oneflow/ops/initializer_util.py
  python/oneflow/ops/util/__init__.py
  python/oneflow/ops/util/initializer_util.py
  python/oneflow/test/tensor/test_tensor_part_1.py
Labels: enhancement, automerge, bug, eager

#8650 Fix nn doc
  python/oneflow/framework/docstr/math_ops.py
  python/oneflow/nn/modules/dataset.py
Labels: enhancement, automerge, bug, eager, documentation

#8651 Fix reduce max min bool dtype bug
  oneflow/core/ndarray/ndarray_reduce_impl.cu
  oneflow/user/kernels/argmax_kernel.cpp
  oneflow/user/kernels/argmax_kernel.cu
  oneflow/user/kernels/reduce_kernel.cpp
  python/oneflow/test/modules/test_logical_reduce.py
  python/oneflow/test/tensor/test_tensor_part_1.py
Labels: enhancement, automerge, bug, eager, api

#8631 Remove redundant exception wrapper
  python/oneflow/_utils.py
  python/oneflow/utils/data/__init__.py
  python/oneflow/utils/data/_utils/pin_memory.py
  python/oneflow/utils/data/_utils/worker.py
  python/oneflow/utils/data/dataloader.py
Labels: enhancement, automerge, eager

#7727 Refactor MemoryCase to eliminate determine statements of device_type
  .github/workflows/test.yml
  oneflow/core/ep/cpu/cpu_device.cpp
  oneflow/core/ep/cuda/cuda_device.cpp
  oneflow/core/framework/device.cpp
  oneflow/core/graph/copy_task_node.cpp
  oneflow/core/graph/task_node.cpp
  oneflow/core/job/inter_job_mem_sharing_util.cpp
  oneflow/core/job/intra_job_mem_sharing_util.cpp
  oneflow/core/job/plan_util.cpp
  oneflow/core/kernel/kernel_util.cpp
  oneflow/core/kernel/sync_dynamic_resize_kernel.cpp
  oneflow/core/memory/chunk_manager.cpp
  oneflow/core/memory/memory_allocator.cpp
  oneflow/core/memory/memory_case.proto
  oneflow/core/memory/memory_case_util.cpp
  oneflow/core/memory/memory_case_util.h
  oneflow/core/register/ofblob.h
  oneflow/core/register/register_desc.cpp
  oneflow/core/register/register_desc.h
  oneflow/core/register/register_manager.cpp
  oneflow/core/register/runtime_register_desc.cpp
  python/oneflow/test/modules/test_global_einsum_tensor_contraction.py
Labels: enhancement, automerge, graph, need-test-distributed

#8654 fix some data races in c++ api and SteadyVector
  oneflow/api/cpp/tests/api_test.cpp
  oneflow/core/common/shape_view.cpp
  oneflow/core/common/steady_vector.h
  oneflow/core/vm/virtual_machine.cpp
Labels: automerge, bug, system

#8648 Fix sin/cos higher order derivative
  oneflow/core/autograd/autograd_engine.cpp
  oneflow/core/autograd/gradient_funcs/higher_derivative_grad.cpp
  oneflow/core/autograd/gradient_funcs/math_unary_op.cpp
  python/oneflow/test/modules/test_global_math_op_higher_derivative.py
  python/oneflow/test/modules/test_math_op_higher_derivative.py
Labels: automerge, bug, eager

#8568 refine_eager_boxing_to_adapt_ep
  oneflow/api/python/utils/tensor_utils.cpp
  oneflow/core/autograd/gradient_funcs/global_cast.cpp
  oneflow/core/boxing/asymmetric_broadcast.cpp
  oneflow/core/boxing/cuda_copy_boxing_interpreter.cpp
  oneflow/core/boxing/eager_boxing_interpreter_mgr.cpp
  oneflow/core/boxing/flatten_hierarchy.cpp
  oneflow/core/boxing/generic_symmetric_nd_sbp_boxing.cpp
  oneflow/core/boxing/identity_boxing_interpreter.cpp
  oneflow/core/boxing/naive_1_to_p_boxing.cpp
  oneflow/core/boxing/naive_b_to_1_boxing.cpp
  oneflow/core/boxing/naive_b_to_s_boxing.cpp
  oneflow/core/boxing/naive_p_to_b_boxing.cpp
  oneflow/core/boxing/naive_p_to_s_boxing.cpp
  oneflow/core/boxing/naive_s_to_b_boxing.cpp
  oneflow/core/boxing/naive_s_to_p_boxing.cpp
  oneflow/core/boxing/naive_s_to_s_boxing.cpp
  oneflow/core/boxing/nccl_boxing_function.cpp
  oneflow/core/boxing/nd_sbp_dim_reduce_boxing.cpp
  oneflow/core/boxing/one_to_one_boxing.cpp
  oneflow/core/boxing/symmetric_acyclic_nd_sbp_boxing.cpp
  oneflow/core/boxing/symmetric_b_to_p_boxing.cpp
  oneflow/core/boxing/symmetric_b_to_s_boxing.cpp
  oneflow/core/boxing/unflatten_hierarchy.cpp
  oneflow/core/framework/op_interpreter/eager_local_op_interpreter.cpp
  oneflow/core/framework/tensor.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/core/functional/impl/global_cast.cpp
  oneflow/user/kernels/eager_symmetric_s_to_p_kernel.cpp
Labels: enhancement, automerge, system

#8645 Fix repeat bug
  oneflow/core/functional/impl/array_functor.cpp
  python/oneflow/test/modules/test_repeat.py
Labels: automerge, bug, eager, op

#8672 Refine naive interpret
  oneflow/core/common/container_util.h
  oneflow/core/eager/call_context.h
  oneflow/core/eager/critical_section_phy_instr_operand.h
  oneflow/core/eager/eager_blob_object.cpp
  oneflow/core/eager/eager_blob_object.h
  oneflow/core/eager/lazy_job_phy_instr_operand.h
  oneflow/core/eager/local_dep_object.h
  oneflow/core/eager/op_call_instruction_type.cpp
  oneflow/core/eager/op_call_phy_instr_operand.cpp
  oneflow/core/eager/op_call_phy_instr_operand.h
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/framework/instructions_builder.h
  oneflow/core/framework/nn_graph.cpp
  oneflow/core/framework/op_interpreter/eager_global_op_interpreter.cpp
  oneflow/core/framework/op_interpreter/eager_local_op_interpreter.cpp
  oneflow/core/framework/tensor_impl.cpp
  oneflow/core/framework/tensor_methods.cpp
  oneflow/core/operator/operator.cpp
  oneflow/core/vm/consume_local_dep_object_phy_instr_operand.cpp
  oneflow/core/vm/consume_local_dep_object_phy_instr_operand.h
  oneflow/core/vm/phy_instr_operand.h
  oneflow/core/vm/touch_tensors_instruction_type.cpp
  oneflow/core/vm/touch_tensors_instruction_type.h
  oneflow/user/kernels/stateful_opkernel.cpp
  oneflow/user/kernels/stateful_opkernel.h
Labels: enhancement, automerge, system

#8689 Fix sbp print bug
  oneflow/core/framework/sbp_infer_util.cpp
  oneflow/core/operator/operator.cpp
  python/oneflow/test/modules/test_global_deconv2d.py
Labels: feature, automerge, bug, graph

#8693 fix gelu nn.Module bug and support tanh mode.
  docs/source/tensor.rst
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/math_functor.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/activation.py
  python/oneflow/framework/docstr/tensor.py
  python/oneflow/nn/functional/__init__.py
  python/oneflow/nn/modules/activation.py
  python/oneflow/test/modules/test_gelu_approximate.py
Labels: enhancement, automerge, bug, eager, api

#8677 Fix bug in CrossFeatureInteraction LazyBackward
  oneflow/user/ops/fused_cross_feature_interaction_op.cpp
Labels: automerge, bug, op, embedding

#8673 fix floating-point scalar tensor in arange
  python/oneflow/nn/modules/arange.py
  python/oneflow/test/modules/test_arange.py
Labels: automerge, bug, op

#8667 Add nn functional fold
  docs/source/nn.functional.rst
  oneflow/core/autograd/gradient_funcs/fold.cpp
  oneflow/core/autograd/gradient_funcs/unfold.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  python/oneflow/framework/docstr/__init__.py
  python/oneflow/framework/docstr/convolution.py
  python/oneflow/nn/functional/__init__.py
  python/oneflow/nn/modules/fold.py
  python/oneflow/test/modules/test_fold.py
  python/oneflow/test/modules/test_global_fold.py
  python/oneflow/test/modules/test_global_unfold.py
  python/oneflow/test/modules/test_unfold.py
Labels: enhancement, automerge, eager, documentation, api

#8566 modify some file and improve the error message
  oneflow/user/ops/reshape_op.cpp
  oneflow/user/ops/reshape_user_op_util.cpp
  oneflow/user/ops/roi_align_op.cpp
  oneflow/user/ops/roll_op.cpp
  python/oneflow/test/exceptions/test_roi_align_op.py
Labels: enhancement, automerge, op, test, documentation, need-check-error-message

#8683 [OneEmbedding] add id_shuffle_copy_out
  oneflow/core/job_rewriter/replace_embedding_ops_pass.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/one_embedding_kernels.cu
  oneflow/user/ops/one_embedding_ops.cpp
Labels: enhancement, automerge, op

#8698 fix add_param_group step key not match error
  python/oneflow/nn/optimizer/optimizer.py
  python/oneflow/test/modules/test_optim_add_param_group.py
Labels: enhancement, automerge, bug, eager, api

#8703 add env ONEFLOW_EP_CUDA_DEVICE_FLAGS and ONEFLOW_EP_CUDA_STREAM_FLAGS
  oneflow/core/ep/cuda/cuda_device.cpp
  oneflow/core/ep/cuda/cuda_stream.cpp
Labels: enhancement, automerge, system

#8710 fix for docsv0.8
  docs/source/nn.rst
Labels: bug, documentation, build

#8712 Refactor auto parallel sbp node
  oneflow/core/auto_parallel/sbp_collector.cpp
  oneflow/core/auto_parallel/sbp_constructor.cpp
  oneflow/core/auto_parallel/sbp_edge.h
  oneflow/core/auto_parallel/sbp_graph.h
  oneflow/core/auto_parallel/sbp_node.h
Labels: AutoParallel

#8707 fix repeat op 0-size releated bug (both in FW and AD)
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/core/functional/impl/common.cpp
  oneflow/user/kernels/copy_data_content_kernel.cpp
  oneflow/user/ops/reshape_op.cpp
  python/oneflow/test/modules/test_repeat.py
Labels: enhancement, automerge, bug, eager, api

#8633 Support Dropout Scale in FusedMLPGrad[OneEmbedding]
  oneflow/core/autograd/gradient_funcs/cublas_fused_mlp.cpp
  oneflow/core/autograd/gradient_funcs/fused_matmul_bias_add_relu_dropout.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_grad_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/cublas_fused_mlp_grad_kernel.cu
  oneflow/user/ops/cublas_fused_mlp_op.cpp
  oneflow/user/ops/fused_matmul_bias_add_relu_dropout_op.cpp
Labels: enhancement, automerge, op, embedding

#8697 Fix bug of Tensor.type
  oneflow/api/python/framework/tensor.cpp
  oneflow/api/python/framework/tensor.h
  python/oneflow/framework/docstr/tensor.py
  python/oneflow/test/modules/test_tensor_ops.py
Labels: enhancement, automerge, api, python

#8706 ONEFLOW_GRAPH_PLACE_TRAINING_STATE_ON_ALL_RANKS
  oneflow/core/job/parallel_desc.cpp
  oneflow/core/job/parallel_desc.h
  oneflow/core/job_rewriter/auto_train_step.cpp
Labels: enhancement, automerge, system

#8722 Refactor auto parallel sbp graph
  oneflow/core/auto_parallel/algorithm_util.h
  oneflow/core/auto_parallel/boxing_collector.cpp
  oneflow/core/auto_parallel/sbp_collector.cpp
  oneflow/core/auto_parallel/sbp_constructor.cpp
  oneflow/core/auto_parallel/sbp_constructor.h
  oneflow/core/auto_parallel/sbp_edge.h
  oneflow/core/auto_parallel/sbp_graph.h
  oneflow/core/auto_parallel/sbp_node.h
Labels: AutoParallel

#8714 add unsqueeze_multiple_op
  oneflow/core/common/wrap_dim_utils.h
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/array_functor.cpp
Labels: enhancement, automerge, op, documentation, build

#8720 modify broadcast_like_op.cpp and add test
  oneflow/user/ops/broadcast_like_op.cpp
  python/oneflow/test/modules/test_broadcast_like.py
Labels: enhancement, automerge, op, documentation, build

#8500 JIT LR
  oneflow/api/python/ir.cpp
  oneflow/ir/oneflow-extension/CMakeLists.txt
  oneflow/ir/oneflow-extension/include/OneFlow/OneFlowLRJITRegistry.h
  oneflow/ir/oneflow-extension/include/OneFlow/OneFlowRoundTrip.h
  oneflow/ir/oneflow-extension/include/PyAst/Ast.h
  oneflow/ir/oneflow-extension/include/PyAst/AstMlirGen.h
  oneflow/ir/oneflow-extension/lr_jit.cpp
  oneflow/ir/oneflow-extension/mlir_gen.cpp
  oneflow/ir/test/OneFlow/lower_to_tosa.mlir
  python/oneflow/ir/ast_gen_transformer.py
  python/oneflow/ir/bisect_transformer.py
  python/oneflow/ir/lr_jit.py
  python/oneflow/ir/math_params_transformer.py
  python/oneflow/ir/self_params_transformer.py
  python/oneflow/nn/optimizer/multistep_lr.py
Labels: feature, automerge, ir

#8599 Add logspace
  docs/source/oneflow.rst
  python/oneflow/__init__.py
  python/oneflow/nn/modules/logspace.py
  python/oneflow/test/modules/test_global_linspace.py
  python/oneflow/test/modules/test_global_logspace.py
  python/oneflow/test/modules/test_logspace.py
Labels: enhancement, automerge, eager, documentation, api

#8615 Add hann_window
  docs/source/oneflow.rst
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/math_functor.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/__init__.py
  python/oneflow/framework/docstr/hann_window.py
  python/oneflow/test/exceptions/test_hann_window.py
  python/oneflow/test/modules/test_global_hann_window.py
  python/oneflow/test/modules/test_hann_window.py
Labels: automerge, eager, documentation, api

#8730 add ONEFLOW_VM_PENDING_HANDLE_WINDOW_SIZE
  oneflow/core/common/env_var/vm.h
  oneflow/core/vm/virtual_machine_engine.cpp
Labels: enhancement, automerge, system, refactor

#8713 Fix as strided bool type and view bug
  oneflow/user/kernels/as_strided_kernel.cu
  python/oneflow/test/modules/test_as_stride.py
Labels: automerge, bug, eager, documentation, api

#8708 Add functional binary cross entropy
  docs/source/nn.functional.rst
  oneflow/core/functional/functional_api.yaml
  python/oneflow/framework/docstr/loss.py
  python/oneflow/nn/functional/__init__.py
  python/oneflow/test/modules/test_loss.py
Labels: enhancement, automerge, eager, documentation, api

#8666 support map_location in flow.load
  python/oneflow/framework/check_point_v2.py
  python/oneflow/test/modules/test_module.py
Labels: enhancement, automerge, system

#8581 Add addcdiv
  docs/source/oneflow.rst
  docs/source/tensor.rst
  oneflow/api/python/framework/tensor_functions.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/math_functor.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/__init__.py
  python/oneflow/framework/docstr/addcdiv.py
  python/oneflow/framework/docstr/tensor.py
  python/oneflow/test/modules/test_addcdiv.py
  python/oneflow/test/modules/test_global_addcdiv.py
  python/oneflow/test/modules/test_global_full.py
  python/oneflow/test/modules/test_global_full_like.py
Labels: enhancement, automerge, eager, documentation, api

#8403 Inner most dim case for cumsum cumprod op
  oneflow/user/kernels/cum_forward_kernel.cpp
  oneflow/user/kernels/cum_forward_kernel.cu
Labels: enhancement, automerge, op

#8624 Dev refactor fuse instruction policy
  oneflow/core/vm/fuse_instruction_policy.h
  oneflow/core/vm/fuse_instruction_type.h
  oneflow/core/vm/instruction_policy.h
  oneflow/core/vm/instruction_policy_util.h
  oneflow/core/vm/virtual_machine_engine.cpp
Labels: enhancement, automerge, system, refactor

#8723 fix bug of batchnorm num_batches_tracked global error when loading state_dict
  python/oneflow/nn/modules/batchnorm.py
Labels: enhancement, automerge, api, python

#8563 add launch master port limit
  python/oneflow/distributed/launch.py
Labels: enhancement, api, python

#8691 Fix docs import distance
  docs/source/cuda.rst
  docs/source/nn.functional.rst
  docs/source/nn.rst
  docs/source/oneflow.rst
  docs/source/tensor.rst
  python/oneflow/framework/docstr/__init__.py
  python/oneflow/framework/docstr/activation.py
  python/oneflow/framework/docstr/ctc_decode.py
  python/oneflow/framework/docstr/distance.py
  python/oneflow/framework/docstr/loss.py
  python/oneflow/framework/docstr/random.py
  python/oneflow/nn/modules/dataset.py
Labels: automerge, ci, documentation, build, api

#8647 refactor control stream type
  oneflow/core/eager/blob_instruction_type.cpp
  oneflow/core/vm/barrier_instruction_type.h
  oneflow/core/vm/control_stream_policy.h
  oneflow/core/vm/control_stream_type.cpp
  oneflow/core/vm/control_stream_type.h
  oneflow/core/vm/stream_get_stream_type.h
Labels: enhancement, automerge, eager, system, refactor

#8662 Symbolic local tensor meta
  oneflow/api/python/functional/tensor_api.cpp
  oneflow/core/common/op_args_vector.h
  oneflow/core/common/tensor_desc.cpp
  oneflow/core/common/tensor_desc.h
  oneflow/core/common/tensor_meta.cpp
  oneflow/core/common/tensor_meta.h
  oneflow/core/eager/critical_section_phy_instr_operand.cpp
  oneflow/core/eager/eager_blob_object.cpp
  oneflow/core/eager/eager_blob_object.h
  oneflow/core/eager/op_call_phy_instr_operand.cpp
  oneflow/core/framework/consistency_check.h
  oneflow/core/framework/framework.h
  oneflow/core/framework/global_tensor_infer_cache.h
  oneflow/core/framework/infer_util.h
  oneflow/core/framework/local_tensor_infer_cache.cpp
  oneflow/core/framework/local_tensor_infer_cache.h
  oneflow/core/framework/op_expr.cpp
  oneflow/core/framework/op_interpreter/eager_local_op_interpreter.cpp
  oneflow/core/framework/placement_sbp_util.cpp
  oneflow/core/framework/placement_sbp_util_test.cpp
  oneflow/core/framework/sync_symbol_global_tensor_meta.cpp
  oneflow/core/framework/tensor.cpp
  oneflow/core/framework/tensor.h
  oneflow/core/framework/tensor_impl.cpp
  oneflow/core/framework/tensor_impl.h
  oneflow/core/framework/tensor_methods.cpp
  oneflow/core/framework/user_op_conf.h
  oneflow/core/framework/user_op_registry_manager.cpp
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/core/operator/user_op.cpp
  oneflow/core/register/blob.h
  oneflow/user/kernels/stateful_opkernel.cpp
  oneflow/user/kernels/stateful_opkernel.h
Labels: enhancement, automerge, system

#8437 Feat general basic communication
  oneflow/core/auto_parallel/boxing_collector.cpp
  oneflow/core/auto_parallel/boxing_collector.h
  oneflow/core/framework/sbp_infer_util.cpp
  oneflow/core/framework/sbp_infer_util.h
  oneflow/core/graph/boxing/hierarchical_sub_task_graph_builder_impl.cpp
  oneflow/core/graph/nccl_send_recv_boxing_task_node.cpp
  oneflow/core/graph/nccl_send_recv_boxing_task_node.h
  oneflow/core/graph/straighten_nodes.cpp
  oneflow/core/graph/task_graph.cpp
  oneflow/core/job/eager_nccl_comm_manager.cpp
  oneflow/core/job/eager_nccl_comm_manager.h
  oneflow/core/job/nd_sbp_util.cpp
  oneflow/core/job/nd_sbp_util.h
  oneflow/core/job/task.proto
  oneflow/core/job_rewriter/boxing_with_middle_nodes.cpp
  oneflow/core/kernel/nccl_send_recv_boxing_kernel.cpp
  oneflow/core/lazy/actor/naive_actor.cpp
  oneflow/core/operator/nccl_send_recv_boxing_op.cpp
  oneflow/core/operator/nccl_send_recv_boxing_op_util.cpp
  oneflow/core/operator/nccl_send_recv_boxing_op_util.h
  oneflow/core/operator/op_conf.proto
  oneflow/user/kernels/nccl_logical_send_recv_kernel.cpp
  python/oneflow/test/graph/test_comb1to2d.py
  python/oneflow/test/graph/test_comb2d.py
  python/oneflow/test/graph/test_gbc1to2d.py
  python/oneflow/test/graph/test_gbc2d.py
  python/oneflow/test/graph/test_gbc2to1d.py
  python/oneflow/test/graph/test_gbc2to2d.py
  python/oneflow/test/modules/test_comb2to2d.py
Labels: feature, automerge, graph

#8694 Move nonzero to c plus plus side
  oneflow/core/framework/tensor_util.cpp
  oneflow/core/framework/tensor_util.h
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/user/kernels/arg_where_kernel.cpp
  oneflow/user/kernels/arg_where_kernel_util.cpp
  oneflow/user/kernels/arg_where_kernel_util.cu
  oneflow/user/kernels/arg_where_kernel_util.h
  python/oneflow/nn/modules/nonzero.py
Labels: enhancement, automerge, system

#8733 refine infer shape fn
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/core/functional/impl/common.cpp
  oneflow/core/functional/impl/common.h
  python/oneflow/test/exceptions/test_reshape.py
Labels: enhancement, automerge, eager

#8734 fuse bce loss ops
  oneflow/core/job/job_build_and_infer_ctx.cpp
  oneflow/core/job_rewriter/fuse_bce_reduce_mean_fw_bw_pass.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/binary_cross_entropy_with_logits_mean_kernel.cu
  oneflow/user/ops/binary_cross_entropy_with_logits_reduce_mean_op.cpp
Labels: enhancement, automerge, op

#8736 Fix tensor argsort bug
  python/oneflow/framework/tensor.py
  python/oneflow/test/modules/test_argsort.py
Labels: enhancement, automerge, python

#8718 refactor op call instruction
  oneflow/core/eager/op_call_instruction_type.cpp
  oneflow/core/eager/op_call_instruction_type.h
  oneflow/core/eager/op_call_phy_instr_operand.cpp
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/framework/instructions_builder.h
  oneflow/core/vm/op_call_instruction_policy.cpp
  oneflow/core/vm/op_call_instruction_policy.h
Labels: enhancement, automerge, system, refactor

#8705 oneEmbedding add shuffle p2p kernel
  oneflow/core/embedding/embedding_manager.h
  oneflow/core/job_rewriter/replace_embedding_ops_pass.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/data_shuffle_kernel.cu
  oneflow/user/kernels/fused_dot_feature_interaction_kernel.cu
  oneflow/user/kernels/one_embedding_embedding_gradient_shuffle_p2p_kernel.cu
  oneflow/user/kernels/one_embedding_embedding_shuffle_p2p_kernel.cu
  oneflow/user/kernels/one_embedding_id_shuffle_p2p_kernel.cu
Labels: enhancement, automerge, op

#8756 fix p2p kernel cuda_version
  oneflow/user/kernels/one_embedding_embedding_gradient_shuffle_p2p_kernel.cu
  oneflow/user/kernels/one_embedding_embedding_shuffle_p2p_kernel.cu
Labels: automerge, bug, op

#8729 Dev refactor barrier instruction policy
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/vm/barrier_instruction_policy.h
  oneflow/core/vm/barrier_instruction_type.h
  oneflow/core/vm/global_sync_instruction_policy.h
  oneflow/core/vm/virtual_machine.cpp
  oneflow/core/vm/virtual_machine_engine.cpp
Labels: enhancement, automerge, system, refactor

#8742 Fix masked_fill graph grad
  oneflow/user/ops/masked_fill_op.cpp
  python/oneflow/test/graph/test_graph_masked_fill.py
  python/oneflow/test/modules/test_global_logspace.py
  python/oneflow/test/modules/test_global_masked_fill.py
  python/oneflow/test/modules/test_masked_fill.py
Labels: enhancement, automerge, bug, api, graph

#8754 refactor EpRecordEventInstructionPolicy and AccessBlobArgCbInstructio…
  oneflow/core/eager/blob_instruction_type.cpp
  oneflow/core/eager/blob_instruction_type.h
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/vm/access_blob_arg_cb_instruction_policy.h
  oneflow/core/vm/access_blob_arg_cb_phy_instr_operand.cpp
  oneflow/core/vm/access_blob_arg_cb_phy_instr_operand.h
  oneflow/core/vm/consume_local_dep_object_phy_instr_operand.cpp
  oneflow/core/vm/consume_local_dep_object_phy_instr_operand.h
  oneflow/core/vm/ep_record_event_instruction_policy.h
Labels: enhancement, automerge, system, refactor

#8751 fix var cuda kernel illegal memoey
  oneflow/user/kernels/variance_kernel.cpp
  python/oneflow/test/modules/test_var.py
Labels: enhancement, automerge, bug, eager, api

#8725 Add RMSLayerNorm Module
  docs/source/nn.rst
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/math_functor.cpp
  python/oneflow/nn/__init__.py
  python/oneflow/nn/modules/normalization.py
  python/oneflow/test/modules/test_t5_layernorm.py
Labels: enhancement, automerge, bug, eager, documentation, api

#8735 refactor lazy job instruction policy
  oneflow/core/eager/lazy_job_phy_instr_operand.cpp
  oneflow/core/eager/lazy_job_phy_instr_operand.h
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/framework/instructions_builder.h
  oneflow/core/vm/lazy_job_instruction_policy.h
Labels: enhancement, automerge, eager, system, refactor

#8748 refine qat conv module tests
  python/oneflow/test/modules/test_qat_conv_modules.py
Labels: enhancement, automerge, eager, test, api, need-highest-priority

#8779 refine oneflow readme introduction
  README.md
Labels: enhancement, automerge, documentation, python, refactor

#8727 remove unused graph resource config API
  python/oneflow/framework/config_util.py
  python/oneflow/test/graph/test_optimization_conf.py
Labels: enhancement, automerge, api, graph

#8747 refactor PadFunctor
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
Labels: enhancement, eager, refactor

#8774 refactor touch tensors instruction type
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/vm/touch_tensors_instruction_policy.h
  oneflow/core/vm/touch_tensors_instruction_type.cpp
Labels: enhancement, automerge, system, refactor

#8759 fix gradient shuffle bug and typo
  oneflow/user/kernels/one_embedding_embedding_gradient_shuffle_p2p_kernel.cu
Labels: bug, op

#8591 United allocators
  oneflow/api/python/functional/tensor_api.cpp
  oneflow/core/eager/eager_blob_object.cpp
  oneflow/core/eager/eager_blob_object.h
  oneflow/core/eager/release_tensor_arg_phy_instr_operand.h
  oneflow/core/eager/release_tensor_instruction_type.h
  oneflow/core/ep/cuda/cuda_device.cpp
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/vm/release_tensor_instruction_policy.h
  oneflow/core/vm/virtual_machine_engine.cpp
  oneflow/core/vm/virtual_machine_engine.h
  python/oneflow/nn/qat/conv.py
Labels: enhancement, automerge, eager, system

#8792 resolve the bug of using ONEFLOW_PYTHON_BASE_DIR in CMake
  CMakeLists.txt
  oneflow/api/python/env/env.cpp
  oneflow/api/python/functional/python_frame.h
  oneflow/core/job/graph_scope_vars.cpp
  oneflow/core/job/graph_scope_vars.h
  python/oneflow/__init__.py
Labels: automerge, bug, api, graph

#8746 fix amp pass when lbi2ibns size greater than 1
  oneflow/core/job_rewriter/auto_mixed_precision.cpp
Labels: enhancement, automerge, system

#8783 Return infinity for different sbps while is_mutable
  oneflow/core/framework/sbp_infer_util.cpp
Labels: automerge, bug, graph

#8721 RawReader
  oneflow/api/python/functional/dispatch_stateful_ops.cpp
  oneflow/api/python/functional/dispatch_stateful_ops.yaml
  oneflow/core/graph/compute_task_node.h
  oneflow/core/graph_impl/decode_h2d_compute_task_node.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/raw_reader_kernel.cpp
  oneflow/user/ops/raw_reader_op.cpp
  python/oneflow/nn/__init__.py
  python/oneflow/nn/modules/dataset.py
Labels: feature, automerge, op

#8786 Fix kineto and cupti not found
  CMakeLists.txt
  cmake/oneflow.cmake
Labels: enhancement, bug, build, need-clean-ccache

#8799 fix dynamic_loss_scale_schedule ods and adjust the round trip pass order
  oneflow/core/job/job_build_and_infer_ctx.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
Labels: automerge, bug, system

#8791 refactor auto contiguous and check view inplace operation
  oneflow/core/framework/op_interpreter.h
  oneflow/core/framework/op_interpreter/op_interpreter.cpp
  oneflow/core/framework/op_interpreter/op_interpreter_util.cpp
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/core/functional/tensor_processor.cpp
  oneflow/core/functional/tensor_processor.h
  python/oneflow/test/expensive/test_compatibility.py
Labels: automerge, bug, system, refactor

#8801 Fix pip install failure in release workflow
  .github/workflows/release.yml
Labels: bug, ci

#8761 Dev refactor critical section instruction policy
  oneflow/core/eager/critical_section_instruction_type.h
  oneflow/core/eager/critical_section_phy_instr_operand.h
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/vm/critical_section_instruction_policy.cpp
  oneflow/core/vm/critical_section_instruction_policy.h
  oneflow/core/vm/ep_record_event_instruction_policy.h
  oneflow/core/vm/instruction.cpp
  oneflow/core/vm/instruction.h
  oneflow/core/vm/lazy_job_instruction_policy.h
  oneflow/core/vm/naive_instruction_policy.h
  oneflow/core/vm/release_tensor_instruction_policy.h
  oneflow/core/vm/touch_tensors_instruction_policy.h
  oneflow/core/vm/virtual_machine.cpp
  oneflow/core/vm/virtual_machine_engine.cpp
Labels: enhancement, automerge, system, refactor

#8023 add isfinite
  oneflow/core/ep/common/primitive/elementwise_unary.h
  oneflow/core/ep/common/primitive/unary_functor.h
  oneflow/core/ep/cpu/primitive/unary_functor.h
  oneflow/core/ep/cuda/primitive/unary_functor.cuh
  oneflow/core/ep/include/primitive/unary_op.h
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/util_ops_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/util_ops_kernels.cpp
  oneflow/user/ops/util_ops.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/util_ops.py
  python/oneflow/test/modules/test_util_ops.py
Labels: enhancement, automerge, op, primitive
