Repository Oneflow-Inc/oneflow, pull requests merged in 2023-08, with the labels that each got.

#10308 Speedup bincount
  oneflow/user/kernels/bincount_kernel.cu
  python/oneflow/test/modules/test_bincount.py
Labels: enhancement, op, api

#10312 Add ONEFLOW_DEBUG_CHECKPOINT to debug torch.load
  python/oneflow/framework/check_point_v2.py
Labels: enhancement, automerge, bug, system

#10311 tensor add storage method
  python/oneflow/framework/tensor.py
Labels: eager, documentation, api

#10314 fix shared op warning
  oneflow/core/framework/nn_graph.cpp
Labels: automerge, bug, graph

#10310 flip memory coalescing for last dim case
  oneflow/user/kernels/flip_kernel.cu
  python/oneflow/test/modules/test_flip.py
Labels: enhancement, op, api

#10316 Add squared relu
  docs/source/nn.functional.rst
  docs/source/nn.rst
  docs/source/oneflow.rst
  oneflow/core/autograd/gradient_funcs/activation.cpp
  oneflow/core/ep/common/primitive/broadcast_elementwise_binary.h
  oneflow/core/ep/common/primitive/elementwise_unary.h
  oneflow/core/ep/cpu/primitive/binary_functor.h
  oneflow/core/ep/cpu/primitive/unary_functor.h
  oneflow/core/ep/cuda/primitive/binary_functor.cuh
  oneflow/core/ep/cuda/primitive/unary_functor.cuh
  oneflow/core/ep/include/primitive/binary_op.h
  oneflow/core/ep/include/primitive/unary_op.h
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/activation_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/activation_kernels.cpp
  oneflow/user/ops/square_relu_op.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/activation.py
  python/oneflow/nn/__init__.py
  python/oneflow/nn/functional/__init__.py
  python/oneflow/nn/modules/activation.py
  python/oneflow/test/modules/test_square_relu.py
Labels: op, documentation, api

#10322 fix kMaxInputCount check in GroupedMatmulFunctor
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/user/kernels/grouped_matmul_bias.cu
Labels: automerge, bug, system

#10318 Fix dynamo mock error
  python/oneflow/_dynamo/__init__.py
  python/oneflow/framework/args_tree.py
  python/oneflow/nn/graph/graph.py
Labels: feature, automerge, bug, graph
