Repository Oneflow-Inc/oneflow, pull requests merged in 2023-02, with the labels that each got.

#9816 Fix filechecks not throttled on GPU usage properly
  .github/CODEOWNERS
  .gitignore
  oneflow/ir/test/OneFlow/cuda_code_gen/fuse_cast_scale.mlir
  oneflow/ir/test/OneFlow/cuda_code_gen/gpu_runner.mlir
  oneflow/ir/test/OneFlow/cuda_graph/test_cuda_graph.py
  oneflow/ir/test/OneFlow/cuda_graph/test_cuda_graph_split.py
  oneflow/ir/test/OneFlow/folding/test_conv_bn.py
  oneflow/ir/test/OneFlow/kernel_launch/test_okl_ops.py
  oneflow/ir/test/OneFlow/test_cast_optimal_pass.py
  oneflow/ir/test/OneFlow/with_cuda/test_fuse_bias_add_dropout.py
  oneflow/ir/test/OneFlow/with_cuda/test_fuse_bias_add_gelu.py
  oneflow/ir/test/OneFlow/with_cuda/test_fuse_scale_tril.py
Labels: enhancement, automerge, ir

#9754 Feat multi input sharing graph, save and load compiled graph
  oneflow/api/cpp/framework/graph.cpp
  oneflow/api/python/framework/nn_graph.cpp
  oneflow/core/common/buffer_manager.h
  oneflow/core/framework/nn_graph.cpp
  oneflow/core/framework/nn_graph.h
  oneflow/core/job/compiler.cpp
  oneflow/core/job/job_build_and_infer_ctx.cpp
  oneflow/core/job/job_desc.cpp
  oneflow/core/job/oneflow.cpp
  oneflow/core/job_rewriter/job_completer.cpp
  oneflow/core/job_rewriter/job_completer.h
  python/oneflow/__init__.py
  python/oneflow/framework/session_context.py
  python/oneflow/nn/graph/graph.py
  python/oneflow/test/expensive/test_graph_multi_graph.py
Labels: feature, automerge, graph

#9791 refine device-related code
  oneflow/api/python/framework/random_generator.cpp
  oneflow/core/common/device.proto
  oneflow/core/framework/attr_value.h
  oneflow/core/framework/attr_value_accessor.cpp
  oneflow/core/framework/device.cpp
  oneflow/core/framework/device.h
  oneflow/core/framework/op_interpreter/lazy_op_interpreter.cpp
  oneflow/core/framework/random_generator_impl.cpp
  oneflow/core/framework/tensor.cpp
  oneflow/core/framework/user_op_attr.proto
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/core/job/parallel_desc.cpp
  oneflow/user/ops/copy_op.cpp
Labels: enhancement, automerge, system

#9736 Add op rrelu
  oneflow/core/autograd/gradient_funcs/rrelu.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/activation_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/rrelu_kernel.cpp
  oneflow/user/kernels/rrelu_kernel.cu
  oneflow/user/ops/rrelu_op.cpp
  python/oneflow/framework/docstr/activation.py
  python/oneflow/nn/__init__.py
  python/oneflow/nn/functional/__init__.py
  python/oneflow/nn/modules/activation.py
  python/oneflow/test/modules/test_rrelu.py
Labels: enhancement, feature, automerge, op, api

#9817 [FusedGlu]fix errors
  oneflow/user/kernels/fused_glu_kernel.cu
  oneflow/user/kernels/fused_multi_head_attention_inference_kernel.cu
Labels: automerge, bug, op

#9771 Import onefx into oneflow.fx.
  .github/workflows/test.yml
  python/oneflow/__init__.py
  python/oneflow/fx/__init__.py
  python/oneflow/test/graph/test_fx_fuse.py
  python/oneflow/test/graph/test_fx_replace_ops.py
  python/oneflow/test/graph/test_fx_symbolic_trace_module.py
Labels: feature, api, python

#9804 fix flow.load error on pytorch-saved non-tensor object
  python/oneflow/framework/check_point_v2.py
  python/oneflow/test/modules/test_save_load.py
Labels: automerge, bug, python

#9810 mock torch raises ModuleNotFoundError instead of NotImplementedError
  ci/test/test_mock_script.sh
  python/oneflow/mock_torch/__init__.py
  python/oneflow/test/misc/test_mock_scope.py
Labels: enhancement, automerge, python

#9805 add a env var ONEFLOW_DISABLE_MOCK_TORCH
  python/oneflow/mock_torch/__init__.py
  python/oneflow/test/misc/test_mock_scope.py
Labels: enhancement, automerge, python

#9803 Not set env vars by default
  python/oneflow/distributed/__init__.py
  python/oneflow/framework/env_util.py
  python/oneflow/test/graph/test_input_op_expr.py
  python/oneflow/test/graph/test_output_op_expr.py
  python/oneflow/test/graph/test_user_op_expr.py
  python/oneflow/test/graph/test_variable_op_expr.py
  python/oneflow/test/misc/test_distributed_env_vars.py
Labels: automerge, bug, python

#9632 bump to cpp17
  .github/workflows/canary.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  CMakeLists.txt
  ci/manylinux/build-gcc9.sh
  cmake/cuda.cmake
  cmake/third_party/json.cmake
  oneflow/core/common/cplusplus_17.h
  oneflow/core/common/cplusplus_17_test.cpp
  oneflow/core/common/stride.cpp
  oneflow/user/kernels/stft_kernel.cu
  python/oneflow/test/expensive/test_resnet50_without_bn.py
  python/oneflow/test/expensive/test_rnn_utils.py
  python/oneflow/test/modules/test_dynamic_allocation_gradient_shuffle_shuffle_global.py
  python/oneflow/test/modules/test_swautils.py
  tools/oneflow-tblgen/op_schema_emitter.cpp
Labels: feature, automerge, build, system, need-all-tests-even-fail

#9830 fix scalar judge when input is a numpy scalar
  oneflow/api/python/functional/common.cpp
  python/oneflow/test/tensor/test_tensor_and_ndarray_compatibility.py
Labels: enhancement, automerge, bug, eager, api

#9825 Fix the order of opencv static libraries
  cmake/third_party/opencv.cmake
Labels: automerge, bug, build

#9834 Remove cu102 from release
  .github/workflows/release.yml
Labels: enhancement, ci

#9826 support_float16_nonzero
  oneflow/user/kernels/arg_where_kernel.cpp
  oneflow/user/kernels/arg_where_kernel_util.cpp
  oneflow/user/kernels/arg_where_kernel_util.cu
  python/oneflow/test/modules/test_nonzero.py
Labels: enhancement, automerge, system

#9836 [OneEmbedding] Fix snapshot load
  oneflow/core/embedding/cached_key_value_store.cu
  oneflow/core/embedding/full_cache.cu
Labels: automerge, bug, op, embedding

#9833 make some functions return multi values
  oneflow/api/python/framework/random_generator.cpp
  oneflow/core/framework/device.cpp
  oneflow/core/framework/device.h
  oneflow/core/job/parallel_desc.cpp
  oneflow/core/job/parallel_desc.h
Labels: enhancement, automerge, system

#9841 fix communication in background threads
  oneflow/api/cpp/env.cpp
  oneflow/api/python/rpc/global_rpc_token_scope.cpp
  oneflow/core/framework/rank_group_rpc_util.cpp
  oneflow/core/framework/rank_group_rpc_util.h
  oneflow/core/framework/transport_token.cpp
  oneflow/core/job/rank_group_scope.cpp
  oneflow/core/job/rank_group_scope.h
  oneflow/core/job/rank_group_scope_test.cpp
  oneflow/core/thread/thread_global_id.cpp
  oneflow/core/thread/thread_global_id.h
  python/oneflow/__init__.py
  python/oneflow/test/modules/test_comm.py
Labels: automerge, bug, system

#9807 Add oneflow.nn.functional.depend api
  oneflow/core/autograd/gradient_funcs/depand.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/util_ops_functor.cpp
  oneflow/core/job/job_build_and_infer_ctx.cpp
  oneflow/core/job/job_conf.proto
  oneflow/core/job/job_desc.h
  oneflow/core/job_rewriter/prune_depend_op_pass.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/copy_data_content_kernel.cpp
  oneflow/user/ops/depend_op.cpp
  python/oneflow/framework/docstr/__init__.py
  python/oneflow/framework/docstr/depend.py
  python/oneflow/framework/function_util.py
  python/oneflow/nn/functional/__init__.py
  python/oneflow/nn/functional/functional_depend.py
  python/oneflow/test/graph/test_graph_depend.py
Labels: feature, op, test, documentation, api, python

#9821 refine graph python stack
  oneflow/api/python/autograd/autograd.cpp
  oneflow/api/python/functional/python_frame.h
  oneflow/extension/stack/python/stack_getter.cpp
  oneflow/extension/stack/python/stack_getter.h
  tools/functional/generate_dispatch_stateful_ops.py
  tools/functional/generate_functional_api.py
  tools/functional/generate_tensor_api.py
Labels: feature, automerge, graph

#9838 fix ci test error introduced by (#9781)
  python/oneflow/test/modules/test_swautils.py
Labels: enhancement, automerge, python

#9850 remove redundant Device constructor in copy op
  oneflow/user/ops/copy_op.cpp
Labels: enhancement, automerge, op, system

#9831 Fix the ci test error introduced by (#9771).
  python/oneflow/test/graph/test_fx_fuse.py
Labels: automerge, bug, ci

#9853 Add attn_bias support for fmha
  CMakeLists.txt
  cmake/oneflow.cmake
  cmake/third_party/cutlass.cmake
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/fused_multi_head_attention_inference_kernel.cu
  oneflow/user/ops/fused_multi_head_attention_inference_op.cpp
  python/oneflow/test/modules/test_fused_multi_head_attention_inference.py
Labels: enhancement, op

#9846 [DDP] support arbitrary output type by ArgsTree
  python/oneflow/framework/args_tree.py
  python/oneflow/framework/check_point_v2.py
  python/oneflow/nn/graph/graph.py
  python/oneflow/nn/graph/proxy.py
  python/oneflow/nn/graph/util.py
  python/oneflow/nn/parallel/distributed.py
  python/oneflow/test/graph/test_graph_io_check.py
  python/oneflow/test/modules/test_ddp_multi_outputs.py
  python/oneflow/test/modules/test_global_cast.py
  python/oneflow/utils/global_view/global_utils.py
  python/oneflow/utils/global_view/to_global.py
  python/oneflow/utils/global_view/to_local.py
Labels: automerge, bug, python

#9851 Refine vm::TensorStorage
  oneflow/api/python/dlpack/converter.cpp
  oneflow/api/python/functional/tensor_api.cpp
  oneflow/core/eager/eager_blob_object.cpp
  oneflow/core/eager/eager_blob_object.h
  oneflow/core/eager/tensor_storage.cpp
  oneflow/core/eager/tensor_storage.h
  oneflow/core/framework/tensor_impl.cpp
  oneflow/core/framework/tensor_storage.cpp
  oneflow/core/vm/release_tensor_instruction_policy.h
Labels: enhancement, automerge, eager

#9856 trigger CI when added to a merge queue
  .github/workflows/test.yml
Labels: feature, automerge, ci

#9852 fix_unbalanced_mem_allocate_of_local_to_global
  oneflow/core/framework/op_interpreter/eager_local_op_interpreter.cpp
Labels: enhancement, automerge, system

#9842 add bitwise_and/or/xor ops
  docs/source/oneflow.rst
  docs/source/tensor.rst
  oneflow/api/python/framework/tensor_functions.cpp
  oneflow/core/ep/common/primitive/binary_functor.h
  oneflow/core/ep/common/primitive/broadcast_elementwise_binary.h
  oneflow/core/ep/cpu/primitive/broadcast_elementwise_binary.cpp
  oneflow/core/ep/cuda/primitive/broadcast_elementwise_binary.cu
  oneflow/core/ep/cuda/primitive/broadcast_elementwise_binary_bitwise.cu
  oneflow/core/ep/include/primitive/binary_op.h
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/binary_functor.cpp
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/core/ndarray/binary_func.h
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/math_binary_broadcast_kernels.cpp
  oneflow/user/kernels/scalar_bitwise_kernels.cpp
  oneflow/user/ops/math_binary_broadcast_seq.h
  oneflow/user/ops/scalar_bitwise_op.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/__init__.py
  python/oneflow/framework/docstr/bitwise_ops.py
  python/oneflow/framework/docstr/tensor.py
  python/oneflow/test/modules/test_bitwise.py
  python/oneflow/test/modules/test_global_bitwise.py
  python/oneflow/test_utils/test_util.py
Labels: enhancement, automerge, op, test, api

#9845 fix_error_of_ctc_loss_with_diff_device
  oneflow/core/functional/impl/nn_functor.cpp
  python/oneflow/test/modules/test_ctc_loss.py
Labels: enhancement, automerge, system, need-clean-ccache

#9854 Fix Mulcast Pattern Rewrite
  oneflow/ir/lib/OneFlow/OneFlowRewrites.cpp
  oneflow/ir/lib/OneFlow/PDLL/ElementwiseFusionPatterns.pdll
Labels: enhancement, automerge, ir

#9859 Dev add bitwise_not op
  docs/source/oneflow.rst
  oneflow/api/python/framework/tensor_functions.cpp
  oneflow/core/ep/common/primitive/elementwise_unary.h
  oneflow/core/ep/common/primitive/unary_functor.h
  oneflow/core/ep/cpu/primitive/elementwise_unary.cpp
  oneflow/core/ep/cuda/primitive/elementwise_unary.cu
  oneflow/core/ep/include/primitive/unary_op.h
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/unary_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/math_unary_elementwise_primitive_kernel.cpp
  oneflow/user/ops/math_unary_elementwise_op.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/bitwise_ops.py
  python/oneflow/test/modules/test_bitwise.py
  python/oneflow/test/modules/test_global_bitwise.py
Labels: enhancement, automerge, op, test, api

#9862 update xformers fmha
  CMakeLists.txt
  oneflow/user/kernels/fused_multi_head_attention_inference_kernel.cu
Labels: enhancement, automerge, op

#9445 Switch cpu threading runtime dynamically
  .github/workflows/simple.yml
  CMakeLists.txt
  cmake/caches/ci/cpu-asan-ubsan.cmake
  cmake/caches/ci/cpu-tsan.cmake
  cmake/caches/ci/cpu.cmake
  cmake/caches/ci/cuda.cmake
  cmake/caches/ci/serving/openvino.cmake
  cmake/caches/cn/fast/mlir-cpu.cmake
  cmake/caches/cn/fast/mlir-cuda-75.cmake
  cmake/cuda.cmake
  cmake/oneflow.cmake
  cmake/platform.cmake
  cmake/third_party/oneDNN.cmake
  cmake/threading.cmake
  cmake/util.cmake
  external/CMakeLists.txt
  external/onetbb/CMakeLists.txt
  oneflow/core/ep/cpu/cpu_stream.cpp
  oneflow/core/ep/cpu/cpu_stream.h
  oneflow/core/thread/thread_runtime.h
  oneflow/core/thread/thread_runtime_factory.cpp
  oneflow/core/thread/thread_runtime_factory.h
Labels: enhancement, system

#9598 Unary: add broadcast_elementwise_unary unit test, fix pack
  oneflow/core/ep/common/primitive/broadcast_elementwise_unary.h
  oneflow/core/ep/common/primitive/elementwise_unary.h
  oneflow/core/ep/common/primitive/unary_functor.h
  oneflow/core/ep/common/primitive/util.h
  oneflow/core/ep/cpu/primitive/broadcast_elementwise_unary.cpp
  oneflow/core/ep/cuda/primitive/broadcast_elementwise_unary.cu
  oneflow/core/ep/cuda/primitive/unary_functor.cuh
  oneflow/core/ep/test/primitive/unary_test.cpp
Labels: feature, op, primitive

#9495 oneflow lite model converter
  CMakeLists.txt
  oneflow/ir/CMakeLists.txt
  oneflow/ir/include/OneFlow/OneFlowOps.td
  oneflow/ir/oneflow-lite/CMakeLists.txt
  oneflow/ir/oneflow-lite/OneFlowLiteCompileMain.cpp
  oneflow/ir/oneflow-lite/include/OneFlow/ConvertToLiteExecutable.h
  oneflow/ir/oneflow-lite/include/OneFlow/FlatbufferUtils.h
  oneflow/ir/oneflow-lite/include/OneFlow/OneFlowLiteUtils.h
  oneflow/ir/oneflow-lite/include/OneFlow/Transform/FoldVariable.h
  oneflow/ir/oneflow-lite/include/OneFlow/Transform/InferPlacement.h
  oneflow/ir/oneflow-lite/include/OneFlow/Transform/InsertTransferOp.h
  oneflow/ir/oneflow-lite/include/OneFlow/Transform/Lowering/LoweringAscend.h
  oneflow/ir/oneflow-lite/include/OneFlow/Transform/Lowering/LoweringAscendUtils.h
  oneflow/ir/oneflow-lite/include/OneFlow/Transform/LoweringLaunchJob.h
  oneflow/ir/oneflow-lite/include/OneFlow/Transform/MemoryPlanning.h
  oneflow/ir/oneflow-lite/include/OneFlow/Transform/PartitionLaunchJob.h
  oneflow/ir/oneflow-lite/lib/CMakeLists.txt
  oneflow/ir/oneflow-lite/lib/OneFlow/CMakeLists.txt
  oneflow/ir/oneflow-lite/lib/OneFlow/ConvertToLiteExecutable.cpp
  oneflow/ir/oneflow-lite/lib/OneFlow/FlatbufferUtils.cpp
  oneflow/ir/oneflow-lite/lib/OneFlow/OneFlowLiteUtils.cpp
  oneflow/ir/oneflow-lite/lib/OneFlow/Transform/FoldVariable.cpp
  oneflow/ir/oneflow-lite/lib/OneFlow/Transform/InferPlacement.cpp
  oneflow/ir/oneflow-lite/lib/OneFlow/Transform/InsertTransferOp.cpp
  oneflow/ir/oneflow-lite/lib/OneFlow/Transform/Lowering/LoweringAscend.cpp
  oneflow/ir/oneflow-lite/lib/OneFlow/Transform/LoweringLaunchJob.cpp
  oneflow/ir/oneflow-lite/lib/OneFlow/Transform/MemoryPlanning.cpp
  oneflow/ir/oneflow-lite/lib/OneFlow/Transform/PartitionLaunchJob.cpp
  oneflow/ir/oneflow-lite/lib/OneFlow/cmake/FindAscendSdk.cmake
  oneflow/ir/oneflow-lite/schemas/CMakeLists.txt
  oneflow/ir/oneflow-lite/schemas/attributes/CMakeLists.txt
  oneflow/ir/oneflow-lite/schemas/attributes/bool.fbs
  oneflow/ir/oneflow-lite/schemas/attributes/f32.fbs
  oneflow/ir/oneflow-lite/schemas/attributes/f32s.fbs
  oneflow/ir/oneflow-lite/schemas/attributes/f64.fbs
  oneflow/ir/oneflow-lite/schemas/attributes/i32.fbs
  oneflow/ir/oneflow-lite/schemas/attributes/i32s.fbs
  oneflow/ir/oneflow-lite/schemas/attributes/i64.fbs
  oneflow/ir/oneflow-lite/schemas/attributes/i64s.fbs
  oneflow/ir/oneflow-lite/schemas/attributes/shape.fbs
  oneflow/ir/oneflow-lite/schemas/attributes/shapes.fbs
  oneflow/ir/oneflow-lite/schemas/attributes/str.fbs
  oneflow/ir/oneflow-lite/schemas/attributes/strs.fbs
  oneflow/ir/oneflow-lite/schemas/executable.fbs
  oneflow/ir/oneflow-lite/schemas/install_flatcc.cmake
Labels: enhancement, automerge, system, lite

#9870 Refactor local to global api
  oneflow/core/framework/op_interpreter/eager_local_op_interpreter.cpp
  oneflow/core/functional/impl/global_cast.cpp
  python/oneflow/framework/docstr/tensor.py
  python/oneflow/test/tensor/test_tensor_part_2.py
Labels: enhancement, automerge, system, api, refactor

#9871 Fix an issue with OneTBB linking to OneDNN
  cmake/third_party/oneDNN.cmake
  external/onetbb/CMakeLists.txt
Labels: enhancement, bug, build, system

#9794 Add BroadcastMulToScalarMulPattern PDLL Pattern
  oneflow/ir/include/OneFlow/OneFlowPatterns.td
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/ir/lib/OneFlow/OneFlowRewrites.cpp
  oneflow/ir/lib/OneFlow/PDLL/ForwardOpPatterns.pdll
  oneflow/ir/lib/OneFlow/PDLL/OneFlowPDLLUtils.pdll
  oneflow/ir/lib/OneFlow/Passes.cpp
  oneflow/ir/oneflow-translate/lib/OneFlow/MLIROneFlowTranslation.cpp
  oneflow/ir/test/OneFlow/cuda_code_gen/test_fuser_cast_scale.py
  oneflow/ir/test/OneFlow/fuse_forward_ops.mlir
Labels: enhancement, ir

#9818 [Graph] Stream-Ordered Memory Allocation
  oneflow/core/ep/common/device.cpp
  oneflow/core/ep/cuda/cuda_device.cpp
  oneflow/core/ep/cuda/cuda_device.h
  oneflow/core/ep/cuda/cuda_stream.cpp
  oneflow/core/ep/cuda/cuda_stream.h
  oneflow/core/ep/include/device.h
  oneflow/core/ep/include/stream.h
  oneflow/core/graph/collective_boxing_task_node.cpp
  oneflow/core/graph/copy_task_node.cpp
  oneflow/core/graph/copy_task_node.h
  oneflow/core/kernel/user_kernel.cpp
  oneflow/core/lazy/actor/actor.cpp
  oneflow/core/lazy/actor/actor.h
  oneflow/core/lazy/actor/light_actor.cpp
  oneflow/core/lazy/actor/repeat_actor.cpp
  oneflow/core/register/blob.cpp
  oneflow/core/register/register.cpp
  oneflow/core/register/register.h
  oneflow/core/register/register_manager.cpp
  oneflow/core/register/register_manager.h
  oneflow/core/register/runtime_register_desc.cpp
  oneflow/core/register/runtime_register_desc.h
Labels: enhancement, system

#9580 Fix straighten memory diffuser bug
  oneflow/core/graph/straighten_nodes.cpp
  oneflow/core/job/intra_job_mem_sharing_util.cpp
  oneflow/core/job/job_conf.proto
  python/oneflow/nn/graph/graph_config.py
Labels: feature, automerge, graph

#9277 add generic_ctor to pass dtype for type tensor
  oneflow/api/python/framework/tensortype.cpp
  oneflow/api/python/functional/tensor_api.cpp
  oneflow/api/python/functional/tensor_api.yaml
  python/oneflow/test/modules/test_type_tensor.py
Labels: enhancement, automerge, bug, test, api

#9519 Fuse att pat
  oneflow/ir/lib/OneFlow/OneFlowRewrites.cpp
  oneflow/ir/lib/OneFlow/PDLL/ForwardOpPatterns.pdll
  oneflow/ir/lib/OneFlow/PDLL/OneFlowPDLLUtils.pdll
  oneflow/ir/oneflow-translate/lib/OneFlow/MLIROneFlowTranslation.cpp
  oneflow/ir/test/OneFlow/fuse_forward_ops.mlir
  oneflow/ir/test/OneFlow/with_cuda/test_fused_multi_head_attention_inference.py
Labels: enhancement, automerge, ir

#9886 Reduce arg combinations of sgd/adam/adamw unittest to prevent timeout
  python/oneflow/test/modules/test_optim_adam.py
  python/oneflow/test/modules/test_optim_adamw.py
  python/oneflow/test/modules/test_optim_sgd.py
Labels: enhancement, automerge, test

#9889 Fix tbbbind linking
  external/onetbb/CMakeLists.txt
Labels: automerge, bug, build

#9880 Fix bug of the sum priority ratio
  oneflow/core/operator/operator.cpp
Labels: feature, automerge, eager, graph

#9894 Fix fmt not found in xrt
  external/fmt/CMakeLists.txt
Labels: automerge, bug, build

#9883 fix Interpolate warning in graph
  python/oneflow/nn/modules/interpolate.py
Labels: automerge, bug, eager

#9896 Revert "Refine vm::TensorStorage"
  oneflow/api/python/dlpack/converter.cpp
  oneflow/api/python/functional/tensor_api.cpp
  oneflow/core/eager/eager_blob_object.cpp
  oneflow/core/eager/eager_blob_object.h
  oneflow/core/eager/tensor_storage.cpp
  oneflow/core/eager/tensor_storage.h
  oneflow/core/framework/tensor_impl.cpp
  oneflow/core/framework/tensor_storage.cpp
  oneflow/core/vm/release_tensor_instruction_policy.h
Labels: automerge, bug, eager

#9891 add default Hob to kernels
  oneflow/core/framework/user_op_kernel_registry.cpp
  oneflow/user/kernels/acc_kernel.cpp
  oneflow/user/kernels/assign_kernel.cpp
  oneflow/user/kernels/cast_to_static_shape_kernel.cpp
  oneflow/user/kernels/copy_data_content_kernel.cpp
  oneflow/user/kernels/copy_hd_kernel.cpp
  oneflow/user/kernels/copy_kernel.cpp
  oneflow/user/kernels/empty_kernel.cpp
  oneflow/user/kernels/nop_kernel.cpp
  oneflow/user/kernels/raw_reader_kernel.cpp
  oneflow/user/kernels/throw_error_kernel.cpp
  oneflow/user/kernels/zero_like_kernel.cpp
Labels: automerge, bug, op

#9903 Avoid using 'device_type == kCUDA' equation in GenLightPlan
  oneflow/core/job/plan_util.cpp
Labels: enhancement, automerge, graph

#9884 Run nn.Graph by VM
  oneflow/api/python/framework/nn_graph.cpp
  oneflow/core/framework/nn_graph.h
  oneflow/core/job/job_interpreter.cpp
  oneflow/core/job/job_interpreter.h
  python/oneflow/nn/graph/graph.py
  python/oneflow/test/graph/test_run_graph_by_vm.py
Labels: feature, automerge, graph

#9876 add APIs and update mock torch support torchvision
  ci/test/test_mock_script.sh
  python/oneflow/hub.py
  python/oneflow/jit/__init__.py
  python/oneflow/jit/_script.py
  python/oneflow/mock_torch/__init__.py
  python/oneflow/mock_torch/__main__.py
  python/oneflow/mock_torch/torch/__init__.py
  python/oneflow/ops/__init__.py
  python/oneflow/test/misc/test_mock_scope.py
Labels: enhancement, automerge, python

#9868 fix a bug inside gather kernel
  oneflow/user/kernels/gather_kernel.cpp
Labels: automerge, bug, op

#9901 Rm groups in OneFlowUserOps.td
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
Labels: enhancement, automerge, ir

#9881 Dev add tensor new api
  oneflow/api/python/framework/tensor_functions.cpp
  python/oneflow/framework/docstr/tensor.py
  python/oneflow/test/modules/test_global_tensor_new.py
  python/oneflow/test/tensor/test_tensor_part_3.py
Labels: enhancement, automerge, test, documentation, api

#9909 refactor and remove order_in_graph
  oneflow/core/graph/plan_task_graph.cpp
  oneflow/core/graph/plan_task_graph.h
  oneflow/core/graph/straighten_nodes.cpp
  oneflow/core/graph/task_graph.cpp
  oneflow/core/graph/task_graph.h
  oneflow/core/graph/task_node.cpp
  oneflow/core/graph/task_node.h
  oneflow/core/job/intra_job_mem_sharing_util.cpp
  oneflow/core/job/plan_util.cpp
  oneflow/core/job/task.proto
  oneflow/core/job_rewriter/logical_chain_pass.cpp
  oneflow/core/operator/op_conf.proto
Labels: bug, graph

#9887 Functional ctc loss
  docs/source/nn.functional.rst
  python/oneflow/nn/functional/__init__.py
  python/oneflow/nn/functional/batch_norm.py
  python/oneflow/nn/functional/ctc_loss.py
  python/oneflow/nn/functional/deform_conv.py
  python/oneflow/nn/functional/depend.py
  python/oneflow/nn/functional/maxpool.py
  python/oneflow/nn/functional/pad.py
  python/oneflow/test/modules/test_ctc_loss.py
Labels: enhancement, automerge, bug, api, python

#9888 support copy_ on different devices and dtypes
  oneflow/api/python/functional/tensor_api.cpp
  python/oneflow/framework/tensor.py
  python/oneflow/test/modules/test_copy.py
  python/oneflow/test/tensor/test_global_tensor.py
  python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py
Labels: automerge, bug, python

#9900 GroupwiseQuantization
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/quantization.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/groupwise_quantization_kernels.cu
  oneflow/user/ops/fused_linear_with_groupwise_quantized_weight_op.cpp
  oneflow/user/ops/groupwise_dequantize_op.cpp
  python/oneflow/test/modules/test_groupwise_quantization.py
Labels: feature, automerge, op
