Repository Oneflow-Inc/oneflow, pull requests merged in 2023-01, with the labels that each got.

#9624 imporve syncbn forward speed
  python/oneflow/nn/modules/batchnorm.py
Labels: enhancement, automerge, eager, op, python

#9638 Add more issue templates.
  .github/ISSUE_TEMPLATE/blank_issue.yml
  .github/ISSUE_TEMPLATE/documention_issue.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/performance_issue.yml
  .github/ISSUE_TEMPLATE/question.yml
Labels: enhancement, serving

#9671 fix zero dp sequence size check
  oneflow/core/job_rewriter/optimizer_placement_optimization_pass.cpp
Labels: automerge, bug, graph

#9675 Feat auto parallel memory
  docs/source/auto_parallel.rst
  oneflow/core/auto_parallel/algorithm_util.cpp
  oneflow/core/auto_parallel/algorithm_util.h
  oneflow/core/auto_parallel/auto_memory.cpp
  oneflow/core/auto_parallel/auto_memory.h
  oneflow/core/auto_parallel/boxing_collector.cpp
  oneflow/core/auto_parallel/boxing_collector.h
  oneflow/core/auto_parallel/sbp_constructor.cpp
  oneflow/core/auto_parallel/sbp_constructor.h
  oneflow/core/auto_parallel/sbp_edge.cpp
  oneflow/core/auto_parallel/sbp_edge.h
  oneflow/core/auto_parallel/sbp_graph.cpp
  oneflow/core/auto_parallel/sbp_graph.h
  oneflow/core/auto_parallel/sbp_node.cpp
  oneflow/core/auto_parallel/sbp_node.h
  oneflow/core/framework/sbp_infer_util.cpp
  oneflow/core/framework/sbp_infer_util.h
  oneflow/core/graph/normal_forward_compute_task_node.h
  oneflow/core/graph/straighten_nodes.cpp
  oneflow/core/graph/straighten_nodes.h
  oneflow/core/graph/task_graph.cpp
  oneflow/core/graph_impl/normal_forward_compute_task_node.cpp
  oneflow/core/job/job_conf.proto
  oneflow/core/job/memory_share_strategy.cpp
  python/oneflow/nn/graph/graph_config.py
Labels: AutoParallel

#9576 Refactor rpc connection failure mechanism
  oneflow/core/common/env_var/bootstrap.h
  oneflow/core/control/rank_info_bootstrap_server.cpp
  oneflow/core/control/rank_info_bootstrap_server.h
  oneflow/core/control/rpc_client.cpp
Labels: automerge, bug, system, refactor

#9617 Supports tenosr and ndarray compatibility
  oneflow/api/python/framework/tensor_functions.cpp
  python/oneflow/test/tensor/test_global_tensor_and_ndarray_compatibility.py
  python/oneflow/test/tensor/test_tensor_and_ndarray_compatibility.py
Labels: enhancement, feature, automerge, bug, eager, api

#9682 allow override ONEFLOW_PYTHON_STACK_GETTER
  oneflow/core/common/env_var/debug_mode.h
Labels: enhancement, automerge, system, need-all-tests-even-fail

#9681 Fix stack getter segfault caused by is_shutting_down and gil
  oneflow/extension/stack/python/stack_getter.cpp
  python/oneflow/__init__.py
Labels: bug, system, python

#9683 Add is_cufft_available in stft case
  python/oneflow/test/modules/test_stft.py
Labels: enhancement, automerge, test

#9701 Use ubuntu latest in GH actions
  .github/workflows/pr.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
Labels: automerge, bug, ci

#9702 Fix GH action ubuntu latest
  .github/workflows/pr.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  oneflow/core/profiler/event_recorder.cpp
Labels: automerge, bug, ci

#9692 Fix StackGradOp::GetSbp
  oneflow/user/ops/stack_op.cpp
Labels: automerge, bug, op

#9703 Fix tensor topk param
  oneflow/api/python/framework/tensor_functions.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/array_functor.cpp
  python/oneflow/framework/tensor.py
  python/oneflow/test/tensor/test_tensor_part_1.py
Labels: enhancement, automerge, test, api

#9698 vm single thread mode
  oneflow/core/common/env_var/vm.h
  oneflow/core/vm/stream_policy.cpp
  oneflow/core/vm/virtual_machine.cpp
  oneflow/core/vm/virtual_machine.h
  python/oneflow/test/modules/test_single_threaded_vm.py
Labels: feature, automerge, eager

#9678 New version 0.9.1
  .github/workflows/release.yml
  CHANGELOG.md
  README.md
  docs/source/environment_variables.rst
  tools/generate_pip_version.py
Labels: enhancement, automerge, build

#9670 move trt_flash_attn to thirdparty
  .github/workflows/test.yml
  ci/check/run_clang_format.py
  cmake/oneflow.cmake
  cmake/third_party.cmake
  cmake/third_party/cutlass.cmake
  cmake/third_party/trt_flash_attention.cmake
  oneflow/user/kernels/fmha_flash_attention/cudaDriverWrapper.cpp
  oneflow/user/kernels/fmha_flash_attention/cudaDriverWrapper.h
  oneflow/user/kernels/fmha_flash_attention/fmha.cpp
  oneflow/user/kernels/fmha_flash_attention/fmha.h
  oneflow/user/kernels/fmha_flash_attention/include/commonDatatype.h
  oneflow/user/kernels/fmha_flash_attention/include/fmha_flash_attention.h
  oneflow/user/kernels/fmha_flash_attention/include/sharedCubinLoader.h
  oneflow/user/kernels/fmha_flash_attention/src/fmha_v2_flash_attention_fp16_S_128_sm80.cubin.cpp
  oneflow/user/kernels/fmha_flash_attention/src/fmha_v2_flash_attention_fp16_S_128_sm86.cubin.cpp
  oneflow/user/kernels/fmha_flash_attention/src/fmha_v2_flash_attention_fp16_S_128_sm89.cubin.cpp
  oneflow/user/kernels/fmha_flash_attention/src/fmha_v2_flash_attention_fp16_S_160_sm80.cubin.cpp
  oneflow/user/kernels/fmha_flash_attention/src/fmha_v2_flash_attention_fp16_S_160_sm86.cubin.cpp
  oneflow/user/kernels/fmha_flash_attention/src/fmha_v2_flash_attention_fp16_S_160_sm89.cubin.cpp
  oneflow/user/kernels/fmha_flash_attention/src/fmha_v2_flash_attention_fp16_S_16_sm80.cubin.cpp
  oneflow/user/kernels/fmha_flash_attention/src/fmha_v2_flash_attention_fp16_S_16_sm86.cubin.cpp
  oneflow/user/kernels/fmha_flash_attention/src/fmha_v2_flash_attention_fp16_S_16_sm89.cubin.cpp
  oneflow/user/kernels/fmha_flash_attention/src/fmha_v2_flash_attention_fp16_S_256_sm80.cubin.cpp
  oneflow/user/kernels/fmha_flash_attention/src/fmha_v2_flash_attention_fp16_S_256_sm86.cubin.cpp
  oneflow/user/kernels/fmha_flash_attention/src/fmha_v2_flash_attention_fp16_S_256_sm89.cubin.cpp
  oneflow/user/kernels/fmha_flash_attention/src/fmha_v2_flash_attention_fp16_S_32_sm80.cubin.cpp
  oneflow/user/kernels/fmha_flash_attention/src/fmha_v2_flash_attention_fp16_S_32_sm86.cubin.cpp
  oneflow/user/kernels/fmha_flash_attention/src/fmha_v2_flash_attention_fp16_S_32_sm89.cubin.cpp
  oneflow/user/kernels/fmha_flash_attention/src/fmha_v2_flash_attention_fp16_S_40_sm80.cubin.cpp
  oneflow/user/kernels/fmha_flash_attention/src/fmha_v2_flash_attention_fp16_S_40_sm86.cubin.cpp
  oneflow/user/kernels/fmha_flash_attention/src/fmha_v2_flash_attention_fp16_S_40_sm89.cubin.cpp
  oneflow/user/kernels/fmha_flash_attention/src/fmha_v2_flash_attention_fp16_S_64_sm80.cubin.cpp
  oneflow/user/kernels/fmha_flash_attention/src/fmha_v2_flash_attention_fp16_S_64_sm86.cubin.cpp
  oneflow/user/kernels/fmha_flash_attention/src/fmha_v2_flash_attention_fp16_S_64_sm89.cubin.cpp
  oneflow/user/kernels/fmha_flash_attention/src/fmha_v2_flash_attention_fp16_S_80_sm80.cubin.cpp
  oneflow/user/kernels/fmha_flash_attention/src/fmha_v2_flash_attention_fp16_S_80_sm86.cubin.cpp
  oneflow/user/kernels/fmha_flash_attention/src/fmha_v2_flash_attention_fp16_S_80_sm89.cubin.cpp
  oneflow/user/kernels/fused_multi_head_attention_inference_kernel.cu
Labels: enhancement, automerge, op, build, need-all-tests-even-fail

#9664 support bfloat16 in typeinfo
  oneflow/api/python/framework/typeinfo.cpp
  oneflow/core/common/data_type.cpp
  oneflow/core/common/data_type.h
  oneflow/core/framework/dtype.cpp
  python/oneflow/test/modules/test_info.py
Labels: enhancement, automerge, test, api, python

#9690 fix stft large tensor bug
  python/oneflow/test/modules/test_stft.py
Labels: automerge, bug, ci, eager, api

#9712 OneEmbedding add trunc_normal initializer
  oneflow/user/kernels/one_embedding_kernels.cu
  python/oneflow/one_embedding.py
Labels: enhancement, op, embedding

#9672 Add flow.distributed apis comptible with PyTorch
  docs/source/distributed.rst
  python/oneflow/distributed/__init__.py
Labels: enhancement, automerge, python

#9707 conv op more friendly error message
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/user/ops/conv_op.cpp
Labels: enhancement, feature, automerge, bug, eager, api

#9714 fix bug of `random_cpu/gpu_placement calc_device`
  python/oneflow/test_utils/automated_test_util/generators.py
Labels: enhancement, automerge, test, python

#9258 Auto Parallel consider memory
  docs/source/auto_parallel.rst
  oneflow/core/auto_parallel/algorithm_util.cpp
  oneflow/core/auto_parallel/algorithm_util.h
  oneflow/core/auto_parallel/auto_memory.cpp
  oneflow/core/auto_parallel/auto_memory.h
  oneflow/core/auto_parallel/boxing_collector.cpp
  oneflow/core/auto_parallel/boxing_collector.h
  oneflow/core/auto_parallel/sbp_constructor.cpp
  oneflow/core/auto_parallel/sbp_constructor.h
  oneflow/core/auto_parallel/sbp_edge.cpp
  oneflow/core/auto_parallel/sbp_edge.h
  oneflow/core/auto_parallel/sbp_graph.cpp
  oneflow/core/auto_parallel/sbp_graph.h
  oneflow/core/auto_parallel/sbp_node.cpp
  oneflow/core/auto_parallel/sbp_node.h
  oneflow/core/framework/sbp_infer_util.cpp
  oneflow/core/framework/sbp_infer_util.h
  oneflow/core/graph/normal_forward_compute_task_node.h
  oneflow/core/graph/straighten_nodes.cpp
  oneflow/core/graph/straighten_nodes.h
  oneflow/core/graph/task_graph.cpp
  oneflow/core/graph_impl/normal_forward_compute_task_node.cpp
  oneflow/core/job/job_conf.proto
  oneflow/core/job/memory_share_strategy.cpp
  oneflow/core/job_rewriter/optimizer_placement_optimization_pass.cpp
  python/oneflow/nn/graph/graph_config.py
Labels: feature, automerge, graph, AutoParallel

#9340 Contiguous params optimizer
  python/oneflow/nn/optimizer/adadelta.py
  python/oneflow/nn/optimizer/adagrad.py
  python/oneflow/nn/optimizer/adam.py
  python/oneflow/nn/optimizer/adamw.py
  python/oneflow/nn/optimizer/lamb.py
  python/oneflow/nn/optimizer/rmsprop.py
  python/oneflow/nn/optimizer/sgd.py
  python/oneflow/optim/optimizer.py
  python/oneflow/test/modules/test_optim_adadelta.py
  python/oneflow/test/modules/test_optim_adagrad.py
  python/oneflow/test/modules/test_optim_adam.py
  python/oneflow/test/modules/test_optim_adamw.py
  python/oneflow/test/modules/test_optim_lamb.py
  python/oneflow/test/modules/test_optim_rmsprop.py
  python/oneflow/test/modules/test_optim_sgd.py
Labels: feature, eager, python

#9680 restruct fast_atomic_add location
  oneflow/core/cuda/atomic.cuh
  oneflow/core/kernel/kernel_util.cuh
  oneflow/user/kernels/upsample_bicubic_2d_kernel.cu
  oneflow/user/kernels/upsample_bilinear_2d_kernel.cu
  oneflow/user/kernels/upsample_linear_1d_kernel.cu
  oneflow/user/kernels/upsample_nearest_kernel.cu
  oneflow/user/kernels/upsample_trilinear_3d_kernel.cu
Labels: enhancement, feature, automerge, eager, api

#9720 Remove the base class of _ConstantBase to solve the warning
  python/oneflow/nn/modules/constant.py
Labels: automerge, bug, op, graph

#9684 small change for alignment with pytorch
  python/oneflow/distributed/__init__.py
Labels: enhancement, automerge, python

#9705 Optimize RunLazyNNGraph var blobs
  oneflow/api/cpp/framework/graph.cpp
  oneflow/core/framework/nn_graph.cpp
  oneflow/core/framework/nn_graph.h
  python/oneflow/nn/graph/graph.py
Labels: enhancement, feature, graph

#9721 Auto expand dims for conv
  oneflow/core/functional/impl/common.cpp
  oneflow/core/functional/impl/common.h
  oneflow/core/functional/impl/nn_functor.cpp
  python/oneflow/test/modules/test_conv1d.py
  python/oneflow/test/modules/test_conv2d.py
Labels: enhancement, automerge, bug, eager, api

#9724 fix fused_matmul_bias_kernel compiled error in cuda11.0
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/user/kernels/fused_matmul_bias_kernel.cu
Labels: automerge, bug, build

#9713 Expand bits of stream index
  oneflow/api/python/session/session.cpp
  oneflow/core/device/device_id.h
  oneflow/core/graph/stream_id.h
  oneflow/core/profiler/event_recorder.cpp
  python/oneflow/framework/multi_client_session.py
  python/oneflow/framework/unittest.py
  python/oneflow/test/expensive/test_session_reset_stream_index_state.py
  python/oneflow/test/modules/test_fmod.py
  python/oneflow/test/modules/test_global_gru_cell.py
  python/oneflow/test/modules/test_global_lstm_cell.py
  python/oneflow/test/modules/test_global_rnn_cell.py
  python/oneflow/test/tensor/test_lazy_tensor_indexing.py
Labels: automerge, bug, graph

#9729 Disable CUDA_STATIC for cu11
  cmake/cuda.cmake
Labels: automerge, bug, build

#9725 refine cpu available mem size
  oneflow/core/common/util.cpp
Labels: enhancement, help wanted, automerge, system

#9633 Dev add linalg det
  cmake/cuda.cmake
  docs/source/linalg.rst
  oneflow/core/autograd/gradient_funcs/det.cpp
  oneflow/core/device/cuda_util.cpp
  oneflow/core/device/cuda_util.h
  oneflow/core/ep/cuda/cuda_stream.cpp
  oneflow/core/ep/cuda/cuda_stream.h
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/det_kernel.cpp
  oneflow/user/kernels/lu_decomposition_kernel.cu
  oneflow/user/ops/det_op.cpp
  oneflow/user/ops/lu_composition_op.cpp
  python/oneflow/__init__.py
  python/oneflow/linalg.py
  python/oneflow/test/modules/test_det.py
  python/oneflow/test/modules/test_global_det.py
  python/oneflow/test_utils/automated_test_util/generators.py
Labels: enhancement, automerge, op, test, api, python

#9679 Add oneflow.mode
  docs/source/oneflow.rst
  docs/source/tensor.rst
  oneflow/api/python/framework/tensor_functions.cpp
  oneflow/core/autograd/gradient_funcs/mode.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/mode_kernel.cpp
  oneflow/user/ops/mode_op.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/math_ops.py
  python/oneflow/framework/docstr/tensor.py
  python/oneflow/test/exceptions/test_mode.py
  python/oneflow/test/modules/test_mode.py
Labels: enhancement, feature, automerge, op, api, interface

#8553 profiler supports op attr
  cmake/oneflow.cmake
  cmake/op_schema.cmake
  external/fmt/CMakeLists.txt
  oneflow/core/common/stride.cpp
  oneflow/core/common/stride.h
  oneflow/core/common/util.h
  oneflow/core/framework/attr_map.cpp
  oneflow/core/framework/attr_map.h
  oneflow/core/framework/attr_value.h
  oneflow/core/profiler/event.cpp
  oneflow/core/profiler/event.h
  oneflow/core/profiler/event_recorder.cpp
  oneflow/core/profiler/event_recorder.h
  oneflow/core/profiler/profile_manager.h
  oneflow/core/profiler/profiler.cpp
  oneflow/core/profiler/profiler.h
  oneflow/core/vm/op_call_instruction_policy.h
  oneflow/user/kernels/stateful_opkernel.cpp
  python/oneflow/profiler/events.py
  python/oneflow/profiler/profiler.py
  python/oneflow/test/profiler/test_profile_lenet.py
Labels: enhancement, automerge, op

#9591 Tensor offload and load
  oneflow/api/python/env/env.cpp
  oneflow/api/python/framework/tensor.cpp
  oneflow/core/common/mem_util.cpp
  oneflow/core/common/mem_util.h
  oneflow/core/framework/tensor.cpp
  oneflow/core/framework/tensor.h
  python/oneflow/test/expensive/test_global_tensor_offload.py
  python/oneflow/test/expensive/test_tensor_offload.py
Labels: feature, automerge, eager, global

#9742 ddp supports use_bucket=False
  python/oneflow/nn/parallel/distributed.py
  python/oneflow/test/modules/test_ddp.py
Labels: automerge, bug, eager, python

#9744 Refine offload test
  python/oneflow/test/expensive/test_global_tensor_offload.py
  python/oneflow/test/expensive/test_tensor_offload.py
Labels: bug, ci

#9747 fix event_recorder.cpp clang-format
  oneflow/core/profiler/event_recorder.cpp
Labels: automerge, bug, build

#9745 DelayVariableOpExecutionPass
  oneflow/core/job/job_build_and_infer_ctx.cpp
  oneflow/core/job_rewriter/delay_variable_op_execution_pass.cpp
Labels: enhancement, automerge, system

#9691 Refactor random generator and distribution kernels
  oneflow/core/framework/random_generator_impl.cpp
  oneflow/core/framework/random_generator_impl.cu
  oneflow/core/framework/random_generator_impl.h
  oneflow/user/kernels/distributions/distribution_template_util.cuh
  oneflow/user/kernels/distributions/exponential_distribution.cu
  oneflow/user/kernels/distributions/multinomial_with_replacement_kernel.cu
  oneflow/user/kernels/distributions/normal_distribution.cu
  oneflow/user/kernels/distributions/uniform_distribution.cu
  oneflow/user/kernels/distributions/uniform_int_distribution.cu
  oneflow/user/kernels/dropout_kernel.cu
  oneflow/user/kernels/fused_matmul_bias_add_relu_dropout.cu
  oneflow/user/kernels/fused_rnn_cell_kernel_util.h
  oneflow/user/kernels/random_mask_generator.cu
  oneflow/user/kernels/randperm_kernel.cu
Labels: enhancement, automerge, system, refactor

#9694 add fake fx.Proxy for transformers
  python/oneflow/fx/__init__.py
Labels: enhancement, automerge, python

#9750 fix trt_flash_attention include
  cmake/third_party/trt_flash_attention.cmake
  oneflow/user/kernels/fused_multi_head_attention_inference_kernel.cu
Labels: automerge, bug, build

#9752 remove CHECK_JUST in TensorStorage destructor
  oneflow/core/framework/tensor_impl.cpp
Labels: automerge, bug, system

#9753 Modify offload ci test mode
  python/oneflow/test/expensive/test_global_tensor_offload.py
  python/oneflow/test/expensive/test_tensor_offload.py
Labels: automerge, bug, ci, test

#8777 cast kernel support stride
  oneflow/core/common/small_vector.h
  oneflow/core/common/stride.cpp
  oneflow/core/common/stride.h
  oneflow/core/common/tensor_meta.cpp
  oneflow/core/ep/common/primitive/broadcast_elementwise_unary.h
  oneflow/core/ep/common/primitive/unary_functor.h
  oneflow/core/ep/cpu/primitive/broadcast_elementwise_unary.cpp
  oneflow/core/ep/cuda/primitive/broadcast_elementwise_unary.cu
  oneflow/core/ep/cuda/primitive/unary_functor.cuh
  oneflow/core/ep/include/primitive/unary_op.h
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/cast_kernel.cpp
  python/oneflow/test/modules/test_cast.py
Labels: enhancement, op, refactor

#9740 deconv support auto squeeze and fix autotest bug
  oneflow/core/functional/impl/nn_functor.cpp
  python/oneflow/nn/modules/conv.py
  python/oneflow/test/modules/test_conv2d.py
  python/oneflow/test/modules/test_deconv2d.py
Labels: enhancement, automerge, bug, eager, api

#9733 Optimize actor performance
  oneflow/core/lazy/actor/actor.cpp
  oneflow/core/lazy/actor/actor.h
  oneflow/core/lazy/actor/actor_message.h
  oneflow/core/lazy/actor/actor_message_bus.cpp
  oneflow/core/lazy/actor/actor_message_bus.h
  oneflow/core/lazy/actor/light_actor.cpp
  oneflow/core/lazy/actor/register_slot.cpp
  oneflow/core/lazy/actor/register_slot.h
Labels: enhancement, automerge, system

#9697 float16 traits
  oneflow/api/python/functional/common.cpp
  oneflow/core/common/data_type.cpp
  oneflow/core/common/data_type.h
  oneflow/core/common/type_traits.h
  oneflow/core/framework/tensor_impl.cpp
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/core/vm/release_tensor_instruction_policy.h
  oneflow/user/kernels/collective_communication/cpu/cpu_broadcast.cpp
  oneflow/user/kernels/collective_communication/cpu/cpu_recv.cpp
  oneflow/user/kernels/collective_communication/cpu/cpu_send.cpp
  oneflow/user/kernels/distributions/common.h
  oneflow/user/kernels/empty_kernel.cpp
  oneflow/user/kernels/tensor_buffer_kernels.cpp
  oneflow/user/ops/tensor_buffer_ops.cpp
Labels: enhancement, automerge, system, api, need-all-tests-even-fail

#9748 Feat straighten delay short gpu
  oneflow/core/graph/straighten_nodes.cpp
  oneflow/core/graph/straighten_nodes.h
  oneflow/core/job/job_conf.proto
  python/oneflow/nn/graph/graph_config.py
Labels: enhancement, automerge, graph

#9730 add prune api match pytorch
  python/oneflow/nn/utils/__init__.py
  python/oneflow/nn/utils/convert_parameters.py
  python/oneflow/nn/utils/prune.py
  python/oneflow/test/modules/test_pruning.py
Labels: enhancement, automerge, python

#9760 add oneflow.cuda.get_rng_state and oneflow.cuda.get_rng_state_all api
  docs/source/cuda.rst
  python/oneflow/cuda/__init__.py
  python/oneflow/cuda/random.py
Labels: enhancement, automerge, bug, eager, api

#9700 enable stack getter by default if CMAKE_BUILD_TYPE is Debug
  cmake/oneflow.cmake
  cmake/util.cmake
  oneflow/core/common/env_var/debug_mode.h
  oneflow/core/common/error.cpp
Labels: enhancement, automerge, build

#8987 floor mode for div tensors finished
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/binary_functor.cpp
  oneflow/core/functional/impl/math_functor.cpp
  python/oneflow/framework/docstr/math_ops.py
  python/oneflow/test/modules/test_div.py
Labels: feature, automerge, op

#9608 fix: inplace greater
  docs/source/tensor.rst
  oneflow/api/python/framework/tensor_functions.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/binary_functor.cpp
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/greater_inplace_kernel.cpp
  oneflow/user/kernels/greater_inplace_kernel_util.cpp
  oneflow/user/kernels/greater_inplace_kernel_util.cu
  oneflow/user/kernels/greater_inplace_kernel_util.h
  oneflow/user/ops/greater_inplace_op.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/tensor.py
  python/oneflow/test/modules/test_greater.py
Labels: automerge, bug, op, documentation, need-clean-ccache

#9764 fix cuda12 compilation
  oneflow/core/ep/cuda/cuda_stream.cpp
  oneflow/core/ndarray/ndarray_reduce_impl.cu
  oneflow/user/kernels/arg_where_kernel_util.cu
  oneflow/user/kernels/cublas_fused_mlp_util.cuh
Labels: enhancement, automerge, bug, build

#9761 enable cuda graph support for Conv2dCutlassKernel
  oneflow/user/kernels/arange_kernel.cpp
  oneflow/user/kernels/clip_by_value_kernel.cpp
  oneflow/user/kernels/concat_kernel.cpp
  oneflow/user/kernels/conv_cutlass_kernels.cu
  oneflow/user/kernels/cutlass_conv_tuner.cpp
  oneflow/user/kernels/scalar_math_kernels.cpp
Labels: enhancement, automerge, op

#9765 Fix global mode docstr
  docs/source/utils.global_view.rst
  python/oneflow/utils/global_view/global_mode.py
Labels: automerge, documentation, build, api

#9667 flow.save saves data as a single file by default
  python/oneflow/framework/check_point_v2.py
  python/oneflow/test/graph/test_graph_save_load.py
  python/oneflow/test/graph/test_graph_save_load_global_b_s.py
  python/oneflow/test/modules/save_load_test_data/3x3_i3o3_conv2d/pickled_data
  python/oneflow/test/modules/save_load_test_data/3x3_i3o3_conv2d/tensor_3/meta
  python/oneflow/test/modules/save_load_test_data/3x3_i3o3_conv2d/tensor_3/out
  python/oneflow/test/modules/save_load_test_data/3x3_i3o3_conv2d/tensor_4/meta
  python/oneflow/test/modules/save_load_test_data/3x3_i3o3_conv2d/tensor_4/out
  python/oneflow/test/modules/save_load_test_data/3x3_i3o3_conv2d_params/pickled_data
  python/oneflow/test/modules/save_load_test_data/3x3_i3o3_conv2d_params/tensor_5/meta
  python/oneflow/test/modules/save_load_test_data/3x3_i3o3_conv2d_params/tensor_5/out
  python/oneflow/test/modules/save_load_test_data/3x3_i3o3_conv2d_params/tensor_6/meta
  python/oneflow/test/modules/save_load_test_data/3x3_i3o3_conv2d_params/tensor_6/out
  python/oneflow/test/modules/test_lr_scheduler.py
  python/oneflow/test/modules/test_module.py
  python/oneflow/test/modules/test_optim_adadelta.py
  python/oneflow/test/modules/test_optim_adagrad.py
  python/oneflow/test/modules/test_optim_adam.py
  python/oneflow/test/modules/test_optim_adamw.py
  python/oneflow/test/modules/test_optim_ftrl.py
  python/oneflow/test/modules/test_optim_lamb.py
  python/oneflow/test/modules/test_optim_rmsprop.py
  python/oneflow/test/modules/test_optim_sgd.py
  python/oneflow/test/modules/test_pruning.py
  python/oneflow/test/modules/test_save_load.py
  python/oneflow/test_utils/oneflow_pytorch_compatibility/oneflow_pytorch_compatiblity_test.py
  tools/check_src.py
Labels: feature, automerge, python

#9774 Hotfix SimplifyBroadcastDims
  oneflow/core/ep/common/primitive/util.h
Labels: automerge, bug, op, primitive

#9673 Refactor where
  oneflow/core/autograd/gradient_funcs/where.cpp
  oneflow/core/common/data_type.h
  oneflow/core/common/data_type_seq.h
  oneflow/core/ep/common/primitive/where.h
  oneflow/core/ep/cpu/primitive/where.cpp
  oneflow/core/ep/cuda/primitive/where.cu
  oneflow/core/ep/include/primitive/where.h
  oneflow/core/ep/test/primitive/where_test.cpp
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/core/job_rewriter/auto_mixed_precision_lists.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/where_kernel.cpp
  oneflow/user/ops/where_op.cpp
Labels: automerge, bug, op

#9780 Improve where cuda performance
  oneflow/core/ep/cuda/primitive/where.cu
Labels: enhancement, automerge, op, primitive

#9776 fix fill_ infer dtype bug in autocast
  oneflow/core/job_rewriter/auto_mixed_precision_lists.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  python/oneflow/test/modules/test_cast.py
  python/oneflow/test/tensor/test_tensor_part_1.py
Labels: enhancement, automerge, bug, eager, api

#9770 Fix graph repr placement bug
  python/oneflow/nn/graph/util.py
Labels: automerge, bug, graph

#9785 HobEnvBool
  oneflow/core/framework/user_op_hob.h
  oneflow/core/job_rewriter/cutlass_conv_tuning_warmup_pass.cpp
  oneflow/user/kernels/conv_cutlass_kernels.cu
  oneflow/user/kernels/fused_glu_kernel.cu
  oneflow/user/kernels/fused_multi_head_attention_inference_kernel.cu
Labels: enhancement, automerge, bug, op

#9762 Remove ActorMsg::user_data_
  oneflow/core/comm_network/ibverbs/ibverbs_comm_network.cpp
  oneflow/core/comm_network/ibverbs/ibverbs_comm_network.h
  oneflow/core/comm_network/ibverbs/ibverbs_qp.cpp
  oneflow/core/comm_network/ibverbs/ibverbs_qp.h
  oneflow/core/lazy/actor/actor_message.cpp
  oneflow/core/lazy/actor/actor_message.h
Labels: enhancement, automerge, system

#9782 Fix EagerBlobObject::ByteSizeOfBlobBody
  oneflow/core/eager/eager_blob_object.h
Labels: automerge, bug, eager

#9788 set CUDA_NVCC_THREADS_NUMBER to 2
  cmake/caches/ci/release/cuda.cmake
Labels: automerge, bug, build

#9781 add swa_utils modules
  python/oneflow/nn/modules/batchnorm.py
  python/oneflow/nn/optimizer/multiplicative_lr.py
  python/oneflow/nn/optimizer/swa_utils.py
  python/oneflow/optim/__init__.py
  python/oneflow/optim/lr_scheduler.py
  python/oneflow/profiler/__init__.py
  python/oneflow/test/modules/test_swautils.py
Labels: enhancement, automerge, python

#9797 fix not_equal dont support None in codegeex
  oneflow/api/python/framework/tensor_functions.cpp
  python/oneflow/test/modules/test_ne.py
Labels: enhancement, automerge, bug, eager, api

#9792 fix gcc 11 compilation
  cmake/third_party/absl.cmake
Labels: enhancement, automerge, build

#9801 delete wrong check in inverse op
  oneflow/api/python/framework/tensor_functions.cpp
  python/oneflow/test/modules/test_logical_and.py
Labels: enhancement, automerge, bug, eager, api

#9800 add oneflow.clone api
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/array_functor.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/array_ops.py
  python/oneflow/framework/docstr/tensor.py
  python/oneflow/test/modules/test_clone.py
Labels: enhancement, automerge, test, documentation, api, python

#9737 add check for input/output size for upsample ops
  oneflow/user/ops/upsample_op.cpp
Labels: enhancement, automerge, op, api

#9526 Add fused glu grad
  oneflow/core/autograd/gradient_funcs/fused_glu.cpp
  oneflow/core/ep/common/primitive/binary_functor.h
  oneflow/core/ep/common/primitive/broadcast_elementwise_binary.h
  oneflow/core/ep/cuda/primitive/binary_functor.cuh
  oneflow/core/ep/include/primitive/binary_op.h
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/core/functional/impl/nn_grad_functor.cpp
  oneflow/core/job_rewriter/auto_mixed_precision_lists.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/fused_glu_kernel.cu
  oneflow/user/kernels/fused_glu_without_linear_grad_kernel.cu
  oneflow/user/ops/fused_glu_op.cpp
  oneflow/user/ops/fused_glu_without_linear_grad_op.cpp
  python/oneflow/test/modules/test_fused_glu.py
Labels: feature, automerge, op

#9802 fix gcc 12 compilation
  cmake/third_party/opencv.cmake
Labels: automerge, bug, build

#9809 add auto_backward='auto' in autotest
  python/oneflow/test/modules/test_global_det.py
  python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py
Labels: enhancement, automerge, test, python

#9808 Fix dropout functor error
  oneflow/core/functional/impl/nn_functor.cpp
  python/oneflow/test/modules/test_dropout.py
Labels: enhancement, automerge, system
