Repository Oneflow-Inc/oneflow, pull requests merged in 2023-10, with the labels that each got.

#10335 Feat graph load to new device
  oneflow/core/graph/stream_id.cpp
  oneflow/core/graph/task_id.cpp
  python/oneflow/nn/graph/cache.py
  python/oneflow/nn/graph/graph.py
  python/oneflow/nn/graph/util.py
  python/oneflow/test/expensive/test_graph_multi_graph_v2.py
Labels: feature, automerge, graph

#10343 set default cpg to None
  python/oneflow/nn/modules/module.py
Labels: automerge, bug, eager

#10348 Add cu12 release
  .github/workflows/canary.yml
  .github/workflows/on_merge.yml
  .github/workflows/priv_release.yml
  .github/workflows/release.yml
  .github/workflows/simple.yml
  .github/workflows/test.yml
  README.md
Labels: enhancement, ci

#10349 Fix typo in release workflow
  .github/workflows/release.yml
Labels: bug, ci
