Repository Oneflow-Inc/oneflow, pull requests merged in 2023-06, with the labels that each got.

#10141 Plan rank compiler
  oneflow/core/graph/graph.h
  oneflow/core/graph/op_graph.cpp
  oneflow/core/graph/op_graph.h
  oneflow/core/graph/task_graph.cpp
  oneflow/core/graph/task_graph.h
  oneflow/core/graph/task_node.cpp
  oneflow/core/graph/task_node.h
  oneflow/core/job/compiler.cpp
  oneflow/core/job/parallel_desc.cpp
  oneflow/core/job/parallel_desc.h
  oneflow/core/job/plan_util.cpp
  oneflow/core/job/plan_util.h
  oneflow/core/job/rank_compiler.cpp
  oneflow/core/job/rank_compiler.h
  oneflow/core/operator/op_conf.proto
Labels: feature, automerge, graph

#10281 use primitive to implement "conj_physical", "real" and "imag" op
  oneflow/core/ep/common/primitive/elementwise_unary.h
  oneflow/core/ep/common/primitive/unary_functor.h
  oneflow/core/ep/cpu/primitive/elementwise_unary.cpp
  oneflow/core/ep/cpu/primitive/unary_functor.h
  oneflow/core/ep/cuda/primitive/elementwise_unary.cu
  oneflow/core/ep/cuda/primitive/unary_functor.cuh
  oneflow/core/ep/include/primitive/unary_op.h
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/user/kernels/complex_kernels.cpp
  oneflow/user/kernels/complex_kernels_util.cpp
  oneflow/user/kernels/complex_kernels_util.cu
  oneflow/user/kernels/complex_kernels_util.h
Labels: feature, automerge, op

#10048 Global Interpreter
  oneflow/core/job/job_interpreter.cpp
  python/oneflow/nn/graph/graph.py
  python/oneflow/test/graph/test_run_global_graph_by_vm.py
  python/oneflow/test/graph/test_run_graph_by_vm.py
Labels: feature, automerge, graph

#9920 Plan separation compile
  oneflow/core/common/env_var/env_var.h
  oneflow/core/framework/nn_graph.cpp
  oneflow/core/framework/nn_graph.h
  oneflow/core/graph/boxing/hierarchical_sub_task_graph_builder_impl.cpp
  oneflow/core/graph/compute_task_node.h
  oneflow/core/graph/copy_task_node.cpp
  oneflow/core/graph/exec_graph.cpp
  oneflow/core/graph/plan_task_graph.cpp
  oneflow/core/graph/plan_task_graph.h
  oneflow/core/graph/slice_boxing_task_node.cpp
  oneflow/core/graph/task_id_generator.cpp
  oneflow/core/graph/task_id_generator.h
  oneflow/core/graph/task_stream_index_manager.h
  oneflow/core/job/compile_mode.cpp
  oneflow/core/job/compile_mode.h
  oneflow/core/job/id_manager.cpp
  oneflow/core/job/id_manager.h
  oneflow/core/job/intra_job_mem_sharing_util.cpp
  oneflow/core/job/job_conf.proto
  oneflow/core/job/plan_util.cpp
  oneflow/core/job/plan_util.h
  oneflow/core/memory/chunk_manager.cpp
  oneflow/core/memory/chunk_manager.h
  oneflow/core/operator/collective_boxing_pack_op.cpp
  oneflow/core/operator/op_attribute.proto
  oneflow/core/operator/operator.cpp
  oneflow/core/register/register_desc.h
  oneflow/core/register/register_desc.proto
  oneflow/core/rpc/include/global_process_ctx.h
  oneflow/core/rpc/lib/global_process_ctx.cpp
  python/oneflow/nn/graph/graph.py
  python/oneflow/test/graph/test_alexnet_auto_parallel.py
  python/oneflow/test/graph/test_fx_fuse.py
  python/oneflow/test/graph/test_fx_replace_ops.py
  python/oneflow/test/graph/test_fx_symbolic_trace_module.py
  python/oneflow/test/graph/test_graph_pipeline.py
  python/oneflow/test/graph/test_graph_separate_compile.py
Labels: enhancement, bottleneck, system, graph

#10295 fix ci error
  .github/workflows/test.yml
  python/oneflow/test/modules/test_global_higher_derivative_pool.py
Labels: automerge, bug, ci

#10265 Lbfgs
  docs/source/optim.rst
  python/oneflow/nn/optimizer/lbfgs.py
  python/oneflow/test/modules/test_higher_derivative_pool.py
  python/oneflow/test/modules/test_optim_lbfgs.py
Labels: feature, automerge, op

#10284 Applying autotest module on existing complex operators
  oneflow/core/autograd/gradient_funcs/broadcast_binary_ops.cpp
  oneflow/core/framework/dtype.cpp
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/core/functional/tensor_processor.cpp
  oneflow/user/kernels/reduce_like_kernels.cpp
  python/oneflow/test/modules/test_add.py
  python/oneflow/test/modules/test_cast.py
  python/oneflow/test/modules/test_constant_pad.py
  python/oneflow/test/modules/test_equal.py
  python/oneflow/test/modules/test_mul.py
  python/oneflow/test/modules/test_sub.py
  python/oneflow/test/modules/test_sum.py
  python/oneflow/test/tensor/test_complex.py
  python/oneflow/test_utils/automated_test_util/generators.py
  python/oneflow/test_utils/test_util.py
Labels: feature, automerge, op

#10269 add mm, sqrt, div operators for complex tensor to support OneScience
  oneflow/core/autograd/gradient_funcs/broadcast_binary_ops.cpp
  oneflow/core/autograd/gradient_funcs/matrix_vector_product.cpp
  oneflow/core/common/blas.h
  oneflow/core/ep/common/primitive/broadcast_elementwise_binary.h
  oneflow/core/ep/common/primitive/broadcast_matmul.h
  oneflow/core/ep/common/primitive/elementwise_unary.h
  oneflow/core/ep/cpu/primitive/binary_functor.h
  oneflow/core/ep/cpu/primitive/broadcast_elementwise_binary.cpp
  oneflow/core/ep/cpu/primitive/broadcast_matmul.cpp
  oneflow/core/ep/cuda/primitive/binary_functor.cuh
  oneflow/core/ep/cuda/primitive/broadcast_elementwise_binary.cu
  oneflow/core/ep/cuda/primitive/broadcast_matmul.cpp
  oneflow/core/ep/cuda/primitive/math_elementwise_unary_math_grad_complex.cu
  oneflow/core/ep/cuda/primitive/unary_functor.cuh
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/user/kernels/broadcast_div_grad_kernel.cpp
  python/oneflow/test/modules/test_add.py
  python/oneflow/test/modules/test_constant_pad.py
  python/oneflow/test/modules/test_div.py
  python/oneflow/test/modules/test_global_tile.py
  python/oneflow/test/modules/test_math_ops.py
  python/oneflow/test/modules/test_matmul.py
  python/oneflow/test/modules/test_mul.py
  python/oneflow/test/modules/test_sub.py
  python/oneflow/test/modules/test_sum.py
  python/oneflow/test/tensor/test_complex.py
  python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py
Labels: feature, automerge, op
