Repository Oneflow-Inc/oneflow, pull requests merged in 2023-05, with the labels that each got.

#10188 [feat]: Update highorder autograd rules for tanh
  oneflow/core/autograd/gradient_funcs/math_unary_op.cpp
  oneflow/core/autograd/higher_order_gradient_funcs/math_unary_op.cpp
  oneflow/core/ep/common/primitive/broadcast_elementwise_binary.h
  oneflow/core/ep/cpu/primitive/binary_functor.h
  oneflow/core/ep/cuda/primitive/binary_functor.cuh
  oneflow/core/ep/include/primitive/binary_op.h
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/higher_derivative_functor.cpp
  oneflow/core/functional/impl/unary_functor.cpp
  oneflow/extension/stack/stacktrace.h
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/activation_kernels.cpp
Labels: feature, ci, eager, op

#10225 add cpu nms kernel
  oneflow/user/kernels/nms_kernel.cpp
  python/oneflow/test/modules/test_nms.py
Labels: enhancement, automerge, bug, eager, api

#10223 add extra_libs functionality
  python/oneflow/mock_torch/__init__.py
  python/oneflow/test/misc/test_mock_scope.py
Labels: feature, automerge, python

#10166 Refactor to better support more devices
  oneflow/core/device/cuda_util.cpp
  oneflow/core/device/device_context.h
  oneflow/core/eager/call_context.h
  oneflow/core/eager/eager_blob_object.h
  oneflow/core/ep/cpu/cpu_device.h
  oneflow/core/ep/cuda/cuda_device.cpp
  oneflow/core/ep/cuda/cuda_device.h
  oneflow/core/ep/cuda/cuda_device_manager.h
  oneflow/core/ep/cuda/cuda_stream.cpp
  oneflow/core/ep/cuda/cuda_stream.h
  oneflow/core/ep/include/device.h
  oneflow/core/ep/include/device_manager.h
  oneflow/core/ep/include/stream.h
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/framework/stream.cpp
  oneflow/core/framework/stream.h
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/core/kernel/kernel_context.h
  oneflow/core/register/blob.h
  oneflow/core/vm/ep_backend_allocator.cpp
  oneflow/core/vm/ep_optional_event_record_status_querier.h
  oneflow/core/vm/stream.h
  oneflow/core/vm/stream_wait_event_instruction_policy.cpp
  oneflow/core/vm/stream_wait_instruction_policy.cpp
Labels: enhancement, automerge, system, refactor, need-clean-ccache

#10177 lgamma backward
  oneflow/core/ep/common/primitive/binary_functor.h
  oneflow/core/ep/cpu/primitive/binary_functor.h
  oneflow/core/ep/cuda/primitive/binary_functor.cuh
  python/oneflow/test/modules/test_math_ops.py
Labels: automerge, bug, op, api, refactor, primitive

#10226 fix GetItemInScalarTensor dtype bug
  oneflow/core/framework/tensor_util.h
  oneflow/core/functional/tensor_index.cpp
  python/oneflow/framework/tensor.py
  python/oneflow/test/modules/test_slice.py
Labels: enhancement, automerge, bug, eager, api

#10224 [CodeGen]update llvm2023.0504x for new features in transform dialect
  .github/workflows/test.yml
  cmake/oneflow.cmake
  oneflow/ir/include/OneFlow/CMakeLists.txt
  oneflow/ir/include/OneFlow/OKL/Kernel/LauncherState.h
  oneflow/ir/lib/OneFlow/CMakeLists.txt
  oneflow/ir/lib/OneFlow/Conversion/NVVMToCubin.cpp
  oneflow/ir/lib/OneFlow/Conversion/OneFlowToTosa.cpp
  oneflow/ir/lib/OneFlow/OneFlowInferReturnTypes.cpp
  oneflow/ir/lib/OneFlow/OneFlowOpFolders.cpp
  oneflow/ir/lib/OneFlow/PDLL/ForwardOpPatterns.pdll
  oneflow/ir/lib/OneFlow/PDLL/FuseOpsWithBackwardImplPattern.pdll
  oneflow/ir/lib/OneFlow/PDLL/NormalizationPatterns.pdll
  oneflow/ir/lib/OneFlow/Passes.cpp
  oneflow/ir/lib/OneFlow/Transform/OneFlowStream.cpp
  oneflow/ir/oneflow-extension/lr_jit.cpp
  oneflow/ir/oneflow-extension/mlir_jit_op_kernel.cpp
  oneflow/ir/oneflow-opt/oneflow-opt.cpp
  oneflow/ir/test/Frontend/test_tosa_to_elf.mlir
  oneflow/ir/test/OneFlow/conversion/OneFlowToTosa.mlir
  oneflow/ir/test/OneFlow/cuda_code_gen/test_append_oneflow_stream.mlir
Labels: feature, need-all-tests-even-fail, ir

#10118 bugfix: nccl logical stream over max cnt
  oneflow/core/job_rewriter/insert_nccl_logical_op_pass.cpp
  python/oneflow/test/graph/test_comb1to2d.py
  python/oneflow/test/graph/test_comb2d.py
  python/oneflow/test/graph/test_graph_nccl_logical_fusion.py
  python/oneflow/test/graph/test_nccl_logical_send_recv.py
Labels: automerge, bug, graph

#10228 conv module support device and dtype flag
  oneflow/core/functional/impl/array_functor.cpp
  python/oneflow/nn/modules/conv.py
  python/oneflow/test/modules/test_conv2d.py
Labels: enhancement, automerge, bug, eager, api

#10227 [CodeGen]Support Transform Dialect in MLIR For Future Optimization Work
  oneflow/ir/include/CMakeLists.txt
  oneflow/ir/include/Transform/CMakeLists.txt
  oneflow/ir/include/Transform/TestTransformDialectExtension.h
  oneflow/ir/include/Transform/TestTransformDialectExtension.td
  oneflow/ir/include/Transform/TestTransformStateExtension.h
  oneflow/ir/lib/CMakeLists.txt
  oneflow/ir/lib/Transform/CMakeLists.txt
  oneflow/ir/lib/Transform/TestTransformDialectExtension.cpp
  oneflow/ir/lib/Transform/TestTransformDialectInterpreter.cpp
  oneflow/ir/lib/Transform/TestTransformStateExtension.cpp
  oneflow/ir/oneflow-opt/CMakeLists.txt
  oneflow/ir/oneflow-opt/oneflow-opt.cpp
  oneflow/ir/test/Transform/softmax-trait.mlir
  oneflow/ir/test/Transform/softmax.mlir
  oneflow/ir/test/Transform/test-dialect.mlir
Labels: feature, ir

#10140 Add consume fake regst
  oneflow/core/graph/compute_task_node.cpp
  oneflow/core/graph/compute_task_node.h
  oneflow/core/graph/fake_consumed_regst_provider.h
  oneflow/core/graph/normal_forward_compute_task_node.h
  oneflow/core/graph/task_node.cpp
  oneflow/core/graph/task_node.h
  oneflow/core/graph_impl/acc_compute_task_node.cpp
  oneflow/core/graph_impl/acc_ctrl_tick_compute_task_node.cpp
  oneflow/core/graph_impl/acc_tick_compute_task_node.cpp
  oneflow/core/graph_impl/callback_notify_compute_task_node.cpp
  oneflow/core/graph_impl/case_compute_task_node.cpp
  oneflow/core/graph_impl/critical_section_wait_compute_task_node.cpp
  oneflow/core/graph_impl/decode_h2d_compute_task_node.cpp
  oneflow/core/graph_impl/device_tick_compute_task_node.cpp
  oneflow/core/graph_impl/distribute_concat_compute_task_node.cpp
  oneflow/core/graph_impl/distribute_split_compute_task_node.cpp
  oneflow/core/graph_impl/dst_subset_tick_compute_task_node.cpp
  oneflow/core/graph_impl/esac_compute_task_node.cpp
  oneflow/core/graph_impl/normal_forward_compute_task_node.cpp
  oneflow/core/graph_impl/pack_compute_task_node.cpp
  oneflow/core/graph_impl/reentrant_lock_compute_task_node.cpp
  oneflow/core/graph_impl/repeat_compute_task_node.cpp
  oneflow/core/graph_impl/source_tick_compute_task_node.cpp
  oneflow/core/graph_impl/src_subset_tick_compute_task_node.cpp
  oneflow/core/graph_impl/ssp_variable_proxy_task_node.cpp
  oneflow/core/graph_impl/tick_compute_task_node.cpp
  oneflow/core/graph_impl/unpack_compute_task_node.cpp
  oneflow/core/graph_impl/wait_and_send_ids_compute_task_node.cpp
  oneflow/core/register/register_desc.cpp
  oneflow/core/register/register_desc.h
Labels: feature, automerge, graph

#10082 refactor_collective_boxing_executor_backend
  oneflow/core/graph/boxing/ccl_sub_task_graph_builder.cpp
  oneflow/core/graph/boxing/ccl_sub_task_graph_builder.h
  oneflow/core/graph/boxing/collective_boxing.proto
  oneflow/core/graph/boxing/collective_boxing_sub_task_graph_builder.cpp
  oneflow/core/graph/boxing/hierarchical_sub_task_graph_builder_impl.cpp
  oneflow/core/graph/boxing/hierarchical_sub_task_graph_builder_util.cpp
  oneflow/core/graph/boxing/hierarchical_sub_task_graph_builder_util.h
  oneflow/core/graph/boxing/sub_task_graph_builder_util.cpp
  oneflow/core/graph/boxing/sub_task_graph_builder_util.h
  oneflow/core/graph/task_graph.cpp
  oneflow/core/graph/task_graph.h
  oneflow/core/job/collective_boxing/executor_backend_manager.cpp
  oneflow/core/job/collective_boxing/executor_backend_manager.h
  oneflow/core/job/collective_boxing/nccl_executor_backend.cu
  oneflow/core/job/collective_boxing/nccl_executor_backend.h
  oneflow/core/job/collective_boxing/scheduler.cpp
Labels: enhancement, automerge, system, refactor

#10236 Fix build error with gcc 12 for oneTBB
  external/onetbb/CMakeLists.txt
Labels: automerge, bug, build

#10233 handle zipimporter in mock with extra_libs
  python/oneflow/mock_torch/__init__.py
Labels: enhancement, automerge, bug, eager, api

#10185 Develop_OneFlow_Normal_Distribution_Synced_With_PyTorch_Tensor
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/common.cpp
  oneflow/core/functional/impl/common.h
  oneflow/core/functional/impl/random_functor.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/random.py
  python/oneflow/test/modules/test_normal.py
Labels: feature, ci, eager, op, documentation, api, ir

#10218 add warmup inside load state dict
  python/oneflow/nn/graph/cache.py
  python/oneflow/nn/graph/graph.py
Labels: automerge, bug, python

#10238 fuse bn_add_relu and bn_relu for inference
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/ir/lib/OneFlow/PDLL/NormalizationPatterns.pdll
  oneflow/ir/lib/OneFlow/UserOpConversion.cpp
  oneflow/user/kernels/normalization_kernel.cu
  oneflow/user/ops/normalization_op.cpp
Labels: enhancement, automerge, system

#10232 [CodeGen]Support OneShotBufferize in MLIR CodeGen
  oneflow/ir/lib/OneFlow/Passes.cpp
  oneflow/ir/lib/OneFlow/Transform/JITPasses.cpp
  oneflow/ir/oneflow-opt/oneflow-opt.cpp
Labels: feature, automerge, ir

#10230 Nccl use compute stream
  oneflow/core/common/env_var/eager.h
  oneflow/user/ops/comm_net_device_infer_util.h
Labels: enhancement, eager, global

#9973 Fix default generator
  oneflow/api/python/framework/random_generator.cpp
  oneflow/core/device/cuda_util.cpp
  python/oneflow/cuda/__init__.py
  python/oneflow/test/modules/test_generator.py
Labels: enhancement, bug, eager, documentation, api, need-clean-ccache

#10251 Autograd.grad support allow_unused argument
  oneflow/api/python/autograd/autograd.cpp
  oneflow/core/autograd/autograd_engine.cpp
  oneflow/core/autograd/autograd_engine.h
  python/oneflow/autograd/autograd.py
  python/oneflow/test/exceptions/test_autograd.py
  python/oneflow/test/modules/test_autograd.py
Labels: enhancement, automerge, test

#10237 [fix]: fix tanh grad grad, add the third derivative test
  oneflow/core/autograd/higher_order_gradient_funcs/math_unary_op.cpp
Labels: enhancement, automerge, ci, eager, op

#10255 [CodeGen] Support transform.oneflow.apply_patterns Op in MLIR
  oneflow/ir/include/Transform/CMakeLists.txt
  oneflow/ir/include/Transform/TestTransformDialectExtension.h
  oneflow/ir/include/Transform/TestTransformDialectExtension.td
  oneflow/ir/include/Transform/TestTransformStateExtension.h
  oneflow/ir/include/Transform/TransformDialectExtension.h
  oneflow/ir/include/Transform/TransformDialectExtension.td
  oneflow/ir/include/Transform/TransformStateExtension.h
  oneflow/ir/lib/Transform/CMakeLists.txt
  oneflow/ir/lib/Transform/TestTransformDialectExtension.cpp
  oneflow/ir/lib/Transform/TransformDialectExtension.cpp
  oneflow/ir/lib/Transform/TransformDialectInterpreter.cpp
  oneflow/ir/lib/Transform/TransformStateExtension.cpp
  oneflow/ir/oneflow-opt/CMakeLists.txt
  oneflow/ir/oneflow-opt/oneflow-opt.cpp
  oneflow/ir/test/Transform/apply-patterns.mlir
  oneflow/ir/test/Transform/softmax.mlir
  oneflow/ir/test/Transform/test-dialect.mlir
Labels: feature, automerge, ir

#10234 [CodeGen]Support Basic Shlib Relative Path in MLIR Runner Test
  oneflow/ir/test/OneFlow/cuda_code_gen/test_gpu_all_reduce.mlir
  oneflow/ir/test/lit.cfg.py
  oneflow/ir/test/lit.site.cfg.py.in
Labels: feature, automerge, ir

#10261 [CodeGen] Update LLVM Version For The Newest Transform Tiling and Mapping Support
  cmake/oneflow.cmake
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
Labels: feature, automerge, ir

#10262 fix BldSubTskGphByBoxing
  oneflow/core/common/singleton.h
  oneflow/core/common/singleton_ptr.h
  oneflow/core/framework/instructions_builder.cpp
  oneflow/core/graph/task_graph.cpp
  oneflow/core/job/env_global_objects_scope.cpp
  oneflow/core/vm/release_tensor_instruction_policy.h
  oneflow/core/vm/virtual_machine.cpp
  oneflow/core/vm/virtual_machine_engine.cpp
Labels: automerge, bug, system, graph

#9988 modify ParamGroup
  python/oneflow/optim/optimizer.py
  python/oneflow/test/modules/test_param_group.py
Labels: enhancement, automerge, op, python

#10260 remove prefix of project_source_dir in stacktrace filepath
  cmake/oneflow.cmake
  oneflow/core/common/error.h
Labels: enhancement, automerge, system

#10065 Create new shared graph after loading
  oneflow/api/python/framework/id_state.cpp
  oneflow/core/device/device_id.cpp
  oneflow/core/device/device_id.h
  oneflow/core/framework/multi_client_session_context.cpp
  oneflow/core/framework/multi_client_session_context.h
  oneflow/core/graph/stream_index_generator.cpp
  oneflow/core/graph/stream_index_generator.h
  oneflow/core/graph/task_id_generator.cpp
  oneflow/core/graph/task_id_generator.h
  oneflow/core/graph/task_stream_index_manager.cpp
  oneflow/core/graph/task_stream_index_manager.h
  oneflow/core/job/id_manager.cpp
  oneflow/core/job/id_manager.h
  oneflow/core/job/id_state.h
  oneflow/core/job/job_build_and_infer_ctx_mgr.cpp
  oneflow/core/job/job_build_and_infer_ctx_mgr.h
  oneflow/core/register/register_manager.cpp
  python/oneflow/nn/graph/graph.py
  python/oneflow/test/expensive/test_graph_multi_graph_v2.py
Labels: feature, automerge, graph

#9786 fix contiguous paramter buffer conflict
  oneflow/api/python/framework/tensor.cpp
  oneflow/core/framework/tensor.cpp
  oneflow/core/framework/tensor.h
  python/oneflow/nn/modules/module.py
  python/oneflow/nn/optimizer/sgd.py
  python/oneflow/nn/parallel/distributed.py
  python/oneflow/nn/utils/__init__.py
  python/oneflow/nn/utils/parameters_grouping.py
  python/oneflow/optim/optimizer.py
  python/oneflow/test/modules/test_optim_rmsprop.py
  python/oneflow/test/modules/test_parameters_grouping.py
  python/oneflow/test/tensor/test_tensor_part_1.py
Labels: feature, bug, eager, system, python

#10263 [CodeGen]Manage The Process From Linalg to Gpu in Softmax with Transform Dialect
  oneflow/ir/include/Transform/TransformDialectExtension.h
  oneflow/ir/include/Transform/TransformDialectExtension.td
  oneflow/ir/lib/Transform/TransformDialectExtension.cpp
  oneflow/ir/test/Frontend/oneflow_to_iree.mlir
  oneflow/ir/test/Frontend/tosa_to_elf.mlir
  oneflow/ir/test/GPU/nvvm_to_cubin.mlir
  oneflow/ir/test/OneFlow/conversion/lower_to_tosa.mlir
  oneflow/ir/test/OneFlow/conversion/lower_to_tosa_signed.mlir
  oneflow/ir/test/OneFlow/conversion/oneflow_to_tosa.mlir
  oneflow/ir/test/OneFlow/fuse/fuse_forward_ops.mlir
  oneflow/ir/test/OneFlow/fuse/test_cast_optimal_pass.py
  oneflow/ir/test/OneFlow/fuse/test_fuse_pad_conv.py
  oneflow/ir/test/OneFlow/jit_outline_func.mlir
  oneflow/ir/test/OneFlow/kernel_launch/OKLPass/lower_launcher_to_llvm_ptr.mlir
  oneflow/ir/test/OneFlow/kernel_launch/OKLPass/lower_okl_to_llvm_call.mlir
  oneflow/ir/test/OneFlow/kernel_launch/OKLPass/tag_cuda_graph_support.mlir
  oneflow/ir/test/OneFlow/kernel_launch/OKMPass/extract_okm_tensor.mlir
  oneflow/ir/test/OneFlow/kernel_launch/OKMPass/okm_to_okl.mlir
  oneflow/ir/test/OneFlow/kernel_launch/OKMPass/opt_okm_memref.mlir
  oneflow/ir/test/OneFlow/kernel_launch/OKMPass/wrap_okm_kernel.mlir
  oneflow/ir/test/OneFlow/kernel_launch/OneFlowPass/aggregate_compute_ops.mlir
  oneflow/ir/test/OneFlow/kernel_launch/OneFlowPass/wrap_ops_to_kernel_launch/cuda_graph.mlir
  oneflow/ir/test/OneFlow/kernel_launch/OneFlowPass/wrap_ops_to_kernel_launch/lit.local.cfg
  oneflow/ir/test/OneFlow/kernel_launch/OneFlowPass/wrap_ops_to_kernel_launch/simple.mlir
  oneflow/ir/test/Transform/apply_patterns.mlir
  oneflow/ir/test/Transform/softmax-trait.mlir
  oneflow/ir/test/Transform/softmax.mlir
  oneflow/ir/test/Transform/softmax_codegen_spec.mlir
  oneflow/ir/test/Transform/test_dialect.mlir
Labels: feature, automerge, ir

#10271 Replace dummy array initialization with fold expression
  oneflow/api/python/functional/python_arg_parser.h
  oneflow/core/common/hash.h
  oneflow/core/common/just.h
  oneflow/core/common/meta_util.hpp
  oneflow/core/framework/mutable_attr_map.h
  oneflow/core/functional/function_library.h
  oneflow/maybe/error.h
Labels: enhancement, automerge, system

#10027 Add FFT operators
  oneflow/core/autograd/gradient_funcs/fft.cpp
  oneflow/core/device/cuda_util.cpp
  oneflow/core/device/cuda_util.h
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/cufft_plan_cache.h
  oneflow/user/kernels/fft_kernel_util.cpp
  oneflow/user/kernels/fft_kernel_util.cu
  oneflow/user/kernels/fft_kernel_util.h
  oneflow/user/kernels/fft_kernels.cpp
  oneflow/user/kernels/pocketfftplan.h
  oneflow/user/kernels/stft_kernel.cpp
  oneflow/user/kernels/stft_kernel.cu
  oneflow/user/kernels/to_contiguous_kernel.h
  oneflow/user/ops/fft_ops.cpp
  python/oneflow/__init__.py
  python/oneflow/fft/__init__.py
  python/oneflow/test/exceptions/test_stft_op.py
  python/oneflow/test/modules/test_fft.py
  python/oneflow/test_utils/automated_test_util/generators.py
  python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py
Labels: feature, automerge, op

#10272 [CodeGen]Support Softmax Codegen v2
  oneflow/ir/include/OneFlow/OneFlowPasses.td
  oneflow/ir/include/OneFlow/Transform/OneFlowMemPool.h
  oneflow/ir/include/Transform/TransformDialectExtension.td
  oneflow/ir/lib/OneFlow/Transform/OneFlowMemPool.cpp
  oneflow/ir/lib/Transform/TransformDialectExtension.cpp
  oneflow/ir/test/Transform/apply_patterns.mlir
  oneflow/ir/test/Transform/softmax.mlir
  oneflow/ir/test/Transform/softmax_codegen_spec.mlir
Labels: feature, ir, codegen

#10275 force load mlir static libs
  cmake/oneflow.cmake
  cmake/util.cmake
  oneflow/core/framework/attr_value.h
  oneflow/core/framework/attr_value_accessor.cpp
  oneflow/core/framework/user_op_attr.proto
  oneflow/ir/include/OneFlow/OneFlowBase.td
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/ir/lib/OneFlow/OKL/Kernel/JITOpInfer.cpp
  oneflow/ir/lib/OneFlow/OKL/Kernel/LauncherState.cpp
  oneflow/ir/lib/OneFlow/OKL/Kernel/TmpBufferManager.cpp
  oneflow/ir/lib/OneFlow/UserOpConversion.cpp
  oneflow/ir/oneflow-extension/mlir_jit_op_kernel.cpp
  tools/oneflow-tblgen/op_schema_types.inc
Labels: enhancement, automerge, build, system, need-clean-ccache

#10282 fix add FoldAllocToSubviewPass
  oneflow/ir/lib/OneFlow/Passes.cpp
Labels: automerge, bug, system, need-clean-ccache, codegen

#10279 fix at double attr
  oneflow/core/framework/nn_graph.cpp
  oneflow/core/job_rewriter/job_completer.cpp
Labels: automerge, bug, graph

#9986 support noncontiguous binary op
  oneflow/core/autograd/gradient_funcs/noncontiguous_binary_op.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/noncontiguous_binary_op.cu
  oneflow/user/ops/noncontiguous_binary_op.cpp
  python/oneflow/test/modules/test_noncontiguous_binary_op.py
Labels: enhancement, feature, op, api

#10283 [CodeGen]Support matmul codegen and runtime in mlir jit
  oneflow/ir/lib/OneFlow/PDLL/AllocEliminationPatterns.pdll
  oneflow/ir/lib/OneFlow/Passes.cpp
  oneflow/ir/test/OneFlow/cuda_code_gen/test_matmul.py
  oneflow/ir/test/Transform/lit.local.cfg
  oneflow/ir/test/Transform/matmul.mlir
  oneflow/ir/test/Transform/softmax.mlir
  oneflow/ir/test/Transform/softmax_codegen_spec_no_vectorize.mlir
Labels: feature, ir, codegen
