Repository Oneflow-Inc/oneflow, pull requests merged in 2023-04, with the labels that each got.

#10050 release np array in main thread to eliminate the time-consuming gil request
  ci/fixed-dev-requirements.txt
  dev-requirements.txt
  oneflow/api/python/utils/tensor_utils.h
  oneflow/core/vm/virtual_machine.cpp
  oneflow/core/vm/virtual_machine.h
Labels: enhancement, eager

#9990 迁移tensor api
  oneflow/api/python/framework/tensor_functions.cpp
  python/oneflow/framework/tensor.py
Labels: enhancement, feature, automerge, op, api, interface

#10021 fix save and load
  python/oneflow/framework/check_point_v2.py
  python/oneflow/test/modules/test_save_load.py
Labels: enhancement, automerge, python

#10052 fix map_location
  python/oneflow/framework/check_point_v2.py
Labels: enhancement, automerge, bug, python

#10069 add dtype for nn.functional.softmax
  python/oneflow/nn/functional/__init__.py
  python/oneflow/nn/functional/softmax.py
  python/oneflow/test/modules/test_softmax.py
Labels: enhancement, op

#9356 Update oneflow readme v3
  README.md
Labels: automerge, tooling, documentation

#10061 add get range index of balance_spliter
  oneflow/core/common/balanced_splitter.cpp
  oneflow/core/common/balanced_splitter.h
  oneflow/core/common/balanced_splitter_test.cpp
Labels: tooling, system

#10049 Extend existing Op support for Complex64 and Complex128 Tensor
  oneflow/core/common/data_type.cpp
  oneflow/core/ep/common/primitive/broadcast_elementwise_binary.h
  oneflow/core/ep/cpu/primitive/broadcast_elementwise_binary.cpp
  oneflow/core/ep/cpu/primitive/broadcast_elementwise_unary.cpp
  oneflow/core/ep/cpu/primitive/fill.cpp
  oneflow/core/ep/cpu/primitive/type_seq.h
  oneflow/core/framework/dtype.cpp
  oneflow/core/framework/tensor_impl.cpp
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/core/ndarray/binary_func.h
  oneflow/core/ndarray/ndarray_apply_broadcast_unary_core.cpp
  oneflow/core/ndarray/ndarray_assign_core.cpp
  oneflow/core/ndarray/ndarray_reduce_impl.cpp
  oneflow/user/kernels/broadcast_like_kernel.cpp
  oneflow/user/kernels/reduce_kernel.cpp
  oneflow/user/kernels/slice_kernel.cpp
  oneflow/user/kernels/slice_util.cpp
  python/oneflow/test/tensor/test_complex.py
Labels: feature, automerge, op, api

#10060 Refine thread manager
  CMakeLists.txt
  oneflow/core/common/balanced_splitter.cpp
  oneflow/core/common/balanced_splitter.h
  oneflow/core/common/balanced_splitter_test.cpp
  oneflow/core/thread/thread_manager.cpp
  oneflow/core/thread/thread_manager.h
  oneflow/core/vm/lazy_job_instruction_policy.h
Labels: enhancement, automerge, system

#10075 Modify graph ops debug
  python/oneflow/nn/graph/graph.py
  python/oneflow/nn/graph/graph_block.py
Labels: enhancement, automerge, graph

#10034 Support real, imag, conj, conj_physical api
  oneflow/core/autograd/gradient_funcs/complex.cpp
  oneflow/core/common/data_type.h
  oneflow/core/ep/cuda/primitive/add.cu
  oneflow/core/ep/cuda/primitive/fill.cu
  oneflow/core/ep/cuda/primitive/type_seq.h
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/complex_kernels.cpp
  oneflow/user/kernels/complex_kernels_util.cpp
  oneflow/user/kernels/complex_kernels_util.cu
  oneflow/user/kernels/complex_kernels_util.h
  oneflow/user/ops/complex_ops.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/math_ops.py
  python/oneflow/framework/tensor.py
  python/oneflow/test/tensor/test_complex.py
Labels: feature, automerge, op, api

#9985 Update LLVM Version to 16.0.0
  .github/workflows/test.yml
  cmake/oneflow.cmake
  cmake/util.cmake
  oneflow/ir/include/OneFlow/OKL/Kernel/LauncherState.h
  oneflow/ir/include/OneFlow/OneFlowBase.td
  oneflow/ir/include/OneFlow/OneFlowOps.h
  oneflow/ir/include/OneFlow/OneFlowOps.td
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/ir/include/OneFlow/SBP/SBPBase.td
  oneflow/ir/lib/OneFlow/Conversion/OneFlowToTosa.cpp
  oneflow/ir/lib/OneFlow/OKL/Conversion/CudaGraphSupport.cpp
  oneflow/ir/lib/OneFlow/OKL/Conversion/OKLToLLVM.cpp
  oneflow/ir/lib/OneFlow/OKL/Kernel/ComputeContext.cpp
  oneflow/ir/lib/OneFlow/OKL/Kernel/JITOpInfer.cpp
  oneflow/ir/lib/OneFlow/OKL/Kernel/LauncherState.cpp
  oneflow/ir/lib/OneFlow/OKL/Kernel/RegContext.cpp
  oneflow/ir/lib/OneFlow/OKM/passes.cpp
  oneflow/ir/lib/OneFlow/OneFlowCanonicalizers.cpp
  oneflow/ir/lib/OneFlow/OneFlowInferReturnTypes.cpp
  oneflow/ir/lib/OneFlow/OneFlowOpFolders.cpp
  oneflow/ir/lib/OneFlow/OneFlowOps.cpp
  oneflow/ir/lib/OneFlow/OneFlowRewrites.cpp
  oneflow/ir/lib/OneFlow/PDLL/ForwardOpPatterns.pdll
  oneflow/ir/lib/OneFlow/PDLL/FuseOpsWithBackwardImplPattern.pdll
  oneflow/ir/lib/OneFlow/PDLL/NormalizationPatterns.pdll
  oneflow/ir/lib/OneFlow/Passes.cpp
  oneflow/ir/lib/OneFlow/SBP/SBPAttributes.cpp
  oneflow/ir/lib/OneFlow/Transform/AggregateOps.cpp
  oneflow/ir/lib/OneFlow/Transform/AutoNHWCOps.cpp
  oneflow/ir/lib/OneFlow/Transform/GroupMatMulOps.cpp
  oneflow/ir/lib/OneFlow/Transform/OutlineAndFuse.cpp
  oneflow/ir/lib/OneFlow/UserOpConversion.cpp
  oneflow/ir/lib/OneFlow/UserOpReflection.cpp
  oneflow/ir/oneflow-extension/include/PyAst/AstMlirGen.h
  oneflow/ir/oneflow-extension/lr_jit.cpp
  oneflow/ir/oneflow-lite/include/OneFlow/FlatbufferUtils.h
  oneflow/ir/oneflow-lite/lib/OneFlow/ConvertToLiteExecutable.cpp
  oneflow/ir/oneflow-lite/lib/OneFlow/OneFlowLiteUtils.cpp
  oneflow/ir/oneflow-lite/lib/OneFlow/Transform/InsertTransferOp.cpp
  oneflow/ir/oneflow-lite/lib/OneFlow/Transform/Lowering/LoweringAscend.cpp
  oneflow/ir/oneflow-lite/lib/OneFlow/Transform/LoweringLaunchJob.cpp
  oneflow/ir/oneflow-lite/lib/OneFlow/Transform/PartitionLaunchJob.cpp
  oneflow/ir/oneflow-opt/oneflow-opt.cpp
  oneflow/ir/oneflow-translate/lib/OneFlow/Importer.cpp
  oneflow/ir/oneflow-translate/lib/OneFlow/MLIROneFlowTranslation.cpp
  oneflow/ir/test/OneFlow/conversion/OneFlowToTosa.mlir
  oneflow/ir/test/OneFlow/cse.mlir
  oneflow/ir/test/OneFlow/cuda_code_gen/fuse_cast_scale.mlir
  oneflow/ir/test/OneFlow/cuda_code_gen/gpu_copy_arg.mlir
  oneflow/ir/test/OneFlow/cuda_code_gen/gpu_runner.mlir
  oneflow/ir/test/OneFlow/fuse_forward_ops.mlir
  oneflow/ir/test/OneFlow/jit-outline-func.mlir
  oneflow/ir/test/OneFlow/kernel_launch/test_resnet.py
  tools/oneflow-tblgen/example/constant.td
  tools/oneflow-tblgen/op_schema_emitter.cpp
Labels: enhancement, need-all-tests-even-fail, ir

#9879 NCCL logical kernel fusion
  oneflow/core/common/env_var/debug_mode.h
  oneflow/core/job/sbp_parallel.cpp
  oneflow/core/job/sbp_parallel.h
  oneflow/core/job_rewriter/insert_nccl_logical_op_pass.cpp
  oneflow/core/job_rewriter/job_completer.cpp
  oneflow/core/job_rewriter/logical_chain_pass.cpp
  oneflow/core/job_rewriter/nccl_logical_chain_strict_order_pass.cpp
  oneflow/core/job_rewriter/nccl_logical_op_fusion_pass.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/nccl_logical_fusion_kernel.cpp
  oneflow/user/kernels/nccl_logical_send_recv_kernel.cpp
  oneflow/user/ops/nccl_logical_fusion_op.cpp
  oneflow/user/ops/nccl_logical_ops.cpp
  oneflow/user/ops/nccl_logical_util.cpp
  oneflow/user/ops/nccl_logical_util.h
  python/oneflow/nn/graph/graph_config.py
  python/oneflow/test/graph/test_graph_nccl_logical_fusion.py
Labels: feature, bottleneck, automerge, graph

#10084 Fix graph map tuple leaf for dict
  python/oneflow/framework/args_tree.py
  python/oneflow/test/graph/test_graph_io_check.py
Labels: bug, graph

#10078 shared in graph _compile
  python/oneflow/nn/graph/cache.py
  python/oneflow/nn/graph/graph.py
Labels: feature, automerge, graph

#10081 Debug actor log
  oneflow/core/common/env_var/debug_mode.h
  oneflow/core/lazy/actor/actor.cpp
  oneflow/core/lazy/actor/actor.h
  oneflow/core/lazy/actor/light_actor.cpp
  oneflow/core/vm/lazy_job_instruction_policy.h
Labels: feature, automerge, graph

#9914 implement fused rotary embedding
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/fused_attention_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/fused_attention_kernels.cu
  oneflow/user/ops/fused_attention_ops.cpp
  python/oneflow/test/modules/test_fused_rotary_embedding.py
Labels: feature, automerge, op

#10086 Dev support char and short dtype
  oneflow/api/python/framework/dtype.cpp
  oneflow/api/python/framework/tensor.cpp
  oneflow/api/python/framework/tensortype.cpp
  oneflow/api/python/functional/python_arg.cpp
  oneflow/api/python/functional/value_types.cpp
  oneflow/api/python/functional/value_types.h
  oneflow/core/common/data_type.cpp
  oneflow/core/common/data_type.h
  oneflow/core/common/data_type_seq.h
  oneflow/core/ep/cpu/primitive/type_seq.h
  oneflow/core/ep/cuda/primitive/type_seq.h
  oneflow/extension/python/numpy.cpp
  python/oneflow/__init__.py
  python/oneflow/framework/dtype.py
  python/oneflow/test/modules/test_constant.py
  python/oneflow/test/modules/test_tensor_ops.py
Labels: enhancement, feature, automerge, eager, api

#10095 fix clang-tidy ci
  .github/workflows/test.yml
Labels: automerge, bug, ci, build

#10094 hot fix short dtype bug in primitive
  oneflow/core/ep/cpu/primitive/fill.cpp
  oneflow/core/ep/cpu/primitive/type_seq.h
  oneflow/core/ep/cuda/primitive/fill.cu
  oneflow/core/ep/cuda/primitive/type_seq.h
  oneflow/core/functional/impl/comm_functor.cpp
Labels: enhancement, automerge, bug, eager, api

#10097 remove mem_chain merge
  oneflow/core/job/compiler.cpp
  oneflow/core/job/intra_job_mem_sharing_util.cpp
  oneflow/core/job/intra_job_mem_sharing_util.h
  oneflow/core/job/resource.proto
Labels: purge, automerge, graph

#9993 Refactor codegen
  .github/workflows/test.yml
  oneflow/ir/include/OneFlow/Conversion/OneFlowToTosa.h
  oneflow/ir/include/OneFlow/OneFlowPDLLPatterns.h
  oneflow/ir/include/OneFlow/OneFlowPasses.td
  oneflow/ir/include/OneFlow/Passes.h
  oneflow/ir/include/OneFlow/Transform/FuncOps.h
  oneflow/ir/lib/OneFlow/CMakeLists.txt
  oneflow/ir/lib/OneFlow/Conversion/OneFlowToLinalg.cpp
  oneflow/ir/lib/OneFlow/Conversion/OneFlowToTosa.cpp
  oneflow/ir/lib/OneFlow/OneFlowRewrites.cpp
  oneflow/ir/lib/OneFlow/PDLL/CMakeLists.txt
  oneflow/ir/lib/OneFlow/PDLL/ElementwiseFusionPatterns.pdll
  oneflow/ir/lib/OneFlow/PDLL/ForwardOpPatterns.pdll
  oneflow/ir/lib/OneFlow/PDLL/OneFlowPDLLUtils.pdll
  oneflow/ir/lib/OneFlow/Passes.cpp
  oneflow/ir/lib/OneFlow/Transform/FuncOps.cpp
  oneflow/ir/lib/OneFlow/Transform/JITPasses.cpp
  oneflow/ir/lib/OneFlow/Transform/OutlineAndFuse.cpp
  oneflow/ir/oneflow-extension/mlir_jit_op_kernel.cpp
  oneflow/ir/oneflow-opt/oneflow-opt.cpp
  oneflow/ir/oneflow-translate/lib/OneFlow/CMakeLists.txt
  oneflow/ir/oneflow-translate/lib/OneFlow/MLIROneFlowTranslation.cpp
  oneflow/ir/test/Frontend/OneFlowToIree.mlir
  oneflow/ir/test/Frontend/test_tosa_to_elf.mlir
  oneflow/ir/test/OneFlow/cuda_code_gen/fuse_cast_scale.mlir
  oneflow/ir/test/OneFlow/cuda_code_gen/tosa_to_linalg.mlir
  oneflow/ir/test/OneFlow/jit-outline-func.mlir
  oneflow/ir/test/OneFlow/kernel_launch/test_resnet.py
  oneflow/ir/test/OneFlow/with_cuda/test_graph_save_and_load.py
  oneflow/ir/test/lit.cfg.py
Labels: enhancement, automerge, need-all-tests-even-fail, ir

#10093 change top k kernel dispatching logic
  oneflow/user/kernels/radix_sort_top_k_kernel.cu
  oneflow/user/kernels/top_k_kernel.cu
Labels: enhancement, automerge, bug, op

#10102 TaskNode::order_in_chain
  oneflow/core/graph/plan_task_graph.cpp
  oneflow/core/graph/plan_task_graph.h
  oneflow/core/graph/straighten_nodes.cpp
  oneflow/core/graph/task_graph.cpp
  oneflow/core/graph/task_graph.h
  oneflow/core/graph/task_node.cpp
  oneflow/core/graph/task_node.h
  oneflow/core/job/intra_job_mem_sharing_util.cpp
  oneflow/core/job/plan_util.cpp
  oneflow/core/job/task.proto
  oneflow/core/job_rewriter/logical_chain_pass.cpp
  oneflow/core/operator/op_conf.proto
Labels: enhancement, graph

#10089 support training nn.Graph by VM in limited cases
  oneflow/core/job/job_interpreter.cpp
  oneflow/core/vm/op_call_instruction_policy.cpp
  oneflow/core/vm/remat/disjoint_set.cpp
  oneflow/core/vm/remat/util.cpp
Labels: enhancement, automerge, system

#10066 add Digamma op
  docs/source/special.rst
  docs/source/tensor.rst
  oneflow/api/python/framework/tensor_functions.cpp
  oneflow/core/common/math_util.h
  oneflow/core/ep/common/primitive/broadcast_elementwise_binary.h
  oneflow/core/ep/common/primitive/elementwise_unary.h
  oneflow/core/ep/cpu/primitive/binary_functor.h
  oneflow/core/ep/cpu/primitive/unary_functor.h
  oneflow/core/ep/cuda/primitive/binary_functor.cuh
  oneflow/core/ep/cuda/primitive/unary_functor.cuh
  oneflow/core/ep/include/primitive/binary_op.h
  oneflow/core/ep/include/primitive/unary_op.h
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/unary_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/math_unary_elementwise_primitive_kernel.cpp
  oneflow/user/ops/math_unary_elementwise_seq.h
  python/oneflow/__init__.py
  python/oneflow/framework/docstr/math_ops.py
  python/oneflow/framework/docstr/special_ops.py
  python/oneflow/framework/docstr/tensor.py
  python/oneflow/special/__init__.py
  python/oneflow/special/special_ops.py
  python/oneflow/test/modules/test_global_math_ops.py
  python/oneflow/test/modules/test_math_ops.py
  python/oneflow/test/modules/test_special_ops.py
  python/oneflow/test/tensor/test_bfloat16_activation.py
  python/oneflow/test/tensor/test_tensor_part_2.py
Labels: enhancement, feature, automerge, op, api, interface

#10111 add tensor.data_ptr()
  oneflow/api/python/framework/tensor.cpp
  oneflow/api/python/utils/tensor_utils.h
  python/oneflow/test/tensor/test_data_ptr.py
Labels: feature, eager

#10109 fix rotary emb sbp
  oneflow/user/ops/fused_attention_ops.cpp
Labels: bug, op

#9819 add IsNonOverlappingAndDense fn
  oneflow/core/functional/impl/common.cpp
  oneflow/core/functional/impl/common.h
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  python/oneflow/test/modules/test_cast.py
Labels: enhancement, bug, eager

#10115 refine conv test
  python/oneflow/test/modules/test_conv2d.py
Labels: enhancement, automerge, bug, ci, eager, api

#10025 develop ep random generator
  oneflow/core/common/device_type.cpp
  oneflow/core/common/device_type.h
  oneflow/core/ep/cpu/cpu_device_manager.cpp
  oneflow/core/ep/cpu/cpu_device_manager.h
  oneflow/core/ep/cpu/cpu_random_generator.cpp
  oneflow/core/ep/cpu/cpu_random_generator.h
  oneflow/core/ep/cuda/cuda_device_manager.cpp
  oneflow/core/ep/cuda/cuda_device_manager.h
  oneflow/core/ep/cuda/cuda_random_generator.cpp
  oneflow/core/ep/cuda/cuda_random_generator.h
  oneflow/core/ep/include/device_manager.h
  oneflow/core/ep/include/random_generator.h
  oneflow/core/framework/auto_random_generator.cpp
  oneflow/core/framework/auto_random_generator.h
  oneflow/core/framework/random_generator.cpp
  oneflow/core/framework/random_generator.h
  oneflow/core/framework/random_generator_impl.cpp
  oneflow/core/framework/random_generator_impl.h
  oneflow/user/kernels/bernoulli_kernel.cpp
  oneflow/user/kernels/distributions/exponential_distribution.cpp
  oneflow/user/kernels/distributions/exponential_distribution.cu
  oneflow/user/kernels/distributions/multinomial_with_replacement_kernel.cpp
  oneflow/user/kernels/distributions/multinomial_with_replacement_kernel.cu
  oneflow/user/kernels/distributions/normal_distribution.cpp
  oneflow/user/kernels/distributions/normal_distribution.cu
  oneflow/user/kernels/distributions/uniform_distribution.cpp
  oneflow/user/kernels/distributions/uniform_distribution.cu
  oneflow/user/kernels/distributions/uniform_int_distribution.cpp
  oneflow/user/kernels/distributions/uniform_int_distribution.cu
  oneflow/user/kernels/dropout_kernel.cpp
  oneflow/user/kernels/dropout_kernel.cu
  oneflow/user/kernels/fused_matmul_bias_add_relu_dropout.cu
  oneflow/user/kernels/random_mask_generator.h
  oneflow/user/kernels/random_seed_util.cpp
  oneflow/user/kernels/randperm_kernel.cpp
  oneflow/user/kernels/randperm_kernel.cu
  oneflow/user/kernels/rrelu_kernel.cpp
  oneflow/user/kernels/rrelu_kernel.cu
  python/oneflow/framework/register_class_method_util.py
Labels: enhancement, automerge, system, refactor

#7811 Add module .get_submodule() and .get_parameter() function
  python/oneflow/nn/modules/module.py
  python/oneflow/test/modules/test_module.py
Labels: enhancement, automerge, api, python

#10101 support tensor.is_view
  oneflow/api/python/framework/tensor.cpp
  oneflow/core/common/tensor_meta.cpp
  oneflow/core/common/tensor_meta.h
  oneflow/core/framework/tensor.h
  oneflow/core/framework/tensor_impl.h
  oneflow/core/framework/tensor_methods.cpp
  python/oneflow/test/tensor/test_tensor_is_view.py
Labels: enhancement, automerge, eager, api

#10090 print key in error msg of MapAt
  oneflow/core/common/container_util.h
Labels: enhancement, automerge, system

#10088 speed up module constructor
  python/oneflow/nn/modules/module.py
Labels: enhancement, feature, automerge, python

#10131 fix link error
  cmake/caches/cn/cuda.cmake
Labels: automerge, bug, build, system

#10121 remove some unused code in op_interpreter
  oneflow/core/framework/op_interpreter.h
  oneflow/core/framework/op_interpreter/op_interpreter_util.cpp
  oneflow/core/framework/op_interpreter/op_interpreter_util.h
Labels: purge, automerge, system

#10108 fix_fused_glu_sbp
  oneflow/user/ops/fused_glu_op.cpp
Labels: bug, op

#9912 use bombela/backward-cpp to get better stacktrace
  cmake/oneflow.cmake
  cmake/third_party/FindBFD.cmake
  cmake/third_party/FindUnwind.cmake
  oneflow/api/python/stack_getter.cpp
  oneflow/core/common/error.cpp
  oneflow/core/common/error.h
  oneflow/extension/stack/stacktrace.h
  python/oneflow/__init__.py
Labels: feature, automerge, system

#10125 align AutoGrad engine function_node name and next_functions type with pytorch AutoGrad Engine
  oneflow/core/autograd/autograd_engine.cpp
  oneflow/core/autograd/autograd_engine.h
  oneflow/core/autograd/gradient_funcs/concat.cpp
  oneflow/core/framework/op_interpreter/op_interpreter.cpp
  oneflow/core/functional/impl/array_functor.cpp
  oneflow/core/job_rewriter/auto_mixed_precision_lists.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/binary_concat_kernel.cu
  oneflow/user/kernels/concat_kernel.cpp
  python/oneflow/framework/docstr/activation.py
  python/oneflow/nn/functional/ctc_loss.py
  python/oneflow/nn/graph/graph.py
  python/oneflow/nn/modules/module.py
  python/oneflow/test/modules/test_concat.py
  python/oneflow/utils/hooks.py
Labels: enhancement, automerge, eager, api

#10139 support data_ptr() on global tensors
  oneflow/api/python/framework/tensor.cpp
  python/oneflow/test/tensor/test_data_ptr.py
Labels: enhancement, automerge, eager

#10133 100 runs on diff
  .github/workflows/test.yml
  ci/test/generic_test_multi_client.sh
  ci/test/multi_launch.py
  dev-requirements.txt
  python/oneflow/test/graph/test_graph_zero.py
  python/oneflow/test/modules/test_tensor_ops.py
Labels: enhancement, ci

#10110 nn.MaxPool2d support 3D input tensor
  oneflow/core/functional/impl/common.cpp
  oneflow/core/functional/impl/common.h
  oneflow/core/functional/impl/nn_functor.cpp
  python/oneflow/test/modules/test_maxpool.py
Labels: enhancement, automerge, eager, api

#10153 Increase oneflow ci pass rate
  oneflow/api/cpp/tests/graph_test.cpp
  python/oneflow/test/expensive/test_einsum.py
  python/oneflow/test/expensive/test_remat.py
  python/oneflow/test/expensive/test_rnn_cell.py
  python/oneflow/test/graph/test_graph_lrs.py
  python/oneflow/test/graph/test_graph_optim_adadelta.py
  python/oneflow/test/graph/test_graph_random_seed.py
  python/oneflow/test/graph/test_graph_save_load_global_b_s.py
  python/oneflow/test/graph/test_graph_sparse_optimizer.py
  python/oneflow/test/graph/test_graph_with_global.py
  python/oneflow/test/misc/test_placement.py
  python/oneflow/test/modules/test_batchnorm.py
  python/oneflow/test/modules/test_constant.py
  python/oneflow/test/modules/test_conv1d.py
  python/oneflow/test/modules/test_conv2d.py
  python/oneflow/test/modules/test_copy.py
  python/oneflow/test/modules/test_cosine_similarity.py
  python/oneflow/test/modules/test_ctc_loss.py
  python/oneflow/test/modules/test_dropout.py
  python/oneflow/test/modules/test_fused_glu.py
  python/oneflow/test/modules/test_global_TripletMarginLoss.py
  python/oneflow/test/modules/test_global_dot.py
  python/oneflow/test/modules/test_global_einsum_alphaflod_usecase3.py
  python/oneflow/test/modules/test_global_einsum_batch_matrix_vector_multiply.py
  python/oneflow/test/modules/test_global_einsum_matmul2.py
  python/oneflow/test/modules/test_global_einsum_matrix_column_sum.py
  python/oneflow/test/modules/test_global_einsum_tensor_contraction2.py
  python/oneflow/test/modules/test_global_higher_derivative_div.py
  python/oneflow/test/modules/test_global_higher_derivative_matmul.py
  python/oneflow/test/modules/test_global_min.py
  python/oneflow/test/modules/test_global_random_op_data.py
  python/oneflow/test/modules/test_global_searchsorted.py
  python/oneflow/test/modules/test_global_slice.py
  python/oneflow/test/modules/test_global_weight_norm.py
  python/oneflow/test/modules/test_higher_derivative_activation.py
  python/oneflow/test/modules/test_higher_derivative_loss.py
  python/oneflow/test/modules/test_loss.py
  python/oneflow/test/modules/test_module_to.py
  python/oneflow/test/modules/test_one_embedding_adam.py
  python/oneflow/test/modules/test_random_generator_and_seed.py
  python/oneflow/test/modules/test_rmsnorm.py
  python/oneflow/test/modules/test_rrelu.py
  python/oneflow/test/tensor/test_complex.py
Labels: automerge, bug, ci, eager, api

#10062 modify check msg
  oneflow/user/ops/in_top_k_op.cpp
  oneflow/user/ops/masked_fill_op.cpp
  python/oneflow/test/exceptions/test_gird_sample_op.py
  python/oneflow/test/exceptions/test_in_top_k.py
Labels: enhancement, automerge, op, test, need-check-error-message

#10092 Update absl to fix #10091
  .github/workflows/test.yml
  cmake/third_party/absl.cmake
  cmake/third_party/grpc.cmake
Labels: bug, build

#10105 Fix CodeGen Bug
  oneflow/ir/include/OneFlow/Conversion/OneFlowToTosa.h
  oneflow/ir/include/OneFlow/OneFlowOps.td
  oneflow/ir/include/OneFlow/OneFlowPasses.td
  oneflow/ir/lib/OneFlow/Conversion/OneFlowToTosa.cpp
  oneflow/ir/lib/OneFlow/OneFlowInferReturnTypes.cpp
  oneflow/ir/lib/OneFlow/Transform/AutoNHWCOps.cpp
  oneflow/ir/oneflow-opt/oneflow-opt.cpp
  oneflow/ir/oneflow-translate/lib/OneFlow/MLIROneFlowTranslation.cpp
  oneflow/ir/test/Frontend/OneFlowToIree.mlir
  oneflow/ir/test/OneFlow/auto_nhwc/test_nhwc_resnet.py
  oneflow/ir/test/OneFlow/conversion/OneFlowToTosa.mlir
  oneflow/ir/test/OneFlow/cuda_code_gen/test_cast_ops_to_signless.mlir
Labels: enhancement, automerge, need-all-tests-even-fail, ir

#10160 skip global ctc loss test
  oneflow/core/functional/impl/nn_functor.cpp
  python/oneflow/test/modules/test_global_ctc_loss.py
  python/oneflow/test/modules/test_global_einsum_matmul.py
Labels: automerge, bug, ci

#10161 shorten the signature of complex func in stacktrace
  oneflow/extension/stack/stacktrace.h
Labels: enhancement, automerge, system

#10119 Task to/from proto
  oneflow/core/graph/boxing_identity_task_node.cpp
  oneflow/core/graph/boxing_identity_task_node.h
  oneflow/core/graph/boxing_task_graph.proto
  oneflow/core/graph/boxing_zeros_task_node.cpp
  oneflow/core/graph/boxing_zeros_task_node.h
  oneflow/core/graph/collective_boxing_pack_task_node.cpp
  oneflow/core/graph/collective_boxing_pack_task_node.h
  oneflow/core/graph/collective_boxing_task_node.cpp
  oneflow/core/graph/collective_boxing_task_node.h
  oneflow/core/graph/collective_boxing_unpack_task_node.cpp
  oneflow/core/graph/collective_boxing_unpack_task_node.h
  oneflow/core/graph/compute_task_node.cpp
  oneflow/core/graph/compute_task_node.h
  oneflow/core/graph/copy_task_node.cpp
  oneflow/core/graph/copy_task_node.h
  oneflow/core/graph/nccl_send_recv_boxing_task_node.cpp
  oneflow/core/graph/nccl_send_recv_boxing_task_node.h
  oneflow/core/graph/slice_boxing_task_node.cpp
  oneflow/core/graph/slice_boxing_task_node.h
  oneflow/core/graph/task_edge.proto
  oneflow/core/graph/task_graph_rebuild_ctx.cpp
  oneflow/core/graph/task_graph_rebuild_ctx.h
  oneflow/core/graph/task_node.cpp
  oneflow/core/graph/task_node.h
  oneflow/core/graph/task_type_visitor.h
  oneflow/core/graph/transport_task_node.cpp
  oneflow/core/graph/transport_task_node.h
  oneflow/core/register/register_desc.cpp
  oneflow/core/register/register_desc.h
Labels: feature, automerge, graph

#10164 add mlu device type
  oneflow/core/common/device_type.proto
Labels: enhancement, automerge, system, mlu

#10124 Task infer blob desc support choosing method
  oneflow/core/graph/boxing_identity_task_node.cpp
  oneflow/core/graph/boxing_zeros_task_node.cpp
  oneflow/core/graph/collective_boxing_pack_task_node.cpp
  oneflow/core/graph/collective_boxing_task_node.cpp
  oneflow/core/graph/collective_boxing_unpack_task_node.cpp
  oneflow/core/graph/compute_task_node.h
  oneflow/core/graph/exec_graph.cpp
  oneflow/core/graph/exec_graph.h
  oneflow/core/graph/nccl_send_recv_boxing_task_node.cpp
  oneflow/core/graph/slice_boxing_task_node.cpp
  oneflow/core/graph/task_node.h
  oneflow/core/graph/transport_task_node.h
  oneflow/core/graph_impl/acc_compute_task_node.cpp
  oneflow/core/graph_impl/acc_ctrl_tick_compute_task_node.cpp
  oneflow/core/graph_impl/acc_tick_compute_task_node.cpp
  oneflow/core/graph_impl/case_compute_task_node.cpp
  oneflow/core/graph_impl/critical_section_wait_compute_task_node.cpp
  oneflow/core/graph_impl/decode_h2d_compute_task_node.cpp
  oneflow/core/graph_impl/device_tick_compute_task_node.cpp
  oneflow/core/graph_impl/distribute_concat_compute_task_node.cpp
  oneflow/core/graph_impl/distribute_split_compute_task_node.cpp
  oneflow/core/graph_impl/dst_subset_tick_compute_task_node.cpp
  oneflow/core/graph_impl/esac_compute_task_node.cpp
  oneflow/core/graph_impl/normal_forward_compute_task_node.cpp
  oneflow/core/graph_impl/pack_compute_task_node.cpp
  oneflow/core/graph_impl/reentrant_lock_compute_task_node.cpp
  oneflow/core/graph_impl/repeat_compute_task_node.cpp
  oneflow/core/graph_impl/source_tick_compute_task_node.cpp
  oneflow/core/graph_impl/src_subset_tick_compute_task_node.cpp
  oneflow/core/graph_impl/ssp_variable_proxy_task_node.cpp
  oneflow/core/graph_impl/tick_compute_task_node.cpp
  oneflow/core/graph_impl/unpack_compute_task_node.cpp
  oneflow/core/graph_impl/wait_and_send_ids_compute_task_node.cpp
Labels: feature, automerge, graph

#10172 add is_cpu api
  oneflow/api/python/framework/tensor.cpp
  oneflow/api/python/framework/tensor_functions.cpp
  oneflow/core/framework/tensor.cpp
  oneflow/core/framework/tensor.h
  python/oneflow/nn/modules/normalization.py
Labels: enhancement, automerge, system

#10117 Trigamma kernel dev
  oneflow/core/ep/common/primitive/elementwise_unary.h
  oneflow/core/ep/cpu/primitive/binary_functor.h
  oneflow/core/ep/cpu/primitive/unary_functor.h
  oneflow/core/ep/cuda/primitive/binary_functor.cuh
  oneflow/core/ep/cuda/primitive/unary_functor.cuh
  oneflow/core/ep/include/primitive/unary_op.h
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/unary_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/math_unary_elementwise_primitive_kernel.cpp
  oneflow/user/ops/math_unary_elementwise_op.cpp
  oneflow/user/ops/math_unary_elementwise_seq.h
  python/oneflow/test/modules/test_global_math_ops.py
  python/oneflow/test/modules/test_math_ops.py
  python/oneflow/test/modules/test_special_ops.py
  python/oneflow/test/tensor/test_tensor_part_2.py
Labels: enhancement, feature, automerge, op, api, primitive

#10171 add layout and frombuffer
  python/oneflow/__init__.py
  python/oneflow/framework/check_point_v2.py
  python/oneflow/framework/tensor.py
  python/oneflow/test/tensor/test_safetensors.py
Labels: automerge, bug, python

#10167 align conv/conv_transpose init attr
  python/oneflow/nn/modules/conv.py
Labels: enhancement, automerge, bug, eager, api

#10169 delete pooling_batchify repeated function
  oneflow/core/functional/impl/common.cpp
  oneflow/core/functional/impl/common.h
  oneflow/core/functional/impl/nn_functor.cpp
Labels: enhancement, automerge, bug, eager, api

#10175 speed uppppppppppppppppppppppppppppppppppppppp ci
  python/oneflow/test/graph/test_alexnet_graph.py
  python/oneflow/test/graph/test_forward_graph.py
  python/oneflow/test/graph/test_graph_copy.py
  python/oneflow/test/graph/test_graph_free_eager_tensor.py
  python/oneflow/test/graph/test_graph_image_gpu_decoder.py
  python/oneflow/test/graph/test_graph_optimizer.py
  python/oneflow/test/graph/test_graph_save_load_global_b_s.py
  python/oneflow/test/misc/test_mock_scope.py
  python/oneflow/test/modules/test_TripletMarginLoss.py
  python/oneflow/test/modules/test_adaptive_max_pool.py
  python/oneflow/test/modules/test_autograd.py
  python/oneflow/test/modules/test_generator.py
  python/oneflow/test/modules/test_global_0_dim_tensor.py
  python/oneflow/test/modules/test_global_abs.py
  python/oneflow/test/modules/test_global_add.py
  python/oneflow/test/modules/test_global_deconv2d.py
  python/oneflow/test/modules/test_global_repeat.py
  python/oneflow/test/modules/test_global_sum.py
  python/oneflow/test/modules/test_global_tril.py
  python/oneflow/test/modules/test_loss.py
  python/oneflow/test/modules/test_one_embedding_ftrl.py
  python/oneflow/test/modules/test_parital_fc.py
  python/oneflow/test/modules/test_qat_conv_modules.py
  python/oneflow/test/modules/test_sparse.py
  python/oneflow/test/modules/test_sub.py
  python/oneflow/test/tensor/test_complex.py
  python/oneflow/test/tensor/test_tensor_part_1.py
  python/oneflow/test/tensor/test_tensor_part_2.py
Labels: enhancement, automerge, ci, eager, api

#10100 refactor_ccl_comm_mgr_register
  oneflow/core/functional/impl/comm_functor.cpp
  oneflow/core/job/eager_ccl_comm_manager.cpp
  oneflow/core/job/eager_ccl_comm_manager.h
  oneflow/core/job/eager_nccl_comm_manager.cpp
  oneflow/core/job/eager_nccl_comm_manager.h
  oneflow/core/job/env_global_objects_scope.cpp
  oneflow/core/job/runtime.cpp
  oneflow/core/job_rewriter/insert_nccl_logical_op_pass.cpp
  oneflow/core/kernel/nccl_send_recv_boxing_kernel.cpp
  oneflow/core/vm/remat/util.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/collective_communication/cuda/cuda_communication_context.cpp
  oneflow/user/kernels/collective_communication/cuda/cuda_send_recv_util.cpp
  oneflow/user/kernels/cublas_fused_mlp_grad_kernel.cu
  oneflow/user/kernels/data_shuffle_kernel.cu
  oneflow/user/kernels/eager_ccl_kernel.cpp
  oneflow/user/kernels/eager_nccl_kernels.cu
  oneflow/user/kernels/eager_nccl_s2s_kernel.cu
  oneflow/user/kernels/nccl_logical_2d_sbp_kernels.cpp
  oneflow/user/kernels/nccl_logical_fusion_kernel.cpp
  oneflow/user/kernels/nccl_logical_kernels.cpp
  oneflow/user/kernels/nccl_logical_send_recv_kernel.cpp
  oneflow/user/kernels/one_embedding_kernels.cu
  oneflow/user/ops/eager_ccl_ops.cpp
Labels: enhancement, automerge, system

#10179 update freedesktop urls
  cmake/third_party/hwloc.cmake
Labels: automerge, bug, ci, build

#10165 fix scalar max bug
  oneflow/core/functional/functional_api.yaml
  python/oneflow/test/modules/test_max.py
Labels: enhancement, automerge, bug, eager, api

#9296 Add cache for eager amp parameter
  oneflow/api/python/framework/autocast.cpp
  oneflow/core/framework/autocast.cpp
  oneflow/core/framework/autocast.h
  oneflow/core/functional/tensor_processor.cpp
  oneflow/core/vm/remat/disjoint_set.cpp
Labels: enhancement, automerge, eager, build, system

#10138 improve flow.load for better error message
  python/oneflow/framework/check_point_v2.py
  python/oneflow/mock_torch/__init__.py
  python/oneflow/test/exceptions/test_save_load.py
Labels: enhancement, automerge, eager

#10132 fix groupwise quantization sbp
  oneflow/user/ops/fused_linear_with_groupwise_quantized_weight_op.cpp
  oneflow/user/ops/groupwise_dequantize_op.cpp
Labels: bug, op, api, global

#10157 avoid memcpy DtoD when set grad_sbp under eval mode
  oneflow/core/functional/impl/global_cast.cpp
Labels: enhancement, automerge, bug, eager, api

#10186 fix 0size tensor braodcast bug
  oneflow/core/functional/impl/common.cpp
  python/oneflow/test/modules/test_add.py
Labels: enhancement, automerge, bug, eager, api

#10073 enable eager global inputs with inconsistent placement
  oneflow/core/framework/op_interpreter/eager_global_op_interpreter.cpp
  python/oneflow/test/modules/test_auto_to_global.py
Labels: enhancement, feature, eager

#10083 fix_eager_code_to_support_new_device
  oneflow/core/boxing/symmetric_b_to_s_boxing.cpp
  oneflow/core/functional/impl/global_cast.cpp
  oneflow/user/kernels/eager_ccl_kernel.cpp
  oneflow/user/ops/comm_net_device_infer_util.cpp
  oneflow/user/ops/comm_net_device_infer_util.h
Labels: enhancement, automerge, eager, system, refactor

#10137 [resubmit] support training nn.Graph by VM in limited cases
  .github/workflows/test.yml
  .tsan-suppressions
  cmake/util.cmake
  oneflow/api/cpp/tests/graph_test.cpp
  oneflow/core/job/job_interpreter.cpp
  oneflow/core/vm/op_call_instruction_policy.cpp
  oneflow/core/vm/remat/allocator.cpp
  oneflow/core/vm/remat/disjoint_set.cpp
  oneflow/core/vm/remat/env.h
  oneflow/core/vm/remat/util.cpp
  oneflow/ir/oneflow-lite/schemas/install_flatcc.cmake
  tools/oneflow-tblgen/CMakeLists.txt
Labels: enhancement, automerge, graph

#10208 fix cmake error
  cmake/util.cmake
  oneflow/ir/oneflow-lite/schemas/install_flatcc.cmake
  tools/oneflow-tblgen/CMakeLists.txt
Labels: bug, build

#10174 [AutoGrad] FunctionNode support variable(Return which Tensor's gradient needs to be accumulated)
  oneflow/api/python/autograd/function_node.cpp
  oneflow/core/autograd/autograd_engine.cpp
  oneflow/core/autograd/autograd_engine.h
  python/oneflow/test/modules/test_concat.py
Labels: enhancement, automerge, bug, eager, api

#10204 reduce sum support dtype
  oneflow/api/python/framework/tensor_functions.cpp
  oneflow/core/autograd/gradient_funcs/bias_add.cpp
  oneflow/core/autograd/gradient_funcs/conv.cpp
  oneflow/core/autograd/gradient_funcs/cublas_fused_mlp.cpp
  oneflow/core/autograd/gradient_funcs/expand.cpp
  oneflow/core/autograd/gradient_funcs/fill.cpp
  oneflow/core/autograd/gradient_funcs/fused_bias_add_dropout.cpp
  oneflow/core/autograd/gradient_funcs/fused_bias_add_gelu.cpp
  oneflow/core/autograd/gradient_funcs/fused_glu.cpp
  oneflow/core/autograd/gradient_funcs/fused_matmul_bias.cpp
  oneflow/core/autograd/gradient_funcs/fused_matmul_bias_add_relu_dropout.cpp
  oneflow/core/autograd/gradient_funcs/fused_scale_mask_bias_softmax.cpp
  oneflow/core/autograd/gradient_funcs/median.cpp
  oneflow/core/autograd/gradient_funcs/reduce_ops.cpp
  oneflow/core/autograd/gradient_funcs/tensor_scalar_binary.cpp
  oneflow/core/autograd/gradient_funcs/where.cpp
  oneflow/core/autograd/higher_order_gradient_funcs/log_softmax.cpp
  oneflow/core/autograd/higher_order_gradient_funcs/softmax.cpp
  oneflow/core/framework/tensor_methods.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/math_functor.cpp
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/core/functional/impl/random_functor.cpp
  python/oneflow/test/modules/test_sum.py
Labels: enhancement, automerge, bug, eager, api

#10211 cast support bool2int16
  oneflow/core/ep/cpu/primitive/broadcast_elementwise_unary.cpp
  oneflow/core/ep/cuda/primitive/broadcast_elementwise_unary.cu
  python/oneflow/test/modules/test_cast.py
Labels: enhancement, automerge, bug, eager, api

#10207 Update mock behaviour
  python/oneflow/mock_torch/__init__.py
  python/oneflow/test/misc/test_mock_scope.py
Labels: automerge, bug, python

#10214 Release/add nightly date index
  .github/workflows/canary.yml
  .github/workflows/on_merge.yml
  .github/workflows/release.yml
  .github/workflows/simple.yml
  .github/workflows/test.yml
  tools/generate_pip_version.py
Labels: enhancement, ci

#10194 support setattr on mock torch object
  python/oneflow/mock_torch/__init__.py
  python/oneflow/test/misc/test_mock_scope.py
Labels: enhancement, automerge, python
