Repository Oneflow-Inc/oneflow, pull requests merged in 2023-12, with the labels that each got.

#10369 Fix concurrency for priv/community
  .github/workflows/community_release.yml
  .github/workflows/priv_release.yml
Labels: enhancement, ci

#10368 Community fix cu12 pkg size
  .github/workflows/canary.yml
  .github/workflows/on_merge.yml
  .github/workflows/release.yml
  .github/workflows/simple.yml
  .github/workflows/test.yml
Labels: enhancement, ci

#10371 Remove py3.7 in release
  .github/workflows/release.yml
Labels: enhancement, ci

#10373 Use dynamic link in cn/cpu.cmake, international/cpu.cmake, international/cuda.cmake to avoid llvm15 link error
  cmake/caches/cn/cpu.cmake
  cmake/caches/international/cpu.cmake
  cmake/caches/international/cuda.cmake
Labels: enhancement, build

#10377 Community build py311
  .github/workflows/canary.yml
  .github/workflows/on_merge.yml
  .github/workflows/release.yml
  .github/workflows/simple.yml
  .github/workflows/test.yml
Labels: enhancement, ci

#10383 Skip Conv cases failed
  .github/workflows/test.yml
  ci/test/generic_test_multi_client.sh
  python/oneflow/test/expensive/test_compatibility.py
  python/oneflow/test/modules/test_fft.py
Labels: automerge, bug, ci

#10356 autograd.functional.vjp
  docs/source/autograd.rst
  python/oneflow/__init__.py
  python/oneflow/autograd/functional.py
  python/oneflow/test/misc/test_autograd_functional.py
Labels: enhancement, documentation, api, python, need-clean-ccache

#10367 Support cuda 12.x
  oneflow/core/device/cuda_pseudo_bfloat16.h
  oneflow/core/ep/test/primitive/fill_test.cpp
  oneflow/core/ndarray/ndarray_reduce_impl.cu
  oneflow/user/kernels/arange_kernel.cpp
Labels: bug, build

#10386 Support Huawei Ascend910b chip
  oneflow/core/common/device_type.proto
  oneflow/ir/lib/OneFlow/UserOpConversion.cpp
Labels: enhancement, system, breaking change

#10388 Update CMake cache files for new community builds
  .github/workflows/community_release.yml
  .github/workflows/priv_release.yml
  .github/workflows/release.yml
Labels: enhancement, ci

#10387 Cache global generator
  oneflow/core/framework/random_generator.cpp
  oneflow/core/framework/random_generator.h
  oneflow/user/kernels/random_seed_util.cpp
  python/oneflow/test/graph/test_graph_normal_inplace.py
Labels: enhancement, automerge, system

#10389 Fix community uploads
  .github/workflows/community_release.yml
  .github/workflows/release.yml
Labels: bug, ci

#10370 Dev support oneflow insight
  python/oneflow/utils/insight/README.md
  python/oneflow/utils/insight/requirements.txt
  python/oneflow/utils/insight/sqlite_to_google_trace_event.py
  python/oneflow/utils/insight/trace.json.png
Labels: enhancement, feature, eager
