Repository Oneflow-Inc/oneflow, pull requests merged in 2024-12, with the labels that each got.

#10569 CXX flags to make it less verbose in GitHub Action
  .github/workflows/simple.yml
  .github/workflows/test.yml
  cmake/caches/ci/release/cpu.cmake
  cmake/caches/ci/release/cu118.cmake
  cmake/caches/ci/release/cuda.cmake
Labels: enhancement, build

#10359 CI uses cuda118
  .github/workflows/canary.yml
  .github/workflows/on_merge.yml
  .github/workflows/release.yml
  .github/workflows/simple.yml
  .github/workflows/test.yml
  cmake/caches/ci/cuda.cmake
  cmake/third_party/flash_attention.cmake
  python/oneflow/test/modules/test_normal.py
Labels: enhancement, ci

#10606 Use cu118 in canary
  .github/workflows/canary.yml
Labels: enhancement, build

#10608 update error tol
  python/oneflow/test/modules/test_normal.py
  python/oneflow/test/modules/test_scaled_dot_product_attention.py
Labels: bug, ci

#10568 for compiling with cuda 12.x
  cmake/cuda.cmake
  cmake/third_party/FindCUDNN.cmake
Labels: enhancement, build

#10609 fix bug of group norm and layer norm for npu
  oneflow/user/ops/group_norm_op.cpp
  oneflow/user/ops/layer_norm_op.cpp
Labels: enhancement, automerge, op

#10563 fix device_type2sub_tsk_gph_builder_
  oneflow/core/graph/task_graph.cpp
Labels: bug, system, graph

#10611 Only release custom OneFlow once a week
  .github/workflows/community_release.yml
  .github/workflows/priv_release.yml
Labels: enhancement, ci

#10540 add support for xpu/KunLunXin device
  oneflow/core/common/device_type.proto
  oneflow/ir/lib/OneFlow/UserOpConversion.cpp
Labels: feature, system
