Repository Oneflow-Inc/oneflow, pull requests merged in 2024-01, with the labels that each got.

#10391 fix py38 and support python3.11
  cmake/pybind11.cmake
  oneflow/extension/stack/python/custom_eval_frame.c
  oneflow/extension/stack/python/stack_getter.cpp
Labels: enhancement, automerge, build, system, api

#10398 add cuda.mem_get_info (#82)
  oneflow/api/python/env/env.cpp
  python/oneflow/cuda/__init__.py
  python/oneflow/test/misc/test_env_cuda.py
Labels: enhancement, automerge, test, api, python

#10396 refine_mock_torch
  ci/test/test_mock_script.sh
  python/oneflow/mock_torch/__init__.py
  python/oneflow/mock_torch/__main__.py
  python/oneflow/mock_torch/dyn_mock_mod.py
  python/oneflow/mock_torch/mock_importer.py
  python/oneflow/mock_torch/mock_modules.py
  python/oneflow/mock_torch/mock_utils.py
Labels: enhancement, eager

#10400 Update default input of branch to main, in the community build
  .github/workflows/community_release.yml
Labels: bug, ci

#10399 Support is_grads_batched parameter for autograd.grad
  oneflow/api/python/autograd/autograd.cpp
  oneflow/core/common/shape.cpp
  oneflow/core/common/shape.h
  python/oneflow/autograd/autograd.py
  python/oneflow/test/modules/test_autograd.py
Labels: feature, automerge, system, api

#10402 Backport changes auto-install CUDA packages
  python/setup.py
Labels: enhancement, python

#10403 remove jit warning in __init__
  python/oneflow/jit/__init__.py
Labels: enhancement, automerge, documentation, api, python

#10406 Autograd.grad support out_grads with list of None
  oneflow/api/python/autograd/autograd.cpp
  python/oneflow/test/modules/test_autograd.py
Labels: automerge, bug, eager

#10407 Add proxy env in CI
  .github/workflows/community_release.yml
  .github/workflows/priv_release.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
Labels: enhancement, ci

#10408 re: transfer oneflow_compile from onediff to oneflow
  python/oneflow/framework/infer_compiler/__init__.py
  python/oneflow/framework/infer_compiler/import_tools/__init__.py
  python/oneflow/framework/infer_compiler/import_tools/format_utils.py
  python/oneflow/framework/infer_compiler/import_tools/importer.py
  python/oneflow/framework/infer_compiler/transform/__init__.py
  python/oneflow/framework/infer_compiler/transform/builtin_transform.py
  python/oneflow/framework/infer_compiler/transform/custom_transform.py
  python/oneflow/framework/infer_compiler/transform/manager.py
  python/oneflow/framework/infer_compiler/utils/__init__.py
  python/oneflow/framework/infer_compiler/utils/args_tree_util.py
  python/oneflow/framework/infer_compiler/utils/cost_util.py
  python/oneflow/framework/infer_compiler/utils/log_utils.py
  python/oneflow/framework/infer_compiler/utils/oneflow_exec_mode.py
  python/oneflow/framework/infer_compiler/utils/param_utils.py
  python/oneflow/framework/infer_compiler/utils/patch_for_compiler.py
  python/oneflow/framework/infer_compiler/utils/patch_for_diffusers.py
  python/oneflow/framework/infer_compiler/with_fx_graph.py
  python/oneflow/framework/infer_compiler/with_fx_interpreter.py
  python/oneflow/framework/infer_compiler/with_oneflow_compile.py
  python/oneflow/test/graph/test_oneflow_compiler.py
Labels: feature, automerge, python, graph

#10410 Change default value for ONEFLOW_MLIR_PREFER_NHWC
  python/oneflow/framework/infer_compiler/with_oneflow_compile.py
Labels: automerge, bug, system

#10411 refine add_n_op's error message
  oneflow/user/ops/add_n_op.cpp
Labels: enhancement, automerge, op

#10414 Fix bug when compiling faster_rcnn's backbone
  oneflow/core/job_rewriter/job_completer.cpp
  python/oneflow/nn/graph/graph.py
Labels: enhancement, system

#10415 Decrease default cuda architectures to build on cause the limitation of the host compiler.
  cmake/cuda.cmake
Labels: enhancement, automerge, system

#10412 Dev add jvp jacobian hessian
  docs/source/autograd.rst
  python/oneflow/autograd/__init__.py
  python/oneflow/autograd/functional.py
  python/oneflow/test/misc/test_autograd_functional.py
Labels: enhancement, eager, documentation, api

#10416 Fixed nightly version for pro, instead adding commit hash
  .github/workflows/release.yml
Labels: enhancement, ci

#10417 add functional group norm and dtype device param
  docs/source/nn.functional.rst
  python/oneflow/nn/functional/__init__.py
  python/oneflow/nn/modules/normalization.py
Labels: enhancement, automerge, documentation, api, python

#10422 Dump MLIR only in debug mode
  oneflow/ir/oneflow-translate/lib/OneFlow/MLIROneFlowTranslation.cpp
Labels: enhancement, automerge, system

#10423 change all_dynamic to dynamic
  python/oneflow/framework/infer_compiler/with_oneflow_compile.py
Labels: feature, python, graph
