Repository Oneflow-Inc/oneflow, pull requests merged in 2024-05, with the labels that each got.

#10495 flash_attention_v2_backward
  oneflow/core/autograd/gradient_funcs/scaled_dot_product_attention.cpp
  oneflow/core/functional/functional_api.yaml
  oneflow/core/functional/impl/nn_functor.cpp
  oneflow/ir/include/OneFlow/OneFlowUserOps.td
  oneflow/user/kernels/scaled_dot_product_attention_grad_kernel.cu
  oneflow/user/kernels/scaled_dot_product_attention_util.h
  oneflow/user/ops/scaled_dot_product_flash_attention_op.cpp
  python/oneflow/test/modules/test_scaled_dot_product_attention.py
  python/setup.py
Labels: enhancement, op

#10494 fix GroupNorm init
  python/oneflow/nn/modules/normalization.py
Labels: bug, op, python

#10496 add_npu_support for goup_norm
  python/oneflow/nn/modules/normalization.py
Labels: enhancement, op

#10527 fix_structseq_repr_error
  oneflow/api/python/functional/python_return_types.h
Labels: bug, eager, system

#10528 Update nigthly whl version
  README.md
  docs/source/environment_variables.rst
  tools/generate_pip_version.py
Labels: enhancement, automerge, build

#10533 fix fuse-bn-add-relu bug.
  oneflow/core/job_rewriter/cudnn_fused_normalization_add_relu_pass.cpp
Labels: enhancement, bug, graph
